import type { TutorBankItemV4 } from "@/lib/tutor-v4/types";

export const iaB1QuestionBank: TutorBankItemV4[] = [
  {
    kind: "fixed",
    id: "ia_b1_reperer_douteux_qcm_001",
    niveau: "b1",
    matiere: "ia",
    notionId: "ia_b1_verification",
    microId: "ia_b1_reperer_douteux",
    difficulty: 1,
    text: "Quelle affirmation valide la micro-comp?tence B1 : Je sais rep?rer une information douteuse ou invent?e.",
    format: "qcm",
    choices: ["Je sais rep?rer une information douteuse ou invent?e.","Je laisse l'IA d?cider ? ma place.","Je copie la r?ponse sans v?rifier."],
    expected: ["A"],
    comparator: "mcq_exact",
    hint: "Cherche la r?ponse qui garde m?thode, jugement et responsabilit? humaine.",
    explanation: "Bonne r?ponse : Je sais rep?rer une information douteuse ou invent?e.",
  },
  {
    kind: "fixed",
    id: "ia_b1_reperer_douteux_qcm_002",
    niveau: "b1",
    matiere: "ia",
    notionId: "ia_b1_verification",
    microId: "ia_b1_reperer_douteux",
    difficulty: 1,
    text: "Dans une situation r?elle, quelle action correspond le mieux ? : Je sais rep?rer une information douteuse ou invent?e.",
    format: "qcm",
    choices: ["Je sais rep?rer une information douteuse ou invent?e.","Partager des informations sensibles pour aller plus vite.","Faire confiance ? une seule r?ponse sans recul."],
    expected: ["A"],
    comparator: "mcq_exact",
    hint: "L'IA est un outil : l'?l?ve garde l'objectif, la v?rification et la d?cision.",
    explanation: "Cette micro-comp?tence se valide quand l'?l?ve sait faire ceci : Je sais rep?rer une information douteuse ou invent?e.",
  },
  {
    kind: "fixed",
    id: "ia_b1_sources_fiables_qcm_001",
    niveau: "b1",
    matiere: "ia",
    notionId: "ia_b1_verification",
    microId: "ia_b1_sources_fiables",
    difficulty: 1,
    text: "Quelle affirmation valide la micro-comp?tence B1 : Je sais v?rifier une information avec des sources fiables.",
    format: "qcm",
    choices: ["Je sais v?rifier une information avec des sources fiables.","Je laisse l'IA d?cider ? ma place.","Je copie la r?ponse sans v?rifier."],
    expected: ["A"],
    comparator: "mcq_exact",
    hint: "Cherche la r?ponse qui garde m?thode, jugement et responsabilit? humaine.",
    explanation: "Bonne r?ponse : Je sais v?rifier une information avec des sources fiables.",
  },
  {
    kind: "fixed",
    id: "ia_b1_sources_fiables_qcm_002",
    niveau: "b1",
    matiere: "ia",
    notionId: "ia_b1_verification",
    microId: "ia_b1_sources_fiables",
    difficulty: 1,
    text: "Dans une situation r?elle, quelle action correspond le mieux ? : Je sais v?rifier une information avec des sources fiables.",
    format: "qcm",
    choices: ["Je sais v?rifier une information avec des sources fiables.","Partager des informations sensibles pour aller plus vite.","Faire confiance ? une seule r?ponse sans recul."],
    expected: ["A"],
    comparator: "mcq_exact",
    hint: "L'IA est un outil : l'?l?ve garde l'objectif, la v?rification et la d?cision.",
    explanation: "Cette micro-comp?tence se valide quand l'?l?ve sait faire ceci : Je sais v?rifier une information avec des sources fiables.",
  },
  {
    kind: "fixed",
    id: "ia_b1_fait_opinion_hypothese_qcm_001",
    niveau: "b1",
    matiere: "ia",
    notionId: "ia_b1_verification",
    microId: "ia_b1_fait_opinion_hypothese",
    difficulty: 2,
    text: "Quelle affirmation valide la micro-comp?tence B1 : Je sais distinguer un fait, une opinion et une hypoth?se.",
    format: "qcm",
    choices: ["Je sais distinguer un fait, une opinion et une hypoth?se.","Je laisse l'IA d?cider ? ma place.","Je copie la r?ponse sans v?rifier."],
    expected: ["A"],
    comparator: "mcq_exact",
    hint: "Cherche la r?ponse qui garde m?thode, jugement et responsabilit? humaine.",
    explanation: "Bonne r?ponse : Je sais distinguer un fait, une opinion et une hypoth?se.",
  },
  {
    kind: "fixed",
    id: "ia_b1_fait_opinion_hypothese_qcm_002",
    niveau: "b1",
    matiere: "ia",
    notionId: "ia_b1_verification",
    microId: "ia_b1_fait_opinion_hypothese",
    difficulty: 2,
    text: "Dans une situation r?elle, quelle action correspond le mieux ? : Je sais distinguer un fait, une opinion et une hypoth?se.",
    format: "qcm",
    choices: ["Je sais distinguer un fait, une opinion et une hypoth?se.","Partager des informations sensibles pour aller plus vite.","Faire confiance ? une seule r?ponse sans recul."],
    expected: ["A"],
    comparator: "mcq_exact",
    hint: "L'IA est un outil : l'?l?ve garde l'objectif, la v?rification et la d?cision.",
    explanation: "Cette micro-comp?tence se valide quand l'?l?ve sait faire ceci : Je sais distinguer un fait, une opinion et une hypoth?se.",
  },
  {
    kind: "fixed",
    id: "ia_b1_donnees_personnelles_qcm_001",
    niveau: "b1",
    matiere: "ia",
    notionId: "ia_b1_securite",
    microId: "ia_b1_donnees_personnelles",
    difficulty: 2,
    text: "Quelle affirmation valide la micro-comp?tence B1 : Je sais ne pas partager de donn?es personnelles sensibles avec une IA.",
    format: "qcm",
    choices: ["Je sais ne pas partager de donn?es personnelles sensibles avec une IA.","Je laisse l'IA d?cider ? ma place.","Je copie la r?ponse sans v?rifier."],
    expected: ["A"],
    comparator: "mcq_exact",
    hint: "Cherche la r?ponse qui garde m?thode, jugement et responsabilit? humaine.",
    explanation: "Bonne r?ponse : Je sais ne pas partager de donn?es personnelles sensibles avec une IA.",
  },
  {
    kind: "fixed",
    id: "ia_b1_donnees_personnelles_qcm_002",
    niveau: "b1",
    matiere: "ia",
    notionId: "ia_b1_securite",
    microId: "ia_b1_donnees_personnelles",
    difficulty: 2,
    text: "Dans une situation r?elle, quelle action correspond le mieux ? : Je sais ne pas partager de donn?es personnelles sensibles avec une IA.",
    format: "qcm",
    choices: ["Je sais ne pas partager de donn?es personnelles sensibles avec une IA.","Partager des informations sensibles pour aller plus vite.","Faire confiance ? une seule r?ponse sans recul."],
    expected: ["A"],
    comparator: "mcq_exact",
    hint: "L'IA est un outil : l'?l?ve garde l'objectif, la v?rification et la d?cision.",
    explanation: "Cette micro-comp?tence se valide quand l'?l?ve sait faire ceci : Je sais ne pas partager de donn?es personnelles sensibles avec une IA.",
  },
  {
    kind: "fixed",
    id: "ia_b1_deepfake_arnaque_qcm_001",
    niveau: "b1",
    matiere: "ia",
    notionId: "ia_b1_securite",
    microId: "ia_b1_deepfake_arnaque",
    difficulty: 3,
    text: "Quelle affirmation valide la micro-comp?tence B1 : Je connais les risques de deepfakes, d'arnaques et de manipulation.",
    format: "qcm",
    choices: ["Je connais les risques de deepfakes, d'arnaques et de manipulation.","Je laisse l'IA d?cider ? ma place.","Je copie la r?ponse sans v?rifier."],
    expected: ["A"],
    comparator: "mcq_exact",
    hint: "Cherche la r?ponse qui garde m?thode, jugement et responsabilit? humaine.",
    explanation: "Bonne r?ponse : Je connais les risques de deepfakes, d'arnaques et de manipulation.",
  },
  {
    kind: "fixed",
    id: "ia_b1_deepfake_arnaque_qcm_002",
    niveau: "b1",
    matiere: "ia",
    notionId: "ia_b1_securite",
    microId: "ia_b1_deepfake_arnaque",
    difficulty: 3,
    text: "Dans une situation r?elle, quelle action correspond le mieux ? : Je connais les risques de deepfakes, d'arnaques et de manipulation.",
    format: "qcm",
    choices: ["Je connais les risques de deepfakes, d'arnaques et de manipulation.","Partager des informations sensibles pour aller plus vite.","Faire confiance ? une seule r?ponse sans recul."],
    expected: ["A"],
    comparator: "mcq_exact",
    hint: "L'IA est un outil : l'?l?ve garde l'objectif, la v?rification et la d?cision.",
    explanation: "Cette micro-comp?tence se valide quand l'?l?ve sait faire ceci : Je connais les risques de deepfakes, d'arnaques et de manipulation.",
  },
  {
    kind: "fixed",
    id: "ia_b1_plagiat_triche_qcm_001",
    niveau: "b1",
    matiere: "ia",
    notionId: "ia_b1_securite",
    microId: "ia_b1_plagiat_triche",
    difficulty: 3,
    text: "Quelle affirmation valide la micro-comp?tence B1 : Je sais distinguer aide autoris?e, aide limite, plagiat et triche.",
    format: "qcm",
    choices: ["Je sais distinguer aide autoris?e, aide limite, plagiat et triche.","Je laisse l'IA d?cider ? ma place.","Je copie la r?ponse sans v?rifier."],
    expected: ["A"],
    comparator: "mcq_exact",
    hint: "Cherche la r?ponse qui garde m?thode, jugement et responsabilit? humaine.",
    explanation: "Bonne r?ponse : Je sais distinguer aide autoris?e, aide limite, plagiat et triche.",
  },
  {
    kind: "fixed",
    id: "ia_b1_plagiat_triche_qcm_002",
    niveau: "b1",
    matiere: "ia",
    notionId: "ia_b1_securite",
    microId: "ia_b1_plagiat_triche",
    difficulty: 3,
    text: "Dans une situation r?elle, quelle action correspond le mieux ? : Je sais distinguer aide autoris?e, aide limite, plagiat et triche.",
    format: "qcm",
    choices: ["Je sais distinguer aide autoris?e, aide limite, plagiat et triche.","Partager des informations sensibles pour aller plus vite.","Faire confiance ? une seule r?ponse sans recul."],
    expected: ["A"],
    comparator: "mcq_exact",
    hint: "L'IA est un outil : l'?l?ve garde l'objectif, la v?rification et la d?cision.",
    explanation: "Cette micro-comp?tence se valide quand l'?l?ve sait faire ceci : Je sais distinguer aide autoris?e, aide limite, plagiat et triche.",
  },
];

export function getIaB1QuestionBank(args?: {
  notionId?: string | null;
  microId?: string | null;
}): TutorBankItemV4[] {
  let bank = iaB1QuestionBank;

  if (args?.notionId) bank = bank.filter((item) => item.notionId === args.notionId);
  if (args?.microId) bank = bank.filter((item) => item.microId === args.microId);

  return bank;
}
