import type { TutorBankItemV4 } from "@/lib/tutor-v4/types";

export const iaB1QuestionBank: TutorBankItemV4[] = [
  {
    kind: "fixed",
    id: "ia_b1_reperer_douteux_qcm_001",
    niveau: "b1",
    matiere: "ia",
    notionId: "ia_b1_verification",
    microId: "ia_b1_reperer_douteux",
    difficulty: 1,
    text: "Quelle affirmation valide la micro-competence B1 : Je sais reperer une information douteuse ou inventee.",
    format: "qcm",
    choices: ["Je sais reperer une information douteuse ou inventee.","Je laisse l'IA decider a ma place.","Je copie la reponse sans verifier."],
    expected: ["Je sais reperer une information douteuse ou inventee."],
    comparator: "mcq_exact",
    hint: "Cherche la reponse qui garde methode, jugement et responsabilite humaine.",
    explanation: "Bonne reponse : Je sais reperer une information douteuse ou inventee.",
  },
  {
    kind: "fixed",
    id: "ia_b1_reperer_douteux_qcm_002",
    niveau: "b1",
    matiere: "ia",
    notionId: "ia_b1_verification",
    microId: "ia_b1_reperer_douteux",
    difficulty: 1,
    text: "Dans une situation reelle, quelle action correspond le mieux a : Je sais reperer une information douteuse ou inventee.",
    format: "qcm",
    choices: ["Je sais reperer une information douteuse ou inventee.","Partager des informations sensibles pour aller plus vite.","Faire confiance a une seule reponse sans recul."],
    expected: ["Je sais reperer une information douteuse ou inventee."],
    comparator: "mcq_exact",
    hint: "L'IA est un outil : l'eleve garde l'objectif, la verification et la decision.",
    explanation: "Cette micro-competence se valide quand l'eleve sait faire ceci : Je sais reperer une information douteuse ou inventee.",
  },
  {
    kind: "fixed",
    id: "ia_b1_sources_fiables_qcm_001",
    niveau: "b1",
    matiere: "ia",
    notionId: "ia_b1_verification",
    microId: "ia_b1_sources_fiables",
    difficulty: 1,
    text: "Quelle affirmation valide la micro-competence B1 : Je sais verifier une information avec des sources fiables.",
    format: "qcm",
    choices: ["Je sais verifier une information avec des sources fiables.","Je laisse l'IA decider a ma place.","Je copie la reponse sans verifier."],
    expected: ["Je sais verifier une information avec des sources fiables."],
    comparator: "mcq_exact",
    hint: "Cherche la reponse qui garde methode, jugement et responsabilite humaine.",
    explanation: "Bonne reponse : Je sais verifier une information avec des sources fiables.",
  },
  {
    kind: "fixed",
    id: "ia_b1_sources_fiables_qcm_002",
    niveau: "b1",
    matiere: "ia",
    notionId: "ia_b1_verification",
    microId: "ia_b1_sources_fiables",
    difficulty: 1,
    text: "Dans une situation reelle, quelle action correspond le mieux a : Je sais verifier une information avec des sources fiables.",
    format: "qcm",
    choices: ["Je sais verifier une information avec des sources fiables.","Partager des informations sensibles pour aller plus vite.","Faire confiance a une seule reponse sans recul."],
    expected: ["Je sais verifier une information avec des sources fiables."],
    comparator: "mcq_exact",
    hint: "L'IA est un outil : l'eleve garde l'objectif, la verification et la decision.",
    explanation: "Cette micro-competence se valide quand l'eleve sait faire ceci : Je sais verifier une information avec des sources fiables.",
  },
  {
    kind: "fixed",
    id: "ia_b1_fait_opinion_hypothese_qcm_001",
    niveau: "b1",
    matiere: "ia",
    notionId: "ia_b1_verification",
    microId: "ia_b1_fait_opinion_hypothese",
    difficulty: 2,
    text: "Quelle affirmation valide la micro-competence B1 : Je sais distinguer un fait, une opinion et une hypothese.",
    format: "qcm",
    choices: ["Je sais distinguer un fait, une opinion et une hypothese.","Je laisse l'IA decider a ma place.","Je copie la reponse sans verifier."],
    expected: ["Je sais distinguer un fait, une opinion et une hypothese."],
    comparator: "mcq_exact",
    hint: "Cherche la reponse qui garde methode, jugement et responsabilite humaine.",
    explanation: "Bonne reponse : Je sais distinguer un fait, une opinion et une hypothese.",
  },
  {
    kind: "fixed",
    id: "ia_b1_fait_opinion_hypothese_qcm_002",
    niveau: "b1",
    matiere: "ia",
    notionId: "ia_b1_verification",
    microId: "ia_b1_fait_opinion_hypothese",
    difficulty: 2,
    text: "Dans une situation reelle, quelle action correspond le mieux a : Je sais distinguer un fait, une opinion et une hypothese.",
    format: "qcm",
    choices: ["Je sais distinguer un fait, une opinion et une hypothese.","Partager des informations sensibles pour aller plus vite.","Faire confiance a une seule reponse sans recul."],
    expected: ["Je sais distinguer un fait, une opinion et une hypothese."],
    comparator: "mcq_exact",
    hint: "L'IA est un outil : l'eleve garde l'objectif, la verification et la decision.",
    explanation: "Cette micro-competence se valide quand l'eleve sait faire ceci : Je sais distinguer un fait, une opinion et une hypothese.",
  },
  {
    kind: "fixed",
    id: "ia_b1_donnees_personnelles_qcm_001",
    niveau: "b1",
    matiere: "ia",
    notionId: "ia_b1_securite",
    microId: "ia_b1_donnees_personnelles",
    difficulty: 2,
    text: "Quelle affirmation valide la micro-competence B1 : Je sais ne pas partager de donnees personnelles sensibles avec une IA.",
    format: "qcm",
    choices: ["Je sais ne pas partager de donnees personnelles sensibles avec une IA.","Je laisse l'IA decider a ma place.","Je copie la reponse sans verifier."],
    expected: ["Je sais ne pas partager de donnees personnelles sensibles avec une IA."],
    comparator: "mcq_exact",
    hint: "Cherche la reponse qui garde methode, jugement et responsabilite humaine.",
    explanation: "Bonne reponse : Je sais ne pas partager de donnees personnelles sensibles avec une IA.",
  },
  {
    kind: "fixed",
    id: "ia_b1_donnees_personnelles_qcm_002",
    niveau: "b1",
    matiere: "ia",
    notionId: "ia_b1_securite",
    microId: "ia_b1_donnees_personnelles",
    difficulty: 2,
    text: "Dans une situation reelle, quelle action correspond le mieux a : Je sais ne pas partager de donnees personnelles sensibles avec une IA.",
    format: "qcm",
    choices: ["Je sais ne pas partager de donnees personnelles sensibles avec une IA.","Partager des informations sensibles pour aller plus vite.","Faire confiance a une seule reponse sans recul."],
    expected: ["Je sais ne pas partager de donnees personnelles sensibles avec une IA."],
    comparator: "mcq_exact",
    hint: "L'IA est un outil : l'eleve garde l'objectif, la verification et la decision.",
    explanation: "Cette micro-competence se valide quand l'eleve sait faire ceci : Je sais ne pas partager de donnees personnelles sensibles avec une IA.",
  },
  {
    kind: "fixed",
    id: "ia_b1_deepfake_arnaque_qcm_001",
    niveau: "b1",
    matiere: "ia",
    notionId: "ia_b1_securite",
    microId: "ia_b1_deepfake_arnaque",
    difficulty: 3,
    text: "Quelle affirmation valide la micro-competence B1 : Je connais les risques de deepfakes, d'arnaques et de manipulation.",
    format: "qcm",
    choices: ["Je connais les risques de deepfakes, d'arnaques et de manipulation.","Je laisse l'IA decider a ma place.","Je copie la reponse sans verifier."],
    expected: ["Je connais les risques de deepfakes, d'arnaques et de manipulation."],
    comparator: "mcq_exact",
    hint: "Cherche la reponse qui garde methode, jugement et responsabilite humaine.",
    explanation: "Bonne reponse : Je connais les risques de deepfakes, d'arnaques et de manipulation.",
  },
  {
    kind: "fixed",
    id: "ia_b1_deepfake_arnaque_qcm_002",
    niveau: "b1",
    matiere: "ia",
    notionId: "ia_b1_securite",
    microId: "ia_b1_deepfake_arnaque",
    difficulty: 3,
    text: "Dans une situation reelle, quelle action correspond le mieux a : Je connais les risques de deepfakes, d'arnaques et de manipulation.",
    format: "qcm",
    choices: ["Je connais les risques de deepfakes, d'arnaques et de manipulation.","Partager des informations sensibles pour aller plus vite.","Faire confiance a une seule reponse sans recul."],
    expected: ["Je connais les risques de deepfakes, d'arnaques et de manipulation."],
    comparator: "mcq_exact",
    hint: "L'IA est un outil : l'eleve garde l'objectif, la verification et la decision.",
    explanation: "Cette micro-competence se valide quand l'eleve sait faire ceci : Je connais les risques de deepfakes, d'arnaques et de manipulation.",
  },
  {
    kind: "fixed",
    id: "ia_b1_plagiat_triche_qcm_001",
    niveau: "b1",
    matiere: "ia",
    notionId: "ia_b1_securite",
    microId: "ia_b1_plagiat_triche",
    difficulty: 3,
    text: "Quelle affirmation valide la micro-competence B1 : Je sais distinguer aide autorisee, aide limite, plagiat et triche.",
    format: "qcm",
    choices: ["Je sais distinguer aide autorisee, aide limite, plagiat et triche.","Je laisse l'IA decider a ma place.","Je copie la reponse sans verifier."],
    expected: ["Je sais distinguer aide autorisee, aide limite, plagiat et triche."],
    comparator: "mcq_exact",
    hint: "Cherche la reponse qui garde methode, jugement et responsabilite humaine.",
    explanation: "Bonne reponse : Je sais distinguer aide autorisee, aide limite, plagiat et triche.",
  },
  {
    kind: "fixed",
    id: "ia_b1_plagiat_triche_qcm_002",
    niveau: "b1",
    matiere: "ia",
    notionId: "ia_b1_securite",
    microId: "ia_b1_plagiat_triche",
    difficulty: 3,
    text: "Dans une situation reelle, quelle action correspond le mieux a : Je sais distinguer aide autorisee, aide limite, plagiat et triche.",
    format: "qcm",
    choices: ["Je sais distinguer aide autorisee, aide limite, plagiat et triche.","Partager des informations sensibles pour aller plus vite.","Faire confiance a une seule reponse sans recul."],
    expected: ["Je sais distinguer aide autorisee, aide limite, plagiat et triche."],
    comparator: "mcq_exact",
    hint: "L'IA est un outil : l'eleve garde l'objectif, la verification et la decision.",
    explanation: "Cette micro-competence se valide quand l'eleve sait faire ceci : Je sais distinguer aide autorisee, aide limite, plagiat et triche.",
  },
];

export function getIaB1QuestionBank(args?: {
  notionId?: string | null;
  microId?: string | null;
}): TutorBankItemV4[] {
  let bank = iaB1QuestionBank;

  if (args?.notionId) bank = bank.filter((item) => item.notionId === args.notionId);
  if (args?.microId) bank = bank.filter((item) => item.microId === args.microId);

  return bank;
}
