// Micro-compétences de mathématiques pour la classe de CM2.

import type { MicroSkillSource } from "@/lib/tutor-v4/knowledge/buildKnowledge";

export const microSkills: MicroSkillSource[] = [
  {
    id: "lire_ecrire_nombres",
    label: "Lire et écrire des nombres",
    notionId: "nombres_entiers",
    prerequis: [],
  },
  {
    id: "comparer_nombres",
    label: "Comparer des nombres",
    notionId: "nombres_entiers",
    prerequis: ["lire_ecrire_nombres"],
  },
  {
    id: "decomposer_nombres",
    label: "Décomposer des nombres",
    notionId: "nombres_entiers",
    prerequis: ["lire_ecrire_nombres"],
  },
  {
    id: "calculer_mentalement",
    label: "Calculer mentalement",
    notionId: "calcul_mental",
    prerequis: ["lire_ecrire_nombres"],
  },
  {
    id: "addition_posee",
    label: "Poser une addition",
    notionId: "calcul_pose",
    prerequis: ["calculer_mentalement"],
  },
  {
    id: "soustraction_posee",
    label: "Poser une soustraction",
    notionId: "calcul_pose",
    prerequis: ["addition_posee"],
  },
  {
    id: "multiplication_posee",
    label: "Poser une multiplication",
    notionId: "calcul_pose",
    prerequis: ["calculer_mentalement"],
  },
  {
    id: "division_posee",
    label: "Poser une division simple",
    notionId: "calcul_pose",
    prerequis: ["multiplication_posee"],
  },
  {
    id: "resoudre_probleme",
    label: "Résoudre un problème arithmétique",
    notionId: "problemes_arithmetiques",
    prerequis: ["addition_posee", "soustraction_posee", "multiplication_posee"],
  },
  {
    id: "problemes_defis",
    label: "Défis de problèmes arithmétiques",
    notionId: "problemes_arithmetiques",
    prerequis: ["resoudre_probleme"],
  },
  {
    id: "fraction_lire",
    label: "Lire une fraction",
    notionId: "fractions",
    prerequis: ["lire_ecrire_nombres"],
  },
  {
    id: "fraction_representer",
    label: "Représenter une fraction",
    notionId: "fractions",
    prerequis: ["fraction_lire"],
  },
  {
    id: "decimal_lire",
    label: "Lire un nombre décimal",
    notionId: "nombres_decimaux",
    prerequis: ["fraction_lire"],
  },
  {
    id: "decimal_comparer",
    label: "Comparer des nombres décimaux",
    notionId: "nombres_decimaux",
    prerequis: ["decimal_lire", "comparer_nombres"],
  },
  {
    id: "comprendre_egalite",
    label: "Comprendre une égalité",
    notionId: "egalites",
    prerequis: ["calculer_mentalement"],
  },
  {
    id: "completer_egalite",
    label: "Compléter une égalité",
    notionId: "egalites",
    prerequis: ["comprendre_egalite"],
  },
  {
    id: "utiliser_schema_barre",
    label: "Utiliser un schéma en barres",
    notionId: "schemas_barres",
    prerequis: ["comprendre_egalite"],
  },
  {
    id: "reconnaitre_motif",
    label: "Reconnaître un motif",
    notionId: "motifs_evolutifs",
    prerequis: ["comprendre_egalite"],
  },
  {
    id: "suites_evolutives",
    label: "Poursuivre une suite évolutive",
    notionId: "motifs_evolutifs",
    prerequis: ["reconnaitre_motif"],
  },
  {
    id: "algorithmes_simples",
    label: "Décrire un algorithme simple",
    notionId: "motifs_evolutifs",
    prerequis: ["suites_evolutives"],
  },
  {
    id: "nombre_inconnu_simple",
    label: "Trouver un nombre inconnu",
    notionId: "nombres_inconnus",
    prerequis: ["completer_egalite", "utiliser_schema_barre"],
  },
  {
    id: "algebra_defis",
    label: "Défis de pensée algébrique",
    notionId: "nombres_inconnus",
    prerequis: ["nombre_inconnu_simple", "suites_evolutives"],
  },
  {
    id: "lire_tableau",
    label: "Lire un tableau",
    notionId: "tableaux",
    prerequis: [],
  },
  {
    id: "completer_tableau_donnees",
    label: "Compléter un tableau de données",
    notionId: "tableaux",
    prerequis: ["lire_tableau"],
  },
  {
    id: "lire_graphique",
    label: "Lire un graphique",
    notionId: "graphiques",
    prerequis: ["lire_tableau"],
  },
  {
    id: "construire_graphique",
    label: "Construire un graphique simple",
    notionId: "graphiques",
    prerequis: ["lire_graphique"],
  },
  {
    id: "lire_diagramme",
    label: "Lire un diagramme",
    notionId: "diagrammes",
    prerequis: ["lire_tableau"],
  },
  {
    id: "interpreter_donnees",
    label: "Interpréter des données",
    notionId: "diagrammes",
    prerequis: ["lire_graphique", "lire_diagramme"],
  },
  {
    id: "donnees_defis",
    label: "Défis sur les données",
    notionId: "diagrammes",
    prerequis: ["interpreter_donnees"],
  },
  {
    id: "reconnaitre_hasard",
    label: "Reconnaître une situation de hasard",
    notionId: "hasard",
    prerequis: ["lire_tableau"],
  },
  {
    id: "experiences_aleatoires",
    label: "Décrire une expérience aléatoire",
    notionId: "hasard",
    prerequis: ["reconnaitre_hasard"],
  },
  {
    id: "situations_equiprobables",
    label: "Reconnaître des issues équiprobables",
    notionId: "probabilites_simples",
    prerequis: ["experiences_aleatoires"],
  },
  {
    id: "comparer_probabilites",
    label: "Comparer des probabilités simples",
    notionId: "probabilites_simples",
    prerequis: ["situations_equiprobables"],
  },
  {
    id: "probabilites_defis",
    label: "Défis de probabilités",
    notionId: "probabilites_simples",
    prerequis: ["comparer_probabilites"],
  },
  {
    id: "verifier_alignement",
    label: "Vérifier un alignement",
    notionId: "alignement",
    prerequis: [],
  },
  {
    id: "reconnaitre_angle",
    label: "Reconnaître un angle",
    notionId: "angles",
    prerequis: ["verifier_alignement"],
  },
  {
    id: "mesurer_angle",
    label: "Mesurer un angle",
    notionId: "angles",
    prerequis: ["reconnaitre_angle"],
  },
  {
    id: "tracer_triangle",
    label: "Tracer un triangle",
    notionId: "triangles",
    prerequis: ["mesurer_angle"],
  },
  {
    id: "reconnaitre_quadrilatere",
    label: "Reconnaître un quadrilatère",
    notionId: "quadrilateres",
    prerequis: ["reconnaitre_angle"],
  },
  {
    id: "tracer_cercle",
    label: "Tracer un cercle",
    notionId: "cercle",
    prerequis: ["verifier_alignement"],
  },
  {
    id: "symetrie_axiale",
    label: "Utiliser la symétrie axiale",
    notionId: "symetrie",
    prerequis: ["verifier_alignement"],
  },
  {
    id: "reconnaitre_solide",
    label: "Reconnaître un solide",
    notionId: "solides",
    prerequis: ["reconnaitre_quadrilatere"],
  },
  {
    id: "patrons_simples",
    label: "Reconnaître un patron simple",
    notionId: "solides",
    prerequis: ["reconnaitre_solide"],
  },
  {
    id: "se_reperer_espace",
    label: "Se repérer dans l’espace",
    notionId: "reperage_espace",
    prerequis: ["verifier_alignement"],
  },
  {
    id: "geometrie_defis",
    label: "Défis de géométrie",
    notionId: "reperage_espace",
    prerequis: ["tracer_triangle", "reconnaitre_quadrilatere", "symetrie_axiale"],
  },
  {
    id: "convertir_longueurs",
    label: "Convertir des longueurs",
    notionId: "longueurs",
    prerequis: [],
  },
  {
    id: "convertir_masses",
    label: "Convertir des masses",
    notionId: "masses",
    prerequis: [],
  },
  {
    id: "convertir_contenances",
    label: "Convertir des contenances",
    notionId: "contenances",
    prerequis: [],
  },
  {
    id: "mesurer_duree",
    label: "Mesurer une durée",
    notionId: "durees",
    prerequis: [],
  },
  {
    id: "calculer_perimetre",
    label: "Calculer un périmètre",
    notionId: "perimetres",
    prerequis: ["convertir_longueurs"],
  },
  {
    id: "calculer_aire_rectangle",
    label: "Calculer l’aire d’un rectangle",
    notionId: "aires",
    prerequis: ["convertir_longueurs"],
  },
  {
    id: "comparer_volumes",
    label: "Comparer des volumes",
    notionId: "volumes",
    prerequis: ["convertir_contenances"],
  },
  {
    id: "grandeurs_defis",
    label: "Défis de grandeurs et mesures",
    notionId: "volumes",
    prerequis: ["calculer_perimetre", "calculer_aire_rectangle", "comparer_volumes"],
  },
  {
    id: "reconnaitre_proportionnalite",
    label: "Reconnaître une proportionnalité",
    notionId: "proportionnalite_reconnaitre",
    prerequis: ["comparer_nombres"],
  },
  {
    id: "completer_tableau",
    label: "Compléter un tableau de proportionnalité",
    notionId: "tableaux_proportionnalite",
    prerequis: ["reconnaitre_proportionnalite", "calculer_mentalement"],
  },
  {
    id: "calculer_quatrieme",
    label: "Calculer une quatrième proportionnelle",
    notionId: "quatrieme_proportionnelle",
    prerequis: ["completer_tableau"],
  },
  {
    id: "utiliser_pourcentage_simple",
    label: "Utiliser un pourcentage simple",
    notionId: "pourcentages_simples",
    prerequis: ["fraction_lire", "completer_tableau"],
  },
  {
    id: "utiliser_echelle",
    label: "Utiliser une échelle simple",
    notionId: "echelles_simples",
    prerequis: ["completer_tableau", "convertir_longueurs"],
  },
  {
    id: "proportionnalite_defis",
    label: "Défis de proportionnalité",
    notionId: "defis_proportionnalite",
    prerequis: ["calculer_quatrieme", "utiliser_pourcentage_simple", "utiliser_echelle"],
  },
  {
    id: "suivre_instruction",
    label: "Suivre une instruction",
    notionId: "suites_instructions",
    prerequis: [],
  },
  {
    id: "coder_deplacement",
    label: "Coder un déplacement",
    notionId: "deplacements_quadrillage",
    prerequis: ["suivre_instruction", "se_reperer_espace"],
  },
  {
    id: "reproduire_programme",
    label: "Reproduire un programme simple",
    notionId: "programmation_simple",
    prerequis: ["coder_deplacement"],
  },
  {
    id: "suites_algorithmiques",
    label: "Poursuivre une suite algorithmique",
    notionId: "logique",
    prerequis: ["suivre_instruction"],
  },
  {
    id: "repetition_simple",
    label: "Utiliser une répétition simple",
    notionId: "programmation_simple",
    prerequis: ["reproduire_programme", "suites_algorithmiques"],
  },
  {
    id: "informatique_defis",
    label: "Défis de pensée informatique",
    notionId: "programmation_simple",
    prerequis: ["repetition_simple"],
  },
];
