-- LES MICRO-COMPÉTENCES DE LA CLASSE DE DÉMONSTRATION.
--
-- POURQUOI UN SECOND SCRIPT (11/08/2026). Le peuplement initial écrivait
-- `details.micros = []` : la synthèse « compétence par compétence » — la
-- colonne de gauche de la restitution officielle, celle que M. Pelka a
-- envoyée en exemple — n'avait donc rien à agréger et ne s'affichait pas.
--
-- Les micro-compétences ci-dessous ne sont pas inventées : elles sont tirées
-- du knowledge CM2 réel, les mêmes que celles que l'épreuve pose. Les
-- réussites suivent le profil de chaque élève (les trois premiers réussissent
-- ~80 %, le milieu ~45 %, les derniers ~20 %), et le tirage est DÉTERMINISTE :
-- rejouer ce script redonne exactement les mêmes lignes.
--
-- ⛔ Ces lignes partent avec le reste — voir demo_6e_dimitile_effacer.sql.

update public.resultats_evaluation_nationale
set details = jsonb_set(details, '{micros}', '[{"microId":"figure_reconnaitre","microLabel":"Reconnaître une figure plane","notionId":"","notionLabel":"Figures planes","reussi":false},{"microId":"figure_construire","microLabel":"Construire une figure plane simple","notionId":"","notionLabel":"Figures planes","reussi":false},{"microId":"reperage_coordonnees","microLabel":"Lire les coordonnées d’un point","notionId":"","notionLabel":"Repérage","reussi":true},{"microId":"solide_reconnaitre","microLabel":"Reconnaître les solides usuels","notionId":"","notionLabel":"Solides","reussi":true},{"microId":"algo_logique","microLabel":"Compléter une suite logique","notionId":"","notionLabel":"Algorithmique","reussi":false},{"microId":"perimetre_defi","microLabel":"Résoudre un défi de périmètre","notionId":"","notionLabel":"Périmètres","reussi":true},{"microId":"masse_estimer","microLabel":"Estimer une masse","notionId":"","notionLabel":"Masses","reussi":true},{"microId":"angle_droit","microLabel":"Reconnaître un angle droit","notionId":"","notionLabel":"Angles","reussi":true},{"microId":"angle_reconnaitre","microLabel":"Reconnaître un angle","notionId":"","notionLabel":"Angles","reussi":true},{"microId":"longueur_estimer","microLabel":"Estimer une longueur","notionId":"","notionLabel":"Longueurs","reussi":true},{"microId":"perimetre_quadrilatere","microLabel":"Calculer le périmètre d’un quadrilatère","notionId":"","notionLabel":"Périmètres","reussi":true},{"microId":"algebre_relation","microLabel":"Décrire une relation entre deux quantités","notionId":"","notionLabel":"Algèbre","reussi":true},{"microId":"entier_lire","microLabel":"Lire et écrire des nombres entiers","notionId":"","notionLabel":"Nombres entiers","reussi":false},{"microId":"multiplication_posee","microLabel":"Poser une multiplication","notionId":"","notionLabel":"Multiplication","reussi":true},{"microId":"division_sens","microLabel":"Comprendre le sens de la division","notionId":"","notionLabel":"Division","reussi":true},{"microId":"multiplication_mental","microLabel":"Multiplier mentalement","notionId":"","notionLabel":"Multiplication","reussi":true},{"microId":"entier_comparer","microLabel":"Comparer et ordonner des nombres entiers","notionId":"","notionLabel":"Nombres entiers","reussi":true},{"microId":"fraction_lire","microLabel":"Lire une fraction","notionId":"","notionLabel":"Fractions","reussi":false},{"microId":"decimal_comparer","microLabel":"Comparer des nombres décimaux","notionId":"","notionLabel":"Nombres décimaux","reussi":true},{"microId":"fraction_droite","microLabel":"Placer une fraction sur une droite graduée","notionId":"","notionLabel":"Fractions","reussi":false}]'::jsonb)
where code_etablissement = 'DIMITILE' and code_utilisateur = '6ETEST-01'
  and classe = '6e' and matiere = 'maths';

update public.resultats_evaluation_nationale
set details = jsonb_set(details, '{micros}', '[{"microId":"symetrie_axe","microLabel":"Reconnaître un axe de symétrie","notionId":"","notionLabel":"Symétrie","reussi":true},{"microId":"droite_perpendiculaire","microLabel":"Reconnaître des droites perpendiculaires","notionId":"","notionLabel":"Droites","reussi":true},{"microId":"symetrie_completer","microLabel":"Compléter une figure par symétrie","notionId":"","notionLabel":"Symétrie","reussi":false},{"microId":"reperage_deplacement","microLabel":"Décrire un déplacement sur quadrillage","notionId":"","notionLabel":"Repérage","reussi":true},{"microId":"figure_quadrilatere","microLabel":"Reconnaître les quadrilatères","notionId":"","notionLabel":"Figures planes","reussi":false},{"microId":"longueur_comparer","microLabel":"Comparer des longueurs","notionId":"","notionLabel":"Longueurs","reussi":false},{"microId":"longueur_estimer","microLabel":"Estimer une longueur","notionId":"","notionLabel":"Longueurs","reussi":true},{"microId":"duree_convertir","microLabel":"Convertir des durées","notionId":"","notionLabel":"Durées","reussi":true},{"microId":"echelle_distance_reelle","microLabel":"Calculer une distance réelle avec une échelle","notionId":"","notionLabel":"Échelles simples","reussi":true},{"microId":"masse_defi","microLabel":"Résoudre un défi de masses","notionId":"","notionLabel":"Masses","reussi":true},{"microId":"masse_convertir","microLabel":"Convertir des masses","notionId":"","notionLabel":"Masses","reussi":true},{"microId":"pourcentage_defi","microLabel":"Résoudre un défi de pourcentage","notionId":"","notionLabel":"Pourcentages simples","reussi":true},{"microId":"decimal_lire","microLabel":"Lire et écrire un nombre décimal","notionId":"","notionLabel":"Nombres décimaux","reussi":true},{"microId":"suite_regle","microLabel":"Trouver la règle d’une suite","notionId":"","notionLabel":"Suites de nombres","reussi":true},{"microId":"entier_arrondir","microLabel":"Arrondir un nombre entier","notionId":"","notionLabel":"Nombres entiers","reussi":true},{"microId":"entier_defi","microLabel":"Résoudre un défi sur les nombres entiers","notionId":"","notionLabel":"Nombres entiers","reussi":true},{"microId":"fraction_lire","microLabel":"Lire une fraction","notionId":"","notionLabel":"Fractions","reussi":true},{"microId":"suite_defi","microLabel":"Résoudre un défi sur les suites","notionId":"","notionLabel":"Suites de nombres","reussi":true},{"microId":"fraction_equivalente","microLabel":"Reconnaître des fractions équivalentes","notionId":"","notionLabel":"Fractions","reussi":false},{"microId":"division_reste","microLabel":"Interpréter le reste d’une division","notionId":"","notionLabel":"Division","reussi":false}]'::jsonb)
where code_etablissement = 'DIMITILE' and code_utilisateur = '6ETEST-02'
  and classe = '6e' and matiere = 'maths';

update public.resultats_evaluation_nationale
set details = jsonb_set(details, '{micros}', '[{"microId":"reperage_quadrillage","microLabel":"Se repérer sur un quadrillage","notionId":"","notionLabel":"Repérage","reussi":true},{"microId":"algo_deplacement","microLabel":"Coder un déplacement sur quadrillage","notionId":"","notionLabel":"Algorithmique","reussi":true},{"microId":"symetrie_propriete","microLabel":"Utiliser les propriétés de la symétrie","notionId":"","notionLabel":"Symétrie","reussi":true},{"microId":"symetrie_defi","microLabel":"Résoudre un défi de symétrie","notionId":"","notionLabel":"Symétrie","reussi":true},{"microId":"algo_repetition","microLabel":"Utiliser une répétition simple","notionId":"","notionLabel":"Algorithmique","reussi":false},{"microId":"longueur_comparer","microLabel":"Comparer des longueurs","notionId":"","notionLabel":"Longueurs","reussi":false},{"microId":"duree_lire","microLabel":"Lire une heure ou une durée","notionId":"","notionLabel":"Durées","reussi":true},{"microId":"angle_reconnaitre","microLabel":"Reconnaître un angle","notionId":"","notionLabel":"Angles","reussi":true},{"microId":"echelle_defi","microLabel":"Résoudre un défi d’échelle","notionId":"","notionLabel":"Échelles simples","reussi":true},{"microId":"perimetre_comprendre","microLabel":"Comprendre ce qu’est un périmètre","notionId":"","notionLabel":"Périmètres","reussi":false},{"microId":"longueur_convertir","microLabel":"Convertir des longueurs","notionId":"","notionLabel":"Longueurs","reussi":false},{"microId":"prop_probleme","microLabel":"Résoudre un problème de proportionnalité","notionId":"","notionLabel":"Proportionnalité","reussi":true},{"microId":"calcul_decimal_addition","microLabel":"Additionner des nombres décimaux","notionId":"","notionLabel":"Calculs","reussi":false},{"microId":"calcul_addition_posee","microLabel":"Poser une addition","notionId":"","notionLabel":"Calculs","reussi":true},{"microId":"algebre_egalite","microLabel":"Comprendre une égalité","notionId":"","notionLabel":"Algèbre","reussi":true},{"microId":"algebre_defi","microLabel":"Résoudre un défi d’algèbre","notionId":"","notionLabel":"Algèbre","reussi":true},{"microId":"tableau_defi","microLabel":"Résoudre un défi avec un tableau","notionId":"","notionLabel":"Tableaux","reussi":true},{"microId":"algebre_completer_egalite","microLabel":"Compléter une égalité","notionId":"","notionLabel":"Algèbre","reussi":true},{"microId":"prop_coefficient","microLabel":"Utiliser un coefficient de proportionnalité","notionId":"","notionLabel":"Proportionnalité","reussi":false},{"microId":"prop_quatrieme","microLabel":"Calculer une quatrième proportionnelle","notionId":"","notionLabel":"Proportionnalité","reussi":true}]'::jsonb)
where code_etablissement = 'DIMITILE' and code_utilisateur = '6ETEST-03'
  and classe = '6e' and matiere = 'maths';

update public.resultats_evaluation_nationale
set details = jsonb_set(details, '{micros}', '[{"microId":"reperage_defi","microLabel":"Résoudre un défi de repérage","notionId":"","notionLabel":"Repérage","reussi":false},{"microId":"figure_construire","microLabel":"Construire une figure plane simple","notionId":"","notionLabel":"Figures planes","reussi":false},{"microId":"solide_patron","microLabel":"Reconnaître un patron de solide","notionId":"","notionLabel":"Solides","reussi":true},{"microId":"algo_instruction","microLabel":"Suivre une suite d’instructions","notionId":"","notionLabel":"Algorithmique","reussi":true},{"microId":"figure_defi","microLabel":"Résoudre un défi sur les figures planes","notionId":"","notionLabel":"Figures planes","reussi":false},{"microId":"echelle_distance_plan","microLabel":"Calculer une distance sur un plan avec une échelle","notionId":"","notionLabel":"Échelles simples","reussi":true},{"microId":"perimetre_defi","microLabel":"Résoudre un défi de périmètre","notionId":"","notionLabel":"Périmètres","reussi":false},{"microId":"echelle_distance_reelle","microLabel":"Calculer une distance réelle avec une échelle","notionId":"","notionLabel":"Échelles simples","reussi":false},{"microId":"perimetre_polygone","microLabel":"Calculer le périmètre d’un polygone","notionId":"","notionLabel":"Périmètres","reussi":false},{"microId":"perimetre_comprendre","microLabel":"Comprendre ce qu’est un périmètre","notionId":"","notionLabel":"Périmètres","reussi":false},{"microId":"duree_probleme","microLabel":"Résoudre un problème de durées","notionId":"","notionLabel":"Durées","reussi":false},{"microId":"entier_multiple","microLabel":"Reconnaître les multiples d’un nombre","notionId":"","notionLabel":"Nombres entiers","reussi":true},{"microId":"suite_regle","microLabel":"Trouver la règle d’une suite","notionId":"","notionLabel":"Suites de nombres","reussi":true},{"microId":"suite_croissante_decroissante","microLabel":"Reconnaître une suite croissante ou décroissante","notionId":"","notionLabel":"Suites de nombres","reussi":false},{"microId":"decimal_valeur_chiffre","microLabel":"Donner la valeur d’un chiffre dans un nombre décimal","notionId":"","notionLabel":"Nombres décimaux","reussi":false},{"microId":"calcul_soustraction_posee","microLabel":"Poser une soustraction","notionId":"","notionLabel":"Calculs","reussi":false},{"microId":"entier_arrondir","microLabel":"Arrondir un nombre entier","notionId":"","notionLabel":"Nombres entiers","reussi":false},{"microId":"decimal_comparer","microLabel":"Comparer des nombres décimaux","notionId":"","notionLabel":"Nombres décimaux","reussi":false},{"microId":"division_posee","microLabel":"Poser une division simple","notionId":"","notionLabel":"Division","reussi":false},{"microId":"entier_decomposer","microLabel":"Décomposer des nombres entiers","notionId":"","notionLabel":"Nombres entiers","reussi":true}]'::jsonb)
where code_etablissement = 'DIMITILE' and code_utilisateur = '6ETEST-04'
  and classe = '6e' and matiere = 'maths';

update public.resultats_evaluation_nationale
set details = jsonb_set(details, '{micros}', '[{"microId":"reperage_quadrillage","microLabel":"Se repérer sur un quadrillage","notionId":"","notionLabel":"Repérage","reussi":false},{"microId":"figure_cercle","microLabel":"Reconnaître et utiliser le cercle","notionId":"","notionLabel":"Figures planes","reussi":true},{"microId":"reperage_coordonnees","microLabel":"Lire les coordonnées d’un point","notionId":"","notionLabel":"Repérage","reussi":true},{"microId":"solide_sommet_arete_face","microLabel":"Identifier sommets, arêtes et faces","notionId":"","notionLabel":"Solides","reussi":false},{"microId":"algo_logique","microLabel":"Compléter une suite logique","notionId":"","notionLabel":"Algorithmique","reussi":true},{"microId":"echelle_comprendre","microLabel":"Comprendre une échelle simple","notionId":"","notionLabel":"Échelles simples","reussi":false},{"microId":"perimetre_polygone","microLabel":"Calculer le périmètre d’un polygone","notionId":"","notionLabel":"Périmètres","reussi":false},{"microId":"contenance_defi","microLabel":"Résoudre un défi de contenances","notionId":"","notionLabel":"Contenances","reussi":false},{"microId":"perimetre_quadrilatere","microLabel":"Calculer le périmètre d’un quadrilatère","notionId":"","notionLabel":"Périmètres","reussi":false},{"microId":"longueur_estimer","microLabel":"Estimer une longueur","notionId":"","notionLabel":"Longueurs","reussi":false},{"microId":"masse_defi","microLabel":"Résoudre un défi de masses","notionId":"","notionLabel":"Masses","reussi":true},{"microId":"division_lien_multiplication","microLabel":"Associer multiplication et division","notionId":"","notionLabel":"Division","reussi":false},{"microId":"calcul_priorite","microLabel":"Utiliser les priorités opératoires simples","notionId":"","notionLabel":"Calculs","reussi":false},{"microId":"entier_lire","microLabel":"Lire et écrire des nombres entiers","notionId":"","notionLabel":"Nombres entiers","reussi":false},{"microId":"entier_comparer","microLabel":"Comparer et ordonner des nombres entiers","notionId":"","notionLabel":"Nombres entiers","reussi":false},{"microId":"multiplication_mental","microLabel":"Multiplier mentalement","notionId":"","notionLabel":"Multiplication","reussi":false},{"microId":"division_sens","microLabel":"Comprendre le sens de la division","notionId":"","notionLabel":"Division","reussi":false},{"microId":"suite_defi","microLabel":"Résoudre un défi sur les suites","notionId":"","notionLabel":"Suites de nombres","reussi":false},{"microId":"decimal_fraction","microLabel":"Relier fraction décimale et nombre décimal","notionId":"","notionLabel":"Nombres décimaux","reussi":false},{"microId":"entier_defi","microLabel":"Résoudre un défi sur les nombres entiers","notionId":"","notionLabel":"Nombres entiers","reussi":true}]'::jsonb)
where code_etablissement = 'DIMITILE' and code_utilisateur = '6ETEST-05'
  and classe = '6e' and matiere = 'maths';

update public.resultats_evaluation_nationale
set details = jsonb_set(details, '{micros}', '[{"microId":"symetrie_axe","microLabel":"Reconnaître un axe de symétrie","notionId":"","notionLabel":"Symétrie","reussi":true},{"microId":"droite_reconnaitre","microLabel":"Reconnaître des droites, segments et demi-droites","notionId":"","notionLabel":"Droites","reussi":true},{"microId":"symetrie_defi","microLabel":"Résoudre un défi de symétrie","notionId":"","notionLabel":"Symétrie","reussi":false},{"microId":"symetrie_completer","microLabel":"Compléter une figure par symétrie","notionId":"","notionLabel":"Symétrie","reussi":false},{"microId":"algo_instruction","microLabel":"Suivre une suite d’instructions","notionId":"","notionLabel":"Algorithmique","reussi":true},{"microId":"duree_defi","microLabel":"Résoudre un défi de durées","notionId":"","notionLabel":"Durées","reussi":true},{"microId":"longueur_convertir","microLabel":"Convertir des longueurs","notionId":"","notionLabel":"Longueurs","reussi":true},{"microId":"masse_comparer","microLabel":"Comparer des masses","notionId":"","notionLabel":"Masses","reussi":false},{"microId":"masse_estimer","microLabel":"Estimer une masse","notionId":"","notionLabel":"Masses","reussi":true},{"microId":"angle_defi","microLabel":"Résoudre un défi sur les angles","notionId":"","notionLabel":"Angles","reussi":true},{"microId":"echelle_distance_plan","microLabel":"Calculer une distance sur un plan avec une échelle","notionId":"","notionLabel":"Échelles simples","reussi":true},{"microId":"calcul_priorite","microLabel":"Utiliser les priorités opératoires simples","notionId":"","notionLabel":"Calculs","reussi":true},{"microId":"fraction_defi","microLabel":"Résoudre un défi sur les fractions","notionId":"","notionLabel":"Fractions","reussi":true},{"microId":"calcul_mental","microLabel":"Calculer mentalement","notionId":"","notionLabel":"Calculs","reussi":true},{"microId":"decimal_fraction","microLabel":"Relier fraction décimale et nombre décimal","notionId":"","notionLabel":"Nombres décimaux","reussi":true},{"microId":"multiplication_table","microLabel":"Connaître les tables de multiplication","notionId":"","notionLabel":"Multiplication","reussi":true},{"microId":"entier_arrondir","microLabel":"Arrondir un nombre entier","notionId":"","notionLabel":"Nombres entiers","reussi":false},{"microId":"entier_multiple","microLabel":"Reconnaître les multiples d’un nombre","notionId":"","notionLabel":"Nombres entiers","reussi":true},{"microId":"entier_comparer","microLabel":"Comparer et ordonner des nombres entiers","notionId":"","notionLabel":"Nombres entiers","reussi":true},{"microId":"fraction_equivalente","microLabel":"Reconnaître des fractions équivalentes","notionId":"","notionLabel":"Fractions","reussi":false}]'::jsonb)
where code_etablissement = 'DIMITILE' and code_utilisateur = '6ETEST-06'
  and classe = '6e' and matiere = 'maths';

update public.resultats_evaluation_nationale
set details = jsonb_set(details, '{micros}', '[{"microId":"reperage_quadrillage","microLabel":"Se repérer sur un quadrillage","notionId":"","notionLabel":"Repérage","reussi":false},{"microId":"symetrie_construire","microLabel":"Construire le symétrique d’un point ou d’une figure","notionId":"","notionLabel":"Symétrie","reussi":false},{"microId":"algo_programme","microLabel":"Lire ou compléter un programme simple","notionId":"","notionLabel":"Algorithmique","reussi":false},{"microId":"figure_defi","microLabel":"Résoudre un défi sur les figures planes","notionId":"","notionLabel":"Figures planes","reussi":true},{"microId":"reperage_deplacement","microLabel":"Décrire un déplacement sur quadrillage","notionId":"","notionLabel":"Repérage","reussi":false},{"microId":"echelle_comprendre","microLabel":"Comprendre une échelle simple","notionId":"","notionLabel":"Échelles simples","reussi":false},{"microId":"echelle_distance_reelle","microLabel":"Calculer une distance réelle avec une échelle","notionId":"","notionLabel":"Échelles simples","reussi":true},{"microId":"masse_convertir","microLabel":"Convertir des masses","notionId":"","notionLabel":"Masses","reussi":true},{"microId":"angle_defi","microLabel":"Résoudre un défi sur les angles","notionId":"","notionLabel":"Angles","reussi":false},{"microId":"contenance_estimer","microLabel":"Estimer une contenance","notionId":"","notionLabel":"Contenances","reussi":true},{"microId":"echelle_distance_plan","microLabel":"Calculer une distance sur un plan avec une échelle","notionId":"","notionLabel":"Échelles simples","reussi":false},{"microId":"decimal_comparer","microLabel":"Comparer des nombres décimaux","notionId":"","notionLabel":"Nombres décimaux","reussi":true},{"microId":"fraction_defi","microLabel":"Résoudre un défi sur les fractions","notionId":"","notionLabel":"Fractions","reussi":true},{"microId":"entier_arrondir","microLabel":"Arrondir un nombre entier","notionId":"","notionLabel":"Nombres entiers","reussi":false},{"microId":"suite_regle","microLabel":"Trouver la règle d’une suite","notionId":"","notionLabel":"Suites de nombres","reussi":true},{"microId":"fraction_lire","microLabel":"Lire une fraction","notionId":"","notionLabel":"Fractions","reussi":true},{"microId":"decimal_ordonner","microLabel":"Ordonner des nombres décimaux","notionId":"","notionLabel":"Nombres décimaux","reussi":false},{"microId":"division_lien_multiplication","microLabel":"Associer multiplication et division","notionId":"","notionLabel":"Division","reussi":true},{"microId":"suite_croissante_decroissante","microLabel":"Reconnaître une suite croissante ou décroissante","notionId":"","notionLabel":"Suites de nombres","reussi":true},{"microId":"division_sens","microLabel":"Comprendre le sens de la division","notionId":"","notionLabel":"Division","reussi":true}]'::jsonb)
where code_etablissement = 'DIMITILE' and code_utilisateur = '6ETEST-07'
  and classe = '6e' and matiere = 'maths';

update public.resultats_evaluation_nationale
set details = jsonb_set(details, '{micros}', '[{"microId":"algo_instruction","microLabel":"Suivre une suite d’instructions","notionId":"","notionLabel":"Algorithmique","reussi":true},{"microId":"solide_face","microLabel":"Identifier les faces d’un solide","notionId":"","notionLabel":"Solides","reussi":false},{"microId":"droite_reconnaitre","microLabel":"Reconnaître des droites, segments et demi-droites","notionId":"","notionLabel":"Droites","reussi":true},{"microId":"droite_parallele","microLabel":"Reconnaître des droites parallèles","notionId":"","notionLabel":"Droites","reussi":false},{"microId":"solide_defi","microLabel":"Résoudre un défi sur les solides","notionId":"","notionLabel":"Solides","reussi":false},{"microId":"aire_triangle_rectangle","microLabel":"Calculer l’aire d’un triangle rectangle","notionId":"","notionLabel":"Aires","reussi":true},{"microId":"masse_estimer","microLabel":"Estimer une masse","notionId":"","notionLabel":"Masses","reussi":true},{"microId":"longueur_estimer","microLabel":"Estimer une longueur","notionId":"","notionLabel":"Longueurs","reussi":true},{"microId":"perimetre_defi","microLabel":"Résoudre un défi de périmètre","notionId":"","notionLabel":"Périmètres","reussi":true},{"microId":"echelle_distance_reelle","microLabel":"Calculer une distance réelle avec une échelle","notionId":"","notionLabel":"Échelles simples","reussi":false},{"microId":"echelle_defi","microLabel":"Résoudre un défi d’échelle","notionId":"","notionLabel":"Échelles simples","reussi":true},{"microId":"suite_continuer","microLabel":"Continuer une suite de nombres","notionId":"","notionLabel":"Suites de nombres","reussi":true},{"microId":"division_sens","microLabel":"Comprendre le sens de la division","notionId":"","notionLabel":"Division","reussi":false},{"microId":"fraction_lire","microLabel":"Lire une fraction","notionId":"","notionLabel":"Fractions","reussi":true},{"microId":"decimal_ordonner","microLabel":"Ordonner des nombres décimaux","notionId":"","notionLabel":"Nombres décimaux","reussi":true},{"microId":"suite_defi","microLabel":"Résoudre un défi sur les suites","notionId":"","notionLabel":"Suites de nombres","reussi":false},{"microId":"division_lien_multiplication","microLabel":"Associer multiplication et division","notionId":"","notionLabel":"Division","reussi":true},{"microId":"fraction_equivalente","microLabel":"Reconnaître des fractions équivalentes","notionId":"","notionLabel":"Fractions","reussi":true},{"microId":"calcul_decimal_addition","microLabel":"Additionner des nombres décimaux","notionId":"","notionLabel":"Calculs","reussi":false},{"microId":"decimal_valeur_chiffre","microLabel":"Donner la valeur d’un chiffre dans un nombre décimal","notionId":"","notionLabel":"Nombres décimaux","reussi":false}]'::jsonb)
where code_etablissement = 'DIMITILE' and code_utilisateur = '6ETEST-08'
  and classe = '6e' and matiere = 'maths';

update public.resultats_evaluation_nationale
set details = jsonb_set(details, '{micros}', '[{"microId":"droite_perpendiculaire","microLabel":"Reconnaître des droites perpendiculaires","notionId":"","notionLabel":"Droites","reussi":true},{"microId":"solide_patron","microLabel":"Reconnaître un patron de solide","notionId":"","notionLabel":"Solides","reussi":false},{"microId":"droite_parallele","microLabel":"Reconnaître des droites parallèles","notionId":"","notionLabel":"Droites","reussi":false},{"microId":"solide_reconnaitre","microLabel":"Reconnaître les solides usuels","notionId":"","notionLabel":"Solides","reussi":true},{"microId":"symetrie_completer","microLabel":"Compléter une figure par symétrie","notionId":"","notionLabel":"Symétrie","reussi":true},{"microId":"masse_comparer","microLabel":"Comparer des masses","notionId":"","notionLabel":"Masses","reussi":false},{"microId":"echelle_distance_reelle","microLabel":"Calculer une distance réelle avec une échelle","notionId":"","notionLabel":"Échelles simples","reussi":false},{"microId":"echelle_comprendre","microLabel":"Comprendre une échelle simple","notionId":"","notionLabel":"Échelles simples","reussi":false},{"microId":"duree_lire","microLabel":"Lire une heure ou une durée","notionId":"","notionLabel":"Durées","reussi":true},{"microId":"angle_defi","microLabel":"Résoudre un défi sur les angles","notionId":"","notionLabel":"Angles","reussi":true},{"microId":"longueur_convertir","microLabel":"Convertir des longueurs","notionId":"","notionLabel":"Longueurs","reussi":false},{"microId":"suite_defi","microLabel":"Résoudre un défi sur les suites","notionId":"","notionLabel":"Suites de nombres","reussi":true},{"microId":"suite_continuer","microLabel":"Continuer une suite de nombres","notionId":"","notionLabel":"Suites de nombres","reussi":true},{"microId":"decimal_comparer","microLabel":"Comparer des nombres décimaux","notionId":"","notionLabel":"Nombres décimaux","reussi":false},{"microId":"multiplication_mental","microLabel":"Multiplier mentalement","notionId":"","notionLabel":"Multiplication","reussi":false},{"microId":"fraction_equivalente","microLabel":"Reconnaître des fractions équivalentes","notionId":"","notionLabel":"Fractions","reussi":false},{"microId":"entier_lire","microLabel":"Lire et écrire des nombres entiers","notionId":"","notionLabel":"Nombres entiers","reussi":false},{"microId":"multiplication_probleme","microLabel":"Utiliser la multiplication dans un problème","notionId":"","notionLabel":"Multiplication","reussi":true},{"microId":"entier_comparer","microLabel":"Comparer et ordonner des nombres entiers","notionId":"","notionLabel":"Nombres entiers","reussi":false},{"microId":"multiplication_table","microLabel":"Connaître les tables de multiplication","notionId":"","notionLabel":"Multiplication","reussi":true}]'::jsonb)
where code_etablissement = 'DIMITILE' and code_utilisateur = '6ETEST-09'
  and classe = '6e' and matiere = 'maths';

update public.resultats_evaluation_nationale
set details = jsonb_set(details, '{micros}', '[{"microId":"droite_tracer","microLabel":"Tracer des droites parallèles ou perpendiculaires","notionId":"","notionLabel":"Droites","reussi":false},{"microId":"algo_programme","microLabel":"Lire ou compléter un programme simple","notionId":"","notionLabel":"Algorithmique","reussi":true},{"microId":"figure_cercle","microLabel":"Reconnaître et utiliser le cercle","notionId":"","notionLabel":"Figures planes","reussi":true},{"microId":"droite_perpendiculaire","microLabel":"Reconnaître des droites perpendiculaires","notionId":"","notionLabel":"Droites","reussi":true},{"microId":"figure_reconnaitre","microLabel":"Reconnaître une figure plane","notionId":"","notionLabel":"Figures planes","reussi":false},{"microId":"longueur_comparer","microLabel":"Comparer des longueurs","notionId":"","notionLabel":"Longueurs","reussi":true},{"microId":"angle_reconnaitre","microLabel":"Reconnaître un angle","notionId":"","notionLabel":"Angles","reussi":false},{"microId":"masse_convertir","microLabel":"Convertir des masses","notionId":"","notionLabel":"Masses","reussi":false},{"microId":"aire_carre_rectangle","microLabel":"Calculer l’aire d’un carré ou d’un rectangle","notionId":"","notionLabel":"Aires","reussi":false},{"microId":"perimetre_triangle","microLabel":"Calculer le périmètre d’un triangle","notionId":"","notionLabel":"Périmètres","reussi":false},{"microId":"aire_composer","microLabel":"Calculer une aire par découpage ou assemblage","notionId":"","notionLabel":"Aires","reussi":true},{"microId":"decimal_comparer","microLabel":"Comparer des nombres décimaux","notionId":"","notionLabel":"Nombres décimaux","reussi":false},{"microId":"entier_multiple","microLabel":"Reconnaître les multiples d’un nombre","notionId":"","notionLabel":"Nombres entiers","reussi":false},{"microId":"entier_lire","microLabel":"Lire et écrire des nombres entiers","notionId":"","notionLabel":"Nombres entiers","reussi":false},{"microId":"entier_arrondir","microLabel":"Arrondir un nombre entier","notionId":"","notionLabel":"Nombres entiers","reussi":false},{"microId":"fraction_droite","microLabel":"Placer une fraction sur une droite graduée","notionId":"","notionLabel":"Fractions","reussi":true},{"microId":"prop_tableau","microLabel":"Compléter un tableau de proportionnalité","notionId":"","notionLabel":"Proportionnalité","reussi":true},{"microId":"pourcentage_calculer","microLabel":"Calculer un pourcentage simple","notionId":"","notionLabel":"Pourcentages simples","reussi":true},{"microId":"calcul_addition_posee","microLabel":"Poser une addition","notionId":"","notionLabel":"Calculs","reussi":true},{"microId":"decimal_ordonner","microLabel":"Ordonner des nombres décimaux","notionId":"","notionLabel":"Nombres décimaux","reussi":true}]'::jsonb)
where code_etablissement = 'DIMITILE' and code_utilisateur = '6ETEST-10'
  and classe = '6e' and matiere = 'maths';

update public.resultats_evaluation_nationale
set details = jsonb_set(details, '{micros}', '[{"microId":"solide_sommet_arete_face","microLabel":"Identifier sommets, arêtes et faces","notionId":"","notionLabel":"Solides","reussi":false},{"microId":"algo_instruction","microLabel":"Suivre une suite d’instructions","notionId":"","notionLabel":"Algorithmique","reussi":true},{"microId":"droite_tracer","microLabel":"Tracer des droites parallèles ou perpendiculaires","notionId":"","notionLabel":"Droites","reussi":true},{"microId":"algo_defi","microLabel":"Résoudre un défi d’algorithmique","notionId":"","notionLabel":"Algorithmique","reussi":true},{"microId":"figure_defi","microLabel":"Résoudre un défi sur les figures planes","notionId":"","notionLabel":"Figures planes","reussi":true},{"microId":"echelle_defi","microLabel":"Résoudre un défi d’échelle","notionId":"","notionLabel":"Échelles simples","reussi":true},{"microId":"masse_convertir","microLabel":"Convertir des masses","notionId":"","notionLabel":"Masses","reussi":false},{"microId":"perimetre_triangle","microLabel":"Calculer le périmètre d’un triangle","notionId":"","notionLabel":"Périmètres","reussi":false},{"microId":"aire_defi","microLabel":"Résoudre un défi d’aire","notionId":"","notionLabel":"Aires","reussi":false},{"microId":"contenance_estimer","microLabel":"Estimer une contenance","notionId":"","notionLabel":"Contenances","reussi":true},{"microId":"duree_defi","microLabel":"Résoudre un défi de durées","notionId":"","notionLabel":"Durées","reussi":false},{"microId":"fraction_defi","microLabel":"Résoudre un défi sur les fractions","notionId":"","notionLabel":"Fractions","reussi":true},{"microId":"decimal_comparer","microLabel":"Comparer des nombres décimaux","notionId":"","notionLabel":"Nombres décimaux","reussi":false},{"microId":"entier_multiple","microLabel":"Reconnaître les multiples d’un nombre","notionId":"","notionLabel":"Nombres entiers","reussi":true},{"microId":"entier_lire","microLabel":"Lire et écrire des nombres entiers","notionId":"","notionLabel":"Nombres entiers","reussi":true},{"microId":"fraction_representer","microLabel":"Représenter une fraction","notionId":"","notionLabel":"Fractions","reussi":true},{"microId":"multiplication_defi","microLabel":"Résoudre un défi de multiplication","notionId":"","notionLabel":"Multiplication","reussi":true},{"microId":"decimal_defi","microLabel":"Résoudre un défi sur les nombres décimaux","notionId":"","notionLabel":"Nombres décimaux","reussi":true},{"microId":"decimal_lire","microLabel":"Lire et écrire un nombre décimal","notionId":"","notionLabel":"Nombres décimaux","reussi":false},{"microId":"division_posee","microLabel":"Poser une division simple","notionId":"","notionLabel":"Division","reussi":false}]'::jsonb)
where code_etablissement = 'DIMITILE' and code_utilisateur = '6ETEST-11'
  and classe = '6e' and matiere = 'maths';

update public.resultats_evaluation_nationale
set details = jsonb_set(details, '{micros}', '[{"microId":"algo_deplacement","microLabel":"Coder un déplacement sur quadrillage","notionId":"","notionLabel":"Algorithmique","reussi":false},{"microId":"solide_face","microLabel":"Identifier les faces d’un solide","notionId":"","notionLabel":"Solides","reussi":false},{"microId":"solide_sommet_arete_face","microLabel":"Identifier sommets, arêtes et faces","notionId":"","notionLabel":"Solides","reussi":false},{"microId":"solide_defi","microLabel":"Résoudre un défi sur les solides","notionId":"","notionLabel":"Solides","reussi":false},{"microId":"algo_repetition","microLabel":"Utiliser une répétition simple","notionId":"","notionLabel":"Algorithmique","reussi":false},{"microId":"echelle_distance_plan","microLabel":"Calculer une distance sur un plan avec une échelle","notionId":"","notionLabel":"Échelles simples","reussi":true},{"microId":"masse_estimer","microLabel":"Estimer une masse","notionId":"","notionLabel":"Masses","reussi":false},{"microId":"angle_defi","microLabel":"Résoudre un défi sur les angles","notionId":"","notionLabel":"Angles","reussi":true},{"microId":"angle_type","microLabel":"Reconnaître un angle aigu, obtus, plat ou droit","notionId":"","notionLabel":"Angles","reussi":false},{"microId":"perimetre_defi","microLabel":"Résoudre un défi de périmètre","notionId":"","notionLabel":"Périmètres","reussi":false},{"microId":"perimetre_polygone","microLabel":"Calculer le périmètre d’un polygone","notionId":"","notionLabel":"Périmètres","reussi":false},{"microId":"probleme_rediger","microLabel":"Rédiger une réponse claire à un problème","notionId":"","notionLabel":"Problèmes","reussi":false},{"microId":"probleme_plusieurs_etapes","microLabel":"Résoudre un problème à plusieurs étapes","notionId":"","notionLabel":"Problèmes","reussi":true},{"microId":"graphique_defi","microLabel":"Résoudre un défi avec un graphique","notionId":"","notionLabel":"Graphiques et diagrammes","reussi":true},{"microId":"algebre_nombre_inconnu","microLabel":"Trouver un nombre inconnu","notionId":"","notionLabel":"Algèbre","reussi":false},{"microId":"pourcentage_comprendre","microLabel":"Comprendre un pourcentage simple","notionId":"","notionLabel":"Pourcentages simples","reussi":false},{"microId":"probleme_defi","microLabel":"Résoudre un défi de problème","notionId":"","notionLabel":"Problèmes","reussi":false},{"microId":"graphique_interpreter","microLabel":"Interpréter un graphique ou un diagramme","notionId":"","notionLabel":"Graphiques et diagrammes","reussi":false},{"microId":"algebre_schema_barre","microLabel":"Utiliser un schéma en barres","notionId":"","notionLabel":"Algèbre","reussi":true},{"microId":"fraction_defi","microLabel":"Résoudre un défi sur les fractions","notionId":"","notionLabel":"Fractions","reussi":false}]'::jsonb)
where code_etablissement = 'DIMITILE' and code_utilisateur = '6ETEST-12'
  and classe = '6e' and matiere = 'maths';

update public.resultats_evaluation_nationale
set details = jsonb_set(details, '{micros}', '[{"microId":"symetrie_propriete","microLabel":"Utiliser les propriétés de la symétrie","notionId":"","notionLabel":"Symétrie","reussi":true},{"microId":"droite_tracer","microLabel":"Tracer des droites parallèles ou perpendiculaires","notionId":"","notionLabel":"Droites","reussi":false},{"microId":"algo_deplacement","microLabel":"Coder un déplacement sur quadrillage","notionId":"","notionLabel":"Algorithmique","reussi":false},{"microId":"droite_perpendiculaire","microLabel":"Reconnaître des droites perpendiculaires","notionId":"","notionLabel":"Droites","reussi":true},{"microId":"figure_cercle","microLabel":"Reconnaître et utiliser le cercle","notionId":"","notionLabel":"Figures planes","reussi":false},{"microId":"longueur_defi","microLabel":"Résoudre un défi de longueurs","notionId":"","notionLabel":"Longueurs","reussi":false},{"microId":"echelle_distance_reelle","microLabel":"Calculer une distance réelle avec une échelle","notionId":"","notionLabel":"Échelles simples","reussi":false},{"microId":"masse_defi","microLabel":"Résoudre un défi de masses","notionId":"","notionLabel":"Masses","reussi":false},{"microId":"duree_lire","microLabel":"Lire une heure ou une durée","notionId":"","notionLabel":"Durées","reussi":true},{"microId":"aire_carre_rectangle","microLabel":"Calculer l’aire d’un carré ou d’un rectangle","notionId":"","notionLabel":"Aires","reussi":false},{"microId":"longueur_estimer","microLabel":"Estimer une longueur","notionId":"","notionLabel":"Longueurs","reussi":false},{"microId":"entier_decomposer","microLabel":"Décomposer des nombres entiers","notionId":"","notionLabel":"Nombres entiers","reussi":true},{"microId":"multiplication_puissance_dix","microLabel":"Multiplier par 10, 100 ou 1 000","notionId":"","notionLabel":"Multiplication","reussi":false},{"microId":"pourcentage_probleme","microLabel":"Résoudre un problème avec un pourcentage simple","notionId":"","notionLabel":"Pourcentages simples","reussi":false},{"microId":"algebre_relation","microLabel":"Décrire une relation entre deux quantités","notionId":"","notionLabel":"Algèbre","reussi":false},{"microId":"fraction_decimale","microLabel":"Reconnaître une fraction décimale","notionId":"","notionLabel":"Fractions","reussi":true},{"microId":"calcul_decimal_addition","microLabel":"Additionner des nombres décimaux","notionId":"","notionLabel":"Calculs","reussi":true},{"microId":"algebre_schema_barre","microLabel":"Utiliser un schéma en barres","notionId":"","notionLabel":"Algèbre","reussi":true},{"microId":"entier_arrondir","microLabel":"Arrondir un nombre entier","notionId":"","notionLabel":"Nombres entiers","reussi":false},{"microId":"entier_multiple","microLabel":"Reconnaître les multiples d’un nombre","notionId":"","notionLabel":"Nombres entiers","reussi":true}]'::jsonb)
where code_etablissement = 'DIMITILE' and code_utilisateur = '6ETEST-13'
  and classe = '6e' and matiere = 'maths';

update public.resultats_evaluation_nationale
set details = jsonb_set(details, '{micros}', '[{"microId":"algo_logique","microLabel":"Compléter une suite logique","notionId":"","notionLabel":"Algorithmique","reussi":false},{"microId":"symetrie_construire","microLabel":"Construire le symétrique d’un point ou d’une figure","notionId":"","notionLabel":"Symétrie","reussi":false},{"microId":"symetrie_defi","microLabel":"Résoudre un défi de symétrie","notionId":"","notionLabel":"Symétrie","reussi":false},{"microId":"droite_tracer","microLabel":"Tracer des droites parallèles ou perpendiculaires","notionId":"","notionLabel":"Droites","reussi":false},{"microId":"solide_reconnaitre","microLabel":"Reconnaître les solides usuels","notionId":"","notionLabel":"Solides","reussi":false},{"microId":"contenance_comparer","microLabel":"Comparer des contenances","notionId":"","notionLabel":"Contenances","reussi":false},{"microId":"duree_lire","microLabel":"Lire une heure ou une durée","notionId":"","notionLabel":"Durées","reussi":false},{"microId":"angle_droit","microLabel":"Reconnaître un angle droit","notionId":"","notionLabel":"Angles","reussi":false},{"microId":"masse_convertir","microLabel":"Convertir des masses","notionId":"","notionLabel":"Masses","reussi":true},{"microId":"angle_mesurer","microLabel":"Mesurer un angle avec un rapporteur","notionId":"","notionLabel":"Angles","reussi":false},{"microId":"echelle_defi","microLabel":"Résoudre un défi d’échelle","notionId":"","notionLabel":"Échelles simples","reussi":false},{"microId":"entier_decomposer","microLabel":"Décomposer des nombres entiers","notionId":"","notionLabel":"Nombres entiers","reussi":false},{"microId":"fraction_droite","microLabel":"Placer une fraction sur une droite graduée","notionId":"","notionLabel":"Fractions","reussi":true},{"microId":"division_lien_multiplication","microLabel":"Associer multiplication et division","notionId":"","notionLabel":"Division","reussi":false},{"microId":"fraction_decimale","microLabel":"Reconnaître une fraction décimale","notionId":"","notionLabel":"Fractions","reussi":true},{"microId":"entier_comparer","microLabel":"Comparer et ordonner des nombres entiers","notionId":"","notionLabel":"Nombres entiers","reussi":false},{"microId":"multiplication_defi","microLabel":"Résoudre un défi de multiplication","notionId":"","notionLabel":"Multiplication","reussi":false},{"microId":"suite_croissante_decroissante","microLabel":"Reconnaître une suite croissante ou décroissante","notionId":"","notionLabel":"Suites de nombres","reussi":false},{"microId":"fraction_defi","microLabel":"Résoudre un défi sur les fractions","notionId":"","notionLabel":"Fractions","reussi":false},{"microId":"tableau_lire","microLabel":"Lire un tableau","notionId":"","notionLabel":"Tableaux","reussi":false}]'::jsonb)
where code_etablissement = 'DIMITILE' and code_utilisateur = '6ETEST-14'
  and classe = '6e' and matiere = 'maths';

update public.resultats_evaluation_nationale
set details = jsonb_set(details, '{micros}', '[{"microId":"solide_face","microLabel":"Identifier les faces d’un solide","notionId":"","notionLabel":"Solides","reussi":false},{"microId":"droite_tracer","microLabel":"Tracer des droites parallèles ou perpendiculaires","notionId":"","notionLabel":"Droites","reussi":false},{"microId":"figure_reconnaitre","microLabel":"Reconnaître une figure plane","notionId":"","notionLabel":"Figures planes","reussi":false},{"microId":"algo_defi","microLabel":"Résoudre un défi d’algorithmique","notionId":"","notionLabel":"Algorithmique","reussi":false},{"microId":"algo_logique","microLabel":"Compléter une suite logique","notionId":"","notionLabel":"Algorithmique","reussi":false},{"microId":"angle_droit","microLabel":"Reconnaître un angle droit","notionId":"","notionLabel":"Angles","reussi":false},{"microId":"perimetre_triangle","microLabel":"Calculer le périmètre d’un triangle","notionId":"","notionLabel":"Périmètres","reussi":false},{"microId":"angle_type","microLabel":"Reconnaître un angle aigu, obtus, plat ou droit","notionId":"","notionLabel":"Angles","reussi":false},{"microId":"angle_defi","microLabel":"Résoudre un défi sur les angles","notionId":"","notionLabel":"Angles","reussi":false},{"microId":"angle_mesurer","microLabel":"Mesurer un angle avec un rapporteur","notionId":"","notionLabel":"Angles","reussi":false},{"microId":"duree_defi","microLabel":"Résoudre un défi de durées","notionId":"","notionLabel":"Durées","reussi":false},{"microId":"entier_lire","microLabel":"Lire et écrire des nombres entiers","notionId":"","notionLabel":"Nombres entiers","reussi":true},{"microId":"entier_defi","microLabel":"Résoudre un défi sur les nombres entiers","notionId":"","notionLabel":"Nombres entiers","reussi":false},{"microId":"fraction_equivalente","microLabel":"Reconnaître des fractions équivalentes","notionId":"","notionLabel":"Fractions","reussi":false},{"microId":"fraction_lire","microLabel":"Lire une fraction","notionId":"","notionLabel":"Fractions","reussi":false},{"microId":"probleme_choisir_operation","microLabel":"Choisir la bonne opération dans un problème","notionId":"","notionLabel":"Problèmes","reussi":false},{"microId":"calcul_decimal_addition","microLabel":"Additionner des nombres décimaux","notionId":"","notionLabel":"Calculs","reussi":false},{"microId":"probleme_defi","microLabel":"Résoudre un défi de problème","notionId":"","notionLabel":"Problèmes","reussi":false},{"microId":"calcul_defi","microLabel":"Résoudre un défi de calcul","notionId":"","notionLabel":"Calculs","reussi":false},{"microId":"pourcentage_defi","microLabel":"Résoudre un défi de pourcentage","notionId":"","notionLabel":"Pourcentages simples","reussi":false}]'::jsonb)
where code_etablissement = 'DIMITILE' and code_utilisateur = '6ETEST-15'
  and classe = '6e' and matiere = 'maths';

-- Contrôle : chaque ligne doit avoir une vingtaine de micro-compétences.
-- select code_utilisateur, jsonb_array_length(details->'micros') as micros
-- from public.resultats_evaluation_nationale
-- where code_etablissement = 'DIMITILE' and code_utilisateur like '6ETEST-%'
-- order by code_utilisateur;
