import type { TutorBankItemV4 } from "@/lib/tutor-v4/types";

export const iaC1QuestionBank: TutorBankItemV4[] = [
  {
    kind: "fixed",
    id: "ia_c1_probleme_reel_qcm_001",
    niveau: "c1",
    matiere: "ia",
    notionId: "ia_c1_cadrer_projet",
    microId: "ia_c1_probleme_reel",
    difficulty: 1,
    text: "Quelle affirmation valide la micro-comp?tence C1 : Je sais identifier un probl?me r?el et formuler le besoin d'un utilisateur.",
    format: "qcm",
    choices: ["Je sais identifier un probl?me r?el et formuler le besoin d'un utilisateur.","Je laisse l'IA d?cider ? ma place.","Je copie la r?ponse sans v?rifier."],
    expected: ["A"],
    comparator: "mcq_exact",
    hint: "Cherche la r?ponse qui garde m?thode, jugement et responsabilit? humaine.",
    explanation: "Bonne r?ponse : Je sais identifier un probl?me r?el et formuler le besoin d'un utilisateur.",
  },
  {
    kind: "fixed",
    id: "ia_c1_probleme_reel_qcm_002",
    niveau: "c1",
    matiere: "ia",
    notionId: "ia_c1_cadrer_projet",
    microId: "ia_c1_probleme_reel",
    difficulty: 1,
    text: "Dans une situation r?elle, quelle action correspond le mieux ? : Je sais identifier un probl?me r?el et formuler le besoin d'un utilisateur.",
    format: "qcm",
    choices: ["Je sais identifier un probl?me r?el et formuler le besoin d'un utilisateur.","Partager des informations sensibles pour aller plus vite.","Faire confiance ? une seule r?ponse sans recul."],
    expected: ["A"],
    comparator: "mcq_exact",
    hint: "L'IA est un outil : l'?l?ve garde l'objectif, la v?rification et la d?cision.",
    explanation: "Cette micro-comp?tence se valide quand l'?l?ve sait faire ceci : Je sais identifier un probl?me r?el et formuler le besoin d'un utilisateur.",
  },
  {
    kind: "fixed",
    id: "ia_c1_donnees_role_humain_qcm_001",
    niveau: "c1",
    matiere: "ia",
    notionId: "ia_c1_cadrer_projet",
    microId: "ia_c1_donnees_role_humain",
    difficulty: 1,
    text: "Quelle affirmation valide la micro-comp?tence C1 : Je sais d?crire les donn?es n?cessaires, ce que fait l'IA et ce que d?cide l'humain.",
    format: "qcm",
    choices: ["Je sais d?crire les donn?es n?cessaires, ce que fait l'IA et ce que d?cide l'humain.","Je laisse l'IA d?cider ? ma place.","Je copie la r?ponse sans v?rifier."],
    expected: ["A"],
    comparator: "mcq_exact",
    hint: "Cherche la r?ponse qui garde m?thode, jugement et responsabilit? humaine.",
    explanation: "Bonne r?ponse : Je sais d?crire les donn?es n?cessaires, ce que fait l'IA et ce que d?cide l'humain.",
  },
  {
    kind: "fixed",
    id: "ia_c1_donnees_role_humain_qcm_002",
    niveau: "c1",
    matiere: "ia",
    notionId: "ia_c1_cadrer_projet",
    microId: "ia_c1_donnees_role_humain",
    difficulty: 1,
    text: "Dans une situation r?elle, quelle action correspond le mieux ? : Je sais d?crire les donn?es n?cessaires, ce que fait l'IA et ce que d?cide l'humain.",
    format: "qcm",
    choices: ["Je sais d?crire les donn?es n?cessaires, ce que fait l'IA et ce que d?cide l'humain.","Partager des informations sensibles pour aller plus vite.","Faire confiance ? une seule r?ponse sans recul."],
    expected: ["A"],
    comparator: "mcq_exact",
    hint: "L'IA est un outil : l'?l?ve garde l'objectif, la v?rification et la d?cision.",
    explanation: "Cette micro-comp?tence se valide quand l'?l?ve sait faire ceci : Je sais d?crire les donn?es n?cessaires, ce que fait l'IA et ce que d?cide l'humain.",
  },
  {
    kind: "fixed",
    id: "ia_c1_criteres_reussite_qcm_001",
    niveau: "c1",
    matiere: "ia",
    notionId: "ia_c1_cadrer_projet",
    microId: "ia_c1_criteres_reussite",
    difficulty: 2,
    text: "Quelle affirmation valide la micro-comp?tence C1 : Je sais d?finir des crit?res pour savoir si le projet fonctionne.",
    format: "qcm",
    choices: ["Je sais d?finir des crit?res pour savoir si le projet fonctionne.","Je laisse l'IA d?cider ? ma place.","Je copie la r?ponse sans v?rifier."],
    expected: ["A"],
    comparator: "mcq_exact",
    hint: "Cherche la r?ponse qui garde m?thode, jugement et responsabilit? humaine.",
    explanation: "Bonne r?ponse : Je sais d?finir des crit?res pour savoir si le projet fonctionne.",
  },
  {
    kind: "fixed",
    id: "ia_c1_criteres_reussite_qcm_002",
    niveau: "c1",
    matiere: "ia",
    notionId: "ia_c1_cadrer_projet",
    microId: "ia_c1_criteres_reussite",
    difficulty: 2,
    text: "Dans une situation r?elle, quelle action correspond le mieux ? : Je sais d?finir des crit?res pour savoir si le projet fonctionne.",
    format: "qcm",
    choices: ["Je sais d?finir des crit?res pour savoir si le projet fonctionne.","Partager des informations sensibles pour aller plus vite.","Faire confiance ? une seule r?ponse sans recul."],
    expected: ["A"],
    comparator: "mcq_exact",
    hint: "L'IA est un outil : l'?l?ve garde l'objectif, la v?rification et la d?cision.",
    explanation: "Cette micro-comp?tence se valide quand l'?l?ve sait faire ceci : Je sais d?finir des crit?res pour savoir si le projet fonctionne.",
  },
  {
    kind: "fixed",
    id: "ia_c1_risques_regles_qcm_001",
    niveau: "c1",
    matiere: "ia",
    notionId: "ia_c1_responsabilite_pitch",
    microId: "ia_c1_risques_regles",
    difficulty: 2,
    text: "Quelle affirmation valide la micro-comp?tence C1 : Je sais pr?voir les risques et proposer des r?gles de s?curit?.",
    format: "qcm",
    choices: ["Je sais pr?voir les risques et proposer des r?gles de s?curit?.","Je laisse l'IA d?cider ? ma place.","Je copie la r?ponse sans v?rifier."],
    expected: ["A"],
    comparator: "mcq_exact",
    hint: "Cherche la r?ponse qui garde m?thode, jugement et responsabilit? humaine.",
    explanation: "Bonne r?ponse : Je sais pr?voir les risques et proposer des r?gles de s?curit?.",
  },
  {
    kind: "fixed",
    id: "ia_c1_risques_regles_qcm_002",
    niveau: "c1",
    matiere: "ia",
    notionId: "ia_c1_responsabilite_pitch",
    microId: "ia_c1_risques_regles",
    difficulty: 2,
    text: "Dans une situation r?elle, quelle action correspond le mieux ? : Je sais pr?voir les risques et proposer des r?gles de s?curit?.",
    format: "qcm",
    choices: ["Je sais pr?voir les risques et proposer des r?gles de s?curit?.","Partager des informations sensibles pour aller plus vite.","Faire confiance ? une seule r?ponse sans recul."],
    expected: ["A"],
    comparator: "mcq_exact",
    hint: "L'IA est un outil : l'?l?ve garde l'objectif, la v?rification et la d?cision.",
    explanation: "Cette micro-comp?tence se valide quand l'?l?ve sait faire ceci : Je sais pr?voir les risques et proposer des r?gles de s?curit?.",
  },
  {
    kind: "fixed",
    id: "ia_c1_tester_ameliorer_qcm_001",
    niveau: "c1",
    matiere: "ia",
    notionId: "ia_c1_responsabilite_pitch",
    microId: "ia_c1_tester_ameliorer",
    difficulty: 3,
    text: "Quelle affirmation valide la micro-comp?tence C1 : Je sais tester une maquette et am?liorer le projet ? partir des retours.",
    format: "qcm",
    choices: ["Je sais tester une maquette et am?liorer le projet ? partir des retours.","Je laisse l'IA d?cider ? ma place.","Je copie la r?ponse sans v?rifier."],
    expected: ["A"],
    comparator: "mcq_exact",
    hint: "Cherche la r?ponse qui garde m?thode, jugement et responsabilit? humaine.",
    explanation: "Bonne r?ponse : Je sais tester une maquette et am?liorer le projet ? partir des retours.",
  },
  {
    kind: "fixed",
    id: "ia_c1_tester_ameliorer_qcm_002",
    niveau: "c1",
    matiere: "ia",
    notionId: "ia_c1_responsabilite_pitch",
    microId: "ia_c1_tester_ameliorer",
    difficulty: 3,
    text: "Dans une situation r?elle, quelle action correspond le mieux ? : Je sais tester une maquette et am?liorer le projet ? partir des retours.",
    format: "qcm",
    choices: ["Je sais tester une maquette et am?liorer le projet ? partir des retours.","Partager des informations sensibles pour aller plus vite.","Faire confiance ? une seule r?ponse sans recul."],
    expected: ["A"],
    comparator: "mcq_exact",
    hint: "L'IA est un outil : l'?l?ve garde l'objectif, la v?rification et la d?cision.",
    explanation: "Cette micro-comp?tence se valide quand l'?l?ve sait faire ceci : Je sais tester une maquette et am?liorer le projet ? partir des retours.",
  },
  {
    kind: "fixed",
    id: "ia_c1_pitch_jury_qcm_001",
    niveau: "c1",
    matiere: "ia",
    notionId: "ia_c1_responsabilite_pitch",
    microId: "ia_c1_pitch_jury",
    difficulty: 3,
    text: "Quelle affirmation valide la micro-comp?tence C1 : Je sais pr?senter un pitch clair et r?pondre aux questions d'un jury.",
    format: "qcm",
    choices: ["Je sais pr?senter un pitch clair et r?pondre aux questions d'un jury.","Je laisse l'IA d?cider ? ma place.","Je copie la r?ponse sans v?rifier."],
    expected: ["A"],
    comparator: "mcq_exact",
    hint: "Cherche la r?ponse qui garde m?thode, jugement et responsabilit? humaine.",
    explanation: "Bonne r?ponse : Je sais pr?senter un pitch clair et r?pondre aux questions d'un jury.",
  },
  {
    kind: "fixed",
    id: "ia_c1_pitch_jury_qcm_002",
    niveau: "c1",
    matiere: "ia",
    notionId: "ia_c1_responsabilite_pitch",
    microId: "ia_c1_pitch_jury",
    difficulty: 3,
    text: "Dans une situation r?elle, quelle action correspond le mieux ? : Je sais pr?senter un pitch clair et r?pondre aux questions d'un jury.",
    format: "qcm",
    choices: ["Je sais pr?senter un pitch clair et r?pondre aux questions d'un jury.","Partager des informations sensibles pour aller plus vite.","Faire confiance ? une seule r?ponse sans recul."],
    expected: ["A"],
    comparator: "mcq_exact",
    hint: "L'IA est un outil : l'?l?ve garde l'objectif, la v?rification et la d?cision.",
    explanation: "Cette micro-comp?tence se valide quand l'?l?ve sait faire ceci : Je sais pr?senter un pitch clair et r?pondre aux questions d'un jury.",
  },
];

export function getIaC1QuestionBank(args?: {
  notionId?: string | null;
  microId?: string | null;
}): TutorBankItemV4[] {
  let bank = iaC1QuestionBank;

  if (args?.notionId) bank = bank.filter((item) => item.notionId === args.notionId);
  if (args?.microId) bank = bank.filter((item) => item.microId === args.microId);

  return bank;
}
