import type { TutorBankItemV4 } from "@/lib/tutor-v4/types";

export const iaC1QuestionBank: TutorBankItemV4[] = [
  {
    kind: "fixed",
    id: "ia_c1_probleme_reel_qcm_001",
    niveau: "c1",
    matiere: "ia",
    notionId: "ia_c1_cadrer_projet",
    microId: "ia_c1_probleme_reel",
    difficulty: 1,
    text: "Quelle affirmation valide la micro-competence C1 : Je sais identifier un probleme reel et formuler le besoin d'un utilisateur.",
    format: "qcm",
    choices: ["Je sais identifier un probleme reel et formuler le besoin d'un utilisateur.","Je laisse l'IA decider a ma place.","Je copie la reponse sans verifier."],
    expected: ["Je sais identifier un probleme reel et formuler le besoin d'un utilisateur."],
    comparator: "mcq_exact",
    hint: "Cherche la reponse qui garde methode, jugement et responsabilite humaine.",
    explanation: "Bonne reponse : Je sais identifier un probleme reel et formuler le besoin d'un utilisateur.",
  },
  {
    kind: "fixed",
    id: "ia_c1_probleme_reel_qcm_002",
    niveau: "c1",
    matiere: "ia",
    notionId: "ia_c1_cadrer_projet",
    microId: "ia_c1_probleme_reel",
    difficulty: 1,
    text: "Dans une situation reelle, quelle action correspond le mieux a : Je sais identifier un probleme reel et formuler le besoin d'un utilisateur.",
    format: "qcm",
    choices: ["Je sais identifier un probleme reel et formuler le besoin d'un utilisateur.","Partager des informations sensibles pour aller plus vite.","Faire confiance a une seule reponse sans recul."],
    expected: ["Je sais identifier un probleme reel et formuler le besoin d'un utilisateur."],
    comparator: "mcq_exact",
    hint: "L'IA est un outil : l'eleve garde l'objectif, la verification et la decision.",
    explanation: "Cette micro-competence se valide quand l'eleve sait faire ceci : Je sais identifier un probleme reel et formuler le besoin d'un utilisateur.",
  },
  {
    kind: "fixed",
    id: "ia_c1_donnees_role_humain_qcm_001",
    niveau: "c1",
    matiere: "ia",
    notionId: "ia_c1_cadrer_projet",
    microId: "ia_c1_donnees_role_humain",
    difficulty: 1,
    text: "Quelle affirmation valide la micro-competence C1 : Je sais decrire les donnees necessaires, ce que fait l'IA et ce que decide l'humain.",
    format: "qcm",
    choices: ["Je sais decrire les donnees necessaires, ce que fait l'IA et ce que decide l'humain.","Je laisse l'IA decider a ma place.","Je copie la reponse sans verifier."],
    expected: ["Je sais decrire les donnees necessaires, ce que fait l'IA et ce que decide l'humain."],
    comparator: "mcq_exact",
    hint: "Cherche la reponse qui garde methode, jugement et responsabilite humaine.",
    explanation: "Bonne reponse : Je sais decrire les donnees necessaires, ce que fait l'IA et ce que decide l'humain.",
  },
  {
    kind: "fixed",
    id: "ia_c1_donnees_role_humain_qcm_002",
    niveau: "c1",
    matiere: "ia",
    notionId: "ia_c1_cadrer_projet",
    microId: "ia_c1_donnees_role_humain",
    difficulty: 1,
    text: "Dans une situation reelle, quelle action correspond le mieux a : Je sais decrire les donnees necessaires, ce que fait l'IA et ce que decide l'humain.",
    format: "qcm",
    choices: ["Je sais decrire les donnees necessaires, ce que fait l'IA et ce que decide l'humain.","Partager des informations sensibles pour aller plus vite.","Faire confiance a une seule reponse sans recul."],
    expected: ["Je sais decrire les donnees necessaires, ce que fait l'IA et ce que decide l'humain."],
    comparator: "mcq_exact",
    hint: "L'IA est un outil : l'eleve garde l'objectif, la verification et la decision.",
    explanation: "Cette micro-competence se valide quand l'eleve sait faire ceci : Je sais decrire les donnees necessaires, ce que fait l'IA et ce que decide l'humain.",
  },
  {
    kind: "fixed",
    id: "ia_c1_criteres_reussite_qcm_001",
    niveau: "c1",
    matiere: "ia",
    notionId: "ia_c1_cadrer_projet",
    microId: "ia_c1_criteres_reussite",
    difficulty: 2,
    text: "Quelle affirmation valide la micro-competence C1 : Je sais definir des criteres pour savoir si le projet fonctionne.",
    format: "qcm",
    choices: ["Je sais definir des criteres pour savoir si le projet fonctionne.","Je laisse l'IA decider a ma place.","Je copie la reponse sans verifier."],
    expected: ["Je sais definir des criteres pour savoir si le projet fonctionne."],
    comparator: "mcq_exact",
    hint: "Cherche la reponse qui garde methode, jugement et responsabilite humaine.",
    explanation: "Bonne reponse : Je sais definir des criteres pour savoir si le projet fonctionne.",
  },
  {
    kind: "fixed",
    id: "ia_c1_criteres_reussite_qcm_002",
    niveau: "c1",
    matiere: "ia",
    notionId: "ia_c1_cadrer_projet",
    microId: "ia_c1_criteres_reussite",
    difficulty: 2,
    text: "Dans une situation reelle, quelle action correspond le mieux a : Je sais definir des criteres pour savoir si le projet fonctionne.",
    format: "qcm",
    choices: ["Je sais definir des criteres pour savoir si le projet fonctionne.","Partager des informations sensibles pour aller plus vite.","Faire confiance a une seule reponse sans recul."],
    expected: ["Je sais definir des criteres pour savoir si le projet fonctionne."],
    comparator: "mcq_exact",
    hint: "L'IA est un outil : l'eleve garde l'objectif, la verification et la decision.",
    explanation: "Cette micro-competence se valide quand l'eleve sait faire ceci : Je sais definir des criteres pour savoir si le projet fonctionne.",
  },
  {
    kind: "fixed",
    id: "ia_c1_risques_regles_qcm_001",
    niveau: "c1",
    matiere: "ia",
    notionId: "ia_c1_responsabilite_pitch",
    microId: "ia_c1_risques_regles",
    difficulty: 2,
    text: "Quelle affirmation valide la micro-competence C1 : Je sais prevoir les risques et proposer des regles de securite.",
    format: "qcm",
    choices: ["Je sais prevoir les risques et proposer des regles de securite.","Je laisse l'IA decider a ma place.","Je copie la reponse sans verifier."],
    expected: ["Je sais prevoir les risques et proposer des regles de securite."],
    comparator: "mcq_exact",
    hint: "Cherche la reponse qui garde methode, jugement et responsabilite humaine.",
    explanation: "Bonne reponse : Je sais prevoir les risques et proposer des regles de securite.",
  },
  {
    kind: "fixed",
    id: "ia_c1_risques_regles_qcm_002",
    niveau: "c1",
    matiere: "ia",
    notionId: "ia_c1_responsabilite_pitch",
    microId: "ia_c1_risques_regles",
    difficulty: 2,
    text: "Dans une situation reelle, quelle action correspond le mieux a : Je sais prevoir les risques et proposer des regles de securite.",
    format: "qcm",
    choices: ["Je sais prevoir les risques et proposer des regles de securite.","Partager des informations sensibles pour aller plus vite.","Faire confiance a une seule reponse sans recul."],
    expected: ["Je sais prevoir les risques et proposer des regles de securite."],
    comparator: "mcq_exact",
    hint: "L'IA est un outil : l'eleve garde l'objectif, la verification et la decision.",
    explanation: "Cette micro-competence se valide quand l'eleve sait faire ceci : Je sais prevoir les risques et proposer des regles de securite.",
  },
  {
    kind: "fixed",
    id: "ia_c1_tester_ameliorer_qcm_001",
    niveau: "c1",
    matiere: "ia",
    notionId: "ia_c1_responsabilite_pitch",
    microId: "ia_c1_tester_ameliorer",
    difficulty: 3,
    text: "Quelle affirmation valide la micro-competence C1 : Je sais tester une maquette et ameliorer le projet a partir des retours.",
    format: "qcm",
    choices: ["Je sais tester une maquette et ameliorer le projet a partir des retours.","Je laisse l'IA decider a ma place.","Je copie la reponse sans verifier."],
    expected: ["Je sais tester une maquette et ameliorer le projet a partir des retours."],
    comparator: "mcq_exact",
    hint: "Cherche la reponse qui garde methode, jugement et responsabilite humaine.",
    explanation: "Bonne reponse : Je sais tester une maquette et ameliorer le projet a partir des retours.",
  },
  {
    kind: "fixed",
    id: "ia_c1_tester_ameliorer_qcm_002",
    niveau: "c1",
    matiere: "ia",
    notionId: "ia_c1_responsabilite_pitch",
    microId: "ia_c1_tester_ameliorer",
    difficulty: 3,
    text: "Dans une situation reelle, quelle action correspond le mieux a : Je sais tester une maquette et ameliorer le projet a partir des retours.",
    format: "qcm",
    choices: ["Je sais tester une maquette et ameliorer le projet a partir des retours.","Partager des informations sensibles pour aller plus vite.","Faire confiance a une seule reponse sans recul."],
    expected: ["Je sais tester une maquette et ameliorer le projet a partir des retours."],
    comparator: "mcq_exact",
    hint: "L'IA est un outil : l'eleve garde l'objectif, la verification et la decision.",
    explanation: "Cette micro-competence se valide quand l'eleve sait faire ceci : Je sais tester une maquette et ameliorer le projet a partir des retours.",
  },
  {
    kind: "fixed",
    id: "ia_c1_pitch_jury_qcm_001",
    niveau: "c1",
    matiere: "ia",
    notionId: "ia_c1_responsabilite_pitch",
    microId: "ia_c1_pitch_jury",
    difficulty: 3,
    text: "Quelle affirmation valide la micro-competence C1 : Je sais presenter un pitch clair et repondre aux questions d'un jury.",
    format: "qcm",
    choices: ["Je sais presenter un pitch clair et repondre aux questions d'un jury.","Je laisse l'IA decider a ma place.","Je copie la reponse sans verifier."],
    expected: ["Je sais presenter un pitch clair et repondre aux questions d'un jury."],
    comparator: "mcq_exact",
    hint: "Cherche la reponse qui garde methode, jugement et responsabilite humaine.",
    explanation: "Bonne reponse : Je sais presenter un pitch clair et repondre aux questions d'un jury.",
  },
  {
    kind: "fixed",
    id: "ia_c1_pitch_jury_qcm_002",
    niveau: "c1",
    matiere: "ia",
    notionId: "ia_c1_responsabilite_pitch",
    microId: "ia_c1_pitch_jury",
    difficulty: 3,
    text: "Dans une situation reelle, quelle action correspond le mieux a : Je sais presenter un pitch clair et repondre aux questions d'un jury.",
    format: "qcm",
    choices: ["Je sais presenter un pitch clair et repondre aux questions d'un jury.","Partager des informations sensibles pour aller plus vite.","Faire confiance a une seule reponse sans recul."],
    expected: ["Je sais presenter un pitch clair et repondre aux questions d'un jury."],
    comparator: "mcq_exact",
    hint: "L'IA est un outil : l'eleve garde l'objectif, la verification et la decision.",
    explanation: "Cette micro-competence se valide quand l'eleve sait faire ceci : Je sais presenter un pitch clair et repondre aux questions d'un jury.",
  },
];

export function getIaC1QuestionBank(args?: {
  notionId?: string | null;
  microId?: string | null;
}): TutorBankItemV4[] {
  let bank = iaC1QuestionBank;

  if (args?.notionId) bank = bank.filter((item) => item.notionId === args.notionId);
  if (args?.microId) bank = bank.filter((item) => item.microId === args.microId);

  return bank;
}
