// lib/tutor-v4/questionBank/terminale-spe/maths/concentration.bank.ts
//
// Notion : Concentration, loi des grands nombres (concentration_echantillonnage)
//
// microSkills couverts (~10 items chacun, difficultés étalées 1→5) :
//   concentration_echantillon_moyenne      — E(Mₙ)=μ, V(Mₙ)=σ²/n
//   concentration_inegalite_bienayme       — Inégalité de Bienaymé-Tchebychev
//   concentration_inegalite_concentration  — Inégalité de concentration
//   concentration_loi_grands_nombres       — Loi des grands nombres
//   concentration_fluctuation              — Fluctuation d'une fréquence
//   concentration_defi                     — Exercice type bac
//
// Rappels : Mₙ = (X₁+…+Xₙ)/n ; E(Mₙ)=μ ; V(Mₙ)=σ²/n.
//   Bienaymé : P(|X−μ|≥δ) ≤ V(X)/δ². Concentration : P(|Mₙ−μ|≥δ) ≤ σ²/(nδ²).
//   Fréquence : E(Fₙ)=p ; V(Fₙ)=p(1−p)/n.

import type { TutorBankItemV4 } from "@/lib/tutor-v4/types";

function exp(definition: string, methode: string, calcul: string, conclusion: string) {
  return (
    `Définition : ${definition}\n\n` +
    `Méthode : ${methode}\n\n` +
    `Calcul / Observation : ${calcul}\n\n` +
    `Conclusion : ${conclusion}`
  );
}

export const concentrationBank: TutorBankItemV4[] = [
  /* =========================================================
     CONCENTRATION_ECHANTILLON_MOYENNE
  ========================================================= */

  {
    kind: "fixed",
    id: "terminale_spe_conc_moy_fixed_1",
    niveau: "terminale-spe",
    matiere: "maths",
    notionId: "concentration_echantillonnage",
    microId: "concentration_echantillon_moyenne",
    difficulty: 2,
    theme: "neutral",
    text: "Soit $M_n$ la moyenne d'un échantillon de $n$ variables identiques d'espérance $\\mu$. Que vaut $E(M_n)$ ?",
    format: "qcm",
    choices: ["$\\mu$", "$\\dfrac{\\mu}{n}$", "$n\\mu$", "$\\mu^2$"],
    expected: ["$\\mu$"],
    comparator: "mcq_exact",
    hint: "La moyenne d'échantillon a la même espérance que chaque variable.",
    explanation: exp(
      "L'espérance de la moyenne d'échantillon se conserve.",
      "On utilise $E(M_n) = \\mu$.",
      "$E(M_n) = \\mu$, l'espérance commune.",
      "$E(M_n) = \\mu$."
    ),
    tags: ["terminale-spe", "concentration", "echantillon", "qcm"],
  },

  {
    kind: "fixed",
    id: "terminale_spe_conc_moy_fixed_2",
    niveau: "terminale-spe",
    matiere: "maths",
    notionId: "concentration_echantillonnage",
    microId: "concentration_echantillon_moyenne",
    difficulty: 3,
    theme: "neutral",
    text: "Avec les mêmes notations (variance commune $\\sigma^2$), que vaut $V(M_n)$ ?",
    format: "qcm",
    choices: ["$\\dfrac{\\sigma^2}{n}$", "$\\sigma^2$", "$n\\sigma^2$", "$\\dfrac{\\sigma}{n}$"],
    expected: ["$\\dfrac{\\sigma^2}{n}$"],
    comparator: "mcq_exact",
    hint: "La variance de la moyenne diminue avec $n$.",
    explanation: exp(
      "La variance de la moyenne d'échantillon décroît avec la taille.",
      "On utilise $V(M_n) = \\dfrac{\\sigma^2}{n}$.",
      "$V(M_n) = \\dfrac{\\sigma^2}{n}$.",
      "$V(M_n) = \\dfrac{\\sigma^2}{n}$."
    ),
    tags: ["terminale-spe", "concentration", "echantillon", "qcm"],
  },

  {
    kind: "fixed",
    id: "terminale_spe_conc_moy_fixed_3",
    niveau: "terminale-spe",
    matiere: "maths",
    notionId: "concentration_echantillonnage",
    microId: "concentration_echantillon_moyenne",
    difficulty: 3,
    theme: "neutral",
    text: "Si $\\sigma^2 = 9$ et $n = 9$, que vaut $V(M_n)$ ?",
    format: "short",
    expected: ["1"],
    comparator: "number_equal",
    hint: "$V(M_n) = \\dfrac{9}{9}$.",
    explanation: exp(
      "On applique $V(M_n) = \\dfrac{\\sigma^2}{n}$.",
      "$V(M_n) = \\dfrac{9}{9}$.",
      "$= 1$.",
      "$V(M_n) = 1$."
    ),
    tags: ["terminale-spe", "concentration", "echantillon", "short"],
  },

  {
    kind: "fixed",
    id: "terminale_spe_conc_moy_fixed_4",
    niveau: "terminale-spe",
    matiere: "maths",
    notionId: "concentration_echantillonnage",
    microId: "concentration_echantillon_moyenne",
    difficulty: 4,
    theme: "neutral",
    text: "Si $\\sigma^2 = 8$ et $n = 2$, que vaut $V(M_n)$ ?",
    format: "short",
    expected: ["4"],
    comparator: "number_equal",
    hint: "$\\dfrac{8}{2}$.",
    explanation: exp(
      "On applique $V(M_n) = \\dfrac{\\sigma^2}{n}$.",
      "$V(M_n) = \\dfrac{8}{2}$.",
      "$= 4$.",
      "$V(M_n) = 4$."
    ),
    tags: ["terminale-spe", "concentration", "echantillon", "short"],
  },

  {
    kind: "fixed",
    id: "terminale_spe_conc_moy_fixed_5",
    niveau: "terminale-spe",
    matiere: "maths",
    notionId: "concentration_echantillonnage",
    microId: "concentration_echantillon_moyenne",
    difficulty: 3,
    theme: "neutral",
    text: "Quand la taille $n$ de l'échantillon augmente, la variance $V(M_n)$ :",
    format: "qcm",
    choices: ["diminue", "augmente", "reste constante", "devient négative"],
    expected: ["diminue"],
    comparator: "mcq_exact",
    hint: "$V(M_n) = \\dfrac{\\sigma^2}{n}$ : $n$ est au dénominateur.",
    explanation: exp(
      "On observe la dépendance en $n$ de $V(M_n)$.",
      "$V(M_n) = \\dfrac{\\sigma^2}{n}$ : plus $n$ grandit, plus le quotient est petit.",
      "Donc $V(M_n)$ diminue.",
      "La variance $V(M_n)$ diminue."
    ),
    tags: ["terminale-spe", "concentration", "echantillon", "qcm"],
  },

  {
    kind: "fixed",
    id: "terminale_spe_conc_moy_fixed_6",
    niveau: "terminale-spe",
    matiere: "maths",
    notionId: "concentration_echantillonnage",
    microId: "concentration_echantillon_moyenne",
    difficulty: 4,
    theme: "neutral",
    text: "Que vaut l'écart-type $\\sigma(M_n)$ de la moyenne d'échantillon ?",
    format: "qcm",
    choices: ["$\\dfrac{\\sigma}{\\sqrt{n}}$", "$\\dfrac{\\sigma}{n}$", "$\\sigma\\sqrt{n}$", "$\\sigma^2 n$"],
    expected: ["$\\dfrac{\\sigma}{\\sqrt{n}}$"],
    comparator: "mcq_exact",
    hint: "$\\sigma(M_n) = \\sqrt{V(M_n)} = \\sqrt{\\sigma^2/n}$.",
    explanation: exp(
      "L'écart-type est la racine de la variance.",
      "$\\sigma(M_n) = \\sqrt{\\dfrac{\\sigma^2}{n}}$.",
      "$= \\dfrac{\\sigma}{\\sqrt{n}}$.",
      "$\\sigma(M_n) = \\dfrac{\\sigma}{\\sqrt{n}}$."
    ),
    tags: ["terminale-spe", "concentration", "echantillon", "qcm"],
  },

  {
    kind: "fixed",
    id: "terminale_spe_conc_moy_fixed_7",
    niveau: "terminale-spe",
    matiere: "maths",
    notionId: "concentration_echantillonnage",
    microId: "concentration_echantillon_moyenne",
    difficulty: 4,
    theme: "neutral",
    text: "Si $\\sigma^2 = 4$ et $n = 100$, que vaut $V(M_n)$ ?",
    format: "qcm",
    choices: ["$0{,}04$", "$0{,}4$", "$4$", "$25$"],
    expected: ["$0{,}04$"],
    comparator: "mcq_exact",
    hint: "$\\dfrac{4}{100}$.",
    explanation: exp(
      "On applique $V(M_n) = \\dfrac{\\sigma^2}{n}$.",
      "$V(M_n) = \\dfrac{4}{100}$.",
      "$= 0{,}04$.",
      "$V(M_n) = 0{,}04$."
    ),
    tags: ["terminale-spe", "concentration", "echantillon", "qcm"],
  },

  {
    kind: "fixed",
    id: "terminale_spe_conc_moy_fixed_8",
    niveau: "terminale-spe",
    matiere: "maths",
    notionId: "concentration_echantillonnage",
    microId: "concentration_echantillon_moyenne",
    difficulty: 5,
    theme: "neutral",
    text: "Pourquoi $E(M_n) = \\mu$ ne dépend-il pas de $n$, alors que $V(M_n)$ en dépend ?",
    format: "qcm",
    choices: [
      "la moyenne reste centrée sur $\\mu$, mais se concentre quand $n$ grandit",
      "car $\\mu$ change avec $n$",
      "car la variance est toujours nulle",
      "c'est une erreur, les deux dépendent de $n$",
    ],
    expected: ["la moyenne reste centrée sur $\\mu$, mais se concentre quand $n$ grandit"],
    comparator: "mcq_exact",
    hint: "L'espérance = centre ; la variance = dispersion.",
    explanation: exp(
      "L'espérance situe le centre, la variance mesure la dispersion.",
      "$M_n$ reste centrée sur $\\mu$ (espérance constante).",
      "Mais sa dispersion $V(M_n) = \\sigma^2/n$ diminue : elle se concentre autour de $\\mu$.",
      "$M_n$ reste centrée sur $\\mu$ et se concentre quand $n$ grandit."
    ),
    tags: ["terminale-spe", "concentration", "echantillon", "qcm"],
  },

  {
    kind: "fixed",
    id: "terminale_spe_conc_moy_fixed_9",
    niveau: "terminale-spe",
    matiere: "maths",
    notionId: "concentration_echantillonnage",
    microId: "concentration_echantillon_moyenne",
    difficulty: 3,
    theme: "neutral",
    text: "Si $\\sigma^2 = 12$ et $n = 3$, que vaut $V(M_n)$ ?",
    format: "short",
    expected: ["4"],
    comparator: "number_equal",
    hint: "$\\dfrac{12}{3}$.",
    explanation: exp(
      "On applique $V(M_n) = \\dfrac{\\sigma^2}{n}$.",
      "$V(M_n) = \\dfrac{12}{3}$.",
      "$= 4$.",
      "$V(M_n) = 4$."
    ),
    tags: ["terminale-spe", "concentration", "echantillon", "short"],
  },

  {
    kind: "fixed",
    id: "terminale_spe_conc_moy_fixed_10",
    niveau: "terminale-spe",
    matiere: "maths",
    notionId: "concentration_echantillonnage",
    microId: "concentration_echantillon_moyenne",
    difficulty: 4,
    theme: "neutral",
    text: "Un échantillon de $n = 25$ variables de variance $\\sigma^2 = 5$. Que vaut $V(M_n)$ ?",
    format: "qcm",
    choices: ["$0{,}2$", "$5$", "$125$", "$0{,}04$"],
    expected: ["$0{,}2$"],
    comparator: "mcq_exact",
    hint: "$\\dfrac{5}{25}$.",
    explanation: exp(
      "On applique $V(M_n) = \\dfrac{\\sigma^2}{n}$.",
      "$V(M_n) = \\dfrac{5}{25}$.",
      "$= 0{,}2$.",
      "$V(M_n) = 0{,}2$."
    ),
    tags: ["terminale-spe", "concentration", "echantillon", "qcm"],
  },

  /* =========================================================
     CONCENTRATION_INEGALITE_BIENAYME
  ========================================================= */

  {
    kind: "fixed",
    id: "terminale_spe_conc_bien_fixed_1",
    niveau: "terminale-spe",
    matiere: "maths",
    notionId: "concentration_echantillonnage",
    microId: "concentration_inegalite_bienayme",
    difficulty: 2,
    theme: "neutral",
    text: "Quelle est l'inégalité de Bienaymé-Tchebychev pour une variable $X$ ?",
    format: "qcm",
    choices: [
      "$P(|X - \\mu| \\ge \\delta) \\le \\dfrac{V(X)}{\\delta^2}$",
      "$P(|X - \\mu| \\ge \\delta) \\le \\dfrac{V(X)}{\\delta}$",
      "$P(|X - \\mu| \\ge \\delta) \\ge \\dfrac{V(X)}{\\delta^2}$",
      "$P(|X - \\mu| \\ge \\delta) = V(X)\\delta^2$",
    ],
    expected: ["$P(|X - \\mu| \\ge \\delta) \\le \\dfrac{V(X)}{\\delta^2}$"],
    comparator: "mcq_exact",
    hint: "Variance divisée par $\\delta$ au carré, et c'est un majorant.",
    explanation: exp(
      "L'inégalité de Bienaymé-Tchebychev majore une probabilité d'écart.",
      "On retient la formule du cours.",
      "$P(|X - \\mu| \\ge \\delta) \\le \\dfrac{V(X)}{\\delta^2}$.",
      "C'est $P(|X - \\mu| \\ge \\delta) \\le \\dfrac{V(X)}{\\delta^2}$."
    ),
    tags: ["terminale-spe", "concentration", "bienayme", "qcm"],
  },

  {
    kind: "fixed",
    id: "terminale_spe_conc_bien_fixed_2",
    niveau: "terminale-spe",
    matiere: "maths",
    notionId: "concentration_echantillonnage",
    microId: "concentration_inegalite_bienayme",
    difficulty: 3,
    theme: "neutral",
    text: "Avec $V(X) = 4$ et $\\delta = 2$, quel majorant donne Bienaymé-Tchebychev pour $P(|X - \\mu| \\ge 2)$ ?",
    format: "short",
    expected: ["1"],
    comparator: "number_equal",
    hint: "$\\dfrac{V(X)}{\\delta^2} = \\dfrac{4}{4}$.",
    explanation: exp(
      "On applique $\\dfrac{V(X)}{\\delta^2}$.",
      "$\\dfrac{4}{2^2} = \\dfrac{4}{4}$.",
      "$= 1$.",
      "Le majorant est $1$ (peu informatif ici, mais valide)."
    ),
    tags: ["terminale-spe", "concentration", "bienayme", "short"],
  },

  {
    kind: "fixed",
    id: "terminale_spe_conc_bien_fixed_3",
    niveau: "terminale-spe",
    matiere: "maths",
    notionId: "concentration_echantillonnage",
    microId: "concentration_inegalite_bienayme",
    difficulty: 4,
    theme: "neutral",
    text: "Avec $V(X) = 1$ et $\\delta = 2$, quel majorant donne Bienaymé-Tchebychev pour $P(|X - \\mu| \\ge 2)$ ?",
    format: "qcm",
    choices: ["$0{,}25$", "$0{,}5$", "$2$", "$1$"],
    expected: ["$0{,}25$"],
    comparator: "mcq_exact",
    hint: "$\\dfrac{1}{2^2} = \\dfrac{1}{4}$.",
    explanation: exp(
      "On applique $\\dfrac{V(X)}{\\delta^2}$.",
      "$\\dfrac{1}{4}$.",
      "$= 0{,}25$.",
      "Le majorant est $0{,}25$."
    ),
    tags: ["terminale-spe", "concentration", "bienayme", "qcm"],
  },

  {
    kind: "fixed",
    id: "terminale_spe_conc_bien_fixed_4",
    niveau: "terminale-spe",
    matiere: "maths",
    notionId: "concentration_echantillonnage",
    microId: "concentration_inegalite_bienayme",
    difficulty: 3,
    theme: "neutral",
    text: "L'inégalité de Bienaymé-Tchebychev fournit, sur une probabilité, un :",
    format: "qcm",
    choices: ["majorant (borne supérieure)", "minorant", "valeur exacte", "intervalle de confiance"],
    expected: ["majorant (borne supérieure)"],
    comparator: "mcq_exact",
    hint: "Le symbole est $\\le$.",
    explanation: exp(
      "L'inégalité encadre la probabilité par le haut.",
      "$P(\\dots) \\le \\dfrac{V(X)}{\\delta^2}$ : c'est une borne supérieure.",
      "Elle ne donne pas la valeur exacte.",
      "Elle fournit un majorant."
    ),
    tags: ["terminale-spe", "concentration", "bienayme", "qcm"],
  },

  {
    kind: "fixed",
    id: "terminale_spe_conc_bien_fixed_5",
    niveau: "terminale-spe",
    matiere: "maths",
    notionId: "concentration_echantillonnage",
    microId: "concentration_inegalite_bienayme",
    difficulty: 4,
    theme: "neutral",
    text: "Avec $V(X) = 9$ et $\\delta = 3$, quel majorant pour $P(|X - \\mu| \\ge 3)$ ?",
    format: "short",
    expected: ["1"],
    comparator: "number_equal",
    hint: "$\\dfrac{9}{3^2}$.",
    explanation: exp(
      "On applique $\\dfrac{V(X)}{\\delta^2}$.",
      "$\\dfrac{9}{9}$.",
      "$= 1$.",
      "Le majorant est $1$."
    ),
    tags: ["terminale-spe", "concentration", "bienayme", "short"],
  },

  {
    kind: "fixed",
    id: "terminale_spe_conc_bien_fixed_6",
    niveau: "terminale-spe",
    matiere: "maths",
    notionId: "concentration_echantillonnage",
    microId: "concentration_inegalite_bienayme",
    difficulty: 4,
    theme: "neutral",
    text: "Avec $V(X) = 2$ et $\\delta = 2$, quel majorant pour $P(|X - \\mu| \\ge 2)$ ?",
    format: "qcm",
    choices: ["$0{,}5$", "$1$", "$0{,}25$", "$4$"],
    expected: ["$0{,}5$"],
    comparator: "mcq_exact",
    hint: "$\\dfrac{2}{4}$.",
    explanation: exp(
      "On applique $\\dfrac{V(X)}{\\delta^2}$.",
      "$\\dfrac{2}{4}$.",
      "$= 0{,}5$.",
      "Le majorant est $0{,}5$."
    ),
    tags: ["terminale-spe", "concentration", "bienayme", "qcm"],
  },

  {
    kind: "fixed",
    id: "terminale_spe_conc_bien_fixed_7",
    niveau: "terminale-spe",
    matiere: "maths",
    notionId: "concentration_echantillonnage",
    microId: "concentration_inegalite_bienayme",
    difficulty: 5,
    theme: "neutral",
    text: "Que se passe-t-il pour le majorant $\\dfrac{V(X)}{\\delta^2}$ quand $\\delta$ augmente ?",
    format: "qcm",
    choices: [
      "il diminue (les grands écarts sont plus rares)",
      "il augmente",
      "il reste constant",
      "il devient négatif",
    ],
    expected: ["il diminue (les grands écarts sont plus rares)"],
    comparator: "mcq_exact",
    hint: "$\\delta$ est au dénominateur (au carré).",
    explanation: exp(
      "On étudie la dépendance du majorant en $\\delta$.",
      "$\\dfrac{V(X)}{\\delta^2}$ décroît quand $\\delta$ augmente.",
      "Les écarts de plus en plus grands sont de plus en plus improbables.",
      "Le majorant diminue."
    ),
    tags: ["terminale-spe", "concentration", "bienayme", "qcm"],
  },

  {
    kind: "fixed",
    id: "terminale_spe_conc_bien_fixed_8",
    niveau: "terminale-spe",
    matiere: "maths",
    notionId: "concentration_echantillonnage",
    microId: "concentration_inegalite_bienayme",
    difficulty: 3,
    theme: "neutral",
    text: "Avec $V(X) = 5$ et $\\delta = 5$, quel majorant pour $P(|X - \\mu| \\ge 5)$ ?",
    format: "qcm",
    choices: ["$0{,}2$", "$1$", "$5$", "$0{,}04$"],
    expected: ["$0{,}2$"],
    comparator: "mcq_exact",
    hint: "$\\dfrac{5}{25}$.",
    explanation: exp(
      "On applique $\\dfrac{V(X)}{\\delta^2}$.",
      "$\\dfrac{5}{5^2} = \\dfrac{5}{25}$.",
      "$= 0{,}2$.",
      "Le majorant est $0{,}2$."
    ),
    tags: ["terminale-spe", "concentration", "bienayme", "qcm"],
  },

  {
    kind: "fixed",
    id: "terminale_spe_conc_bien_fixed_9",
    niveau: "terminale-spe",
    matiere: "maths",
    notionId: "concentration_echantillonnage",
    microId: "concentration_inegalite_bienayme",
    difficulty: 5,
    theme: "neutral",
    text: "À quoi sert principalement l'inégalité de Bienaymé-Tchebychev ?",
    format: "qcm",
    choices: [
      "majorer la probabilité de s'écarter de la moyenne",
      "calculer une dérivée",
      "résoudre une équation différentielle",
      "tracer une courbe",
    ],
    expected: ["majorer la probabilité de s'écarter de la moyenne"],
    comparator: "mcq_exact",
    hint: "Elle borne $P(|X - \\mu| \\ge \\delta)$.",
    explanation: exp(
      "L'inégalité contrôle les écarts à la moyenne.",
      "Elle majore $P(|X - \\mu| \\ge \\delta)$ par $\\dfrac{V(X)}{\\delta^2}$.",
      "Elle sert donc à borner la probabilité d'un grand écart.",
      "Elle sert à majorer la probabilité de s'écarter de la moyenne."
    ),
    tags: ["terminale-spe", "concentration", "bienayme", "qcm"],
  },

  {
    kind: "fixed",
    id: "terminale_spe_conc_bien_fixed_10",
    niveau: "terminale-spe",
    matiere: "maths",
    notionId: "concentration_echantillonnage",
    microId: "concentration_inegalite_bienayme",
    difficulty: 4,
    theme: "neutral",
    text: "Avec $V(X) = 1$ et $\\delta = 5$, quel majorant pour $P(|X - \\mu| \\ge 5)$ ?",
    format: "qcm",
    choices: ["$0{,}04$", "$0{,}2$", "$0{,}25$", "$1$"],
    expected: ["$0{,}04$"],
    comparator: "mcq_exact",
    hint: "$\\dfrac{1}{25}$.",
    explanation: exp(
      "On applique $\\dfrac{V(X)}{\\delta^2}$.",
      "$\\dfrac{1}{25}$.",
      "$= 0{,}04$.",
      "Le majorant est $0{,}04$."
    ),
    tags: ["terminale-spe", "concentration", "bienayme", "qcm"],
  },

  /* =========================================================
     CONCENTRATION_INEGALITE_CONCENTRATION
  ========================================================= */

  {
    kind: "fixed",
    id: "terminale_spe_conc_conc_fixed_1",
    niveau: "terminale-spe",
    matiere: "maths",
    notionId: "concentration_echantillonnage",
    microId: "concentration_inegalite_concentration",
    difficulty: 3,
    theme: "neutral",
    text: "Quelle est l'inégalité de concentration pour la moyenne $M_n$ ?",
    format: "qcm",
    choices: [
      "$P(|M_n - \\mu| \\ge \\delta) \\le \\dfrac{\\sigma^2}{n\\delta^2}$",
      "$P(|M_n - \\mu| \\ge \\delta) \\le \\dfrac{\\sigma^2}{\\delta^2}$",
      "$P(|M_n - \\mu| \\ge \\delta) \\le \\dfrac{n\\sigma^2}{\\delta^2}$",
      "$P(|M_n - \\mu| \\ge \\delta) = \\dfrac{\\sigma^2}{n}$",
    ],
    expected: ["$P(|M_n - \\mu| \\ge \\delta) \\le \\dfrac{\\sigma^2}{n\\delta^2}$"],
    comparator: "mcq_exact",
    hint: "C'est Bienaymé appliqué à $M_n$, dont la variance est $\\sigma^2/n$.",
    explanation: exp(
      "On applique Bienaymé-Tchebychev à $M_n$, de variance $\\dfrac{\\sigma^2}{n}$.",
      "$P(|M_n - \\mu| \\ge \\delta) \\le \\dfrac{V(M_n)}{\\delta^2} = \\dfrac{\\sigma^2/n}{\\delta^2}$.",
      "$= \\dfrac{\\sigma^2}{n\\delta^2}$.",
      "C'est $P(|M_n - \\mu| \\ge \\delta) \\le \\dfrac{\\sigma^2}{n\\delta^2}$."
    ),
    tags: ["terminale-spe", "concentration", "concentration", "qcm"],
  },

  {
    kind: "fixed",
    id: "terminale_spe_conc_conc_fixed_2",
    niveau: "terminale-spe",
    matiere: "maths",
    notionId: "concentration_echantillonnage",
    microId: "concentration_inegalite_concentration",
    difficulty: 4,
    theme: "neutral",
    text: "Avec $\\sigma^2 = 0{,}25$, $n = 100$, $\\delta = 0{,}1$, quel majorant pour $P(|M_n - \\mu| \\ge 0{,}1)$ ?",
    format: "qcm",
    choices: ["$0{,}25$", "$1$", "$0{,}025$", "$2{,}5$"],
    expected: ["$0{,}25$"],
    comparator: "mcq_exact",
    hint: "$\\dfrac{0{,}25}{100 \\times 0{,}01}$.",
    explanation: exp(
      "On applique $\\dfrac{\\sigma^2}{n\\delta^2}$.",
      "$\\dfrac{0{,}25}{100 \\times 0{,}1^2} = \\dfrac{0{,}25}{100 \\times 0{,}01} = \\dfrac{0{,}25}{1}$.",
      "$= 0{,}25$.",
      "Le majorant est $0{,}25$."
    ),
    tags: ["terminale-spe", "concentration", "concentration", "qcm"],
  },

  {
    kind: "fixed",
    id: "terminale_spe_conc_conc_fixed_3",
    niveau: "terminale-spe",
    matiere: "maths",
    notionId: "concentration_echantillonnage",
    microId: "concentration_inegalite_concentration",
    difficulty: 4,
    theme: "neutral",
    text: "Avec $\\sigma^2 = 4$, $n = 400$, $\\delta = 1$, quel majorant pour $P(|M_n - \\mu| \\ge 1)$ ?",
    format: "qcm",
    choices: ["$0{,}01$", "$0{,}1$", "$1$", "$0{,}04$"],
    expected: ["$0{,}01$"],
    comparator: "mcq_exact",
    hint: "$\\dfrac{4}{400 \\times 1}$.",
    explanation: exp(
      "On applique $\\dfrac{\\sigma^2}{n\\delta^2}$.",
      "$\\dfrac{4}{400 \\times 1^2} = \\dfrac{4}{400}$.",
      "$= 0{,}01$.",
      "Le majorant est $0{,}01$."
    ),
    tags: ["terminale-spe", "concentration", "concentration", "qcm"],
  },

  {
    kind: "fixed",
    id: "terminale_spe_conc_conc_fixed_4",
    niveau: "terminale-spe",
    matiere: "maths",
    notionId: "concentration_echantillonnage",
    microId: "concentration_inegalite_concentration",
    difficulty: 4,
    theme: "neutral",
    text: "Dans le majorant $\\dfrac{\\sigma^2}{n\\delta^2}$, que se passe-t-il quand $n$ augmente ?",
    format: "qcm",
    choices: [
      "le majorant diminue (la moyenne se concentre)",
      "le majorant augmente",
      "rien ne change",
      "le majorant devient négatif",
    ],
    expected: ["le majorant diminue (la moyenne se concentre)"],
    comparator: "mcq_exact",
    hint: "$n$ est au dénominateur.",
    explanation: exp(
      "On observe la dépendance en $n$.",
      "$\\dfrac{\\sigma^2}{n\\delta^2}$ décroît quand $n$ augmente.",
      "La probabilité d'écart diminue : $M_n$ se concentre autour de $\\mu$.",
      "Le majorant diminue."
    ),
    tags: ["terminale-spe", "concentration", "concentration", "qcm"],
  },

  {
    kind: "fixed",
    id: "terminale_spe_conc_conc_fixed_5",
    niveau: "terminale-spe",
    matiere: "maths",
    notionId: "concentration_echantillonnage",
    microId: "concentration_inegalite_concentration",
    difficulty: 5,
    theme: "neutral",
    text: "Avec $\\sigma^2 = 1$, $n = 25$, $\\delta = 0{,}2$, quel majorant pour $P(|M_n - \\mu| \\ge 0{,}2)$ ?",
    format: "qcm",
    choices: ["$1$", "$0{,}25$", "$0{,}04$", "$4$"],
    expected: ["$1$"],
    comparator: "mcq_exact",
    hint: "$\\dfrac{1}{25 \\times 0{,}04}$.",
    explanation: exp(
      "On applique $\\dfrac{\\sigma^2}{n\\delta^2}$.",
      "$\\dfrac{1}{25 \\times 0{,}2^2} = \\dfrac{1}{25 \\times 0{,}04} = \\dfrac{1}{1}$.",
      "$= 1$.",
      "Le majorant est $1$ (ici non informatif)."
    ),
    tags: ["terminale-spe", "concentration", "concentration", "qcm"],
  },

  {
    kind: "fixed",
    id: "terminale_spe_conc_conc_fixed_6",
    niveau: "terminale-spe",
    matiere: "maths",
    notionId: "concentration_echantillonnage",
    microId: "concentration_inegalite_concentration",
    difficulty: 3,
    theme: "neutral",
    text: "L'inégalité de concentration s'obtient en appliquant Bienaymé-Tchebychev à :",
    format: "qcm",
    choices: ["la moyenne $M_n$", "une seule variable $X$", "la variance", "l'écart-type"],
    expected: ["la moyenne $M_n$"],
    comparator: "mcq_exact",
    hint: "On remplace $X$ par $M_n$ et $V(X)$ par $V(M_n)$.",
    explanation: exp(
      "L'inégalité de concentration est un cas particulier de Bienaymé.",
      "On l'applique à la variable $M_n$, de variance $\\dfrac{\\sigma^2}{n}$.",
      "On obtient $P(|M_n - \\mu| \\ge \\delta) \\le \\dfrac{\\sigma^2}{n\\delta^2}$.",
      "On l'applique à la moyenne $M_n$."
    ),
    tags: ["terminale-spe", "concentration", "concentration", "qcm"],
  },

  {
    kind: "fixed",
    id: "terminale_spe_conc_conc_fixed_7",
    niveau: "terminale-spe",
    matiere: "maths",
    notionId: "concentration_echantillonnage",
    microId: "concentration_inegalite_concentration",
    difficulty: 5,
    theme: "neutral",
    text: "Avec $\\sigma^2 = 2$, $n = 200$, $\\delta = 0{,}1$, quel majorant pour $P(|M_n - \\mu| \\ge 0{,}1)$ ?",
    format: "qcm",
    choices: ["$1$", "$0{,}5$", "$0{,}1$", "$2$"],
    expected: ["$1$"],
    comparator: "mcq_exact",
    hint: "$\\dfrac{2}{200 \\times 0{,}01}$.",
    explanation: exp(
      "On applique $\\dfrac{\\sigma^2}{n\\delta^2}$.",
      "$\\dfrac{2}{200 \\times 0{,}01} = \\dfrac{2}{2}$.",
      "$= 1$.",
      "Le majorant est $1$."
    ),
    tags: ["terminale-spe", "concentration", "concentration", "qcm"],
  },

  {
    kind: "fixed",
    id: "terminale_spe_conc_conc_fixed_8",
    niveau: "terminale-spe",
    matiere: "maths",
    notionId: "concentration_echantillonnage",
    microId: "concentration_inegalite_concentration",
    difficulty: 4,
    theme: "neutral",
    text: "Pour rendre $P(|M_n - \\mu| \\ge \\delta)$ aussi petite qu'on veut, on peut :",
    format: "qcm",
    choices: [
      "augmenter la taille $n$ de l'échantillon",
      "diminuer $n$",
      "diminuer $\\delta$ seulement",
      "rien, c'est impossible",
    ],
    expected: ["augmenter la taille $n$ de l'échantillon"],
    comparator: "mcq_exact",
    hint: "Le majorant $\\dfrac{\\sigma^2}{n\\delta^2}$ tend vers 0 quand $n \\to +\\infty$.",
    explanation: exp(
      "Le majorant dépend de $n$ au dénominateur.",
      "En augmentant $n$, $\\dfrac{\\sigma^2}{n\\delta^2} \\to 0$.",
      "La probabilité d'écart devient aussi petite que voulu.",
      "On augmente la taille $n$ de l'échantillon."
    ),
    tags: ["terminale-spe", "concentration", "concentration", "qcm"],
  },

  {
    kind: "fixed",
    id: "terminale_spe_conc_conc_fixed_9",
    niveau: "terminale-spe",
    matiere: "maths",
    notionId: "concentration_echantillonnage",
    microId: "concentration_inegalite_concentration",
    difficulty: 5,
    theme: "neutral",
    text: "Avec $\\sigma^2 = 0{,}25$, $n = 2500$, $\\delta = 0{,}1$, quel majorant pour $P(|M_n - \\mu| \\ge 0{,}1)$ ?",
    format: "qcm",
    choices: ["$0{,}01$", "$0{,}1$", "$1$", "$0{,}25$"],
    expected: ["$0{,}01$"],
    comparator: "mcq_exact",
    hint: "$\\dfrac{0{,}25}{2500 \\times 0{,}01}$.",
    explanation: exp(
      "On applique $\\dfrac{\\sigma^2}{n\\delta^2}$.",
      "$\\dfrac{0{,}25}{2500 \\times 0{,}01} = \\dfrac{0{,}25}{25}$.",
      "$= 0{,}01$.",
      "Le majorant est $0{,}01$."
    ),
    tags: ["terminale-spe", "concentration", "concentration", "qcm"],
  },

  {
    kind: "fixed",
    id: "terminale_spe_conc_conc_fixed_10",
    niveau: "terminale-spe",
    matiere: "maths",
    notionId: "concentration_echantillonnage",
    microId: "concentration_inegalite_concentration",
    difficulty: 4,
    theme: "neutral",
    text: "Avec $\\sigma^2 = 9$, $n = 100$, $\\delta = 3$, quel majorant pour $P(|M_n - \\mu| \\ge 3)$ ?",
    format: "qcm",
    choices: ["$0{,}01$", "$0{,}1$", "$1$", "$0{,}09$"],
    expected: ["$0{,}01$"],
    comparator: "mcq_exact",
    hint: "$\\dfrac{9}{100 \\times 9}$.",
    explanation: exp(
      "On applique $\\dfrac{\\sigma^2}{n\\delta^2}$.",
      "$\\dfrac{9}{100 \\times 3^2} = \\dfrac{9}{900}$.",
      "$= 0{,}01$.",
      "Le majorant est $0{,}01$."
    ),
    tags: ["terminale-spe", "concentration", "concentration", "qcm"],
  },

  /* =========================================================
     CONCENTRATION_LOI_GRANDS_NOMBRES
  ========================================================= */

  {
    kind: "fixed",
    id: "terminale_spe_conc_lgn_fixed_1",
    niveau: "terminale-spe",
    matiere: "maths",
    notionId: "concentration_echantillonnage",
    microId: "concentration_loi_grands_nombres",
    difficulty: 2,
    theme: "neutral",
    text: "Que dit la loi des grands nombres pour la moyenne $M_n$ d'un échantillon ?",
    format: "qcm",
    choices: [
      "$M_n$ se rapproche de $\\mu$ quand $n$ devient grand",
      "$M_n$ s'éloigne de $\\mu$",
      "$M_n$ est toujours égale à $\\mu$",
      "$M_n$ devient nulle",
    ],
    expected: ["$M_n$ se rapproche de $\\mu$ quand $n$ devient grand"],
    comparator: "mcq_exact",
    hint: "La moyenne se stabilise sur l'espérance.",
    explanation: exp(
      "La loi des grands nombres relie moyenne observée et espérance.",
      "Quand $n$ grandit, $M_n$ se concentre autour de $\\mu$.",
      "$M_n$ se rapproche de $\\mu$.",
      "$M_n$ se rapproche de $\\mu$ quand $n$ devient grand."
    ),
    tags: ["terminale-spe", "concentration", "lgn", "qcm"],
  },

  {
    kind: "fixed",
    id: "terminale_spe_conc_lgn_fixed_2",
    niveau: "terminale-spe",
    matiere: "maths",
    notionId: "concentration_echantillonnage",
    microId: "concentration_loi_grands_nombres",
    difficulty: 3,
    theme: "neutral",
    text: "D'après la loi des grands nombres, pour tout $\\delta > 0$, $P(|M_n - \\mu| \\ge \\delta)$ :",
    format: "qcm",
    choices: ["tend vers $0$ quand $n \\to +\\infty$", "tend vers $1$", "reste constante", "tend vers $\\mu$"],
    expected: ["tend vers $0$ quand $n \\to +\\infty$"],
    comparator: "mcq_exact",
    hint: "C'est la conséquence de l'inégalité de concentration.",
    explanation: exp(
      "On utilise l'inégalité de concentration et la limite.",
      "$P(|M_n - \\mu| \\ge \\delta) \\le \\dfrac{\\sigma^2}{n\\delta^2} \\to 0$.",
      "Donc la probabilité d'écart tend vers $0$.",
      "$P(|M_n - \\mu| \\ge \\delta) \\to 0$."
    ),
    tags: ["terminale-spe", "concentration", "lgn", "qcm"],
  },

  {
    kind: "fixed",
    id: "terminale_spe_conc_lgn_fixed_3",
    niveau: "terminale-spe",
    matiere: "maths",
    notionId: "concentration_echantillonnage",
    microId: "concentration_loi_grands_nombres",
    difficulty: 3,
    theme: "neutral",
    text: "En lançant un dé équilibré un très grand nombre de fois, la moyenne des résultats se rapproche de :",
    format: "qcm",
    choices: ["$3{,}5$", "$6$", "$1$", "$0$"],
    expected: ["$3{,}5$"],
    comparator: "mcq_exact",
    hint: "C'est l'espérance d'un dé.",
    explanation: exp(
      "La loi des grands nombres : la moyenne tend vers l'espérance.",
      "Pour un dé, $E(X) = 3{,}5$.",
      "La moyenne observée se rapproche de $3{,}5$.",
      "Elle se rapproche de $3{,}5$."
    ),
    tags: ["terminale-spe", "concentration", "lgn", "qcm"],
  },

  {
    kind: "fixed",
    id: "terminale_spe_conc_lgn_fixed_4",
    niveau: "terminale-spe",
    matiere: "maths",
    notionId: "concentration_echantillonnage",
    microId: "concentration_loi_grands_nombres",
    difficulty: 4,
    theme: "neutral",
    text: "La loi des grands nombres justifie qu'on estime une probabilité par :",
    format: "qcm",
    choices: [
      "la fréquence observée sur un grand échantillon",
      "une seule observation",
      "la variance",
      "l'écart-type",
    ],
    expected: ["la fréquence observée sur un grand échantillon"],
    comparator: "mcq_exact",
    hint: "Fréquence ≈ probabilité pour $n$ grand.",
    explanation: exp(
      "La loi des grands nombres relie fréquence et probabilité.",
      "Sur un grand échantillon, la fréquence se stabilise sur la probabilité.",
      "On peut donc estimer une probabilité par une fréquence observée.",
      "Par la fréquence observée sur un grand échantillon."
    ),
    tags: ["terminale-spe", "concentration", "lgn", "qcm"],
  },

  {
    kind: "fixed",
    id: "terminale_spe_conc_lgn_fixed_5",
    niveau: "terminale-spe",
    matiere: "maths",
    notionId: "concentration_echantillonnage",
    microId: "concentration_loi_grands_nombres",
    difficulty: 4,
    theme: "neutral",
    text: "La loi des grands nombres garantit-elle que $M_n$ soit EXACTEMENT égale à $\\mu$ pour $n$ grand ?",
    format: "qcm",
    choices: [
      "Non, elle s'en rapproche seulement (avec forte probabilité)",
      "Oui, exactement",
      "Oui, dès $n = 10$",
      "Non, $M_n$ s'en éloigne",
    ],
    expected: ["Non, elle s'en rapproche seulement (avec forte probabilité)"],
    comparator: "mcq_exact",
    hint: "C'est un résultat de probabilité, pas une égalité.",
    explanation: exp(
      "La loi des grands nombres est un énoncé probabiliste.",
      "$M_n$ reste aléatoire ; elle se concentre autour de $\\mu$.",
      "On a une forte probabilité d'être proche, pas une égalité exacte.",
      "Non, $M_n$ se rapproche de $\\mu$ avec forte probabilité."
    ),
    tags: ["terminale-spe", "concentration", "lgn", "qcm"],
  },

  {
    kind: "fixed",
    id: "terminale_spe_conc_lgn_fixed_6",
    niveau: "terminale-spe",
    matiere: "maths",
    notionId: "concentration_echantillonnage",
    microId: "concentration_loi_grands_nombres",
    difficulty: 3,
    theme: "neutral",
    text: "En lançant une pièce équilibrée un grand nombre de fois, la fréquence de « pile » se rapproche de :",
    format: "qcm",
    choices: ["$0{,}5$", "$1$", "$0$", "$0{,}25$"],
    expected: ["$0{,}5$"],
    comparator: "mcq_exact",
    hint: "$P(\\text{pile}) = 0{,}5$.",
    explanation: exp(
      "La fréquence tend vers la probabilité théorique.",
      "Pour une pièce équilibrée, $P(\\text{pile}) = 0{,}5$.",
      "La fréquence se rapproche de $0{,}5$.",
      "Elle se rapproche de $0{,}5$."
    ),
    tags: ["terminale-spe", "concentration", "lgn", "qcm"],
  },

  {
    kind: "fixed",
    id: "terminale_spe_conc_lgn_fixed_7",
    niveau: "terminale-spe",
    matiere: "maths",
    notionId: "concentration_echantillonnage",
    microId: "concentration_loi_grands_nombres",
    difficulty: 5,
    theme: "neutral",
    text: "La loi des grands nombres est une conséquence directe de :",
    format: "qcm",
    choices: [
      "l'inégalité de concentration",
      "la dérivation",
      "le théorème des valeurs intermédiaires",
      "la formule du binôme",
    ],
    expected: ["l'inégalité de concentration"],
    comparator: "mcq_exact",
    hint: "Le majorant $\\sigma^2/(n\\delta^2)$ tend vers 0.",
    explanation: exp(
      "On déduit la loi des grands nombres d'une majoration.",
      "L'inégalité de concentration donne $P(|M_n-\\mu|\\ge\\delta) \\le \\dfrac{\\sigma^2}{n\\delta^2}$.",
      "Ce majorant tend vers $0$, d'où la loi des grands nombres.",
      "C'est une conséquence de l'inégalité de concentration."
    ),
    tags: ["terminale-spe", "concentration", "lgn", "qcm"],
  },

  {
    kind: "fixed",
    id: "terminale_spe_conc_lgn_fixed_8",
    niveau: "terminale-spe",
    matiere: "maths",
    notionId: "concentration_echantillonnage",
    microId: "concentration_loi_grands_nombres",
    difficulty: 4,
    theme: "neutral",
    text: "Pourquoi un sondage sur 1000 personnes est-il plus fiable qu'un sondage sur 10 personnes ?",
    format: "qcm",
    choices: [
      "car la fréquence se concentre autour de la vraie proportion quand $n$ augmente",
      "car 1000 est un nombre rond",
      "car la variance augmente",
      "ce n'est pas plus fiable",
    ],
    expected: ["car la fréquence se concentre autour de la vraie proportion quand $n$ augmente"],
    comparator: "mcq_exact",
    hint: "Loi des grands nombres + concentration.",
    explanation: exp(
      "La fiabilité augmente avec la taille de l'échantillon.",
      "Quand $n$ grandit, la fréquence se concentre autour de la vraie proportion.",
      "Un grand $n$ réduit la fluctuation d'échantillonnage.",
      "Car la fréquence se concentre autour de la vraie proportion quand $n$ augmente."
    ),
    tags: ["terminale-spe", "concentration", "lgn", "qcm"],
  },

  {
    kind: "fixed",
    id: "terminale_spe_conc_lgn_fixed_9",
    niveau: "terminale-spe",
    matiere: "maths",
    notionId: "concentration_echantillonnage",
    microId: "concentration_loi_grands_nombres",
    difficulty: 3,
    theme: "neutral",
    text: "La loi des grands nombres concerne le comportement de $M_n$ lorsque :",
    format: "qcm",
    choices: ["$n$ tend vers $+\\infty$", "$n = 1$", "$\\delta$ tend vers $+\\infty$", "$\\mu = 0$"],
    expected: ["$n$ tend vers $+\\infty$"],
    comparator: "mcq_exact",
    hint: "« Grands nombres » = grande taille d'échantillon.",
    explanation: exp(
      "Le nom indique le régime concerné.",
      "On s'intéresse au comportement pour $n$ très grand.",
      "$n \\to +\\infty$.",
      "Elle concerne $n \\to +\\infty$."
    ),
    tags: ["terminale-spe", "concentration", "lgn", "qcm"],
  },

  {
    kind: "fixed",
    id: "terminale_spe_conc_lgn_fixed_10",
    niveau: "terminale-spe",
    matiere: "maths",
    notionId: "concentration_echantillonnage",
    microId: "concentration_loi_grands_nombres",
    difficulty: 5,
    theme: "neutral",
    text: "Un casino gagne « en moyenne » à long terme grâce à un léger avantage par partie. Quel principe l'explique ?",
    format: "qcm",
    choices: [
      "la loi des grands nombres (la moyenne des gains se stabilise sur l'espérance)",
      "la dérivation",
      "le théorème de Pascal",
      "la convexité",
    ],
    expected: ["la loi des grands nombres (la moyenne des gains se stabilise sur l'espérance)"],
    comparator: "mcq_exact",
    hint: "Sur un très grand nombre de parties, la moyenne tend vers $E$.",
    explanation: exp(
      "Sur un grand nombre de parties, la moyenne des gains se stabilise.",
      "Elle tend vers l'espérance de gain par partie (favorable au casino).",
      "C'est la loi des grands nombres.",
      "C'est la loi des grands nombres."
    ),
    tags: ["terminale-spe", "concentration", "lgn", "qcm"],
  },

  /* =========================================================
     CONCENTRATION_FLUCTUATION
  ========================================================= */

  {
    kind: "fixed",
    id: "terminale_spe_conc_fluc_fixed_1",
    niveau: "terminale-spe",
    matiere: "maths",
    notionId: "concentration_echantillonnage",
    microId: "concentration_fluctuation",
    difficulty: 2,
    theme: "neutral",
    text: "Pour une fréquence $F_n$ de succès (proportion $p$), que vaut $E(F_n)$ ?",
    format: "qcm",
    choices: ["$p$", "$np$", "$\\dfrac{p}{n}$", "$p(1-p)$"],
    expected: ["$p$"],
    comparator: "mcq_exact",
    hint: "La fréquence estime la proportion $p$.",
    explanation: exp(
      "L'espérance de la fréquence est la proportion théorique.",
      "$F_n = \\dfrac{X}{n}$ avec $X \\sim \\mathcal{B}(n,p)$, donc $E(F_n) = \\dfrac{np}{n}$.",
      "$= p$.",
      "$E(F_n) = p$."
    ),
    tags: ["terminale-spe", "concentration", "fluctuation", "qcm"],
  },

  {
    kind: "fixed",
    id: "terminale_spe_conc_fluc_fixed_2",
    niveau: "terminale-spe",
    matiere: "maths",
    notionId: "concentration_echantillonnage",
    microId: "concentration_fluctuation",
    difficulty: 3,
    theme: "neutral",
    text: "Que vaut la variance $V(F_n)$ d'une fréquence ?",
    format: "qcm",
    choices: ["$\\dfrac{p(1-p)}{n}$", "$p(1-p)$", "$np(1-p)$", "$\\dfrac{p}{n}$"],
    expected: ["$\\dfrac{p(1-p)}{n}$"],
    comparator: "mcq_exact",
    hint: "$V(F_n) = \\dfrac{V(X)}{n^2}$ avec $V(X) = np(1-p)$.",
    explanation: exp(
      "On divise la variance de $X \\sim \\mathcal{B}(n,p)$ par $n^2$.",
      "$V(F_n) = \\dfrac{V(X)}{n^2} = \\dfrac{np(1-p)}{n^2}$.",
      "$= \\dfrac{p(1-p)}{n}$.",
      "$V(F_n) = \\dfrac{p(1-p)}{n}$."
    ),
    tags: ["terminale-spe", "concentration", "fluctuation", "qcm"],
  },

  {
    kind: "fixed",
    id: "terminale_spe_conc_fluc_fixed_3",
    niveau: "terminale-spe",
    matiere: "maths",
    notionId: "concentration_echantillonnage",
    microId: "concentration_fluctuation",
    difficulty: 4,
    theme: "neutral",
    text: "Avec $p = 0{,}5$ et $n = 100$, que vaut $V(F_n)$ ?",
    format: "qcm",
    choices: ["$0{,}0025$", "$0{,}25$", "$0{,}025$", "$0{,}5$"],
    expected: ["$0{,}0025$"],
    comparator: "mcq_exact",
    hint: "$\\dfrac{0{,}5 \\times 0{,}5}{100}$.",
    explanation: exp(
      "On applique $V(F_n) = \\dfrac{p(1-p)}{n}$.",
      "$\\dfrac{0{,}5 \\times 0{,}5}{100} = \\dfrac{0{,}25}{100}$.",
      "$= 0{,}0025$.",
      "$V(F_n) = 0{,}0025$."
    ),
    tags: ["terminale-spe", "concentration", "fluctuation", "qcm"],
  },

  {
    kind: "fixed",
    id: "terminale_spe_conc_fluc_fixed_4",
    niveau: "terminale-spe",
    matiere: "maths",
    notionId: "concentration_echantillonnage",
    microId: "concentration_fluctuation",
    difficulty: 4,
    theme: "neutral",
    text: "Quand $n$ augmente, la fréquence $F_n$ d'un échantillon :",
    format: "qcm",
    choices: [
      "fluctue de moins en moins autour de $p$",
      "fluctue de plus en plus",
      "devient égale à $1$",
      "ne dépend plus de $p$",
    ],
    expected: ["fluctue de moins en moins autour de $p$"],
    comparator: "mcq_exact",
    hint: "$V(F_n) = \\dfrac{p(1-p)}{n}$ diminue.",
    explanation: exp(
      "La fluctuation se mesure par la variance.",
      "$V(F_n) = \\dfrac{p(1-p)}{n}$ diminue quand $n$ augmente.",
      "La fréquence se resserre autour de $p$.",
      "Elle fluctue de moins en moins autour de $p$."
    ),
    tags: ["terminale-spe", "concentration", "fluctuation", "qcm"],
  },

  {
    kind: "fixed",
    id: "terminale_spe_conc_fluc_fixed_5",
    niveau: "terminale-spe",
    matiere: "maths",
    notionId: "concentration_echantillonnage",
    microId: "concentration_fluctuation",
    difficulty: 5,
    theme: "neutral",
    text: "Avec $p = 0{,}2$ et $n = 100$, que vaut $V(F_n)$ ?",
    format: "qcm",
    choices: ["$0{,}0016$", "$0{,}16$", "$0{,}016$", "$0{,}2$"],
    expected: ["$0{,}0016$"],
    comparator: "mcq_exact",
    hint: "$\\dfrac{0{,}2 \\times 0{,}8}{100}$.",
    explanation: exp(
      "On applique $V(F_n) = \\dfrac{p(1-p)}{n}$.",
      "$\\dfrac{0{,}2 \\times 0{,}8}{100} = \\dfrac{0{,}16}{100}$.",
      "$= 0{,}0016$.",
      "$V(F_n) = 0{,}0016$."
    ),
    tags: ["terminale-spe", "concentration", "fluctuation", "qcm"],
  },

  {
    kind: "fixed",
    id: "terminale_spe_conc_fluc_fixed_6",
    niveau: "terminale-spe",
    matiere: "maths",
    notionId: "concentration_echantillonnage",
    microId: "concentration_fluctuation",
    difficulty: 3,
    theme: "neutral",
    text: "La « fluctuation d'échantillonnage » désigne :",
    format: "qcm",
    choices: [
      "la variation de la fréquence d'un échantillon à l'autre",
      "une erreur de calcul",
      "la moyenne théorique",
      "la dérivée de la fréquence",
    ],
    expected: ["la variation de la fréquence d'un échantillon à l'autre"],
    comparator: "mcq_exact",
    hint: "Deux échantillons donnent des fréquences différentes.",
    explanation: exp(
      "La fluctuation décrit la variabilité due au hasard de l'échantillon.",
      "D'un échantillon à l'autre, la fréquence observée change.",
      "C'est la fluctuation d'échantillonnage.",
      "C'est la variation de la fréquence d'un échantillon à l'autre."
    ),
    tags: ["terminale-spe", "concentration", "fluctuation", "qcm"],
  },

  {
    kind: "fixed",
    id: "terminale_spe_conc_fluc_fixed_7",
    niveau: "terminale-spe",
    matiere: "maths",
    notionId: "concentration_echantillonnage",
    microId: "concentration_fluctuation",
    difficulty: 5,
    theme: "neutral",
    text: "Avec $p = 0{,}145$, l'expression $p(1-p)$ vaut $0{,}123975$. Que vaut alors $V(F_n)$ en fonction de $n$ ?",
    format: "qcm",
    choices: [
      "$\\dfrac{0{,}123975}{n}$",
      "$0{,}123975 \\times n$",
      "$\\dfrac{0{,}145}{n}$",
      "$\\dfrac{0{,}123975}{n^2}$",
    ],
    expected: ["$\\dfrac{0{,}123975}{n}$"],
    comparator: "mcq_exact",
    hint: "$V(F_n) = \\dfrac{p(1-p)}{n}$.",
    explanation: exp(
      "On applique $V(F_n) = \\dfrac{p(1-p)}{n}$.",
      "Avec $p(1-p) = 0{,}123975$.",
      "$V(F_n) = \\dfrac{0{,}123975}{n}$.",
      "$V(F_n) = \\dfrac{0{,}123975}{n}$ (cf. bac Amérique du Nord 2025)."
    ),
    tags: ["terminale-spe", "concentration", "fluctuation", "qcm"],
  },

  {
    kind: "fixed",
    id: "terminale_spe_conc_fluc_fixed_8",
    niveau: "terminale-spe",
    matiere: "maths",
    notionId: "concentration_echantillonnage",
    microId: "concentration_fluctuation",
    difficulty: 4,
    theme: "neutral",
    text: "Une fréquence observée $F_n$ est utilisée pour estimer :",
    format: "qcm",
    choices: ["la proportion $p$ dans la population", "la variance", "la taille $n$", "l'écart-type seul"],
    expected: ["la proportion $p$ dans la population"],
    comparator: "mcq_exact",
    hint: "$E(F_n) = p$.",
    explanation: exp(
      "La fréquence est un estimateur de la proportion.",
      "Comme $E(F_n) = p$, $F_n$ estime $p$.",
      "On estime ainsi la proportion inconnue de la population.",
      "Elle estime la proportion $p$."
    ),
    tags: ["terminale-spe", "concentration", "fluctuation", "qcm"],
  },

  {
    kind: "fixed",
    id: "terminale_spe_conc_fluc_fixed_9",
    niveau: "terminale-spe",
    matiere: "maths",
    notionId: "concentration_echantillonnage",
    microId: "concentration_fluctuation",
    difficulty: 5,
    theme: "neutral",
    text: "Avec $p = 0{,}1$ et $n = 900$, que vaut $V(F_n)$ ?",
    format: "qcm",
    choices: ["$0{,}0001$", "$0{,}001$", "$0{,}09$", "$0{,}01$"],
    expected: ["$0{,}0001$"],
    comparator: "mcq_exact",
    hint: "$\\dfrac{0{,}1 \\times 0{,}9}{900} = \\dfrac{0{,}09}{900}$.",
    explanation: exp(
      "On applique $V(F_n) = \\dfrac{p(1-p)}{n}$.",
      "$\\dfrac{0{,}1 \\times 0{,}9}{900} = \\dfrac{0{,}09}{900}$.",
      "$= 0{,}0001$.",
      "$V(F_n) = 0{,}0001$."
    ),
    tags: ["terminale-spe", "concentration", "fluctuation", "qcm"],
  },

  {
    kind: "fixed",
    id: "terminale_spe_conc_fluc_fixed_10",
    niveau: "terminale-spe",
    matiere: "maths",
    notionId: "concentration_echantillonnage",
    microId: "concentration_fluctuation",
    difficulty: 4,
    theme: "neutral",
    text: "Pour réduire la fluctuation d'une fréquence (la rendre plus fiable), il faut :",
    format: "qcm",
    choices: ["augmenter $n$", "diminuer $n$", "changer $p$", "rien faire"],
    expected: ["augmenter $n$"],
    comparator: "mcq_exact",
    hint: "$V(F_n) = \\dfrac{p(1-p)}{n}$ : $n$ au dénominateur.",
    explanation: exp(
      "La fluctuation se mesure par $V(F_n)$.",
      "$V(F_n) = \\dfrac{p(1-p)}{n}$ diminue quand $n$ augmente.",
      "Un plus grand échantillon réduit la fluctuation.",
      "Il faut augmenter $n$."
    ),
    tags: ["terminale-spe", "concentration", "fluctuation", "qcm"],
  },

  /* =========================================================
     CONCENTRATION_DEFI — Type bac
  ========================================================= */

  {
    kind: "fixed",
    id: "terminale_spe_conc_defi_fixed_1",
    niveau: "terminale-spe",
    matiere: "maths",
    notionId: "concentration_echantillonnage",
    microId: "concentration_defi",
    difficulty: 5,
    theme: "neutral",
    text: "Bac 2025 : $F_n$ a pour variance $V(F_n) = \\dfrac{0{,}123975}{n}$. Par l'inégalité de concentration, $P(|F_n - 0{,}145| \\ge 0{,}1)$ est majorée par :",
    format: "qcm",
    choices: [
      "$\\dfrac{12{,}3975}{n}$",
      "$\\dfrac{0{,}123975}{n}$",
      "$\\dfrac{1{,}23975}{n}$",
      "$\\dfrac{0{,}1}{n}$",
    ],
    expected: ["$\\dfrac{12{,}3975}{n}$"],
    comparator: "mcq_exact",
    hint: "Majorant $= \\dfrac{V(F_n)}{\\delta^2} = \\dfrac{0{,}123975/n}{0{,}1^2}$.",
    explanation: exp(
      "On applique l'inégalité de concentration avec $\\delta = 0{,}1$.",
      "Majorant $= \\dfrac{V(F_n)}{\\delta^2} = \\dfrac{0{,}123975/n}{0{,}01}$.",
      "$= \\dfrac{12{,}3975}{n}$ (que l'on majore par $\\dfrac{12{,}5}{n}$ au bac).",
      "Le majorant est $\\dfrac{12{,}3975}{n}$."
    ),
    tags: ["terminale-spe", "concentration", "type_bac", "qcm"],
  },

  {
    kind: "fixed",
    id: "terminale_spe_conc_defi_fixed_2",
    niveau: "terminale-spe",
    matiere: "maths",
    notionId: "concentration_echantillonnage",
    microId: "concentration_defi",
    difficulty: 5,
    theme: "neutral",
    text: "Un responsable observe $F_{1000} = 0{,}3$ alors que la proportion attendue est $p = 0{,}145$. L'écart $|0{,}3 - 0{,}145| = 0{,}155$ est :",
    format: "qcm",
    choices: [
      "anormalement grand (dysfonctionnement probable)",
      "tout à fait normal",
      "impossible",
      "égal à la variance",
    ],
    expected: ["anormalement grand (dysfonctionnement probable)"],
    comparator: "mcq_exact",
    hint: "Avec $n = 1000$, la concentration rend un tel écart très improbable.",
    explanation: exp(
      "On compare l'écart observé à ce que permet la concentration.",
      "Pour $n = 1000$, $P(|F_n - 0{,}145| \\ge 0{,}1) \\le \\dfrac{12{,}5}{1000} = 0{,}0125$.",
      "Un écart de $0{,}155 > 0{,}1$ est donc très improbable : anomalie.",
      "L'écart est anormalement grand : le responsable a raison de soupçonner un problème."
    ),
    tags: ["terminale-spe", "concentration", "type_bac", "qcm"],
  },

  {
    kind: "fixed",
    id: "terminale_spe_conc_defi_fixed_3",
    niveau: "terminale-spe",
    matiere: "maths",
    notionId: "concentration_echantillonnage",
    microId: "concentration_defi",
    difficulty: 4,
    theme: "neutral",
    text: "On veut $P(|M_n - \\mu| \\ge 0{,}1) \\le 0{,}01$ avec $\\sigma^2 = 1$. L'inégalité de concentration donne $\\dfrac{1}{n \\times 0{,}01} \\le 0{,}01$. Quelle valeur de $n$ convient ?",
    format: "qcm",
    choices: ["$n = 10\\,000$", "$n = 100$", "$n = 1\\,000$", "$n = 10$"],
    expected: ["$n = 10\\,000$"],
    comparator: "mcq_exact",
    hint: "Résous $\\dfrac{1}{0{,}01\\,n} \\le 0{,}01$, soit $\\dfrac{100}{n} \\le 0{,}01$.",
    explanation: exp(
      "On résout l'inéquation en $n$.",
      "$\\dfrac{\\sigma^2}{n\\delta^2} = \\dfrac{1}{n \\times 0{,}01} = \\dfrac{100}{n} \\le 0{,}01$.",
      "$n \\ge \\dfrac{100}{0{,}01} = 10\\,000$.",
      "$n = 10\\,000$ convient."
    ),
    tags: ["terminale-spe", "concentration", "type_bac", "qcm"],
  },

  {
    kind: "fixed",
    id: "terminale_spe_conc_defi_fixed_4",
    niveau: "terminale-spe",
    matiere: "maths",
    notionId: "concentration_echantillonnage",
    microId: "concentration_defi",
    difficulty: 5,
    theme: "neutral",
    text: "Un sondage : on interroge $n$ personnes, fréquence de « oui » $F_n$, proportion réelle $p$. Pourquoi un grand $n$ donne-t-il un sondage fiable ?",
    format: "qcm",
    choices: [
      "car $V(F_n) = \\dfrac{p(1-p)}{n}$ devient petite : $F_n$ se concentre sur $p$",
      "car $E(F_n)$ augmente",
      "car $p$ change",
      "car la fluctuation augmente",
    ],
    expected: ["car $V(F_n) = \\dfrac{p(1-p)}{n}$ devient petite : $F_n$ se concentre sur $p$"],
    comparator: "mcq_exact",
    hint: "Variance de la fréquence en $1/n$.",
    explanation: exp(
      "La fiabilité dépend de la variance de la fréquence.",
      "$V(F_n) = \\dfrac{p(1-p)}{n}$ décroît en $\\dfrac{1}{n}$.",
      "Pour $n$ grand, $F_n$ se concentre autour de $p$ (loi des grands nombres).",
      "Car $V(F_n)$ devient petite : $F_n$ se concentre sur $p$."
    ),
    tags: ["terminale-spe", "concentration", "type_bac", "qcm"],
  },

  {
    kind: "fixed",
    id: "terminale_spe_conc_defi_fixed_5",
    niveau: "terminale-spe",
    matiere: "maths",
    notionId: "concentration_echantillonnage",
    microId: "concentration_defi",
    difficulty: 4,
    theme: "neutral",
    text: "Un échantillon de $n = 100$ pièces, $X \\sim \\mathcal{B}(100\\,;0{,}5)$, $M_n = \\dfrac{X}{100} = F_n$. Que vaut $E(F_n)$ ?",
    format: "qcm",
    choices: ["$0{,}5$", "$50$", "$0{,}25$", "$100$"],
    expected: ["$0{,}5$"],
    comparator: "mcq_exact",
    hint: "$E(F_n) = p$.",
    explanation: exp(
      "La fréquence a pour espérance la proportion.",
      "$E(F_n) = p = 0{,}5$.",
      "$= 0{,}5$.",
      "$E(F_n) = 0{,}5$."
    ),
    tags: ["terminale-spe", "concentration", "type_bac", "qcm"],
  },

  {
    kind: "fixed",
    id: "terminale_spe_conc_defi_fixed_6",
    niveau: "terminale-spe",
    matiere: "maths",
    notionId: "concentration_echantillonnage",
    microId: "concentration_defi",
    difficulty: 5,
    theme: "neutral",
    text: "Pour estimer $p$ à $\\pm 0{,}05$ avec une bonne fiabilité, on doit surtout :",
    format: "qcm",
    choices: [
      "choisir une grande taille d'échantillon $n$",
      "choisir $n = 5$",
      "changer la valeur de $p$",
      "augmenter $\\delta$",
    ],
    expected: ["choisir une grande taille d'échantillon $n$"],
    comparator: "mcq_exact",
    hint: "La précision exige $V(F_n)$ petite, donc $n$ grand.",
    explanation: exp(
      "La précision d'une estimation dépend de la taille de l'échantillon.",
      "Plus $n$ est grand, plus la fréquence est proche de $p$ (faible fluctuation).",
      "Pour une marge de $\\pm 0{,}05$ fiable, il faut $n$ grand.",
      "Il faut choisir une grande taille $n$."
    ),
    tags: ["terminale-spe", "concentration", "type_bac", "qcm"],
  },

  {
    kind: "fixed",
    id: "terminale_spe_conc_defi_fixed_7",
    niveau: "terminale-spe",
    matiere: "maths",
    notionId: "concentration_echantillonnage",
    microId: "concentration_defi",
    difficulty: 5,
    theme: "neutral",
    text: "Avec $\\sigma^2 = 1$, on veut $\\dfrac{\\sigma^2}{n\\delta^2} \\le 0{,}05$ pour $\\delta = 0{,}2$. Quelle est la plus petite valeur de $n$ ?",
    format: "qcm",
    choices: ["$500$", "$50$", "$100$", "$2000$"],
    expected: ["$500$"],
    comparator: "mcq_exact",
    hint: "$\\dfrac{1}{n \\times 0{,}04} \\le 0{,}05$.",
    explanation: exp(
      "On résout l'inéquation en $n$.",
      "$\\dfrac{1}{n \\times 0{,}2^2} = \\dfrac{1}{0{,}04\\,n} = \\dfrac{25}{n} \\le 0{,}05$.",
      "$n \\ge \\dfrac{25}{0{,}05} = 500$.",
      "La plus petite valeur est $n = 500$."
    ),
    tags: ["terminale-spe", "concentration", "type_bac", "qcm"],
  },

  {
    kind: "fixed",
    id: "terminale_spe_conc_defi_fixed_8",
    niveau: "terminale-spe",
    matiere: "maths",
    notionId: "concentration_echantillonnage",
    microId: "concentration_defi",
    difficulty: 4,
    theme: "neutral",
    text: "La loi des grands nombres et l'inégalité de concentration justifient ensemble que :",
    format: "qcm",
    choices: [
      "la moyenne (ou fréquence) d'un grand échantillon est une bonne estimation",
      "une seule mesure suffit",
      "le hasard n'existe pas",
      "la variance est toujours nulle",
    ],
    expected: ["la moyenne (ou fréquence) d'un grand échantillon est une bonne estimation"],
    comparator: "mcq_exact",
    hint: "C'est le fondement de l'estimation statistique.",
    explanation: exp(
      "Ces résultats fondent l'estimation par échantillon.",
      "Concentration + loi des grands nombres : la moyenne se concentre sur $\\mu$.",
      "Un grand échantillon donne donc une estimation fiable.",
      "La moyenne (ou fréquence) d'un grand échantillon est une bonne estimation."
    ),
    tags: ["terminale-spe", "concentration", "type_bac", "qcm"],
  },

  {
    kind: "fixed",
    id: "terminale_spe_conc_defi_fixed_9",
    niveau: "terminale-spe",
    matiere: "maths",
    notionId: "concentration_echantillonnage",
    microId: "concentration_defi",
    difficulty: 5,
    theme: "neutral",
    text: "Si pour $n = 1000$ le majorant de $P(|F_n - p| \\ge 0{,}1)$ vaut $0{,}0125$, alors un écart supérieur à $0{,}1$ se produit :",
    format: "qcm",
    choices: [
      "au plus dans 1,25 % des cas",
      "dans au moins 98,75 % des cas",
      "toujours",
      "jamais",
    ],
    expected: ["au plus dans 1,25 % des cas"],
    comparator: "mcq_exact",
    hint: "$0{,}0125 = 1{,}25\\,\\%$ est un majorant de probabilité.",
    explanation: exp(
      "Le majorant borne la probabilité de l'événement.",
      "$P(|F_n - p| \\ge 0{,}1) \\le 0{,}0125$.",
      "Soit au plus $1{,}25\\,\\%$ des cas.",
      "Un tel écart se produit au plus dans 1,25 % des cas."
    ),
    tags: ["terminale-spe", "concentration", "type_bac", "qcm"],
  },

  {
    kind: "fixed",
    id: "terminale_spe_conc_defi_fixed_10",
    niveau: "terminale-spe",
    matiere: "maths",
    notionId: "concentration_echantillonnage",
    microId: "concentration_defi",
    difficulty: 4,
    theme: "neutral",
    text: "Avec $p = 0{,}5$ et $n = 400$, que vaut $V(F_n)$ ?",
    format: "qcm",
    choices: ["$0{,}000625$", "$0{,}25$", "$0{,}0025$", "$0{,}1$"],
    expected: ["$0{,}000625$"],
    comparator: "mcq_exact",
    hint: "$\\dfrac{0{,}25}{400}$.",
    explanation: exp(
      "On applique $V(F_n) = \\dfrac{p(1-p)}{n}$.",
      "$\\dfrac{0{,}5 \\times 0{,}5}{400} = \\dfrac{0{,}25}{400}$.",
      "$= 0{,}000625$.",
      "$V(F_n) = 0{,}000625$."
    ),
    tags: ["terminale-spe", "concentration", "type_bac", "qcm"],
  },
];
