// « Cartes défis · Vers la 3e » — révision 4e → entrée en 3e (~14-15 ans, brevet).
// Conseil à 7 rôles, l'élève tranche : ne pas infantiliser ni moraliser, parler son monde.
// 🌋 La Réunion (fierté/identité), 🤝 Respect (émotions, premiers amours — sans morale,
// en vrai/faux ou « que fais-tu ? »), 📱 Numérique (jeux vidéo, argent, réseaux, esprit
// critique), maths brevet avec DÉMONSTRATION (Thalès, Pythagore, trigo, calcul littéral).

import type { CarteDefi } from "@/components/cartes/types";

export const CARTES: CarteDefi[] = [
  { ref: "3E·01", questions: [ {matiere:"maths",q:"Thalès s'applique quand les droites sont… ?",r:"parallèles"}, {matiere:"reunion",q:"Le point culminant de La Réunion ?",r:"le Piton des Neiges (3071 m)"}, {matiere:"emc",q:"Vrai/faux : dire « non » et être respecté, c'est un droit.",r:"vrai"}, {matiere:"numerique",q:"Dans un jeu, les « loot boxes » payantes, c'est surtout… ?",r:"un piège à argent (au hasard)"} ], bouge: "25 squats" },
  { ref: "3E·02", questions: [ {matiere:"maths",q:"Développe (x + 4)(x − 4).",r:"x² − 16"}, {matiere:"reunion",q:"La musique réunionnaise classée à l'UNESCO ?",r:"le maloya"}, {matiere:"sport",q:"Heures de sommeil pour un ado de 15 ans ?",r:"8 à 10 h 😴"}, {matiere:"histoire",q:"Année de la fin de la 2de Guerre mondiale ?",r:"1945"} ], bouge: "gainage 40 s" },
  { ref: "3E·03", questions: [ {matiere:"maths",q:"Dans un triangle rectangle, cos = ?",r:"adjacent / hypoténuse"}, {matiere:"numerique",q:"Une info virale : à faire avant de la partager ?",r:"vérifier la source"}, {matiere:"emc",q:"Un ami se moque d'un autre en ligne : que fais-tu ?",r:"je n'encourage pas, je soutiens la victime"}, {matiere:"francais",q:"« Ses yeux sont des étoiles » : quelle figure ?",r:"une métaphore"} ], bouge: "20 pompes" },
  { ref: "3E·04", questions: [ {matiere:"maths",q:"Écris 45 000 en notation scientifique.",r:"4,5 × 10⁴"}, {matiere:"reunion",q:"Le cirque le plus isolé, sans route ?",r:"Mafate"}, {matiere:"nutrition",q:"Prendre du muscle à l'ado : quel nutriment clé ?",r:"les protéines"}, {matiere:"anglais",q:"Present perfect de « to see » (I …) ?",r:"I have seen"} ], bouge: "30 fentes" },
  { ref: "3E·05", questions: [ {matiere:"maths",q:"Factorise x² + 5x.",r:"x(x + 5)"}, {matiere:"numerique",q:"6 h/jour d'écran : impact sur le sommeil ?",r:"il le dégrade (surtout le soir)"}, {matiere:"emc",q:"Le consentement, c'est… ?",r:"un accord libre, qu'on peut retirer"}, {matiere:"sciences",q:"Où se trouve l'ADN dans la cellule ?",r:"dans le noyau (les chromosomes)"} ], bouge: "cours sur place 40 s" },
  { ref: "3E·06", questions: [ {matiere:"maths",q:"Résous 2x − 3 = 7.",r:"x = 5"}, {matiere:"reunion",q:"Le Piton de la Fournaise est l'un des plus… au monde ?",r:"des volcans les plus actifs 🌋"}, {matiere:"sport",q:"Après une grosse séance, on récupère avec… ?",r:"sommeil + hydratation + repos"}, {matiere:"histoire",q:"Quel mur tombe en 1989 ?",r:"le mur de Berlin"} ], bouge: "20 burpees" },
  { ref: "3E·07", questions: [ {matiere:"maths",q:"Hypoténuse d'un triangle rectangle de côtés 6 et 8 ?",r:"10"}, {matiere:"numerique",q:"Jouer en ligne avec des potes développe quoi de bien ?",r:"l'esprit d'équipe, l'anglais, les réflexes"}, {matiere:"emc",q:"Vrai/faux : on peut aimer quelqu'un ET respecter son « non ».",r:"vrai"}, {matiere:"geo",q:"La mondialisation, c'est… ?",r:"l'intensification des échanges mondiaux"} ], bouge: "gainage 40 s" },
  { ref: "3E·08", questions: [ {matiere:"maths",q:"Moyenne de 8, 12 et 10 ?",r:"10"}, {matiere:"reunion",q:"Un oiseau endémique de La Réunion ?",r:"le tuit-tuit (ou le paille-en-queue)"}, {matiere:"nutrition",q:"Le sucre caché se trouve surtout dans… ?",r:"les sodas et produits industriels"}, {matiere:"francais",q:"Auteur des « Misérables » ?",r:"Victor Hugo"} ], bouge: "25 squats" },
  { ref: "3E·09", questions: [ {matiere:"maths",q:"Calcule (−3)².",r:"9"}, {matiere:"numerique",q:"Tes photos et ton adresse : à qui les confier en ligne ?",r:"à personne d'inconnu"}, {matiere:"emc",q:"Gérer sa colère, comment ?",r:"respirer, prendre du recul avant d'agir"}, {matiere:"sciences",q:"Unité de la puissance électrique ?",r:"le watt (W)"} ], bouge: "30 fentes" },
  { ref: "3E·10", questions: [ {matiere:"maths",q:"Développe 3(2x − 5).",r:"6x − 15"}, {matiere:"reunion",q:"En quelle année La Réunion devient département ?",r:"1946"}, {matiere:"sport",q:"Le sport améliore l'humeur grâce à… ?",r:"les endorphines"}, {matiere:"anglais",q:"Prétérit de « to go » ?",r:"went"} ], bouge: "20 pompes" },
  { ref: "3E·11", questions: [ {matiere:"maths",q:"Dans un triangle rectangle, sin = ?",r:"opposé / hypoténuse"}, {matiere:"emc",q:"Un chagrin d'amour, c'est grave ?",r:"c'est normal et ça passe ; on peut en parler"}, {matiere:"reunion",q:"Le lagon protégé de la côte ouest ?",r:"le lagon de l'Ermitage / Saint-Gilles"}, {matiere:"histoire",q:"La 1re Guerre mondiale : quelles années ?",r:"1914-1918"} ], bouge: "cours sur place 40 s" },
  { ref: "3E·12", questions: [ {matiere:"maths",q:"Résous x / 3 = 4.",r:"x = 12"}, {matiere:"numerique",q:"Les influenceurs montrent-ils leur vraie vie ?",r:"non, surtout le meilleur (mis en scène)"}, {matiere:"nutrition",q:"Combien de repas + collation pour bien grandir ?",r:"3 repas + 1 collation"}, {matiere:"francais",q:"« Rapide comme l'éclair » : quelle figure ?",r:"une comparaison"} ], bouge: "gainage 40 s" },
  { ref: "3E·13", questions: [ {matiere:"maths",q:"Aire d'un disque de rayon 3 (π ≈ 3,14) ?",r:"≈ 28,3 (soit 9π)"}, {matiere:"reunion",q:"La langue parlée avec le français à La Réunion ?",r:"le créole réunionnais"}, {matiere:"emc",q:"S'affirmer sans écraser l'autre, ça s'appelle… ?",r:"le respect (s'affirmer)"}, {matiere:"sciences",q:"Combien de chromosomes chez l'humain ?",r:"46 (23 paires)"} ], bouge: "25 squats" },
  { ref: "3E·14", questions: [ {matiere:"maths",q:"Calcule 2⁵.",r:"32"}, {matiere:"numerique",q:"Le cyberharcèlement est-il puni par la loi ?",r:"oui, c'est un délit"}, {matiere:"sport",q:"Bien manger + bouger = ?",r:"un corps en forme"}, {matiere:"anglais",q:"Traduis « I have finished ».",r:"j'ai fini"} ], bouge: "30 fentes" },
  { ref: "3E·15", questions: [ {matiere:"maths",q:"Développe (x + 3)².",r:"x² + 6x + 9"}, {matiere:"reunion",q:"Le plat servi le dimanche à La Réunion ?",r:"le cari (poulet, canard…)"}, {matiere:"emc",q:"Mettre la pression pour un rendez-vous : ok ?",r:"non, on respecte le choix de l'autre"}, {matiere:"histoire",q:"Qui dirige l'Allemagne nazie ?",r:"Hitler"} ], bouge: "20 burpees" },
  { ref: "3E·16", questions: [ {matiere:"maths",q:"Résous 5x = 45.",r:"x = 9"}, {matiere:"numerique",q:"Avant de dépenser de l'argent réel dans un jeu, pense à… ?",r:"ton budget : est-ce que ça vaut le coup ?"}, {matiere:"nutrition",q:"Une boisson zéro sucre ?",r:"l'eau 💧"}, {matiere:"sciences",q:"Vitesse de la lumière (ordre de grandeur) ?",r:"≈ 300 000 km/s"} ], bouge: "gainage 40 s" },
  { ref: "3E·17", questions: [ {matiere:"maths",q:"Notation scientifique de 0,003 ?",r:"3 × 10⁻³"}, {matiere:"reunion",q:"Le fruit-roi de l'été austral à La Réunion ?",r:"le letchi 🍒"}, {matiere:"emc",q:"Un secret qu'on t'a confié : tu le postes sur le groupe ?",r:"non, on respecte la confiance"}, {matiere:"francais",q:"Le registre qui cherche à émouvoir ?",r:"le registre pathétique"} ], bouge: "cours sur place 40 s" },
  { ref: "3E·18", questions: [ {matiere:"maths",q:"Pythagore : côtés 5 et 12, hypoténuse ?",r:"13"}, {matiere:"numerique",q:"Un jeu vidéo fait souvent progresser en quelle langue ?",r:"l'anglais"}, {matiere:"sport",q:"L'échauffement sert à… ?",r:"préparer les muscles, éviter les blessures"}, {matiere:"geo",q:"Cite une grande métropole mondiale.",r:"Paris, Londres, New York, Tokyo…"} ], bouge: "25 squats" },
  { ref: "3E·19", questions: [ {matiere:"maths",q:"Calcule (−4) × (−5).",r:"20"}, {matiere:"reunion",q:"Le sport de glisse au lagon ?",r:"le surf / le bodyboard 🏄"}, {matiere:"emc",q:"Se comparer aux autres en permanence : bon pour l'estime ?",r:"non, ça la fragilise ; chacun est différent"}, {matiere:"sciences",q:"Organe qui filtre le sang ?",r:"le rein"} ], bouge: "30 fentes" },
  { ref: "3E·20", questions: [ {matiere:"maths",q:"Factorise 4x + 8.",r:"4(x + 2)"}, {matiere:"numerique",q:"Une pause écran de temps en temps : utile ?",r:"oui : yeux, sommeil, tête reposée"}, {matiere:"nutrition",q:"Trop de sel : mauvais pour… ?",r:"le cœur / la tension"}, {matiere:"anglais",q:"Prétérit de « to make » ?",r:"made"} ], bouge: "20 pompes" },
  { ref: "3E·21", questions: [ {matiere:"maths",q:"Moyenne de 15 et 5 ?",r:"10"}, {matiere:"reunion",q:"« ça va ? » en créole réunionnais ?",r:"« Koman i lé ? »"}, {matiere:"emc",q:"L'amitié se construit avec… ?",r:"la confiance et le respect"}, {matiere:"histoire",q:"La Révolution française commence en… ?",r:"1789"} ], bouge: "gainage 40 s" },
  { ref: "3E·22", questions: [ {matiere:"maths",q:"Résous x + 7 = 2.",r:"x = −5"}, {matiere:"numerique",q:"Un mot de passe solide, c'est… ?",r:"long, unique, avec chiffres et symboles"}, {matiere:"sport",q:"Cardio ou muscu pour le souffle ?",r:"le cardio (endurance)"}, {matiere:"francais",q:"Auteur du « Rouge et le Noir » ?",r:"Stendhal"} ], bouge: "cours sur place 40 s" },
  { ref: "3E·23", questions: [ {matiere:"maths",q:"Calcule 10³.",r:"1000"}, {matiere:"reunion",q:"Un cirque connu pour ses eaux thermales ?",r:"Cilaos"}, {matiere:"emc",q:"Dire ses émotions plutôt que tout garder : bon ?",r:"oui, ça aide à aller mieux"}, {matiere:"sciences",q:"Formule chimique de l'eau ?",r:"H₂O"} ], bouge: "25 squats" },
  { ref: "3E·24", questions: [ {matiere:"maths",q:"Résous 3x + 2 = 11.",r:"x = 3"}, {matiere:"numerique",q:"Une vidéo « trop belle pour être vraie » : réflexe ?",r:"douter, vérifier (un fake est possible)"}, {matiere:"nutrition",q:"Le petit-déj le jour du brevet, utile ?",r:"oui, pour la concentration"}, {matiere:"anglais",q:"Present perfect de « eat » (I …) ?",r:"I have eaten"} ], bouge: "30 fentes" },
  { ref: "3E·25", questions: [ {matiere:"maths",q:"Périmètre d'un cercle de rayon 5 (π ≈ 3,14) ?",r:"≈ 31,4 (soit 10π)"}, {matiere:"reunion",q:"Le peuplement de La Réunion, c'est surtout… ?",r:"un métissage (Europe, Afrique, Inde, Chine…)"}, {matiere:"emc",q:"Le respect vaut-il aussi en ligne ?",r:"oui, autant que dans la vraie vie"}, {matiere:"histoire",q:"La 5e République date de… ?",r:"1958"} ], bouge: "20 burpees" },
  { ref: "3E·26", questions: [ {matiere:"maths",q:"Factorise x² − 9.",r:"(x − 3)(x + 3)"}, {matiere:"numerique",q:"Passer sa colère sur les réseaux, bonne idée ?",r:"non, on réfléchit avant de poster"}, {matiere:"sport",q:"Marcher 10 000 pas/jour, bon pour la santé ?",r:"oui"}, {matiere:"geo",q:"Une inégalité de la mondialisation ?",r:"l'écart entre pays riches et pauvres"} ], bouge: "gainage 40 s" },
  { ref: "3E·27", questions: [ {matiere:"maths",q:"Calcule 7 × 10⁴.",r:"70 000"}, {matiere:"reunion",q:"Une grande randonnée à La Réunion ?",r:"l'ascension du Piton des Neiges"}, {matiere:"emc",q:"Aider un camarade en difficulté, c'est… ?",r:"de la solidarité / de la bienveillance"}, {matiere:"francais",q:"Une strophe de 4 vers s'appelle… ?",r:"un quatrain"} ], bouge: "25 squats" },
  { ref: "3E·28", questions: [ {matiere:"maths",q:"Résous 4(x − 1) = 12.",r:"x = 4"}, {matiere:"numerique",q:"Ton temps de jeu idéal, c'est… ?",r:"équilibré : jeu + sommeil + amis + sport"}, {matiere:"nutrition",q:"Fruit ou chips avant le sport ?",r:"un fruit (énergie) 🍌"}, {matiere:"sciences",q:"Quel gaz respire-t-on pour vivre ?",r:"le dioxygène (O₂)"} ], bouge: "30 fentes" },
  { ref: "3E·29", questions: [ {matiere:"maths",q:"Lequel = opposé / adjacent : sin, cos ou tan ?",r:"la tangente (tan)"}, {matiere:"reunion",q:"La devise créole de la fierté ?",r:"« Nou la fé ! » 🌺"}, {matiere:"emc",q:"Un premier amour, ça compte ?",r:"oui, tes émotions sont légitimes"}, {matiere:"histoire",q:"La Déclaration des droits de l'homme date de… ?",r:"1789"} ], bouge: "20 pompes" },
  { ref: "3E·30", questions: [ {matiere:"maths",q:"Pythagore : côtés 9 et 12, hypoténuse ?",r:"15"}, {matiere:"numerique",q:"Message clé : ta valeur dépend-elle des likes ?",r:"non, tu vaux bien plus que des likes 💙"}, {matiere:"sport",q:"Bouger, c'est prendre soin de son corps ?",r:"oui, bravo !"}, {matiere:"reunion",q:"Fier de ton île ? 🌋",r:"oui ! Nou la fé !"} ], bouge: "grand final : gainage 40 s 💪" },
];
