import type { TutorBankItemV4 } from "@/lib/tutor-v4/types";

const WORDS = [
  { slug: "medio_ambiente",  es: "medio ambiente",  fr: "environnement",         notionId: "es_b1_environment", audio: "/audio/espagnol/environment/b1/medio_ambiente.mp3"   },
  { slug: "contaminacion",   es: "contaminación",   fr: "pollution",             notionId: "es_b1_environment", audio: "/audio/espagnol/environment/b1/contaminacion.mp3"    },
  { slug: "reciclaje",       es: "reciclaje",        fr: "recyclage",             notionId: "es_b1_environment", audio: "/audio/espagnol/environment/b1/reciclaje.mp3"        },
  { slug: "cambio_climatico",es: "cambio climático", fr: "changement climatique", notionId: "es_b1_environment", audio: "/audio/espagnol/environment/b1/cambio_climatico.mp3" },
  { slug: "energia_solar",   es: "energía solar",   fr: "énergie solaire",       notionId: "es_b1_environment", audio: "/audio/espagnol/environment/b1/energia_solar.mp3"    },
  { slug: "opinion",         es: "opinión",          fr: "opinion",               notionId: "es_b1_opinions",    audio: "/audio/espagnol/opinions/b1/opinion.mp3"             },
  { slug: "creo_que",        es: "creo que",         fr: "je pense que",          notionId: "es_b1_opinions",    audio: "/audio/espagnol/opinions/b1/creo_que.mp3"            },
  { slug: "estoy_de_acuerdo",es: "estoy de acuerdo", fr: "je suis d'accord",      notionId: "es_b1_opinions",    audio: "/audio/espagnol/opinions/b1/estoy_de_acuerdo.mp3"    },
  { slug: "periodico",       es: "periódico",        fr: "journal",               notionId: "es_b1_media",       audio: "/audio/espagnol/media/b1/periodico.mp3"              },
  { slug: "television",      es: "televisión",       fr: "télévision",            notionId: "es_b1_media",       audio: "/audio/espagnol/media/b1/television.mp3"             },
  { slug: "economia",        es: "economía",         fr: "économie",              notionId: "es_b1_economy",     audio: "/audio/espagnol/economy/b1/economia.mp3"             },
  { slug: "empresa",         es: "empresa",          fr: "entreprise",            notionId: "es_b1_economy",     audio: "/audio/espagnol/economy/b1/empresa.mp3"              },
  { slug: "laboratorio",     es: "laboratorio",      fr: "laboratoire",           notionId: "es_b1_science",     audio: "/audio/espagnol/science/b1/laboratorio.mp3"          },
  { slug: "experimento",     es: "experimento",      fr: "expérience",            notionId: "es_b1_science",     audio: "/audio/espagnol/science/b1/experimento.mp3"          },
] as const;

function dFr(exclude: string) { return WORDS.filter(w => w.fr !== exclude).map(w => w.fr).slice(0, 3); }
function dEs(exclude: string) { return WORDS.filter(w => w.es !== exclude).map(w => w.es).slice(0, 3); }

export const espagnolB1QuestionBank: TutorBankItemV4[] = WORDS.flatMap((word) => [
  {
    kind: "fixed" as const,
    id: `es_b1_${word.slug}_es_to_fr`,
    niveau: "b1" as const,
    matiere: "espagnol" as const,
    notionId: word.notionId,
    microId: `${word.notionId}_es_to_fr`,
    difficulty: 2 as const,
    text: `Que signifie "${word.es}" en français ?`,
    format: "qcm" as const,
    choices: [word.fr, ...dFr(word.fr)],
    expected: [word.fr],
    comparator: "mcq_exact" as const,
    explanation: `"${word.es}" = "${word.fr}".`,
  },
  {
    kind: "fixed" as const,
    id: `es_b1_${word.slug}_fr_to_es`,
    niveau: "b1" as const,
    matiere: "espagnol" as const,
    notionId: word.notionId,
    microId: `${word.notionId}_fr_to_es`,
    difficulty: 3 as const,
    text: `Comment dit-on "${word.fr}" en espagnol ?`,
    format: "qcm" as const,
    choices: [word.es, ...dEs(word.es)],
    expected: [word.es],
    comparator: "mcq_exact" as const,
    explanation: `"${word.fr}" se dit "${word.es}" en espagnol.`,
  },
  {
    kind: "fixed" as const,
    id: `es_b1_${word.slug}_listen`,
    niveau: "b1" as const,
    matiere: "espagnol" as const,
    notionId: word.notionId,
    microId: `${word.notionId}_listen`,
    difficulty: 3 as const,
    text: `🔊 Écoute et choisis la traduction française.`,
    format: "qcm" as const,
    audioSrc: word.audio,
    choices: [word.fr, ...dFr(word.fr)],
    expected: [word.fr],
    comparator: "mcq_exact" as const,
    hint: `Écoute attentivement la prononciation.`,
    explanation: `Le mot entendu est "${word.es}" (${word.fr}).`,
  },
]);
