import type { TutorBankItemV4 } from "@/lib/tutor-v4/types";

const WORDS = [
  { slug: "medio_ambiente",  es: "medio ambiente",  fr: "environnement",         notionId: "es_b1_environment", audio: "/audio/espagnol/environment/b1/medio_ambiente.mp3"   },
  { slug: "contaminacion",   es: "contaminación",   fr: "pollution",             notionId: "es_b1_environment", audio: "/audio/espagnol/environment/b1/contaminacion.mp3"    },
  { slug: "reciclaje",       es: "reciclaje",        fr: "recyclage",             notionId: "es_b1_environment", audio: "/audio/espagnol/environment/b1/reciclaje.mp3"        },
  { slug: "cambio_climatico",es: "cambio climático", fr: "changement climatique", notionId: "es_b1_environment", audio: "/audio/espagnol/environment/b1/cambio_climatico.mp3" },
  { slug: "energia_solar",   es: "energía solar",   fr: "énergie solaire",       notionId: "es_b1_environment", audio: "/audio/espagnol/environment/b1/energia_solar.mp3"    },
  { slug: "opinion",         es: "opinión",          fr: "opinion",               notionId: "es_b1_opinions",    audio: "/audio/espagnol/opinions/b1/opinion.mp3"             },
  { slug: "creo_que",        es: "creo que",         fr: "je pense que",          notionId: "es_b1_opinions",    audio: "/audio/espagnol/opinions/b1/creo_que.mp3"            },
  { slug: "estoy_de_acuerdo",es: "estoy de acuerdo", fr: "je suis d'accord",      notionId: "es_b1_opinions",    audio: "/audio/espagnol/opinions/b1/estoy_de_acuerdo.mp3"    },
  { slug: "periodico",       es: "periódico",        fr: "journal",               notionId: "es_b1_media",       audio: "/audio/espagnol/media/b1/periodico.mp3"              },
  { slug: "television",      es: "televisión",       fr: "télévision",            notionId: "es_b1_media",       audio: "/audio/espagnol/media/b1/television.mp3"             },
  { slug: "economia",        es: "economía",         fr: "économie",              notionId: "es_b1_economy",     audio: "/audio/espagnol/economy/b1/economia.mp3"             },
  { slug: "empresa",         es: "empresa",          fr: "entreprise",            notionId: "es_b1_economy",     audio: "/audio/espagnol/economy/b1/empresa.mp3"              },
  { slug: "laboratorio",     es: "laboratorio",      fr: "laboratoire",           notionId: "es_b1_science",     audio: "/audio/espagnol/science/b1/laboratorio.mp3"          },
  { slug: "experimento",     es: "experimento",      fr: "expérience",            notionId: "es_b1_science",     audio: "/audio/espagnol/science/b1/experimento.mp3"          },
  // Finance
  { slug: "inversion",       es: "inversión",        fr: "investissement",        notionId: "es_b1_finance",     audio: "/audio/espagnol/finance/b1/inversion.mp3" },
  { slug: "prestamo",        es: "préstamo",         fr: "prêt",                  notionId: "es_b1_finance",     audio: "/audio/espagnol/finance/b1/prestamo.mp3"  },
  { slug: "interes",         es: "interés",          fr: "intérêt",               notionId: "es_b1_finance",     audio: "/audio/espagnol/finance/b1/interes.mp3"   },
  { slug: "beneficio",       es: "beneficio",        fr: "bénéfice",              notionId: "es_b1_finance",     audio: "/audio/espagnol/finance/b1/beneficio.mp3" },
  { slug: "perdida",         es: "pérdida",          fr: "perte",                 notionId: "es_b1_finance",     audio: "/audio/espagnol/finance/b1/perdida.mp3"   },
  { slug: "impuesto",        es: "impuesto",         fr: "impôt",                 notionId: "es_b1_finance",     audio: "/audio/espagnol/finance/b1/impuesto.mp3"  },
  { slug: "mercado",         es: "mercado",          fr: "marché",                notionId: "es_b1_finance",     audio: "/audio/espagnol/finance/b1/mercado.mp3"   },
  { slug: "ahorro",          es: "ahorro",           fr: "épargne",               notionId: "es_b1_finance",     audio: "/audio/espagnol/finance/b1/ahorro.mp3"    },
  { slug: "deuda",           es: "deuda",            fr: "dette",                 notionId: "es_b1_finance",     audio: "/audio/espagnol/finance/b1/deuda.mp3"     },
  { slug: "hipoteca",        es: "hipoteca",         fr: "prêt immobilier",       notionId: "es_b1_finance",     audio: "/audio/espagnol/finance/b1/hipoteca.mp3"  },
  // Géographie physique
  { slug: "clima",           es: "clima",            fr: "climat",                notionId: "es_b1_physical_geography", audio: "/audio/espagnol/physical_geography/b1/clima.mp3"      },
  { slug: "desierto",        es: "desierto",         fr: "désert",                notionId: "es_b1_physical_geography", audio: "/audio/espagnol/physical_geography/b1/desierto.mp3"   },
  { slug: "valle",           es: "valle",            fr: "vallée",                notionId: "es_b1_physical_geography", audio: "/audio/espagnol/physical_geography/b1/valle.mp3"      },
  { slug: "cordillera",      es: "cordillera",       fr: "chaîne de montagnes",   notionId: "es_b1_physical_geography", audio: "/audio/espagnol/physical_geography/b1/cordillera.mp3" },
  { slug: "meseta",          es: "meseta",           fr: "plateau",               notionId: "es_b1_physical_geography", audio: "/audio/espagnol/physical_geography/b1/meseta.mp3"     },
  { slug: "costa",           es: "costa",            fr: "côte",                  notionId: "es_b1_physical_geography", audio: "/audio/espagnol/physical_geography/b1/costa.mp3"      },
  { slug: "peninsula",       es: "península",        fr: "péninsule",             notionId: "es_b1_physical_geography", audio: "/audio/espagnol/physical_geography/b1/peninsula.mp3"  },
  { slug: "glaciar",         es: "glaciar",          fr: "glacier",               notionId: "es_b1_physical_geography", audio: "/audio/espagnol/physical_geography/b1/glaciar.mp3"    },
  { slug: "llanura",         es: "llanura",          fr: "plaine",                notionId: "es_b1_physical_geography", audio: "/audio/espagnol/physical_geography/b1/llanura.mp3"    },
  { slug: "selva",           es: "selva",            fr: "forêt tropicale",       notionId: "es_b1_physical_geography", audio: "/audio/espagnol/physical_geography/b1/selva.mp3"      },
  // Biologie
  { slug: "celula",          es: "célula",           fr: "cellule",               notionId: "es_b1_science_biology", audio: "/audio/espagnol/science_biology/b1/celula.mp3"     },
  { slug: "oxigeno",         es: "oxígeno",          fr: "oxygène",               notionId: "es_b1_science_biology", audio: "/audio/espagnol/science_biology/b1/oxigeno.mp3"    },
  { slug: "bacteria",        es: "bacteria",         fr: "bactérie",              notionId: "es_b1_science_biology", audio: "/audio/espagnol/science_biology/b1/bacteria.mp3"   },
  { slug: "virus",           es: "virus",            fr: "virus",                 notionId: "es_b1_science_biology", audio: "/audio/espagnol/science_biology/b1/virus.mp3"      },
  { slug: "vacuna",          es: "vacuna",           fr: "vaccin",                notionId: "es_b1_science_biology", audio: "/audio/espagnol/science_biology/b1/vacuna.mp3"     },
  { slug: "cerebro",         es: "cerebro",          fr: "cerveau",               notionId: "es_b1_science_biology", audio: "/audio/espagnol/science_biology/b1/cerebro.mp3"    },
  { slug: "sangre",          es: "sangre",           fr: "sang",                  notionId: "es_b1_science_biology", audio: "/audio/espagnol/science_biology/b1/sangre.mp3"     },
  { slug: "gen",             es: "gen",              fr: "gène",                  notionId: "es_b1_science_biology", audio: "/audio/espagnol/science_biology/b1/gen.mp3"        },
  { slug: "especie",         es: "especie",          fr: "espèce",                notionId: "es_b1_science_biology", audio: "/audio/espagnol/science_biology/b1/especie.mp3"    },
  { slug: "ecosistema",      es: "ecosistema",       fr: "écosystème",            notionId: "es_b1_science_biology", audio: "/audio/espagnol/science_biology/b1/ecosistema.mp3" },
  // Sport & statistiques
  { slug: "record",          es: "récord",           fr: "record",                notionId: "es_b1_sport_stats", audio: "/audio/espagnol/sport_stats/b1/record.mp3"        },
  { slug: "velocidad",       es: "velocidad",        fr: "vitesse",               notionId: "es_b1_sport_stats", audio: "/audio/espagnol/sport_stats/b1/velocidad.mp3"     },
  { slug: "distancia",       es: "distancia",        fr: "distance",              notionId: "es_b1_sport_stats", audio: "/audio/espagnol/sport_stats/b1/distancia.mp3"     },
  { slug: "puntuacion",      es: "puntuación",       fr: "score",                 notionId: "es_b1_sport_stats", audio: "/audio/espagnol/sport_stats/b1/puntuacion.mp3"    },
  { slug: "clasificacion",   es: "clasificación",    fr: "classement",            notionId: "es_b1_sport_stats", audio: "/audio/espagnol/sport_stats/b1/clasificacion.mp3" },
  { slug: "promedio",        es: "promedio",         fr: "moyenne",               notionId: "es_b1_sport_stats", audio: "/audio/espagnol/sport_stats/b1/promedio.mp3"      },
  { slug: "resultado",       es: "resultado",        fr: "résultat",              notionId: "es_b1_sport_stats", audio: "/audio/espagnol/sport_stats/b1/resultado.mp3"     },
  { slug: "rendimiento",     es: "rendimiento",      fr: "performance",           notionId: "es_b1_sport_stats", audio: "/audio/espagnol/sport_stats/b1/rendimiento.mp3"   },
  { slug: "temporada",       es: "temporada",        fr: "saison",                notionId: "es_b1_sport_stats", audio: "/audio/espagnol/sport_stats/b1/temporada.mp3"     },
  { slug: "torneo",          es: "torneo",           fr: "tournoi",               notionId: "es_b1_sport_stats", audio: "/audio/espagnol/sport_stats/b1/torneo.mp3"        },
  // Économie (complément)
  { slug: "comercio",        es: "comercio",         fr: "commerce",              notionId: "es_b1_economy",     audio: "/audio/espagnol/economy/b1/comercio.mp3"  },
  { slug: "industria",       es: "industria",        fr: "industrie",             notionId: "es_b1_economy",     audio: "/audio/espagnol/economy/b1/industria.mp3" },
  { slug: "consumo",         es: "consumo",          fr: "consommation",          notionId: "es_b1_economy",     audio: "/audio/espagnol/economy/b1/consumo.mp3"   },
  { slug: "producto",        es: "producto",         fr: "produit",               notionId: "es_b1_economy",     audio: "/audio/espagnol/economy/b1/producto.mp3"  },
  { slug: "oferta",          es: "oferta",           fr: "offre",                 notionId: "es_b1_economy",     audio: "/audio/espagnol/economy/b1/oferta.mp3"    },
  { slug: "demanda",         es: "demanda",          fr: "demande",               notionId: "es_b1_economy",     audio: "/audio/espagnol/economy/b1/demanda.mp3"   },
  { slug: "salario",         es: "salario",          fr: "salaire",               notionId: "es_b1_economy",     audio: "/audio/espagnol/economy/b1/salario.mp3"   },
  { slug: "negocio",         es: "negocio",          fr: "affaire",               notionId: "es_b1_economy",     audio: "/audio/espagnol/economy/b1/negocio.mp3"   },
  // Médias (complément)
  { slug: "radio",           es: "radio",            fr: "radio",                 notionId: "es_b1_media",       audio: "/audio/espagnol/media/b1/radio.mp3"      },
  { slug: "noticia",         es: "noticia",          fr: "information",           notionId: "es_b1_media",       audio: "/audio/espagnol/media/b1/noticia.mp3"    },
  { slug: "revista",         es: "revista",          fr: "magazine",              notionId: "es_b1_media",       audio: "/audio/espagnol/media/b1/revista.mp3"    },
  { slug: "publicidad",      es: "publicidad",       fr: "publicité",             notionId: "es_b1_media",       audio: "/audio/espagnol/media/b1/publicidad.mp3" },
  { slug: "entrevista",      es: "entrevista",       fr: "interview",             notionId: "es_b1_media",       audio: "/audio/espagnol/media/b1/entrevista.mp3" },
  { slug: "titular",         es: "titular",          fr: "gros titre",            notionId: "es_b1_media",       audio: "/audio/espagnol/media/b1/titular.mp3"    },
  { slug: "prensa",          es: "prensa",           fr: "presse",                notionId: "es_b1_media",       audio: "/audio/espagnol/media/b1/prensa.mp3"     },
  { slug: "reportaje",       es: "reportaje",        fr: "reportage",             notionId: "es_b1_media",       audio: "/audio/espagnol/media/b1/reportaje.mp3"  },
  // Opinions (complément)
  { slug: "no_estoy_de_acuerdo", es: "no estoy de acuerdo", fr: "je ne suis pas d'accord", notionId: "es_b1_opinions", audio: "/audio/espagnol/opinions/b1/no_estoy_de_acuerdo.mp3" },
  { slug: "me_parece",       es: "me parece",        fr: "il me semble",          notionId: "es_b1_opinions",    audio: "/audio/espagnol/opinions/b1/me_parece.mp3"      },
  { slug: "punto_de_vista",  es: "punto de vista",   fr: "point de vue",          notionId: "es_b1_opinions",    audio: "/audio/espagnol/opinions/b1/punto_de_vista.mp3" },
  { slug: "argumento",       es: "argumento",        fr: "argument",              notionId: "es_b1_opinions",    audio: "/audio/espagnol/opinions/b1/argumento.mp3"      },
  { slug: "debate",          es: "debate",           fr: "débat",                 notionId: "es_b1_opinions",    audio: "/audio/espagnol/opinions/b1/debate.mp3"         },
  { slug: "razon",           es: "razón",            fr: "raison",                notionId: "es_b1_opinions",    audio: "/audio/espagnol/opinions/b1/razon.mp3"          },
  { slug: "duda",            es: "duda",             fr: "doute",                 notionId: "es_b1_opinions",    audio: "/audio/espagnol/opinions/b1/duda.mp3"           },
  // Science (complément)
  { slug: "tecnologia",      es: "tecnología",       fr: "technologie",           notionId: "es_b1_science",     audio: "/audio/espagnol/science/b1/tecnologia.mp3"     },
  { slug: "investigacion",   es: "investigación",    fr: "recherche",             notionId: "es_b1_science",     audio: "/audio/espagnol/science/b1/investigacion.mp3"  },
  { slug: "descubrimiento",  es: "descubrimiento",   fr: "découverte",            notionId: "es_b1_science",     audio: "/audio/espagnol/science/b1/descubrimiento.mp3" },
  { slug: "invento",         es: "invento",          fr: "invention",             notionId: "es_b1_science",     audio: "/audio/espagnol/science/b1/invento.mp3"        },
  { slug: "teoria",          es: "teoría",           fr: "théorie",               notionId: "es_b1_science",     audio: "/audio/espagnol/science/b1/teoria.mp3"         },
  { slug: "dato",            es: "dato",             fr: "donnée",                notionId: "es_b1_science",     audio: "/audio/espagnol/science/b1/dato.mp3"           },
  { slug: "maquina",         es: "máquina",          fr: "machine",               notionId: "es_b1_science",     audio: "/audio/espagnol/science/b1/maquina.mp3"        },
  { slug: "robot",           es: "robot",            fr: "robot",                 notionId: "es_b1_science",     audio: "/audio/espagnol/science/b1/robot.mp3"          },
] as const;

function dFr(exclude: string) { return WORDS.filter(w => w.fr !== exclude).map(w => w.fr).slice(0, 3); }
function dEs(exclude: string) { return WORDS.filter(w => w.es !== exclude).map(w => w.es).slice(0, 3); }

export const espagnolB1QuestionBank: TutorBankItemV4[] = WORDS.flatMap((word) => [
  {
    kind: "fixed" as const,
    id: `es_b1_${word.slug}_es_to_fr`,
    niveau: "b1" as const,
    matiere: "espagnol" as const,
    notionId: word.notionId,
    microId: `${word.notionId}_es_to_fr`,
    difficulty: 2 as const,
    text: `Que signifie "${word.es}" en français ?`,
    format: "qcm" as const,
    choices: [word.fr, ...dFr(word.fr)],
    expected: [word.fr],
    comparator: "mcq_exact" as const,
    explanation: `"${word.es}" = "${word.fr}".`,
  },
  {
    kind: "fixed" as const,
    id: `es_b1_${word.slug}_fr_to_es`,
    niveau: "b1" as const,
    matiere: "espagnol" as const,
    notionId: word.notionId,
    microId: `${word.notionId}_fr_to_es`,
    difficulty: 3 as const,
    text: `Comment dit-on "${word.fr}" en espagnol ?`,
    format: "qcm" as const,
    choices: [word.es, ...dEs(word.es)],
    expected: [word.es],
    comparator: "mcq_exact" as const,
    explanation: `"${word.fr}" se dit "${word.es}" en espagnol.`,
  },
  {
    kind: "fixed" as const,
    id: `es_b1_${word.slug}_listen`,
    niveau: "b1" as const,
    matiere: "espagnol" as const,
    notionId: word.notionId,
    microId: `${word.notionId}_listen`,
    difficulty: 3 as const,
    text: `🔊 Écoute et choisis la traduction française.`,
    format: "qcm" as const,
    audioSrc: word.audio,
    choices: [word.fr, ...dFr(word.fr)],
    expected: [word.fr],
    comparator: "mcq_exact" as const,
    hint: `Écoute attentivement la prononciation.`,
    explanation: `Le mot entendu est "${word.es}" (${word.fr}).`,
  },
]);
