// 3ᵉ · français — enrichissement des pools d'ÉTUDE DE LA LANGUE.
//
// TROISIÈME ET DERNIER NIVEAU DU CHANTIER cycle 4, après la 5ᵉ et la 4ᵉ. Même
// mesure partout : 7 énoncés distincts par micro-compétence produits par le
// builder, contre 32 en cycle 3 (npx --yes tsx@4
// scripts/auditer-banque-runtime.ts 3e --variete).
//
// LA RÈGLE D'ÉCRITURE ne change pas : aucun item ne commence par « Un(e) X
// est… ». On donne l'énoncé, on demande ce que la forme FAIT.
//
// CHAQUE ÉNONCÉ EST DISTINCT, y compris de ceux de la 4ᵉ et de la 5ᵉ : le
// tirage des épreuves déduplique sur le texte de la question.
//
// LES EXEMPLES SONT PRIS DANS LES ENTRÉES DE 3ᵉ — se raconter, dénoncer les
// travers de la société, agir dans la cité, la parole publique — et le niveau
// grammatical suit : voix passive, accord des verbes pronominaux, subordonnées
// circonstancielles, concordance des temps, discours indirect libre, ironie.
//
// QCM uniquement, comme tout le cycle 4.

import type { TutorBankItemFixedV4 } from "@/lib/tutor-v4/types";

function qcm(
  n: number,
  microId: string,
  notionId: string,
  difficulty: 1 | 2 | 3,
  text: string,
  choices: string[],
  correct: string,
  explanation: string,
): TutorBankItemFixedV4 {
  return {
    kind: "fixed",
    id: `3e_fr_compl_${microId}_${n}`,
    niveau: "3e",
    matiere: "francais",
    notionId,
    microId,
    difficulty,
    theme: "neutral",
    text,
    format: "qcm",
    choices,
    expected: [correct],
    comparator: "mcq_exact",
    explanation,
    tags: ["3e", "francais", notionId, microId, "qcm"],
  };
}

const V = (n: number, m: string, d: 1 | 2 | 3, t: string, c: string[], r: string, e: string) =>
  qcm(n, m, "vocabulaire", d, t, c, r, e);
const G = (n: number, m: string, d: 1 | 2 | 3, t: string, c: string[], r: string, e: string) =>
  qcm(n, m, "grammaire_phrase", d, t, c, r, e);
const C = (n: number, m: string, d: 1 | 2 | 3, t: string, c: string[], r: string, e: string) =>
  qcm(n, m, "conjugaison", d, t, c, r, e);
const D = (n: number, m: string, d: 1 | 2 | 3, t: string, c: string[], r: string, e: string) =>
  qcm(n, m, "analyse_discours", d, t, c, r, e);

export const complementsEtudeLangue3eBank: TutorBankItemFixedV4[] = [
  // ══════════════════════════════════════════════════════════════════════
  // VOCABULAIRE · inférer le sens par le contexte
  // ══════════════════════════════════════════════════════════════════════
  V(1, "3e_voc_contexte", 1,
    "« Son récit était lacunaire : des années entières manquaient. » Que veut dire « lacunaire » ?",
    ["incomplet, plein de trous", "trop long", "inventé de toutes pièces", "écrit à la main"],
    "incomplet, plein de trous",
    "La phrase qui suit donne la mesure du mot : des années manquent. Un récit lacunaire n'est pas faux, il est troué — c'est souvent le cas des souvenirs d'enfance."),
  V(2, "3e_voc_contexte", 2,
    "« Il évoqua son enfance avec une pudeur qui interdisait les questions. » Que veut dire « pudeur » ?",
    [
      "une retenue qui empêche d'en dire plus",
      "une fierté que rien n'entame",
      "une tristesse bien visible de tous",
      "une froideur nettement méprisante",
    ],
    "une retenue qui empêche d'en dire plus",
    "« Qui interdisait les questions » indique une réserve, pas un refus brutal. La pudeur est ce qui retient, chez celui qui parle comme chez celui qui écoute."),
  V(3, "3e_voc_contexte", 2,
    "« L'orateur fustigea l'indifférence de ses contemporains. » Que veut dire « fustigea » ?",
    ["critiqua violemment", "excusa", "constata sans réagir", "ignora"],
    "critiqua violemment",
    "Le complément — l'indifférence — indique ce qu'on attaque, et le contexte d'un discours public suppose de la force. Le verbe vient d'ailleurs du fouet : il frappe."),
  V(4, "3e_voc_contexte", 2,
    "« Le témoin livra un récit circonstancié de la nuit du 3 mai. » Que veut dire « circonstancié » ?",
    ["détaillé, précis point par point", "confus et mal ordonné", "très bref, en deux mots", "mensonger d'un bout à l'autre"],
    "détaillé, précis point par point",
    "La date exacte, dans la suite de la phrase, donne le ton : on est dans la précision. Un récit circonstancié rapporte les circonstances, une à une — le mot le dit."),
  V(5, "3e_voc_contexte", 3,
    "« Ses promesses, une fois de plus, se révélèrent fallacieuses. » Que veut dire « fallacieuses » ?",
    [
      "trompeuses, faites pour tromper",
      "beaucoup trop nombreuses pour être tenues",
      "difficiles à tenir jusqu'au bout du mandat",
      "prononcées à voix très basse, sans témoin",
    ],
    "trompeuses, faites pour tromper",
    "« Une fois de plus » suppose une déception qui se répète, et « se révélèrent » annonce une découverte tardive. Le mot ne dit pas seulement le faux : il dit l'intention de tromper."),
  V(6, "3e_voc_contexte", 3,
    "« La foule, d'abord houleuse, finit par se disperser sans incident. » Que veut dire « houleuse » ?",
    ["agitée", "silencieuse", "clairsemée", "joyeuse"],
    "agitée",
    "Le mot vient de la houle, ce mouvement lourd de la mer : la foule ondule et gronde. « D'abord » annonce d'ailleurs un changement — si elle finit par se disperser sans incident, c'est qu'elle avait commencé autrement."),

  // ── VOCABULAIRE · relations entre les mots ────────────────────────────
  V(1, "3e_voc_relations", 1,
    "Dans « un discours véhément », quel mot en serait le contraire ?",
    ["posé", "long", "célèbre", "écrit"],
    "posé",
    "« Véhément » dit l'emportement de celui qui parle. Son contraire doit porter sur la même chose — la manière — et non sur la durée ou la notoriété du discours."),
  V(2, "3e_voc_relations", 2,
    "Dans « une remarque perfide », quel synonyme conserve le mieux le sens ?",
    ["sournoise", "maladroite", "franche", "amusante"],
    "sournoise",
    "La perfidie ajoute au mal fait la dissimulation : on blesse sans en avoir l'air. « Maladroite » supposerait au contraire qu'on n'a pas voulu blesser."),
  V(3, "3e_voc_relations", 2,
    "Quel mot n'appartient PAS au champ lexical de la justice ?",
    ["récolte", "verdict", "plaidoirie", "témoignage"],
    "récolte",
    "Verdict, plaidoirie et témoignage se rencontrent tous dans un procès. Repérer un champ lexical, c'est voir de quel monde un texte tire ses mots — et donc de quoi il parle vraiment."),
  V(4, "3e_voc_relations", 2,
    "Quel mot n'est PAS de la même famille que les autres ?",
    ["polir", "politique", "polémique", "police"],
    "polir",
    "Politique, police et polémique remontent au grec « polis », la cité, et à « polemos », la guerre — la parenté est celle de la vie publique. « Polir » vient du latin et parle de surface lisse."),
  V(5, "3e_voc_relations", 3,
    "« Un mensonge » et « une contrevérité » : qu'est-ce qui les distingue ?",
    [
      "l'intention : le mensonge suppose qu'on sait dire le faux",
      "rien du tout : les deux mots sont interchangeables",
      "le registre : « mensonge » appartient au soutenu",
      "le nombre de personnes que cela concerne",
    ],
    "l'intention : le mensonge suppose qu'on sait dire le faux",
    "Une contrevérité peut se dire de bonne foi ; un mensonge, jamais. C'est pourquoi la presse écrit souvent « contrevérité » : le mot décrit le propos sans juger celui qui le tient."),
  V(6, "3e_voc_relations", 3,
    "Quel couple de mots ci-dessous n'entretient PAS un rapport de contraire ?",
    [
      "dénoncer / accuser",
      "louer / blâmer",
      "révéler / dissimuler",
      "libérer / asservir",
    ],
    "dénoncer / accuser",
    "Les trois autres couples s'opposent terme à terme. Dénoncer et accuser désignent le même geste, avec un écart de portée : on dénonce une situation, on accuse quelqu'un."),

  // ── VOCABULAIRE · formation des mots ──────────────────────────────────
  V(1, "3e_voc_formation", 1,
    "« Démocratie », « aristocratie », « bureaucratie » : que désigne l'élément « -cratie » ?",
    ["le pouvoir", "le peuple", "la loi", "la parole"],
    "le pouvoir",
    "Ce qui change devant le suffixe, c'est celui qui l'exerce : le peuple, les meilleurs, les bureaux. Connaitre la racine permet de comprendre un mot qu'on n'a jamais lu."),
  V(2, "3e_voc_formation", 2,
    "Dans « misanthrope » et « philanthrope », que désigne l'élément « -anthrope » ?",
    ["l'être humain", "la solitude", "la richesse", "le voyage"],
    "l'être humain",
    "Les deux préfixes disent le sentiment qu'on lui porte : misein, haïr, et philein, aimer. Molière a bâti toute une pièce sur ce seul mot."),
  V(3, "3e_voc_formation", 2,
    "Quel préfixe faut-il placer devant « juste » pour former le mot qui nomme son contraire ?",
    ["in-", "dé-", "mé-", "anti-"],
    "in-",
    "« Injuste », comme « inutile » ou « incapable ». Le préfixe in- se transforme en im- devant m, b et p — la langue évite ainsi les enchaînements difficiles à prononcer."),
  V(4, "3e_voc_formation", 2,
    "« Prévoir », « prévenir », « prédire » : que marque le préfixe pré- ?",
    ["l'antériorité", "la répétition", "la négation", "l'excès"],
    "l'antériorité",
    "À chaque fois, l'action se produit avant : voir avant, avertir avant, dire avant. Le préfixe ajoute du temps au verbe, pas de l'intensité."),
  V(5, "3e_voc_formation", 3,
    "« Bienveillance », « malveillance » : sur quel verbe ces deux noms sont-ils construits ?",
    ["vouloir", "veiller", "valoir", "venir"],
    "vouloir",
    "Les deux mots disent ce qu'on veut pour autrui — du bien ou du mal. La graphie fait penser à « veiller », mais c'est bien « vouloir » qui est à la racine, sous une forme ancienne."),
  V(6, "3e_voc_formation", 3,
    "Le mot « covoiturage » a été formé récemment. Comment ?",
    [
      "par ajout du préfixe co- au mot « voiturage »",
      "par emprunt à l'anglais",
      "par abréviation d'une expression plus longue",
      "par changement de sens d'un mot ancien",
    ],
    "par ajout du préfixe co- au mot « voiturage »",
    "Le préfixe co- dit qu'on fait ensemble, comme dans « coéquipier » ou « copropriété ». Une langue vivante fabrique ses mots nouveaux avec des pièces très anciennes."),

  // ── VOCABULAIRE · réemployer un lexique précis ────────────────────────
  V(1, "3e_voc_reemploi", 1,
    "Pour dire qu'un auteur critique la société en la faisant rire, quel mot convient ?",
    ["la satire", "l'éloge", "la biographie", "la chronique"],
    "la satire",
    "La satire attaque en amusant : c'est ce double mouvement qui la distingue du simple pamphlet. Le rire y est une arme, pas une récréation."),
  V(2, "3e_voc_reemploi", 2,
    "Quel terme désigne le récit qu'un auteur fait de sa propre vie ?",
    ["une autobiographie", "une biographie", "un portrait", "un journal de bord"],
    "une autobiographie",
    "Le préfixe auto- fait toute la différence : c'est le même récit, mais écrit par celui-là même dont on parle. Une biographie, elle, est écrite par un autre."),
  V(3, "3e_voc_reemploi", 2,
    "Dans un texte engagé, quel verbe dit le mieux qu'on rend publique une injustice ?",
    ["dénoncer", "mentionner", "raconter", "évoquer"],
    "dénoncer",
    "Mentionner et évoquer laissent le lecteur libre d'y voir ou non un problème. Dénoncer engage celui qui écrit : il désigne, et il prend le risque de désigner."),
  V(4, "3e_voc_reemploi", 2,
    "Pour dire qu'un souvenir revient sans qu'on l'ait cherché, quel verbe est le plus juste ?",
    ["il resurgit", "il apparaît", "il existe", "il se trouve"],
    "il resurgit",
    "Le verbe contient à la fois le retour et la brusquerie. C'est le mot des récits d'enfance, où la mémoire ne se commande pas."),
  V(5, "3e_voc_reemploi", 3,
    "Quel mot désigne une critique amère, écrite pour attaquer une personne ou une institution ?",
    ["un pamphlet", "un roman", "un plaidoyer", "un compte rendu"],
    "un pamphlet",
    "Le plaidoyer défend, le pamphlet attaque : les deux sont engagés, mais pas dans le même sens. Un compte rendu, lui, ne prend pas parti."),
  V(6, "3e_voc_reemploi", 3,
    "Pour qualifier un témoignage qu'on ne peut pas mettre en doute, quel adjectif convient ?",
    ["irréfutable", "invraisemblable", "indifférent", "interminable"],
    "irréfutable",
    "Le mot dit qu'on ne peut pas le réfuter, c'est-à-dire prouver qu'il est faux. Les trois autres commencent pareil et disent tout autre chose : le préfixe ne fait pas le sens."),

  // ── VOCABULAIRE · orthographe des mots étudiés ────────────────────────
  V(1, "3e_voc_orthographe", 1,
    "« Il a présenté ses … au tribunal. » Comment s'écrit le mot ?",
    ["excuses", "excuzes", "escuses", "exuses"],
    "excuses",
    "Le x note ici le son « ks » suivi du c : c'est la même famille que « excuser » et « excusable ». La lettre s en fin de mot marque le pluriel, pas le son."),
  V(2, "3e_voc_orthographe", 2,
    "« Son … pour la cause était total. » Quelle orthographe convient ?",
    ["dévouement", "dévoument", "dévouemment", "dévoûment"],
    "dévouement",
    "Les noms formés sur un verbe en -ouer gardent le e du radical avant -ment : dévouer donne dévouement, comme éternuer donne éternuement."),
  V(3, "3e_voc_orthographe", 2,
    "« Il a fait preuve d'une grande … . » Quel mot complète correctement la phrase ?",
    ["persévérance", "perséverance", "perseverance", "persévérence"],
    "persévérance",
    "Trois accents aigus, un par e du radical, et la finale en -ance comme dans « endurance » ou « vigilance ». C'est l'accent oublié au milieu du mot qui piège le plus souvent."),
  V(4, "3e_voc_orthographe", 2,
    "« Le tribunal a rendu un jugement … . » Quel adjectif est correctement écrit ?",
    ["impartial", "impartiale", "inpartial", "impartiel"],
    "impartial",
    "Le préfixe in- devient im- devant le p. Et la finale est en -ial, comme dans « partial » dont il est le contraire — pas en -iel, qui appartient à « essentiel » ou « partiel »."),
  V(5, "3e_voc_orthographe", 3,
    "« Il fit un récit … des événements. » Quelle orthographe convient ?",
    ["détaillé", "détaïllé", "detaillé", "détailler"],
    "détaillé",
    "Le groupe -aill- note le son mouillé, et l'accent aigu reste sur le premier e. Attention à la dernière proposition : « détailler » est l'infinitif, pas le participe qui qualifie le récit."),
  V(6, "3e_voc_orthographe", 3,
    "« Cette décision est … de conséquences. » Quel mot convient ?",
    ["lourde", "lourdes", "lourd", "lourdent"],
    "lourde",
    "L'adjectif s'accorde avec « décision », féminin singulier — et non avec « conséquences », qui n'est qu'un complément. C'est le nom qualifié qui commande, jamais le mot le plus proche."),

  // ══════════════════════════════════════════════════════════════════════
  // GRAMMAIRE · les constituants de la phrase
  // ══════════════════════════════════════════════════════════════════════
  G(1, "3e_gram_constituants", 1,
    "« Bien qu'il eût tout prévu, le voyage tourna mal. » Que exprime la proposition « Bien qu'il eût tout prévu » ?",
    ["l'opposition", "la cause", "la conséquence", "le but"],
    "l'opposition",
    "« Bien que » annonce que la suite va contredire ce qu'on vient de lire. La subordonnée pose une attente, la principale la déçoit — c'est le ressort de bien des récits."),
  G(2, "3e_gram_constituants", 2,
    "« Il se tut pour que personne ne devine sa peur. » Que exprime la subordonnée ?",
    ["le but", "la cause", "le temps", "la condition"],
    "le but",
    "« Pour que » indique ce qu'on cherche à obtenir, et il entraîne le subjonctif : le résultat n'est pas acquis. Avec « parce que », le verbe resterait à l'indicatif."),
  G(3, "3e_gram_constituants", 2,
    "« La salle était si pleine que des gens restaient debout. » Que exprime la subordonnée ?",
    ["la conséquence", "la comparaison entre deux réalités opposées", "l'opposition", "la condition"],
    "la conséquence",
    "Le couple « si… que » relie une intensité à ce qu'elle produit. Retirez « si », et la phrase perd son ressort : c'est l'excès qui provoque le résultat."),
  G(4, "3e_gram_constituants", 2,
    "« L'homme dont je vous ai parlé attendait dehors. » Quelle est la proposition subordonnée relative ?",
    [
      "dont je vous ai parlé",
      "L'homme attendait dehors",
      "attendait dehors",
      "je vous ai parlé attendait",
    ],
    "dont je vous ai parlé",
    "Elle commence par le pronom relatif « dont », qui remplace « de lui », et vient compléter le nom « homme ». Sa place, à l'intérieur du groupe sujet, la rend facile à manquer."),
  G(5, "3e_gram_constituants", 3,
    "« S'il avait parlé plus tôt, rien de tout cela ne serait arrivé. » Que exprime la subordonnée ?",
    ["la condition", "le temps", "la cause", "la concession"],
    "la condition",
    "« Si » ouvre une hypothèse dont la principale tire la conséquence. Les deux temps se répondent : plus-que-parfait d'un côté, conditionnel passé de l'autre."),
  G(6, "3e_gram_constituants", 3,
    "« Je crois qu'il ment » et « L'homme qu'il rencontre ment » : qu'est-ce qui distingue les deux subordonnées ?",
    [
      "la première complète le verbe, la seconde complète un nom",
      "la première est conjuguée au subjonctif présent",
      "la seconde n'est pas du tout une subordonnée",
      "rien du tout : les deux ont exactement la même fonction",
    ],
    "la première complète le verbe, la seconde complète un nom",
    "Le mot « que » ne suffit pas à identifier une subordonnée : il faut voir ce qu'elle complète. Complétive après un verbe d'opinion, relative après un nom — deux fonctions, un seul mot."),

  // ── GRAMMAIRE · fonctions ─────────────────────────────────────────────
  G(1, "3e_gram_fonctions", 1,
    "« La loi a été votée par les députés. » Quel groupe accomplit réellement l'action ?",
    ["les députés", "la loi", "personne", "a été votée"],
    "les députés",
    "À la voix passive, celui qui agit passe derrière : c'est le complément d'agent, introduit par « par ». Le sujet grammatical, lui, subit l'action au lieu de la faire."),
  G(2, "3e_gram_fonctions", 2,
    "« Les habitants furent prévenus trop tard. » Pourquoi cette phrase est-elle à la voix passive ?",
    [
      "le sujet subit l'action au lieu de l'accomplir",
      "le verbe est conjugué au passé simple",
      "il n'y a aucun complément d'objet dans la phrase",
      "le sujet du verbe est au pluriel",
    ],
    "le sujet subit l'action au lieu de l'accomplir",
    "Et l'agent n'est pas nommé : la phrase dit que quelqu'un a prévenu trop tard, sans dire qui. Le passif sert souvent, en politique comme dans la presse, à laisser cette place vide."),
  G(3, "3e_gram_fonctions", 2,
    "« Ce témoignage me parait sincère. » Quelle est la fonction de « sincère » ?",
    ["attribut du sujet", "complément d'objet direct", "épithète", "complément d'agent"],
    "attribut du sujet",
    "« Paraitre » relie une qualité à son sujet, il ne reçoit pas d'objet. Le pronom « me », lui, indique à qui la chose parait : c'est un complément d'objet indirect."),
  G(4, "3e_gram_fonctions", 2,
    "« Le rapport que la commission a remis hier accable le ministère. » Quel est le sujet de « accable » ?",
    ["le rapport", "la commission", "hier", "le ministère"],
    "le rapport",
    "La relative s'intercale entre le sujet et son verbe, et l'on prend volontiers le dernier nom lu pour le sujet. Supprimez la subordonnée : « le rapport accable le ministère » remet tout en place."),
  G(5, "3e_gram_fonctions", 3,
    "« On l'a nommée présidente du conseil. » Quelle est la fonction de « présidente » ?",
    [
      "attribut du complément d'objet",
      "complément d'objet direct",
      "apposition au sujet",
      "complément du nom « conseil »",
    ],
    "attribut du complément d'objet",
    "Le verbe « nommer » attribue une qualité à son complément, pas au sujet : c'est « la » qui devient présidente, pas « on ». Même mécanisme avec « on le croyait innocent »."),
  G(6, "3e_gram_fonctions", 3,
    "« Épuisé par la marche, il s'assit au bord du chemin. » Quel est le rôle du groupe « Épuisé par la marche » ?",
    [
      "il qualifie le sujet et en donne la cause",
      "il est le complément d'objet du verbe",
      "il est le sujet de « s'assit »",
      "il complète le nom « marche »",
    ],
    "il qualifie le sujet et en donne la cause",
    "Le participe passé détaché en tête de phrase se rapporte au sujet qui suit, et ajoute une nuance de cause : il s'assit parce qu'il était épuisé. Deux informations en trois mots."),

  // ── GRAMMAIRE · accords ───────────────────────────────────────────────
  G(1, "3e_gram_accords", 1,
    "« Elle s'est … les mains avant de partir. » Quelle forme convient ?",
    ["lavé", "lavée", "lavés", "lavées"],
    "lavé",
    "Le complément d'objet direct, « les mains », est placé APRÈS le verbe : le participe reste invariable. Comparez « elle s'est lavée », où le pronom lui-même est l'objet et commande l'accord."),
  G(2, "3e_gram_accords", 2,
    "« Ils se sont … pendant vingt ans, sans jamais se revoir. » Quelle forme du verbe « écrire » convient ?",
    ["écrit", "écrits", "écrite", "écrites"],
    "écrit",
    "On écrit À quelqu'un : le pronom « se » est ici un complément indirect, et le participe ne s'accorde pas. Le sens du verbe décide de l'accord, pas l'oreille."),
  G(3, "3e_gram_accords", 2,
    "« Les mesures que le gouvernement a … restent contestées. » Quelle forme du verbe « prendre » convient ?",
    ["prises", "pris", "prise", "prisent"],
    "prises",
    "Le pronom relatif « que » reprend « les mesures » et précède l'auxiliaire avoir : l'accord se fait au féminin pluriel. Sans déplacement, on écrirait « le gouvernement a pris des mesures »."),
  G(4, "3e_gram_accords", 2,
    "« Une foule de manifestants … rassemblée devant la mairie. » Quelle forme convient ?",
    ["s'est", "se sont", "s'étaient", "sont"],
    "s'est",
    "Le sujet est « une foule », singulier ; « de manifestants » n'est que son complément. L'accord avec le complément se rencontre chez les écrivains, mais il demande de le vouloir."),
  G(5, "3e_gram_accords", 3,
    "« Les cinq années qu'il a … en exil l'ont transformé. » Quelle forme du verbe « passer » convient ?",
    ["passées", "passé", "passés", "passée"],
    "passées",
    "Ici « les cinq années » est bien le complément d'objet direct du verbe « passer », et il est placé avant : l'accord se fait. Le piège est de le prendre pour un complément de temps."),
  G(6, "3e_gram_accords", 3,
    "« Elle s'est … de son erreur trop tard. » Quelle forme du verbe « apercevoir » convient ?",
    ["aperçue", "aperçu", "aperçus", "apercevue"],
    "aperçue",
    "« S'apercevoir de quelque chose » est un verbe essentiellement pronominal dans ce sens : le participe s'accorde alors avec le sujet. La cédille, elle, maintient le son doux devant le u."),

  // ── GRAMMAIRE · usages de l'oral et de l'écrit ────────────────────────
  G(1, "3e_gram_oral_ecrit", 1,
    "« Faut qu'on y aille. » Comment écrire cette phrase dans une copie ?",
    [
      "Il faut que nous y allions.",
      "Faut qu'on y aille.",
      "Il faut qu'on y aille.",
      "Faut que nous y allions.",
    ],
    "Il faut que nous y allions.",
    "Deux marques d'oral à corriger : le « il » impersonnel qu'on n'entend plus, et le « on » mis pour « nous ». L'écrit scolaire rétablit les deux."),
  G(2, "3e_gram_oral_ecrit", 2,
    "« C'est de ça dont je voulais parler. » Qu'est-ce qui cloche dans cette phrase ?",
    [
      "« dont » et « de ça » font double emploi",
      "« c'est » devrait être au pluriel",
      "« ça » ne peut pas commencer une phrase",
      "rien, la phrase est correcte",
    ],
    "« dont » et « de ça » font double emploi",
    "« Dont » contient déjà le « de ». On écrit « c'est ce dont je voulais parler », ou « c'est de cela que je voulais parler » — jamais les deux."),
  G(3, "3e_gram_oral_ecrit", 2,
    "Laquelle de ces phrases relève d'un usage écrit soigné ?",
    [
      "Je ne sais pas ce qu'il veut.",
      "Je sais pas ce qu'il veut.",
      "Je sais pas c'qu'il veut.",
      "Ce qu'il veut, j'sais pas.",
    ],
    "Je ne sais pas ce qu'il veut.",
    "La négation est complète et rien n'est élidé. Les trois autres notent une prononciation : elles ne s'écrivent que dans un dialogue, pour faire entendre une voix."),
  G(4, "3e_gram_oral_ecrit", 2,
    "« Le maire, il a rien dit. » Quelles sont les deux marques d'oral dans cette phrase ?",
    [
      "la reprise du sujet par « il » et la négation incomplète",
      "l'absence de complément et l'emploi du passé composé",
      "la virgule mal placée et le mot « maire »",
      "l'ordre des mots et le temps auquel est le verbe",
    ],
    "la reprise du sujet par « il » et la négation incomplète",
    "L'oral annonce le thème puis le reprend par un pronom : c'est efficace pour la voix, redondant pour l'œil. À l'écrit : « Le maire n'a rien dit. »"),
  G(5, "3e_gram_oral_ecrit", 3,
    "Dans un texte argumentatif, quelle formulation convient ?",
    [
      "Cette mesure parait difficilement applicable.",
      "Cette mesure, elle est carrément inapplicable.",
      "Franchement, cette mesure ça marchera jamais.",
      "Cette mesure ? Impossible, point.",
    ],
    "Cette mesure parait difficilement applicable.",
    "L'écrit argumentatif nuance au lieu d'asséner, et se passe des marques d'oralité. « Parait » et « difficilement » laissent d'ailleurs la place à la discussion — ce qui est le but d'un débat."),
  G(6, "3e_gram_oral_ecrit", 3,
    "Pourquoi un romancier peut-il écrire « Y avait personne, ce soir-là » ?",
    [
      "parce qu'il fait entendre la voix d'un personnage",
      "parce que la règle d'écriture a changé tout récemment",
      "parce que la phrase est conjuguée à un temps du passé",
      "parce qu'un roman n'obéit à aucune règle de langue",
    ],
    "parce qu'il fait entendre la voix d'un personnage",
    "L'écart est volontaire et il produit un effet : on entend quelqu'un. La même phrase dans une copie ne produirait rien du tout — c'est l'intention qui change tout."),

  // ══════════════════════════════════════════════════════════════════════
  // CONJUGAISON · identifier temps, mode et personne
  // ══════════════════════════════════════════════════════════════════════
  C(1, "3e_conj_identifier", 1,
    "« Nous aurons terminé avant la nuit. » Quel est le temps de ce verbe ?",
    ["le futur antérieur", "le futur simple", "le passé composé", "le conditionnel passé"],
    "le futur antérieur",
    "Auxiliaire au futur simple plus participe passé : le futur antérieur situe une action avant une autre, toutes deux à venir. « Avant la nuit » le confirme."),
  C(2, "3e_conj_identifier", 2,
    "« En sortant, il claqua la porte. » Quelle est la forme verbale « en sortant » ?",
    ["un gérondif", "un participe présent seul", "un infinitif", "un subjonctif"],
    "un gérondif",
    "Le gérondif se reconnaît à la préposition « en » devant la forme en -ant. Il indique que les deux actions sont simultanées et se rapportent au même sujet."),
  C(3, "3e_conj_identifier", 2,
    "« Il aurait fallu le prévenir. » Quel est le temps de « aurait fallu » ?",
    ["le conditionnel passé", "le plus-que-parfait", "le futur antérieur", "le subjonctif passé"],
    "le conditionnel passé",
    "L'auxiliaire est au conditionnel présent. Le temps sert ici au regret : on parle de ce qui n'a pas été fait et qu'on ne peut plus faire."),
  C(4, "3e_conj_identifier", 2,
    "« Bien qu'elle sache la vérité, elle se tut. » À quel mode « sache » est-il ?",
    ["au subjonctif", "à l'indicatif", "au conditionnel", "à l'impératif"],
    "au subjonctif",
    "« Bien que » impose toujours le subjonctif. Le fait est pourtant certain — elle sait — mais la conjonction commande la forme, quel que soit le degré de réalité."),
  C(5, "3e_conj_identifier", 3,
    "« Il fallut qu'elle partît sur-le-champ. » À quel temps « partît » est-il ?",
    [
      "à l'imparfait du subjonctif",
      "au passé simple",
      "à l'imparfait de l'indicatif",
      "au conditionnel présent",
    ],
    "à l'imparfait du subjonctif",
    "L'accent circonflexe sur le i, à la troisième personne, en est la marque. On ne l'écrit plus guère, mais on le lit chez les auteurs du XIXᵉ siècle — le reconnaitre suffit."),
  C(6, "3e_conj_identifier", 3,
    "Entre « il conclut hier » et « il conclut chaque fois », qu'est-ce qui distingue les deux formes ?",
    [
      "le complément de temps : la forme est la même aux deux temps",
      "l'accent, qui n'est présent que dans un seul des deux cas",
      "la personne à laquelle le verbe est conjugué",
      "rien du tout : c'est deux fois le même présent de l'indicatif",
    ],
    "le complément de temps : la forme est la même aux deux temps",
    "Certains verbes du troisième groupe ont la même forme aux deux temps à la troisième personne. Seul le contexte tranche — c'est un des rares cas où la grammaire seule ne suffit pas."),

  // ── CONJUGAISON · composer les formes ─────────────────────────────────
  C(1, "3e_conj_composer", 1,
    "« Je ne pense pas qu'il … raison. » Quelle forme du verbe « avoir » convient ?",
    ["ait", "a", "aura", "aurait"],
    "ait",
    "Un verbe d'opinion à la forme négative entraîne le subjonctif : le doute s'installe. À la forme affirmative — « je pense qu'il a raison » — l'indicatif revient."),
  C(2, "3e_conj_composer", 2,
    "« Quand il … son discours, la salle applaudit longuement. » Quelle forme du verbe « achever » convient ?",
    ["eut achevé", "eût achevé", "avait achevé", "achevait"],
    "eut achevé",
    "Le passé antérieur accompagne le passé simple de la principale : l'action est terminée juste avant. Sans accent, car il s'agit de l'indicatif, pas du subjonctif."),
  C(3, "3e_conj_composer", 2,
    "« Si nous avions su, nous … autrement. » Quelle forme du verbe « agir » convient ?",
    ["aurions agi", "aurons agi", "agirions", "avions agi"],
    "aurions agi",
    "Plus-que-parfait après « si », conditionnel passé dans la principale : c'est le système de l'irréel du passé. Les faits sont joués, on parle de ce qui aurait pu être."),
  C(4, "3e_conj_composer", 2,
    "« Il exigea que chacun … présent à l'ouverture. » Quelle forme du verbe « être » convient ?",
    ["soit", "est", "serait", "sera"],
    "soit",
    "« Exiger que » réclame le subjonctif : une exigence porte sur ce qui n'est pas encore fait. Le sujet « chacun » impose par ailleurs le singulier."),
  C(5, "3e_conj_composer", 3,
    "« À peine … -il entré que le silence se fit. » Quelle forme convient ?",
    ["fut", "était", "fût", "serait"],
    "fut",
    "« À peine » en tête entraîne l'inversion du sujet, et le passé antérieur accompagne le passé simple qui suit. L'accent circonflexe ferait basculer la phrase au subjonctif, sans raison."),
  C(6, "3e_conj_composer", 3,
    "« Elle voulait qu'on la … telle qu'elle était. » Quelle forme du verbe « prendre » convient ?",
    ["prenne", "prend", "prendrait", "prendra"],
    "prenne",
    "Le verbe « vouloir » entraîne toujours le subjonctif dans la subordonnée, quel que soit le temps de la principale. La volonté porte sur ce qui n'est pas encore acquis."),

  // ── CONJUGAISON · employer les temps selon le sens ────────────────────
  C(1, "3e_conj_employer", 1,
    "« Chaque été, nous retournions dans la maison de ma grand-mère. » Que dit l'imparfait ici ?",
    [
      "une habitude qui s'est répétée",
      "une action unique et brève",
      "une action en cours d'accomplissement",
      "une action à venir",
    ],
    "une habitude qui s'est répétée",
    "« Chaque été » ne laisse aucun doute : le temps ne raconte pas un été, il les résume tous. C'est l'imparfait des récits d'enfance, où les années se confondent."),
  C(2, "3e_conj_employer", 2,
    "Dans un récit autobiographique, que change l'emploi du présent à la place du passé simple ?",
    [
      "il rapproche la scène, comme si elle se jouait devant nous",
      "il rend le récit nettement moins clair et moins précis",
      "il indique que les faits racontés sont entièrement inventés",
      "il marque une habitude ancienne, souvent répétée autrefois",
    ],
    "il rapproche la scène, comme si elle se jouait devant nous",
    "C'est le présent de narration. L'adulte qui écrit revient à l'instant même où l'enfant vivait la scène — l'écart entre les deux disparaît, et le lecteur y entre avec lui."),
  C(3, "3e_conj_employer", 2,
    "« Selon le rapport, les travaux auraient coûté le double. » Que marque le conditionnel ?",
    [
      "que l'information est rapportée sans garantie",
      "que les travaux sont déjà tout à fait terminés",
      "qu'il s'agit d'une hypothèse tout à fait absurde",
      "qu'une condition doit d'abord être remplie",
    ],
    "que l'information est rapportée sans garantie",
    "« Selon » et le conditionnel travaillent ensemble : celui qui écrit reste à distance du chiffre. Retirer les deux reviendrait à en prendre la responsabilité."),
  C(4, "3e_conj_employer", 2,
    "« Il partira dès qu'il aura reçu la lettre. » Pourquoi le futur antérieur est-il nécessaire ?",
    [
      "parce que la réception doit précéder le départ",
      "parce que le départ est incertain",
      "parce que la phrase contient deux sujets",
      "parce que « dès que » l'exige toujours",
    ],
    "parce que la réception doit précéder le départ",
    "Les deux actions sont à venir, mais elles ne le sont pas au même degré : l'une conditionne l'autre. Le futur antérieur range le temps à l'intérieur du futur."),
  C(5, "3e_conj_employer", 3,
    "« J'aurais dû me taire. » Quelle nuance le conditionnel passé apporte-t-il ?",
    ["le regret d'une chose non faite", "une promesse", "une hypothèse encore possible", "un ordre atténué"],
    "le regret d'une chose non faite",
    "Le temps dit à la fois ce qui aurait été souhaitable et le fait que ce ne soit pas arrivé. Il n'y a plus rien à décider : c'est ce qui le sépare du conditionnel présent."),
  C(6, "3e_conj_employer", 3,
    "« Qu'il s'en aille ! » Que exprime ici le subjonctif employé seul ?",
    [
      "un ordre à la troisième personne, hors de l'impératif",
      "une hypothèse, que le conditionnel exprimerait mieux",
      "un souhait irréalisable, plutôt qu'un ordre donné",
      "une action passée, que l'imparfait suffirait à dire",
    ],
    "un ordre à la troisième personne, hors de l'impératif",
    "L'impératif n'existe qu'aux personnes à qui l'on parle. Pour commander à propos d'un absent, la langue passe par le subjonctif — c'est aussi la forme des inscriptions et des devises."),

  // ══════════════════════════════════════════════════════════════════════
  // DISCOURS · les registres de langue
  // ══════════════════════════════════════════════════════════════════════
  D(1, "3e_discours_registres", 1,
    "« Ce type raconte n'importe quoi » et « Cet homme tient des propos infondés » : qu'est-ce qui sépare ces deux phrases ?",
    [
      "le registre : le jugement est le même, la façon de le dire change",
      "le sens : les deux phrases ne disent pas du tout la même chose",
      "le temps auquel les verbes sont conjugués",
      "le nombre de personnes que le jugement vise",
    ],
    "le registre : le jugement est le même, la façon de le dire change",
    "La seconde phrase pourrait paraitre dans un journal, la première non. Le registre ne modifie pas le contenu — il décide de qui pourra l'entendre sans se braquer."),
  D(2, "3e_discours_registres", 2,
    "Dans une lettre de motivation, quelle formulation convient ?",
    [
      "Je me permets de vous adresser ma candidature.",
      "Je vous envoie mon CV, voilà.",
      "J'aimerais bien bosser chez vous.",
      "Je postule, si jamais ça vous intéresse.",
    ],
    "Je me permets de vous adresser ma candidature.",
    "La formule marque la distance et la considération, deux choses que le destinataire lira avant même le contenu. Le registre est ici le premier argument du candidat."),
  D(3, "3e_discours_registres", 2,
    "Un personnage de roman dit : « J'vais lui dire deux mots, moi. » Pourquoi l'auteur écrit-il ainsi ?",
    [
      "pour faire entendre la voix et le milieu du personnage",
      "parce qu'il ne connaît pas lui-même la règle",
      "parce que le roman est par nature un genre familier",
      "pour gagner de la place dans la page",
    ],
    "pour faire entendre la voix et le milieu du personnage",
    "Le registre devient un outil de caractérisation : on sait qui parle sans qu'on nous le dise. C'est aussi pourquoi la même phrase serait une faute dans le récit du narrateur."),
  D(4, "3e_discours_registres", 2,
    "Quel mot relève du registre soutenu ?",
    ["quérir", "chercher", "aller voir", "récupérer"],
    "quérir",
    "Le verbe ne se rencontre plus qu'à l'écrit littéraire ou dans des expressions figées. Employé aujourd'hui à l'oral, il produirait un effet — comique ou solennel selon le contexte."),
  D(5, "3e_discours_registres", 3,
    "Pourquoi un discours politique mêle-t-il souvent registre soutenu et formules très simples ?",
    [
      "pour être à la fois respecté et compris de tous",
      "parce que l'orateur hésite entre deux styles",
      "parce que le soutenu est interdit à l'oral",
      "pour allonger le discours",
    ],
    "pour être à la fois respecté et compris de tous",
    "Le soutenu installe l'autorité, le courant crée la proximité. L'alternance n'est pas une maladresse : c'est une stratégie, et elle s'analyse comme telle."),
  D(6, "3e_discours_registres", 3,
    "« Veuillez agréer, Madame, l'expression de mes salutations distinguées. » Que signale cette formule ?",
    [
      "un rapport officiel entre inconnus",
      "une amitié déjà ancienne entre les deux",
      "de l'ironie à l'égard du destinataire",
      "une plainte adressée à un supérieur direct",
    ],
    "un rapport officiel entre inconnus",
    "La formule est figée, et c'est justement ce qui la rend utile : elle clôt une lettre sans rien engager de personnel. Adressée à un ami, elle deviendrait blessante ou drôle."),

  // ── DISCOURS · les paroles rapportées ─────────────────────────────────
  D(1, "3e_discours_rapportees", 1,
    "« Elle répondit qu'elle n'y croyait plus depuis longtemps. » De quel type de discours s'agit-il ?",
    ["du discours indirect", "du discours direct", "du discours indirect libre", "d'un monologue"],
    "du discours indirect",
    "Un verbe de parole, une conjonction « que », et les paroles fondues dans la phrase du narrateur. On perd les mots exacts, on gagne la fluidité."),
  D(2, "3e_discours_rapportees", 2,
    "« Il s'arrêta net. Où allait-il donc, à cette heure, sans manteau ? » Quel procédé le narrateur emploie-t-il ?",
    [
      "le discours indirect libre : les pensées sans verbe introducteur",
      "le discours direct, avec des guillemets simplement sous-entendus",
      "une simple question que le narrateur pose directement au lecteur",
      "le discours narrativisé, résumé en un groupe nominal",
    ],
    "le discours indirect libre : les pensées sans verbe introducteur",
    "Ni guillemets ni « il se demanda si » : la voix du personnage passe directement dans le récit. C'est ce qui rend le procédé si difficile à repérer — et si efficace."),
  D(3, "3e_discours_rapportees", 2,
    "« Il jura qu'il reviendrait le lendemain. » Quelles étaient ses paroles exactes ?",
    [
      "« Je reviendrai demain. »",
      "« Je reviendrais demain. »",
      "« Il reviendra demain. »",
      "« Je revenais demain. »",
    ],
    "« Je reviendrai demain. »",
    "On défait les transformations une à une : la personne redevient « je », le conditionnel redevient futur, et « le lendemain » redevient « demain »."),
  D(4, "3e_discours_rapportees", 2,
    "Que perd-on en passant du discours direct au discours indirect ?",
    [
      "les mots exacts, le ton et l'oral",
      "le sens général de tout le propos",
      "l'identité même de celui qui parle",
      "le moment où les paroles ont été dites",
    ],
    "les mots exacts, le ton et l'oral",
    "L'indirect résume et lisse : les hésitations, les exclamations, le registre disparaissent. C'est un gain de rapidité payé par une perte de voix."),
  D(5, "3e_discours_rapportees", 3,
    "Dans un article, pourquoi un journaliste choisit-il de citer entre guillemets plutôt que de résumer ?",
    [
      "pour montrer qu'il rapporte les mots exacts, sans les reformuler",
      "pour rendre l'article sensiblement plus long",
      "parce que le résumé des propos est interdit dans la presse",
      "pour glisser son propre avis dans l'article",
    ],
    "pour montrer qu'il rapporte les mots exacts, sans les reformuler",
    "La citation engage celui qui l'a prononcée, pas celui qui la rapporte. C'est aussi une preuve : le lecteur peut juger la formule elle-même, et pas seulement ce qu'on lui en dit."),
  D(6, "3e_discours_rapportees", 3,
    "« La direction a évoqué d'éventuelles suppressions de postes. » Comment la parole est-elle rapportée ici ?",
    [
      "elle est réduite à un groupe nominal, sans les mots dits",
      "elle est citée mot pour mot, entre des guillemets",
      "elle est transposée au discours indirect libre du récit",
      "elle est reprise au discours direct, avec un tiret",
    ],
    "elle est réduite à un groupe nominal, sans les mots dits",
    "Ni subordonnée ni guillemets : le discours narrativisé résume en un mot ce qui a peut-être pris une heure. Pratique — mais impossible de vérifier ce qui a réellement été dit."),

  // ── DISCOURS · les procédés de l'argumentation ────────────────────────
  D(1, "3e_discours_argumentatif", 1,
    "Dans un texte argumentatif, qu'appelle-t-on la thèse ?",
    [
      "l'opinion que l'auteur veut faire partager",
      "le tout premier argument du texte",
      "l'exemple le plus longuement développé",
      "l'avis de celui qui n'est pas d'accord du tout",
    ],
    "l'opinion que l'auteur veut faire partager",
    "Tout le reste — arguments, exemples, concessions — travaille pour elle. Repérer la thèse en premier, c'est savoir à quoi sert chaque paragraphe qu'on lit ensuite."),
  D(2, "3e_discours_argumentatif", 2,
    "« Bravo, voilà encore une idée lumineuse : supprimer les bibliothèques. » Quel procédé l'auteur emploie-t-il ?",
    [
      "l'ironie : il dit le contraire de sa pensée",
      "la comparaison entre deux réalités opposées",
      "la concession accordée à l'adversaire",
      "l'exemple emprunté à la réalité",
    ],
    "l'ironie : il dit le contraire de sa pensée",
    "Le décalage entre l'éloge et ce qui est loué signale le renversement. L'ironie n'a pas besoin d'expliquer — mais elle suppose un lecteur capable de la voir, sinon elle se retourne."),
  D(3, "3e_discours_argumentatif", 2,
    "« Nos aînés se sont battus pour ce droit. » Sur quoi cet argument cherche-t-il à agir ?",
    [
      "sur l'émotion et le sens du devoir",
      "sur des données chiffrées et vérifiées",
      "sur l'autorité reconnue d'un spécialiste",
      "sur la seule logique du raisonnement",
    ],
    "sur l'émotion et le sens du devoir",
    "L'argument ne démontre rien : il fait honte à qui n'agirait pas. Ce n'est pas une raison de le rejeter, mais il faut savoir reconnaitre ce qui persuade de ce qui prouve."),
  D(4, "3e_discours_argumentatif", 2,
    "Lequel de ces connecteurs introduit une opposition ?",
    ["néanmoins", "ainsi", "en effet", "par conséquent"],
    "néanmoins",
    "« Ainsi » et « par conséquent » tirent une conclusion, « en effet » justifie. « Néanmoins » annonce au lecteur qu'il va falloir tourner la tête dans l'autre sens."),
  D(5, "3e_discours_argumentatif", 3,
    "« Si l'on suit ce raisonnement, il faudrait interdire les livres. » Quel procédé l'auteur emploie-t-il ?",
    [
      "il pousse la thèse adverse jusqu'à l'absurde",
      "il concède un point pour reprendre la main ensuite",
      "il donne un exemple précis, tiré de l'actualité",
      "il cite une autorité pour se dispenser de prouver",
    ],
    "il pousse la thèse adverse jusqu'à l'absurde",
    "On accepte provisoirement l'idée de l'autre pour montrer où elle mène. Le procédé est redoutable — et malhonnête dès qu'on exagère la thèse qu'on prête à l'adversaire."),
  D(6, "3e_discours_argumentatif", 3,
    "« Il semblerait que cette mesure soit prématurée. » Que produisent « il semblerait » et le subjonctif ?",
    [
      "ils atténuent l'affirmation et ouvrent la discussion",
      "ils renforcent l'affirmation et la rendent certaine",
      "ils indiquent une certitude établie scientifiquement",
      "ils signalent une citation empruntée à un autre",
    ],
    "ils atténuent l'affirmation et ouvrent la discussion",
    "C'est la modalisation : l'auteur dit la même chose en s'engageant moins. Comparez avec « cette mesure est prématurée » — le contenu ne bouge pas, le ton change du tout au tout."),
];
