import type { TutorBankItemV4 } from "@/lib/tutor-v4/types";

const WORDS = [
  { slug: "lunes",       es: "lunes",       fr: "lundi",      audio: "/audio/espagnol/days/a1/lunes.mp3"       },
  { slug: "martes",      es: "martes",      fr: "mardi",      audio: "/audio/espagnol/days/a1/martes.mp3"      },
  { slug: "miercoles",   es: "miércoles",   fr: "mercredi",   audio: "/audio/espagnol/days/a1/miercoles.mp3"   },
  { slug: "jueves",      es: "jueves",      fr: "jeudi",      audio: "/audio/espagnol/days/a1/jueves.mp3"      },
  { slug: "viernes",     es: "viernes",     fr: "vendredi",   audio: "/audio/espagnol/days/a1/viernes.mp3"     },
  { slug: "sabado",      es: "sábado",      fr: "samedi",     audio: "/audio/espagnol/days/a1/sabado.mp3"      },
  { slug: "domingo",     es: "domingo",     fr: "dimanche",   audio: "/audio/espagnol/days/a1/domingo.mp3"     },
  { slug: "enero",       es: "enero",       fr: "janvier",    audio: "/audio/espagnol/days/a1/enero.mp3"       },
  { slug: "febrero",     es: "febrero",     fr: "février",    audio: "/audio/espagnol/days/a1/febrero.mp3"     },
  { slug: "marzo",       es: "marzo",       fr: "mars",       audio: "/audio/espagnol/days/a1/marzo.mp3"       },
  { slug: "abril",       es: "abril",       fr: "avril",      audio: "/audio/espagnol/days/a1/abril.mp3"       },
  { slug: "mayo",        es: "mayo",        fr: "mai",        audio: "/audio/espagnol/days/a1/mayo.mp3"        },
  { slug: "junio",       es: "junio",       fr: "juin",       audio: "/audio/espagnol/days/a1/junio.mp3"       },
  { slug: "julio",       es: "julio",       fr: "juillet",    audio: "/audio/espagnol/days/a1/julio.mp3"       },
  { slug: "agosto",      es: "agosto",      fr: "août",       audio: "/audio/espagnol/days/a1/agosto.mp3"      },
  { slug: "septiembre",  es: "septiembre",  fr: "septembre",  audio: "/audio/espagnol/days/a1/septiembre.mp3"  },
  { slug: "octubre",     es: "octubre",     fr: "octobre",    audio: "/audio/espagnol/days/a1/octubre.mp3"     },
  { slug: "noviembre",   es: "noviembre",   fr: "novembre",   audio: "/audio/espagnol/days/a1/noviembre.mp3"   },
  { slug: "diciembre",   es: "diciembre",   fr: "décembre",   audio: "/audio/espagnol/days/a1/diciembre.mp3"   },
] as const;

function dFr(exclude: string) { return WORDS.filter(w => w.fr !== exclude).map(w => w.fr).slice(0, 3); }
function dEs(exclude: string) { return WORDS.filter(w => w.es !== exclude).map(w => w.es).slice(0, 3); }

export const daysA1EsBank: TutorBankItemV4[] = WORDS.flatMap((word) => [
  {
    kind: "fixed" as const,
    id: `es_a1_days_es_to_fr_${word.slug}`,
    niveau: "a1" as const,
    matiere: "espagnol" as const,
    notionId: "es_a1_days",
    microId: "es_a1_days_es_to_fr",
    difficulty: 1 as const,
    text: `Que signifie "${word.es}" en français ?`,
    format: "qcm" as const,
    choices: [word.fr, ...dFr(word.fr)],
    expected: [word.fr],
    comparator: "mcq_exact" as const,
    explanation: `"${word.es}" = "${word.fr}".`,
  },
  {
    kind: "fixed" as const,
    id: `es_a1_days_fr_to_es_${word.slug}`,
    niveau: "a1" as const,
    matiere: "espagnol" as const,
    notionId: "es_a1_days",
    microId: "es_a1_days_fr_to_es",
    difficulty: 2 as const,
    text: `Comment dit-on "${word.fr}" en espagnol ?`,
    format: "qcm" as const,
    choices: [word.es, ...dEs(word.es)],
    expected: [word.es],
    comparator: "mcq_exact" as const,
    explanation: `"${word.fr}" se dit "${word.es}" en espagnol.`,
  },
  {
    kind: "fixed" as const,
    id: `es_a1_days_listen_${word.slug}`,
    niveau: "a1" as const,
    matiere: "espagnol" as const,
    notionId: "es_a1_days",
    microId: "es_a1_days_listen",
    difficulty: 2 as const,
    text: `🔊 Écoute et choisis la traduction française.`,
    format: "qcm" as const,
    audioSrc: word.audio,
    choices: [word.fr, ...dFr(word.fr)],
    expected: [word.fr],
    comparator: "mcq_exact" as const,
    hint: `Écoute attentivement.`,
    explanation: `Le mot entendu est "${word.es}" (${word.fr}).`,
  },
]);
