import type { TutorBankItemV4 } from "@/lib/tutor-v4/types";

const WORDS = [
  { slug: "once",         es: "once",         fr: "onze",              audio: "/audio/espagnol/numbers/a1/once.mp3"         },
  { slug: "doce",         es: "doce",         fr: "douze",             audio: "/audio/espagnol/numbers/a1/doce.mp3"         },
  { slug: "trece",        es: "trece",        fr: "treize",            audio: "/audio/espagnol/numbers/a1/trece.mp3"        },
  { slug: "catorce",      es: "catorce",      fr: "quatorze",          audio: "/audio/espagnol/numbers/a1/catorce.mp3"      },
  { slug: "quince",       es: "quince",       fr: "quinze",            audio: "/audio/espagnol/numbers/a1/quince.mp3"       },
  { slug: "veinte",       es: "veinte",       fr: "vingt",             audio: "/audio/espagnol/numbers/a1/veinte.mp3"       },
  { slug: "treinta",      es: "treinta",      fr: "trente",            audio: "/audio/espagnol/numbers/a1/treinta.mp3"      },
  { slug: "cuarenta",     es: "cuarenta",     fr: "quarante",          audio: "/audio/espagnol/numbers/a1/cuarenta.mp3"     },
  { slug: "cincuenta",    es: "cincuenta",    fr: "cinquante",         audio: "/audio/espagnol/numbers/a1/cincuenta.mp3"    },
  { slug: "sesenta",      es: "sesenta",      fr: "soixante",          audio: "/audio/espagnol/numbers/a1/sesenta.mp3"      },
  { slug: "setenta",      es: "setenta",      fr: "soixante-dix",      audio: "/audio/espagnol/numbers/a1/setenta.mp3"      },
  { slug: "ochenta",      es: "ochenta",      fr: "quatre-vingts",     audio: "/audio/espagnol/numbers/a1/ochenta.mp3"      },
  { slug: "noventa",      es: "noventa",      fr: "quatre-vingt-dix",  audio: "/audio/espagnol/numbers/a1/noventa.mp3"      },
  { slug: "cien",         es: "cien",         fr: "cent",              audio: "/audio/espagnol/numbers/a1/cien.mp3"         },
  { slug: "mil",          es: "mil",          fr: "mille",             audio: "/audio/espagnol/numbers/a1/mil.mp3"          },
] as const;

function dFr(exclude: string) { return WORDS.filter(w => w.fr !== exclude).map(w => w.fr).slice(0, 3); }
function dEs(exclude: string) { return WORDS.filter(w => w.es !== exclude).map(w => w.es).slice(0, 3); }

export const numbersA1EsBank: TutorBankItemV4[] = WORDS.flatMap((word) => [
  {
    kind: "fixed" as const,
    id: `es_a1_numbers_es_to_fr_${word.slug}`,
    niveau: "a1" as const,
    matiere: "espagnol" as const,
    notionId: "es_a1_numbers",
    microId: "es_a1_numbers_es_to_fr",
    difficulty: 1 as const,
    text: `Que signifie "${word.es}" en français ?`,
    format: "qcm" as const,
    choices: [word.fr, ...dFr(word.fr)],
    expected: [word.fr],
    comparator: "mcq_exact" as const,
    explanation: `"${word.es}" = "${word.fr}".`,
  },
  {
    kind: "fixed" as const,
    id: `es_a1_numbers_fr_to_es_${word.slug}`,
    niveau: "a1" as const,
    matiere: "espagnol" as const,
    notionId: "es_a1_numbers",
    microId: "es_a1_numbers_fr_to_es",
    difficulty: 2 as const,
    text: `Comment dit-on "${word.fr}" en espagnol ?`,
    format: "qcm" as const,
    choices: [word.es, ...dEs(word.es)],
    expected: [word.es],
    comparator: "mcq_exact" as const,
    explanation: `"${word.fr}" se dit "${word.es}" en espagnol.`,
  },
  {
    kind: "fixed" as const,
    id: `es_a1_numbers_listen_${word.slug}`,
    niveau: "a1" as const,
    matiere: "espagnol" as const,
    notionId: "es_a1_numbers",
    microId: "es_a1_numbers_listen",
    difficulty: 2 as const,
    text: `🔊 Écoute et choisis la traduction française.`,
    format: "qcm" as const,
    audioSrc: word.audio,
    choices: [word.fr, ...dFr(word.fr)],
    expected: [word.fr],
    comparator: "mcq_exact" as const,
    hint: `Écoute attentivement.`,
    explanation: `Le nombre entendu est "${word.es}" (${word.fr}).`,
  },
]);
