import type { TutorBankItemV4 } from "@/lib/tutor-v4/types";

export const mathsAdulteQuestionBank: TutorBankItemV4[] = [
  {
    kind: "fixed",
    id: "adulte_calcul_total_001",
    niveau: "adulte",
    matiere: "maths",
    notionId: "calcul_mental_utile",
    microId: "adulte_calcul_mental_total",
    difficulty: 1,
    theme: "reunion",
    text: "Au marche, tu prends 12 euros de fruits et 8 euros de legumes. Quel est le total ?",
    format: "short",
    expected: ["20", "20 euros"],
    comparator: "number_equal",
    hint: "Additionne 12 et 8.",
    explanation: "12 + 8 = 20 euros.",
    tags: ["adulte", "courses", "marche"],
  },
  {
    kind: "fixed",
    id: "adulte_calcul_total_002",
    niveau: "adulte",
    matiere: "maths",
    notionId: "calcul_mental_utile",
    microId: "adulte_calcul_mental_total",
    difficulty: 1,
    theme: "neutral",
    text: "A la caisse : 18 euros, 7 euros et 5 euros. Total a payer ?",
    format: "short",
    expected: ["30", "30 euros"],
    comparator: "number_equal",
    hint: "Regroupe 18 + 7, puis ajoute 5.",
    explanation: "18 + 7 + 5 = 30 euros.",
    tags: ["adulte", "courses"],
  },
  {
    kind: "fixed",
    id: "adulte_difference_001",
    niveau: "adulte",
    matiere: "maths",
    notionId: "calcul_mental_utile",
    microId: "adulte_calcul_difference",
    difficulty: 1,
    theme: "neutral",
    text: "Tu paies 32 euros avec un billet de 50 euros. Combien doit-on te rendre ?",
    format: "short",
    expected: ["18", "18 euros"],
    comparator: "number_equal",
    hint: "Calcule 50 - 32.",
    explanation: "50 - 32 = 18 euros.",
    tags: ["adulte", "monnaie"],
  },
  {
    kind: "fixed",
    id: "adulte_estimer_001",
    niveau: "adulte",
    matiere: "maths",
    notionId: "calcul_mental_utile",
    microId: "adulte_calcul_estimer",
    difficulty: 2,
    theme: "neutral",
    text: "Pour estimer vite : 19 euros + 31 euros, c'est environ ?",
    format: "qcm",
    choices: ["30 euros", "50 euros", "70 euros"],
    expected: ["50 euros"],
    comparator: "mcq_exact",
    hint: "19 est proche de 20, 31 est proche de 30.",
    explanation: "20 + 30 = 50, donc l'estimation est 50 euros.",
    tags: ["adulte", "estimation"],
  },
  {
    kind: "fixed",
    id: "adulte_budget_reste_001",
    niveau: "adulte",
    matiere: "maths",
    notionId: "argent_budget",
    microId: "adulte_budget_reste",
    difficulty: 2,
    theme: "neutral",
    text: "Tu as 80 euros de budget. Tu depenses 35 euros. Combien reste-t-il ?",
    format: "short",
    expected: ["45", "45 euros"],
    comparator: "number_equal",
    hint: "Soustrais la depense au budget.",
    explanation: "80 - 35 = 45 euros.",
    tags: ["adulte", "budget"],
  },
  {
    kind: "fixed",
    id: "adulte_budget_plusieurs_001",
    niveau: "adulte",
    matiere: "maths",
    notionId: "argent_budget",
    microId: "adulte_budget_plusieurs_depenses",
    difficulty: 2,
    theme: "neutral",
    text: "Budget 150 euros. Courses 48 euros, essence 32 euros. Combien reste-t-il ?",
    format: "short",
    expected: ["70", "70 euros"],
    comparator: "number_equal",
    hint: "Additionne les depenses, puis soustrais.",
    explanation: "48 + 32 = 80, puis 150 - 80 = 70 euros.",
    tags: ["adulte", "budget", "essence"],
  },
  {
    kind: "fixed",
    id: "adulte_prix_unitaire_001",
    niveau: "adulte",
    matiere: "maths",
    notionId: "prix_comparer",
    microId: "adulte_prix_unitaire",
    difficulty: 2,
    theme: "neutral",
    text: "2 kg de riz coutent 6 euros. Quel est le prix pour 1 kg ?",
    format: "short",
    expected: ["3", "3 euros"],
    comparator: "number_equal",
    hint: "Divise 6 euros par 2 kg.",
    explanation: "6 / 2 = 3 euros par kg.",
    tags: ["adulte", "prix", "kilo"],
  },
  {
    kind: "fixed",
    id: "adulte_comparer_offres_001",
    niveau: "adulte",
    matiere: "maths",
    notionId: "prix_comparer",
    microId: "adulte_comparer_offres",
    difficulty: 2,
    theme: "neutral",
    text: "Quel est le moins cher au kilo : 2 kg pour 6 euros ou 3 kg pour 12 euros ?",
    format: "qcm",
    choices: ["2 kg pour 6 euros", "3 kg pour 12 euros", "C'est pareil"],
    expected: ["2 kg pour 6 euros"],
    comparator: "mcq_exact",
    hint: "Calcule le prix de 1 kg dans chaque offre.",
    explanation: "6 / 2 = 3 euros/kg. 12 / 3 = 4 euros/kg. Le premier est moins cher.",
    tags: ["adulte", "prix", "comparaison"],
  },
  {
    kind: "fixed",
    id: "adulte_pourcentage_10_001",
    niveau: "adulte",
    matiere: "maths",
    notionId: "pourcentages_quotidien",
    microId: "adulte_pourcentage_10",
    difficulty: 1,
    theme: "neutral",
    text: "10 % de 70 euros, c'est combien ?",
    format: "short",
    expected: ["7", "7 euros"],
    comparator: "number_equal",
    hint: "10 %, c'est un dixieme.",
    explanation: "70 / 10 = 7 euros.",
    tags: ["adulte", "pourcentage"],
  },
  {
    kind: "fixed",
    id: "adulte_pourcentage_10_002",
    niveau: "adulte",
    matiere: "maths",
    notionId: "pourcentages_quotidien",
    microId: "adulte_pourcentage_10",
    difficulty: 2,
    theme: "neutral",
    text: "Sur 120 euros de courses, 10 % representent combien ?",
    format: "short",
    expected: ["12", "12 euros"],
    comparator: "number_equal",
    hint: "Divise 120 par 10.",
    explanation: "120 / 10 = 12 euros.",
    tags: ["adulte", "pourcentage", "courses"],
  },
  {
    kind: "fixed",
    id: "adulte_pourcentage_20_001",
    niveau: "adulte",
    matiere: "maths",
    notionId: "pourcentages_quotidien",
    microId: "adulte_pourcentage_20_25_50",
    difficulty: 2,
    theme: "neutral",
    text: "20 % de 50 euros, c'est combien ?",
    format: "short",
    expected: ["10", "10 euros"],
    comparator: "number_equal",
    hint: "20 %, c'est un cinquieme.",
    explanation: "50 / 5 = 10 euros.",
    tags: ["adulte", "pourcentage"],
  },
  {
    kind: "fixed",
    id: "adulte_pourcentage_25_001",
    niveau: "adulte",
    matiere: "maths",
    notionId: "pourcentages_quotidien",
    microId: "adulte_pourcentage_20_25_50",
    difficulty: 2,
    theme: "neutral",
    text: "25 % de 80 euros, c'est combien ?",
    format: "short",
    expected: ["20", "20 euros"],
    comparator: "number_equal",
    hint: "25 %, c'est un quart.",
    explanation: "80 / 4 = 20 euros.",
    tags: ["adulte", "pourcentage"],
  },
  {
    kind: "fixed",
    id: "adulte_pourcentage_50_001",
    niveau: "adulte",
    matiere: "maths",
    notionId: "pourcentages_quotidien",
    microId: "adulte_pourcentage_20_25_50",
    difficulty: 1,
    theme: "neutral",
    text: "50 % de 36 euros, c'est combien ?",
    format: "short",
    expected: ["18", "18 euros"],
    comparator: "number_equal",
    hint: "50 %, c'est la moitie.",
    explanation: "36 / 2 = 18 euros.",
    tags: ["adulte", "pourcentage"],
  },
  {
    kind: "fixed",
    id: "adulte_remise_001",
    niveau: "adulte",
    matiere: "maths",
    notionId: "pourcentages_quotidien",
    microId: "adulte_remise",
    difficulty: 2,
    theme: "neutral",
    text: "Un article coute 40 euros. Il y a 10 % de remise. Montant de la remise ?",
    format: "short",
    expected: ["4", "4 euros"],
    comparator: "number_equal",
    hint: "10 %, c'est un dixieme.",
    explanation: "40 / 10 = 4 euros de remise.",
    tags: ["adulte", "remise"],
  },
  {
    kind: "fixed",
    id: "adulte_remise_002",
    niveau: "adulte",
    matiere: "maths",
    notionId: "pourcentages_quotidien",
    microId: "adulte_remise",
    difficulty: 2,
    theme: "neutral",
    text: "Une paire de chaussures a 60 euros a -20 %. Montant de la remise ?",
    format: "short",
    expected: ["12", "12 euros"],
    comparator: "number_equal",
    hint: "20 %, c'est un cinquieme.",
    explanation: "60 / 5 = 12 euros.",
    tags: ["adulte", "remise"],
  },
  {
    kind: "fixed",
    id: "adulte_prix_apres_remise_001",
    niveau: "adulte",
    matiere: "maths",
    notionId: "pourcentages_quotidien",
    microId: "adulte_prix_apres_remise",
    difficulty: 3,
    theme: "neutral",
    text: "Un panier coute 50 euros. Remise de 10 %. Quel est le prix final ?",
    format: "short",
    expected: ["45", "45 euros"],
    comparator: "number_equal",
    hint: "Calcule 10 % puis enleve la remise.",
    explanation: "10 % de 50 = 5, donc 50 - 5 = 45 euros.",
    tags: ["adulte", "prix-final", "remise"],
  },
  {
    kind: "fixed",
    id: "adulte_prix_apres_remise_002",
    niveau: "adulte",
    matiere: "maths",
    notionId: "pourcentages_quotidien",
    microId: "adulte_prix_apres_remise",
    difficulty: 3,
    theme: "neutral",
    text: "Un appareil coute 100 euros. Remise de 25 %. Prix final ?",
    format: "short",
    expected: ["75", "75 euros"],
    comparator: "number_equal",
    hint: "25 %, c'est un quart.",
    explanation: "25 % de 100 = 25. Prix final : 100 - 25 = 75 euros.",
    tags: ["adulte", "prix-final", "remise"],
  },
  {
    kind: "fixed",
    id: "adulte_pourcentage_augmentation_001",
    niveau: "adulte",
    matiere: "maths",
    notionId: "pourcentages_quotidien",
    microId: "adulte_pourcentage_augmentation",
    difficulty: 3,
    theme: "neutral",
    text: "Une facture de 80 euros augmente de 10 %. Nouveau montant ?",
    format: "short",
    expected: ["88", "88 euros"],
    comparator: "number_equal",
    hint: "10 % de 80 vaut 8, puis ajoute.",
    explanation: "80 + 8 = 88 euros.",
    tags: ["adulte", "pourcentage", "hausse"],
  },
  {
    kind: "fixed",
    id: "adulte_recette_001",
    niveau: "adulte",
    matiere: "maths",
    notionId: "proportionnalite_pratique",
    microId: "adulte_recette",
    difficulty: 2,
    theme: "cuisine",
    text: "Une recette pour 2 personnes demande 300 g de riz. Pour 4 personnes ?",
    format: "short",
    expected: ["600", "600 g"],
    comparator: "number_equal",
    hint: "4 personnes, c'est deux fois plus.",
    explanation: "300 x 2 = 600 g.",
    tags: ["adulte", "recette"],
  },
  {
    kind: "fixed",
    id: "adulte_dose_quantite_001",
    niveau: "adulte",
    matiere: "maths",
    notionId: "proportionnalite_pratique",
    microId: "adulte_dose_quantite",
    difficulty: 2,
    theme: "cuisine",
    text: "Pour 3 personnes, il faut 600 g de carry. Pour 6 personnes, combien faut-il en grammes ?",
    format: "short",
    expected: ["1200", "1200 g"],
    comparator: "number_equal",
    hint: "6 personnes, c'est le double de 3.",
    explanation: "600 x 2 = 1200 g.",
    tags: ["adulte", "recette", "reunion"],
  },
  {
    kind: "fixed",
    id: "adulte_fraction_part_001",
    niveau: "adulte",
    matiere: "maths",
    notionId: "fractions_ratios",
    microId: "adulte_fraction_part",
    difficulty: 1,
    theme: "neutral",
    text: "La moitie de 36 euros, c'est combien ?",
    format: "short",
    expected: ["18", "18 euros"],
    comparator: "number_equal",
    hint: "La moitie, c'est diviser par 2.",
    explanation: "36 / 2 = 18 euros.",
    tags: ["adulte", "moitie"],
  },
  {
    kind: "fixed",
    id: "adulte_fraction_part_002",
    niveau: "adulte",
    matiere: "maths",
    notionId: "fractions_ratios",
    microId: "adulte_fraction_part",
    difficulty: 2,
    theme: "neutral",
    text: "Le quart de 48 euros, c'est combien ?",
    format: "short",
    expected: ["12", "12 euros"],
    comparator: "number_equal",
    hint: "Le quart, c'est diviser par 4.",
    explanation: "48 / 4 = 12 euros.",
    tags: ["adulte", "quart"],
  },
  {
    kind: "fixed",
    id: "adulte_partage_montant_001",
    niveau: "adulte",
    matiere: "maths",
    notionId: "fractions_ratios",
    microId: "adulte_partage_montant",
    difficulty: 2,
    theme: "neutral",
    text: "Trois personnes partagent 60 euros. Combien chacune recoit ?",
    format: "short",
    expected: ["20", "20 euros"],
    comparator: "number_equal",
    hint: "Divise 60 par 3.",
    explanation: "60 / 3 = 20 euros.",
    tags: ["adulte", "partage"],
  },
  {
    kind: "fixed",
    id: "adulte_conversion_mesure_001",
    niveau: "adulte",
    matiere: "maths",
    notionId: "mesures_conversions",
    microId: "adulte_conversion_mesure",
    difficulty: 2,
    theme: "cuisine",
    text: "1,5 L d'eau, cela fait combien de cL ?",
    format: "short",
    expected: ["150", "150 cL", "150cl"],
    comparator: "number_equal",
    hint: "1 L = 100 cL.",
    explanation: "1,5 x 100 = 150 cL.",
    tags: ["adulte", "mesure"],
  },
  {
    kind: "fixed",
    id: "adulte_conversion_mesure_002",
    niveau: "adulte",
    matiere: "maths",
    notionId: "mesures_conversions",
    microId: "adulte_conversion_mesure",
    difficulty: 2,
    theme: "cuisine",
    text: "500 g, cela fait combien de kg ?",
    format: "short",
    expected: ["0,5", "0.5", "0,5 kg", "0.5 kg"],
    comparator: "number_equal",
    hint: "1000 g = 1 kg.",
    explanation: "500 g = 0,5 kg.",
    tags: ["adulte", "mesure"],
  },
  {
    kind: "fixed",
    id: "adulte_conversion_distance_001",
    niveau: "adulte",
    matiere: "maths",
    notionId: "mesures_conversions",
    microId: "adulte_conversion_distance",
    difficulty: 2,
    theme: "neutral",
    text: "2,5 km, cela fait combien de metres ?",
    format: "short",
    expected: ["2500", "2500 m"],
    comparator: "number_equal",
    hint: "1 km = 1000 m.",
    explanation: "2,5 x 1000 = 2500 m.",
    tags: ["adulte", "distance"],
  },
  {
    kind: "fixed",
    id: "adulte_horaire_duree_001",
    niveau: "adulte",
    matiere: "maths",
    notionId: "durees_trajets",
    microId: "adulte_horaire_duree",
    difficulty: 2,
    theme: "neutral",
    text: "Tu pars a 14 h 20 pour un trajet de 45 minutes. Heure d'arrivee ?",
    format: "short",
    expected: ["15h05", "15 h 05", "15:05", "15h5"],
    comparator: "exact_text",
    hint: "Ajoute 40 minutes, puis 5 minutes.",
    explanation: "14 h 20 + 45 min = 15 h 05.",
    tags: ["adulte", "trajet"],
  },
  {
    kind: "fixed",
    id: "adulte_horaire_attente_001",
    niveau: "adulte",
    matiere: "maths",
    notionId: "durees_trajets",
    microId: "adulte_horaire_attente",
    difficulty: 2,
    theme: "neutral",
    text: "Le bus passe a 9 h 15. Il est 8 h 50. Temps d'attente ?",
    format: "short",
    expected: ["25", "25 min", "25 minutes"],
    comparator: "number_equal",
    hint: "De 8 h 50 a 9 h, il y a 10 min, puis 15 min.",
    explanation: "10 + 15 = 25 minutes.",
    tags: ["adulte", "horaire"],
  },
  {
    kind: "fixed",
    id: "adulte_tableau_lire_001",
    niveau: "adulte",
    matiere: "maths",
    notionId: "donnees_tableaux",
    microId: "adulte_tableau_lire",
    difficulty: 2,
    theme: "neutral",
    text: "Dans un budget : alimentation 220 euros, transport 80 euros, loisirs 60 euros. Quelle depense est la plus elevee ?",
    format: "qcm",
    choices: ["Alimentation", "Transport", "Loisirs"],
    expected: ["Alimentation"],
    comparator: "mcq_exact",
    hint: "Compare les trois montants.",
    explanation: "220 euros est plus grand que 80 euros et 60 euros.",
    tags: ["adulte", "donnees", "budget"],
  },
  {
    kind: "fixed",
    id: "adulte_tableau_comparer_001",
    niveau: "adulte",
    matiere: "maths",
    notionId: "donnees_tableaux",
    microId: "adulte_tableau_comparer",
    difficulty: 2,
    theme: "neutral",
    text: "Factures : eau 45 euros, telephone 29 euros, electricite 72 euros. Laquelle est la plus basse ?",
    format: "qcm",
    choices: ["Eau", "Telephone", "Electricite"],
    expected: ["Telephone"],
    comparator: "mcq_exact",
    hint: "Cherche le plus petit montant.",
    explanation: "29 euros est le plus petit montant.",
    tags: ["adulte", "donnees", "factures"],
  },
  {
    kind: "fixed",
    id: "adulte_moyenne_001",
    niveau: "adulte",
    matiere: "maths",
    notionId: "statistiques_simples",
    microId: "adulte_moyenne",
    difficulty: 3,
    theme: "neutral",
    text: "Sur trois semaines, tu economises 10 euros, 20 euros puis 30 euros. Moyenne par semaine ?",
    format: "short",
    expected: ["20", "20 euros"],
    comparator: "number_equal",
    hint: "Additionne puis divise par 3.",
    explanation: "10 + 20 + 30 = 60, puis 60 / 3 = 20 euros.",
    tags: ["adulte", "moyenne"],
  },
  {
    kind: "fixed",
    id: "adulte_stat_total_001",
    niveau: "adulte",
    matiere: "maths",
    notionId: "statistiques_simples",
    microId: "adulte_stat_total",
    difficulty: 2,
    theme: "neutral",
    text: "Depenses de la semaine : 25 euros, 18 euros, 12 euros. Total ?",
    format: "short",
    expected: ["55", "55 euros"],
    comparator: "number_equal",
    hint: "Additionne les trois montants.",
    explanation: "25 + 18 + 12 = 55 euros.",
    tags: ["adulte", "total", "donnees"],
  },
];

export function getMathAdulteQuestionBank(args?: {
  notionId?: string | null;
  microId?: string | null;
}): TutorBankItemV4[] {
  let bank = mathsAdulteQuestionBank;

  if (args?.notionId) {
    bank = bank.filter((item) => item.notionId === args.notionId);
  }

  if (args?.microId) {
    bank = bank.filter((item) => item.microId === args.microId);
  }

  return bank;
}
