import type { TutorBankItemV4 } from "@/lib/tutor-v4/types";

export const mathsAdulteQuestionBank: TutorBankItemV4[] = [
  {
    kind: "fixed",
    id: "adulte_calcul_total_001",
    niveau: "adulte",
    matiere: "maths",
    notionId: "calcul_mental_utile",
    microId: "adulte_calcul_mental_total",
    difficulty: 1,
    theme: "neutral",
    text: "Au marché, tu prends 12 euros de fruits et 8 euros de légumes. Quel est le total ?",
    format: "short",
    expected: ["20", "20 euros"],
    comparator: "number_equal",
    hint: "Additionne 12 et 8.",
    explanation: "12 + 8 = 20 euros.",
    tags: ["adulte", "quotidien", "addition"],
  },
  {
    kind: "fixed",
    id: "adulte_budget_reste_001",
    niveau: "adulte",
    matiere: "maths",
    notionId: "argent_budget",
    microId: "adulte_budget_reste",
    difficulty: 2,
    theme: "neutral",
    text: "Tu as 50 euros de budget. Tu dépenses 18 euros puis 12 euros. Combien reste-t-il ?",
    format: "short",
    expected: ["20", "20 euros"],
    comparator: "number_equal",
    hint: "Calcule d'abord la dépense totale.",
    explanation: "18 + 12 = 30, puis 50 - 30 = 20 euros.",
    tags: ["adulte", "budget"],
  },
  {
    kind: "fixed",
    id: "adulte_prix_unitaire_001",
    niveau: "adulte",
    matiere: "maths",
    notionId: "prix_comparer",
    microId: "adulte_prix_unitaire",
    difficulty: 2,
    theme: "neutral",
    text: "Quel est le moins cher au kilo : 2 kg pour 6 euros ou 3 kg pour 12 euros ?",
    format: "qcm",
    choices: ["2 kg pour 6 euros", "3 kg pour 12 euros", "C'est pareil"],
    expected: ["2 kg pour 6 euros"],
    comparator: "mcq_exact",
    hint: "Calcule le prix pour 1 kg.",
    explanation: "6 ÷ 2 = 3 euros/kg. 12 ÷ 3 = 4 euros/kg. Le premier est moins cher.",
    tags: ["adulte", "prix"],
  },
  {
    kind: "fixed",
    id: "adulte_remise_001",
    niveau: "adulte",
    matiere: "maths",
    notionId: "pourcentages_quotidien",
    microId: "adulte_remise",
    difficulty: 2,
    theme: "neutral",
    text: "Un article coûte 40 euros. Il y a 10 % de remise. Quel est le montant de la remise ?",
    format: "short",
    expected: ["4", "4 euros"],
    comparator: "number_equal",
    hint: "10 %, c'est un dixième.",
    explanation: "10 % de 40 euros = 40 ÷ 10 = 4 euros.",
    tags: ["adulte", "pourcentage"],
  },
  {
    kind: "fixed",
    id: "adulte_recette_001",
    niveau: "adulte",
    matiere: "maths",
    notionId: "proportionnalite_pratique",
    microId: "adulte_recette",
    difficulty: 2,
    theme: "cuisine",
    text: "Une recette pour 2 personnes demande 300 g de riz. Combien faut-il pour 4 personnes ?",
    format: "short",
    expected: ["600", "600 g"],
    comparator: "number_equal",
    hint: "4 personnes, c'est deux fois plus que 2 personnes.",
    explanation: "On double la quantité : 300 x 2 = 600 g.",
    tags: ["adulte", "recette"],
  },
  {
    kind: "fixed",
    id: "adulte_fraction_part_001",
    niveau: "adulte",
    matiere: "maths",
    notionId: "fractions_ratios",
    microId: "adulte_fraction_part",
    difficulty: 1,
    theme: "neutral",
    text: "La moitié de 36 euros, c'est combien ?",
    format: "short",
    expected: ["18", "18 euros"],
    comparator: "number_equal",
    hint: "La moitié, c'est diviser par 2.",
    explanation: "36 ÷ 2 = 18 euros.",
    tags: ["adulte", "fraction"],
  },
  {
    kind: "fixed",
    id: "adulte_conversion_mesure_001",
    niveau: "adulte",
    matiere: "maths",
    notionId: "mesures_conversions",
    microId: "adulte_conversion_mesure",
    difficulty: 2,
    theme: "neutral",
    text: "1,5 L d'eau, cela fait combien de cL ?",
    format: "short",
    expected: ["150", "150 cL", "150cl"],
    comparator: "number_equal",
    hint: "1 L = 100 cL.",
    explanation: "1,5 x 100 = 150 cL.",
    tags: ["adulte", "mesure"],
  },
  {
    kind: "fixed",
    id: "adulte_horaire_duree_001",
    niveau: "adulte",
    matiere: "maths",
    notionId: "durees_trajets",
    microId: "adulte_horaire_duree",
    difficulty: 2,
    theme: "neutral",
    text: "Tu pars à 14 h 20 pour un trajet de 45 minutes. À quelle heure arrives-tu ?",
    format: "short",
    expected: ["15h05", "15 h 05", "15:05", "15h5"],
    comparator: "exact_text",
    hint: "Ajoute 40 minutes, puis encore 5 minutes.",
    explanation: "14 h 20 + 45 min = 15 h 05.",
    tags: ["adulte", "duree"],
  },
  {
    kind: "fixed",
    id: "adulte_tableau_lire_001",
    niveau: "adulte",
    matiere: "maths",
    notionId: "donnees_tableaux",
    microId: "adulte_tableau_lire",
    difficulty: 2,
    theme: "neutral",
    text: "Dans un tableau de budget : alimentation 220 euros, transport 80 euros, loisirs 60 euros. Quelle dépense est la plus élevée ?",
    format: "qcm",
    choices: ["Alimentation", "Transport", "Loisirs"],
    expected: ["Alimentation"],
    comparator: "mcq_exact",
    hint: "Compare les trois montants.",
    explanation: "220 euros est plus grand que 80 euros et 60 euros.",
    tags: ["adulte", "donnees"],
  },
  {
    kind: "fixed",
    id: "adulte_moyenne_001",
    niveau: "adulte",
    matiere: "maths",
    notionId: "statistiques_simples",
    microId: "adulte_moyenne",
    difficulty: 3,
    theme: "neutral",
    text: "Sur trois semaines, tu économises 10 euros, 20 euros puis 30 euros. Quelle est l'économie moyenne par semaine ?",
    format: "short",
    expected: ["20", "20 euros"],
    comparator: "number_equal",
    hint: "Additionne puis divise par 3.",
    explanation: "10 + 20 + 30 = 60, puis 60 ÷ 3 = 20 euros.",
    tags: ["adulte", "moyenne"],
  },
];

export function getMathAdulteQuestionBank(args?: {
  notionId?: string | null;
  microId?: string | null;
}): TutorBankItemV4[] {
  let bank = mathsAdulteQuestionBank;

  if (args?.notionId) {
    bank = bank.filter((item) => item.notionId === args.notionId);
  }

  if (args?.microId) {
    bank = bank.filter((item) => item.microId === args.microId);
  }

  return bank;
}
