import type { NotionSource } from "@/lib/tutor-v4/knowledge/buildKnowledge";

export const notions: NotionSource[] = [
  {
    id: "en_b2_verbs",
    label: "Mathematical Verbs B2",
    boId: "ENGL_B2_VERBS",
    prerequis: [],
    levels: [3, 4],
  },
  {
    id: "en_b2_proof",
    label: "Proof & Logic B2",
    boId: "ENGL_B2_PROOF",
    prerequis: ["en_b2_verbs"],
    levels: [3, 4],
  },
  {
    id: "en_b2_analysis",
    label: "Analysis Vocabulary B2",
    boId: "ENGL_B2_ANALYSIS",
    prerequis: ["en_b2_verbs"],
    levels: [3, 4],
  },
  {
    id: "en_b2_sport_verbs",
    label: "Sport Verbs B2",
    boId: "ENGL_B2_SPORT_VERBS",
    prerequis: [],
    levels: [3, 4],
  },
  {
    id: "en_b2_sport_science",
    label: "Sport Science B2",
    boId: "ENGL_B2_SPORT_SCIENCE",
    prerequis: ["en_b2_sport_verbs"],
    levels: [3, 4],
  },
  {
    id: "en_b2_sport_data",
    label: "Sport Data Analysis B2",
    boId: "ENGL_B2_SPORT_DATA",
    prerequis: ["en_b2_sport_verbs"],
    levels: [3, 4],
  },
  {
    id: "en_b2_science_biology",
    label: "Science — Biology B2",
    boId: "ENGL_B2_SCIENCE_BIOLOGY",
    prerequis: [],
    levels: [3, 4],
  },
  {
    id: "en_b2_science_chemistry",
    label: "Science — Chemistry B2",
    boId: "ENGL_B2_SCIENCE_CHEMISTRY",
    prerequis: [],
    levels: [3, 4],
  },
  {
    id: "en_b2_science_physics",
    label: "Science — Physics B2",
    boId: "ENGL_B2_SCIENCE_PHYSICS",
    prerequis: [],
    levels: [3, 4],
  },
  {
    id: "en_b2_macroeconomics",
    label: "Économie - Gestion — Macroeconomics B2",
    boId: "ENGL_B2_MACROECONOMICS",
    prerequis: [],
    levels: [3, 4],
  },
  {
    id: "en_b2_business",
    label: "Économie - Gestion — Business B2",
    boId: "ENGL_B2_BUSINESS",
    prerequis: ["en_b2_macroeconomics"],
    levels: [3, 4],
  },
  {
    id: "en_b2_eco_statistics",
    label: "Économie - Gestion — Statistics B2",
    boId: "ENGL_B2_ECO_STATISTICS",
    prerequis: ["en_b2_macroeconomics"],
    levels: [3, 4],
  },
  {
    id: "en_b2_geopolitics",
    label: "Géographie - Voyage — Geopolitics B2",
    boId: "ENGL_B2_GEOPOLITICS",
    prerequis: [],
    levels: [3, 4],
  },
  {
    id: "en_b2_climate_science",
    label: "Géographie - Voyage — Climate Science B2",
    boId: "ENGL_B2_CLIMATE_SCIENCE",
    prerequis: ["en_b2_geopolitics"],
    levels: [3, 4],
  },
  {
    id: "en_b2_geo_statistics",
    label: "Géographie - Voyage — Geo Statistics B2",
    boId: "ENGL_B2_GEO_STATISTICS",
    prerequis: ["en_b2_geopolitics"],
    levels: [3, 4],
  },
];
