// 5ᵉ · français — enrichissement des pools d'ÉTUDE DE LA LANGUE.
//
// POURQUOI CELLES-CI D'ABORD (01/08). Mesuré : le builder du cycle 4 produit
// 7 énoncés distincts par micro-compétence, quand celui du cycle 3 en produit
// 32. Son propre en-tête vise pourtant « 12-20 par micro ». Et l'étude de la
// langue alimente 15 des 20 questions de l'épreuve blanche de 4ᵉ — la
// compréhension de l'écrit, elle, est désormais portée par des textes
// supports.
//
// LA RÈGLE D'ÉCRITURE, tirée du cahier officiel de 5ᵉ : jamais de définition
// à réciter. On donne l'énoncé, on demande ce que la forme FAIT. « Cette
// phrase signifie que… », « l'impératif exprime… », « choisir le mot correct
// en s'appuyant sur le temps des verbes soulignés ». Aucun item de ce fichier
// ne commence par « Un(e) X est… ».
//
// QCM uniquement, comme tout le cycle 4 : le comparateur exact_text
// sanctionnerait des accents qu'on n'a pas demandés (cf. le piège relevé sur
// le français cycle 3).

import type { TutorBankItemFixedV4 } from "@/lib/tutor-v4/types";

function qcm(
  n: number,
  microId: string,
  notionId: string,
  difficulty: 1 | 2 | 3,
  text: string,
  choices: string[],
  correct: string,
  explanation: string,
): TutorBankItemFixedV4 {
  return {
    kind: "fixed",
    id: `5e_fr_compl_${microId}_${n}`,
    niveau: "5e",
    matiere: "francais",
    notionId,
    microId,
    difficulty,
    theme: "neutral",
    text,
    format: "qcm",
    choices,
    expected: [correct],
    comparator: "mcq_exact",
    explanation,
    tags: ["5e", "francais", notionId, microId, "qcm"],
  };
}

const V = (n: number, m: string, d: 1 | 2 | 3, t: string, c: string[], r: string, e: string) =>
  qcm(n, m, "vocabulaire", d, t, c, r, e);
const G = (n: number, m: string, d: 1 | 2 | 3, t: string, c: string[], r: string, e: string) =>
  qcm(n, m, "grammaire_phrase", d, t, c, r, e);
const C = (n: number, m: string, d: 1 | 2 | 3, t: string, c: string[], r: string, e: string) =>
  qcm(n, m, "conjugaison", d, t, c, r, e);
const D = (n: number, m: string, d: 1 | 2 | 3, t: string, c: string[], r: string, e: string) =>
  qcm(n, m, "analyse_discours", d, t, c, r, e);

export const complementsEtudeLangue5eBank: TutorBankItemFixedV4[] = [
  // ══════════════════════════════════════════════════════════════════════
  // VOCABULAIRE · inférer par le contexte
  // ══════════════════════════════════════════════════════════════════════
  V(1, "5e_voc_contexte", 1,
    "« La foule était compacte : on avançait à peine. » Que veut dire « compacte » ?",
    ["serrée, sans espace entre eux", "bruyante et très agitée", "joyeuse, détendue et bruyante", "clairsemée, peu nombreuse"],
    "serrée, sans espace entre eux",
    "« On avançait à peine » est la clé : si l'on n'avance pas, c'est qu'il n'y a pas de place. Le contexte donne le sens quand le mot manque."),
  V(2, "5e_voc_contexte", 2,
    "« Son visage s'assombrit lorsqu'il apprit la nouvelle. » Que veut dire « s'assombrit » ?",
    ["devint triste", "devint plus beau", "rougit de honte", "se mit à rire"],
    "devint triste",
    "Le verbe joue sur l'image de la lumière qui baisse. Une nouvelle apprise puis un visage qui s'obscurcit : le mouvement du texte impose le sens figuré."),
  V(3, "5e_voc_contexte", 2,
    "« Le vieil homme marchait d'un pas alerte malgré son âge. » Que veut dire « alerte » ?",
    ["vif et rapide", "hésitant", "douloureux", "silencieux"],
    "vif et rapide",
    "« Malgré son âge » signale une opposition : on attendait un pas lent, le texte dit le contraire. Un mot de liaison suffit souvent à orienter le sens."),
  V(4, "5e_voc_contexte", 2,
    "« Elle réfuta ses arguments un à un, sans jamais élever la voix. » Que veut dire « réfuta » ?",
    ["montra qu'ils étaient faux", "les répéta un par un", "les approuva sans réserve", "les nota soigneusement par écrit"],
    "montra qu'ils étaient faux",
    "« Un à un » indique un travail méthodique contre les arguments. Si elle les approuvait, la précision « sans élever la voix » n'aurait aucun intérêt."),
  V(5, "5e_voc_contexte", 3,
    "« Il consentit à nous suivre, mais de mauvaise grâce. » Que veut dire « consentit » ?",
    ["accepta", "refusa", "hésita longtemps", "s'enfuit"],
    "accepta",
    "La suite le confirme : « mais de mauvaise grâce » n'aurait pas de sens après un refus. Le « mais » oppose l'accord donné à la manière de le donner."),
  V(6, "5e_voc_contexte", 3,
    "« Le sentier devenait de plus en plus escarpé ; nous avancions courbés. » Que veut dire « escarpé » ?",
    ["en pente raide", "boueux", "encombré de branches", "très large"],
    "en pente raide",
    "« Nous avancions courbés » est l'indice : on se penche pour monter, pas pour éviter la boue. Le corps des personnages renseigne sur le décor."),

  // ── VOCABULAIRE · relations entre les mots ────────────────────────────
  V(1, "5e_voc_relations", 1,
    "Dans « Il était ravi de sa journée », quel mot pourrait remplacer « ravi » sans changer le sens ?",
    ["enchanté", "épuisé", "surpris", "inquiet"],
    "enchanté",
    "Deux synonymes doivent tenir dans la même phrase sans la fausser. « Épuisé » et « inquiet » diraient tout autre chose."),
  V(2, "5e_voc_relations", 1,
    "Quel mot est le contraire de « éphémère » dans « un bonheur éphémère » ?",
    ["durable", "immense", "discret", "fragile"],
    "durable",
    "« Éphémère » dit ce qui ne dure pas. Attention à « fragile » : c'est un mot voisin, mais il parle de solidité, pas de durée."),
  V(3, "5e_voc_relations", 2,
    "Quel mot n'appartient PAS au champ lexical de la mer ?",
    ["clairière", "houle", "écume", "récif"],
    "clairière",
    "Un champ lexical réunit les mots d'un même domaine. Houle, écume et récif appartiennent à la mer ; une clairière est un espace dégagé dans une forêt."),
  V(4, "5e_voc_relations", 2,
    "Quel mot n'est PAS de la même famille que les autres ?",
    ["terrible", "terrain", "terrestre", "atterrir"],
    "terrible",
    "Terrain, terrestre et atterrir se construisent tous sur « terre ». « Terrible » vient de « terreur » : la ressemblance des lettres n'est pas une parenté de sens."),
  V(5, "5e_voc_relations", 3,
    "Dans « une remarque acerbe », quel synonyme convient le mieux ?",
    ["mordante", "flatteuse", "confuse", "prudente"],
    "mordante",
    "« Acerbe » qualifie ce qui blesse par sa dureté. « Mordante » garde à la fois le sens et la violence de l'image ; « prudente » dirait l'inverse."),
  V(6, "5e_voc_relations", 3,
    "Quel couple de mots forme une paire d'antonymes ?",
    ["abondant / rare", "abondant / nombreux", "abondant / copieux", "abondant / généreux"],
    "abondant / rare",
    "Trois de ces propositions sont des synonymes ou presque. Seul « rare » s'oppose vraiment à « abondant » : peu contre beaucoup."),

  // ── VOCABULAIRE · formation des mots ──────────────────────────────────
  V(1, "5e_voc_formation", 1,
    "Dans « inhabituel », que change le préfixe « in- » ?",
    ["il donne le sens contraire", "il indique une répétition", "il marque le passé", "il indique la petitesse"],
    "il donne le sens contraire",
    "« Inhabituel » = qui n'est pas habituel. Le préfixe « in- » (ou « im- », « il- », « ir- ») retourne le sens du mot qu'il précède."),
  V(2, "5e_voc_formation", 1,
    "Dans « refaire », que signale le préfixe « re- » ?",
    ["que l'action est recommencée", "que l'action est ratée", "que l'action est lente", "que l'action est interdite"],
    "que l'action est recommencée",
    "Refaire, relire, redire : le préfixe « re- » remet l'action en route. C'est le même dans « recommencer », où il double presque le sens."),
  V(3, "5e_voc_formation", 2,
    "Dans « fillette », que traduit le suffixe « -ette » ?",
    ["une idée de petitesse ou d'affection", "une action qui est encore en cours", "le métier qu'exerce quelqu'un", "le lieu où l'action se déroule"],
    "une idée de petitesse ou d'affection",
    "Fillette, maisonnette, tablette : le suffixe « -ette » rapetisse. On l'appelle un diminutif, et il porte souvent de la tendresse."),
  V(4, "5e_voc_formation", 2,
    "Le mot « chronomètre » est formé de « chrono- » (temps) et « -mètre » (mesure). Que désigne-t-il ?",
    ["un appareil qui mesure le temps", "un appareil qui mesure une distance", "une unité de temps", "une science du temps"],
    "un appareil qui mesure le temps",
    "Découper un mot savant en ses racines suffit souvent à le comprendre. Le même « -mètre » se retrouve dans thermomètre et baromètre."),
  V(5, "5e_voc_formation", 3,
    "Dans « désordonné », combien y a-t-il d'affixes autour du radical « ordre » ?",
    ["deux : un préfixe et un suffixe", "un seul : le préfixe « dés- » placé devant", "un seul : le suffixe « -é » placé derrière", "aucun : « ordre » porte déjà ce sens"],
    "deux : un préfixe et un suffixe",
    "On lit dés-ordonn-é : le préfixe nie, le suffixe fabrique un adjectif à partir du verbe « ordonner ». Un mot peut porter les deux à la fois."),
  V(6, "5e_voc_formation", 3,
    "Quel mot n'est PAS construit avec un préfixe ?",
    ["décor", "décoller", "défaire", "déplacer"],
    "décor",
    "Décoller, défaire et déplacer se construisent sur coller, faire, placer. Dans « décor », le « dé- » fait partie du mot : on ne peut pas l'enlever."),

  // ── VOCABULAIRE · réemploi ────────────────────────────────────────────
  V(1, "5e_voc_reemploi", 1,
    "Quel mot est le plus précis pour compléter : « Le vent … les volets contre le mur. »",
    ["rabattait", "faisait", "mettait", "donnait"],
    "rabattait",
    "« Faire », « mettre », « donner » conviennent à tout et ne disent rien. Un verbe précis fait voir le mouvement : le volet rabattu claque contre le mur."),
  V(2, "5e_voc_reemploi", 2,
    "Quel verbe rend le mieux : « Il … la porte sans un bruit, pour ne réveiller personne. »",
    ["referma", "claqua", "poussa violemment", "défonça"],
    "referma",
    "L'intention est dans la phrase : ne réveiller personne. Le verbe doit s'accorder avec elle ; « claqua » la contredirait aussitôt."),
  V(3, "5e_voc_reemploi", 2,
    "Quel adjectif est le plus juste : « Après la course, elle avait le souffle … »",
    ["court", "petit", "faible", "mince"],
    "court",
    "« Avoir le souffle court » est l'expression consacrée. Les autres adjectifs disent bien l'idée de peu, mais aucun ne se dit du souffle."),
  V(4, "5e_voc_reemploi", 2,
    "Quel mot évite la répétition : « Il tenait un vieux livre. Ce … datait du siècle dernier. »",
    ["ouvrage", "objet", "truc", "machin"],
    "ouvrage",
    "Reprendre un mot par un synonyme évite la répétition sans perdre en précision. « Objet » serait vague, « truc » relèverait de l'oral."),
  V(5, "5e_voc_reemploi", 3,
    "Quel verbe convient à un registre soutenu : « Le ministre … qu'il n'avait pas été informé. »",
    ["affirma", "dit qu'il", "balança", "raconta"],
    "affirma",
    "« Affirmer » porte l'idée de déclaration ferme, dans un registre qui convient au contexte officiel. « Balancer » relèverait du langage familier."),
  V(6, "5e_voc_reemploi", 3,
    "Quelle formulation est la plus précise : « La nuit, la ville … de mille lumières. »",
    ["scintillait", "était jolie", "avait des lumières", "faisait de la lumière"],
    "scintillait",
    "Un seul verbe peut remplacer une description entière. « Scintiller » contient à la fois la lumière, son tremblement et sa multiplicité."),

  // ── VOCABULAIRE · orthographe lexicale ────────────────────────────────
  // ⚠️ CHAQUE ÉNONCÉ DOIT ÊTRE DISTINCT. Ces six questions partageaient
  // toutes le même intitulé — « Quelle est l'orthographe correcte ? » — et
  // ne différaient que par les propositions. Or le tirage de l'épreuve
  // déduplique sur l'ÉNONCÉ : une seule des six aurait pu tomber, et une fois
  // vue, les cinq autres devenaient inatteignables. Le mot est donc replacé
  // dans une phrase, ce qui vaut mieux de toute façon : on n'écrit jamais un
  // mot tout seul.
  V(1, "5e_voc_orthographe", 1,
    "« Il se trouvait face à un véritable … » Quelle orthographe convient ?",
    ["dilemme", "dilemne", "dillemme", "dilême"],
    "dilemme",
    "Deux « m », un seul « l », et pas de « n » : le piège vient de « indemne », qui n'a rien à voir."),
  V(2, "5e_voc_orthographe", 1,
    "« Cette chanson a un … entraînant. » Quelle orthographe convient ?",
    ["rythme", "rytme", "rithme", "rhytme"],
    "rythme",
    "Le mot vient du grec : « rh » au début, « y » au milieu, « thme » à la fin. Même famille que « rythmique »."),
  V(3, "5e_voc_orthographe", 2,
    "« Le … du village a duré dix ans. » Quelle orthographe convient ?",
    ["développement", "dévelopement", "dévellopement", "développemment"],
    "développement",
    "Deux « p », un seul « l », un seul « m ». Le doublement porte sur le p, jamais sur le l."),
  V(4, "5e_voc_orthographe", 2,
    "« Au détour du chemin, la mer … soudain. » Quelle orthographe convient ?",
    ["apparaît", "apparait", "aparaît", "apparraît"],
    "apparaît",
    "Deux « p », un seul « r », et l'accent circonflexe sur le « i » devant le « t ». Même règle pour « paraître » et « connaître »."),
  V(5, "5e_voc_orthographe", 3,
    "« Ce métier demande une … » Quelle forme est correcte ?",
    ["exigence particulière", "exigeance particulière", "exigence particulier", "exigeance particulier"],
    "exigence particulière",
    "« Exigence » s'écrit sans « a », contrairement à « vengeance » ou « surveillance ». Et l'adjectif s'accorde : particulière."),
  V(6, "5e_voc_orthographe", 3,
    "« Trop tard, ils … de leur erreur. » Quelle forme convient ?",
    ["se sont aperçus", "se sont apperçus", "se sont aperçu", "se sont apercus"],
    "se sont aperçus",
    "Un seul « p », une cédille sous le « c » devant le « u », et l'accord au pluriel avec « ils ». Trois pièges dans un seul mot."),

  // ══════════════════════════════════════════════════════════════════════
  // GRAMMAIRE · constituants
  // ══════════════════════════════════════════════════════════════════════
  G(1, "5e_gram_constituants", 1,
    "« Le facteur a déposé le colis devant la porte. » Combien cette phrase compte-t-elle de verbes conjugués ?",
    ["un", "deux", "trois", "aucun"],
    "un",
    "« A déposé » est un passé composé : l'auxiliaire et le participe forment UN seul verbe conjugué. La phrase est donc simple."),
  G(2, "5e_gram_constituants", 2,
    "« Nous partirons dès que la pluie cessera. » Combien de propositions ?",
    ["deux", "une", "trois", "aucune"],
    "deux",
    "Deux verbes conjugués, « partirons » et « cessera », donc deux propositions. La seconde est introduite par « dès que » : elle dépend de la première."),
  G(3, "5e_gram_constituants", 2,
    "« Il pleuvait, et personne ne sortait. » Comment les deux propositions sont-elles reliées ?",
    ["par coordination, avec « et »", "par subordination", "par juxtaposition seule", "elles ne sont pas reliées"],
    "par coordination, avec « et »",
    "Une conjonction de coordination relie deux propositions de même rang : aucune ne dépend de l'autre. Avec « parce que », il y aurait subordination."),
  G(4, "5e_gram_constituants", 2,
    "« Le vent tomba ; la mer redevint lisse. » Comment ces propositions sont-elles reliées ?",
    ["par juxtaposition, avec un point-virgule", "par coordination, avec la conjonction « et »", "par subordination, avec le pronom « qui »", "par une conjonction de subordination"],
    "par juxtaposition, avec un point-virgule",
    "Juxtaposer, c'est poser côte à côte avec une simple ponctuation — virgule, point-virgule ou deux points — sans mot de liaison."),
  G(5, "5e_gram_constituants", 3,
    "« Le livre que tu m'as prêté m'a beaucoup plu. » Quelle est la proposition subordonnée ?",
    ["que tu m'as prêté", "Le livre", "m'a beaucoup plu", "Le livre m'a beaucoup plu"],
    "que tu m'as prêté",
    "Elle est introduite par « que » et ne peut pas vivre seule : « que tu m'as prêté » n'est pas une phrase. Elle complète le nom « livre »."),
  G(6, "5e_gram_constituants", 3,
    "« Bien qu'il fût tard, elle continua de lire. » Que devient la phrase si l'on supprime la proposition subordonnée ?",
    ["« Elle continua de lire. » — la phrase reste correcte", "« Elle continua. » — la phrase devient incorrecte", "« Bien qu'il fût tard. » — il ne reste plus rien", "« Elle continua de lire. » — le sens s'inverse"],
    "« Elle continua de lire. » — la phrase reste correcte",
    "C'est le test de la subordonnée : on peut l'ôter, la principale tient debout. L'inverse n'est pas vrai — « Bien qu'il fût tard » ne se dit pas seul."),

  // ── GRAMMAIRE · fonctions ─────────────────────────────────────────────
  G(1, "5e_gram_fonctions", 1,
    "« Chaque matin, les élèves traversent la cour. » Quel est le sujet ?",
    ["les élèves", "Chaque matin", "la cour", "traversent"],
    "les élèves",
    "On pose la question « qui est-ce qui traverse ? ». « Chaque matin » répond à « quand », c'est un complément de temps placé en tête."),
  G(2, "5e_gram_fonctions", 2,
    "« Le jardinier taille les rosiers avec soin. » Quel est le complément d'objet direct ?",
    ["les rosiers", "Le jardinier", "avec soin", "taille"],
    "les rosiers",
    "« Taille quoi ? » — les rosiers. Le COD suit le verbe sans préposition ; « avec soin » répond à « comment » et se supprime sans gêne."),
  G(3, "5e_gram_fonctions", 2,
    "« Elle offrit un cadeau à son frère. » Quel est le complément d'objet indirect ?",
    ["à son frère", "un cadeau", "Elle", "offrit"],
    "à son frère",
    "Le COI est relié au verbe par une préposition : « offrit à qui ? ». « Un cadeau » répond à « quoi » sans préposition : c'est le COD."),
  G(4, "5e_gram_fonctions", 2,
    "« Sous le manguier, les enfants dormaient. » Quelle est la fonction de « Sous le manguier » ?",
    ["complément circonstanciel de lieu", "complément circonstanciel de temps", "complément d'objet direct", "complément du nom qui précède"],
    "complément circonstanciel de lieu",
    "Il répond à « où ». On peut le déplacer — « Les enfants dormaient sous le manguier » — ou le supprimer : c'est la marque du circonstanciel."),
  G(5, "5e_gram_fonctions", 3,
    "« Cette réponse paraît juste. » Quelle est la fonction de « juste » ?",
    ["attribut du sujet", "complément d'objet direct", "complément circonstanciel", "sujet"],
    "attribut du sujet",
    "« Paraître » est un verbe d'état, comme « être », « sembler », « devenir ». Ce qui le suit qualifie le sujet au lieu de subir l'action."),
  G(6, "5e_gram_fonctions", 3,
    "« Le chemin qui longe la rivière est ombragé. » Que complète la proposition « qui longe la rivière » ?",
    ["le nom « chemin »", "le verbe « est »", "l'adjectif « ombragé »", "toute la phrase"],
    "le nom « chemin »",
    "Une relative se place juste après le nom qu'elle précise et commence par un pronom relatif. Elle dit DE QUEL chemin on parle."),

  // ── GRAMMAIRE · accords ───────────────────────────────────────────────
  G(1, "5e_gram_accords", 1,
    "Quelle phrase est correctement accordée ?",
    ["Les fleurs blanches embaument le jardin.", "Les fleurs blanche embaument le jardin.", "Les fleur blanches embaument le jardin.", "Les fleurs blanches embaume le jardin."],
    "Les fleurs blanches embaument le jardin.",
    "Dans le groupe nominal, le déterminant et l'adjectif suivent le nom : féminin pluriel partout. Et le verbe s'accorde avec le sujet « les fleurs »."),
  G(2, "5e_gram_accords", 2,
    "« La liste des candidats … affichée. » Quelle forme convient ?",
    ["est", "sont", "êtes", "seront"],
    "est",
    "Le sujet est « la liste », pas « les candidats ». Le complément du nom, même au pluriel, ne commande jamais l'accord du verbe."),
  G(3, "5e_gram_accords", 2,
    "« Les lettres qu'elle a … sont arrivées. » Quelle forme convient ?",
    ["écrites", "écrit", "écrit(e)s au choix", "écrivait"],
    "écrites",
    "Avec « avoir », le participe s'accorde avec le COD s'il est placé avant : « qu' » reprend « les lettres », féminin pluriel."),
  G(4, "5e_gram_accords", 2,
    "« Elles se sont … à midi. » Quelle forme convient ?",
    ["levées", "levé", "levés", "lever"],
    "levées",
    "Avec « être », le participe s'accorde avec le sujet. « Elles » est féminin pluriel : deux « e », un « s »."),
  G(5, "5e_gram_accords", 3,
    "« Nous avons trouvé des solutions … » Quel adjectif est correctement accordé ?",
    ["originales", "original", "originaux", "originale"],
    "originales",
    "L'adjectif qualifie « solutions », féminin pluriel. « Originaux » serait le masculin pluriel — le piège vient du singulier « original »."),
  G(6, "5e_gram_accords", 3,
    "« Chacun des élèves … son cahier. » Quelle forme convient ?",
    ["a apporté", "ont apporté", "avaient apportés", "ont apportés"],
    "a apporté",
    "Le sujet est « chacun », singulier, malgré « des élèves » qui suit. Le verbe se met donc au singulier, et le participe reste invariable avec « avoir » sans COD antéposé."),

  // ── GRAMMAIRE · oral et écrit ─────────────────────────────────────────
  G(1, "5e_gram_oral_ecrit", 1,
    "« J'sais pas si y'a quelqu'un. » Comment écrit-on cette phrase ?",
    ["Je ne sais pas s'il y a quelqu'un.", "Je sais pas si il y a quelqu'un.", "J'sais pas s'il y a quelqu'un.", "Je ne sais pas si y a quelqu'un."],
    "Je ne sais pas s'il y a quelqu'un.",
    "À l'écrit on rétablit ce que l'oral avale : le « ne » de la négation, le sujet « je » entier, et « il » dans « il y a »."),
  G(2, "5e_gram_oral_ecrit", 2,
    "« Où c'est qu'tu vas ? » Quelle est la forme écrite correcte ?",
    ["Où vas-tu ?", "Où que tu vas ?", "Où c'est que tu vas ?", "Tu vas où ?"],
    "Où vas-tu ?",
    "L'interrogation écrite inverse le sujet et le verbe. « Tu vas où ? » se comprend, mais reste une tournure orale."),
  G(3, "5e_gram_oral_ecrit", 2,
    "Quelle phrase relève de l'écrit soigné ?",
    ["Il n'a rien dit.", "Il a rien dit.", "Y'a rien qu'il a dit.", "Il a pas dit un truc."],
    "Il n'a rien dit.",
    "La négation écrite garde ses deux éléments : « ne… rien ». À l'oral, le « ne » disparaît presque toujours — ce n'est pas une faute d'oral, c'en est une à l'écrit."),
  G(4, "5e_gram_oral_ecrit", 2,
    "« Le mec, il est parti. » Comment écrire cette phrase ?",
    ["L'homme est parti.", "Le mec il est parti.", "Le mec, il est parti.", "Lui, il est parti, le mec."],
    "L'homme est parti.",
    "Deux choses relèvent de l'oral : le mot « mec », familier, et la reprise du sujet par « il ». L'écrit dit le sujet une seule fois."),
  G(5, "5e_gram_oral_ecrit", 3,
    "« Faut qu'on parte. » Quelle forme écrite convient ?",
    ["Il faut que nous partions.", "Faut que nous partions.", "Il faut qu'on parte.", "Il faut que on parte."],
    "Il faut que nous partions.",
    "Trois rétablissements : le « il » impersonnel, le pronom « nous » à la place de « on », et le subjonctif « partions » qu'exige « il faut que »."),
  G(6, "5e_gram_oral_ecrit", 3,
    "Quelle phrase garde une trace d'oral qu'un texte écrit éviterait ?",
    ["Ce livre, je l'ai lu deux fois.", "J'ai lu ce livre deux fois.", "Ce livre a été lu deux fois.", "J'ai relu ce livre."],
    "Ce livre, je l'ai lu deux fois.",
    "Détacher le complément en tête puis le reprendre par un pronom est un procédé de l'oral. On l'appelle la dislocation ; l'écrit la garde pour insister."),

  // ══════════════════════════════════════════════════════════════════════
  // CONJUGAISON · identifier
  // ══════════════════════════════════════════════════════════════════════
  C(1, "5e_conj_identifier", 1,
    "« Nous prenions le bus à sept heures. » À quel temps est le verbe ?",
    ["à l'imparfait", "au présent", "au passé simple", "au futur"],
    "à l'imparfait",
    "La terminaison « -ions » à la première personne du pluriel est celle de l'imparfait. Au présent, on aurait « nous prenons »."),
  C(2, "5e_conj_identifier", 2,
    "« Il fallut attendre la fin de la pluie. » À quel temps est « fallut » ?",
    ["au passé simple", "à l'imparfait", "au présent", "au conditionnel"],
    "au passé simple",
    "Le passé simple de « falloir » à la troisième personne donne « il fallut ». L'imparfait serait « il fallait », avec deux syllabes de plus."),
  C(3, "5e_conj_identifier", 2,
    "« Que tu viennes demain m'arrangerait. » À quel mode est « viennes » ?",
    ["au subjonctif", "à l'indicatif", "à l'impératif", "au conditionnel"],
    "au subjonctif",
    "« Que » suivi d'un verbe qui change de forme — « viennes » et non « viens » — signale le subjonctif : le fait est envisagé, pas constaté."),
  C(4, "5e_conj_identifier", 2,
    "« Ferme la porte en sortant. » À quel mode est « Ferme » ?",
    ["à l'impératif", "à l'indicatif présent", "au subjonctif", "à l'infinitif"],
    "à l'impératif",
    "Aucun sujet exprimé et un ordre adressé à quelqu'un : c'est l'impératif. À l'indicatif, on dirait « tu fermes la porte »."),
  C(5, "5e_conj_identifier", 3,
    "« Ils avaient terminé avant notre arrivée. » À quel temps est ce verbe ?",
    ["au plus-que-parfait", "au passé composé", "à l'imparfait", "au conditionnel passé"],
    "au plus-que-parfait",
    "L'auxiliaire est à l'imparfait — « avaient » — suivi du participe. Le plus-que-parfait dit une action achevée AVANT une autre action passée."),
  C(6, "5e_conj_identifier", 3,
    "« Nous aimerions vous rencontrer. » À quel mode et temps ?",
    ["au conditionnel présent", "au futur simple", "à l'imparfait", "au subjonctif présent"],
    "au conditionnel présent",
    "On reconnaît le conditionnel au « r » du futur suivi des terminaisons de l'imparfait : « -rions ». Au futur, ce serait « nous aimerons »."),

  // ── CONJUGAISON · composer ────────────────────────────────────────────
  C(1, "5e_conj_composer", 1,
    "« Hier, nous … au marché. » Quelle forme convient ?",
    ["sommes allés", "avons allé", "sommes allé", "avons allés"],
    "sommes allés",
    "« Aller » se conjugue avec l'auxiliaire « être » au passé composé, et le participe s'accorde alors avec le sujet : « nous » au masculin pluriel."),
  C(2, "5e_conj_composer", 2,
    "« Il faut que tu … plus tôt. » Quelle forme convient ?",
    ["partes", "pars", "partiras", "partais"],
    "partes",
    "« Il faut que » commande le subjonctif. Au présent du subjonctif, « partir » donne « que tu partes » — l'indicatif « tu pars » ne convient pas."),
  C(3, "5e_conj_composer", 2,
    "« Si j'avais su, je … autrement. » Quelle forme convient ?",
    ["aurais agi", "avais agi", "aurai agi", "agirais"],
    "aurais agi",
    "Après « si » suivi du plus-que-parfait, la principale se met au conditionnel passé. C'est le couple habituel du regret."),
  C(4, "5e_conj_composer", 2,
    "« Quand vous … votre travail, vous pourrez sortir. » Quelle forme convient ?",
    ["aurez fini", "finirez", "avez fini", "finissiez"],
    "aurez fini",
    "Le futur antérieur marque une action achevée avant une autre action future. On finit d'abord, on sort ensuite."),
  C(5, "5e_conj_composer", 3,
    "« Elles se sont … les mains. » Quelle forme convient ?",
    ["lavé", "lavées", "lavés", "laver"],
    "lavé",
    "Le COD « les mains » est placé APRÈS le verbe : le participe ne s'accorde pas. Sans ce complément, on écrirait « elles se sont lavées »."),
  C(6, "5e_conj_composer", 3,
    "« Je souhaite qu'il … présent demain. » Quelle forme convient ?",
    ["soit", "est", "sera", "serait"],
    "soit",
    "« Souhaiter que » exprime une volonté, donc un fait non réalisé : le subjonctif s'impose. « Il est » ou « il sera » affirmeraient le fait."),

  // ── CONJUGAISON · employer selon le sens ──────────────────────────────
  C(1, "5e_conj_employer", 2,
    "« La Terre tourne autour du Soleil. » Que dit ici le présent ?",
    ["une vérité qui vaut toujours", "une action en train de se faire", "une habitude passée", "une action à venir"],
    "une vérité qui vaut toujours",
    "C'est le présent de vérité générale, celui des sciences et des proverbes. Il ne situe pas dans le temps : il énonce ce qui est vrai en permanence."),
  C(2, "5e_conj_employer", 2,
    "« Tous les étés, nous allions chez ma grand-mère. » Que dit ici l'imparfait ?",
    ["une action qui se répétait", "une action unique et brève", "une action à venir", "un ordre"],
    "une action qui se répétait",
    "« Tous les étés » le confirme : c'est l'imparfait d'habitude. Le même temps peut ailleurs décrire un décor qui dure."),
  C(3, "5e_conj_employer", 2,
    "« Elle relisait sa lettre quand le téléphone sonna. » Quel verbe interrompt l'autre ?",
    ["« sonna », au passé simple", "« relisait », à l'imparfait", "les deux en même temps", "aucun des deux"],
    "« sonna », au passé simple",
    "L'imparfait installe l'action en cours, le passé simple vient la couper. C'est le partage des rôles du récit."),
  C(4, "5e_conj_employer", 3,
    "« Il aurait quitté la ville depuis un mois, dit-on. » Que marque ce conditionnel ?",
    ["une information non confirmée", "une condition encore à remplir", "un regret portant sur le passé", "une demande faite poliment"],
    "une information non confirmée",
    "« Dit-on » donne la clé : le conditionnel prend ses distances avec l'information. C'est l'usage constant de la presse pour ce qui n'est pas vérifié."),
  C(5, "5e_conj_employer", 3,
    "« Encore un pas, et je tombais. » Que dit ici l'imparfait ?",
    ["ce qui a failli arriver", "ce qui arrivait souvent", "ce qui va arriver demain", "un ordre donné"],
    "ce qui a failli arriver",
    "L'imparfait sert ici à raconter ce qui ne s'est PAS produit, mais de très peu. On le remplacerait par « j'allais tomber »."),
  C(6, "5e_conj_employer", 3,
    "« Vous voudrez bien nous excuser. » Que marque ce futur ?",
    ["une demande polie", "une certitude sur l'avenir", "une obligation légale", "un regret"],
    "une demande polie",
    "Le futur adoucit ici une demande présente : on n'annonce rien, on prie. C'est la même politesse détournée que dans « je voudrais »."),

  // ══════════════════════════════════════════════════════════════════════
  // DISCOURS · registres
  // ══════════════════════════════════════════════════════════════════════
  D(1, "5e_discours_registres", 1,
    "Quelle phrase relève du registre familier ?",
    ["On s'est bien marrés hier soir.", "Nous nous sommes bien amusés hier soir.", "La soirée fut fort plaisante.", "Nous avons passé une bonne soirée."],
    "On s'est bien marrés hier soir.",
    "« Se marrer » appartient à la langue parlée entre proches, et « on » y remplace « nous ». Le registre se lit au vocabulaire autant qu'à la construction."),
  D(2, "5e_discours_registres", 2,
    "« Je sollicite votre bienveillance. » À quel registre appartient cette phrase ?",
    ["au registre soutenu", "au registre familier", "au registre courant", "à aucun registre"],
    "au registre soutenu",
    "« Solliciter » et « bienveillance » ne s'emploient pas dans la conversation ordinaire. On les rencontre dans les lettres officielles."),
  D(3, "5e_discours_registres", 2,
    "Comment dire « Il a paumé ses clés » en registre courant ?",
    ["Il a perdu ses clés.", "Il a égaré ses clefs.", "Il a paumé ses clefs.", "Ses clés, il les a paumées."],
    "Il a perdu ses clés.",
    "« Perdre » est le mot neutre, celui de tous les jours. « Égarer » monterait d'un cran vers le soutenu ; « paumer » reste familier."),
  D(4, "5e_discours_registres", 2,
    "À qui s'adresserait-on ainsi : « Auriez-vous l'obligeance de patienter ? »",
    ["à une personne qu'on ne connaît pas, avec déférence", "à un camarade de classe, sur le ton de la plaisanterie", "à un petit frère, pour le taquiner gentiment", "à personne : la phrase est grammaticalement incorrecte"],
    "à une personne qu'on ne connaît pas, avec déférence",
    "Le conditionnel, le vouvoiement et « obligeance » construisent une distance polie. À un camarade, on dirait « tu peux attendre ? »."),
  D(5, "5e_discours_registres", 3,
    "Quelle phrase mélange deux registres ?",
    ["Je vous prie d'agréer mes salutations, c'est top.", "Je vous prie d'agréer mes salutations distinguées.", "Salut, à demain, on se voit devant le portail !", "Bonjour, à demain, et bonne fin de journée."],
    "Je vous prie d'agréer mes salutations, c'est top.",
    "La formule de politesse appartient au soutenu, « c'est top » au familier. Le mélange sonne faux : on choisit un registre et on s'y tient."),
  D(6, "5e_discours_registres", 3,
    "« Cet individu s'est permis de pénétrer sans y avoir été convié. » Que produit ce registre soutenu ?",
    ["il met de la distance et souligne la désapprobation", "il rend la scène franchement amusante et légère", "il montre que le narrateur est un ami de cet homme", "il rend le texte plus vif et plus rapide à lire"],
    "il met de la distance et souligne la désapprobation",
    "« Individu », « convié » : les mots choisis tiennent le personnage à distance. Le registre n'est pas qu'une étiquette, il produit un effet."),

  // ── DISCOURS · paroles rapportées ─────────────────────────────────────
  D(1, "5e_discours_rapportees", 1,
    "« Il déclara : “Je reviendrai demain.” » Comment ces paroles sont-elles rapportées ?",
    ["au discours direct", "au discours indirect", "au discours indirect libre", "elles ne sont pas rapportées"],
    "au discours direct",
    "Deux points, guillemets, et les mots tels qu'ils ont été prononcés : le discours direct donne la parole sans la transformer."),
  D(2, "5e_discours_rapportees", 2,
    "« Il déclara qu'il reviendrait le lendemain. » Qu'est-ce qui a changé par rapport au discours direct ?",
    ["le temps du verbe et l'indication de temps", "seulement la ponctuation de la phrase", "rien du tout : la phrase est identique", "seulement le verbe qui introduit les paroles"],
    "le temps du verbe et l'indication de temps",
    "« Je reviendrai demain » devient « qu'il reviendrait le lendemain » : le futur passe au conditionnel, et « demain » se recalcule depuis le moment du récit."),
  D(3, "5e_discours_rapportees", 2,
    "Quel verbe introduit des paroles en indiquant que celui qui parle proteste ?",
    ["s'indigner", "murmurer", "chuchoter", "répéter"],
    "s'indigner",
    "Le verbe introducteur ne sert pas qu'à annoncer : il colore la parole. « S'indigner » dit à la fois qu'on parle et qu'on n'accepte pas."),
  D(4, "5e_discours_rapportees", 2,
    "« — Tu viens ? demanda-t-elle. » À quoi sert le tiret en début de ligne ?",
    ["il signale une prise de parole", "il marque une hésitation dans la voix", "il remplace une virgule sans rien changer", "il annonce une énumération qui va suivre"],
    "il signale une prise de parole",
    "Dans un dialogue, chaque tiret annonce que quelqu'un d'autre parle. C'est ce qui permet de suivre l'échange sans répéter les noms."),
  D(5, "5e_discours_rapportees", 3,
    "« Elle se demanda si elle avait bien fermé la porte. » Ces paroles sont rapportées...",
    ["au discours indirect", "au discours direct", "sans aucun rapport de paroles", "au discours narrativisé seulement"],
    "au discours indirect",
    "La question intérieure est intégrée dans une subordonnée introduite par « si », sans guillemets. Au direct : « Ai-je bien fermé la porte ? »."),
  D(6, "5e_discours_rapportees", 3,
    "Quelle transformation est correcte au discours indirect ? « Il dit : “Je suis fatigué.” »",
    ["Il dit qu'il était fatigué.", "Il dit que je suis fatigué.", "Il dit qu'il est fatigué hier.", "Il dit : qu'il était fatigué."],
    "Il dit qu'il était fatigué.",
    "Deux changements obligatoires : le pronom « je » devient « il », et le présent passe à l'imparfait puisque le récit est au passé."),

  // ── DISCOURS · argumentation ──────────────────────────────────────────
  D(1, "5e_discours_argumentatif", 2,
    "« Le sport à l'école est utile : il apprend à perdre. » Quel est l'argument ?",
    ["il apprend à perdre", "Le sport à l'école est utile", "les deux à la fois", "il n'y a pas d'argument"],
    "il apprend à perdre",
    "La première partie énonce ce qu'on veut faire admettre — la thèse. Ce qui vient après les deux points la soutient : c'est l'argument."),
  D(2, "5e_discours_argumentatif", 2,
    "« Lire développe le vocabulaire. Par exemple, un lecteur régulier connaît deux fois plus de mots. » À quoi sert la seconde phrase ?",
    ["elle illustre l'argument par un cas", "elle énonce une nouvelle thèse", "elle contredit la première phrase", "elle pose une question au lecteur"],
    "elle illustre l'argument par un cas",
    "Un exemple ne prouve pas à lui seul : il rend visible. « Par exemple » annonce toujours qu'on passe de l'idée au concret."),
  D(3, "5e_discours_argumentatif", 2,
    "Quel mot de liaison introduit une opposition ?",
    ["cependant", "donc", "en effet", "ainsi"],
    "cependant",
    "« Cependant » annonce qu'on va contredire ce qui précède. « Donc » et « ainsi » tirent une conséquence ; « en effet » confirme."),
  D(4, "5e_discours_argumentatif", 2,
    "« Certains diront que les écrans sont inoffensifs. Pourtant, les études montrent le contraire. » Que fait la première phrase ?",
    ["elle énonce l'objection pour mieux y répondre", "elle énonce la thèse que défend l'auteur", "elle donne un exemple qui illustre l'idée", "elle conclut tout le raisonnement mené"],
    "elle énonce l'objection pour mieux y répondre",
    "On appelle cela concéder : on formule l'avis adverse avant de le réfuter. Le « Pourtant » marque le retournement."),
  D(5, "5e_discours_argumentatif", 3,
    "« Il faut protéger les récifs, car ils abritent un quart de la vie marine. » Quel mot relie l'argument à la thèse ?",
    ["car", "il faut", "protéger", "un quart"],
    "car",
    "« Car » annonce la raison. Sans lui, on aurait deux affirmations posées côte à côte, sans montrer que l'une soutient l'autre."),
  D(6, "5e_discours_argumentatif", 3,
    "« D'abord… Ensuite… Enfin… » À quoi servent ces mots dans un texte argumentatif ?",
    ["à ranger les arguments et à guider le lecteur", "à indiquer le temps où se passe le récit", "à introduire les paroles d'un personnage", "à marquer une opposition entre deux faits"],
    "à ranger les arguments et à guider le lecteur",
    "Ce sont des connecteurs d'organisation. Ils ne disent rien du contenu : ils montrent l'architecture, et permettent de suivre sans se perdre."),
];
