// « Cartes défis · Vers la 5e » — révision 6e → entrée en 5e (~11-12 ans).
// Rééquilibré (conseil à 7 rôles, l'élève tranche) : moins de nutrition/sport,
// plus de disciplinaire (maths sur chaque carte) + fierté péi 🌋. « Sport du jour ».

import type { CarteDefi } from "@/components/cartes/types";

export const CARTES: CarteDefi[] = [
  { ref: "5E·01", questions: [ {matiere:"maths",q:"Écris 3/4 en décimal.",r:"0,75"}, {matiere:"francais",q:"« a » ou « à » : « Il va ___ Paris. »",r:"à"}, {matiere:"reunion",q:"Combien de cirques à La Réunion ?",r:"3 : Cilaos, Mafate, Salazie"}, {matiere:"sport",q:"Pourquoi s'échauffer avant le sport ?",r:"préparer les muscles, éviter les blessures"} ], bouge: "20 sauts sur place" },
  { ref: "5E·02", questions: [ {matiere:"maths",q:"Calcule 2 + 3 × 4.",r:"14 (× avant +)"}, {matiere:"anglais",q:"Traduis « I have a dog ».",r:"j'ai un chien"}, {matiere:"sciences",q:"Que rejette-t-on en respirant ?",r:"du dioxyde de carbone (CO₂)"}, {matiere:"nutrition",q:"Une boisson zéro sucre idéale ?",r:"l'eau 💧"} ], bouge: "gainage 20 s" },
  { ref: "5E·03", questions: [ {matiere:"maths",q:"Périmètre d'un carré de côté 5 cm ?",r:"20 cm"}, {matiere:"francais",q:"Conjugue « aller » au présent (je).",r:"je vais"}, {matiere:"histoire",q:"Qui a fondé Rome selon la légende ?",r:"Romulus"}, {matiere:"geo",q:"Combien de continents sur Terre ?",r:"6 (ou 7)"} ], bouge: "10 fentes" },
  { ref: "5E·04", questions: [ {matiere:"maths",q:"Aire d'un rectangle 4 cm × 3 cm ?",r:"12 cm²"}, {matiere:"anglais",q:"Traduis « she is happy ».",r:"elle est contente"}, {matiere:"sport",q:"Boire pendant l'effort : vrai ou faux ?",r:"vrai, régulièrement"}, {matiere:"reunion",q:"Le plat créole aux grains, avec du riz ?",r:"le cari / le rougail"} ], bouge: "15 jumping jacks" },
  { ref: "5E·05", questions: [ {matiere:"maths",q:"Simplifie 6/8.",r:"3/4"}, {matiere:"francais",q:"« et » ou « est » : « Il ___ grand ___ fort. »",r:"est / et"}, {matiere:"sciences",q:"Combien de planètes dans le système solaire ?",r:"8"}, {matiere:"nutrition",q:"Un fruit péi riche en vitamine C ?",r:"le letchi ou la goyave"} ], bouge: "cours sur place 20 s" },
  { ref: "5E·06", questions: [ {matiere:"maths",q:"Le plus grand : 0,5 ; 0,05 ; 0,55 ?",r:"0,55"}, {matiere:"anglais",q:"Pluriel de « child » ?",r:"children"}, {matiere:"geo",q:"Le plus grand océan ?",r:"l'océan Pacifique"}, {matiere:"histoire",q:"Écriture des Égyptiens ?",r:"les hiéroglyphes"} ], bouge: "20 sauts sur place" },
  { ref: "5E·07", questions: [ {matiere:"maths",q:"Calcule 1/2 + 1/4.",r:"3/4"}, {matiere:"francais",q:"Nature du mot « rapidement » ?",r:"un adverbe"}, {matiere:"sport",q:"Combien d'heures de sommeil vers 12 ans ?",r:"environ 9 à 10 h"}, {matiere:"nutrition",q:"Le diabète est lié à l'excès de quoi ?",r:"de sucre 🍬"} ], bouge: "gainage 20 s" },
  { ref: "5E·08", questions: [ {matiere:"maths",q:"7 × 8 = ?",r:"56"}, {matiere:"anglais",q:"Traduis « we go to school ».",r:"nous allons à l'école"}, {matiere:"sciences",q:"Mélange eau + huile : homogène ?",r:"non, hétérogène"}, {matiere:"reunion",q:"« ça va ? » en créole ?",r:"« Koman i lé ? »"} ], bouge: "10 fentes" },
  { ref: "5E·09", questions: [ {matiere:"maths",q:"Convertis 1/5 en décimal.",r:"0,2"}, {matiere:"francais",q:"Trouve le COD : « Je mange une pomme. »",r:"une pomme"}, {matiere:"histoire",q:"Langue de la Grèce antique ?",r:"le grec"}, {matiere:"sport",q:"L'endurance : courir vite ou longtemps ?",r:"longtemps, à son rythme"} ], bouge: "15 jumping jacks" },
  { ref: "5E·10", questions: [ {matiere:"maths",q:"Périmètre rectangle 6 cm × 2 cm ?",r:"16 cm"}, {matiere:"anglais",q:"« have » à la 3e personne (he) ?",r:"has"}, {matiere:"sciences",q:"Organe de la respiration ?",r:"les poumons"}, {matiere:"nutrition",q:"Combien de fruits/légumes par jour ?",r:"5 par jour"} ], bouge: "cours sur place 20 s" },
  { ref: "5E·11", questions: [ {matiere:"maths",q:"Calcule (5 + 3) × 2.",r:"16"}, {matiere:"francais",q:"Passé composé de « manger » (je).",r:"j'ai mangé"}, {matiere:"reunion",q:"Nom du volcan actif de La Réunion ?",r:"le Piton de la Fournaise 🌋"}, {matiere:"geo",q:"Sur quel continent est la France ?",r:"l'Europe"} ], bouge: "20 sauts sur place" },
  { ref: "5E·12", questions: [ {matiere:"maths",q:"Le double de 2,5 ?",r:"5"}, {matiere:"anglais",q:"Traduis « my name is Léa ».",r:"je m'appelle Léa"}, {matiere:"sport",q:"À quoi sert l'échauffement du cœur ?",r:"augmenter le rythme progressivement"}, {matiere:"nutrition",q:"Trop de sel : bon ou mauvais ?",r:"mauvais pour le cœur"} ], bouge: "gainage 20 s" },
  { ref: "5E·13", questions: [ {matiere:"maths",q:"Combien de côtés a un pentagone ?",r:"5"}, {matiere:"francais",q:"« La nuit tombe » : quelle figure ?",r:"une personnification"}, {matiere:"sciences",q:"L'astre au centre du système solaire ?",r:"le Soleil ☀️"}, {matiere:"histoire",q:"Peuple qui construisit les pyramides ?",r:"les Égyptiens"} ], bouge: "10 fentes" },
  { ref: "5E·14", questions: [ {matiere:"maths",q:"Écris 25 % en fraction simple.",r:"1/4"}, {matiere:"anglais",q:"Traduis « they are friends ».",r:"ils sont amis"}, {matiere:"reunion",q:"La musique traditionnelle réunionnaise ?",r:"le maloya"}, {matiere:"sport",q:"Que boire pour bien s'hydrater ?",r:"de l'eau, régulièrement"} ], bouge: "15 jumping jacks" },
  { ref: "5E·15", questions: [ {matiere:"maths",q:"Calcule 100 − 45.",r:"55"}, {matiere:"francais",q:"« ou » ou « où » : « Tu vas ___ ? »",r:"où"}, {matiere:"sciences",q:"Séparer le sable de l'eau : comment ?",r:"par filtration"}, {matiere:"nutrition",q:"Le petit-déjeuner, utile ou pas ?",r:"utile, il donne de l'énergie"} ], bouge: "cours sur place 20 s" },
  { ref: "5E·16", questions: [ {matiere:"maths",q:"Donne un exemple de nombre négatif.",r:"−3 (tout nombre inférieur à 0)"}, {matiere:"anglais",q:"Traduis « I like blue ».",r:"j'aime le bleu"}, {matiere:"geo",q:"Le plus grand désert chaud du monde ?",r:"le Sahara"}, {matiere:"histoire",q:"Chef gaulois face à César ?",r:"Vercingétorix"} ], bouge: "20 sauts sur place" },
  { ref: "5E·17", questions: [ {matiere:"maths",q:"3/10 en décimal ?",r:"0,3"}, {matiere:"francais",q:"Imparfait de « être » (il).",r:"il était"}, {matiere:"sport",q:"Faux départ en course : autorisé ?",r:"non, on recommence"}, {matiere:"nutrition",q:"Une part de gâteau tous les jours ?",r:"non, plutôt occasionnel 🍰"} ], bouge: "gainage 20 s" },
  { ref: "5E·18", questions: [ {matiere:"maths",q:"Aire d'un carré de côté 6 cm ?",r:"36 cm²"}, {matiere:"anglais",q:"« Monday » en français ?",r:"lundi"}, {matiere:"reunion",q:"Île voisine de La Réunion ?",r:"l'île Maurice"}, {matiere:"sciences",q:"On respire pour capter quel gaz ?",r:"le dioxygène (O₂)"} ], bouge: "10 fentes" },
  { ref: "5E·19", questions: [ {matiere:"maths",q:"Calcule 8 × 25.",r:"200"}, {matiere:"francais",q:"Futur de « finir » (nous).",r:"nous finirons"}, {matiere:"sport",q:"Rôle des étirements après le sport ?",r:"détendre les muscles"}, {matiere:"nutrition",q:"Un aliment plein de fibres ?",r:"fruits, légumes, céréales complètes"} ], bouge: "15 jumping jacks" },
  { ref: "5E·20", questions: [ {matiere:"maths",q:"2 stylos = 3 €. Prix de 4 stylos ?",r:"6 €"}, {matiere:"anglais",q:"Traduis « it is raining ».",r:"il pleut"}, {matiere:"geo",q:"Océan qui borde La Réunion ?",r:"l'océan Indien"}, {matiere:"histoire",q:"Année de la chute de l'Empire romain d'Occident ?",r:"476"} ], bouge: "cours sur place 20 s" },
  { ref: "5E·21", questions: [ {matiere:"maths",q:"Par symétrie, les dimensions sont-elles conservées ?",r:"oui, mêmes dimensions"}, {matiere:"francais",q:"« Fort comme un lion » : quelle figure ?",r:"une comparaison"}, {matiere:"sciences",q:"Un aliment riche en énergie ?",r:"les féculents (pâtes, riz)"}, {matiere:"nutrition",q:"Trop de sodas et diabète 974 : lien ?",r:"oui, l'excès de sucre favorise le diabète"} ], bouge: "20 sauts sur place" },
  { ref: "5E·22", questions: [ {matiere:"maths",q:"Moitié de 3/4 ?",r:"3/8"}, {matiere:"anglais",q:"Traduis « we have got a cat ».",r:"nous avons un chat"}, {matiere:"reunion",q:"Fruit rouge sucré de fin d'année à La Réunion ?",r:"le letchi 🍒"}, {matiere:"sport",q:"Combien de joueurs dans une équipe de foot ?",r:"11"} ], bouge: "gainage 20 s" },
  { ref: "5E·23", questions: [ {matiere:"maths",q:"Calcule 12 × 12.",r:"144"}, {matiere:"francais",q:"Fonction de « rouge » dans « la voiture rouge » ?",r:"épithète"}, {matiere:"sciences",q:"Le sucre dans l'eau : mélange homogène ?",r:"oui, il se dissout"}, {matiere:"histoire",q:"Peuple à l'origine de notre alphabet ?",r:"les Phéniciens"} ], bouge: "10 fentes" },
  { ref: "5E·24", questions: [ {matiere:"maths",q:"Convertis 1,5 en fraction.",r:"3/2"}, {matiere:"anglais",q:"« green » en français ?",r:"vert"}, {matiere:"sport",q:"Pourquoi bien dormir avant un match ?",r:"récupérer et être en forme"}, {matiere:"nutrition",q:"Meilleur en-cas : chips ou fruit ?",r:"un fruit 🍎"} ], bouge: "15 jumping jacks" },
  { ref: "5E·25", questions: [ {matiere:"maths",q:"Calcule 3 × (2 + 2).",r:"12"}, {matiere:"francais",q:"Présent de « faire » (vous).",r:"vous faites"}, {matiere:"reunion",q:"Cirque accessible seulement à pied ?",r:"Mafate"}, {matiere:"geo",q:"Capitale de la France ?",r:"Paris"} ], bouge: "cours sur place 20 s" },
  { ref: "5E·26", questions: [ {matiere:"maths",q:"0,25 + 0,75 = ?",r:"1"}, {matiere:"anglais",q:"Traduis « I don't know ».",r:"je ne sais pas"}, {matiere:"sciences",q:"Temps que met la Terre à tourner autour du Soleil ?",r:"1 an (365 jours)"}, {matiere:"sport",q:"Après le sport, on récupère avec quoi ?",r:"eau + repos"} ], bouge: "20 sauts sur place" },
  { ref: "5E·27", questions: [ {matiere:"maths",q:"Périmètre d'un triangle de côtés 3, 4, 5 cm ?",r:"12 cm"}, {matiere:"francais",q:"« son » ou « sont » : « ___ chien aboie » ?",r:"son"}, {matiere:"nutrition",q:"Combien de repas par jour, en général ?",r:"3 repas (+ un goûter)"}, {matiere:"histoire",q:"Général romain assassiné en −44 ?",r:"Jules César"} ], bouge: "gainage 20 s" },
  { ref: "5E·28", questions: [ {matiere:"maths",q:"−5 + 8 = ?",r:"3"}, {matiere:"anglais",q:"Traduis « what time is it? »",r:"quelle heure est-il ?"}, {matiere:"reunion",q:"Cirque connu pour ses eaux thermales ?",r:"Cilaos"}, {matiere:"sport",q:"Un bon échauffement dure environ… ?",r:"10 minutes"} ], bouge: "10 fentes" },
  { ref: "5E·29", questions: [ {matiere:"maths",q:"Combien de minutes dans 1 h 30 ?",r:"90 minutes"}, {matiere:"francais",q:"Nature de « nous » dans « nous chantons » ?",r:"un pronom personnel (sujet)"}, {matiere:"sciences",q:"Groupe d'aliments qui construit les muscles ?",r:"les protéines"}, {matiere:"nutrition",q:"Un cari péi équilibré, c'est… ?",r:"riz + grains + légumes = complet"} ], bouge: "15 jumping jacks" },
  { ref: "5E·30", questions: [ {matiere:"maths",q:"Calcule 4/5 de 20.",r:"16"}, {matiere:"anglais",q:"Traduis « see you tomorrow ».",r:"à demain"}, {matiere:"geo",q:"Le fleuve qui traverse Paris ?",r:"la Seine"}, {matiere:"sport",q:"Boire seulement quand on a soif : suffisant ?",r:"non, boire régulièrement"} ], bouge: "cours sur place 20 s" },
];
