// lib/matrice/apercus.generated.ts
//
// ⚠️ FICHIER GÉNÉRÉ — ne pas modifier à la main.
//     npm run capturer:apercus -- http://localhost:3000
//
// Les ressources qui ont une bande d'aperçu dans public/apercus/, et le nombre
// d'écrans que porte chacune (1 ou 2) — c'est-à-dire le nombre de pastilles de
// la fenêtre de survol, et le pas dont elle translate la bande.
//
// Une ressource absente d'ici garde sa vignette dessinée et n'ouvre pas de
// fenêtre au survol : c'est le cas des pages derrière une session, qu'un robot
// non connecté ne peut pas photographier honnêtement.

export const APERCUS: Readonly<Record<string, number>> = {
  "aiguille-de-kakeya": 2,
  "anglais-du-jour": 2,
  "bulles": 2,
  "cahier-aider": 2,
  "cahier-maths": 2,
  "cahier-vers-la-2nde": 2,
  "cahier-vers-la-3e": 2,
  "cahier-vers-la-4e": 2,
  "cahier-vers-la-5e": 2,
  "cahier-vers-la-6e": 2,
  "cahier-vers-la-premiere": 2,
  "cahier-vers-la-terminale": 2,
  "cahier-vers-le-bac-plus-1": 2,
  "cahier-vers-le-ce1": 2,
  "cahier-vers-le-ce2": 2,
  "cahier-vers-le-cm1": 2,
  "cahier-vers-le-cm2": 2,
  "cahier-vers-le-cp": 2,
  "calcul-rapide": 2,
  "carte-974": 2,
  "coach-anglais": 2,
  "coach-bac-spe": 2,
  "coach-brevet": 2,
  "coach-espagnol": 2,
  "coach-francais": 2,
  "coach-ia": 2,
  "coach-maths": 2,
  "concours-avenir": 2,
  "concours-general": 2,
  "defis-du-jour": 2,
  "diagonale-des-fous": 2,
  "dico": 2,
  "dictee-du-jour": 2,
  "dimension-du-volcan": 2,
  "espace-ecoles": 2,
  "espace-enseignants": 2,
  "espace-parents": 2,
  "espagnol-du-jour": 2,
  "eval-nat-4e-francais": 2,
  "eval-nat-4e-maths": 2,
  "eval-nat-6e-francais": 2,
  "eval-nat-6e-maths": 2,
  "eval-nationales-hub": 2,
  "eval-pix-ia": 2,
  "explorer": 2,
  "exponentielle": 2,
  "fiches-francais-4e": 2,
  "fiches-francais-5e": 2,
  "fiches-francais-6e": 2,
  "fiches-francais-cm2": 2,
  "fiches-ia": 2,
  "fiches-maths-4e": 2,
  "fiches-maths-5e": 2,
  "fiches-maths-6e": 2,
  "fiches-maths-cm2": 2,
  "fiches-maths-premiere": 2,
  "formation-crpe": 2,
  "guide-anglais-a1": 2,
  "guide-anglais-a2": 2,
  "guide-anglais-b1": 2,
  "guide-anglais-b2": 2,
  "guide-francais-3e": 2,
  "guide-francais-4e": 2,
  "guide-francais-5e": 2,
  "guide-francais-6e": 2,
  "guide-francais-cm1": 2,
  "guide-francais-cm2": 2,
  "guide-maths-cinquieme": 2,
  "guide-maths-cm1": 2,
  "guide-maths-cm2": 2,
  "guide-maths-premiere": 2,
  "guide-maths-quatrieme": 2,
  "guide-maths-seconde": 2,
  "guide-maths-sixieme": 2,
  "guide-maths-terminale": 2,
  "guide-maths-troisieme": 2,
  "loi-normale": 2,
  "loi-pareto": 2,
  "loi-performance": 2,
  "maths-974": 2,
  "parcours-anglais": 2,
  "parcours-espagnol": 2,
  "parcours-francais": 2,
  "parcours-ia": 2,
  "parcours": 2,
  "photo-cours": 1,
  "picto-maths": 2,
  "programme-seo": 2,
  "prompt-pedagogique": 1,
  "simulateur-barrage": 2,
  "simulateur-cyclone": 2,
  "simulateur-energie": 2,
  "simulateur-epsilon": 2,
  "simulateur-fromage": 2,
  "simulateur-hotel": 2,
  "simulateur-lagon": 2,
  "simulateur-sucre": 2,
  "simulateur-volcan": 2,
  "toutes-les-machines": 2,
};

/** Le chemin de la bande d'une ressource, ou `null` si elle n'en a pas. */
export function bandeApercu(id: string): { src: string; ecrans: number } | null {
  const ecrans = APERCUS[id];
  if (!ecrans) return null;
  return { src: `/apercus/${id}.${ecrans}.webp`, ecrans };
}
