// « Cartes défis · Vers la 1re » (prototype co-brandé Keep Cool).
// Conseil à 7 rôles, l'élève tranche : ton adulte, jamais moralisateur.
// Révision fin de 2nde → entrée en 1re (le trou de Nathan lycée). Rééquilibré :
// le disciplinaire domine (maths second degré/fonctions/proba, français bac, sciences),
// on garde le hook fitness/apparence (sport + nutrition) mais PROPORTIONNÉ,
// + 📱 numérique (image de soi, esprit critique) et 🤝 emc (respect, émotions, consentement).

import type { CarteDefi } from "@/components/cartes/types";

export const CARTES: CarteDefi[] = [
  { ref: "1RE·01", questions: [ {matiere:"maths",q:"Résous x² = 49",r:"x = 7 ou x = −7"}, {matiere:"francais",q:"Quelle figure : « cette valise pèse une tonne » ?",r:"Une hyperbole"}, {matiere:"anglais",q:"Traduis « I have lived here for 10 years »",r:"J'habite ici depuis 10 ans"}, {matiere:"sciences",q:"Formule chimique de l'eau ?",r:"H₂O"} ], bouge: "20 squats" },
  { ref: "1RE·02", questions: [ {matiere:"maths",q:"Développe (x + 3)²",r:"x² + 6x + 9"}, {matiere:"histoire",q:"En quelle année débute la Révolution française ?",r:"1789"}, {matiere:"numerique",q:"Vrai/faux : une photo Insta reflète toujours la réalité.",r:"Faux, souvent retouchée/filtrée"}, {matiere:"sport",q:"Temps de récup minimum pour un même muscle ?",r:"Environ 48 h"} ], bouge: "30 s de gainage (planche)" },
  { ref: "1RE·03", questions: [ {matiere:"maths",q:"Factorise x² − 9",r:"(x − 3)(x + 3)"}, {matiere:"francais",q:"Le romantisme, c'est quel siècle ?",r:"Le XIXe siècle"}, {matiere:"geo",q:"Qu'est-ce que la mondialisation ?",r:"La mise en relation des territoires du monde"}, {matiere:"nutrition",q:"Combien de kcal dans 1 g de protéines ?",r:"4 kcal"} ], bouge: "15 pompes" },
  { ref: "1RE·04", questions: [ {matiere:"maths",q:"Résous 2x + 6 = 0",r:"x = −3"}, {matiere:"anglais",q:"Prétérit de « to go » ?",r:"went"}, {matiere:"sciences",q:"Un ion Na⁺ a gagné ou perdu un électron ?",r:"Perdu un électron"}, {matiere:"emc",q:"Consentement, vrai/faux : un « oui » forcé est un vrai oui.",r:"Faux"} ], bouge: "25 mountain climbers" },
  { ref: "1RE·05", questions: [ {matiere:"maths",q:"Image de 3 par f(x) = 2x − 1 ?",r:"5"}, {matiere:"francais",q:"Registre d'un texte qui fait rire ?",r:"Le registre comique"}, {matiere:"numerique",q:"C'est quoi une fake news ?",r:"Une fausse information diffusée comme vraie"}, {matiere:"sport",q:"À quoi sert l'échauffement ?",r:"Préparer le corps, éviter les blessures"} ], bouge: "40 s de saut sur place" },
  { ref: "1RE·06", questions: [ {matiere:"maths",q:"2⁵ = ?",r:"32"}, {matiere:"histoire",q:"Qui prend le pouvoir par un coup d'État en 1799 ?",r:"Napoléon Bonaparte"}, {matiere:"nutrition",q:"Combien de litres d'eau par jour environ ?",r:"Environ 1,5 à 2 L"}, {matiere:"anglais",q:"Traduis « She has already eaten »",r:"Elle a déjà mangé"} ], bouge: "20 fentes (10 par jambe)" },
  { ref: "1RE·07", questions: [ {matiere:"maths",q:"Coeff directeur de la droite y = 3x + 2 ?",r:"3"}, {matiere:"anglais",q:"Present perfect de « to see » (I …) ?",r:"I have seen"}, {matiere:"geo",q:"Cite un pôle majeur de la mondialisation.",r:"New York, Londres, Shanghai…"}, {matiere:"sciences",q:"Symbole chimique du carbone ?",r:"C"} ], bouge: "30 jumping jacks" },
  { ref: "1RE·08", questions: [ {matiere:"maths",q:"Résous x² − 5x = 0",r:"x = 0 ou x = 5"}, {matiere:"francais",q:"Comparaison ou métaphore : « fort comme un lion » ?",r:"Une comparaison (avec « comme »)"}, {matiere:"sport",q:"Que sont les macros ?",r:"Protéines, glucides, lipides"}, {matiere:"numerique",q:"Pourquoi protéger ses données perso ?",r:"Éviter piratage, usurpation, pistage"} ], bouge: "45 s de gainage" },
  { ref: "1RE·09", questions: [ {matiere:"maths",q:"Notation scientifique de 3400 ?",r:"3,4 × 10³"}, {matiere:"sciences",q:"Unité de base du vivant ?",r:"La cellule"}, {matiere:"histoire",q:"1848 en France : quel régime naît ?",r:"La IIe République"}, {matiere:"nutrition",q:"Rôle des protéines pour le muscle ?",r:"Réparer et construire les fibres"} ], bouge: "15 burpees" },
  { ref: "1RE·10", questions: [ {matiere:"maths",q:"Résous 3(x − 2) = 9",r:"x = 5"}, {matiere:"anglais",q:"Traduis « I've never been to London »",r:"Je ne suis jamais allé à Londres"}, {matiere:"emc",q:"On te coupe la parole sans cesse : que fais-tu ?",r:"Je le dis calmement et je repose mon point"}, {matiere:"geo",q:"Une inégalité de la mondialisation ?",r:"L'écart de richesse Nord/Sud"} ], bouge: "20 relevés de genoux rapides" },
  { ref: "1RE·11", questions: [ {matiere:"maths",q:"Développe (x − 4)(x + 4)",r:"x² − 16"}, {matiere:"francais",q:"Auteur des « Misérables » ?",r:"Victor Hugo"}, {matiere:"numerique",q:"Un effet possible d'un temps d'écran excessif ?",r:"Fatigue, mauvais sommeil, moins de concentration"}, {matiere:"sport",q:"Pourquoi bien dormir pour progresser ?",r:"Le muscle récupère et se construit la nuit"} ], bouge: "50 s de planche" },
  { ref: "1RE·12", questions: [ {matiere:"maths",q:"10⁻³ = ?",r:"0,001"}, {matiere:"sciences",q:"Que mesure-t-on en joules ?",r:"L'énergie"}, {matiere:"nutrition",q:"Combien de kcal dans 1 g de lipides ?",r:"9 kcal"}, {matiere:"histoire",q:"Napoléon est sacré empereur en… ?",r:"1804"} ], bouge: "20 squats sautés" },
  { ref: "1RE·13", questions: [ {matiere:"maths",q:"Résous x² = 2x + 3",r:"x = 3 ou x = −1"}, {matiere:"anglais",q:"« since » ou « for » : « I've known her ___ 2010 » ?",r:"since"}, {matiere:"francais",q:"Le réalisme cherche à… ?",r:"Représenter la réalité fidèlement"}, {matiere:"emc",q:"Vrai/faux : respecter, c'est être d'accord avec tout.",r:"Faux, on respecte sans forcément approuver"} ], bouge: "30 s de chaise contre le mur" },
  { ref: "1RE·14", questions: [ {matiere:"maths",q:"Coordonnées du vecteur de A(1;2) à B(4;6) ?",r:"(3;4)"}, {matiere:"numerique",q:"Vrai/faux : un like définit ta valeur.",r:"Faux, ta valeur n'en dépend pas"}, {matiere:"sport",q:"Après l'effort, à quoi sert l'étirement ?",r:"Aider la récupération, garder la souplesse"}, {matiere:"geo",q:"Un flux de la mondialisation ?",r:"Marchandises, capitaux, informations ou humains"} ], bouge: "25 talons-fesses" },
  { ref: "1RE·15", questions: [ {matiere:"maths",q:"Résous 5x − 7 = 3x + 1",r:"x = 4"}, {matiere:"sciences",q:"Atome neutre : autant de protons que de… ?",r:"d'électrons"}, {matiere:"histoire",q:"La Déclaration des droits de l'homme date de… ?",r:"1789"}, {matiere:"nutrition",q:"Un aliment riche en protéines ?",r:"Œuf, poulet, poisson, légumineuses…"} ], bouge: "15 pompes serrées" },
  { ref: "1RE·16", questions: [ {matiere:"maths",q:"Factorise x² + 6x + 9",r:"(x + 3)²"}, {matiere:"francais",q:"« Ô temps, suspends ton vol ! » : quelle figure ?",r:"Une apostrophe"}, {matiere:"anglais",q:"Prétérit de « to buy » ?",r:"bought"}, {matiere:"emc",q:"Gérer sa colère : une bonne 1re étape ?",r:"Respirer, prendre du recul avant de réagir"} ], bouge: "40 mountain climbers" },
  { ref: "1RE·17", questions: [ {matiere:"maths",q:"20 % de 150 ?",r:"30"}, {matiere:"numerique",q:"Une donnée perso publiée peut-elle disparaître ?",r:"Difficilement, elle peut rester en ligne"}, {matiere:"sport",q:"Fréquence d'entraînement raisonnable par semaine ?",r:"3 à 4 séances pour bien récupérer"}, {matiere:"sciences",q:"Formule du dioxyde de carbone ?",r:"CO₂"} ], bouge: "50 s de gainage latéral (25 s/côté)" },
  { ref: "1RE·18", questions: [ {matiere:"maths",q:"Résous x² − 4 = 0",r:"x = 2 ou x = −2"}, {matiere:"francais",q:"Le siècle des Lumières, c'est le… ?",r:"XVIIIe siècle"}, {matiere:"nutrition",q:"À La Réunion (974), quelle maladie liée à l'alimentation est fréquente ?",r:"Le diabète"}, {matiere:"histoire",q:"Défaite finale de Napoléon à Waterloo en… ?",r:"1815"} ], bouge: "20 fentes sautées" },
  { ref: "1RE·19", questions: [ {matiere:"maths",q:"Résous 4x = 2x + 10",r:"x = 5"}, {matiere:"anglais",q:"Traduis « They have finished their homework »",r:"Ils ont fini leurs devoirs"}, {matiere:"emc",q:"Un pote se fait humilier : que fais-tu ?",r:"Je le soutiens, je n'en rajoute pas"}, {matiere:"francais",q:"Genre d'une pièce jouée sur scène ?",r:"Le théâtre"} ], bouge: "30 s de sprint sur place" },
  { ref: "1RE·20", questions: [ {matiere:"maths",q:"Hypoténuse d'un triangle rectangle de côtés 3 et 4 ?",r:"5 (Pythagore)"}, {matiere:"sciences",q:"Quel gaz la photosynthèse rejette-t-elle ?",r:"Du dioxygène (O₂)"}, {matiere:"sport",q:"Signe d'une bonne hydratation à l'effort ?",r:"Urines claires, pas de soif intense"}, {matiere:"geo",q:"Une firme transnationale, c'est… ?",r:"Une entreprise implantée dans plusieurs pays"} ], bouge: "15 burpees" },
  { ref: "1RE·21", questions: [ {matiere:"maths",q:"cos(60°) = ?",r:"0,5"}, {matiere:"francais",q:"Une antithèse, c'est… ?",r:"Opposer deux idées contraires"}, {matiere:"nutrition",q:"Trop de sel : quel risque ?",r:"L'hypertension"}, {matiere:"numerique",q:"Face à une info, 1er réflexe critique ?",r:"Vérifier la source"} ], bouge: "45 s de planche + 10 pompes" },
  { ref: "1RE·22", questions: [ {matiere:"maths",q:"Résous 2x² = 8",r:"x = 2 ou x = −2"}, {matiere:"anglais",q:"« for » exprime une durée : « ___ three hours » ?",r:"for"}, {matiere:"histoire",q:"Abolition définitive de l'esclavage en France en… ?",r:"1848"}, {matiere:"emc",q:"Consentement : peut-on changer d'avis après un oui ?",r:"Oui, toujours"} ], bouge: "25 squats + 15 s gainage" },
  { ref: "1RE·23", questions: [ {matiere:"maths",q:"Aire d'un disque de rayon 5 (π ≈ 3,14) ?",r:"Environ 78,5"}, {matiere:"sciences",q:"Charge électrique d'un proton ?",r:"Positive (+)"}, {matiere:"sport",q:"Vrai/faux : une courbature = muscle qui grossit.",r:"Faux, ce sont des micro-lésions en réparation"}, {matiere:"francais",q:"Le naturalisme est associé à quel auteur ?",r:"Émile Zola"} ], bouge: "30 talons-fesses rapides" },
  { ref: "1RE·24", questions: [ {matiere:"maths",q:"Résous (x − 1)(x + 2) = 0",r:"x = 1 ou x = −2"}, {matiere:"francais",q:"Une périphrase pour « le Soleil » ?",r:"« L'astre du jour »"}, {matiere:"numerique",q:"Photos retouchées : effet sur l'image de soi ?",r:"Complexes, comparaison irréaliste"}, {matiere:"emc",q:"Dire les choses avec respect, ça s'appelle… ?",r:"Être assertif"} ], bouge: "20 pompes" },
  { ref: "1RE·25", questions: [ {matiere:"maths",q:"Résous 3x² − 12 = 0",r:"x = 2 ou x = −2"}, {matiere:"anglais",q:"Complète : « I ___ just finished » (present perfect)",r:"I have just finished"}, {matiere:"francais",q:"Une allitération répète des… ?",r:"Consonnes (sons proches)"}, {matiere:"sport",q:"Combien d'heures de sommeil conseillées à 16 ans ?",r:"Environ 8 à 9 h"} ], bouge: "50 s de corde à sauter" },
  { ref: "1RE·26", questions: [ {matiere:"maths",q:"Proba d'obtenir un 6 avec un dé équilibré ?",r:"1/6"}, {matiere:"sciences",q:"Quelle énergie stocke une batterie ?",r:"De l'énergie chimique"}, {matiere:"nutrition",q:"Protéines/kg/jour visées pour la muscu (ordre) ?",r:"Environ 1,5 à 2 g/kg"}, {matiere:"geo",q:"Un territoire à l'écart de la mondialisation, on dit… ?",r:"Une périphérie délaissée"} ], bouge: "15 squats sautés" },
  { ref: "1RE·27", questions: [ {matiere:"histoire",q:"Prise de la Bastille : quel jour ?",r:"14 juillet 1789"}, {matiere:"anglais",q:"Traduis « Have you ever tried sushi? »",r:"As-tu déjà essayé les sushis ?"}, {matiere:"francais",q:"Une strophe de 4 vers s'appelle… ?",r:"Un quatrain"}, {matiere:"emc",q:"Face à un désaccord, que fais-tu ?",r:"J'écoute et j'expose mes idées sans insulter"} ], bouge: "30 mountain climbers" },
  { ref: "1RE·28", questions: [ {matiere:"francais",q:"Un exemple d'oxymore ?",r:"« Un silence assourdissant »"}, {matiere:"numerique",q:"Cyberharcèlement : le bon réflexe ?",r:"Ne pas répondre, capturer, signaler, en parler"}, {matiere:"nutrition",q:"Un petit-déj équilibré, quel combo ?",r:"Protéine + sucre lent + fruit"}, {matiere:"sciences",q:"À 0 °C, quel changement d'état de l'eau ?",r:"Fusion/solidification (liquide ↔ solide)"} ], bouge: "40 s de gainage" },
  { ref: "1RE·29", questions: [ {matiere:"anglais",q:"Prétérit de « to eat » ?",r:"ate"}, {matiere:"sport",q:"Gagner en force : augmenter quoi progressivement ?",r:"La charge (surcharge progressive)"}, {matiere:"emc",q:"Gérer le stress avant un oral : une technique ?",r:"Respiration lente ou visualisation"}, {matiere:"nutrition",q:"Boisson à limiter pour dents et poids ?",r:"Les sodas sucrés"} ], bouge: "20 burpees" },
  { ref: "1RE·30", questions: [ {matiere:"francais",q:"Quel registre suscite la pitié ?",r:"Le registre pathétique"}, {matiere:"numerique",q:"Un mot de passe solide, c'est… ?",r:"Long, varié (lettres/chiffres/symboles) et unique"}, {matiere:"emc",q:"Avant de poster, je me demande… ?",r:"Est-ce vrai, utile, respectueux ?"}, {matiere:"sciences",q:"Combien de chromosomes chez l'humain ?",r:"46 (23 paires)"} ], bouge: "45 s de planche" },
];
