import type { MicroSkillSource } from "@/lib/tutor-v4/knowledge/buildKnowledge";

export const microSkills: MicroSkillSource[] = [
  { id: "es_b1_opinions_es_to_fr",    label: "Reconnaître opinion ES → FR",          notionId: "es_b1_opinions",    prerequis: [] },
  { id: "es_b1_opinions_fr_to_es",    label: "Donner opinion FR → ES",               notionId: "es_b1_opinions",    prerequis: ["es_b1_opinions_es_to_fr"] },
  { id: "es_b1_opinions_listen",      label: "Écouter et identifier l'opinion 🔊",    notionId: "es_b1_opinions",    prerequis: ["es_b1_opinions_es_to_fr"] },
  { id: "es_b1_environment_es_to_fr", label: "Reconnaître environnement ES → FR",    notionId: "es_b1_environment", prerequis: [] },
  { id: "es_b1_environment_fr_to_es", label: "Donner environnement FR → ES",         notionId: "es_b1_environment", prerequis: ["es_b1_environment_es_to_fr"] },
  { id: "es_b1_environment_listen",   label: "Écouter et identifier l'environnement 🔊", notionId: "es_b1_environment", prerequis: ["es_b1_environment_es_to_fr"] },
  { id: "es_b1_media_es_to_fr",       label: "Reconnaître médias ES → FR",           notionId: "es_b1_media",       prerequis: [] },
  { id: "es_b1_media_fr_to_es",       label: "Donner médias FR → ES",                notionId: "es_b1_media",       prerequis: ["es_b1_media_es_to_fr"] },
  { id: "es_b1_media_listen",         label: "Écouter et identifier les médias 🔊",   notionId: "es_b1_media",       prerequis: ["es_b1_media_es_to_fr"] },
  { id: "es_b1_economy_es_to_fr",     label: "Reconnaître économie ES → FR",         notionId: "es_b1_economy",     prerequis: [] },
  { id: "es_b1_economy_fr_to_es",     label: "Donner économie FR → ES",              notionId: "es_b1_economy",     prerequis: ["es_b1_economy_es_to_fr"] },
  { id: "es_b1_economy_listen",       label: "Écouter et identifier l'économie 🔊",   notionId: "es_b1_economy",     prerequis: ["es_b1_economy_es_to_fr"] },
  { id: "es_b1_science_es_to_fr",     label: "Reconnaître science ES → FR",          notionId: "es_b1_science",     prerequis: [] },
  { id: "es_b1_science_fr_to_es",     label: "Donner science FR → ES",               notionId: "es_b1_science",     prerequis: ["es_b1_science_es_to_fr"] },
  { id: "es_b1_science_listen",       label: "Écouter et identifier la science 🔊",   notionId: "es_b1_science",     prerequis: ["es_b1_science_es_to_fr"] },
  { id: "es_b1_finance_es_to_fr",            label: "Reconnaître finance ES → FR",              notionId: "es_b1_finance",            prerequis: [] },
  { id: "es_b1_finance_fr_to_es",            label: "Donner finance FR → ES",                   notionId: "es_b1_finance",            prerequis: ["es_b1_finance_es_to_fr"] },
  { id: "es_b1_finance_listen",              label: "Écouter et identifier la finance 🔊",       notionId: "es_b1_finance",            prerequis: ["es_b1_finance_es_to_fr"] },
  { id: "es_b1_physical_geography_es_to_fr", label: "Reconnaître géographie physique ES → FR",  notionId: "es_b1_physical_geography", prerequis: [] },
  { id: "es_b1_physical_geography_fr_to_es", label: "Donner géographie physique FR → ES",       notionId: "es_b1_physical_geography", prerequis: ["es_b1_physical_geography_es_to_fr"] },
  { id: "es_b1_physical_geography_listen",   label: "Écouter et identifier le relief 🔊",        notionId: "es_b1_physical_geography", prerequis: ["es_b1_physical_geography_es_to_fr"] },
  { id: "es_b1_science_biology_es_to_fr",    label: "Reconnaître biologie ES → FR",             notionId: "es_b1_science_biology",    prerequis: [] },
  { id: "es_b1_science_biology_fr_to_es",    label: "Donner biologie FR → ES",                  notionId: "es_b1_science_biology",    prerequis: ["es_b1_science_biology_es_to_fr"] },
  { id: "es_b1_science_biology_listen",      label: "Écouter et identifier la biologie 🔊",      notionId: "es_b1_science_biology",    prerequis: ["es_b1_science_biology_es_to_fr"] },
  { id: "es_b1_sport_stats_es_to_fr",        label: "Reconnaître stat sportive ES → FR",        notionId: "es_b1_sport_stats",        prerequis: [] },
  { id: "es_b1_sport_stats_fr_to_es",        label: "Donner stat sportive FR → ES",             notionId: "es_b1_sport_stats",        prerequis: ["es_b1_sport_stats_es_to_fr"] },
  { id: "es_b1_sport_stats_listen",          label: "Écouter et identifier la stat sportive 🔊", notionId: "es_b1_sport_stats",        prerequis: ["es_b1_sport_stats_es_to_fr"] },
];
