import type { TutorBankItemV4 } from "@/lib/tutor-v4/types";

// Vocabulaire A2 — vie quotidienne, voyage, métiers, budget, géographie, vivant, sport
const WORDS = [
  { slug: "ciudad",      es: "ciudad",      fr: "ville",         audio: "/audio/espagnol/daily_life/a2/ciudad.mp3"      },
  { slug: "calle",       es: "calle",       fr: "rue",           audio: "/audio/espagnol/daily_life/a2/calle.mp3"       },
  { slug: "tienda",      es: "tienda",      fr: "magasin",       audio: "/audio/espagnol/shopping/a2/tienda.mp3"        },
  { slug: "mercado",     es: "mercado",     fr: "marché",        audio: "/audio/espagnol/shopping/a2/mercado.mp3"       },
  { slug: "hospital",    es: "hospital",    fr: "hôpital",       audio: "/audio/espagnol/health/a2/hospital.mp3"        },
  { slug: "farmacia",    es: "farmacia",    fr: "pharmacie",     audio: "/audio/espagnol/health/a2/farmacia.mp3"        },
  { slug: "banco",       es: "banco",       fr: "banque",        audio: "/audio/espagnol/shopping/a2/banco.mp3"         },
  { slug: "autobus",     es: "autobús",     fr: "bus",           audio: "/audio/espagnol/travel/a2/autobus.mp3"         },
  { slug: "tren",        es: "tren",        fr: "train",         audio: "/audio/espagnol/travel/a2/tren.mp3"            },
  { slug: "avion",       es: "avión",       fr: "avion",         audio: "/audio/espagnol/travel/a2/avion.mp3"           },
  { slug: "medico",      es: "médico",      fr: "médecin",       audio: "/audio/espagnol/jobs/a2/medico.mp3"            },
  { slug: "enfermero",   es: "enfermero",   fr: "infirmier",     audio: "/audio/espagnol/jobs/a2/enfermero.mp3"         },
  { slug: "maestro",     es: "maestro",     fr: "instituteur",   audio: "/audio/espagnol/jobs/a2/maestro.mp3"           },
  { slug: "policia",     es: "policía",     fr: "policier",      audio: "/audio/espagnol/jobs/a2/policia.mp3"           },
  { slug: "bombero",     es: "bombero",     fr: "pompier",       audio: "/audio/espagnol/jobs/a2/bombero.mp3"           },
  { slug: "tiempo",      es: "tiempo",      fr: "temps / météo", audio: "/audio/espagnol/weather/a2/tiempo.mp3"         },
  { slug: "lluvia",      es: "lluvia",      fr: "pluie",         audio: "/audio/espagnol/weather/a2/lluvia.mp3"         },
  { slug: "sol",         es: "sol",         fr: "soleil",        audio: "/audio/espagnol/weather/a2/sol.mp3"            },
  { slug: "viento",      es: "viento",      fr: "vent",          audio: "/audio/espagnol/weather/a2/viento.mp3"         },
  { slug: "nieve",       es: "nieve",       fr: "neige",         audio: "/audio/espagnol/weather/a2/nieve.mp3"          },
  // Budget familial
  { slug: "ahorrar",     es: "ahorrar",     fr: "économiser",     audio: "/audio/espagnol/family_budget/a2/ahorrar.mp3"     },
  { slug: "gastar",      es: "gastar",      fr: "dépenser",       audio: "/audio/espagnol/family_budget/a2/gastar.mp3"      },
  { slug: "presupuesto", es: "presupuesto", fr: "budget",         audio: "/audio/espagnol/family_budget/a2/presupuesto.mp3" },
  { slug: "cuenta",      es: "cuenta",      fr: "compte",         audio: "/audio/espagnol/family_budget/a2/cuenta.mp3"      },
  { slug: "tarjeta",     es: "tarjeta",     fr: "carte bancaire", audio: "/audio/espagnol/family_budget/a2/tarjeta.mp3"     },
  { slug: "efectivo",    es: "efectivo",    fr: "espèces",        audio: "/audio/espagnol/family_budget/a2/efectivo.mp3"    },
  { slug: "factura",     es: "factura",     fr: "facture",        audio: "/audio/espagnol/family_budget/a2/factura.mp3"     },
  { slug: "rebajas",     es: "rebajas",     fr: "soldes",         audio: "/audio/espagnol/family_budget/a2/rebajas.mp3"     },
  { slug: "propina",     es: "propina",     fr: "pourboire",      audio: "/audio/espagnol/family_budget/a2/propina.mp3"     },
  { slug: "sueldo",      es: "sueldo",      fr: "salaire",        audio: "/audio/espagnol/family_budget/a2/sueldo.mp3"      },
  // Géographie & repères
  { slug: "mapa",        es: "mapa",        fr: "carte",          audio: "/audio/espagnol/geography/a2/mapa.mp3"       },
  { slug: "frontera",    es: "frontera",    fr: "frontière",      audio: "/audio/espagnol/geography/a2/frontera.mp3"   },
  { slug: "capital",     es: "capital",     fr: "capitale",       audio: "/audio/espagnol/geography/a2/capital.mp3"    },
  { slug: "pais",        es: "país",        fr: "pays",           audio: "/audio/espagnol/geography/a2/pais.mp3"       },
  { slug: "continente",  es: "continente",  fr: "continent",      audio: "/audio/espagnol/geography/a2/continente.mp3" },
  { slug: "norte",       es: "norte",       fr: "nord",           audio: "/audio/espagnol/geography/a2/norte.mp3"      },
  { slug: "sur",         es: "sur",         fr: "sud",            audio: "/audio/espagnol/geography/a2/sur.mp3"        },
  { slug: "este",        es: "este",        fr: "est",            audio: "/audio/espagnol/geography/a2/este.mp3"       },
  { slug: "oeste",       es: "oeste",       fr: "ouest",          audio: "/audio/espagnol/geography/a2/oeste.mp3"      },
  { slug: "region",      es: "región",      fr: "région",         audio: "/audio/espagnol/geography/a2/region.mp3"     },
  // Sciences du vivant
  { slug: "planta",      es: "planta",      fr: "plante",         audio: "/audio/espagnol/science_living/a2/planta.mp3"     },
  { slug: "arbol",       es: "árbol",       fr: "arbre",          audio: "/audio/espagnol/science_living/a2/arbol.mp3"      },
  { slug: "flor",        es: "flor",        fr: "fleur",          audio: "/audio/espagnol/science_living/a2/flor.mp3"       },
  { slug: "hoja",        es: "hoja",        fr: "feuille",        audio: "/audio/espagnol/science_living/a2/hoja.mp3"       },
  { slug: "raiz",        es: "raíz",        fr: "racine",         audio: "/audio/espagnol/science_living/a2/raiz.mp3"       },
  { slug: "semilla",     es: "semilla",     fr: "graine",         audio: "/audio/espagnol/science_living/a2/semilla.mp3"    },
  { slug: "insecto",     es: "insecto",     fr: "insecte",        audio: "/audio/espagnol/science_living/a2/insecto.mp3"    },
  { slug: "fruto",       es: "fruto",       fr: "fruit",          audio: "/audio/espagnol/science_living/a2/fruto.mp3"      },
  { slug: "hierba",      es: "hierba",      fr: "herbe",          audio: "/audio/espagnol/science_living/a2/hierba.mp3"     },
  { slug: "naturaleza",  es: "naturaleza",  fr: "nature",         audio: "/audio/espagnol/science_living/a2/naturaleza.mp3" },
  // Verbes du sport
  { slug: "correr",      es: "correr",      fr: "courir",         audio: "/audio/espagnol/sport_verbs/a2/correr.mp3"   },
  { slug: "saltar",      es: "saltar",      fr: "sauter",         audio: "/audio/espagnol/sport_verbs/a2/saltar.mp3"   },
  { slug: "nadar",       es: "nadar",       fr: "nager",          audio: "/audio/espagnol/sport_verbs/a2/nadar.mp3"    },
  { slug: "lanzar",      es: "lanzar",      fr: "lancer",         audio: "/audio/espagnol/sport_verbs/a2/lanzar.mp3"   },
  { slug: "ganar",       es: "ganar",       fr: "gagner",         audio: "/audio/espagnol/sport_verbs/a2/ganar.mp3"    },
  { slug: "perder",      es: "perder",      fr: "perdre",         audio: "/audio/espagnol/sport_verbs/a2/perder.mp3"   },
  { slug: "entrenar",    es: "entrenar",    fr: "s'entraîner",    audio: "/audio/espagnol/sport_verbs/a2/entrenar.mp3" },
  { slug: "jugar",       es: "jugar",       fr: "jouer",          audio: "/audio/espagnol/sport_verbs/a2/jugar.mp3"    },
  { slug: "marcar",      es: "marcar",      fr: "marquer",        audio: "/audio/espagnol/sport_verbs/a2/marcar.mp3"   },
  { slug: "competir",    es: "competir",    fr: "concourir",      audio: "/audio/espagnol/sport_verbs/a2/competir.mp3" },
] as const;

function dFr(exclude: string) { return WORDS.filter(w => w.fr !== exclude).map(w => w.fr).slice(0, 3); }
function dEs(exclude: string) { return WORDS.filter(w => w.es !== exclude).map(w => w.es).slice(0, 3); }

const notionMap: Record<string, string> = {
  ciudad: "es_a2_daily_life", calle: "es_a2_daily_life",
  tienda: "es_a2_shopping", mercado: "es_a2_shopping", banco: "es_a2_shopping",
  hospital: "es_a2_health", farmacia: "es_a2_health",
  autobus: "es_a2_travel", tren: "es_a2_travel", avion: "es_a2_travel",
  medico: "es_a2_jobs", enfermero: "es_a2_jobs", maestro: "es_a2_jobs", policia: "es_a2_jobs", bombero: "es_a2_jobs",
  tiempo: "es_a2_weather", lluvia: "es_a2_weather", sol: "es_a2_weather", viento: "es_a2_weather", nieve: "es_a2_weather",
  ahorrar: "es_a2_family_budget", gastar: "es_a2_family_budget", presupuesto: "es_a2_family_budget", cuenta: "es_a2_family_budget", tarjeta: "es_a2_family_budget",
  efectivo: "es_a2_family_budget", factura: "es_a2_family_budget", rebajas: "es_a2_family_budget", propina: "es_a2_family_budget", sueldo: "es_a2_family_budget",
  mapa: "es_a2_geography", frontera: "es_a2_geography", capital: "es_a2_geography", pais: "es_a2_geography", continente: "es_a2_geography",
  norte: "es_a2_geography", sur: "es_a2_geography", este: "es_a2_geography", oeste: "es_a2_geography", region: "es_a2_geography",
  planta: "es_a2_science_living", arbol: "es_a2_science_living", flor: "es_a2_science_living", hoja: "es_a2_science_living", raiz: "es_a2_science_living",
  semilla: "es_a2_science_living", insecto: "es_a2_science_living", fruto: "es_a2_science_living", hierba: "es_a2_science_living", naturaleza: "es_a2_science_living",
  correr: "es_a2_sport_verbs", saltar: "es_a2_sport_verbs", nadar: "es_a2_sport_verbs", lanzar: "es_a2_sport_verbs", ganar: "es_a2_sport_verbs",
  perder: "es_a2_sport_verbs", entrenar: "es_a2_sport_verbs", jugar: "es_a2_sport_verbs", marcar: "es_a2_sport_verbs", competir: "es_a2_sport_verbs",
};

export const espagnolA2QuestionBank: TutorBankItemV4[] = WORDS.flatMap((word) => {
  const notionId = notionMap[word.slug] ?? "es_a2_daily_life";
  return [
    {
      kind: "fixed" as const,
      id: `es_a2_${word.slug}_es_to_fr`,
      niveau: "a2" as const,
      matiere: "espagnol" as const,
      notionId,
      microId: `${notionId}_es_to_fr`,
      difficulty: 1 as const,
      text: `Que signifie "${word.es}" en français ?`,
      format: "qcm" as const,
      choices: [word.fr, ...dFr(word.fr)],
      expected: [word.fr],
      comparator: "mcq_exact" as const,
      explanation: `"${word.es}" = "${word.fr}".`,
    },
    {
      kind: "fixed" as const,
      id: `es_a2_${word.slug}_fr_to_es`,
      niveau: "a2" as const,
      matiere: "espagnol" as const,
      notionId,
      microId: `${notionId}_fr_to_es`,
      difficulty: 2 as const,
      text: `Comment dit-on "${word.fr}" en espagnol ?`,
      format: "qcm" as const,
      choices: [word.es, ...dEs(word.es)],
      expected: [word.es],
      comparator: "mcq_exact" as const,
      explanation: `"${word.fr}" se dit "${word.es}" en espagnol.`,
    },
    {
      kind: "fixed" as const,
      id: `es_a2_${word.slug}_listen`,
      niveau: "a2" as const,
      matiere: "espagnol" as const,
      notionId,
      microId: `${notionId}_listen`,
      difficulty: 2 as const,
      text: `🔊 Écoute et choisis la traduction française.`,
      format: "qcm" as const,
      audioSrc: word.audio,
      choices: [word.fr, ...dFr(word.fr)],
      expected: [word.fr],
      comparator: "mcq_exact" as const,
      hint: `Écoute attentivement la prononciation.`,
      explanation: `Le mot entendu est "${word.es}" (${word.fr}).`,
    },
  ];
});
