import type { CoachBrevetFixedItem } from "../types";

export const algebreBank: CoachBrevetFixedItem[] = [
  {
    kind: "fixed",
    id: "brevet-alg-001",
    niveau: "3e",
    matiere: "maths",
    notionId: "calcul_litteral",
    microId: "developpement",
    difficulty: 1,
    theme: "automatisme",
    text: "Développe et réduis : 3(x + 5) − 2x",
    format: "short",
    expected: ["x+15", "x + 15"],
    comparator: "exact",
    hint: "Distribue d'abord le 3.",
    explanation: "3x + 15 − 2x = x + 15",
    tags: ["développement"],
  },
  {
    kind: "fixed",
    id: "brevet-alg-002",
    niveau: "3e",
    matiere: "maths",
    notionId: "calcul_litteral",
    microId: "identites-remarquables",
    difficulty: 2,
    theme: "automatisme",
    text: "Développe : (x + 3)²",
    format: "short",
    expected: ["x²+6x+9", "x^2+6x+9"],
    comparator: "exact",
    hint: "(a + b)² = a² + 2ab + b²",
    explanation: "(x+3)² = x² + 2×x×3 + 3² = x² + 6x + 9",
    tags: ["identité remarquable"],
  },
  {
    kind: "fixed",
    id: "brevet-alg-003",
    niveau: "3e",
    matiere: "maths",
    notionId: "calcul_litteral",
    microId: "factorisation",
    difficulty: 2,
    theme: "automatisme",
    text: "Factorise : x² − 9",
    format: "short",
    expected: ["(x-3)(x+3)", "(x+3)(x-3)"],
    comparator: "exact",
    hint: "Utilise l'identité a² − b² = (a−b)(a+b) avec b = 3.",
    explanation: "x² − 9 = x² − 3² = (x−3)(x+3)",
    tags: ["identité remarquable", "différence de carrés"],
  },
  {
    kind: "fixed",
    id: "brevet-alg-004",
    niveau: "3e",
    matiere: "maths",
    notionId: "equations",
    microId: "equation-premier-degre",
    difficulty: 1,
    theme: "automatisme",
    text: "Résous l'équation : 3x − 7 = 11",
    format: "short",
    expected: ["6"],
    comparator: "number_equal",
    hint: "Isole x en ajoutant 7 des deux côtés, puis divise par 3.",
    explanation: "3x = 18, donc x = 6.",
    tags: ["équation"],
  },
  {
    kind: "fixed",
    id: "brevet-alg-005",
    niveau: "3e",
    matiere: "maths",
    notionId: "equations",
    microId: "equation-avec-parentheses",
    difficulty: 2,
    theme: "brevet",
    text: "Résous : 2(x − 3) = 4x + 2",
    format: "short",
    expected: ["-4"],
    comparator: "number_equal",
    hint: "Développe d'abord le membre gauche.",
    explanation: "2x − 6 = 4x + 2 → −6 − 2 = 4x − 2x → −8 = 2x → x = −4",
    tags: ["équation", "développement"],
  },
  {
    kind: "fixed",
    id: "brevet-alg-006",
    niveau: "3e",
    matiere: "maths",
    notionId: "equations",
    microId: "systeme",
    difficulty: 3,
    theme: "brevet",
    text: "Résous le système : { x + y = 10 et 2x − y = 5 }",
    format: "short",
    expected: ["x=5, y=5", "x = 5 et y = 5"],
    comparator: "exact",
    hint: "Additionne les deux équations pour éliminer y.",
    explanation: "En additionnant : 3x = 15 donc x = 5, puis y = 10 − 5 = 5.",
    tags: ["système d'équations"],
  },
  {
    kind: "fixed",
    id: "brevet-alg-007",
    niveau: "3e",
    matiere: "maths",
    notionId: "inegalites",
    microId: "inequation",
    difficulty: 2,
    theme: "automatisme",
    text: "Résous l'inéquation : 2x + 3 > 9",
    format: "short",
    expected: ["x>3"],
    comparator: "exact",
    hint: "Isolate x comme pour une équation.",
    explanation: "2x > 6 donc x > 3.",
    tags: ["inéquation"],
  },
  {
    kind: "fixed",
    id: "brevet-alg-008",
    niveau: "3e",
    matiere: "maths",
    notionId: "inegalites",
    microId: "piege-inegalite",
    difficulty: 2,
    theme: "piege",
    text: "Résous : −3x < 12. Que vaut x ?",
    format: "qcm",
    choices: ["x < −4", "x > −4"],
    expected: ["x > −4"],
    comparator: "mcq_exact",
    hint: "Attention : diviser par un nombre négatif inverse le sens de l'inégalité !",
    explanation: "En divisant par −3 (négatif), on inverse : x > −4.",
    tags: ["piege", "inégalité"],
  },
];
