import type { CoachBrevetFixedItem } from "../types";

export const fonctionsBank: CoachBrevetFixedItem[] = [
  {
    kind: "fixed",
    id: "brevet-fonc-001",
    niveau: "3e",
    matiere: "maths",
    notionId: "fonctions",
    microId: "image",
    difficulty: 1,
    theme: "automatisme",
    text: "Pour la fonction f(x) = 2x − 3, calcule f(4).",
    format: "short",
    expected: ["5"],
    comparator: "number_equal",
    hint: "Remplace x par 4 dans la formule.",
    explanation: "f(4) = 2 × 4 − 3 = 8 − 3 = 5.",
    tags: ["image", "calcul"],
  },
  {
    kind: "fixed",
    id: "brevet-fonc-002",
    niveau: "3e",
    matiere: "maths",
    notionId: "fonctions",
    microId: "antecedent",
    difficulty: 2,
    theme: "automatisme",
    text: "Pour f(x) = 3x + 1, quel est l'antécédent de 10 ?",
    format: "short",
    expected: ["3"],
    comparator: "number_equal",
    hint: "Résous l'équation f(x) = 10.",
    explanation: "3x + 1 = 10 → 3x = 9 → x = 3.",
    tags: ["antécédent"],
  },
  {
    kind: "fixed",
    id: "brevet-fonc-003",
    niveau: "3e",
    matiere: "maths",
    notionId: "fonctions",
    microId: "lecture-graphique",
    difficulty: 2,
    theme: "brevet",
    text: "Sur un graphique, la courbe passe par les points (0 ; 2) et (3 ; 8). Quelle est la fonction affine correspondante ?",
    format: "qcm",
    choices: ["f(x) = 2x + 2", "f(x) = 3x + 2", "f(x) = 2x + 3"],
    expected: ["f(x) = 2x + 2"],
    comparator: "mcq_exact",
    hint: "Pente = (8−2)/(3−0) = 2. Ordonnée à l'origine = 2.",
    explanation: "a = (8−2)/(3−0) = 2, b = 2. Donc f(x) = 2x + 2.",
    tags: ["lecture graphique", "fonction affine"],
  },
  {
    kind: "fixed",
    id: "brevet-fonc-004",
    niveau: "3e",
    matiere: "maths",
    notionId: "fonctions",
    microId: "tableau-valeurs",
    difficulty: 1,
    theme: "automatisme",
    text: "f(x) = x² − 1. Calcule f(−2).",
    format: "short",
    expected: ["3"],
    comparator: "number_equal",
    hint: "Attention au carré d'un nombre négatif.",
    explanation: "f(−2) = (−2)² − 1 = 4 − 1 = 3.",
    tags: ["tableau de valeurs"],
  },
  {
    kind: "fixed",
    id: "brevet-fonc-005",
    niveau: "3e",
    matiere: "maths",
    notionId: "fonctions",
    microId: "piege-lineaire",
    difficulty: 2,
    theme: "piege",
    text: "f est une fonction linéaire telle que f(2) = 6. Quelle est f(5) ?",
    format: "short",
    expected: ["15"],
    comparator: "number_equal",
    hint: "Une fonction linéaire est f(x) = ax. Trouve a d'abord.",
    explanation: "f(x) = ax → f(2) = 2a = 6 → a = 3. Donc f(5) = 3 × 5 = 15.",
    tags: ["fonction linéaire"],
  },
  {
    kind: "fixed",
    id: "brevet-fonc-006",
    niveau: "3e",
    matiere: "maths",
    notionId: "fonctions",
    microId: "intersection",
    difficulty: 3,
    theme: "brevet",
    text: "Les droites d₁ : y = 2x + 1 et d₂ : y = −x + 7 se coupent en quel point ?",
    format: "short",
    expected: ["(2;5)", "(2, 5)", "x=2 y=5"],
    comparator: "exact",
    hint: "Pose 2x + 1 = −x + 7 et résous.",
    explanation: "2x + 1 = −x + 7 → 3x = 6 → x = 2, y = 5. Point (2 ; 5).",
    tags: ["intersection", "système"],
  },
];
