import type { CoachBrevetFixedItem } from "../types";

export const fractionsBank: CoachBrevetFixedItem[] = [
  {
    kind: "fixed",
    id: "brevet-frac-001",
    niveau: "3e",
    matiere: "maths",
    notionId: "fractions",
    microId: "addition",
    difficulty: 1,
    theme: "automatisme",
    text: "Calcule et simplifie : 1/3 + 1/6",
    format: "short",
    expected: ["1/2", "0.5"],
    comparator: "fraction_equal",
    hint: "Réduis au même dénominateur.",
    explanation: "1/3 + 1/6 = 2/6 + 1/6 = 3/6 = 1/2",
    tags: ["addition", "simplification"],
  },
  {
    kind: "fixed",
    id: "brevet-frac-002",
    niveau: "3e",
    matiere: "maths",
    notionId: "fractions",
    microId: "multiplication",
    difficulty: 1,
    theme: "automatisme",
    text: "Calcule : (3/4) × (8/9)",
    format: "short",
    expected: ["2/3"],
    comparator: "fraction_equal",
    hint: "Multiplie numérateurs entre eux et dénominateurs entre eux, puis simplifie.",
    explanation: "(3×8)/(4×9) = 24/36 = 2/3",
    tags: ["multiplication"],
  },
  {
    kind: "fixed",
    id: "brevet-frac-003",
    niveau: "3e",
    matiere: "maths",
    notionId: "fractions",
    microId: "division",
    difficulty: 2,
    theme: "automatisme",
    text: "Calcule : (5/6) ÷ (5/3)",
    format: "short",
    expected: ["1/2", "0.5"],
    comparator: "fraction_equal",
    hint: "Diviser par une fraction revient à multiplier par son inverse.",
    explanation: "(5/6) ÷ (5/3) = (5/6) × (3/5) = 15/30 = 1/2",
    tags: ["division"],
  },
  {
    kind: "fixed",
    id: "brevet-frac-004",
    niveau: "3e",
    matiere: "maths",
    notionId: "fractions",
    microId: "piege-soustraction",
    difficulty: 2,
    theme: "piege",
    text: "Un élève écrit : 1/2 + 1/3 = 2/5. Est-ce correct ?",
    format: "qcm",
    choices: ["Oui", "Non, la réponse est 5/6"],
    expected: ["Non, la réponse est 5/6"],
    comparator: "mcq_exact",
    hint: "On ne peut PAS additionner les numérateurs et les dénominateurs séparément.",
    explanation: "1/2 + 1/3 = 3/6 + 2/6 = 5/6. Additionner les dénominateurs est une erreur classique.",
    tags: ["piege", "addition"],
  },
  {
    kind: "fixed",
    id: "brevet-frac-005",
    niveau: "3e",
    matiere: "maths",
    notionId: "fractions",
    microId: "simplification",
    difficulty: 1,
    theme: "automatisme",
    text: "Simplifie la fraction 36/48.",
    format: "short",
    expected: ["3/4"],
    comparator: "fraction_equal",
    hint: "Cherche le PGCD de 36 et 48.",
    explanation: "PGCD(36, 48) = 12. Donc 36/48 = 3/4.",
    tags: ["simplification", "PGCD"],
  },
  {
    kind: "fixed",
    id: "brevet-frac-006",
    niveau: "3e",
    matiere: "maths",
    notionId: "fractions",
    microId: "comparaison",
    difficulty: 2,
    theme: "brevet",
    text: "Laquelle de ces fractions est la plus grande : 7/9 ou 5/6 ?",
    format: "qcm",
    choices: ["7/9", "5/6"],
    expected: ["5/6"],
    comparator: "mcq_exact",
    hint: "Réduis au même dénominateur : 18.",
    explanation: "7/9 = 14/18 et 5/6 = 15/18. Donc 5/6 > 7/9.",
    tags: ["comparaison"],
  },
  {
    kind: "fixed",
    id: "brevet-frac-007",
    niveau: "3e",
    matiere: "maths",
    notionId: "fractions",
    microId: "expression-mixte",
    difficulty: 3,
    theme: "brevet",
    text: "Calcule et donne le résultat sous forme de fraction irréductible : (2/3 + 1/4) − 5/12",
    format: "short",
    expected: ["1/2", "6/12"],
    comparator: "fraction_equal",
    hint: "Utilise le dénominateur commun 12.",
    explanation: "2/3 = 8/12, 1/4 = 3/12. Donc 8/12 + 3/12 − 5/12 = 6/12 = 1/2.",
    tags: ["addition", "soustraction", "simplification"],
  },
];
