import type { CoachBrevetFixedItem } from "../types";

export const geometrieBank: CoachBrevetFixedItem[] = [
  {
    kind: "fixed",
    id: "brevet-geo-001",
    niveau: "3e",
    matiere: "maths",
    notionId: "pythagore",
    microId: "calcul-hypotenuse",
    difficulty: 1,
    theme: "automatisme",
    text: "Dans un triangle rectangle, les deux côtés de l'angle droit mesurent 3 cm et 4 cm. Quelle est la longueur de l'hypoténuse ?",
    format: "short",
    expected: ["5"],
    comparator: "number_equal",
    hint: "Théorème de Pythagore : c² = a² + b²",
    explanation: "c² = 3² + 4² = 9 + 16 = 25, donc c = 5 cm.",
    tags: ["Pythagore", "hypoténuse"],
  },
  {
    kind: "fixed",
    id: "brevet-geo-002",
    niveau: "3e",
    matiere: "maths",
    notionId: "pythagore",
    microId: "reciproque",
    difficulty: 2,
    theme: "brevet",
    text: "Un triangle a des côtés de longueur 5, 12 et 13. Est-il rectangle ?",
    format: "qcm",
    choices: ["Oui", "Non"],
    expected: ["Oui"],
    comparator: "mcq_exact",
    hint: "Vérifie si c² = a² + b² avec c = 13.",
    explanation: "13² = 169 et 5² + 12² = 25 + 144 = 169. Oui, il est rectangle.",
    tags: ["réciproque Pythagore"],
  },
  {
    kind: "fixed",
    id: "brevet-geo-003",
    niveau: "3e",
    matiere: "maths",
    notionId: "trigonometrie",
    microId: "cosinus",
    difficulty: 2,
    theme: "automatisme",
    text: "Dans un triangle rectangle en A, l'hypoténuse BC = 10 cm et l'angle en B = 30°. Quelle est la longueur AB ? (cos 30° ≈ 0,866)",
    format: "short",
    expected: ["8.66", "8,66"],
    comparator: "number_equal",
    hint: "cos(B) = côté adjacent / hypoténuse = AB / BC",
    explanation: "AB = BC × cos(30°) = 10 × 0,866 = 8,66 cm.",
    tags: ["cosinus", "trigonométrie"],
  },
  {
    kind: "fixed",
    id: "brevet-geo-004",
    niveau: "3e",
    matiere: "maths",
    notionId: "trigonometrie",
    microId: "sinus",
    difficulty: 2,
    theme: "automatisme",
    text: "Dans un triangle rectangle en A, hypoténuse BC = 8 cm et angle B = 45°. Quelle est AC ? (sin 45° ≈ 0,707)",
    format: "short",
    expected: ["5.656", "5.66", "5,66"],
    comparator: "number_equal",
    hint: "sin(B) = côté opposé / hypoténuse = AC / BC",
    explanation: "AC = 8 × sin(45°) = 8 × 0,707 ≈ 5,66 cm.",
    tags: ["sinus", "trigonométrie"],
  },
  {
    kind: "fixed",
    id: "brevet-geo-005",
    niveau: "3e",
    matiere: "maths",
    notionId: "thales",
    microId: "longueur",
    difficulty: 2,
    theme: "brevet",
    text: "Dans un triangle ABC, D est sur AB et E est sur AC avec DE ∥ BC. On sait : AD = 3, DB = 2, DE = 6. Quelle est la longueur BC ?",
    format: "short",
    expected: ["10"],
    comparator: "number_equal",
    hint: "D'après Thalès : AD/AB = DE/BC. AB = AD + DB = 5.",
    explanation: "3/5 = 6/BC → BC = 6 × 5/3 = 10.",
    tags: ["Thalès"],
  },
  {
    kind: "fixed",
    id: "brevet-geo-006",
    niveau: "3e",
    matiere: "maths",
    notionId: "transformations",
    microId: "symetrie-centrale",
    difficulty: 1,
    theme: "automatisme",
    text: "Le symétrique du point A(2 ; 5) par rapport à l'origine O est :",
    format: "qcm",
    choices: ["(−2 ; −5)", "(2 ; −5)", "(−2 ; 5)"],
    expected: ["(−2 ; −5)"],
    comparator: "mcq_exact",
    hint: "Dans une symétrie centrale par rapport à O, le symétrique de (x; y) est (−x; −y).",
    explanation: "Le symétrique de (2; 5) par rapport à O est (−2; −5).",
    tags: ["symétrie centrale"],
  },
  {
    kind: "fixed",
    id: "brevet-geo-007",
    niveau: "3e",
    matiere: "maths",
    notionId: "geometrie_espace",
    microId: "volume-cylindre",
    difficulty: 2,
    theme: "brevet",
    text: "Calcule le volume d'un cylindre de rayon 3 cm et de hauteur 10 cm. (Donne une valeur approchée en cm³, π ≈ 3,14)",
    format: "short",
    expected: ["282.6", "282,6"],
    comparator: "number_equal",
    hint: "V = π × r² × h",
    explanation: "V = 3,14 × 3² × 10 = 3,14 × 9 × 10 = 282,6 cm³.",
    tags: ["volume", "cylindre"],
  },
  {
    kind: "fixed",
    id: "brevet-geo-008",
    niveau: "3e",
    matiere: "maths",
    notionId: "geometrie_espace",
    microId: "volume-cone",
    difficulty: 3,
    theme: "brevet",
    text: "Calcule le volume d'un cône de rayon 4 cm et de hauteur 6 cm. (π ≈ 3,14)",
    format: "short",
    expected: ["100.48", "100,48"],
    comparator: "number_equal",
    hint: "V = (1/3) × π × r² × h",
    explanation: "V = (1/3) × 3,14 × 16 × 6 = (1/3) × 301,44 = 100,48 cm³.",
    tags: ["volume", "cône"],
  },
];
