import type { CoachBrevetFixedItem } from "../types";

export const proportionnaliteBank: CoachBrevetFixedItem[] = [
  {
    kind: "fixed",
    id: "brevet-prop-001",
    niveau: "3e",
    matiere: "maths",
    notionId: "proportionnalite",
    microId: "quatrieme-proportionnelle",
    difficulty: 1,
    theme: "automatisme",
    text: "Si 3 stylos coûtent 4,50 €, combien coûtent 7 stylos ?",
    format: "short",
    expected: ["10.5", "10,5"],
    comparator: "number_equal",
    hint: "Utilise la règle de trois.",
    explanation: "Prix d'un stylo = 4,50 ÷ 3 = 1,50 €. Pour 7 stylos : 7 × 1,50 = 10,50 €.",
    tags: ["règle de trois"],
  },
  {
    kind: "fixed",
    id: "brevet-prop-002",
    niveau: "3e",
    matiere: "maths",
    notionId: "proportionnalite",
    microId: "coefficient",
    difficulty: 1,
    theme: "automatisme",
    text: "Un tableau est-il proportionnel si les valeurs sont : x = 2, 5, 8 et y = 6, 15, 24 ?",
    format: "qcm",
    choices: ["Oui, coefficient 3", "Non"],
    expected: ["Oui, coefficient 3"],
    comparator: "mcq_exact",
    hint: "Calcule y/x pour chaque colonne.",
    explanation: "6/2 = 3, 15/5 = 3, 24/8 = 3. Coefficient de proportionnalité = 3.",
    tags: ["tableau", "coefficient"],
  },
  {
    kind: "fixed",
    id: "brevet-prop-003",
    niveau: "3e",
    matiere: "maths",
    notionId: "proportionnalite",
    microId: "echelle",
    difficulty: 2,
    theme: "brevet",
    text: "Sur une carte à l'échelle 1/50 000, deux villes sont distantes de 4 cm. Quelle est la distance réelle en km ?",
    format: "short",
    expected: ["2", "2 km"],
    comparator: "number_equal",
    hint: "Distance réelle = distance carte × 50 000. Convertis en km.",
    explanation: "4 × 50 000 = 200 000 cm = 2 000 m = 2 km.",
    tags: ["échelle", "conversion"],
  },
  {
    kind: "fixed",
    id: "brevet-prop-004",
    niveau: "3e",
    matiere: "maths",
    notionId: "pourcentages",
    microId: "pourcentage-valeur",
    difficulty: 1,
    theme: "automatisme",
    text: "Calcule 15 % de 80.",
    format: "short",
    expected: ["12"],
    comparator: "number_equal",
    hint: "Multiplie 80 par 0,15.",
    explanation: "80 × 0,15 = 12",
    tags: ["pourcentage"],
  },
  {
    kind: "fixed",
    id: "brevet-prop-005",
    niveau: "3e",
    matiere: "maths",
    notionId: "pourcentages",
    microId: "augmentation",
    difficulty: 2,
    theme: "brevet",
    text: "Un article coûtait 60 €. Son prix a augmenté de 20 %. Quel est le nouveau prix ?",
    format: "short",
    expected: ["72"],
    comparator: "number_equal",
    hint: "Multiplie par 1,20.",
    explanation: "60 × 1,20 = 72 €.",
    tags: ["augmentation", "coefficient multiplicateur"],
  },
  {
    kind: "fixed",
    id: "brevet-prop-006",
    niveau: "3e",
    matiere: "maths",
    notionId: "pourcentages",
    microId: "reduction",
    difficulty: 2,
    theme: "brevet",
    text: "Un vêtement affiché 90 € est soldé à − 30 %. Quel est son prix soldé ?",
    format: "short",
    expected: ["63"],
    comparator: "number_equal",
    hint: "Multiplie par (1 − 0,30) = 0,70.",
    explanation: "90 × 0,70 = 63 €.",
    tags: ["réduction", "soldes"],
  },
  {
    kind: "fixed",
    id: "brevet-prop-007",
    niveau: "3e",
    matiere: "maths",
    notionId: "pourcentages",
    microId: "taux-evolution",
    difficulty: 3,
    theme: "brevet",
    text: "Un produit passe de 40 € à 50 €. Quel est le taux d'augmentation en % ?",
    format: "short",
    expected: ["25"],
    comparator: "number_equal",
    hint: "Taux = (nouvelle valeur − ancienne valeur) / ancienne valeur × 100.",
    explanation: "(50 − 40) / 40 × 100 = 10/40 × 100 = 25 %.",
    tags: ["taux d'évolution"],
  },
];
