import type { CoachBrevetFixedItem } from "../types";

export const puissancesBank: CoachBrevetFixedItem[] = [
  {
    kind: "fixed",
    id: "brevet-puis-001",
    niveau: "3e",
    matiere: "maths",
    notionId: "puissances",
    microId: "definition",
    difficulty: 1,
    theme: "automatisme",
    text: "Calcule 2⁵.",
    format: "short",
    expected: ["32"],
    comparator: "number_equal",
    hint: "2⁵ = 2 × 2 × 2 × 2 × 2",
    explanation: "2⁵ = 32",
    tags: ["calcul"],
  },
  {
    kind: "fixed",
    id: "brevet-puis-002",
    niveau: "3e",
    matiere: "maths",
    notionId: "puissances",
    microId: "puissance-negative",
    difficulty: 2,
    theme: "automatisme",
    text: "Calcule 10⁻³.",
    format: "short",
    expected: ["0.001", "1/1000"],
    comparator: "number_equal",
    hint: "a⁻ⁿ = 1/aⁿ",
    explanation: "10⁻³ = 1/10³ = 1/1000 = 0,001",
    tags: ["puissance negative"],
  },
  {
    kind: "fixed",
    id: "brevet-puis-003",
    niveau: "3e",
    matiere: "maths",
    notionId: "puissances",
    microId: "produit",
    difficulty: 2,
    theme: "automatisme",
    text: "Simplifie : 3⁴ × 3² (écris sous la forme 3ⁿ).",
    format: "short",
    expected: ["3^6", "729"],
    comparator: "exact",
    hint: "aᵐ × aⁿ = aᵐ⁺ⁿ",
    explanation: "3⁴ × 3² = 3⁴⁺² = 3⁶ = 729",
    tags: ["produit"],
  },
  {
    kind: "fixed",
    id: "brevet-puis-004",
    niveau: "3e",
    matiere: "maths",
    notionId: "puissances",
    microId: "quotient",
    difficulty: 2,
    theme: "automatisme",
    text: "Simplifie : 5⁷ ÷ 5³ (écris sous la forme 5ⁿ).",
    format: "short",
    expected: ["5^4", "625"],
    comparator: "exact",
    hint: "aᵐ ÷ aⁿ = aᵐ⁻ⁿ",
    explanation: "5⁷ ÷ 5³ = 5⁷⁻³ = 5⁴ = 625",
    tags: ["quotient"],
  },
  {
    kind: "fixed",
    id: "brevet-puis-005",
    niveau: "3e",
    matiere: "maths",
    notionId: "puissances",
    microId: "piege-zero",
    difficulty: 1,
    theme: "piege",
    text: "Que vaut 7⁰ ?",
    format: "qcm",
    choices: ["0", "1", "7"],
    expected: ["1"],
    comparator: "mcq_exact",
    hint: "Tout nombre non nul élevé à la puissance 0 vaut 1.",
    explanation: "Par définition, a⁰ = 1 pour tout a ≠ 0. Donc 7⁰ = 1.",
    tags: ["piege", "puissance zero"],
  },
  {
    kind: "fixed",
    id: "brevet-puis-006",
    niveau: "3e",
    matiere: "maths",
    notionId: "puissances",
    microId: "notation-scientifique",
    difficulty: 3,
    theme: "brevet",
    text: "Écris 0,00045 en notation scientifique.",
    format: "short",
    expected: ["4.5×10^-4", "4,5×10⁻⁴"],
    comparator: "exact",
    hint: "Déplace la virgule pour obtenir un nombre entre 1 et 10.",
    explanation: "0,00045 = 4,5 × 10⁻⁴",
    tags: ["notation scientifique"],
  },
  {
    kind: "fixed",
    id: "brevet-puis-007",
    niveau: "3e",
    matiere: "maths",
    notionId: "puissances",
    microId: "piege-addition",
    difficulty: 2,
    theme: "piege",
    text: "Un élève écrit 2³ + 2³ = 2⁶. Est-ce correct ?",
    format: "qcm",
    choices: ["Oui", "Non, 2³ + 2³ = 2 × 2³ = 2⁴"],
    expected: ["Non, 2³ + 2³ = 2 × 2³ = 2⁴"],
    comparator: "mcq_exact",
    hint: "La règle aᵐ × aⁿ = aᵐ⁺ⁿ s'applique pour une multiplication, pas une addition.",
    explanation: "2³ + 2³ = 8 + 8 = 16 = 2⁴. On ne peut pas additionner les exposants.",
    tags: ["piege", "addition"],
  },
];
