import type { CoachBrevetFixedItem } from "../types";

export const statistiquesProbabilitesBank: CoachBrevetFixedItem[] = [
  {
    kind: "fixed",
    id: "brevet-stat-001",
    niveau: "3e",
    matiere: "maths",
    notionId: "statistiques",
    microId: "moyenne",
    difficulty: 1,
    theme: "automatisme",
    text: "Calcule la moyenne des notes suivantes : 8, 12, 14, 10, 16.",
    format: "short",
    expected: ["12"],
    comparator: "number_equal",
    hint: "Somme ÷ nombre de valeurs.",
    explanation: "(8+12+14+10+16) ÷ 5 = 60 ÷ 5 = 12.",
    tags: ["moyenne"],
  },
  {
    kind: "fixed",
    id: "brevet-stat-002",
    niveau: "3e",
    matiere: "maths",
    notionId: "statistiques",
    microId: "mediane",
    difficulty: 2,
    theme: "automatisme",
    text: "Quelle est la médiane de la série : 3, 7, 9, 11, 15 ?",
    format: "short",
    expected: ["9"],
    comparator: "number_equal",
    hint: "La médiane est la valeur centrale (série déjà triée).",
    explanation: "5 valeurs triées : la médiane est la 3e valeur = 9.",
    tags: ["médiane"],
  },
  {
    kind: "fixed",
    id: "brevet-stat-003",
    niveau: "3e",
    matiere: "maths",
    notionId: "statistiques",
    microId: "etendue",
    difficulty: 1,
    theme: "automatisme",
    text: "Quelle est l'étendue de la série : 4, 9, 2, 16, 7 ?",
    format: "short",
    expected: ["14"],
    comparator: "number_equal",
    hint: "Étendue = valeur max − valeur min.",
    explanation: "16 − 2 = 14.",
    tags: ["étendue"],
  },
  {
    kind: "fixed",
    id: "brevet-stat-004",
    niveau: "3e",
    matiere: "maths",
    notionId: "statistiques",
    microId: "moyenne-ponderee",
    difficulty: 2,
    theme: "brevet",
    text: "Un élève a eu : 10 (coeff. 2), 14 (coeff. 3), 8 (coeff. 1). Quelle est sa moyenne pondérée ?",
    format: "short",
    expected: ["12"],
    comparator: "number_equal",
    hint: "Moyenne = (somme des produits note×coeff) ÷ (somme des coefficients).",
    explanation: "(10×2 + 14×3 + 8×1) ÷ (2+3+1) = (20+42+8) ÷ 6 = 70 ÷ 6 ≈ 11,67. Attention : résultat exact = 70/6.",
    tags: ["moyenne pondérée"],
  },
  {
    kind: "fixed",
    id: "brevet-stat-005",
    niveau: "3e",
    matiere: "maths",
    notionId: "probabilites",
    microId: "frequence",
    difficulty: 1,
    theme: "automatisme",
    text: "On lance un dé à 6 faces. Quelle est la probabilité d'obtenir un nombre pair ?",
    format: "short",
    expected: ["1/2", "0.5", "3/6"],
    comparator: "fraction_equal",
    hint: "Les nombres pairs sur un dé sont 2, 4, 6.",
    explanation: "Il y a 3 résultats favorables (2, 4, 6) sur 6 possibles. P = 3/6 = 1/2.",
    tags: ["probabilité", "dé"],
  },
  {
    kind: "fixed",
    id: "brevet-stat-006",
    niveau: "3e",
    matiere: "maths",
    notionId: "probabilites",
    microId: "arbre",
    difficulty: 2,
    theme: "brevet",
    text: "Un sac contient 3 boules rouges et 2 bleues. On tire successivement 2 boules SANS remise. Quelle est la probabilité d'obtenir 2 rouges ?",
    format: "short",
    expected: ["3/10", "0.3"],
    comparator: "fraction_equal",
    hint: "P(R₁) = 3/5. Sachant R₁, P(R₂) = 2/4.",
    explanation: "P(2 rouges) = (3/5) × (2/4) = 6/20 = 3/10.",
    tags: ["probabilité", "sans remise", "arbre"],
  },
  {
    kind: "fixed",
    id: "brevet-stat-007",
    niveau: "3e",
    matiere: "maths",
    notionId: "probabilites",
    microId: "complementaire",
    difficulty: 2,
    theme: "automatisme",
    text: "La probabilité qu'il pleuve demain est 0,35. Quelle est la probabilité qu'il ne pleuve pas ?",
    format: "short",
    expected: ["0.65"],
    comparator: "number_equal",
    hint: "P(contraire) = 1 − P(événement).",
    explanation: "1 − 0,35 = 0,65.",
    tags: ["probabilité", "complémentaire"],
  },
];
