// 4ᵉ · français — enrichissement des pools d'ÉTUDE DE LA LANGUE.
//
// MÊME CHANTIER QU'EN 5ᵉ, MÊME MESURE. Le builder du cycle 4 produit 7 énoncés
// distincts par micro-compétence quand celui du cycle 3 en produit 32
// (npx --yes tsx@4 scripts/auditer-banque-runtime.ts 4e --variete). Son propre
// en-tête vise « 12-20 par micro » : la cible n'était pas atteinte, et rien ne
// le signalait puisque la couverture affichait 100 %.
//
// LA RÈGLE D'ÉCRITURE, tirée du cahier officiel : jamais de définition à
// réciter. On donne l'énoncé, on demande ce que la forme FAIT. Aucun item de
// ce fichier ne commence par « Un(e) X est… ».
//
// CHAQUE ÉNONCÉ EST DISTINCT — y compris de ceux de la 5ᵉ. Le tirage des
// épreuves blanches déduplique sur le texte de la question : six items qui
// partageraient l'intitulé « Quelle orthographe convient ? » se réduiraient à
// un seul tirable. Le mot est donc toujours replacé dans une phrase.
//
// LES EXEMPLES SONT PRIS DANS LES ENTRÉES DE 4ᵉ — le fantastique, la lettre et
// l'amour, la presse et l'information — plutôt que dans des phrases neutres :
// un élève reconnaît alors le terrain de ses lectures de l'année.
//
// QCM uniquement, comme tout le cycle 4 : le comparateur exact_text
// sanctionnerait des accents qu'on n'a pas demandés.

import type { TutorBankItemFixedV4 } from "@/lib/tutor-v4/types";

function qcm(
  n: number,
  microId: string,
  notionId: string,
  difficulty: 1 | 2 | 3,
  text: string,
  choices: string[],
  correct: string,
  explanation: string,
): TutorBankItemFixedV4 {
  return {
    kind: "fixed",
    id: `4e_fr_compl_${microId}_${n}`,
    niveau: "4e",
    matiere: "francais",
    notionId,
    microId,
    difficulty,
    theme: "neutral",
    text,
    format: "qcm",
    choices,
    expected: [correct],
    comparator: "mcq_exact",
    explanation,
    tags: ["4e", "francais", notionId, microId, "qcm"],
  };
}

const V = (n: number, m: string, d: 1 | 2 | 3, t: string, c: string[], r: string, e: string) =>
  qcm(n, m, "vocabulaire", d, t, c, r, e);
const G = (n: number, m: string, d: 1 | 2 | 3, t: string, c: string[], r: string, e: string) =>
  qcm(n, m, "grammaire_phrase", d, t, c, r, e);
const C = (n: number, m: string, d: 1 | 2 | 3, t: string, c: string[], r: string, e: string) =>
  qcm(n, m, "conjugaison", d, t, c, r, e);
const D = (n: number, m: string, d: 1 | 2 | 3, t: string, c: string[], r: string, e: string) =>
  qcm(n, m, "analyse_discours", d, t, c, r, e);

export const complementsEtudeLangue4eBank: TutorBankItemFixedV4[] = [
  // ══════════════════════════════════════════════════════════════════════
  // VOCABULAIRE · inférer le sens par le contexte
  // ══════════════════════════════════════════════════════════════════════
  V(1, "4e_voc_contexte", 1,
    "« La maison paraissait vétuste : les volets pendaient, le crépi s'effritait. » Que veut dire « vétuste » ?",
    ["vieille et dégradée", "immense", "récemment repeinte", "inhabitée"],
    "vieille et dégradée",
    "Les deux détails qui suivent les deux points servent de définition : des volets qui pendent, un crépi qui tombe. Quand un texte fait suivre un mot rare de sa description, il vous tend la réponse."),
  V(2, "4e_voc_contexte", 2,
    "« Une clarté blafarde tombait de la lune sur le jardin. » Que veut dire « blafarde » ?",
    ["pâle et sans éclat", "une clarté très vive", "colorée et chaude", "changeante et mouvante"],
    "pâle et sans éclat",
    "Une clarté qui vient de la lune ne peut pas éblouir : le contexte élimine « très vive » avant même qu'on connaisse le mot. Le fantastique aime cette lumière-là, qui montre sans rien éclairer."),
  V(3, "4e_voc_contexte", 2,
    "« Il s'obstinait à nier, malgré les preuves posées devant lui. » Que veut dire « s'obstinait » ?",
    ["persistait avec entêtement", "hésitait à répondre", "avouait peu à peu la vérité", "se taisait complètement"],
    "persistait avec entêtement",
    "« Malgré les preuves » est la clé : le mot doit dire une résistance à ce qui devrait faire céder. Un homme qui hésite ou qui avoue ne rendrait pas ce « malgré » nécessaire."),
  V(4, "4e_voc_contexte", 2,
    "« Le journaliste relata les faits sans jamais les commenter. » Que veut dire « relata » ?",
    ["rapporta", "inventa", "critiqua", "démentit"],
    "rapporta",
    "La fin de la phrase oppose deux gestes : dire ce qui s'est passé, et donner son avis. Puisque le second est écarté, le verbe ne peut désigner que le premier."),
  V(5, "4e_voc_contexte", 3,
    "« Il parlait d'une voix monocorde que rien ne venait relever. » Que veut dire « monocorde » ?",
    ["toujours sur le même ton", "très forte", "cassée par l'émotion", "à peine audible"],
    "toujours sur le même ton",
    "« Que rien ne venait relever » indique l'absence de variation, pas l'absence de volume. Le mot lui-même contient « mono » — une seule corde, donc une seule note."),
  V(6, "4e_voc_contexte", 3,
    "« L'orage imminent noircissait déjà l'horizon. » Que veut dire « imminent » ?",
    ["sur le point d'arriver", "déjà très lointain", "déjà terminé depuis peu", "assez peu probable"],
    "sur le point d'arriver",
    "L'adverbe « déjà » fait tout le travail : quelque chose commence à se voir alors que l'orage n'a pas éclaté. Un orage lointain ou passé ne noircirait pas l'horizon maintenant."),

  // ── VOCABULAIRE · relations entre les mots ────────────────────────────
  V(1, "4e_voc_relations", 1,
    "Dans « un raisonnement obscur », quel mot serait le contraire d'« obscur » ?",
    ["limpide", "compliqué", "long", "savant"],
    "limpide",
    "« Obscur » dit ici ce qu'on ne parvient pas à suivre. Son contraire doit parler de clarté, pas de longueur : « limpide » se dit d'une eau qu'on voit au travers, et d'une idée aussi."),
  V(2, "4e_voc_relations", 1,
    "Dans « un silence pesant s'installa », quel mot pourrait remplacer « pesant » ?",
    ["oppressant", "reposant", "bref", "poli"],
    "oppressant",
    "Deux synonymes doivent tenir dans la même phrase sans en changer l'atmosphère. « Reposant » dirait exactement le contraire de ce que le texte installe."),
  V(3, "4e_voc_relations", 2,
    "Quel mot n'appartient PAS au champ lexical de la peur ?",
    ["quiétude", "effroi", "angoisse", "épouvante"],
    "quiétude",
    "Effroi, angoisse et épouvante nomment des degrés de la même émotion. « Quiétude » nomme le calme : c'est le mot du camp d'en face, et c'est ce qui le rend repérable."),
  V(4, "4e_voc_relations", 2,
    "Quel mot n'est PAS de la même famille que les autres ?",
    ["voyant", "voyage", "voyageur", "voyagiste"],
    "voyant",
    "Voyage, voyageur et voyagiste se construisent tous sur « voyage ». « Voyant » vient de « voir » : les lettres se ressemblent, le sens ne suit pas."),
  V(5, "4e_voc_relations", 3,
    "« Une contrariété » et « un chagrin » : qu'est-ce qui les distingue ?",
    [
      "l'intensité : le chagrin est plus profond",
      "rien du tout, ce sont deux synonymes exacts",
      "le registre : « chagrin » est plus familier",
      "le nombre : l'un est toujours au pluriel",
    ],
    "l'intensité : le chagrin est plus profond",
    "Deux mots voisins ne sont presque jamais interchangeables. Une contrariété s'oublie dans la journée ; un chagrin, non. Choisir entre eux, c'est déjà écrire."),
  V(6, "4e_voc_relations", 3,
    "Quel couple ci-dessous n'est PAS un couple de contraires ?",
    ["redouter / craindre", "éclaircir / obscurcir", "apparaître / disparaître", "avancer / reculer"],
    "redouter / craindre",
    "Les trois autres couples s'opposent terme à terme. « Redouter » et « craindre » disent la même chose avec une nuance d'intensité : ce sont des synonymes, pas des antonymes."),

  // ── VOCABULAIRE · formation des mots ──────────────────────────────────
  V(1, "4e_voc_formation", 1,
    "« Chronomètre », « chronologie », « chronique » : que désigne l'élément « chrono- » ?",
    ["le temps", "la mesure", "l'écriture", "la vitesse"],
    "le temps",
    "Un chronomètre mesure le temps, une chronologie le met en ordre, une chronique le suit au fil des jours. Reconnaître une racine grecque, c'est ouvrir d'un coup toute une famille de mots."),
  V(2, "4e_voc_formation", 1,
    "Dans « microscope », que veut dire l'élément « micro- » ?",
    ["petit", "lointain", "rond", "lumineux"],
    "petit",
    "L'appareil sert à regarder ce qui est trop petit pour l'œil. On retrouve la même racine dans « microbe » et « microphone » — à chaque fois, il s'agit de très peu de chose."),
  V(3, "4e_voc_formation", 2,
    "Quel préfixe faut-il placer devant « mortel » pour en dire le contraire ?",
    ["im-", "dé-", "mal-", "re-"],
    "im-",
    "« Immortel » : le préfixe im- nie l'adjectif, comme dans « impossible » ou « imprudent ». Il prend cette forme devant un m, un b ou un p — ailleurs, il s'écrit in-."),
  V(4, "4e_voc_formation", 2,
    "« Bibliothèque » et « bibliophile » ont un élément commun : que désigne-t-il ?",
    ["le livre", "le savoir", "le silence", "la lecture à voix haute"],
    "le livre",
    "Une bibliothèque range les livres, un bibliophile les aime. Le second élément, lui, change tout : -thèque dit le rangement, -phile dit l'amour."),
  V(5, "4e_voc_formation", 3,
    "« Décoloré », « défaire », « déplier » : que marque le préfixe dé- ?",
    ["l'action inverse", "la répétition", "l'excès", "la petite quantité"],
    "l'action inverse",
    "À chaque fois, le préfixe défait ce que le verbe faisait. C'est le même mouvement dans « déboutonner » ou « démonter » : on revient en arrière."),
  V(6, "4e_voc_formation", 3,
    "Dans « la sonnerie retentit », quel mot appartient à la même famille que « sonnerie » ?",
    ["résonner", "songer", "sonder", "soigner"],
    "résonner",
    "« Sonnerie », « sonner », « résonner » se construisent tous sur le son. Les trois autres n'ont en commun que le début du mot, ce qui ne prouve rien : la parenté est de sens, pas de lettres."),

  // ── VOCABULAIRE · réemployer un lexique précis ────────────────────────
  V(1, "4e_voc_reemploi", 1,
    "Pour dire qu'une peur monte lentement et ne repart pas, quel verbe est le plus juste : « la peur … » ?",
    ["s'installait", "arrivait", "était là", "venait"],
    "s'installait",
    "Le verbe doit contenir à la fois la lenteur et la durée. « S'installer », c'est prendre place pour rester — les trois autres disent seulement que la peur est là."),
  V(2, "4e_voc_reemploi", 2,
    "Dans un article, quel mot indique qu'une information n'est pas encore confirmée ?",
    ["présumé", "avéré", "certain", "prouvé"],
    "présumé",
    "Les trois autres affirment. « Présumé » réserve le jugement — c'est le mot qui permet d'informer sans accuser, et il engage la responsabilité du journal."),
  V(3, "4e_voc_reemploi", 2,
    "Quel verbe dit le mieux qu'il parle avec difficulté, en cherchant ses mots ?",
    ["bredouiller", "clamer", "déclamer", "réciter"],
    "bredouiller",
    "Clamer et déclamer supposent au contraire de l'assurance et du volume. Choisir le verbe exact évite l'adverbe : « il bredouilla » dit ce que « il parla difficilement » met deux mots à dire."),
  V(4, "4e_voc_reemploi", 2,
    "« Le vent … les volets. » Quel verbe rend le mieux la violence du geste ?",
    ["arrachait", "effleurait", "touchait", "caressait"],
    "arrachait",
    "Le verbe porte à lui seul l'intensité de la scène. C'est la règle du récit : on ne dit pas que le vent était fort, on montre ce qu'il fait."),
  V(5, "4e_voc_reemploi", 3,
    "Quel mot désigne une joie éclatante, partagée par tous ?",
    ["l'allégresse", "la satisfaction", "le contentement", "l'agrément"],
    "l'allégresse",
    "Satisfaction et contentement disent une joie tranquille et personnelle. L'allégresse est bruyante et collective : c'est le mot des fêtes et des retours."),
  V(6, "4e_voc_reemploi", 3,
    "Pour décrire un décor qui donne le sentiment d'une menace, quel adjectif convient ?",
    ["inquiétant", "anodin", "plaisant", "banal"],
    "inquiétant",
    "« Anodin » et « banal » disent justement qu'il n'y a rien à craindre. Dans un récit fantastique, l'adjectif fait basculer un lieu ordinaire — c'est souvent lui qui prépare la suite."),

  // ── VOCABULAIRE · orthographe des mots étudiés ────────────────────────
  V(1, "4e_voc_orthographe", 1,
    "« Il a agi par pure … . » Comment s'écrit le mot ?",
    ["négligence", "négligeance", "néglijence", "négligense"],
    "négligence",
    "Le g garde son son doux devant le e : pas besoin du a de « geance ». On retrouve la même finale dans « exigence » et « urgence »."),
  V(2, "4e_voc_orthographe", 2,
    "« Sa décision était … . » Quelle est la bonne orthographe de l'adjectif ?",
    ["irrévocable", "irévocable", "irrévoquable", "irrevocable"],
    "irrévocable",
    "Deux r, parce que le préfixe ir- vient se coller au radical « révocable ». Et un c, comme dans « révoquer » qui donne pourtant un q : la famille ne garantit pas la lettre."),
  V(3, "4e_voc_orthographe", 2,
    "« Il a répondu … qu'il ignorait tout. » Quel est l'adverbe formé sur « évident » ?",
    ["évidemment", "évidament", "évidenment", "évidement"],
    "évidemment",
    "Les adjectifs en -ent donnent des adverbes en -emment, qui se prononcent « amment ». C'est l'oreille qui trompe ici, pas la règle."),
  V(4, "4e_voc_orthographe", 2,
    "« Elle parle … l'espagnol. » Quel est l'adverbe formé sur « courant » ?",
    ["couramment", "courament", "couremment", "courramment"],
    "couramment",
    "Les adjectifs en -ant donnent des adverbes en -amment. Un seul r, deux m : le mot double la consonne du suffixe, pas celle du radical."),
  V(5, "4e_voc_orthographe", 3,
    "« Il se trouvait devant un véritable … . » Quel mot est correctement orthographié ?",
    ["dilemme", "dilemne", "dillemme", "dilême"],
    "dilemme",
    "Un seul l, deux m. Le mot vient du grec et désigne un choix entre deux solutions également difficiles — d'où les deux m, comme les deux branches."),
  V(6, "4e_voc_orthographe", 3,
    "« La … des sources est le premier réflexe du journaliste. » Comment s'écrit ce mot ?",
    ["vérification", "vérifiquation", "verification", "vérificasion"],
    "vérification",
    "Le c de « vérifier » se maintient devant le suffixe -ation, et l'accent aigu reste sur le premier e. La finale -tion s'écrit toujours ainsi après un i."),

  // ══════════════════════════════════════════════════════════════════════
  // GRAMMAIRE · les constituants de la phrase
  // ══════════════════════════════════════════════════════════════════════
  G(1, "4e_gram_constituants", 1,
    "« Depuis la veille, le vent soufflait sans relâche. » Quel groupe peut-on supprimer sans rendre la phrase incorrecte ?",
    ["Depuis la veille", "le vent", "soufflait", "le vent soufflait"],
    "Depuis la veille",
    "Un complément circonstanciel se supprime et se déplace ; le sujet et le verbe, non. C'est ce test-là — supprimer, déplacer — qui identifie un constituant, bien mieux qu'une définition."),
  G(2, "4e_gram_constituants", 2,
    "« Le vieux phare que nous apercevions au loin clignotait faiblement. » Quelle est la proposition subordonnée ?",
    [
      "que nous apercevions au loin",
      "le vieux phare du port",
      "clignotait très faiblement",
      "au loin clignotait encore",
    ],
    "que nous apercevions au loin",
    "Elle commence par un pronom relatif et contient son propre verbe conjugué. Elle est enchâssée dans le groupe nominal sujet, ce qui la rend facile à manquer : on peut la retirer, la phrase tient encore."),
  G(3, "4e_gram_constituants", 2,
    "« Il partit dès que la pluie cessa. » Combien cette phrase contient-elle de propositions ?",
    ["deux", "une", "trois", "aucune, c'est une phrase simple"],
    "deux",
    "On compte les verbes conjugués : « partit » et « cessa ». Deux verbes conjugués, deux propositions — c'est le repère le plus sûr pour distinguer phrase simple et phrase complexe."),
  G(4, "4e_gram_constituants", 2,
    "« Les volets claquaient, la porte grinçait, personne ne dormait. » Comment les propositions sont-elles reliées ?",
    [
      "elles sont juxtaposées, par des virgules",
      "elles sont coordonnées par une conjonction",
      "elles sont subordonnées à la première d'entre elles",
      "elles forment une seule et même proposition",
    ],
    "elles sont juxtaposées, par des virgules",
    "Aucun mot de liaison : c'est la ponctuation seule qui relie. La juxtaposition produit ici un effet d'accumulation, comme si les bruits arrivaient les uns sur les autres."),
  G(5, "4e_gram_constituants", 3,
    "Dans « J'ignore pourquoi il est parti », que complète le groupe « pourquoi il est parti » ?",
    [
      "le verbe « ignore » : c'est son complément d'objet",
      "le sujet « je » de la proposition principale",
      "rien : c'est un complément circonstanciel de cause",
      "le nom « parti », qui est placé juste avant",
    ],
    "le verbe « ignore » : c'est son complément d'objet",
    "On ignore quelque chose : la proposition occupe la place que tiendrait un groupe nominal. Remplacez-la par « la raison » et la phrase reste correcte — la fonction apparaît alors clairement."),
  G(6, "4e_gram_constituants", 3,
    "« Quand le jour se leva, la maison avait disparu. » Quel rôle joue « Quand le jour se leva » ?",
    [
      "il indique le moment : c'est un complément circonstanciel de temps",
      "il indique la cause : c'est un complément circonstanciel de cause",
      "il est le sujet du verbe « avait disparu » de la principale",
      "il complète le nom « maison » : c'est un complément du nom",
    ],
    "il indique le moment : c'est un complément circonstanciel de temps",
    "La subordonnée répond à la question « quand ? » et se déplace en fin de phrase sans dommage. Sa place en tête, ici, sert le récit : on installe l'heure avant de découvrir l'impossible."),

  // ── GRAMMAIRE · fonctions ─────────────────────────────────────────────
  G(1, "4e_gram_fonctions", 1,
    "« Le journaliste a vérifié ses sources. » Quelle est la fonction de « ses sources » ?",
    ["complément d'objet direct", "sujet", "complément circonstanciel", "attribut du sujet"],
    "complément d'objet direct",
    "Il a vérifié quoi ? Ses sources. Le groupe suit le verbe sans préposition et ne se déplace pas : ce sont les deux marques du complément d'objet direct."),
  G(2, "4e_gram_fonctions", 2,
    "« Elle écrivit à son frère une longue lettre. » Quelle est la fonction de « à son frère » ?",
    ["complément d'objet indirect", "complément d'objet direct", "complément du nom", "attribut"],
    "complément d'objet indirect",
    "La préposition « à » signale l'indirect. Le complément direct, lui, est « une longue lettre » : une même phrase peut porter les deux, et l'ordre des mots n'y change rien."),
  G(3, "4e_gram_fonctions", 2,
    "« La rumeur, ce matin-là, parut invraisemblable. » Quelle est la fonction d'« invraisemblable » ?",
    ["attribut du sujet", "complément d'objet direct", "épithète du nom « rumeur »", "complément circonstanciel"],
    "attribut du sujet",
    "« Paraître » est un verbe d'état : il ne reçoit pas d'objet, il attribue une qualité au sujet. Une épithète, elle, serait collée au nom — « une rumeur invraisemblable »."),
  G(4, "4e_gram_fonctions", 2,
    "« Dans le grenier, une malle attendait depuis vingt ans. » Quel est le sujet de « attendait » ?",
    ["une malle", "le grenier", "vingt ans", "dans le grenier"],
    "une malle",
    "Posez la question « qui est-ce qui attendait ? ». Le complément placé en tête n'est là que pour planter le décor : sa position ne lui donne aucun droit sur le verbe."),
  G(5, "4e_gram_fonctions", 3,
    "« Ce vieux manoir abandonné effrayait les enfants du village. » Quel mot est le noyau du groupe sujet ?",
    ["manoir", "vieux", "abandonné", "ce"],
    "manoir",
    "Le noyau est le nom autour duquel tout s'organise : ôtez les autres mots, « le manoir effrayait les enfants » tient debout. Ôtez le nom, il ne reste rien."),
  G(6, "4e_gram_fonctions", 3,
    "« Il semblait épuisé. » Pourquoi « épuisé » n'est-il pas un complément d'objet ?",
    [
      "parce que « sembler » est un verbe d'état : il qualifie le sujet",
      "parce qu'« épuisé » est un participe passé : il reste un verbe",
      "parce que la phrase est trop courte pour avoir un complément",
      "parce qu'il n'y a pas de préposition devant le mot « épuisé »",
    ],
    "parce que « sembler » est un verbe d'état : il qualifie le sujet",
    "Un verbe d'état ne subit aucune action : il relie. Le test le montre — on ne peut pas demander « il semblait quoi ? » comme on demanderait « il portait quoi ? »."),

  // ── GRAMMAIRE · accords ───────────────────────────────────────────────
  G(1, "4e_gram_accords", 1,
    "« Ils sont … à l'aube, sans prévenir personne. » Quelle forme convient ?",
    ["partis", "parti", "partie", "parties"],
    "partis",
    "Avec l'auxiliaire être, le participe passé s'accorde avec le sujet. « Ils » est masculin pluriel : le participe suit, comme le ferait un adjectif."),
  G(2, "4e_gram_accords", 2,
    "« Les lettres qu'il a … n'ont jamais été envoyées. » Quelle forme convient ?",
    ["écrites", "écrit", "écrits", "écrite"],
    "écrites",
    "Avec avoir, le participe s'accorde seulement si le complément d'objet direct le précède. Ici « qu' » remplace « les lettres » et se trouve avant le verbe : l'accord se fait au féminin pluriel."),
  G(3, "4e_gram_accords", 2,
    "« Une odeur et un bruit … montaient de la cave. » Quelle forme de l'adjectif convient ?",
    ["étranges", "étrange", "étrangement", "étranger"],
    "étranges",
    "L'adjectif qualifie les deux noms à la fois : il passe donc au pluriel. Un nom masculin et un nom féminin réunis imposent le masculin pluriel, qui l'emporte à l'écrit."),
  G(4, "4e_gram_accords", 2,
    "« La plupart des habitants … quitté le village. » Quelle forme convient ?",
    ["ont", "a", "avait", "ait"],
    "ont",
    "Après « la plupart des », le verbe s'accorde avec le complément au pluriel, pas avec le mot « plupart ». C'est le sens qui commande : ce sont bien les habitants qui partent."),
  G(5, "4e_gram_accords", 3,
    "« Chacun des élèves … rendu sa copie. » Quelle forme convient ?",
    ["a", "ont", "avaient", "aient"],
    "a",
    "Le sujet est « chacun », qui est singulier ; « des élèves » n'est qu'un complément. Le pluriel qui suit attire l'oreille — c'est précisément le piège que l'exercice teste."),
  G(6, "4e_gram_accords", 3,
    "« Les fenêtres, que le vent avait … , battaient dans la nuit. » Quelle forme convient ?",
    ["ouvertes", "ouvert", "ouverts", "ouverte"],
    "ouvertes",
    "Le pronom relatif « que » reprend « les fenêtres » et se place avant l'auxiliaire avoir : l'accord se fait donc, au féminin pluriel. Sans ce déplacement, on écrirait « le vent avait ouvert les fenêtres »."),

  // ── GRAMMAIRE · usages de l'oral et de l'écrit ────────────────────────
  G(1, "4e_gram_oral_ecrit", 1,
    "« T'as vu l'heure ? » Comment cette question s'écrit-elle dans un texte soigné ?",
    ["As-tu vu l'heure ?", "T'as vu l'heure ?", "Tu as vu l'heure ?", "T'as-tu vu l'heure ?"],
    "As-tu vu l'heure ?",
    "L'écrit soigné rétablit le pronom entier et inverse le sujet pour interroger. « Tu as vu l'heure ? » se comprend, mais garde la forme orale : seule l'intonation y marque la question."),
  G(2, "4e_gram_oral_ecrit", 1,
    "« Je sais pas. » Que manque-t-il à cette phrase à l'écrit ?",
    [
      "la première partie de la négation, « ne »",
      "un point d'exclamation en fin de phrase",
      "le complément qui suit le verbe",
      "une majuscule au premier mot",
    ],
    "la première partie de la négation, « ne »",
    "La négation française tient en deux mots. L'oral en laisse tomber un ; l'écrit le rétablit toujours — c'est la faute la plus fréquente au collège, et la plus facile à corriger."),
  G(3, "4e_gram_oral_ecrit", 2,
    "Laquelle de ces questions relève d'un usage écrit soutenu ?",
    ["Qu'a-t-il dit ?", "Il a dit quoi ?", "C'est quoi qu'il a dit ?", "Il a dit quoi, lui ?"],
    "Qu'a-t-il dit ?",
    "L'inversion du sujet et le pronom « que » placé en tête sont les marques de l'interrogation écrite. Les trois autres formes s'entendent tous les jours et ne s'écrivent que pour faire entendre une voix."),
  G(4, "4e_gram_oral_ecrit", 2,
    "« Y a un truc bizarre dans cette maison. » Comment l'écrire correctement ?",
    [
      "Il y a quelque chose d'étrange dans cette maison.",
      "Y a quelque chose d'étrange dans cette maison.",
      "Il y a un truc bizarre dans cette maison.",
      "Ya un truc bizarre dans cette maison.",
    ],
    "Il y a quelque chose d'étrange dans cette maison.",
    "Deux corrections en une : le sujet « il » qu'on ne prononce plus, et le mot familier « truc » remplacé par un terme précis. Corriger l'un sans l'autre laisse la phrase à mi-chemin."),
  G(5, "4e_gram_oral_ecrit", 3,
    "Dans un article de presse, quelle formulation convient ?",
    [
      "Les habitants affirment n'avoir rien entendu.",
      "Les gens disent qu'ils ont rien entendu.",
      "Les gens, ils disent qu'ils ont rien entendu.",
      "Personne a rien entendu, qu'ils disent.",
    ],
    "Les habitants affirment n'avoir rien entendu.",
    "L'écrit journalistique nomme précisément, garde la négation complète et évite de reprendre le sujet par un pronom. Les trois autres phrases se disent très bien — elles ne s'impriment pas."),
  G(6, "4e_gram_oral_ecrit", 3,
    "« Ce mec-là, il est jamais à l'heure. » Qu'est-ce qui, dans cette phrase, ne s'écrit pas ?",
    [
      "la reprise du sujet par « il » et le mot familier « mec »",
      "le mot « jamais », qui appartient au registre familier",
      "la place du complément « à l'heure » en fin de phrase",
      "rien du tout : la phrase est déjà correcte à l'écrit",
    ],
    "la reprise du sujet par « il » et le mot familier « mec »",
    "L'oral annonce d'abord de qui l'on parle, puis reprend par un pronom : c'est commode pour la voix, inutile pour l'œil. À quoi s'ajoute ici la négation amputée de son « ne »."),

  // ══════════════════════════════════════════════════════════════════════
  // CONJUGAISON · identifier temps, mode et personne
  // ══════════════════════════════════════════════════════════════════════
  C(1, "4e_conj_identifier", 1,
    "« Nous partions à l'aube, le sac déjà prêt. » À quel temps le verbe est-il conjugué ?",
    ["à l'imparfait", "au passé simple", "au présent", "au conditionnel"],
    "à l'imparfait",
    "La terminaison -ions de la première personne du pluriel ne se rencontre qu'à l'imparfait et au subjonctif présent. Ici rien n'introduit un subjonctif : c'est l'indicatif."),
  C(2, "4e_conj_identifier", 2,
    "« Il fallait qu'il vienne avant la nuit. » À quel mode « vienne » est-il ?",
    ["au subjonctif", "à l'indicatif", "au conditionnel", "à l'impératif"],
    "au subjonctif",
    "« Il faut que » réclame toujours le subjonctif : le verbe dépend d'une nécessité, pas d'un fait constaté. Comparez « il vient » — la forme change parce que le regard change."),
  C(3, "4e_conj_identifier", 2,
    "« Elle avait compris bien avant les autres. » Quel est le temps de ce verbe ?",
    ["le plus-que-parfait", "le passé composé", "l'imparfait", "le conditionnel passé"],
    "le plus-que-parfait",
    "Auxiliaire à l'imparfait plus participe passé : le plus-que-parfait sert à raconter ce qui s'est passé avant le reste du récit. « Bien avant les autres » le confirme."),
  C(4, "4e_conj_identifier", 2,
    "« Nous serions arrivés plus tôt sans cette panne. » Quel est le temps de ce verbe ?",
    ["le conditionnel passé", "le futur antérieur", "le plus-que-parfait", "le conditionnel présent"],
    "le conditionnel passé",
    "L'auxiliaire est au conditionnel présent, et le participe passé le complète. Le temps sert ici à dire ce qui aurait pu se produire et ne s'est pas produit."),
  C(5, "4e_conj_identifier", 3,
    "« Ils crurent d'abord à une plaisanterie. » Quel est l'infinitif de « crurent » ?",
    ["croire", "craindre", "croître", "cueillir"],
    "croire",
    "Le passé simple de « croire » fait « il crut, ils crurent ». Attention à « croître », dont le passé simple prend un accent circonflexe : « il crût » — un accent qui distingue deux verbes."),
  C(6, "4e_conj_identifier", 3,
    "Entre « que vous fassiez » et « que vous faisiez », laquelle des deux formes est au subjonctif ?",
    ["que vous fassiez", "que vous faisiez", "les deux", "aucune des deux"],
    "que vous fassiez",
    "Le subjonctif de « faire » se bâtit sur le radical « fass- ». « Que vous faisiez » est un imparfait de l'indicatif, qu'on rencontre après « pendant que » ou « parce que »."),

  // ── CONJUGAISON · composer les formes ─────────────────────────────────
  C(1, "4e_conj_composer", 1,
    "« Il faut que tu … une décision avant ce soir. » Quelle forme du verbe « prendre » convient ?",
    ["prennes", "prends", "prendras", "prenne"],
    "prennes",
    "« Il faut que » impose le subjonctif, et la deuxième personne du singulier y prend un s. « Prenne » conviendrait pour « il » ou « elle »."),
  C(2, "4e_conj_composer", 2,
    "« Si j'avais su, je … avec vous. » Quelle forme du verbe « venir » convient ?",
    ["serais venu", "serai venu", "viendrais", "serais venue"],
    "serais venu",
    "Après un « si » suivi du plus-que-parfait, la seconde partie se met au conditionnel passé. Le conditionnel présent dirait autre chose : que la venue serait encore possible."),
  C(3, "4e_conj_composer", 2,
    "« Nous … volontiers si tu nous invitais. » Quelle forme du verbe « aller » convient ?",
    ["irions", "irons", "allions", "allons"],
    "irions",
    "« Si » suivi de l'imparfait appelle le conditionnel présent : la condition n'est pas remplie. « Irons » supposerait au contraire que l'invitation soit acquise."),
  C(4, "4e_conj_composer", 2,
    "« Ils … le spectacle la veille, et n'en parlaient plus. » Quelle forme du verbe « voir » convient ?",
    ["avaient vu", "ont vu", "virent", "avaient vus"],
    "avaient vu",
    "« La veille » situe l'action avant le récit, qui est à l'imparfait : c'est le plus-que-parfait. Et le participe reste invariable, faute de complément d'objet placé devant."),
  C(5, "4e_conj_composer", 3,
    "« Dès qu'il … , il quitta la pièce sans un mot. » Quelle forme du verbe « finir » convient ?",
    ["eut fini", "eût fini", "a fini", "finissait"],
    "eut fini",
    "Le passé antérieur accompagne le passé simple : l'auxiliaire prend le passé simple, sans accent. Avec l'accent, « eût fini » deviendrait un subjonctif plus-que-parfait, qui n'a rien à faire ici."),
  C(6, "4e_conj_composer", 3,
    "« Je souhaite qu'elle … heureuse. » Quelle forme du verbe « être » convient ?",
    ["soit", "est", "sera", "serait"],
    "soit",
    "Un souhait n'est pas un fait : le verbe passe au subjonctif. C'est la différence entre « je sais qu'elle est heureuse », qui constate, et « je souhaite qu'elle soit heureuse », qui espère."),

  // ── CONJUGAISON · employer les temps selon le sens ────────────────────
  C(1, "4e_conj_employer", 1,
    "« Il marchait depuis une heure quand l'orage éclata. » Que dit l'imparfait dans cette phrase ?",
    [
      "une action qui dure, sur laquelle une autre vient s'inscrire",
      "une action brève et unique, aussitôt achevée dans le récit",
      "une habitude ancienne, que le personnage répète chaque jour",
      "une action encore entièrement à venir au moment du récit",
    ],
    "une action qui dure, sur laquelle une autre vient s'inscrire",
    "Les deux temps se partagent le travail : l'imparfait tend la toile de fond, le passé simple y plante l'événement. C'est ce contraste qui fait avancer un récit."),
  C(2, "4e_conj_employer", 2,
    "« Si tu venais, tout serait plus simple. » Que signifie cette phrase ?",
    [
      "que la venue n'a pas lieu, mais qu'elle changerait les choses",
      "que la venue est certaine, et qu'elle est même déjà décidée",
      "que la venue a déjà eu lieu, et que rien n'a changé",
      "qu'il est formellement interdit de venir, quoi qu'il arrive",
    ],
    "que la venue n'a pas lieu, mais qu'elle changerait les choses",
    "L'imparfait après « si » ouvre une hypothèse, et le conditionnel en tire la conséquence. Rien n'est encore arrivé : la phrase décrit un monde possible, pas le monde réel."),
  C(3, "4e_conj_employer", 2,
    "« Le suspect aurait quitté la ville dans la nuit. » Que marque le conditionnel ici ?",
    [
      "que l'information n'est pas confirmée",
      "que le départ est absolument certain",
      "qu'il s'agit d'un ordre à exécuter",
      "que l'action est déjà très ancienne",
    ],
    "que l'information n'est pas confirmée",
    "C'est le conditionnel de la presse : le journaliste rapporte sans garantir. Le supprimer — « le suspect a quitté la ville » — engagerait le journal tout entier."),
  C(4, "4e_conj_employer", 2,
    "« Je sais que tu pars » et « Je veux que tu partes » : pourquoi le mode change-t-il ?",
    [
      "parce que la première constate un fait, la seconde exprime une volonté",
      "parce que la seconde phrase est tout entière tournée vers le futur",
      "parce que le verbe « vouloir » est un verbe tout à fait irrégulier",
      "parce que la première phrase est nettement plus longue que l'autre",
    ],
    "parce que la première constate un fait, la seconde exprime une volonté",
    "L'indicatif dit ce qui est, le subjonctif ce qu'on veut, craint ou attend. Le mode ne dépend pas du verbe de la subordonnée mais du regard porté depuis la principale."),
  C(5, "4e_conj_employer", 3,
    "« Elle ouvrit la porte, hésita, puis entra. » Que produit le passé simple ?",
    [
      "il fait avancer le récit par actions successives et nettes",
      "il installe un décor immobile qui dure longtemps",
      "il exprime une habitude qui se répète chaque jour",
      "il rapproche l'action du moment où l'on parle aujourd'hui",
    ],
    "il fait avancer le récit par actions successives et nettes",
    "Chaque verbe au passé simple pousse l'histoire d'un cran. Réécrite à l'imparfait, la même phrase donnerait l'impression que rien n'arrive vraiment."),
  C(6, "4e_conj_employer", 3,
    "« Demain, je pars à six heures. » Pourquoi le présent est-il possible ici ?",
    [
      "parce qu'un complément de temps situe déjà l'action dans le futur",
      "parce que le verbe « partir » n'a pas de futur à cette personne",
      "parce que la phrase est en réalité une question déguisée",
      "parce que le présent est toujours possible, en toute phrase",
    ],
    "parce qu'un complément de temps situe déjà l'action dans le futur",
    "« Demain » suffit à déplacer l'action ; le présent apporte alors une nuance de décision prise. « Je partirai » dirait la même chose de plus loin."),

  // ══════════════════════════════════════════════════════════════════════
  // DISCOURS · les registres de langue
  // ══════════════════════════════════════════════════════════════════════
  D(1, "4e_discours_registres", 1,
    "« Ce bouquin est génial » et « Cet ouvrage est remarquable » : qu'est-ce qui change d'une phrase à l'autre ?",
    [
      "le registre de langue, pas le sens",
      "le sens, pas le registre de langue",
      "le temps auquel sont les verbes",
      "la fonction du sujet de la phrase",
    ],
    "le registre de langue, pas le sens",
    "Les deux phrases disent le même jugement à deux publics différents. Choisir un registre, ce n'est pas choisir une idée : c'est choisir à qui l'on parle."),
  D(2, "4e_discours_registres", 1,
    "Parmi ces mots, lequel appartient au registre familier ?",
    ["bagnole", "automobile", "véhicule", "voiture"],
    "bagnole",
    "« Voiture » est courant, « véhicule » et « automobile » relèvent de l'écrit administratif ou technique. « Bagnole » ne s'écrit que pour faire entendre quelqu'un parler."),
  D(3, "4e_discours_registres", 2,
    "Comment écrire « il flippe » dans un devoir ?",
    ["il est terrifié", "il flippe", "il a les jetons", "il flippe complètement"],
    "il est terrifié",
    "Passer du familier au courant demande souvent de changer de mot, pas de le rallonger. Ajouter un adverbe à un terme familier le laisse familier."),
  D(4, "4e_discours_registres", 2,
    "« Auriez-vous l'obligeance de m'indiquer la sortie ? » De quel registre relève cette phrase ?",
    ["soutenu", "courant", "familier", "argotique"],
    "soutenu",
    "Le conditionnel de politesse, l'inversion du sujet et le mot « obligeance » se rencontrent rarement à l'oral ordinaire. Le registre soutenu marque la distance autant que le respect."),
  D(5, "4e_discours_registres", 3,
    "Dans une lettre adressée au principal du collège, quelle formule convient ?",
    [
      "Je vous prie de bien vouloir examiner ma demande.",
      "Ça serait sympa que vous regardiez ma demande.",
      "Vous pouvez regarder ma demande ?",
      "Faut que vous regardiez ma demande.",
    ],
    "Je vous prie de bien vouloir examiner ma demande.",
    "La lettre officielle a ses formules, et elles ne sont pas de la politesse décorative : elles disent qu'on connaît les usages du destinataire. C'est déjà un argument."),
  D(6, "4e_discours_registres", 3,
    "« Il a pas voulu, du coup j'ai laissé tomber. » Pourquoi cette phrase ne convient-elle pas à l'écrit scolaire ?",
    [
      "la négation est incomplète et le lexique est familier",
      "elle contient deux verbes conjugués au lieu d'un seul",
      "elle est bien trop courte pour un écrit scolaire soigné",
      "elle commence par un pronom plutôt que par un nom",
    ],
    "la négation est incomplète et le lexique est familier",
    "Deux marques d'oral se cumulent : le « ne » qui saute, et « du coup » suivi de « laisser tomber ». À l'écrit : « Il a refusé ; j'ai donc renoncé. »"),

  // ── DISCOURS · les paroles rapportées ─────────────────────────────────
  D(1, "4e_discours_rapportees", 1,
    "« Il déclara : « Je pars demain. » » De quel type de discours s'agit-il ?",
    ["du discours direct", "du discours indirect", "du discours narrativisé", "d'un monologue intérieur"],
    "du discours direct",
    "Deux points, guillemets, verbe de parole : les paroles sont données telles qu'elles ont été dites. Le lecteur entend la voix du personnage, pas celle du narrateur."),
  D(2, "4e_discours_rapportees", 2,
    "Comment transposer « Il déclara : « Je pars demain. » » au discours indirect ?",
    [
      "Il déclara qu'il partait le lendemain.",
      "Il déclara qu'il part demain.",
      "Il déclara : il partait le lendemain.",
      "Il déclara qu'il partirait demain.",
    ],
    "Il déclara qu'il partait le lendemain.",
    "Trois changements en même temps : la personne (je → il), le temps (présent → imparfait, à cause du verbe introducteur au passé) et le repère de temps (demain → le lendemain)."),
  D(3, "4e_discours_rapportees", 2,
    "« Elle demanda si nous étions prêts. » Quelle question a-t-elle réellement posée ?",
    ["« Êtes-vous prêts ? »", "« Sommes-nous prêts ? »", "« Étiez-vous prêts ? »", "« Serez-vous prêts ? »"],
    "« Êtes-vous prêts ? »",
    "Pour remonter au discours direct, on défait les transformations : « si » disparaît, le nous redevient vous, et l'imparfait retrouve son présent."),
  D(4, "4e_discours_rapportees", 2,
    "Dans un roman, qu'est-ce qui signale à coup sûr un discours direct ?",
    [
      "les guillemets ou les tirets, avec un verbe de parole",
      "la présence d'un point d'exclamation dans la phrase",
      "un paragraphe très court, bien isolé dans la page",
      "l'emploi du passé simple dans la proposition qui suit",
    ],
    "les guillemets ou les tirets, avec un verbe de parole",
    "La ponctuation ouvre la voix, le verbe dit qui parle. L'un sans l'autre laisse le lecteur dans le doute — et certains auteurs en jouent volontairement."),
  D(5, "4e_discours_rapportees", 3,
    "« Il dit qu'il viendrait le lendemain. » Pourquoi le verbe est-il au conditionnel ?",
    [
      "parce que le verbe introducteur est au passé : futur du passé",
      "parce que la venue annoncée reste malgré tout incertaine",
      "parce qu'il s'agit d'une hypothèse et non d'un fait établi",
      "parce que le narrateur doute ouvertement de cette parole",
    ],
    "parce que le verbe introducteur est au passé : futur du passé",
    "Au discours direct il avait dit « je viendrai ». Le passage à l'indirect, sous un verbe au passé, transforme mécaniquement ce futur en conditionnel — sans jeter le moindre doute sur la parole."),
  D(6, "4e_discours_rapportees", 3,
    "« Le maire a annoncé la fermeture du pont. » Comment la parole est-elle rapportée ?",
    [
      "elle est résumée en quelques mots, sans les mots dits",
      "elle est citée mot pour mot, entre des guillemets",
      "elle est transposée au discours indirect",
      "elle n'est pas du tout rapportée dans cet article",
    ],
    "elle est résumée en quelques mots, sans les mots dits",
    "Aucune subordonnée, aucun guillemet : la parole est réduite à un groupe nominal. Le procédé accélère le récit, mais il fait disparaître la manière dont les choses ont été dites."),

  // ── DISCOURS · les procédés de l'argumentation ────────────────────────
  D(1, "4e_discours_argumentatif", 1,
    "« Ce film est nul, tout le monde le dit. » Sur quoi repose cet argument ?",
    [
      "sur l'opinion du plus grand nombre, qui ne prouve rien",
      "sur une preuve que n'importe qui pourrait vérifier",
      "sur l'avis motivé d'un spécialiste reconnu du sujet",
      "sur un exemple précis pris dans la réalité de tous",
    ],
    "sur l'opinion du plus grand nombre, qui ne prouve rien",
    "Le nombre n'est pas une raison : une opinion partagée par tous peut être fausse. Repérer ce glissement, c'est déjà savoir résister à un argument."),
  D(2, "4e_discours_argumentatif", 1,
    "Lequel de ces mots de liaison introduit une conséquence ?",
    ["donc", "or", "cependant", "bien que"],
    "donc",
    "« Donc » tire la suite de ce qui précède. « Or » relance, « cependant » et « bien que » opposent : les connecteurs sont les panneaux de signalisation d'un raisonnement."),
  D(3, "4e_discours_argumentatif", 2,
    "« Les chiffres publiés par le ministère montrent que le trafic a doublé. » Quel type d'argument est-ce ?",
    [
      "un argument appuyé sur une source qu'on peut nommer",
      "un argument fondé sur la seule émotion du lecteur",
      "un exemple personnel, tiré de sa propre vie",
      "une question rhétorique, posée sans attendre de réponse",
    ],
    "un argument appuyé sur une source qu'on peut nommer",
    "L'argument vaut par sa source, et la source est vérifiable. C'est ce qui le sépare d'un « on dit que » : le lecteur peut aller voir."),
  D(4, "4e_discours_argumentatif", 2,
    "« Certes, le trajet est long ; mais la route est magnifique. » Que fait le mot « certes » ?",
    [
      "il accorde un point à l'adversaire pour le retourner",
      "il annonce une preuve chiffrée et bien vérifiable",
      "il exprime un doute personnel de celui qui parle",
      "il conclut le raisonnement tout entier d'un mot",
    ],
    "il accorde un point à l'adversaire pour le retourner",
    "C'est la concession : on donne raison sur un détail pour mieux emporter le reste. Le vrai argument arrive toujours après le « mais »."),
  D(5, "4e_discours_argumentatif", 3,
    "Parmi ces phrases, laquelle est un exemple et non un argument ?",
    [
      "L'an dernier, ma voisine a attendu trois heures aux urgences.",
      "Les délais d'attente allongent les risques pour les patients.",
      "Un hôpital doit pouvoir accueillir tout le monde.",
      "Réduire les moyens revient à réduire les soins.",
    ],
    "L'an dernier, ma voisine a attendu trois heures aux urgences.",
    "Un exemple raconte un cas ; un argument énonce une raison qui vaut au-delà du cas. L'exemple ne prouve pas tout seul — il rend sensible ce que l'argument affirme."),
  D(6, "4e_discours_argumentatif", 3,
    "« Voulez-vous vraiment que cela recommence ? » Quel effet cette question cherche-t-elle ?",
    [
      "faire adhérer le lecteur sans avoir à démontrer",
      "obtenir du lecteur une information précise",
      "montrer que l'auteur hésite encore un peu",
      "changer de sujet sans le dire au lecteur",
    ],
    "faire adhérer le lecteur sans avoir à démontrer",
    "La question rhétorique n'attend pas de réponse : elle la contient. Elle fait dire au lecteur ce que l'auteur n'aurait pas à prouver — d'où sa force, et sa malhonnêteté possible."),
];
