import type { TutorBankItemV4 } from "@/lib/tutor-v4/types";

export const iaB2QuestionBank: TutorBankItemV4[] = [
  {
    kind: "fixed",
    id: "ia_b2_prompt_structure_qcm_001",
    niveau: "b2",
    matiere: "ia",
    notionId: "ia_b2_prompt_avance",
    microId: "ia_b2_prompt_structure",
    difficulty: 1,
    text: "Quelle affirmation valide la micro-competence B2 : Je sais construire un prompt avec role, contexte, tache, contraintes et format attendu.",
    format: "qcm",
    choices: ["Je sais construire un prompt avec role, contexte, tache, contraintes et format attendu.","Je laisse l'IA decider a ma place.","Je copie la reponse sans verifier."],
    expected: ["Je sais construire un prompt avec role, contexte, tache, contraintes et format attendu."],
    comparator: "mcq_exact",
    hint: "Cherche la reponse qui garde methode, jugement et responsabilite humaine.",
    explanation: "Bonne reponse : Je sais construire un prompt avec role, contexte, tache, contraintes et format attendu.",
  },
  {
    kind: "fixed",
    id: "ia_b2_prompt_structure_qcm_002",
    niveau: "b2",
    matiere: "ia",
    notionId: "ia_b2_prompt_avance",
    microId: "ia_b2_prompt_structure",
    difficulty: 1,
    text: "Dans une situation reelle, quelle action correspond le mieux a : Je sais construire un prompt avec role, contexte, tache, contraintes et format attendu.",
    format: "qcm",
    choices: ["Je sais construire un prompt avec role, contexte, tache, contraintes et format attendu.","Partager des informations sensibles pour aller plus vite.","Faire confiance a une seule reponse sans recul."],
    expected: ["Je sais construire un prompt avec role, contexte, tache, contraintes et format attendu."],
    comparator: "mcq_exact",
    hint: "L'IA est un outil : l'eleve garde l'objectif, la verification et la decision.",
    explanation: "Cette micro-competence se valide quand l'eleve sait faire ceci : Je sais construire un prompt avec role, contexte, tache, contraintes et format attendu.",
  },
  {
    kind: "fixed",
    id: "ia_b2_iteration_qcm_001",
    niveau: "b2",
    matiere: "ia",
    notionId: "ia_b2_prompt_avance",
    microId: "ia_b2_iteration",
    difficulty: 1,
    text: "Quelle affirmation valide la micro-competence B2 : Je sais ameliorer un resultat IA par iterations successives.",
    format: "qcm",
    choices: ["Je sais ameliorer un resultat IA par iterations successives.","Je laisse l'IA decider a ma place.","Je copie la reponse sans verifier."],
    expected: ["Je sais ameliorer un resultat IA par iterations successives."],
    comparator: "mcq_exact",
    hint: "Cherche la reponse qui garde methode, jugement et responsabilite humaine.",
    explanation: "Bonne reponse : Je sais ameliorer un resultat IA par iterations successives.",
  },
  {
    kind: "fixed",
    id: "ia_b2_iteration_qcm_002",
    niveau: "b2",
    matiere: "ia",
    notionId: "ia_b2_prompt_avance",
    microId: "ia_b2_iteration",
    difficulty: 1,
    text: "Dans une situation reelle, quelle action correspond le mieux a : Je sais ameliorer un resultat IA par iterations successives.",
    format: "qcm",
    choices: ["Je sais ameliorer un resultat IA par iterations successives.","Partager des informations sensibles pour aller plus vite.","Faire confiance a une seule reponse sans recul."],
    expected: ["Je sais ameliorer un resultat IA par iterations successives."],
    comparator: "mcq_exact",
    hint: "L'IA est un outil : l'eleve garde l'objectif, la verification et la decision.",
    explanation: "Cette micro-competence se valide quand l'eleve sait faire ceci : Je sais ameliorer un resultat IA par iterations successives.",
  },
  {
    kind: "fixed",
    id: "ia_b2_choisir_version_qcm_001",
    niveau: "b2",
    matiere: "ia",
    notionId: "ia_b2_prompt_avance",
    microId: "ia_b2_choisir_version",
    difficulty: 2,
    text: "Quelle affirmation valide la micro-competence B2 : Je sais generer plusieurs versions puis choisir et justifier la meilleure.",
    format: "qcm",
    choices: ["Je sais generer plusieurs versions puis choisir et justifier la meilleure.","Je laisse l'IA decider a ma place.","Je copie la reponse sans verifier."],
    expected: ["Je sais generer plusieurs versions puis choisir et justifier la meilleure."],
    comparator: "mcq_exact",
    hint: "Cherche la reponse qui garde methode, jugement et responsabilite humaine.",
    explanation: "Bonne reponse : Je sais generer plusieurs versions puis choisir et justifier la meilleure.",
  },
  {
    kind: "fixed",
    id: "ia_b2_choisir_version_qcm_002",
    niveau: "b2",
    matiere: "ia",
    notionId: "ia_b2_prompt_avance",
    microId: "ia_b2_choisir_version",
    difficulty: 2,
    text: "Dans une situation reelle, quelle action correspond le mieux a : Je sais generer plusieurs versions puis choisir et justifier la meilleure.",
    format: "qcm",
    choices: ["Je sais generer plusieurs versions puis choisir et justifier la meilleure.","Partager des informations sensibles pour aller plus vite.","Faire confiance a une seule reponse sans recul."],
    expected: ["Je sais generer plusieurs versions puis choisir et justifier la meilleure."],
    comparator: "mcq_exact",
    hint: "L'IA est un outil : l'eleve garde l'objectif, la verification et la decision.",
    explanation: "Cette micro-competence se valide quand l'eleve sait faire ceci : Je sais generer plusieurs versions puis choisir et justifier la meilleure.",
  },
  {
    kind: "fixed",
    id: "ia_b2_creer_contenu_qcm_001",
    niveau: "b2",
    matiere: "ia",
    notionId: "ia_b2_production",
    microId: "ia_b2_creer_contenu",
    difficulty: 2,
    text: "Quelle affirmation valide la micro-competence B2 : Je sais creer une affiche, un texte, un quiz, une image ou une presentation avec l'IA.",
    format: "qcm",
    choices: ["Je sais creer une affiche, un texte, un quiz, une image ou une presentation avec l'IA.","Je laisse l'IA decider a ma place.","Je copie la reponse sans verifier."],
    expected: ["Je sais creer une affiche, un texte, un quiz, une image ou une presentation avec l'IA."],
    comparator: "mcq_exact",
    hint: "Cherche la reponse qui garde methode, jugement et responsabilite humaine.",
    explanation: "Bonne reponse : Je sais creer une affiche, un texte, un quiz, une image ou une presentation avec l'IA.",
  },
  {
    kind: "fixed",
    id: "ia_b2_creer_contenu_qcm_002",
    niveau: "b2",
    matiere: "ia",
    notionId: "ia_b2_production",
    microId: "ia_b2_creer_contenu",
    difficulty: 2,
    text: "Dans une situation reelle, quelle action correspond le mieux a : Je sais creer une affiche, un texte, un quiz, une image ou une presentation avec l'IA.",
    format: "qcm",
    choices: ["Je sais creer une affiche, un texte, un quiz, une image ou une presentation avec l'IA.","Partager des informations sensibles pour aller plus vite.","Faire confiance a une seule reponse sans recul."],
    expected: ["Je sais creer une affiche, un texte, un quiz, une image ou une presentation avec l'IA."],
    comparator: "mcq_exact",
    hint: "L'IA est un outil : l'eleve garde l'objectif, la verification et la decision.",
    explanation: "Cette micro-competence se valide quand l'eleve sait faire ceci : Je sais creer une affiche, un texte, un quiz, une image ou une presentation avec l'IA.",
  },
  {
    kind: "fixed",
    id: "ia_b2_prototype_simple_qcm_001",
    niveau: "b2",
    matiere: "ia",
    notionId: "ia_b2_production",
    microId: "ia_b2_prototype_simple",
    difficulty: 3,
    text: "Quelle affirmation valide la micro-competence B2 : Je sais creer une maquette ou un petit prototype avec l'aide de l'IA.",
    format: "qcm",
    choices: ["Je sais creer une maquette ou un petit prototype avec l'aide de l'IA.","Je laisse l'IA decider a ma place.","Je copie la reponse sans verifier."],
    expected: ["Je sais creer une maquette ou un petit prototype avec l'aide de l'IA."],
    comparator: "mcq_exact",
    hint: "Cherche la reponse qui garde methode, jugement et responsabilite humaine.",
    explanation: "Bonne reponse : Je sais creer une maquette ou un petit prototype avec l'aide de l'IA.",
  },
  {
    kind: "fixed",
    id: "ia_b2_prototype_simple_qcm_002",
    niveau: "b2",
    matiere: "ia",
    notionId: "ia_b2_production",
    microId: "ia_b2_prototype_simple",
    difficulty: 3,
    text: "Dans une situation reelle, quelle action correspond le mieux a : Je sais creer une maquette ou un petit prototype avec l'aide de l'IA.",
    format: "qcm",
    choices: ["Je sais creer une maquette ou un petit prototype avec l'aide de l'IA.","Partager des informations sensibles pour aller plus vite.","Faire confiance a une seule reponse sans recul."],
    expected: ["Je sais creer une maquette ou un petit prototype avec l'aide de l'IA."],
    comparator: "mcq_exact",
    hint: "L'IA est un outil : l'eleve garde l'objectif, la verification et la decision.",
    explanation: "Cette micro-competence se valide quand l'eleve sait faire ceci : Je sais creer une maquette ou un petit prototype avec l'aide de l'IA.",
  },
  {
    kind: "fixed",
    id: "ia_b2_documenter_role_ia_qcm_001",
    niveau: "b2",
    matiere: "ia",
    notionId: "ia_b2_production",
    microId: "ia_b2_documenter_role_ia",
    difficulty: 3,
    text: "Quelle affirmation valide la micro-competence B2 : Je sais documenter ce que l'IA a produit et ce que j'ai modifie.",
    format: "qcm",
    choices: ["Je sais documenter ce que l'IA a produit et ce que j'ai modifie.","Je laisse l'IA decider a ma place.","Je copie la reponse sans verifier."],
    expected: ["Je sais documenter ce que l'IA a produit et ce que j'ai modifie."],
    comparator: "mcq_exact",
    hint: "Cherche la reponse qui garde methode, jugement et responsabilite humaine.",
    explanation: "Bonne reponse : Je sais documenter ce que l'IA a produit et ce que j'ai modifie.",
  },
  {
    kind: "fixed",
    id: "ia_b2_documenter_role_ia_qcm_002",
    niveau: "b2",
    matiere: "ia",
    notionId: "ia_b2_production",
    microId: "ia_b2_documenter_role_ia",
    difficulty: 3,
    text: "Dans une situation reelle, quelle action correspond le mieux a : Je sais documenter ce que l'IA a produit et ce que j'ai modifie.",
    format: "qcm",
    choices: ["Je sais documenter ce que l'IA a produit et ce que j'ai modifie.","Partager des informations sensibles pour aller plus vite.","Faire confiance a une seule reponse sans recul."],
    expected: ["Je sais documenter ce que l'IA a produit et ce que j'ai modifie."],
    comparator: "mcq_exact",
    hint: "L'IA est un outil : l'eleve garde l'objectif, la verification et la decision.",
    explanation: "Cette micro-competence se valide quand l'eleve sait faire ceci : Je sais documenter ce que l'IA a produit et ce que j'ai modifie.",
  },
];

export function getIaB2QuestionBank(args?: {
  notionId?: string | null;
  microId?: string | null;
}): TutorBankItemV4[] {
  let bank = iaB2QuestionBank;

  if (args?.notionId) bank = bank.filter((item) => item.notionId === args.notionId);
  if (args?.microId) bank = bank.filter((item) => item.microId === args.microId);

  return bank;
}
