import type { TutorBankItemV4 } from "@/lib/tutor-v4/types";

export const iaB2QuestionBank: TutorBankItemV4[] = [
  {
    kind: "fixed",
    id: "ia_b2_prompt_structure_qcm_001",
    niveau: "b2",
    matiere: "ia",
    notionId: "ia_b2_prompt_avance",
    microId: "ia_b2_prompt_structure",
    difficulty: 1,
    text: "Quelle affirmation valide la micro-comp?tence B2 : Je sais construire un prompt avec r?le, contexte, t?che, contraintes et format attendu.",
    format: "qcm",
    choices: ["Je sais construire un prompt avec r?le, contexte, t?che, contraintes et format attendu.","Je laisse l'IA d?cider ? ma place.","Je copie la r?ponse sans v?rifier."],
    expected: ["A"],
    comparator: "mcq_exact",
    hint: "Cherche la r?ponse qui garde m?thode, jugement et responsabilit? humaine.",
    explanation: "Bonne r?ponse : Je sais construire un prompt avec r?le, contexte, t?che, contraintes et format attendu.",
  },
  {
    kind: "fixed",
    id: "ia_b2_prompt_structure_qcm_002",
    niveau: "b2",
    matiere: "ia",
    notionId: "ia_b2_prompt_avance",
    microId: "ia_b2_prompt_structure",
    difficulty: 1,
    text: "Dans une situation r?elle, quelle action correspond le mieux ? : Je sais construire un prompt avec r?le, contexte, t?che, contraintes et format attendu.",
    format: "qcm",
    choices: ["Je sais construire un prompt avec r?le, contexte, t?che, contraintes et format attendu.","Partager des informations sensibles pour aller plus vite.","Faire confiance ? une seule r?ponse sans recul."],
    expected: ["A"],
    comparator: "mcq_exact",
    hint: "L'IA est un outil : l'?l?ve garde l'objectif, la v?rification et la d?cision.",
    explanation: "Cette micro-comp?tence se valide quand l'?l?ve sait faire ceci : Je sais construire un prompt avec r?le, contexte, t?che, contraintes et format attendu.",
  },
  {
    kind: "fixed",
    id: "ia_b2_iteration_qcm_001",
    niveau: "b2",
    matiere: "ia",
    notionId: "ia_b2_prompt_avance",
    microId: "ia_b2_iteration",
    difficulty: 1,
    text: "Quelle affirmation valide la micro-comp?tence B2 : Je sais am?liorer un r?sultat IA par it?rations successives.",
    format: "qcm",
    choices: ["Je sais am?liorer un r?sultat IA par it?rations successives.","Je laisse l'IA d?cider ? ma place.","Je copie la r?ponse sans v?rifier."],
    expected: ["A"],
    comparator: "mcq_exact",
    hint: "Cherche la r?ponse qui garde m?thode, jugement et responsabilit? humaine.",
    explanation: "Bonne r?ponse : Je sais am?liorer un r?sultat IA par it?rations successives.",
  },
  {
    kind: "fixed",
    id: "ia_b2_iteration_qcm_002",
    niveau: "b2",
    matiere: "ia",
    notionId: "ia_b2_prompt_avance",
    microId: "ia_b2_iteration",
    difficulty: 1,
    text: "Dans une situation r?elle, quelle action correspond le mieux ? : Je sais am?liorer un r?sultat IA par it?rations successives.",
    format: "qcm",
    choices: ["Je sais am?liorer un r?sultat IA par it?rations successives.","Partager des informations sensibles pour aller plus vite.","Faire confiance ? une seule r?ponse sans recul."],
    expected: ["A"],
    comparator: "mcq_exact",
    hint: "L'IA est un outil : l'?l?ve garde l'objectif, la v?rification et la d?cision.",
    explanation: "Cette micro-comp?tence se valide quand l'?l?ve sait faire ceci : Je sais am?liorer un r?sultat IA par it?rations successives.",
  },
  {
    kind: "fixed",
    id: "ia_b2_choisir_version_qcm_001",
    niveau: "b2",
    matiere: "ia",
    notionId: "ia_b2_prompt_avance",
    microId: "ia_b2_choisir_version",
    difficulty: 2,
    text: "Quelle affirmation valide la micro-comp?tence B2 : Je sais g?n?rer plusieurs versions puis choisir et justifier la meilleure.",
    format: "qcm",
    choices: ["Je sais g?n?rer plusieurs versions puis choisir et justifier la meilleure.","Je laisse l'IA d?cider ? ma place.","Je copie la r?ponse sans v?rifier."],
    expected: ["A"],
    comparator: "mcq_exact",
    hint: "Cherche la r?ponse qui garde m?thode, jugement et responsabilit? humaine.",
    explanation: "Bonne r?ponse : Je sais g?n?rer plusieurs versions puis choisir et justifier la meilleure.",
  },
  {
    kind: "fixed",
    id: "ia_b2_choisir_version_qcm_002",
    niveau: "b2",
    matiere: "ia",
    notionId: "ia_b2_prompt_avance",
    microId: "ia_b2_choisir_version",
    difficulty: 2,
    text: "Dans une situation r?elle, quelle action correspond le mieux ? : Je sais g?n?rer plusieurs versions puis choisir et justifier la meilleure.",
    format: "qcm",
    choices: ["Je sais g?n?rer plusieurs versions puis choisir et justifier la meilleure.","Partager des informations sensibles pour aller plus vite.","Faire confiance ? une seule r?ponse sans recul."],
    expected: ["A"],
    comparator: "mcq_exact",
    hint: "L'IA est un outil : l'?l?ve garde l'objectif, la v?rification et la d?cision.",
    explanation: "Cette micro-comp?tence se valide quand l'?l?ve sait faire ceci : Je sais g?n?rer plusieurs versions puis choisir et justifier la meilleure.",
  },
  {
    kind: "fixed",
    id: "ia_b2_creer_contenu_qcm_001",
    niveau: "b2",
    matiere: "ia",
    notionId: "ia_b2_production",
    microId: "ia_b2_creer_contenu",
    difficulty: 2,
    text: "Quelle affirmation valide la micro-comp?tence B2 : Je sais cr?er une affiche, un texte, un quiz, une image ou une pr?sentation avec l'IA.",
    format: "qcm",
    choices: ["Je sais cr?er une affiche, un texte, un quiz, une image ou une pr?sentation avec l'IA.","Je laisse l'IA d?cider ? ma place.","Je copie la r?ponse sans v?rifier."],
    expected: ["A"],
    comparator: "mcq_exact",
    hint: "Cherche la r?ponse qui garde m?thode, jugement et responsabilit? humaine.",
    explanation: "Bonne r?ponse : Je sais cr?er une affiche, un texte, un quiz, une image ou une pr?sentation avec l'IA.",
  },
  {
    kind: "fixed",
    id: "ia_b2_creer_contenu_qcm_002",
    niveau: "b2",
    matiere: "ia",
    notionId: "ia_b2_production",
    microId: "ia_b2_creer_contenu",
    difficulty: 2,
    text: "Dans une situation r?elle, quelle action correspond le mieux ? : Je sais cr?er une affiche, un texte, un quiz, une image ou une pr?sentation avec l'IA.",
    format: "qcm",
    choices: ["Je sais cr?er une affiche, un texte, un quiz, une image ou une pr?sentation avec l'IA.","Partager des informations sensibles pour aller plus vite.","Faire confiance ? une seule r?ponse sans recul."],
    expected: ["A"],
    comparator: "mcq_exact",
    hint: "L'IA est un outil : l'?l?ve garde l'objectif, la v?rification et la d?cision.",
    explanation: "Cette micro-comp?tence se valide quand l'?l?ve sait faire ceci : Je sais cr?er une affiche, un texte, un quiz, une image ou une pr?sentation avec l'IA.",
  },
  {
    kind: "fixed",
    id: "ia_b2_prototype_simple_qcm_001",
    niveau: "b2",
    matiere: "ia",
    notionId: "ia_b2_production",
    microId: "ia_b2_prototype_simple",
    difficulty: 3,
    text: "Quelle affirmation valide la micro-comp?tence B2 : Je sais cr?er une maquette ou un petit prototype avec l'aide de l'IA.",
    format: "qcm",
    choices: ["Je sais cr?er une maquette ou un petit prototype avec l'aide de l'IA.","Je laisse l'IA d?cider ? ma place.","Je copie la r?ponse sans v?rifier."],
    expected: ["A"],
    comparator: "mcq_exact",
    hint: "Cherche la r?ponse qui garde m?thode, jugement et responsabilit? humaine.",
    explanation: "Bonne r?ponse : Je sais cr?er une maquette ou un petit prototype avec l'aide de l'IA.",
  },
  {
    kind: "fixed",
    id: "ia_b2_prototype_simple_qcm_002",
    niveau: "b2",
    matiere: "ia",
    notionId: "ia_b2_production",
    microId: "ia_b2_prototype_simple",
    difficulty: 3,
    text: "Dans une situation r?elle, quelle action correspond le mieux ? : Je sais cr?er une maquette ou un petit prototype avec l'aide de l'IA.",
    format: "qcm",
    choices: ["Je sais cr?er une maquette ou un petit prototype avec l'aide de l'IA.","Partager des informations sensibles pour aller plus vite.","Faire confiance ? une seule r?ponse sans recul."],
    expected: ["A"],
    comparator: "mcq_exact",
    hint: "L'IA est un outil : l'?l?ve garde l'objectif, la v?rification et la d?cision.",
    explanation: "Cette micro-comp?tence se valide quand l'?l?ve sait faire ceci : Je sais cr?er une maquette ou un petit prototype avec l'aide de l'IA.",
  },
  {
    kind: "fixed",
    id: "ia_b2_documenter_role_ia_qcm_001",
    niveau: "b2",
    matiere: "ia",
    notionId: "ia_b2_production",
    microId: "ia_b2_documenter_role_ia",
    difficulty: 3,
    text: "Quelle affirmation valide la micro-comp?tence B2 : Je sais documenter ce que l'IA a produit et ce que j'ai modifi?.",
    format: "qcm",
    choices: ["Je sais documenter ce que l'IA a produit et ce que j'ai modifi?.","Je laisse l'IA d?cider ? ma place.","Je copie la r?ponse sans v?rifier."],
    expected: ["A"],
    comparator: "mcq_exact",
    hint: "Cherche la r?ponse qui garde m?thode, jugement et responsabilit? humaine.",
    explanation: "Bonne r?ponse : Je sais documenter ce que l'IA a produit et ce que j'ai modifi?.",
  },
  {
    kind: "fixed",
    id: "ia_b2_documenter_role_ia_qcm_002",
    niveau: "b2",
    matiere: "ia",
    notionId: "ia_b2_production",
    microId: "ia_b2_documenter_role_ia",
    difficulty: 3,
    text: "Dans une situation r?elle, quelle action correspond le mieux ? : Je sais documenter ce que l'IA a produit et ce que j'ai modifi?.",
    format: "qcm",
    choices: ["Je sais documenter ce que l'IA a produit et ce que j'ai modifi?.","Partager des informations sensibles pour aller plus vite.","Faire confiance ? une seule r?ponse sans recul."],
    expected: ["A"],
    comparator: "mcq_exact",
    hint: "L'IA est un outil : l'?l?ve garde l'objectif, la v?rification et la d?cision.",
    explanation: "Cette micro-comp?tence se valide quand l'?l?ve sait faire ceci : Je sais documenter ce que l'IA a produit et ce que j'ai modifi?.",
  },
];

export function getIaB2QuestionBank(args?: {
  notionId?: string | null;
  microId?: string | null;
}): TutorBankItemV4[] {
  let bank = iaB2QuestionBank;

  if (args?.notionId) bank = bank.filter((item) => item.notionId === args.notionId);
  if (args?.microId) bank = bank.filter((item) => item.microId === args.microId);

  return bank;
}
