import type { CoachBrevetProblem } from "../types";

export const sujetsExpressBank: CoachBrevetProblem[] = [
  {
    id: "brevet-se-001",
    title: "Sujet express 1 — Calcul et algèbre",
    notions: ["fractions", "puissances", "calcul_litteral", "equations"],
    difficulty: 2,
    durationMinutes: 30,
    intro: "Mini-sujet chronométré — semaine 1. Fais sans calculatrice.",
    steps: [
      {
        id: "brevet-se-001-s1",
        text: "Calcule : 2/3 + 5/6 − 1/2",
        format: "short",
        expected: ["1", "6/6"],
        hint: "Dénominateur commun = 6.",
        explanation: "4/6 + 5/6 − 3/6 = 6/6 = 1.",
      },
      {
        id: "brevet-se-001-s2",
        text: "Développe et réduis : (2x − 1)(x + 3)",
        format: "short",
        expected: ["2x²+5x-3", "2x² + 5x − 3"],
        hint: "Utilise la distributivité double.",
        explanation: "2x² + 6x − x − 3 = 2x² + 5x − 3.",
      },
      {
        id: "brevet-se-001-s3",
        text: "Résous : 4(x − 2) + x = 3x + 6",
        format: "short",
        expected: ["7"],
        hint: "Développe puis regroupe.",
        explanation: "4x − 8 + x = 3x + 6 → 5x − 8 = 3x + 6 → 2x = 14 → x = 7.",
      },
      {
        id: "brevet-se-001-s4",
        text: "Écris 0,000 032 en notation scientifique.",
        format: "short",
        expected: ["3.2×10^-5", "3,2×10⁻⁵"],
        hint: "Déplace la virgule de 5 rangs vers la droite.",
        explanation: "3,2 × 10⁻⁵.",
      },
    ],
  },
  {
    id: "brevet-se-002",
    title: "Sujet express 2 — Géométrie",
    notions: ["pythagore", "trigonometrie", "thales", "geometrie_espace"],
    difficulty: 2,
    durationMinutes: 30,
    intro: "Mini-sujet géométrie — semaine 2. Formules autorisées.",
    steps: [
      {
        id: "brevet-se-002-s1",
        text: "Un triangle rectangle a des côtés 5 et 12. Calcule l'hypoténuse.",
        format: "short",
        expected: ["13"],
        hint: "5² + 12² = ?",
        explanation: "25 + 144 = 169 = 13².",
      },
      {
        id: "brevet-se-002-s2",
        text: "Dans un triangle rectangle, l'hypoténuse est 20 cm et un angle aigu est 60°. Calcule le côté adjacent à cet angle. (cos 60° = 0,5)",
        format: "short",
        expected: ["10"],
        hint: "côté adjacent = hypoténuse × cos(angle).",
        explanation: "20 × 0,5 = 10 cm.",
      },
      {
        id: "brevet-se-002-s3",
        text: "Calcule le volume d'une sphère de rayon 3 cm. (V = 4/3 × π × r³, π ≈ 3,14)",
        format: "short",
        expected: ["113.04", "113,04"],
        hint: "V = 4/3 × 3,14 × 27",
        explanation: "V = 4/3 × 3,14 × 27 = 4 × 3,14 × 9 = 113,04 cm³.",
      },
    ],
  },
  {
    id: "brevet-se-003",
    title: "Sujet express 3 — Fonctions et stats",
    notions: ["fonctions", "statistiques", "probabilites"],
    difficulty: 3,
    durationMinutes: 30,
    intro: "Mini-sujet fonctions et données — semaine 3.",
    steps: [
      {
        id: "brevet-se-003-s1",
        text: "f(x) = 3x − 5. Pour quelle valeur x a-t-on f(x) = 0 ?",
        format: "short",
        expected: ["5/3", "1.67"],
        hint: "Résous 3x − 5 = 0.",
        explanation: "3x = 5 → x = 5/3 ≈ 1,67.",
      },
      {
        id: "brevet-se-003-s2",
        text: "Série : 5, 8, 6, 9, 7, 11, 6. Calcule la moyenne et la médiane.",
        format: "open",
        hint: "Trie d'abord pour la médiane.",
        explanation: "Moyenne = 52/7 ≈ 7,43. Série triée : 5,6,6,7,8,9,11 → Médiane = 7.",
      },
      {
        id: "brevet-se-003-s3",
        text: "Un jeu de 32 cartes : quelle est la probabilité de tirer un as ?",
        format: "short",
        expected: ["1/8", "4/32", "0.125"],
        hint: "Il y a 4 as dans 32 cartes.",
        explanation: "P = 4/32 = 1/8.",
      },
    ],
  },
  {
    id: "brevet-se-004",
    title: "Grand sujet final — Bilan complet",
    notions: ["equations", "pythagore", "probabilites", "pourcentages", "fonctions"],
    difficulty: 3,
    durationMinutes: 45,
    intro:
      "Sujet final toutes notions — simule les conditions du brevet. Calculatrice autorisée pour la partie 2.",
    steps: [
      {
        id: "brevet-se-004-s1",
        text: "PARTIE 1 (sans calculatrice). Factorise : x² − 16",
        format: "short",
        expected: ["(x-4)(x+4)", "(x+4)(x-4)"],
        hint: "Identité a² − b² = (a−b)(a+b).",
        explanation: "(x−4)(x+4).",
      },
      {
        id: "brevet-se-004-s2",
        text: "PARTIE 2 (calculatrice). Un capital de 1 000 € est placé à 3 % par an. Quel est le capital après 4 ans ? (arrondi à l'euro)",
        format: "short",
        expected: ["1126", "1125.51"],
        hint: "Capital × 1,03⁴",
        explanation: "1000 × 1,03⁴ = 1000 × 1,1255 ≈ 1125,51 € soit 1 126 €.",
      },
      {
        id: "brevet-se-004-s3",
        text: "Un triangle ABC rectangle en C a AC = 7 cm et BC = 24 cm. Calcule AB et l'angle en A (sin A = BC/AB, sin⁻¹(0,9231) ≈ 67,4°).",
        format: "open",
        hint: "AB via Pythagore, puis sin(A) = BC/AB.",
        explanation: "AB = 25 cm. sin(A) = 24/25 = 0,96 → A ≈ 73,7°.",
      },
      {
        id: "brevet-se-004-s4",
        text: "Conclusion personnelle : cite deux notions du brevet où tu te sens encore fragile.",
        format: "open",
        hint: "Réponse libre — introspection.",
        explanation: "À toi de jouer ! Identifie tes points faibles pour les réviser en priorité.",
      },
    ],
  },
];
