// lib/tutor-v4/apercus.generated.ts
//
// ⚠️ FICHIER GÉNÉRÉ — ne pas modifier à la main.
//     npm run capturer:apercus-coach -- http://localhost:3000 --tout
//
// Les notions qui ont un aperçu dans public/apercus/coach/, et le nombre
// d'écrans de chacune. La clé est « matiere/classe/notion » : un identifiant de
// notion n'est unique qu'à l'intérieur d'une classe.
//
// Une notion absente d'ici n'ouvre pas de fenêtre au survol — sa ligne reste
// exactement ce qu'elle était.

export const APERCUS_COACH: Readonly<Record<string, number>> = {
  "francais/5e/conjugaison_formes": 2,
  "francais/5e/conjugaison_temps": 2,
  "francais/5e/conjugaison_valeurs": 2,
  "francais/5e/culture_connaissances": 2,
  "francais/5e/culture_entrees_5e": 2,
  "francais/5e/discours_paroles_rapportees": 2,
  "francais/5e/discours_registres": 2,
  "francais/5e/ecriture_produire": 2,
  "francais/5e/ecriture_reflechir": 2,
  "francais/5e/ecriture_reviser": 2,
  "francais/5e/grammaire_fonctions": 2,
  "francais/5e/grammaire_groupe_nominal": 2,
  "francais/5e/grammaire_phrase": 2,
  "francais/5e/grammaire_reprises": 2,
  "francais/5e/lecture_apprecier": 2,
  "francais/5e/lecture_comprehension": 2,
  "francais/5e/lecture_oeuvre_contextes": 2,
  "francais/5e/lecture_voix_haute": 2,
  "francais/5e/oral_dire_jouer": 2,
  "francais/5e/oral_ecouter": 2,
  "francais/5e/oral_prendre_parole": 2,
  "francais/5e/orthographe_accords": 2,
  "francais/5e/orthographe_participe": 2,
  "francais/5e/vocabulaire_enrichir": 2,
  "francais/5e/vocabulaire_formation": 2,
  "francais/5e/vocabulaire_jouer": 2,
  "francais/5e/vocabulaire_orthographe": 2,
  "francais/5e/vocabulaire_relations": 2,
  "maths/5e/aire_surface": 2,
  "maths/5e/algo_construire": 2,
  "maths/5e/algo_programmation": 2,
  "maths/5e/angle_mesure": 2,
  "maths/5e/divisibilite": 2,
  "maths/5e/fraction_calcul": 2,
  "maths/5e/fraction_nombre": 2,
  "maths/5e/grandeur_conversion": 2,
  "maths/5e/litteral_calcul": 2,
  "maths/5e/parallelogramme": 2,
  "maths/5e/proba_experience": 2,
  "maths/5e/prop_proportionnalite": 2,
  "maths/5e/prop_ratio_pourcentage": 2,
  "maths/5e/relatif_nombre": 2,
  "maths/5e/relatif_operation": 2,
  "maths/5e/stat_statistique": 2,
  "maths/5e/sym_centrale": 2,
  "maths/5e/triangle_figure": 2,
  "maths/5e/volume_solide": 2,
  "maths/premiere/alea_arbre": 2,
  "maths/premiere/alea_arbre_calcul": 2,
  "maths/premiere/alea_bernoulli": 2,
  "maths/premiere/alea_bernoulli_calcul": 2,
  "maths/premiere/alea_conditionnelle": 2,
  "maths/premiere/alea_conditionnelle_calcul": 2,
  "maths/premiere/alea_independance": 2,
  "maths/premiere/auto_coefficient_multiplicateur": 2,
  "maths/premiere/auto_droites": 2,
  "maths/premiere/auto_formules": 2,
  "maths/premiere/auto_indicateurs": 2,
  "maths/premiere/auto_lecture_graphique": 2,
  "maths/premiere/auto_ordres_unites": 2,
  "maths/premiere/auto_resolution_graphique": 2,
  "maths/premiere/auto_taux_evolution": 2,
  "maths/premiere/der_formules": 2,
  "maths/premiere/der_polynome": 2,
  "maths/premiere/expo_fonction_lecture": 2,
  "maths/premiere/expo_suite_geometrique": 2,
  "maths/premiere/expo_suite_terme_general": 2,
  "maths/premiere/expo_taux_moyen": 2,
  "maths/premiere/info_ajustement_affine": 2,
  "maths/premiere/info_point_moyen": 2,
  "maths/premiere/info_representations_croisees": 2,
  "maths/premiere/info_tableur": 2,
  "maths/premiere/lin_suite_arithmetique": 2,
  "maths/premiere/lin_suite_terme_general": 2,
  "maths/premiere/quad_parabole": 2,
  "maths/premiere/quad_racines_signe": 2,
  "maths/premiere-spe/algorithmique": 2,
  "maths/premiere-spe/derivation": 2,
  "maths/premiere-spe/exponentielle": 2,
  "maths/premiere-spe/geometrie_reperee": 2,
  "maths/premiere-spe/logique_ensembles": 2,
  "maths/premiere-spe/probabilites_conditionnelles": 2,
  "maths/premiere-spe/produit_scalaire": 2,
  "maths/premiere-spe/second_degre": 2,
  "maths/premiere-spe/suites": 2,
  "maths/premiere-spe/trigonometrie": 2,
  "maths/premiere-spe/variables_aleatoires": 2,
  "maths/premiere-spe/variations_fonctions": 2,
  "maths/stmg/auto_developper_factoriser": 2,
  "maths/stmg/auto_equations": 2,
  "maths/stmg/auto_evo_coefficient": 2,
  "maths/stmg/auto_evo_enchainees": 2,
  "maths/stmg/auto_evo_taux": 2,
  "maths/stmg/auto_formules": 2,
  "maths/stmg/auto_fractions_puissances": 2,
  "maths/stmg/auto_indice": 2,
  "maths/stmg/auto_ordres_unites": 2,
  "maths/stmg/auto_proportion": 2,
  "maths/stmg/auto_signes": 2,
  "maths/stmg/proba_arbre": 2,
  "maths/stmg/proba_arbre_calcul": 2,
  "maths/stmg/proba_conditionnelle_distinguer": 2,
  "maths/stmg/proba_conditionnelle_tableau": 2,
  "maths/stmg/proba_epreuves_independantes": 2,
  "maths/stmg/proba_independance": 2,
  "maths/stmg/stat_changement_variable": 2,
  "maths/stmg/stat_interpoler": 2,
  "maths/stmg/stat_moindres_carres": 2,
  "maths/stmg/va_bernoulli": 2,
  "maths/stmg/va_esperance": 2,
  "maths/stmg/va_loi_probabilite": 2,
  "maths/terminale-spe/algorithmique_python": 2,
  "maths/terminale-spe/concentration_echantillonnage": 2,
  "maths/terminale-spe/continuite_tvi": 2,
  "maths/terminale-spe/convexite_fonction": 2,
  "maths/terminale-spe/denombrement_combinatoire": 2,
  "maths/terminale-spe/derivation_fonction": 2,
  "maths/terminale-spe/equation_differentielle": 2,
  "maths/terminale-spe/fonction_exponentielle": 2,
  "maths/terminale-spe/fonction_logarithme": 2,
  "maths/terminale-spe/geometrie_espace": 2,
  "maths/terminale-spe/limite_fonction": 2,
  "maths/terminale-spe/limite_suite": 2,
  "maths/terminale-spe/loi_binomiale": 2,
  "maths/terminale-spe/primitive_integrale": 2,
  "maths/terminale-spe/probabilite_conditionnelle": 2,
  "maths/terminale-spe/produit_scalaire_espace": 2,
  "maths/terminale-spe/suite_numerique": 2,
  "maths/terminale-spe/variable_aleatoire": 2,
};

/** Le chemin de l'aperçu d'une notion, ou `null` si elle n'en a pas. */
export function apercuNotion(
  matiere: string,
  classe: string,
  notion: string,
): { src: string; ecrans: number } | null {
  const cle = `${matiere}/${classe}/${notion}`;
  const ecrans = APERCUS_COACH[cle];
  if (!ecrans) return null;
  return { src: `/apercus/coach/${cle}.${ecrans}.webp`, ecrans };
}
