import type { TutorBankItemV4 } from "@/lib/tutor-v4/types";

const WORDS = [
  { slug: "globalizacion", es: "globalización", fr: "mondialisation", notionId: "es_b2_economics",   audio: "/audio/espagnol/economics/b2/globalizacion.mp3" },
  { slug: "desigualdad",   es: "desigualdad",   fr: "inégalité",       notionId: "es_b2_economics",   audio: "/audio/espagnol/economics/b2/desigualdad.mp3"   },
  { slug: "democracia",    es: "democracia",    fr: "démocratie",      notionId: "es_b2_geopolitics", audio: "/audio/espagnol/geopolitics/b2/democracia.mp3"   },
  { slug: "dictadura",     es: "dictadura",     fr: "dictature",       notionId: "es_b2_geopolitics", audio: "/audio/espagnol/geopolitics/b2/dictadura.mp3"    },
  { slug: "inmigracion",   es: "inmigración",   fr: "immigration",     notionId: "es_b2_geopolitics", audio: "/audio/espagnol/geopolitics/b2/inmigracion.mp3"  },
  { slug: "literatura",    es: "literatura",    fr: "littérature",     notionId: "es_b2_literature",  audio: "/audio/espagnol/literature/b2/literatura.mp3"    },
  { slug: "poesia",        es: "poesía",         fr: "poésie",          notionId: "es_b2_literature",  audio: "/audio/espagnol/literature/b2/poesia.mp3"        },
  { slug: "etica",         es: "ética",          fr: "éthique",         notionId: "es_b2_philosophy",  audio: "/audio/espagnol/philosophy/b2/etica.mp3"         },
  { slug: "libertad",      es: "libertad",      fr: "liberté",         notionId: "es_b2_philosophy",  audio: "/audio/espagnol/philosophy/b2/libertad.mp3"      },
  { slug: "justicia",      es: "justicia",      fr: "justice",         notionId: "es_b2_philosophy",  audio: "/audio/espagnol/philosophy/b2/justicia.mp3"      },
  // Macroéconomie
  { slug: "inflacion",         es: "inflación",               fr: "inflation",              notionId: "es_b2_macroeconomics", audio: "/audio/espagnol/macroeconomics/b2/inflacion.mp3"         },
  { slug: "desempleo",         es: "desempleo",               fr: "chômage",                notionId: "es_b2_macroeconomics", audio: "/audio/espagnol/macroeconomics/b2/desempleo.mp3"         },
  { slug: "crecimiento",       es: "crecimiento",             fr: "croissance",             notionId: "es_b2_macroeconomics", audio: "/audio/espagnol/macroeconomics/b2/crecimiento.mp3"       },
  { slug: "pib",               es: "producto interior bruto", fr: "produit intérieur brut", notionId: "es_b2_macroeconomics", audio: "/audio/espagnol/macroeconomics/b2/pib.mp3"               },
  { slug: "deuda_publica",     es: "deuda pública",           fr: "dette publique",         notionId: "es_b2_macroeconomics", audio: "/audio/espagnol/macroeconomics/b2/deuda_publica.mp3"     },
  { slug: "exportacion",       es: "exportación",             fr: "exportation",            notionId: "es_b2_macroeconomics", audio: "/audio/espagnol/macroeconomics/b2/exportacion.mp3"       },
  { slug: "importacion",       es: "importación",             fr: "importation",            notionId: "es_b2_macroeconomics", audio: "/audio/espagnol/macroeconomics/b2/importacion.mp3"       },
  { slug: "mercado_laboral",   es: "mercado laboral",         fr: "marché du travail",      notionId: "es_b2_macroeconomics", audio: "/audio/espagnol/macroeconomics/b2/mercado_laboral.mp3"   },
  { slug: "crisis",            es: "crisis",                  fr: "crise",                  notionId: "es_b2_macroeconomics", audio: "/audio/espagnol/macroeconomics/b2/crisis.mp3"            },
  { slug: "poder_adquisitivo", es: "poder adquisitivo",       fr: "pouvoir d'achat",        notionId: "es_b2_macroeconomics", audio: "/audio/espagnol/macroeconomics/b2/poder_adquisitivo.mp3" },
  // Géographie & démographie
  { slug: "poblacion",         es: "población",               fr: "population",             notionId: "es_b2_geo_statistics", audio: "/audio/espagnol/geo_statistics/b2/poblacion.mp3"         },
  { slug: "densidad",          es: "densidad",                fr: "densité",                notionId: "es_b2_geo_statistics", audio: "/audio/espagnol/geo_statistics/b2/densidad.mp3"          },
  { slug: "urbanizacion",      es: "urbanización",            fr: "urbanisation",           notionId: "es_b2_geo_statistics", audio: "/audio/espagnol/geo_statistics/b2/urbanizacion.mp3"      },
  { slug: "migracion",         es: "migración",               fr: "migration",              notionId: "es_b2_geo_statistics", audio: "/audio/espagnol/geo_statistics/b2/migracion.mp3"         },
  { slug: "natalidad",         es: "natalidad",               fr: "natalité",               notionId: "es_b2_geo_statistics", audio: "/audio/espagnol/geo_statistics/b2/natalidad.mp3"         },
  { slug: "mortalidad",        es: "mortalidad",              fr: "mortalité",              notionId: "es_b2_geo_statistics", audio: "/audio/espagnol/geo_statistics/b2/mortalidad.mp3"        },
  { slug: "esperanza_de_vida", es: "esperanza de vida",       fr: "espérance de vie",       notionId: "es_b2_geo_statistics", audio: "/audio/espagnol/geo_statistics/b2/esperanza_de_vida.mp3" },
  { slug: "censo",             es: "censo",                   fr: "recensement",            notionId: "es_b2_geo_statistics", audio: "/audio/espagnol/geo_statistics/b2/censo.mp3"             },
  { slug: "demografia",        es: "demografía",              fr: "démographie",            notionId: "es_b2_geo_statistics", audio: "/audio/espagnol/geo_statistics/b2/demografia.mp3"        },
  { slug: "exodo_rural",       es: "éxodo rural",             fr: "exode rural",            notionId: "es_b2_geo_statistics", audio: "/audio/espagnol/geo_statistics/b2/exodo_rural.mp3"       },
  // Science du climat
  { slug: "efecto_invernadero",   es: "efecto invernadero",   fr: "effet de serre",            notionId: "es_b2_climate_science", audio: "/audio/espagnol/climate_science/b2/efecto_invernadero.mp3"   },
  { slug: "calentamiento_global", es: "calentamiento global", fr: "réchauffement climatique",  notionId: "es_b2_climate_science", audio: "/audio/espagnol/climate_science/b2/calentamiento_global.mp3" },
  { slug: "emisiones",            es: "emisiones",            fr: "émissions",                 notionId: "es_b2_climate_science", audio: "/audio/espagnol/climate_science/b2/emisiones.mp3"            },
  { slug: "combustibles_fosiles", es: "combustibles fósiles", fr: "combustibles fossiles",     notionId: "es_b2_climate_science", audio: "/audio/espagnol/climate_science/b2/combustibles_fosiles.mp3" },
  { slug: "energia_renovable",    es: "energía renovable",    fr: "énergie renouvelable",      notionId: "es_b2_climate_science", audio: "/audio/espagnol/climate_science/b2/energia_renovable.mp3"    },
  { slug: "sequia",               es: "sequía",               fr: "sécheresse",                notionId: "es_b2_climate_science", audio: "/audio/espagnol/climate_science/b2/sequia.mp3"               },
  { slug: "deshielo",             es: "deshielo",             fr: "fonte des glaces",          notionId: "es_b2_climate_science", audio: "/audio/espagnol/climate_science/b2/deshielo.mp3"             },
  { slug: "huella_de_carbono",    es: "huella de carbono",    fr: "empreinte carbone",         notionId: "es_b2_climate_science", audio: "/audio/espagnol/climate_science/b2/huella_de_carbono.mp3"    },
  { slug: "biodiversidad",        es: "biodiversidad",        fr: "biodiversité",              notionId: "es_b2_climate_science", audio: "/audio/espagnol/climate_science/b2/biodiversidad.mp3"        },
  { slug: "sostenibilidad",       es: "sostenibilidad",       fr: "durabilité",                notionId: "es_b2_climate_science", audio: "/audio/espagnol/climate_science/b2/sostenibilidad.mp3"       },
  // Science du sport
  { slug: "resistencia",          es: "resistencia",          fr: "endurance",                 notionId: "es_b2_sport_science", audio: "/audio/espagnol/sport_science/b2/resistencia.mp3"         },
  { slug: "fuerza",               es: "fuerza",               fr: "force",                     notionId: "es_b2_sport_science", audio: "/audio/espagnol/sport_science/b2/fuerza.mp3"              },
  { slug: "nutricion",            es: "nutrición",            fr: "nutrition",                 notionId: "es_b2_sport_science", audio: "/audio/espagnol/sport_science/b2/nutricion.mp3"           },
  { slug: "hidratacion",          es: "hidratación",          fr: "hydratation",               notionId: "es_b2_sport_science", audio: "/audio/espagnol/sport_science/b2/hidratacion.mp3"         },
  { slug: "lesion",               es: "lesión",               fr: "blessure",                  notionId: "es_b2_sport_science", audio: "/audio/espagnol/sport_science/b2/lesion.mp3"              },
  { slug: "recuperacion",         es: "recuperación",         fr: "récupération",              notionId: "es_b2_sport_science", audio: "/audio/espagnol/sport_science/b2/recuperacion.mp3"        },
  { slug: "frecuencia_cardiaca",  es: "frecuencia cardíaca",  fr: "fréquence cardiaque",       notionId: "es_b2_sport_science", audio: "/audio/espagnol/sport_science/b2/frecuencia_cardiaca.mp3" },
  { slug: "potencia",             es: "potencia",             fr: "puissance",                 notionId: "es_b2_sport_science", audio: "/audio/espagnol/sport_science/b2/potencia.mp3"            },
  { slug: "dopaje",               es: "dopaje",               fr: "dopage",                    notionId: "es_b2_sport_science", audio: "/audio/espagnol/sport_science/b2/dopaje.mp3"              },
  { slug: "fisiologia",           es: "fisiología",           fr: "physiologie",               notionId: "es_b2_sport_science", audio: "/audio/espagnol/sport_science/b2/fisiologia.mp3"          },
  // Économie & mondialisation (complément)
  { slug: "pobreza",         es: "pobreza",          fr: "pauvreté",            notionId: "es_b2_economics",   audio: "/audio/espagnol/economics/b2/pobreza.mp3"         },
  { slug: "riqueza",         es: "riqueza",          fr: "richesse",            notionId: "es_b2_economics",   audio: "/audio/espagnol/economics/b2/riqueza.mp3"         },
  { slug: "desarrollo",      es: "desarrollo",       fr: "développement",       notionId: "es_b2_economics",   audio: "/audio/espagnol/economics/b2/desarrollo.mp3"      },
  { slug: "comercio_justo",  es: "comercio justo",   fr: "commerce équitable",  notionId: "es_b2_economics",   audio: "/audio/espagnol/economics/b2/comercio_justo.mp3"  },
  { slug: "multinacional",   es: "multinacional",    fr: "multinationale",      notionId: "es_b2_economics",   audio: "/audio/espagnol/economics/b2/multinacional.mp3"   },
  { slug: "deslocalizacion", es: "deslocalización",  fr: "délocalisation",      notionId: "es_b2_economics",   audio: "/audio/espagnol/economics/b2/deslocalizacion.mp3" },
  { slug: "consumismo",      es: "consumismo",       fr: "consumérisme",        notionId: "es_b2_economics",   audio: "/audio/espagnol/economics/b2/consumismo.mp3"      },
  { slug: "bienestar",       es: "bienestar",        fr: "bien-être",           notionId: "es_b2_economics",   audio: "/audio/espagnol/economics/b2/bienestar.mp3"       },
  // Géopolitique (complément)
  { slug: "elecciones",       es: "elecciones",       fr: "élections",          notionId: "es_b2_geopolitics", audio: "/audio/espagnol/geopolitics/b2/elecciones.mp3"       },
  { slug: "gobierno",         es: "gobierno",         fr: "gouvernement",       notionId: "es_b2_geopolitics", audio: "/audio/espagnol/geopolitics/b2/gobierno.mp3"         },
  { slug: "derechos_humanos", es: "derechos humanos", fr: "droits de l'homme",  notionId: "es_b2_geopolitics", audio: "/audio/espagnol/geopolitics/b2/derechos_humanos.mp3" },
  { slug: "conflicto",        es: "conflicto",        fr: "conflit",            notionId: "es_b2_geopolitics", audio: "/audio/espagnol/geopolitics/b2/conflicto.mp3"        },
  { slug: "paz",              es: "paz",              fr: "paix",               notionId: "es_b2_geopolitics", audio: "/audio/espagnol/geopolitics/b2/paz.mp3"              },
  { slug: "tratado",          es: "tratado",          fr: "traité",             notionId: "es_b2_geopolitics", audio: "/audio/espagnol/geopolitics/b2/tratado.mp3"          },
  { slug: "soberania",        es: "soberanía",        fr: "souveraineté",       notionId: "es_b2_geopolitics", audio: "/audio/espagnol/geopolitics/b2/soberania.mp3"        },
  // Littérature (complément)
  { slug: "novela",          es: "novela",           fr: "roman",               notionId: "es_b2_literature",  audio: "/audio/espagnol/literature/b2/novela.mp3"    },
  { slug: "cuento",          es: "cuento",           fr: "conte",               notionId: "es_b2_literature",  audio: "/audio/espagnol/literature/b2/cuento.mp3"    },
  { slug: "ensayo",          es: "ensayo",           fr: "essai",               notionId: "es_b2_literature",  audio: "/audio/espagnol/literature/b2/ensayo.mp3"    },
  { slug: "personaje",       es: "personaje",        fr: "personnage",          notionId: "es_b2_literature",  audio: "/audio/espagnol/literature/b2/personaje.mp3" },
  { slug: "narrador",        es: "narrador",         fr: "narrateur",           notionId: "es_b2_literature",  audio: "/audio/espagnol/literature/b2/narrador.mp3"  },
  { slug: "metafora",        es: "metáfora",         fr: "métaphore",           notionId: "es_b2_literature",  audio: "/audio/espagnol/literature/b2/metafora.mp3"  },
  { slug: "obra",            es: "obra",             fr: "œuvre",               notionId: "es_b2_literature",  audio: "/audio/espagnol/literature/b2/obra.mp3"      },
  { slug: "autor",           es: "autor",            fr: "auteur",              notionId: "es_b2_literature",  audio: "/audio/espagnol/literature/b2/autor.mp3"     },
  // Philosophie (complément)
  { slug: "moral",           es: "moral",            fr: "morale",              notionId: "es_b2_philosophy",  audio: "/audio/espagnol/philosophy/b2/moral.mp3"      },
  { slug: "conciencia",      es: "conciencia",       fr: "conscience",          notionId: "es_b2_philosophy",  audio: "/audio/espagnol/philosophy/b2/conciencia.mp3" },
  { slug: "verdad",          es: "verdad",           fr: "vérité",              notionId: "es_b2_philosophy",  audio: "/audio/espagnol/philosophy/b2/verdad.mp3"     },
  { slug: "sabiduria",       es: "sabiduría",        fr: "sagesse",             notionId: "es_b2_philosophy",  audio: "/audio/espagnol/philosophy/b2/sabiduria.mp3"  },
  { slug: "voluntad",        es: "voluntad",         fr: "volonté",             notionId: "es_b2_philosophy",  audio: "/audio/espagnol/philosophy/b2/voluntad.mp3"   },
  { slug: "deber",           es: "deber",            fr: "devoir",              notionId: "es_b2_philosophy",  audio: "/audio/espagnol/philosophy/b2/deber.mp3"      },
  { slug: "felicidad",       es: "felicidad",        fr: "bonheur",             notionId: "es_b2_philosophy",  audio: "/audio/espagnol/philosophy/b2/felicidad.mp3"  },
] as const;

function dFr(exclude: string) { return WORDS.filter(w => w.fr !== exclude).map(w => w.fr).slice(0, 3); }
function dEs(exclude: string) { return WORDS.filter(w => w.es !== exclude).map(w => w.es).slice(0, 3); }

export const espagnolB2QuestionBank: TutorBankItemV4[] = WORDS.flatMap((word) => [
  {
    kind: "fixed" as const,
    id: `es_b2_${word.slug}_es_to_fr`,
    niveau: "b2" as const,
    matiere: "espagnol" as const,
    notionId: word.notionId,
    microId: `${word.notionId}_es_to_fr`,
    difficulty: 3 as const,
    text: `Que signifie "${word.es}" en français ?`,
    format: "qcm" as const,
    choices: [word.fr, ...dFr(word.fr)],
    expected: [word.fr],
    comparator: "mcq_exact" as const,
    explanation: `"${word.es}" = "${word.fr}".`,
  },
  {
    kind: "fixed" as const,
    id: `es_b2_${word.slug}_fr_to_es`,
    niveau: "b2" as const,
    matiere: "espagnol" as const,
    notionId: word.notionId,
    microId: `${word.notionId}_fr_to_es`,
    difficulty: 4 as const,
    text: `Comment dit-on "${word.fr}" en espagnol ?`,
    format: "qcm" as const,
    choices: [word.es, ...dEs(word.es)],
    expected: [word.es],
    comparator: "mcq_exact" as const,
    explanation: `"${word.fr}" se dit "${word.es}" en espagnol.`,
  },
  {
    kind: "fixed" as const,
    id: `es_b2_${word.slug}_listen`,
    niveau: "b2" as const,
    matiere: "espagnol" as const,
    notionId: word.notionId,
    microId: `${word.notionId}_listen`,
    difficulty: 4 as const,
    text: `🔊 Écoute et choisis la traduction française.`,
    format: "qcm" as const,
    audioSrc: word.audio,
    choices: [word.fr, ...dFr(word.fr)],
    expected: [word.fr],
    comparator: "mcq_exact" as const,
    hint: `Écoute attentivement la prononciation.`,
    explanation: `Le mot entendu est "${word.es}" (${word.fr}).`,
  },
]);
