import type { MicroSkillSource } from "@/lib/tutor-v4/knowledge/buildKnowledge";

export const microSkills: MicroSkillSource[] = [
  { id: "reels_ensembles", label: "Distinguer les ensembles N, Z, D, Q et R", notionId: "reels_intervalles", prerequis: [] },
  { id: "reels_droite_graduee", label: "Associer un reel a un point de la droite graduee", notionId: "reels_intervalles", prerequis: ["reels_ensembles"] },
  { id: "intervalle_representer", label: "Representer un intervalle sur une droite", notionId: "reels_intervalles", prerequis: ["reels_droite_graduee"] },
  { id: "intervalle_appartenance", label: "Determiner si un nombre appartient a un intervalle", notionId: "reels_intervalles", prerequis: ["intervalle_representer"] },
  { id: "valeur_absolue_distance", label: "Interpretrer la valeur absolue comme une distance", notionId: "reels_intervalles", prerequis: ["intervalle_appartenance"] },
  { id: "reels_encadrement", label: "Donner un encadrement decimal d'un reel", notionId: "reels_intervalles", prerequis: ["reels_ensembles"] },
  { id: "arith_multiple_diviseur", label: "Utiliser multiple, diviseur, pair et impair", notionId: "arithmetique_entiers", prerequis: [] },
  { id: "arith_nombre_premier", label: "Reconnaitre un nombre premier", notionId: "arithmetique_entiers", prerequis: ["arith_multiple_diviseur"] },
  { id: "arith_fraction_irreductible", label: "Rendre une fraction irreductible", notionId: "arithmetique_entiers", prerequis: ["arith_multiple_diviseur"] },
  { id: "arith_probleme", label: "Modeliser un probleme avec multiples et diviseurs", notionId: "arithmetique_entiers", prerequis: ["arith_nombre_premier", "arith_fraction_irreductible"] },
  { id: "litteral_puissances_racines", label: "Utiliser les puissances et racines carrees", notionId: "calcul_litteral_2de", prerequis: ["reels_ensembles"] },
  { id: "litteral_developper", label: "Developper une expression litterale", notionId: "calcul_litteral_2de", prerequis: ["litteral_puissances_racines"] },
  { id: "litteral_factoriser", label: "Factoriser avec un facteur commun ou une identite", notionId: "calcul_litteral_2de", prerequis: ["litteral_developper"] },
  { id: "litteral_identites", label: "Utiliser les identites remarquables", notionId: "calcul_litteral_2de", prerequis: ["litteral_factoriser"] },
  { id: "litteral_modeliser", label: "Modeliser une situation par une expression", notionId: "calcul_litteral_2de", prerequis: ["litteral_developper"] },
  { id: "equation_resoudre", label: "Resoudre une equation du premier degre", notionId: "equations_inequations_1er_degre", prerequis: ["litteral_developper"] },
  { id: "equation_probleme", label: "Mettre un probleme en equation", notionId: "equations_inequations_1er_degre", prerequis: ["equation_resoudre", "litteral_modeliser"] },
  { id: "inequation_resoudre", label: "Resoudre une inequation du premier degre", notionId: "equations_inequations_1er_degre", prerequis: ["equation_resoudre", "intervalle_representer"] },
  { id: "inequation_intervalle", label: "Traduire une inequation en intervalle de solutions", notionId: "equations_inequations_1er_degre", prerequis: ["inequation_resoudre", "intervalle_appartenance"] },
  { id: "vecteur_definition", label: "Comprendre direction, sens et norme d'un vecteur", notionId: "vecteurs_plan", prerequis: [] },
  { id: "vecteur_egalite", label: "Reconnaitre deux vecteurs egaux", notionId: "vecteurs_plan", prerequis: ["vecteur_definition"] },
  { id: "vecteur_somme", label: "Construire la somme de deux vecteurs", notionId: "vecteurs_plan", prerequis: ["vecteur_egalite"] },
  { id: "vecteur_coordonnees", label: "Calculer les coordonnees d'un vecteur", notionId: "vecteurs_plan", prerequis: ["repere_coordonnees_point"] },
  { id: "repere_coordonnees_point", label: "Lire et placer un point dans un repere", notionId: "repere_coordonnees", prerequis: [] },
  { id: "repere_milieu", label: "Calculer les coordonnees d'un milieu", notionId: "repere_coordonnees", prerequis: ["repere_coordonnees_point"] },
  { id: "repere_distance", label: "Calculer une distance dans un repere orthonorme", notionId: "repere_coordonnees", prerequis: ["repere_coordonnees_point"] },
  { id: "droite_pente_ordonne", label: "Lire pente et ordonnee a l'origine", notionId: "droites_plan", prerequis: ["repere_coordonnees_point"] },
  { id: "droite_equation_reduite", label: "Determiner une equation reduite de droite", notionId: "droites_plan", prerequis: ["droite_pente_ordonne", "equation_resoudre"] },
  { id: "droite_parallelisme", label: "Exploiter le coefficient directeur pour le parallelisme", notionId: "droites_plan", prerequis: ["droite_equation_reduite"] },
  { id: "droite_intersection", label: "Trouver l'intersection de deux droites", notionId: "droites_plan", prerequis: ["droite_equation_reduite", "equation_resoudre"] },
  { id: "espace_solides", label: "Reconnaitre solides usuels et sections simples", notionId: "geometrie_espace_2de", prerequis: [] },
  { id: "espace_representation", label: "Lire une representation en perspective", notionId: "geometrie_espace_2de", prerequis: ["espace_solides"] },
  { id: "espace_positions", label: "Decrire positions relatives de droites et plans", notionId: "geometrie_espace_2de", prerequis: ["espace_representation"] },
  { id: "fonction_vocabulaire", label: "Utiliser image, antecedent et courbe representative", notionId: "fonction_vocabulaire_2de", prerequis: [] },
  { id: "fonction_image_formule", label: "Calculer une image avec une formule", notionId: "fonction_vocabulaire_2de", prerequis: ["fonction_vocabulaire", "litteral_developper"] },
  { id: "fonction_antecedent", label: "Rechercher un antecedent", notionId: "fonction_vocabulaire_2de", prerequis: ["fonction_image_formule", "equation_resoudre"] },
  { id: "fonction_tableau_graphique", label: "Passer d'un tableau a un graphique", notionId: "fonction_vocabulaire_2de", prerequis: ["fonction_vocabulaire"] },
  { id: "variation_tableau", label: "Lire un tableau de variations", notionId: "fonction_variations_extremums", prerequis: ["fonction_vocabulaire"] },
  { id: "variation_croissance", label: "Decrire croissance et decroissance sur un intervalle", notionId: "fonction_variations_extremums", prerequis: ["variation_tableau", "intervalle_appartenance"] },
  { id: "variation_extremum", label: "Identifier minimum et maximum", notionId: "fonction_variations_extremums", prerequis: ["variation_croissance"] },
  { id: "affine_forme", label: "Reconnaitre une fonction affine f(x)=ax+b", notionId: "fonctions_affines_2de", prerequis: ["fonction_image_formule"] },
  { id: "affine_calculer_image", label: "Calculer images et antecedents d'une fonction affine", notionId: "fonctions_affines_2de", prerequis: ["affine_forme", "equation_resoudre"] },
  { id: "affine_determiner_expression", label: "Determiner une fonction affine a partir de donnees", notionId: "fonctions_affines_2de", prerequis: ["affine_calculer_image", "droite_equation_reduite"] },
  { id: "affine_signe", label: "Etudier le signe d'une fonction affine", notionId: "fonctions_affines_2de", prerequis: ["affine_calculer_image", "inequation_resoudre"] },
  { id: "reference_carre", label: "Connaitre la fonction carre", notionId: "fonctions_reference_2de", prerequis: ["fonction_vocabulaire"] },
  { id: "reference_inverse", label: "Connaitre la fonction inverse", notionId: "fonctions_reference_2de", prerequis: ["reference_carre"] },
  { id: "reference_racine", label: "Connaitre la fonction racine carree", notionId: "fonctions_reference_2de", prerequis: ["reference_carre"] },
  { id: "reference_comparer", label: "Comparer deux images avec une fonction de reference", notionId: "fonctions_reference_2de", prerequis: ["reference_carre", "reference_inverse", "reference_racine"] },
  { id: "stat_lire_serie", label: "Lire une serie statistique", notionId: "statistiques_descriptives", prerequis: [] },
  { id: "stat_moyenne", label: "Calculer une moyenne", notionId: "statistiques_descriptives", prerequis: ["stat_lire_serie"] },
  { id: "stat_mediane_quartiles", label: "Determiner mediane et quartiles", notionId: "statistiques_descriptives", prerequis: ["stat_lire_serie"] },
  { id: "stat_frequence", label: "Calculer une frequence", notionId: "statistiques_descriptives", prerequis: ["stat_lire_serie"] },
  { id: "stat_interpreter", label: "Interpreter des indicateurs statistiques", notionId: "statistiques_descriptives", prerequis: ["stat_moyenne", "stat_mediane_quartiles", "stat_frequence"] },
  { id: "proba_vocabulaire", label: "Utiliser issue, evenement et univers", notionId: "probabilites_ensemble_fini", prerequis: [] },
  { id: "proba_modele", label: "Construire une loi de probabilite sur un univers fini", notionId: "probabilites_ensemble_fini", prerequis: ["proba_vocabulaire"] },
  { id: "proba_calculer", label: "Calculer une probabilite par somme des issues", notionId: "probabilites_ensemble_fini", prerequis: ["proba_modele", "stat_frequence"] },
  { id: "proba_evenement_contraire", label: "Utiliser l'evenement contraire", notionId: "probabilites_ensemble_fini", prerequis: ["proba_calculer"] },
  { id: "proba_tableau_arbre", label: "Organiser une experience avec tableau ou arbre", notionId: "probabilites_ensemble_fini", prerequis: ["proba_calculer"] },
  { id: "echantillon_fluctuation", label: "Comprendre la fluctuation d'echantillonnage", notionId: "echantillonnage_simulation", prerequis: ["stat_frequence", "proba_calculer"] },
  { id: "simulation_frequence", label: "Simuler une experience aleatoire et observer les frequences", notionId: "echantillonnage_simulation", prerequis: ["echantillon_fluctuation"] },
  { id: "echantillon_interpreter", label: "Interpreter un resultat de simulation", notionId: "echantillonnage_simulation", prerequis: ["simulation_frequence", "stat_interpreter"] },
  { id: "python_variable_affectation", label: "Utiliser variables et affectations en Python", notionId: "algorithmique_python_2de", prerequis: [] },
  { id: "python_condition", label: "Ecrire une instruction conditionnelle", notionId: "algorithmique_python_2de", prerequis: ["python_variable_affectation", "inequation_resoudre"] },
  { id: "python_boucle", label: "Utiliser une boucle", notionId: "algorithmique_python_2de", prerequis: ["python_condition"] },
  { id: "python_fonction", label: "Ecrire une fonction Python simple", notionId: "algorithmique_python_2de", prerequis: ["python_variable_affectation", "fonction_image_formule"] },
  { id: "python_simulation", label: "Programmer une simulation simple", notionId: "algorithmique_python_2de", prerequis: ["python_boucle", "simulation_frequence"] },
];
