import type { NotionSource } from "@/lib/tutor-v4/knowledge/buildKnowledge";

export const notions: NotionSource[] = [
  {
    id: "en_a2_verbs",
    label: "Mathematical Verbs A2",
    boId: "ENGL_A2_VERBS",
    prerequis: [],
    levels: [1, 2, 3],
  },
  {
    id: "en_a2_expressions",
    label: "Mathematical Expressions A2",
    boId: "ENGL_A2_EXPRESSIONS",
    prerequis: ["en_a2_verbs"],
    levels: [2, 3],
  },
  {
    id: "en_a2_fractions",
    label: "Fractions Vocabulary A2",
    boId: "ENGL_A2_FRACTIONS",
    prerequis: [],
    levels: [2, 3],
  },
  {
    id: "en_a2_geometry",
    label: "Geometry Vocabulary A2",
    boId: "ENGL_A2_GEOMETRY",
    prerequis: [],
    levels: [2, 3],
  },
  {
    id: "en_a2_sport_verbs",
    label: "Sport Verbs A2",
    boId: "ENGL_A2_SPORT_VERBS",
    prerequis: [],
    levels: [1, 2, 3],
  },
  {
    id: "en_a2_sport_stats",
    label: "Sport Stats A2",
    boId: "ENGL_A2_SPORT_STATS",
    prerequis: ["en_a2_sport_verbs"],
    levels: [2, 3],
  },
  {
    id: "en_a2_sport_physics",
    label: "Sport Physics A2",
    boId: "ENGL_A2_SPORT_PHYSICS",
    prerequis: ["en_a2_sport_verbs"],
    levels: [2, 3],
  },
  {
    id: "en_a2_science_biology",
    label: "Science — Biology A2",
    boId: "ENGL_A2_SCIENCE_BIOLOGY",
    prerequis: [],
    levels: [2, 3],
  },
  {
    id: "en_a2_science_chemistry",
    label: "Science — Chemistry A2",
    boId: "ENGL_A2_SCIENCE_CHEMISTRY",
    prerequis: [],
    levels: [2, 3],
  },
  {
    id: "en_a2_science_physics",
    label: "Science — Physics A2",
    boId: "ENGL_A2_SCIENCE_PHYSICS",
    prerequis: [],
    levels: [2, 3],
  },
  {
    id: "en_a2_economy_basics",
    label: "Économie - Gestion — Basics A2",
    boId: "ENGL_A2_ECONOMY_BASICS",
    prerequis: [],
    levels: [1, 2, 3],
  },
  {
    id: "en_a2_family_finance",
    label: "Économie - Gestion — Family Finance A2",
    boId: "ENGL_A2_FAMILY_FINANCE",
    prerequis: ["en_a2_economy_basics"],
    levels: [2, 3],
  },
  {
    id: "en_a2_percentages_eco",
    label: "Économie - Gestion — Percentages A2",
    boId: "ENGL_A2_PERCENTAGES_ECO",
    prerequis: ["en_a2_economy_basics"],
    levels: [2, 3],
  },
  {
    id: "en_a2_travel",
    label: "Géographie - Voyage — Travel A2",
    boId: "ENGL_A2_TRAVEL",
    prerequis: [],
    levels: [1, 2, 3],
  },
  {
    id: "en_a2_geography",
    label: "Géographie - Voyage — Geography A2",
    boId: "ENGL_A2_GEOGRAPHY",
    prerequis: ["en_a2_travel"],
    levels: [2, 3],
  },
  {
    id: "en_a2_directions",
    label: "Géographie - Voyage — Directions A2",
    boId: "ENGL_A2_DIRECTIONS",
    prerequis: ["en_a2_travel"],
    levels: [1, 2, 3],
  },
  { id: "en_a2_home",        label: "Vie Quotidienne — Home A2",        boId: "ENGL_A2_HOME",        prerequis: [],                      levels: [1, 2, 3] },
  { id: "en_a2_daily_verbs", label: "Vie Quotidienne — Daily Verbs A2", boId: "ENGL_A2_DAILY_VERBS", prerequis: [],                      levels: [1, 2, 3] },
  { id: "en_a2_adjectives",  label: "Vie Quotidienne — Adjectives A2",  boId: "ENGL_A2_ADJECTIVES",  prerequis: ["en_a2_daily_verbs"],   levels: [2, 3]    },
  { id: "en_a2_jobs",        label: "Vie Quotidienne — Jobs A2",        boId: "ENGL_A2_JOBS",        prerequis: [],                      levels: [1, 2, 3] },
];
