// lib/tutor-v4/questionBank/premiere-spe/maths/algorithmique.bank.ts
//
// Chapitre : Algorithmique et programmation (notion "algorithmique")
// microSkills :
//   algo_listes    — générer et parcourir une liste
//   algo_boucles   — lire et comprendre une boucle
//   algo_seuil     — recherche de seuil sur une suite
//   algo_fonctions — lire et comprendre une fonction Python
//
// PÉRIMÈTRE BO 2019 Première spé (Python). Conventions : code en `...`, LaTeX pour les maths, règle QCM.

import type { TutorBankItemV4 } from "@/lib/tutor-v4/types";

function randomInt(min: number, max: number) {
  return Math.floor(Math.random() * (max - min + 1)) + min;
}

function exp(definition: string, methode: string, calcul: string, conclusion: string) {
  return (
    `Définition : ${definition}\n\n` +
    `Méthode : ${methode}\n\n` +
    `Calcul / Observation : ${calcul}\n\n` +
    `Conclusion : ${conclusion}`
  );
}

export const algorithmiqueBank: TutorBankItemV4[] = [
  /* ===================== ALGO_LISTES ===================== */
  {
    kind: "fixed",
    id: "premiere_algo_lst_fixed_1",
    niveau: "premiere-spe",
    matiere: "maths",
    notionId: "algorithmique",
    microId: "algo_listes",
    difficulty: 2,
    theme: "neutral",
    text: "En Python, quel est le premier indice d'une liste `L` ?",
    format: "short",
    expected: ["0"],
    comparator: "number_equal",
    hint: "Les indices commencent à...",
    explanation: exp(
      "En Python, les listes sont indexées à partir de $0$.",
      "Le premier élément est `L[0]`.",
      "Donc le premier indice est $0$.",
      "Le premier indice est $0$."
    ),
    tags: ["premiere", "maths", "algorithmique", "listes", "short"],
  },
  {
    kind: "fixed",
    id: "premiere_algo_lst_fixed_2",
    niveau: "premiere-spe",
    matiere: "maths",
    notionId: "algorithmique",
    microId: "algo_listes",
    difficulty: 2,
    theme: "neutral",
    text: "Soit `L = [4, 7, 2, 9]`. Que vaut `L[2]` ?",
    format: "short",
    expected: ["2"],
    comparator: "number_equal",
    hint: "On compte à partir de l'indice 0.",
    explanation: exp(
      "On compte les indices à partir de $0$.",
      "`L[0]=4`, `L[1]=7`, `L[2]=2`.",
      "Donc `L[2]` vaut $2$.",
      "`L[2]` vaut $2$."
    ),
    tags: ["premiere", "maths", "algorithmique", "listes", "short"],
  },
  {
    kind: "fixed",
    id: "premiere_algo_lst_fixed_3",
    niveau: "premiere-spe",
    matiere: "maths",
    notionId: "algorithmique",
    microId: "algo_listes",
    difficulty: 3,
    theme: "neutral",
    text: "Que renvoie `len(L)` pour `L = [3, 5, 8, 1, 6]` ?",
    format: "short",
    expected: ["5"],
    comparator: "number_equal",
    hint: "`len` = nombre d'éléments.",
    explanation: exp(
      "`len(L)` renvoie le nombre d'éléments de la liste.",
      "La liste contient $5$ valeurs.",
      "Donc `len(L)` vaut $5$.",
      "`len(L)` vaut $5$."
    ),
    tags: ["premiere", "maths", "algorithmique", "listes", "short"],
  },
  {
    kind: "fixed",
    id: "premiere_algo_lst_fixed_4",
    niveau: "premiere-spe",
    matiere: "maths",
    notionId: "algorithmique",
    microId: "algo_listes",
    difficulty: 3,
    theme: "neutral",
    text: "Que contient la liste générée par `[2*k for k in range(4)]` ?",
    format: "qcm",
    choices: ["`[0, 2, 4, 6]`", "`[2, 4, 6, 8]`", "`[0, 2, 4, 6, 8]`", "`[1, 2, 3, 4]`"],
    expected: ["`[0, 2, 4, 6]`"],
    comparator: "mcq_exact",
    hint: "`range(4)` donne 0, 1, 2, 3.",
    explanation: exp(
      "C'est une liste définie en compréhension.",
      "`range(4)` parcourt $0, 1, 2, 3$, et on calcule $2k$.",
      "On obtient $0, 2, 4, 6$.",
      "`[0, 2, 4, 6]`."
    ),
    tags: ["premiere", "maths", "algorithmique", "listes", "qcm"],
  },
  {
    kind: "fixed",
    id: "premiere_algo_lst_fixed_5",
    niveau: "premiere-spe",
    matiere: "maths",
    notionId: "algorithmique",
    microId: "algo_listes",
    difficulty: 3,
    theme: "neutral",
    text: "Soit `L = [10, 20, 30]`. Que vaut `L[-1]` (dernier élément) ?",
    format: "short",
    expected: ["30"],
    comparator: "number_equal",
    hint: "L'indice $-1$ désigne le dernier élément.",
    explanation: exp(
      "En Python, l'indice $-1$ désigne le dernier élément.",
      "Le dernier élément de `L` est $30$.",
      "Donc `L[-1]` vaut $30$.",
      "`L[-1]` vaut $30$."
    ),
    tags: ["premiere", "maths", "algorithmique", "listes", "short"],
  },
  {
    kind: "fixed",
    id: "premiere_algo_lst_fixed_6",
    niveau: "premiere-spe",
    matiere: "maths",
    notionId: "algorithmique",
    microId: "algo_listes",
    difficulty: 2,
    theme: "neutral",
    text: "Soit `L = [4, 7, 2, 9]`. Que vaut `L[0]` ?",
    format: "short",
    expected: ["4"],
    comparator: "number_equal",
    hint: "En Python, la numérotation commence à $0$.",
    explanation: exp(
      "Les indices d'une liste Python commencent à $0$.",
      "`L[0]` désigne donc le PREMIER élément de la liste.",
      "Ici, c'est $4$.",
      "`L[0]` vaut $4$."
    ),
    tags: ["premiere", "maths", "algorithmique", "listes", "short"],
  },
  {
    kind: "fixed",
    id: "premiere_algo_lst_fixed_7",
    niveau: "premiere-spe",
    matiere: "maths",
    notionId: "algorithmique",
    microId: "algo_listes",
    difficulty: 4,
    theme: "neutral",
    text: "Que contient la liste `[k**2 for k in range(5)]` ?",
    format: "qcm",
    choices: [
      "`[0, 1, 4, 9, 16]`",
      "`[1, 4, 9, 16, 25]`",
      "`[0, 1, 2, 3, 4]`",
      "`[0, 2, 4, 6, 8]`",
    ],
    expected: ["`[0, 1, 4, 9, 16]`"],
    comparator: "mcq_exact",
    hint: "`range(5)` donne $0, 1, 2, 3, 4$ : on élève chacun au carré.",
    explanation: exp(
      "Une liste en compréhension applique le calcul à chaque valeur parcourue.",
      "`range(5)` parcourt $0, 1, 2, 3, 4$ : la borne $5$ est EXCLUE.",
      "Les carrés sont donc $0, 1, 4, 9, 16$.",
      "La liste est `[0, 1, 4, 9, 16]`."
    ),
    tags: ["premiere", "maths", "algorithmique", "listes", "qcm"],
  },
  {
    kind: "fixed",
    id: "premiere_algo_lst_fixed_8",
    niveau: "premiere-spe",
    matiere: "maths",
    notionId: "algorithmique",
    microId: "algo_listes",
    difficulty: 3,
    theme: "neutral",
    text: "Soit `L = [1, 2]`. Que contient `L` après l'instruction `L.append(5)` ?",
    format: "qcm",
    choices: ["`[1, 2, 5]`", "`[5, 1, 2]`", "`[1, 2]`", "`[1, 7]`"],
    expected: ["`[1, 2, 5]`"],
    comparator: "mcq_exact",
    hint: "`append` ajoute À LA FIN de la liste.",
    explanation: exp(
      "La méthode `append` ajoute un élément à la fin de la liste et modifie celle-ci.",
      "`L` valait `[1, 2]` : on ajoute $5$ après le dernier élément.",
      "`L` vaut alors `[1, 2, 5]`, et `len(L)` passe de $2$ à $3$.",
      "`L` contient `[1, 2, 5]`."
    ),
    tags: ["premiere", "maths", "algorithmique", "listes", "qcm"],
  },
  {
    kind: "fixed",
    id: "premiere_algo_lst_fixed_9",
    niveau: "premiere-spe",
    matiere: "maths",
    notionId: "algorithmique",
    microId: "algo_listes",
    difficulty: 4,
    theme: "neutral",
    text: "Que vaut `s` après : `s = 0` puis `for x in [2, 4, 6]: s = s + x` ?",
    format: "short",
    expected: ["12"],
    comparator: "number_equal",
    hint: "On additionne tous les éléments de la liste.",
    explanation: exp(
      "Cette boucle parcourt directement les VALEURS de la liste (et non les indices).",
      "$s$ prend successivement les valeurs $0 + 2 = 2$, puis $2 + 4 = 6$, puis $6 + 6 = 12$.",
      "$s = 12$.",
      "`s` vaut $12$ : c'est la somme des éléments de la liste."
    ),
    tags: ["premiere", "maths", "algorithmique", "listes", "short"],
  },
  {
    kind: "fixed",
    id: "premiere_algo_lst_fixed_10",
    niveau: "premiere-spe",
    matiere: "maths",
    notionId: "algorithmique",
    microId: "algo_listes",
    difficulty: 5,
    theme: "neutral",
    text: "Soit `L = [1, 2, 3]`. Que se passe-t-il si on écrit `L[3]` ?",
    format: "qcm",
    choices: [
      "une erreur : cet indice n'existe pas",
      "on obtient $3$",
      "on obtient $1$",
      "on ajoute un élément à la liste",
    ],
    expected: ["une erreur : cet indice n'existe pas"],
    comparator: "mcq_exact",
    hint: "Les indices vont de $0$ à `len(L) - 1`.",
    explanation: exp(
      "Pour une liste de $n$ éléments, les indices valides vont de $0$ à $n - 1$.",
      "Ici `len(L)` vaut $3$ : les indices vont de $0$ à $2$, et désignent respectivement $1$, $2$ et $3$.",
      "`L[3]` sort donc de la liste : Python renvoie une erreur d'indice.",
      "C'est une erreur : l'indice $3$ n'existe pas."
    ),
    tags: ["premiere", "maths", "algorithmique", "listes", "qcm"],
  },
  {
    kind: "fixed",
    id: "premiere_algo_lst_fixed_11",
    niveau: "premiere-spe",
    matiere: "maths",
    notionId: "algorithmique",
    microId: "algo_listes",
    difficulty: 4,
    theme: "neutral",
    text: "Combien de valeurs parcourt `range(2, 6)` ?",
    format: "short",
    expected: ["4"],
    comparator: "number_equal",
    hint: "La première borne est incluse, la seconde exclue.",
    explanation: exp(
      "`range(a, b)` parcourt les entiers de $a$ INCLUS à $b$ EXCLU.",
      "Ici : $2$, $3$, $4$, $5$.",
      "Cela fait $4$ valeurs, soit $6 - 2$.",
      "`range(2, 6)` parcourt $4$ valeurs."
    ),
    tags: ["premiere", "maths", "algorithmique", "listes", "short"],
  },
  {
    kind: "template",
    id: "premiere_algo_lst_tpl_1",
    niveau: "premiere-spe",
    matiere: "maths",
    notionId: "algorithmique",
    microId: "algo_listes",
    difficulty: 3,
    theme: "neutral",
    hint: "On compte à partir de l'indice 0.",
    tags: ["premiere", "maths", "algorithmique", "listes", "template"],
    generate: () => {
      const L = [randomInt(1, 9), randomInt(1, 9), randomInt(1, 9), randomInt(1, 9)];
      const i = randomInt(0, 3);
      return {
        text: `Soit \`L = [${L.join(", ")}]\`. Que vaut \`L[${i}]\` ?`,
        format: "short",
        expected: [String(L[i])],
        comparator: "number_equal",
        explanation: exp(
          "On compte les indices à partir de $0$.",
          `\`L[${i}]\` désigne l'élément en position ${i}.`,
          `Cet élément vaut $${L[i]}$.`,
          `\`L[${i}]\` vaut $${L[i]}$.`
        ),
      };
    },
  },

  /* ===================== ALGO_BOUCLES ===================== */
  {
    kind: "fixed",
    id: "premiere_algo_bcl_fixed_1",
    niveau: "premiere-spe",
    matiere: "maths",
    notionId: "algorithmique",
    microId: "algo_boucles",
    difficulty: 2,
    theme: "neutral",
    text: "Combien de fois s'exécute le corps de la boucle `for i in range(5):` ?",
    format: "short",
    expected: ["5"],
    comparator: "number_equal",
    hint: "`range(5)` parcourt 0 à 4.",
    explanation: exp(
      "`range(5)` produit les entiers $0, 1, 2, 3, 4$.",
      "Cela fait $5$ valeurs.",
      "Le corps s'exécute donc $5$ fois.",
      "$5$ fois."
    ),
    tags: ["premiere", "maths", "algorithmique", "boucles", "short"],
  },
  {
    kind: "fixed",
    id: "premiere_algo_bcl_fixed_2",
    niveau: "premiere-spe",
    matiere: "maths",
    notionId: "algorithmique",
    microId: "algo_boucles",
    difficulty: 3,
    theme: "neutral",
    text: "Que vaut `s` après : `s = 0` puis `for k in range(1, 5): s = s + k` ?",
    format: "short",
    expected: ["10"],
    comparator: "number_equal",
    hint: "On additionne $1 + 2 + 3 + 4$.",
    explanation: exp(
      "La boucle parcourt $k = 1, 2, 3, 4$ (range(1, 5) exclut 5).",
      "On accumule : $s = 1 + 2 + 3 + 4$.",
      "$= 10$.",
      "`s` vaut $10$."
    ),
    tags: ["premiere", "maths", "algorithmique", "boucles", "short"],
  },
  {
    kind: "fixed",
    id: "premiere_algo_bcl_fixed_3",
    niveau: "premiere-spe",
    matiere: "maths",
    notionId: "algorithmique",
    microId: "algo_boucles",
    difficulty: 3,
    theme: "neutral",
    text: "Que vaut `p` après : `p = 1` puis `for k in range(1, 4): p = p * k` ?",
    format: "short",
    expected: ["6"],
    comparator: "number_equal",
    hint: "Produit $1 \\times 2 \\times 3$.",
    explanation: exp(
      "La boucle parcourt $k = 1, 2, 3$.",
      "On accumule un produit : $p = 1 \\times 1 \\times 2 \\times 3$.",
      "$= 6$ (c'est $3!$).",
      "`p` vaut $6$."
    ),
    tags: ["premiere", "maths", "algorithmique", "boucles", "short"],
  },
  {
    kind: "fixed",
    id: "premiere_algo_bcl_fixed_4",
    niveau: "premiere-spe",
    matiere: "maths",
    notionId: "algorithmique",
    microId: "algo_boucles",
    difficulty: 2,
    theme: "neutral",
    text: "Quelle boucle utiliser quand on ne connaît pas à l'avance le nombre de répétitions ?",
    format: "qcm",
    choices: ["la boucle `while`", "la boucle `for`", "le test `if`", "la fonction `print`"],
    expected: ["la boucle `while`"],
    comparator: "mcq_exact",
    hint: "Boucle « tant que ».",
    explanation: exp(
      "La boucle `for` répète un nombre connu de fois.",
      "La boucle `while` répète tant qu'une condition est vraie.",
      "On l'utilise quand le nombre d'itérations est inconnu (ex. recherche de seuil).",
      "La boucle `while`."
    ),
    tags: ["premiere", "maths", "algorithmique", "boucles", "qcm"],
  },
  {
    kind: "fixed",
    id: "premiere_algo_bcl_fixed_5",
    niveau: "premiere-spe",
    matiere: "maths",
    notionId: "algorithmique",
    microId: "algo_boucles",
    difficulty: 3,
    theme: "neutral",
    text: "Combien de fois s'exécute le corps de la boucle `for i in range(3, 7):` ?",
    format: "short",
    expected: ["4"],
    comparator: "number_equal",
    hint: "$i$ prend les valeurs $3$, $4$, $5$, $6$.",
    explanation: exp(
      "`range(a, b)` parcourt les entiers de $a$ inclus à $b$ exclu.",
      "Ici $i$ vaut successivement $3$, $4$, $5$, $6$.",
      "Le corps s'exécute donc $4$ fois, soit $7 - 3$ (et non $7 - 3 + 1$ : la borne $7$ est exclue).",
      "Le corps s'exécute $4$ fois."
    ),
    tags: ["premiere", "maths", "algorithmique", "boucles", "short"],
  },
  {
    kind: "fixed",
    id: "premiere_algo_bcl_fixed_6",
    niveau: "premiere-spe",
    matiere: "maths",
    notionId: "algorithmique",
    microId: "algo_boucles",
    difficulty: 4,
    theme: "neutral",
    text: "Que vaut `s` après : `s = 0` puis `for k in range(1, 6): s = s + k` ?",
    format: "short",
    expected: ["15"],
    comparator: "number_equal",
    hint: "$1 + 2 + 3 + 4 + 5$.",
    explanation: exp(
      "La variable `s` accumule les valeurs successives de `k`.",
      "`k` parcourt $1$, $2$, $3$, $4$, $5$ (la borne $6$ est exclue).",
      "$s = 1 + 2 + 3 + 4 + 5 = 15$.",
      "`s` vaut $15$."
    ),
    tags: ["premiere", "maths", "algorithmique", "boucles", "short"],
  },
  {
    kind: "fixed",
    id: "premiere_algo_bcl_fixed_7",
    niveau: "premiere-spe",
    matiere: "maths",
    notionId: "algorithmique",
    microId: "algo_boucles",
    difficulty: 4,
    theme: "neutral",
    text: "Que vaut `p` après : `p = 1` puis `for k in range(1, 5): p = p * k` ?",
    format: "short",
    expected: ["24"],
    comparator: "number_equal",
    hint: "$1 \\times 2 \\times 3 \\times 4$.",
    explanation: exp(
      "La variable `p` accumule un PRODUIT : elle doit donc partir de $1$, et non de $0$.",
      "`k` parcourt $1$, $2$, $3$, $4$.",
      "$p = 1 \\times 1 \\times 2 \\times 3 \\times 4 = 24$.",
      "`p` vaut $24$ (c'est la factorielle de $4$)."
    ),
    tags: ["premiere", "maths", "algorithmique", "boucles", "short"],
  },
  {
    kind: "fixed",
    id: "premiere_algo_bcl_fixed_8",
    niveau: "premiere-spe",
    matiere: "maths",
    notionId: "algorithmique",
    microId: "algo_boucles",
    difficulty: 5,
    theme: "neutral",
    text: "Que vaut `n` à la fin de : `n = 0` puis `while n < 5: n = n + 2` ?",
    format: "short",
    expected: ["6"],
    comparator: "number_equal",
    hint: "Suis les valeurs : $2$, $4$, puis $6$. Quand le test devient-il faux ?",
    explanation: exp(
      "Le test est vérifié AVANT chaque passage : tant que `n < 5`, on ajoute $2$.",
      "$n$ vaut $0$ (test vrai) $\\to 2$ (vrai) $\\to 4$ (vrai) $\\to 6$.",
      "À $6$, le test `6 < 5` est faux : la boucle s'arrête. La variable dépasse donc le seuil $5$.",
      "`n` vaut $6$ à la fin."
    ),
    tags: ["premiere", "maths", "algorithmique", "boucles", "short"],
  },
  {
    kind: "fixed",
    id: "premiere_algo_bcl_fixed_9",
    niveau: "premiere-spe",
    matiere: "maths",
    notionId: "algorithmique",
    microId: "algo_boucles",
    difficulty: 4,
    theme: "neutral",
    text: "Que vaut `x` après : `x = 1` puis `for i in range(4): x = x * 2` ?",
    format: "short",
    expected: ["16"],
    comparator: "number_equal",
    hint: "On double $4$ fois : $2$, $4$, $8$, $16$.",
    explanation: exp(
      "`range(4)` parcourt $0$, $1$, $2$, $3$ : le corps s'exécute $4$ fois.",
      "`x` est doublée à chaque passage : $1 \\to 2 \\to 4 \\to 8 \\to 16$.",
      "$x = 2^4 = 16$.",
      "`x` vaut $16$."
    ),
    tags: ["premiere", "maths", "algorithmique", "boucles", "short"],
  },
  {
    kind: "fixed",
    id: "premiere_algo_bcl_fixed_10",
    niveau: "premiere-spe",
    matiere: "maths",
    notionId: "algorithmique",
    microId: "algo_boucles",
    difficulty: 3,
    theme: "neutral",
    text: "En Python, à quoi sert l'indentation (le décalage vers la droite) après un `for` ?",
    format: "qcm",
    choices: [
      "à indiquer quelles instructions sont répétées",
      "à rendre le code plus joli, sans effet",
      "à compter le nombre de répétitions",
      "à déclarer une variable",
    ],
    expected: ["à indiquer quelles instructions sont répétées"],
    comparator: "mcq_exact",
    hint: "En Python, le décalage n'est pas décoratif.",
    explanation: exp(
      "En Python, l'indentation délimite les blocs : elle remplace les accolades d'autres langages.",
      "Les lignes décalées après le `for` forment le corps de la boucle : ce sont elles qui se répètent.",
      "Une ligne ramenée à gauche n'est exécutée qu'une fois, après la boucle : une erreur d'indentation change donc le résultat.",
      "Elle indique quelles instructions sont répétées."
    ),
    tags: ["premiere", "maths", "algorithmique", "boucles", "qcm"],
  },
  {
    kind: "fixed",
    id: "premiere_algo_bcl_fixed_11",
    niveau: "premiere-spe",
    matiere: "maths",
    notionId: "algorithmique",
    microId: "algo_boucles",
    difficulty: 3,
    theme: "neutral",
    text: "Que vaut `s` après : `s = 0` puis `for k in range(5): s = s + 2` ?",
    format: "short",
    expected: ["10"],
    comparator: "number_equal",
    hint: "On ajoute $2$, cinq fois de suite.",
    explanation: exp(
      "Le corps s'exécute $5$ fois, car `range(5)` parcourt $0, 1, 2, 3, 4$.",
      "À chaque passage on ajoute $2$, quelle que soit la valeur de `k` (elle n'intervient pas dans le calcul).",
      "$s = 5 \\times 2 = 10$.",
      "`s` vaut $10$."
    ),
    tags: ["premiere", "maths", "algorithmique", "boucles", "short"],
  },
  {
    kind: "template",
    id: "premiere_algo_bcl_tpl_1",
    niveau: "premiere-spe",
    matiere: "maths",
    notionId: "algorithmique",
    microId: "algo_boucles",
    difficulty: 3,
    theme: "neutral",
    hint: "Somme des entiers de 1 à n.",
    tags: ["premiere", "maths", "algorithmique", "boucles", "template"],
    generate: () => {
      const n = randomInt(3, 8);
      const s = (n * (n + 1)) / 2;
      return {
        text: `Que vaut \`s\` après : \`s = 0\` puis \`for k in range(1, ${n + 1}): s = s + k\` ?`,
        format: "short",
        expected: [String(s)],
        comparator: "number_equal",
        explanation: exp(
          `La boucle parcourt $k = 1$ à $${n}$ (range(1, ${n + 1})).`,
          `On accumule $1 + 2 + \\dots + ${n}$.`,
          `$= \\dfrac{${n} \\times ${n + 1}}{2} = ${s}$.`,
          `\`s\` vaut $${s}$.`
        ),
      };
    },
  },
  {
    kind: "template",
    id: "premiere_algo_bcl_tpl_2",
    niveau: "premiere-spe",
    matiere: "maths",
    notionId: "algorithmique",
    microId: "algo_boucles",
    difficulty: 2,
    theme: "neutral",
    hint: "`range(a, b)` compte de a à b-1.",
    tags: ["premiere", "maths", "algorithmique", "boucles", "template"],
    generate: () => {
      const a = randomInt(0, 3);
      const b = randomInt(6, 12);
      const n = b - a;
      return {
        text: `Combien de fois s'exécute le corps de la boucle \`for i in range(${a}, ${b}):\` ?`,
        format: "short",
        expected: [String(n)],
        comparator: "number_equal",
        explanation: exp(
          "`range(a, b)` produit les entiers de $a$ à $b-1$.",
          `Ici de $${a}$ à $${b - 1}$, soit $${b} - ${a}$ valeurs.`,
          `$= ${n}$.`,
          `Le corps s'exécute $${n}$ fois.`
        ),
      };
    },
  },

  /* ===================== ALGO_SEUIL ===================== */
  {
    kind: "fixed",
    id: "premiere_algo_seuil_fixed_1",
    niveau: "premiere-spe",
    matiere: "maths",
    notionId: "algorithmique",
    microId: "algo_seuil",
    difficulty: 3,
    theme: "neutral",
    text: "Pour trouver le plus petit $n$ tel qu'une suite dépasse un seuil, on utilise plutôt :",
    format: "qcm",
    choices: ["une boucle `while`", "une boucle `for` fixe", "un simple `if`", "la fonction `len`"],
    expected: ["une boucle `while`"],
    comparator: "mcq_exact",
    hint: "On ne connaît pas $n$ à l'avance.",
    explanation: exp(
      "On cherche le premier rang dépassant un seuil, sans le connaître à l'avance.",
      "On répète « tant que la valeur est inférieure au seuil ».",
      "C'est une boucle `while`.",
      "Une boucle `while`."
    ),
    tags: ["premiere", "maths", "algorithmique", "seuil", "qcm"],
  },
  {
    kind: "fixed",
    id: "premiere_algo_seuil_fixed_2",
    niveau: "premiere-spe",
    matiere: "maths",
    notionId: "algorithmique",
    microId: "algo_seuil",
    difficulty: 4,
    theme: "neutral",
    text: "Suite : `u = 1` ; on répète `u = u * 2` en comptant les étapes. Après combien d'étapes a-t-on `u > 10` ?",
    format: "short",
    expected: ["4"],
    comparator: "number_equal",
    hint: "Liste les puissances de 2 : 2, 4, 8, 16.",
    explanation: exp(
      "On double à chaque étape : $1 \\to 2 \\to 4 \\to 8 \\to 16$.",
      "Les valeurs après chaque étape sont $2, 4, 8, 16$.",
      "La première qui dépasse $10$ est $16$, à la $4^e$ étape.",
      "Après $4$ étapes."
    ),
    tags: ["premiere", "maths", "algorithmique", "seuil", "short"],
  },
  {
    kind: "fixed",
    id: "premiere_algo_seuil_fixed_3",
    niveau: "premiere-spe",
    matiere: "maths",
    notionId: "algorithmique",
    microId: "algo_seuil",
    difficulty: 4,
    theme: "neutral",
    text: "Dans `n = 0` ; `u = 5` ; `while u < 100: u = u * 2 ; n = n + 1`, que compte la variable `n` ?",
    format: "qcm",
    choices: [
      "le nombre d'étapes pour dépasser 100",
      "la valeur finale de u",
      "le seuil 100",
      "la somme des termes",
    ],
    expected: ["le nombre d'étapes pour dépasser 100"],
    comparator: "mcq_exact",
    hint: "`n` augmente de 1 à chaque tour.",
    explanation: exp(
      "À chaque passage dans la boucle, `n` augmente de $1$.",
      "La boucle s'arrête quand `u` atteint ou dépasse $100$.",
      "`n` compte donc le nombre d'étapes (le rang seuil).",
      "Le nombre d'étapes pour dépasser 100."
    ),
    tags: ["premiere", "maths", "algorithmique", "seuil", "qcm"],
  },
  {
    kind: "fixed",
    id: "premiere_algo_seuil_fixed_4",
    niveau: "premiere-spe",
    matiere: "maths",
    notionId: "algorithmique",
    microId: "algo_seuil",
    difficulty: 3,
    theme: "neutral",
    text: "Suite arithmétique : `u = 2` ; on répète `u = u + 3`. Après combien d'étapes a-t-on `u > 10` ?",
    format: "short",
    expected: ["3"],
    comparator: "number_equal",
    hint: "Valeurs : 5, 8, 11.",
    explanation: exp(
      "On ajoute $3$ à chaque étape : $2 \\to 5 \\to 8 \\to 11$.",
      "Les valeurs après chaque étape sont $5, 8, 11$.",
      "La première qui dépasse $10$ est $11$, à la $3^e$ étape.",
      "Après $3$ étapes."
    ),
    tags: ["premiere", "maths", "algorithmique", "seuil", "short"],
  },
  {
    kind: "fixed",
    id: "premiere_algo_seuil_fixed_5",
    niveau: "premiere-spe",
    matiere: "maths",
    notionId: "algorithmique",
    microId: "algo_seuil",
    difficulty: 4,
    theme: "neutral",
    text: "Suite géométrique : `u = 1` ; on répète `u = u * 3`. Après combien d'étapes a-t-on `u > 50` ?",
    format: "short",
    expected: ["4"],
    comparator: "number_equal",
    hint: "Valeurs : $3$, $9$, $27$, $81$.",
    explanation: exp(
      "On triple à chaque étape et on compte les passages jusqu'à dépasser le seuil.",
      "$1 \\to 3 \\to 9 \\to 27 \\to 81$ : les valeurs après chaque étape sont $3$, $9$, $27$, $81$.",
      "La première qui dépasse $50$ est $81$, obtenue à la 4ᵉ étape.",
      "Après $4$ étapes."
    ),
    tags: ["premiere", "maths", "algorithmique", "seuil", "short"],
  },
  {
    kind: "fixed",
    id: "premiere_algo_seuil_fixed_6",
    niveau: "premiere-spe",
    matiere: "maths",
    notionId: "algorithmique",
    microId: "algo_seuil",
    difficulty: 5,
    theme: "neutral",
    text: "Suite décroissante : `u = 100` ; on répète `u = u - 25`. Après combien d'étapes a-t-on `u < 30` ?",
    format: "short",
    expected: ["3"],
    comparator: "number_equal",
    hint: "Valeurs : $75$, $50$, $25$.",
    explanation: exp(
      "Un seuil peut aussi être franchi vers le bas : on retranche $25$ à chaque étape.",
      "$100 \\to 75 \\to 50 \\to 25$ : les valeurs après chaque étape sont $75$, $50$, $25$.",
      "La première qui passe sous $30$ est $25$, à la 3ᵉ étape.",
      "Après $3$ étapes."
    ),
    tags: ["premiere", "maths", "algorithmique", "seuil", "short"],
  },
  {
    kind: "fixed",
    id: "premiere_algo_seuil_fixed_7",
    niveau: "premiere-spe",
    matiere: "maths",
    notionId: "algorithmique",
    microId: "algo_seuil",
    difficulty: 3,
    theme: "neutral",
    text: "Que renvoie un algorithme de recherche de seuil ?",
    format: "qcm",
    choices: [
      "le plus petit rang $n$ à partir duquel la condition est vérifiée",
      "la valeur du seuil",
      "la somme des termes de la suite",
      "la raison de la suite",
    ],
    expected: [
      "le plus petit rang $n$ à partir duquel la condition est vérifiée",
    ],
    comparator: "mcq_exact",
    hint: "On cherche À PARTIR DE QUAND, pas combien.",
    explanation: exp(
      "Une recherche de seuil répond à la question « à partir de quel rang la suite dépasse-t-elle telle valeur ? ».",
      "L'algorithme compte les étapes dans une variable `n` et s'arrête dès que la condition devient vraie.",
      "C'est donc ce compteur `n` qui est renvoyé, pas la valeur atteinte par la suite.",
      "Il renvoie le plus petit rang $n$ vérifiant la condition."
    ),
    tags: ["premiere", "maths", "algorithmique", "seuil", "qcm"],
  },
  {
    kind: "fixed",
    id: "premiere_algo_seuil_fixed_8",
    niveau: "premiere-spe",
    matiere: "maths",
    notionId: "algorithmique",
    microId: "algo_seuil",
    difficulty: 4,
    theme: "neutral",
    text: "Suite arithmétique : `u = 1` ; on répète `u = u + 4`. Après combien d'étapes a-t-on `u > 20` ?",
    format: "short",
    expected: ["5"],
    comparator: "number_equal",
    hint: "Valeurs : $5$, $9$, $13$, $17$, $21$.",
    explanation: exp(
      "On ajoute $4$ à chaque étape et on compte les passages.",
      "$1 \\to 5 \\to 9 \\to 13 \\to 17 \\to 21$.",
      "La première valeur qui dépasse $20$ est $21$, à la 5ᵉ étape. Attention : $17$ ne suffit pas.",
      "Après $5$ étapes."
    ),
    tags: ["premiere", "maths", "algorithmique", "seuil", "short"],
  },
  {
    kind: "fixed",
    id: "premiere_algo_seuil_fixed_9",
    niveau: "premiere-spe",
    matiere: "maths",
    notionId: "algorithmique",
    microId: "algo_seuil",
    difficulty: 4,
    theme: "neutral",
    text: "Dans une boucle `while u < 100:`, quand la boucle s'arrête-t-elle ?",
    format: "qcm",
    choices: [
      "dès que `u` atteint ou dépasse $100$",
      "dès que `u` dépasse strictement $100$",
      "après exactement $100$ tours",
      "elle ne s'arrête jamais",
    ],
    expected: ["dès que `u` atteint ou dépasse $100$"],
    comparator: "mcq_exact",
    hint: "La boucle tourne TANT QUE la condition est vraie.",
    explanation: exp(
      "Une boucle `while` continue tant que sa condition est vraie, et s'arrête dès qu'elle devient fausse.",
      "La condition `u < 100` devient fausse dès que $u \\ge 100$, c'est-à-dire $u = 100$ ou plus.",
      "Il faut donc que `u` évolue vers le seuil, sinon la boucle tournerait indéfiniment.",
      "Elle s'arrête dès que `u` atteint ou dépasse $100$."
    ),
    tags: ["premiere", "maths", "algorithmique", "seuil", "qcm"],
  },
  {
    kind: "fixed",
    id: "premiere_algo_seuil_fixed_10",
    niveau: "premiere-spe",
    matiere: "maths",
    notionId: "algorithmique",
    microId: "algo_seuil",
    difficulty: 5,
    theme: "neutral",
    text: "Où faut-il placer l'instruction `n = n + 1` dans un algorithme de seuil ?",
    format: "qcm",
    choices: [
      "dans la boucle, à chaque mise à jour de la suite",
      "avant la boucle, une seule fois",
      "après la boucle, une seule fois",
      "peu importe, le résultat est le même",
    ],
    expected: ["dans la boucle, à chaque mise à jour de la suite"],
    comparator: "mcq_exact",
    hint: "Le compteur doit avancer exactement au même rythme que la suite.",
    explanation: exp(
      "La variable `n` compte le nombre d'étapes effectuées : elle doit progresser en même temps que la suite.",
      "On la place donc DANS le corps de la boucle, à côté de la mise à jour de `u`.",
      "Hors de la boucle, elle ne serait incrémentée qu'une seule fois et le rang renvoyé serait faux.",
      "Dans la boucle, à chaque mise à jour de la suite."
    ),
    tags: ["premiere", "maths", "algorithmique", "seuil", "qcm"],
  },
  {
    kind: "fixed",
    id: "premiere_algo_seuil_fixed_11",
    niveau: "premiere-spe",
    matiere: "maths",
    notionId: "algorithmique",
    microId: "algo_seuil",
    difficulty: 5,
    theme: "neutral",
    text: "Que vaut `n` à la fin de : `n = 0` ; `u = 5` ; `while u < 100: u = u * 2 ; n = n + 1` ?",
    format: "short",
    expected: ["5"],
    comparator: "number_equal",
    hint: "Valeurs de `u` : $10$, $20$, $40$, $80$, $160$.",
    explanation: exp(
      "À chaque passage, `u` double et `n` augmente de $1$.",
      "$5 \\to 10 \\to 20 \\to 40 \\to 80 \\to 160$ : à $80$ le test `80 < 100` est encore vrai, donc on effectue un dernier tour.",
      "Cinq tours ont été effectués : $n = 5$.",
      "`n` vaut $5$."
    ),
    tags: ["premiere", "maths", "algorithmique", "seuil", "short"],
  },
  {
    kind: "template",
    id: "premiere_algo_seuil_tpl_1",
    niveau: "premiere-spe",
    matiere: "maths",
    notionId: "algorithmique",
    microId: "algo_seuil",
    difficulty: 4,
    theme: "neutral",
    hint: "Compte les étapes en doublant.",
    tags: ["premiere", "maths", "algorithmique", "seuil", "template"],
    generate: () => {
      const seuil = [10, 20, 50, 100][randomInt(0, 3)];
      let u = 1;
      let n = 0;
      while (u <= seuil) {
        u = u * 2;
        n += 1;
      }
      return {
        text: `Suite : \`u = 1\` ; on répète \`u = u * 2\`. Après combien d'étapes a-t-on \`u > ${seuil}\` ?`,
        format: "short",
        expected: [String(n)],
        comparator: "number_equal",
        explanation: exp(
          "On double $u$ à chaque étape (puissances de $2$).",
          `On s'arrête à la première valeur strictement supérieure à $${seuil}$.`,
          `Cela arrive après $${n}$ étapes (u = ${u}).`,
          `Après $${n}$ étapes.`
        ),
      };
    },
  },

  /* ===================== ALGO_FONCTIONS ===================== */
  {
    kind: "fixed",
    id: "premiere_algo_fct_fixed_1",
    niveau: "premiere-spe",
    matiere: "maths",
    notionId: "algorithmique",
    microId: "algo_fonctions",
    difficulty: 2,
    theme: "neutral",
    text: "En Python, quel mot-clé définit une fonction ?",
    format: "qcm",
    choices: ["`def`", "`function`", "`func`", "`return`"],
    expected: ["`def`"],
    comparator: "mcq_exact",
    hint: "Trois lettres.",
    explanation: exp(
      "On définit une fonction avec le mot-clé `def`.",
      "Ex. : `def f(x): return 2*x`.",
      "`return` sert à renvoyer un résultat, pas à définir la fonction.",
      "Le mot-clé est `def`."
    ),
    tags: ["premiere", "maths", "algorithmique", "fonctions", "qcm"],
  },
  {
    kind: "fixed",
    id: "premiere_algo_fct_fixed_2",
    niveau: "premiere-spe",
    matiere: "maths",
    notionId: "algorithmique",
    microId: "algo_fonctions",
    difficulty: 3,
    theme: "neutral",
    text: "Soit `def f(x): return 2*x + 1`. Que renvoie `f(3)` ?",
    format: "short",
    expected: ["7"],
    comparator: "number_equal",
    hint: "Remplace x par 3.",
    explanation: exp(
      "On remplace l'argument `x` par $3$.",
      "`f(3)` $= 2 \\times 3 + 1$.",
      "$= 7$.",
      "`f(3)` renvoie $7$."
    ),
    tags: ["premiere", "maths", "algorithmique", "fonctions", "short"],
  },
  {
    kind: "fixed",
    id: "premiere_algo_fct_fixed_3",
    niveau: "premiere-spe",
    matiere: "maths",
    notionId: "algorithmique",
    microId: "algo_fonctions",
    difficulty: 3,
    theme: "neutral",
    text: "Soit `def carre(x): return x*x`. Que renvoie `carre(5)` ?",
    format: "short",
    expected: ["25"],
    comparator: "number_equal",
    hint: "$5 \\times 5$.",
    explanation: exp(
      "La fonction renvoie le carré de son argument.",
      "`carre(5)` $= 5 \\times 5$.",
      "$= 25$.",
      "`carre(5)` renvoie $25$."
    ),
    tags: ["premiere", "maths", "algorithmique", "fonctions", "short"],
  },
  {
    kind: "fixed",
    id: "premiere_algo_fct_fixed_4",
    niveau: "premiere-spe",
    matiere: "maths",
    notionId: "algorithmique",
    microId: "algo_fonctions",
    difficulty: 3,
    theme: "neutral",
    text: "À quoi sert l'instruction `return` dans une fonction ?",
    format: "qcm",
    choices: [
      "à renvoyer un résultat",
      "à afficher du texte",
      "à créer une boucle",
      "à définir une variable globale",
    ],
    expected: ["à renvoyer un résultat"],
    comparator: "mcq_exact",
    hint: "Valeur de sortie.",
    explanation: exp(
      "`return` indique la valeur renvoyée par la fonction.",
      "C'est le résultat utilisable ensuite dans le programme.",
      "(Pour seulement afficher, on utilise `print`.)",
      "À renvoyer un résultat."
    ),
    tags: ["premiere", "maths", "algorithmique", "fonctions", "qcm"],
  },
  {
    kind: "fixed",
    id: "premiere_algo_fct_fixed_5",
    niveau: "premiere-spe",
    matiere: "maths",
    notionId: "algorithmique",
    microId: "algo_fonctions",
    difficulty: 3,
    theme: "neutral",
    text: "Soit `def f(x): return x**2 - 1`. Que renvoie `f(4)` ?",
    format: "short",
    expected: ["15"],
    comparator: "number_equal",
    hint: "`x**2` signifie « $x$ au carré ».",
    explanation: exp(
      "Appeler une fonction, c'est remplacer le paramètre par la valeur donnée.",
      "On remplace `x` par $4$ : $4^2 - 1$.",
      "$= 16 - 1 = 15$.",
      "`f(4)` renvoie $15$."
    ),
    tags: ["premiere", "maths", "algorithmique", "fonctions", "short"],
  },
  {
    kind: "fixed",
    id: "premiere_algo_fct_fixed_6",
    niveau: "premiere-spe",
    matiere: "maths",
    notionId: "algorithmique",
    microId: "algo_fonctions",
    difficulty: 3,
    theme: "neutral",
    text: "Soit `def somme(a, b): return a + b`. Que renvoie `somme(3, 5)` ?",
    format: "short",
    expected: ["8"],
    comparator: "number_equal",
    hint: "Deux paramètres : $a = 3$ et $b = 5$, dans cet ordre.",
    explanation: exp(
      "Une fonction peut recevoir plusieurs paramètres : ils sont associés dans l'ordre de l'appel.",
      "Ici $a = 3$ et $b = 5$, donc la fonction renvoie $3 + 5$.",
      "$= 8$.",
      "`somme(3, 5)` renvoie $8$."
    ),
    tags: ["premiere", "maths", "algorithmique", "fonctions", "short"],
  },
  {
    kind: "fixed",
    id: "premiere_algo_fct_fixed_7",
    niveau: "premiere-spe",
    matiere: "maths",
    notionId: "algorithmique",
    microId: "algo_fonctions",
    difficulty: 5,
    theme: "neutral",
    text: "Soit `def h(x): return 3*x`. Que renvoie `h(h(2))` ?",
    format: "short",
    expected: ["18"],
    comparator: "number_equal",
    hint: "Calcule d'abord `h(2)`, puis applique `h` au résultat.",
    explanation: exp(
      "On évalue toujours l'appel le plus intérieur en premier.",
      "`h(2)` renvoie $3 \\times 2 = 6$. L'expression devient `h(6)`.",
      "`h(6)` renvoie $3 \\times 6 = 18$.",
      "`h(h(2))` renvoie $18$."
    ),
    tags: ["premiere", "maths", "algorithmique", "fonctions", "short"],
  },
  {
    kind: "fixed",
    id: "premiere_algo_fct_fixed_8",
    niveau: "premiere-spe",
    matiere: "maths",
    notionId: "algorithmique",
    microId: "algo_fonctions",
    difficulty: 5,
    theme: "neutral",
    text: "Une fonction Python ne contient aucune instruction `return`. Que renvoie-t-elle ?",
    format: "qcm",
    choices: [
      "rien d'utilisable : la valeur spéciale `None`",
      "$0$",
      "la dernière valeur calculée",
      "une erreur",
    ],
    expected: ["rien d'utilisable : la valeur spéciale `None`"],
    comparator: "mcq_exact",
    hint: "Une fonction peut s'exécuter sans rien renvoyer.",
    explanation: exp(
      "Sans `return`, la fonction exécute bien ses instructions, mais ne transmet aucun résultat.",
      "Python renvoie alors `None`, qui signifie « aucune valeur ».",
      "C'est l'erreur classique : utiliser `print` à la place de `return`. L'affichage apparaît à l'écran, mais le résultat ne peut pas être réutilisé dans un calcul.",
      "Elle renvoie `None`."
    ),
    tags: ["premiere", "maths", "algorithmique", "fonctions", "qcm"],
  },
  {
    kind: "fixed",
    id: "premiere_algo_fct_fixed_9",
    niveau: "premiere-spe",
    matiere: "maths",
    notionId: "algorithmique",
    microId: "algo_fonctions",
    difficulty: 3,
    theme: "neutral",
    text: "Dans `def f(x): return 2*x + 1`, que représente `x` ?",
    format: "qcm",
    choices: [
      "le paramètre : la valeur donnée lors de l'appel",
      "le résultat renvoyé par la fonction",
      "le nom de la fonction",
      "une valeur fixée une fois pour toutes",
    ],
    expected: ["le paramètre : la valeur donnée lors de l'appel"],
    comparator: "mcq_exact",
    hint: "Il change à chaque appel : `f(3)`, `f(10)`…",
    explanation: exp(
      "Entre les parenthèses de la définition figure le paramètre : une variable d'attente.",
      "Elle prend la valeur fournie au moment de l'appel : `f(3)` donne $x = 3$, `f(10)` donne $x = 10$.",
      "Elle n'est donc pas fixée, et ne doit pas être confondue avec le résultat, qui est ce que produit `return`.",
      "`x` est le paramètre de la fonction."
    ),
    tags: ["premiere", "maths", "algorithmique", "fonctions", "qcm"],
  },
  {
    kind: "fixed",
    id: "premiere_algo_fct_fixed_10",
    niveau: "premiere-spe",
    matiere: "maths",
    notionId: "algorithmique",
    microId: "algo_fonctions",
    difficulty: 4,
    theme: "neutral",
    text: "Soit `def u(n): return 2*n + 1`, qui calcule le terme de rang $n$ d'une suite. Que renvoie `u(0)` ?",
    format: "short",
    expected: ["1"],
    comparator: "number_equal",
    hint: "Remplace `n` par $0$.",
    explanation: exp(
      "Une fonction Python traduit ici la formule explicite d'une suite : `u(n)` donne $u_n$.",
      "On remplace `n` par $0$ : $2 \\times 0 + 1$.",
      "$= 1$.",
      "`u(0)` renvoie $1$ : c'est le premier terme de la suite."
    ),
    tags: ["premiere", "maths", "algorithmique", "fonctions", "short"],
  },
  {
    kind: "fixed",
    id: "premiere_algo_fct_fixed_11",
    niveau: "premiere-spe",
    matiere: "maths",
    notionId: "algorithmique",
    microId: "algo_fonctions",
    difficulty: 4,
    theme: "neutral",
    text: "Quelle est la différence entre DÉFINIR une fonction et l'APPELER ?",
    format: "qcm",
    choices: [
      "définir décrit le calcul ; appeler l'exécute sur une valeur",
      "il n'y a aucune différence",
      "définir exécute le calcul ; appeler l'affiche",
      "on ne peut appeler une fonction qu'une seule fois",
    ],
    expected: ["définir décrit le calcul ; appeler l'exécute sur une valeur"],
    comparator: "mcq_exact",
    hint: "Écrire une recette n'est pas la cuisiner.",
    explanation: exp(
      "La définition (`def f(x): ...`) écrit la marche à suivre, sans rien calculer.",
      "L'appel (`f(3)`) déclenche l'exécution en donnant une valeur au paramètre.",
      "Une fonction se définit une fois et s'appelle autant de fois qu'on veut, avec des valeurs différentes.",
      "Définir décrit le calcul ; appeler l'exécute sur une valeur."
    ),
    tags: ["premiere", "maths", "algorithmique", "fonctions", "qcm"],
  },
  {
    kind: "template",
    id: "premiere_algo_fct_tpl_1",
    niveau: "premiere-spe",
    matiere: "maths",
    notionId: "algorithmique",
    microId: "algo_fonctions",
    difficulty: 3,
    theme: "neutral",
    hint: "Remplace x par la valeur donnée.",
    tags: ["premiere", "maths", "algorithmique", "fonctions", "template"],
    generate: () => {
      const a = randomInt(2, 5);
      const b = randomInt(1, 6);
      const k = randomInt(2, 6);
      const val = a * k + b;
      return {
        text: `Soit \`def f(x): return ${a}*x + ${b}\`. Que renvoie \`f(${k})\` ?`,
        format: "short",
        expected: [String(val)],
        comparator: "number_equal",
        explanation: exp(
          "On remplace l'argument `x` par la valeur donnée.",
          `\`f(${k})\` $= ${a} \\times ${k} + ${b}$.`,
          `$= ${val}$.`,
          `\`f(${k})\` renvoie $${val}$.`
        ),
      };
    },
  },
  {
    kind: "template",
    id: "premiere_algo_fct_tpl_2",
    niveau: "premiere-spe",
    matiere: "maths",
    notionId: "algorithmique",
    microId: "algo_fonctions",
    difficulty: 3,
    theme: "neutral",
    hint: "La fonction renvoie le carré.",
    tags: ["premiere", "maths", "algorithmique", "fonctions", "template"],
    generate: () => {
      const k = randomInt(2, 9);
      return {
        text: `Soit \`def carre(x): return x*x\`. Que renvoie \`carre(${k})\` ?`,
        format: "short",
        expected: [String(k * k)],
        comparator: "number_equal",
        explanation: exp(
          "La fonction renvoie le carré de son argument.",
          `\`carre(${k})\` $= ${k} \\times ${k}$.`,
          `$= ${k * k}$.`,
          `\`carre(${k})\` renvoie $${k * k}$.`
        ),
      };
    },
  },
];
