// lib/tutor-v4/questionBank/premiere-spe/maths/derivation.bank.ts
//
// Chapitre : Dérivation (notion "derivation")
// microSkills :
//   der_taux       — taux de variation et nombre dérivé
//   der_usuelles   — dérivées des fonctions usuelles
//   der_operations — dérivée d'une somme, d'un produit, d'un quotient
//   der_tangente   — équation de la tangente en un point
//
// PÉRIMÈTRE BO 2019 Première spé. Conventions : LaTeX, règle QCM. Canvas : fonctionGraphique (courbe + tangente).

import type { TutorBankItemV4, CanvasFigure } from "@/lib/tutor-v4/types";

function randomInt(min: number, max: number) {
  return Math.floor(Math.random() * (max - min + 1)) + min;
}

function exp(definition: string, methode: string, calcul: string, conclusion: string) {
  return (
    `Définition : ${definition}\n\n` +
    `Méthode : ${methode}\n\n` +
    `Calcul / Observation : ${calcul}\n\n` +
    `Conclusion : ${conclusion}`
  );
}

// Parabole y = x² + bx + c avec sa tangente au point d'abscisse a.
function tangente(b: number, c: number, a: number): CanvasFigure {
  const fa = a * a + b * a + c;
  const pente = 2 * a + b; // dérivée de x²+bx+c
  const ord = fa - pente * a; // y = pente·x + ord
  return {
    kind: "fonctionGraphique",
    size: { width: 320, height: 320 },
    xmin: -5,
    xmax: 5,
    ymin: -6,
    ymax: 10,
    grille: true,
    courbes: [
      { id: "f", type: "quadratique", a: 1, b, c, couleur: "#2563eb" },
      { id: "t", type: "affine", a: pente, b: ord, couleur: "#dc2626" },
    ],
    misesEnEvidence: [{ point: { x: a, y: Math.round(fa * 100) / 100, label: "A", couleur: "#16a34a" } }],
  };
}

export const derivationBank: TutorBankItemV4[] = [
  /* ===================== DER_TAUX ===================== */
  {
    kind: "fixed",
    id: "premiere_der_taux_fixed_1",
    niveau: "premiere-spe",
    matiere: "maths",
    notionId: "derivation",
    microId: "der_taux",
    difficulty: 2,
    theme: "neutral",
    text: "Le taux de variation de $f$ entre $a$ et $b$ s'écrit :",
    format: "qcm",
    choices: [
      "$\\dfrac{f(b) - f(a)}{b - a}$",
      "$\\dfrac{f(b) + f(a)}{b - a}$",
      "$\\dfrac{b - a}{f(b) - f(a)}$",
      "$f(b) - f(a)$",
    ],
    expected: ["$\\dfrac{f(b) - f(a)}{b - a}$"],
    comparator: "mcq_exact",
    hint: "Variation des images divisée par variation des $x$.",
    explanation: exp(
      "Le taux de variation mesure la variation moyenne entre deux points.",
      "On divise la variation des images par la variation des abscisses.",
      "$\\dfrac{f(b) - f(a)}{b - a}$.",
      "$\\dfrac{f(b) - f(a)}{b - a}$."
    ),
    tags: ["premiere", "maths", "derivation", "taux", "qcm"],
  },
  {
    kind: "fixed",
    id: "premiere_der_taux_fixed_2",
    niveau: "premiere-spe",
    matiere: "maths",
    notionId: "derivation",
    microId: "der_taux",
    difficulty: 3,
    theme: "neutral",
    text: "Pour $f(x) = x^2$, calcule le taux de variation entre $a = 1$ et $b = 3$.",
    format: "short",
    expected: ["4"],
    comparator: "number_equal",
    hint: "$\\dfrac{f(3) - f(1)}{3 - 1}$.",
    explanation: exp(
      "On applique la formule du taux de variation.",
      "$\\dfrac{f(3) - f(1)}{3 - 1} = \\dfrac{9 - 1}{2}$.",
      "$= \\dfrac{8}{2} = 4$.",
      "Le taux de variation vaut $4$."
    ),
    tags: ["premiere", "maths", "derivation", "taux", "short"],
  },
  {
    kind: "fixed",
    id: "premiere_der_taux_fixed_3",
    niveau: "premiere-spe",
    matiere: "maths",
    notionId: "derivation",
    microId: "der_taux",
    difficulty: 3,
    theme: "neutral",
    text: "Le nombre dérivé $f'(a)$ s'interprète géométriquement comme :",
    format: "qcm",
    choices: [
      "la pente de la tangente en $a$",
      "l'ordonnée du point $A$",
      "l'aire sous la courbe",
      "la longueur de la courbe",
    ],
    expected: ["la pente de la tangente en $a$"],
    comparator: "mcq_exact",
    hint: "Tangente = « limite des sécantes ».",
    explanation: exp(
      "Le nombre dérivé est la limite des taux de variation quand $b \\to a$.",
      "Cette limite est la pente de la tangente à la courbe au point d'abscisse $a$.",
      "C'est le coefficient directeur de la tangente.",
      "La pente de la tangente en $a$."
    ),
    tags: ["premiere", "maths", "derivation", "taux", "qcm"],
  },
  {
    kind: "fixed",
    id: "premiere_der_taux_fixed_4",
    niveau: "premiere-spe",
    matiere: "maths",
    notionId: "derivation",
    microId: "der_taux",
    difficulty: 3,
    theme: "sport",
    text: "Un cycliste parcourt $f(t)$ km en $t$ heures. Que représente le nombre dérivé $f'(2)$ ?",
    format: "qcm",
    choices: [
      "la vitesse instantanée à $t = 2$ h",
      "la distance totale",
      "le temps de pause",
      "la vitesse moyenne sur tout le trajet",
    ],
    expected: ["la vitesse instantanée à $t = 2$ h"],
    comparator: "mcq_exact",
    hint: "Dérivée d'une position = vitesse.",
    explanation: exp(
      "Le nombre dérivé est un taux de variation instantané.",
      "Pour une distance en fonction du temps, c'est une vitesse.",
      "$f'(2)$ est la vitesse instantanée à l'instant $t = 2$ h.",
      "La vitesse instantanée à $t = 2$ h."
    ),
    tags: ["premiere", "maths", "derivation", "taux", "qcm"],
  },
  {
    kind: "fixed",
    id: "premiere_der_taux_fixed_5",
    niveau: "premiere-spe",
    matiere: "maths",
    notionId: "derivation",
    microId: "der_taux",
    difficulty: 4,
    theme: "neutral",
    text: "Pour $f(x) = x^2$, le taux entre $1$ et $1 + h$ vaut $2 + h$. Vers quoi tend-il quand $h \\to 0$ ?",
    format: "short",
    expected: ["2"],
    comparator: "number_equal",
    hint: "Remplace $h$ par $0$.",
    explanation: exp(
      "Le nombre dérivé est la limite du taux quand $h \\to 0$.",
      "Le taux vaut $2 + h$.",
      "Quand $h \\to 0$, $2 + h \\to 2$.",
      "$f'(1) = 2$."
    ),
    tags: ["premiere", "maths", "derivation", "taux", "short"],
  },
  {
    kind: "fixed",
    id: "premiere_der_taux_fixed_6",
    niveau: "premiere-spe",
    matiere: "maths",
    notionId: "derivation",
    microId: "der_taux",
    difficulty: 3,
    theme: "neutral",
    text: "Pour $f(x) = 3x + 1$, calcule le taux de variation entre $a = 2$ et $b = 5$.",
    format: "short",
    expected: ["3"],
    comparator: "number_equal",
    hint: "$\\dfrac{f(5) - f(2)}{5 - 2}$.",
    explanation: exp(
      "Le taux de variation est $\\dfrac{f(b) - f(a)}{b - a}$.",
      "$f(2) = 7$ et $f(5) = 16$ : $\\dfrac{16 - 7}{5 - 2}$.",
      "$= \\dfrac{9}{3} = 3$. Pour une fonction affine, le taux vaut toujours le coefficient directeur.",
      "Le taux de variation vaut $3$."
    ),
    tags: ["premiere", "maths", "derivation", "taux", "short"],
  },
  {
    kind: "fixed",
    id: "premiere_der_taux_fixed_7",
    niveau: "premiere-spe",
    matiere: "maths",
    notionId: "derivation",
    microId: "der_taux",
    difficulty: 3,
    theme: "neutral",
    text: "Pour $f(x) = x^2$, calcule le taux de variation entre $a = 2$ et $b = 4$.",
    format: "short",
    expected: ["6"],
    comparator: "number_equal",
    hint: "$\\dfrac{16 - 4}{4 - 2}$.",
    explanation: exp(
      "Le taux de variation est $\\dfrac{f(b) - f(a)}{b - a}$.",
      "$f(2) = 4$ et $f(4) = 16$ : $\\dfrac{16 - 4}{4 - 2}$.",
      "$= \\dfrac{12}{2} = 6$.",
      "Le taux de variation vaut $6$."
    ),
    tags: ["premiere", "maths", "derivation", "taux", "short"],
  },
  {
    kind: "fixed",
    id: "premiere_der_taux_fixed_8",
    niveau: "premiere-spe",
    matiere: "maths",
    notionId: "derivation",
    microId: "der_taux",
    difficulty: 3,
    theme: "sport",
    text: "Une coureuse parcourt $d(t)$ mètres en $t$ secondes. Que représente le taux de variation de $d$ entre $t = 0$ et $t = 10$ ?",
    format: "qcm",
    choices: [
      "sa vitesse moyenne sur ces $10$ secondes",
      "sa vitesse au bout de $10$ secondes",
      "la distance totale parcourue",
      "son accélération",
    ],
    expected: ["sa vitesse moyenne sur ces $10$ secondes"],
    comparator: "mcq_exact",
    hint: "Un taux se calcule ENTRE deux instants, pas à un instant précis.",
    explanation: exp(
      "Le taux de variation est $\\dfrac{d(10) - d(0)}{10 - 0}$, c'est-à-dire une distance divisée par une durée.",
      "Comme il porte sur un intervalle, il donne une valeur MOYENNE sur cet intervalle.",
      "La vitesse à un instant précis, elle, correspond au nombre dérivé $d'(10)$.",
      "C'est sa vitesse moyenne sur ces $10$ secondes."
    ),
    tags: ["premiere", "maths", "derivation", "taux", "qcm"],
  },
  {
    kind: "fixed",
    id: "premiere_der_taux_fixed_9",
    niveau: "premiere-spe",
    matiere: "maths",
    notionId: "derivation",
    microId: "der_taux",
    difficulty: 4,
    theme: "neutral",
    text: "Pour $f(x) = x^2$, le taux entre $3$ et $3 + h$ vaut $6 + h$. Combien vaut $f'(3)$ ?",
    format: "short",
    expected: ["6"],
    comparator: "number_equal",
    hint: "Le nombre dérivé est la limite du taux quand $h \\to 0$.",
    explanation: exp(
      "Le nombre dérivé $f'(a)$ est la limite du taux de variation quand $h$ tend vers $0$.",
      "Ici le taux vaut $6 + h$.",
      "Quand $h \\to 0$, $6 + h \\to 6$.",
      "$f'(3) = 6$."
    ),
    tags: ["premiere", "maths", "derivation", "taux", "short"],
  },
  {
    kind: "fixed",
    id: "premiere_der_taux_fixed_10",
    niveau: "premiere-spe",
    matiere: "maths",
    notionId: "derivation",
    microId: "der_taux",
    difficulty: 4,
    theme: "reunion",
    text: "Un randonneur monte au Piton de la Fournaise. Son altitude est de $1800$ m après $1$ h et de $2400$ m après $3$ h. Quelle est sa vitesse moyenne d'ascension, en mètres par heure ?",
    format: "short",
    expected: ["300"],
    comparator: "number_equal",
    hint: "Dénivelé divisé par durée : attention, la durée est de $2$ h.",
    explanation: exp(
      "La vitesse moyenne d'ascension est le taux de variation de l'altitude entre les deux instants.",
      "$\\dfrac{2400 - 1800}{3 - 1}$.",
      "$= \\dfrac{600}{2} = 300$. (Diviser par $3$ au lieu de $2$ est l'erreur courante : on divise par la DURÉE écoulée.)",
      "Il monte de $300$ mètres par heure en moyenne."
    ),
    tags: ["premiere", "maths", "derivation", "taux", "short"],
  },
  {
    kind: "fixed",
    id: "premiere_der_taux_fixed_11",
    niveau: "premiere-spe",
    matiere: "maths",
    notionId: "derivation",
    microId: "der_taux",
    difficulty: 5,
    theme: "neutral",
    text: "Le nombre dérivé $f'(a)$ est la limite, quand $h \\to 0$, de :",
    format: "qcm",
    choices: [
      "$\\dfrac{f(a + h) - f(a)}{h}$",
      "$\\dfrac{f(a + h) - f(a)}{a}$",
      "$f(a + h) - f(a)$",
      "$\\dfrac{f(a)}{h}$",
    ],
    expected: ["$\\dfrac{f(a + h) - f(a)}{h}$"],
    comparator: "mcq_exact",
    hint: "Au numérateur l'écart des images, au dénominateur l'écart des abscisses.",
    explanation: exp(
      "Le nombre dérivé est la limite du taux de variation entre $a$ et $a + h$.",
      "L'écart des abscisses vaut $(a + h) - a = h$ : c'est lui qui va au dénominateur.",
      "D'où $f'(a) = \\lim\\limits_{h \\to 0} \\dfrac{f(a + h) - f(a)}{h}$. Sans le $h$ au dénominateur, la limite vaudrait toujours $0$.",
      "$f'(a) = \\lim\\limits_{h \\to 0} \\dfrac{f(a + h) - f(a)}{h}$."
    ),
    tags: ["premiere", "maths", "derivation", "taux", "qcm"],
  },
  {
    kind: "template",
    id: "premiere_der_taux_tpl_1",
    niveau: "premiere-spe",
    matiere: "maths",
    notionId: "derivation",
    microId: "der_taux",
    difficulty: 3,
    theme: "neutral",
    hint: "$\\dfrac{f(b) - f(a)}{b - a}$ avec $f(x) = x^2$.",
    tags: ["premiere", "maths", "derivation", "taux", "template"],
    generate: () => {
      const a = randomInt(0, 3);
      const b = a + randomInt(1, 4);
      const taux = (b * b - a * a) / (b - a); // = a + b
      return {
        text: `Pour $f(x) = x^2$, calcule le taux de variation entre $a = ${a}$ et $b = ${b}$.`,
        format: "short",
        expected: [String(taux)],
        comparator: "number_equal",
        explanation: exp(
          "On applique $\\dfrac{f(b) - f(a)}{b - a}$.",
          `$\\dfrac{${b}^2 - ${a}^2}{${b} - ${a}} = \\dfrac{${b * b - a * a}}{${b - a}}$.`,
          `$= ${taux}$.`,
          `Le taux de variation vaut $${taux}$.`
        ),
      };
    },
  },
  {
    kind: "template",
    id: "premiere_der_taux_tpl_2",
    niveau: "premiere-spe",
    matiere: "maths",
    notionId: "derivation",
    microId: "der_taux",
    difficulty: 3,
    theme: "neutral",
    hint: "$\\dfrac{f(b) - f(a)}{b - a}$ pour une fonction affine.",
    tags: ["premiere", "maths", "derivation", "taux", "template"],
    generate: () => {
      const m = randomInt(2, 6);
      const p = randomInt(-3, 3);
      const a = randomInt(0, 2);
      const b = a + randomInt(2, 4);
      return {
        text: `Pour $f(x) = ${m}x ${p >= 0 ? "+ " + p : "- " + -p}$, calcule le taux de variation entre $${a}$ et $${b}$.`,
        format: "short",
        expected: [String(m)],
        comparator: "number_equal",
        explanation: exp(
          "Pour une fonction affine, le taux de variation est constant et vaut la pente.",
          `$f(x) = ${m}x ${p >= 0 ? "+ " + p : "- " + -p}$ a pour pente $${m}$.`,
          `Le taux est donc $${m}$.`,
          `Le taux de variation vaut $${m}$.`
        ),
      };
    },
  },

  /* ===================== DER_USUELLES ===================== */
  {
    kind: "fixed",
    id: "premiere_der_us_fixed_1",
    niveau: "premiere-spe",
    matiere: "maths",
    notionId: "derivation",
    microId: "der_usuelles",
    difficulty: 1,
    theme: "neutral",
    text: "Quelle est la dérivée de $f(x) = x^2$ ?",
    format: "qcm",
    choices: ["$f'(x) = 2x$", "$f'(x) = x$", "$f'(x) = 2$", "$f'(x) = x^3$"],
    expected: ["$f'(x) = 2x$"],
    comparator: "mcq_exact",
    hint: "$(x^n)' = n x^{n-1}$.",
    explanation: exp(
      "On applique $(x^n)' = n x^{n-1}$.",
      "Ici $n = 2$.",
      "$f'(x) = 2x^{1} = 2x$.",
      "$f'(x) = 2x$."
    ),
    tags: ["premiere", "maths", "derivation", "usuelles", "qcm"],
  },
  {
    kind: "fixed",
    id: "premiere_der_us_fixed_2",
    niveau: "premiere-spe",
    matiere: "maths",
    notionId: "derivation",
    microId: "der_usuelles",
    difficulty: 2,
    theme: "neutral",
    text: "Quelle est la dérivée de $f(x) = x^3$ ?",
    format: "qcm",
    choices: ["$f'(x) = 3x^2$", "$f'(x) = 2x^2$", "$f'(x) = 3x$", "$f'(x) = x^2$"],
    expected: ["$f'(x) = 3x^2$"],
    comparator: "mcq_exact",
    hint: "$(x^n)' = n x^{n-1}$.",
    explanation: exp(
      "On applique $(x^n)' = n x^{n-1}$.",
      "Ici $n = 3$.",
      "$f'(x) = 3x^{2}$.",
      "$f'(x) = 3x^2$."
    ),
    tags: ["premiere", "maths", "derivation", "usuelles", "qcm"],
  },
  {
    kind: "fixed",
    id: "premiere_der_us_fixed_3",
    niveau: "premiere-spe",
    matiere: "maths",
    notionId: "derivation",
    microId: "der_usuelles",
    difficulty: 3,
    theme: "neutral",
    text: "Quelle est la dérivée de $f(x) = \\dfrac{1}{x}$ ?",
    format: "qcm",
    choices: [
      "$f'(x) = -\\dfrac{1}{x^2}$",
      "$f'(x) = \\dfrac{1}{x^2}$",
      "$f'(x) = -\\dfrac{1}{x}$",
      "$f'(x) = \\ln(x)$",
    ],
    expected: ["$f'(x) = -\\dfrac{1}{x^2}$"],
    comparator: "mcq_exact",
    hint: "Dérivée de la fonction inverse.",
    explanation: exp(
      "La fonction inverse a une dérivée connue.",
      "$\\left(\\dfrac{1}{x}\\right)' = -\\dfrac{1}{x^2}$.",
      "Le signe est négatif.",
      "$f'(x) = -\\dfrac{1}{x^2}$."
    ),
    tags: ["premiere", "maths", "derivation", "usuelles", "qcm"],
  },
  {
    kind: "fixed",
    id: "premiere_der_us_fixed_4",
    niveau: "premiere-spe",
    matiere: "maths",
    notionId: "derivation",
    microId: "der_usuelles",
    difficulty: 3,
    theme: "neutral",
    text: "Quelle est la dérivée de $f(x) = \\sqrt{x}$ ?",
    format: "qcm",
    choices: [
      "$f'(x) = \\dfrac{1}{2\\sqrt{x}}$",
      "$f'(x) = \\dfrac{1}{\\sqrt{x}}$",
      "$f'(x) = 2\\sqrt{x}$",
      "$f'(x) = \\dfrac{1}{2}\\sqrt{x}$",
    ],
    expected: ["$f'(x) = \\dfrac{1}{2\\sqrt{x}}$"],
    comparator: "mcq_exact",
    hint: "Dérivée de la racine carrée.",
    explanation: exp(
      "La fonction racine carrée a une dérivée connue.",
      "$(\\sqrt{x})' = \\dfrac{1}{2\\sqrt{x}}$.",
      "Définie pour $x > 0$.",
      "$f'(x) = \\dfrac{1}{2\\sqrt{x}}$."
    ),
    tags: ["premiere", "maths", "derivation", "usuelles", "qcm"],
  },
  {
    kind: "fixed",
    id: "premiere_der_us_fixed_5",
    niveau: "premiere-spe",
    matiere: "maths",
    notionId: "derivation",
    microId: "der_usuelles",
    difficulty: 2,
    theme: "neutral",
    text: "Quelle est la dérivée d'une fonction constante $f(x) = 7$ ?",
    format: "qcm",
    choices: ["$f'(x) = 0$", "$f'(x) = 7$", "$f'(x) = 1$", "$f'(x) = 7x$"],
    expected: ["$f'(x) = 0$"],
    comparator: "mcq_exact",
    hint: "Une constante ne varie pas.",
    explanation: exp(
      "La dérivée mesure la variation.",
      "Une fonction constante ne varie pas.",
      "Sa dérivée est nulle.",
      "$f'(x) = 0$."
    ),
    tags: ["premiere", "maths", "derivation", "usuelles", "qcm"],
  },
  {
    kind: "fixed",
    id: "premiere_der_us_fixed_6",
    niveau: "premiere-spe",
    matiere: "maths",
    notionId: "derivation",
    microId: "der_usuelles",
    difficulty: 2,
    theme: "neutral",
    text: "Quelle est la dérivée de $f(x) = 5x + 3$ ?",
    format: "qcm",
    choices: ["$f'(x) = 5$", "$f'(x) = 5x$", "$f'(x) = 3$", "$f'(x) = 8$"],
    expected: ["$f'(x) = 5$"],
    comparator: "mcq_exact",
    hint: "Dérivée d'une fonction affine $ax + b$.",
    explanation: exp(
      "La dérivée d'une fonction affine $ax + b$ est la constante $a$.",
      "Ici $a = 5$.",
      "$f'(x) = 5$.",
      "$f'(x) = 5$."
    ),
    tags: ["premiere", "maths", "derivation", "usuelles", "qcm"],
  },
  {
    kind: "fixed",
    id: "premiere_der_us_fixed_7",
    niveau: "premiere-spe",
    matiere: "maths",
    notionId: "derivation",
    microId: "der_usuelles",
    difficulty: 3,
    theme: "neutral",
    text: "Quelle est la dérivée de $f(x) = x^5$ ?",
    format: "qcm",
    choices: ["$f'(x) = 5x^4$", "$f'(x) = 5x^5$", "$f'(x) = x^4$", "$f'(x) = 4x^5$"],
    expected: ["$f'(x) = 5x^4$"],
    comparator: "mcq_exact",
    hint: "L'exposant passe devant et diminue de $1$.",
    explanation: exp(
      "Pour $f(x) = x^n$, on a $f'(x) = n x^{n-1}$.",
      "Ici $n = 5$ : l'exposant $5$ passe en facteur, et le nouvel exposant est $5 - 1 = 4$.",
      "$f'(x) = 5x^4$.",
      "$f'(x) = 5x^4$."
    ),
    tags: ["premiere", "maths", "derivation", "usuelles", "qcm"],
  },
  {
    kind: "fixed",
    id: "premiere_der_us_fixed_8",
    niveau: "premiere-spe",
    matiere: "maths",
    notionId: "derivation",
    microId: "der_usuelles",
    difficulty: 2,
    theme: "neutral",
    text: "Quelle est la dérivée de $f(x) = x$ ?",
    format: "qcm",
    choices: ["$f'(x) = 1$", "$f'(x) = 0$", "$f'(x) = x$", "$f'(x) = 2x$"],
    expected: ["$f'(x) = 1$"],
    comparator: "mcq_exact",
    hint: "C'est la fonction affine $1 \\times x + 0$.",
    explanation: exp(
      "La dérivée d'une fonction affine $ax + b$ est $a$.",
      "$f(x) = x$ s'écrit $1 \\times x + 0$, donc $a = 1$.",
      "$f'(x) = 1$. (C'est $0$ pour une CONSTANTE, pas pour $x$.)",
      "$f'(x) = 1$."
    ),
    tags: ["premiere", "maths", "derivation", "usuelles", "qcm"],
  },
  {
    kind: "fixed",
    id: "premiere_der_us_fixed_9",
    niveau: "premiere-spe",
    matiere: "maths",
    notionId: "derivation",
    microId: "der_usuelles",
    difficulty: 4,
    theme: "neutral",
    text: "Pour $f(x) = x^n$ (avec $n$ entier, $n \\ge 1$), quelle est la dérivée ?",
    format: "qcm",
    choices: [
      "$f'(x) = n x^{n-1}$",
      "$f'(x) = n x^{n+1}$",
      "$f'(x) = x^{n-1}$",
      "$f'(x) = (n-1) x^n$",
    ],
    expected: ["$f'(x) = n x^{n-1}$"],
    comparator: "mcq_exact",
    hint: "Vérifie sur un cas connu : pour $n = 2$, on doit retrouver $2x$.",
    explanation: exp(
      "C'est la formule générale de dérivation des puissances.",
      "L'exposant descend en facteur devant, et l'exposant restant diminue de $1$.",
      "Contrôle sur $n = 2$ : $f'(x) = 2x^1 = 2x$, ce qui est bien la dérivée de $x^2$.",
      "$f'(x) = n x^{n-1}$."
    ),
    tags: ["premiere", "maths", "derivation", "usuelles", "qcm"],
  },
  {
    kind: "fixed",
    id: "premiere_der_us_fixed_10",
    niveau: "premiere-spe",
    matiere: "maths",
    notionId: "derivation",
    microId: "der_usuelles",
    difficulty: 5,
    theme: "neutral",
    text: "Sur quel intervalle la fonction $f(x) = \\sqrt{x}$ est-elle dérivable ?",
    format: "qcm",
    choices: [
      "$]0 ; +\\infty[$",
      "$[0 ; +\\infty[$",
      "$\\mathbb{R}$",
      "$]-\\infty ; 0[$",
    ],
    expected: ["$]0 ; +\\infty[$"],
    comparator: "mcq_exact",
    hint: "Regarde la formule $f'(x) = \\dfrac{1}{2\\sqrt{x}}$ : que se passe-t-il en $0$ ?",
    explanation: exp(
      "La dérivée de $\\sqrt{x}$ est $\\dfrac{1}{2\\sqrt{x}}$.",
      "Cette expression exige $\\sqrt{x} \\neq 0$, donc $x \\neq 0$, en plus de $x \\ge 0$.",
      "La fonction est DÉFINIE en $0$ mais n'y est pas dérivable : sa courbe y a une tangente verticale.",
      "Elle est dérivable sur $]0 ; +\\infty[$."
    ),
    tags: ["premiere", "maths", "derivation", "usuelles", "qcm"],
  },
  {
    kind: "fixed",
    id: "premiere_der_us_fixed_11",
    niveau: "premiere-spe",
    matiere: "maths",
    notionId: "derivation",
    microId: "der_usuelles",
    difficulty: 4,
    theme: "neutral",
    text: "La dérivée de $f(x) = \\dfrac{1}{x}$ est $f'(x) = -\\dfrac{1}{x^2}$. Quel est son signe sur $]0 ; +\\infty[$ ?",
    format: "qcm",
    choices: [
      "négatif : la fonction est décroissante",
      "positif : la fonction est croissante",
      "nul : la fonction est constante",
      "il change de signe en $x = 1$",
    ],
    expected: ["négatif : la fonction est décroissante"],
    comparator: "mcq_exact",
    hint: "$x^2$ est toujours positif ; le signe vient du « moins » devant.",
    explanation: exp(
      "Le signe de la dérivée donne le sens de variation de la fonction.",
      "$x^2 > 0$ pour tout $x \\neq 0$, donc $-\\dfrac{1}{x^2}$ est toujours NÉGATIF.",
      "La fonction inverse est donc décroissante sur $]0 ; +\\infty[$ (et aussi sur $]-\\infty ; 0[$).",
      "La dérivée est négative : la fonction est décroissante."
    ),
    tags: ["premiere", "maths", "derivation", "usuelles", "qcm"],
  },
  {
    kind: "template",
    id: "premiere_der_us_tpl_1",
    niveau: "premiere-spe",
    matiere: "maths",
    notionId: "derivation",
    microId: "der_usuelles",
    difficulty: 3,
    theme: "neutral",
    hint: "$(x^n)' = n x^{n-1}$.",
    tags: ["premiere", "maths", "derivation", "usuelles", "template"],
    generate: () => {
      const n = randomInt(2, 6);
      const correct = n === 2 ? "$f'(x) = 2x$" : `$f'(x) = ${n}x^{${n - 1}}$`;
      const choices = [
        correct,
        `$f'(x) = ${n}x^{${n}}$`,
        `$f'(x) = ${n - 1}x^{${n - 1}}$`,
        `$f'(x) = x^{${n - 1}}$`,
      ];
      return {
        text: `Quelle est la dérivée de $f(x) = x^{${n}}$ ?`,
        format: "qcm",
        choices,
        expected: [correct],
        comparator: "mcq_exact",
        explanation: exp(
          "On applique $(x^n)' = n x^{n-1}$.",
          `Ici $n = ${n}$.`,
          `$f'(x) = ${n}x^{${n - 1}}$.`,
          `${correct}.`
        ),
      };
    },
  },
  {
    kind: "template",
    id: "premiere_der_us_tpl_2",
    niveau: "premiere-spe",
    matiere: "maths",
    notionId: "derivation",
    microId: "der_usuelles",
    difficulty: 2,
    theme: "neutral",
    hint: "Dérivée de $ax + b$.",
    tags: ["premiere", "maths", "derivation", "usuelles", "template"],
    generate: () => {
      const a = randomInt(2, 9);
      const b = randomInt(-5, 5);
      const correct = `$f'(x) = ${a}$`;
      const choices = [correct, `$f'(x) = ${a}x$`, `$f'(x) = ${b}$`, `$f'(x) = ${a + b}$`];
      return {
        text: `Quelle est la dérivée de $f(x) = ${a}x ${b >= 0 ? "+ " + b : "- " + -b}$ ?`,
        format: "qcm",
        choices,
        expected: [correct],
        comparator: "mcq_exact",
        explanation: exp(
          "La dérivée de $ax + b$ est $a$.",
          `Ici $a = ${a}$.`,
          `$f'(x) = ${a}$.`,
          `${correct}.`
        ),
      };
    },
  },

  /* ===================== DER_OPERATIONS ===================== */
  {
    kind: "fixed",
    id: "premiere_der_op_fixed_1",
    niveau: "premiere-spe",
    matiere: "maths",
    notionId: "derivation",
    microId: "der_operations",
    difficulty: 2,
    theme: "neutral",
    text: "Quelle est la dérivée de $f(x) = x^2 + 3x$ ?",
    format: "qcm",
    choices: ["$f'(x) = 2x + 3$", "$f'(x) = 2x + 3x$", "$f'(x) = x + 3$", "$f'(x) = 2x$"],
    expected: ["$f'(x) = 2x + 3$"],
    comparator: "mcq_exact",
    hint: "$(u + v)' = u' + v'$.",
    explanation: exp(
      "La dérivée d'une somme est la somme des dérivées.",
      "$(x^2)' = 2x$ et $(3x)' = 3$.",
      "$f'(x) = 2x + 3$.",
      "$f'(x) = 2x + 3$."
    ),
    tags: ["premiere", "maths", "derivation", "operations", "qcm"],
  },
  {
    kind: "fixed",
    id: "premiere_der_op_fixed_2",
    niveau: "premiere-spe",
    matiere: "maths",
    notionId: "derivation",
    microId: "der_operations",
    difficulty: 3,
    theme: "neutral",
    text: "Quelle est la dérivée de $f(x) = 3x^2 - 5x + 2$ ?",
    format: "qcm",
    choices: ["$f'(x) = 6x - 5$", "$f'(x) = 6x - 5 + 2$", "$f'(x) = 3x - 5$", "$f'(x) = 6x + 5$"],
    expected: ["$f'(x) = 6x - 5$"],
    comparator: "mcq_exact",
    hint: "Dérive terme à terme.",
    explanation: exp(
      "On dérive chaque terme.",
      "$(3x^2)' = 6x$, $(-5x)' = -5$, $(2)' = 0$.",
      "$f'(x) = 6x - 5$.",
      "$f'(x) = 6x - 5$."
    ),
    tags: ["premiere", "maths", "derivation", "operations", "qcm"],
  },
  {
    kind: "fixed",
    id: "premiere_der_op_fixed_3",
    niveau: "premiere-spe",
    matiere: "maths",
    notionId: "derivation",
    microId: "der_operations",
    difficulty: 3,
    theme: "neutral",
    text: "La dérivée d'un produit $(uv)'$ est :",
    format: "qcm",
    choices: ["$u'v + uv'$", "$u'v'$", "$u'v - uv'$", "$u' + v'$"],
    expected: ["$u'v + uv'$"],
    comparator: "mcq_exact",
    hint: "Formule du produit.",
    explanation: exp(
      "La dérivée d'un produit n'est pas le produit des dérivées.",
      "On utilise $(uv)' = u'v + uv'$.",
      "Chaque facteur est dérivé à tour de rôle.",
      "$(uv)' = u'v + uv'$."
    ),
    tags: ["premiere", "maths", "derivation", "operations", "qcm"],
  },
  {
    kind: "fixed",
    id: "premiere_der_op_fixed_4",
    niveau: "premiere-spe",
    matiere: "maths",
    notionId: "derivation",
    microId: "der_operations",
    difficulty: 4,
    theme: "neutral",
    text: "Pour $f(x) = x^2 - 4x + 1$, combien vaut $f'(3)$ ?",
    format: "short",
    expected: ["2"],
    comparator: "number_equal",
    hint: "Calcule $f'(x)$ puis remplace $x$ par $3$.",
    explanation: exp(
      "On dérive d'abord : $f'(x) = 2x - 4$.",
      "Puis on remplace $x$ par $3$.",
      "$f'(3) = 2 \\times 3 - 4 = 2$.",
      "$f'(3) = 2$."
    ),
    tags: ["premiere", "maths", "derivation", "operations", "short"],
  },
  {
    kind: "fixed",
    id: "premiere_der_op_fixed_5",
    niveau: "premiere-spe",
    matiere: "maths",
    notionId: "derivation",
    microId: "der_operations",
    difficulty: 3,
    theme: "neutral",
    text: "Quelle est la dérivée de $f(x) = x^3 - 2x^2$ ?",
    format: "qcm",
    choices: ["$f'(x) = 3x^2 - 4x$", "$f'(x) = 3x^2 - 2x$", "$f'(x) = 3x - 4x$", "$f'(x) = x^2 - 4x$"],
    expected: ["$f'(x) = 3x^2 - 4x$"],
    comparator: "mcq_exact",
    hint: "$(x^3)' = 3x^2$, $(2x^2)' = 4x$.",
    explanation: exp(
      "On dérive terme à terme.",
      "$(x^3)' = 3x^2$ et $(2x^2)' = 4x$.",
      "$f'(x) = 3x^2 - 4x$.",
      "$f'(x) = 3x^2 - 4x$."
    ),
    tags: ["premiere", "maths", "derivation", "operations", "qcm"],
  },
  {
    kind: "fixed",
    id: "premiere_der_op_fixed_6",
    niveau: "premiere-spe",
    matiere: "maths",
    notionId: "derivation",
    microId: "der_operations",
    difficulty: 3,
    theme: "neutral",
    text: "Quelle est la dérivée de $f(x) = 2x^3 - 3x^2 + 4$ ?",
    format: "qcm",
    choices: [
      "$f'(x) = 6x^2 - 6x$",
      "$f'(x) = 6x^2 - 6x + 4$",
      "$f'(x) = 6x^2 - 3x$",
      "$f'(x) = 2x^2 - 6x$",
    ],
    expected: ["$f'(x) = 6x^2 - 6x$"],
    comparator: "mcq_exact",
    hint: "La dérivée d'une constante est nulle : le $+4$ disparaît.",
    explanation: exp(
      "On dérive terme à terme, en gardant les coefficients en facteur.",
      "$(2x^3)' = 2 \\times 3x^2 = 6x^2$ ; $(3x^2)' = 3 \\times 2x = 6x$ ; $(4)' = 0$.",
      "$f'(x) = 6x^2 - 6x$. Garder le $+4$ est l'erreur classique.",
      "$f'(x) = 6x^2 - 6x$."
    ),
    tags: ["premiere", "maths", "derivation", "operations", "qcm"],
  },
  {
    kind: "fixed",
    id: "premiere_der_op_fixed_7",
    niveau: "premiere-spe",
    matiere: "maths",
    notionId: "derivation",
    microId: "der_operations",
    difficulty: 4,
    theme: "neutral",
    text: "La dérivée d'un quotient $\\left(\\dfrac{u}{v}\\right)'$ est :",
    format: "qcm",
    choices: [
      "$\\dfrac{u'v - uv'}{v^2}$",
      "$\\dfrac{u'v + uv'}{v^2}$",
      "$\\dfrac{u'}{v'}$",
      "$\\dfrac{uv' - u'v}{v^2}$",
    ],
    expected: ["$\\dfrac{u'v - uv'}{v^2}$"],
    comparator: "mcq_exact",
    hint: "Le numérateur commence par $u'v$ : l'ordre compte, contrairement au produit.",
    explanation: exp(
      "La dérivée d'un quotient est $\\left(\\dfrac{u}{v}\\right)' = \\dfrac{u'v - uv'}{v^2}$.",
      "Contrairement au produit, la soustraction rend l'ORDRE des termes essentiel.",
      "Écrire $\\dfrac{uv' - u'v}{v^2}$ donne l'opposé du bon résultat, donc un sens de variation inversé.",
      "$\\left(\\dfrac{u}{v}\\right)' = \\dfrac{u'v - uv'}{v^2}$."
    ),
    tags: ["premiere", "maths", "derivation", "operations", "qcm"],
  },
  {
    kind: "fixed",
    id: "premiere_der_op_fixed_8",
    niveau: "premiere-spe",
    matiere: "maths",
    notionId: "derivation",
    microId: "der_operations",
    difficulty: 4,
    theme: "neutral",
    text: "Quelle est la dérivée de $f(x) = (2x + 1)(x - 3)$ ?",
    format: "qcm",
    choices: [
      "$f'(x) = 4x - 5$",
      "$f'(x) = 2$",
      "$f'(x) = 4x + 1$",
      "$f'(x) = 2x - 3$",
    ],
    expected: ["$f'(x) = 4x - 5$"],
    comparator: "mcq_exact",
    hint: "Développe d'abord, ou applique $(uv)' = u'v + uv'$.",
    explanation: exp(
      "On peut développer avant de dériver, ou utiliser la formule du produit.",
      "En développant : $f(x) = 2x^2 - 6x + x - 3 = 2x^2 - 5x - 3$.",
      "$f'(x) = 4x - 5$. Par la formule du produit : $2(x - 3) + (2x + 1) \\times 1 = 4x - 5$ : même résultat.",
      "$f'(x) = 4x - 5$. (Dériver chaque facteur séparément donnerait $2$ : c'est faux.)"
    ),
    tags: ["premiere", "maths", "derivation", "operations", "qcm"],
  },
  {
    kind: "fixed",
    id: "premiere_der_op_fixed_9",
    niveau: "premiere-spe",
    matiere: "maths",
    notionId: "derivation",
    microId: "der_operations",
    difficulty: 4,
    theme: "neutral",
    text: "Pour $f(x) = x^3 - 3x$, combien vaut $f'(2)$ ?",
    format: "short",
    expected: ["9"],
    comparator: "number_equal",
    hint: "Dérive d'abord, remplace ENSUITE par $2$.",
    explanation: exp(
      "On calcule d'abord la fonction dérivée, puis on l'évalue en $2$.",
      "$f'(x) = 3x^2 - 3$.",
      "$f'(2) = 3 \\times 4 - 3 = 12 - 3 = 9$.",
      "$f'(2) = 9$."
    ),
    tags: ["premiere", "maths", "derivation", "operations", "short"],
  },
  {
    kind: "fixed",
    id: "premiere_der_op_fixed_10",
    niveau: "premiere-spe",
    matiere: "maths",
    notionId: "derivation",
    microId: "der_operations",
    difficulty: 5,
    theme: "neutral",
    text: "Quelle est la dérivée de $f(x) = \\dfrac{x}{x + 1}$ ?",
    format: "qcm",
    choices: [
      "$f'(x) = \\dfrac{1}{(x+1)^2}$",
      "$f'(x) = 1$",
      "$f'(x) = \\dfrac{-1}{(x+1)^2}$",
      "$f'(x) = \\dfrac{2x + 1}{(x+1)^2}$",
    ],
    expected: ["$f'(x) = \\dfrac{1}{(x+1)^2}$"],
    comparator: "mcq_exact",
    hint: "$u = x$, $v = x + 1$, donc $u' = 1$ et $v' = 1$.",
    explanation: exp(
      "On applique $\\left(\\dfrac{u}{v}\\right)' = \\dfrac{u'v - uv'}{v^2}$.",
      "Avec $u = x$, $u' = 1$, $v = x + 1$, $v' = 1$ : $f'(x) = \\dfrac{1 \\times (x+1) - x \\times 1}{(x+1)^2}$.",
      "$= \\dfrac{x + 1 - x}{(x+1)^2} = \\dfrac{1}{(x+1)^2}$.",
      "$f'(x) = \\dfrac{1}{(x+1)^2}$ : toujours positive, la fonction est donc croissante."
    ),
    tags: ["premiere", "maths", "derivation", "operations", "qcm"],
  },
  {
    kind: "fixed",
    id: "premiere_der_op_fixed_11",
    niveau: "premiere-spe",
    matiere: "maths",
    notionId: "derivation",
    microId: "der_operations",
    difficulty: 5,
    theme: "neutral",
    text: "Quelle est la dérivée de $f(x) = 4\\sqrt{x}$ sur $]0 ; +\\infty[$ ?",
    format: "qcm",
    choices: [
      "$f'(x) = \\dfrac{2}{\\sqrt{x}}$",
      "$f'(x) = \\dfrac{4}{\\sqrt{x}}$",
      "$f'(x) = \\dfrac{1}{2\\sqrt{x}}$",
      "$f'(x) = 4\\sqrt{x}$",
    ],
    expected: ["$f'(x) = \\dfrac{2}{\\sqrt{x}}$"],
    comparator: "mcq_exact",
    hint: "Le coefficient $4$ reste en facteur : $4 \\times \\dfrac{1}{2\\sqrt{x}}$.",
    explanation: exp(
      "Multiplier une fonction par un nombre multiplie sa dérivée par ce même nombre : $(ku)' = k u'$.",
      "$(\\sqrt{x})' = \\dfrac{1}{2\\sqrt{x}}$, donc $f'(x) = 4 \\times \\dfrac{1}{2\\sqrt{x}}$.",
      "$= \\dfrac{4}{2\\sqrt{x}} = \\dfrac{2}{\\sqrt{x}}$.",
      "$f'(x) = \\dfrac{2}{\\sqrt{x}}$."
    ),
    tags: ["premiere", "maths", "derivation", "operations", "qcm"],
  },
  {
    kind: "template",
    id: "premiere_der_op_tpl_1",
    niveau: "premiere-spe",
    matiere: "maths",
    notionId: "derivation",
    microId: "der_operations",
    difficulty: 3,
    theme: "neutral",
    hint: "Dérive terme à terme.",
    tags: ["premiere", "maths", "derivation", "operations", "template"],
    generate: () => {
      const a = randomInt(1, 5);
      const b = randomInt(1, 6);
      const c = randomInt(-5, 5);
      const correct = `$f'(x) = ${2 * a}x ${b >= 0 ? "+ " + b : "- " + -b}$`;
      const choices = [
        correct,
        `$f'(x) = ${a}x ${b >= 0 ? "+ " + b : "- " + -b}$`,
        `$f'(x) = ${2 * a}x ${b >= 0 ? "+ " + b : "- " + -b} ${c >= 0 ? "+ " + c : "- " + -c}$`,
        `$f'(x) = ${2 * a}x$`,
      ];
      return {
        text: `Quelle est la dérivée de $f(x) = ${a}x^2 ${b >= 0 ? "+ " + b : "- " + -b}x ${c >= 0 ? "+ " + c : "- " + -c}$ ?`,
        format: "qcm",
        choices,
        expected: [correct],
        comparator: "mcq_exact",
        explanation: exp(
          "On dérive chaque terme et la constante disparaît.",
          `$(${a}x^2)' = ${2 * a}x$, $(${b}x)' = ${b}$, $(${c})' = 0$.`,
          `$f'(x) = ${2 * a}x ${b >= 0 ? "+ " + b : "- " + -b}$.`,
          `${correct}.`
        ),
      };
    },
  },
  {
    kind: "template",
    id: "premiere_der_op_tpl_2",
    niveau: "premiere-spe",
    matiere: "maths",
    notionId: "derivation",
    microId: "der_operations",
    difficulty: 4,
    theme: "neutral",
    hint: "Dérive puis remplace.",
    tags: ["premiere", "maths", "derivation", "operations", "template"],
    generate: () => {
      const b = randomInt(-6, 6);
      const k = randomInt(1, 4);
      const val = 2 * k + b;
      return {
        text: `Pour $f(x) = x^2 ${b >= 0 ? "+ " + b : "- " + -b}x$, combien vaut $f'(${k})$ ?`,
        format: "short",
        expected: [String(val)],
        comparator: "number_equal",
        explanation: exp(
          "On dérive : $f'(x) = 2x " + (b >= 0 ? "+ " + b : "- " + -b) + "$.",
          `Puis on remplace $x$ par $${k}$.`,
          `$f'(${k}) = 2 \\times ${k} ${b >= 0 ? "+ " + b : "- " + -b} = ${val}$.`,
          `$f'(${k}) = ${val}$.`
        ),
      };
    },
  },

  /* ===================== DER_TANGENTE ===================== */
  {
    kind: "fixed",
    id: "premiere_der_tan_fixed_1",
    niveau: "premiere-spe",
    matiere: "maths",
    notionId: "derivation",
    microId: "der_tangente",
    difficulty: 2,
    theme: "neutral",
    text: "L'équation de la tangente à $\\mathcal{C}_f$ au point d'abscisse $a$ est :",
    format: "qcm",
    choices: [
      "$y = f'(a)(x - a) + f(a)$",
      "$y = f(a)(x - a) + f'(a)$",
      "$y = f'(a)x + f(a)$",
      "$y = f'(a)(x + a) - f(a)$",
    ],
    expected: ["$y = f'(a)(x - a) + f(a)$"],
    comparator: "mcq_exact",
    hint: "Pente $f'(a)$, passe par $(a ; f(a))$.",
    explanation: exp(
      "La tangente a pour pente le nombre dérivé $f'(a)$ et passe par $(a ; f(a))$.",
      "On écrit l'équation d'une droite de pente $f'(a)$ passant par ce point.",
      "$y = f'(a)(x - a) + f(a)$.",
      "$y = f'(a)(x - a) + f(a)$."
    ),
    tags: ["premiere", "maths", "derivation", "tangente", "qcm"],
  },
  {
    kind: "fixed",
    id: "premiere_der_tan_fixed_2",
    niveau: "premiere-spe",
    matiere: "maths",
    notionId: "derivation",
    microId: "der_tangente",
    difficulty: 3,
    theme: "neutral",
    text: "Soit $f(x) = x^2$. Quelle est la pente de la tangente au point d'abscisse $a = 2$ ?",
    format: "short",
    expected: ["4"],
    comparator: "number_equal",
    hint: "Pente $= f'(2)$ avec $f'(x) = 2x$.",
    explanation: exp(
      "La pente de la tangente est le nombre dérivé $f'(a)$.",
      "$f'(x) = 2x$, donc $f'(2) = 4$.",
      "La pente vaut $4$.",
      "Pente $= 4$."
    ),
    canvas: tangente(0, 0, 2),
    tags: ["premiere", "maths", "derivation", "tangente", "canvas", "short"],
  },
  {
    kind: "fixed",
    id: "premiere_der_tan_fixed_3",
    niveau: "premiere-spe",
    matiere: "maths",
    notionId: "derivation",
    microId: "der_tangente",
    difficulty: 4,
    theme: "neutral",
    text: "Soit $f(x) = x^2$. Quelle est l'équation de la tangente en $a = 1$ ?",
    format: "qcm",
    choices: ["$y = 2x - 1$", "$y = 2x + 1$", "$y = x - 1$", "$y = 2x$"],
    expected: ["$y = 2x - 1$"],
    comparator: "mcq_exact",
    hint: "$f(1) = 1$, $f'(1) = 2$.",
    explanation: exp(
      "On utilise $y = f'(a)(x - a) + f(a)$.",
      "$f(1) = 1$ et $f'(1) = 2$ : $y = 2(x - 1) + 1$.",
      "$y = 2x - 2 + 1 = 2x - 1$.",
      "$y = 2x - 1$."
    ),
    canvas: tangente(0, 0, 1),
    tags: ["premiere", "maths", "derivation", "tangente", "canvas", "qcm"],
  },
  {
    kind: "fixed",
    id: "premiere_der_tan_fixed_4",
    niveau: "premiere-spe",
    matiere: "maths",
    notionId: "derivation",
    microId: "der_tangente",
    difficulty: 3,
    theme: "neutral",
    text: "Si $f'(a) = 0$, la tangente au point d'abscisse $a$ est :",
    format: "qcm",
    choices: ["horizontale", "verticale", "de pente $1$", "confondue avec l'axe des ordonnées"],
    expected: ["horizontale"],
    comparator: "mcq_exact",
    hint: "Pente nulle.",
    explanation: exp(
      "La pente de la tangente est $f'(a)$.",
      "Si $f'(a) = 0$, la pente est nulle.",
      "Une droite de pente nulle est horizontale.",
      "La tangente est horizontale."
    ),
    tags: ["premiere", "maths", "derivation", "tangente", "qcm"],
  },
  {
    kind: "fixed",
    id: "premiere_der_tan_fixed_5",
    niveau: "premiere-spe",
    matiere: "maths",
    notionId: "derivation",
    microId: "der_tangente",
    difficulty: 4,
    theme: "neutral",
    text: "Soit $f(x) = x^2 - 2x$. Quelle est l'ordonnée à l'origine de la tangente en $a = 0$ ?",
    format: "short",
    expected: ["0"],
    comparator: "number_equal",
    hint: "Tangente : $y = f'(0)(x - 0) + f(0)$.",
    explanation: exp(
      "On écrit la tangente en $a = 0$.",
      "$f(0) = 0$, $f'(x) = 2x - 2$ donc $f'(0) = -2$ : $y = -2x + 0$.",
      "L'ordonnée à l'origine est $f(0) = 0$.",
      "Ordonnée à l'origine $= 0$."
    ),
    canvas: tangente(-2, 0, 0),
    tags: ["premiere", "maths", "derivation", "tangente", "canvas", "short"],
  },
  {
    kind: "fixed",
    id: "premiere_der_tan_fixed_6",
    niveau: "premiere-spe",
    matiere: "maths",
    notionId: "derivation",
    microId: "der_tangente",
    difficulty: 3,
    theme: "neutral",
    text: "Soit $f(x) = x^3$. Quelle est la pente de la tangente au point d'abscisse $a = 2$ ?",
    format: "short",
    expected: ["12"],
    comparator: "number_equal",
    hint: "La pente vaut $f'(2)$, avec $f'(x) = 3x^2$.",
    explanation: exp(
      "Le coefficient directeur de la tangente au point d'abscisse $a$ est le nombre dérivé $f'(a)$.",
      "$f'(x) = 3x^2$, donc $f'(2) = 3 \\times 2^2$.",
      "$= 3 \\times 4 = 12$.",
      "La pente vaut $12$."
    ),
    tags: ["premiere", "maths", "derivation", "tangente", "short"],
  },
  {
    kind: "fixed",
    id: "premiere_der_tan_fixed_7",
    niveau: "premiere-spe",
    matiere: "maths",
    notionId: "derivation",
    microId: "der_tangente",
    difficulty: 5,
    theme: "neutral",
    text: "Soit $f(x) = x^2 - 3x$. Quelle est l'équation de la tangente au point d'abscisse $a = 1$ ?",
    format: "qcm",
    choices: ["$y = -x - 1$", "$y = -x + 1$", "$y = x - 3$", "$y = -2x$"],
    expected: ["$y = -x - 1$"],
    comparator: "mcq_exact",
    hint: "$y = f'(1)(x - 1) + f(1)$ : calcule d'abord $f(1)$ et $f'(1)$.",
    explanation: exp(
      "L'équation de la tangente en $a$ est $y = f'(a)(x - a) + f(a)$.",
      "$f(1) = 1 - 3 = -2$ ; $f'(x) = 2x - 3$ donc $f'(1) = -1$.",
      "$y = -1(x - 1) - 2 = -x + 1 - 2 = -x - 1$.",
      "La tangente a pour équation $y = -x - 1$."
    ),
    canvas: tangente(-3, 0, 1),
    tags: ["premiere", "maths", "derivation", "tangente", "canvas", "qcm"],
  },
  {
    kind: "fixed",
    id: "premiere_der_tan_fixed_8",
    niveau: "premiere-spe",
    matiere: "maths",
    notionId: "derivation",
    microId: "der_tangente",
    difficulty: 4,
    theme: "neutral",
    text: "Soit $f(x) = x^2 - 4x$. En quelle abscisse la tangente est-elle horizontale ?",
    format: "short",
    expected: ["2"],
    comparator: "number_equal",
    hint: "Une tangente horizontale a une pente nulle : résous $f'(x) = 0$.",
    explanation: exp(
      "Une tangente est horizontale lorsque son coefficient directeur $f'(x)$ est nul.",
      "$f'(x) = 2x - 4$, on résout $2x - 4 = 0$.",
      "$2x = 4$ donc $x = 2$.",
      "La tangente est horizontale au point d'abscisse $2$ — c'est le sommet de la parabole."
    ),
    tags: ["premiere", "maths", "derivation", "tangente", "short"],
  },
  {
    kind: "fixed",
    id: "premiere_der_tan_fixed_9",
    niveau: "premiere-spe",
    matiere: "maths",
    notionId: "derivation",
    microId: "der_tangente",
    difficulty: 4,
    theme: "neutral",
    text: "Une fonction $f$ vérifie $f(2) = 5$ et $f'(2) = 3$. Quelle est l'équation de la tangente au point d'abscisse $2$ ?",
    format: "qcm",
    choices: ["$y = 3x - 1$", "$y = 3x + 5$", "$y = 5x - 3$", "$y = 2x + 3$"],
    expected: ["$y = 3x - 1$"],
    comparator: "mcq_exact",
    hint: "$y = 3(x - 2) + 5$, puis développe.",
    explanation: exp(
      "On applique $y = f'(a)(x - a) + f(a)$ avec $a = 2$.",
      "$y = 3(x - 2) + 5$.",
      "$= 3x - 6 + 5 = 3x - 1$.",
      "La tangente a pour équation $y = 3x - 1$."
    ),
    tags: ["premiere", "maths", "derivation", "tangente", "qcm"],
  },
  {
    kind: "fixed",
    id: "premiere_der_tan_fixed_10",
    niveau: "premiere-spe",
    matiere: "maths",
    notionId: "derivation",
    microId: "der_tangente",
    difficulty: 5,
    theme: "neutral",
    text: "Soit $f(x) = x^2 + 2x$. Quelle est l'équation de la tangente au point d'abscisse $a = -1$ ?",
    format: "qcm",
    choices: ["$y = -1$", "$y = 0$", "$y = -x - 1$", "$x = -1$"],
    expected: ["$y = -1$"],
    comparator: "mcq_exact",
    hint: "Calcule $f'(-1)$ : que vaut la pente ?",
    explanation: exp(
      "On applique $y = f'(a)(x - a) + f(a)$.",
      "$f(-1) = 1 - 2 = -1$ ; $f'(x) = 2x + 2$ donc $f'(-1) = 0$.",
      "$y = 0 \\times (x + 1) - 1 = -1$ : la tangente est HORIZONTALE.",
      "La tangente a pour équation $y = -1$ (une droite horizontale s'écrit $y = \\dots$, pas $x = \\dots$)."
    ),
    canvas: tangente(2, 0, -1),
    tags: ["premiere", "maths", "derivation", "tangente", "canvas", "qcm"],
  },
  {
    kind: "fixed",
    id: "premiere_der_tan_fixed_11",
    niveau: "premiere-spe",
    matiere: "maths",
    notionId: "derivation",
    microId: "der_tangente",
    difficulty: 3,
    theme: "neutral",
    text: "Dans l'équation $y = f'(a)(x - a) + f(a)$, que représente $f'(a)$ ?",
    format: "qcm",
    choices: [
      "le coefficient directeur de la tangente",
      "l'ordonnée du point de contact",
      "l'ordonnée à l'origine de la tangente",
      "l'abscisse du point de contact",
    ],
    expected: ["le coefficient directeur de la tangente"],
    comparator: "mcq_exact",
    hint: "Compare avec la forme $y = mx + p$ d'une droite.",
    explanation: exp(
      "Une droite s'écrit $y = mx + p$, où $m$ est le coefficient directeur.",
      "Dans $y = f'(a)(x - a) + f(a)$, c'est $f'(a)$ qui multiplie $x$.",
      "$f(a)$, lui, est l'ordonnée du point de contact — pas l'ordonnée à l'origine, sauf si $a = 0$.",
      "$f'(a)$ est le coefficient directeur de la tangente."
    ),
    tags: ["premiere", "maths", "derivation", "tangente", "qcm"],
  },
  {
    kind: "template",
    id: "premiere_der_tan_tpl_1",
    niveau: "premiere-spe",
    matiere: "maths",
    notionId: "derivation",
    microId: "der_tangente",
    difficulty: 3,
    theme: "neutral",
    hint: "Pente $= f'(a) = 2a$ pour $f(x) = x^2$.",
    tags: ["premiere", "maths", "derivation", "tangente", "template"],
    generate: () => {
      const a = randomInt(1, 4);
      const pente = 2 * a;
      return {
        text: `Soit $f(x) = x^2$. Quelle est la pente de la tangente au point d'abscisse $a = ${a}$ ?`,
        format: "short",
        expected: [String(pente)],
        comparator: "number_equal",
        explanation: exp(
          "La pente de la tangente est $f'(a)$.",
          `$f'(x) = 2x$, donc $f'(${a}) = ${pente}$.`,
          `La pente vaut $${pente}$.`,
          `Pente $= ${pente}$.`
        ),
      };
    },
  },
  {
    kind: "template",
    id: "premiere_der_tan_tpl_2",
    niveau: "premiere-spe",
    matiere: "maths",
    notionId: "derivation",
    microId: "der_tangente",
    difficulty: 4,
    theme: "neutral",
    hint: "$y = f'(a)(x - a) + f(a)$.",
    tags: ["premiere", "maths", "derivation", "tangente", "template"],
    generate: () => {
      const a = randomInt(1, 3);
      const pente = 2 * a;
      const fa = a * a;
      const ord = fa - pente * a; // = -a²
      const correct = `$y = ${pente}x ${ord >= 0 ? "+ " + ord : "- " + -ord}$`;
      const choices = [
        correct,
        `$y = ${pente}x ${fa >= 0 ? "+ " + fa : "- " + -fa}$`,
        `$y = ${a}x ${ord >= 0 ? "+ " + ord : "- " + -ord}$`,
        `$y = ${pente}x$`,
      ];
      return {
        text: `Soit $f(x) = x^2$. Quelle est l'équation de la tangente en $a = ${a}$ ?`,
        format: "qcm",
        choices,
        expected: [correct],
        comparator: "mcq_exact",
        explanation: exp(
          "On utilise $y = f'(a)(x - a) + f(a)$.",
          `$f(${a}) = ${fa}$ et $f'(${a}) = ${pente}$ : $y = ${pente}(x - ${a}) + ${fa}$.`,
          `$y = ${pente}x ${ord >= 0 ? "+ " + ord : "- " + -ord}$.`,
          `${correct}.`
        ),
      };
    },
  },
];
