// lib/tutor-v4/questionBank/premiere-spe/maths/exponentielle.bank.ts
//
// Chapitre : Fonction exponentielle (notion "exponentielle")
// microSkills :
//   exp_proprietes   — propriétés algébriques (e^{x+y} = e^x·e^y, e^{-x} = 1/e^x, ...)
//   exp_simplifier   — simplifier une expression avec l'exponentielle
//   exp_derivee      — dérivée, signe et variations de l'exponentielle
//   exp_modelisation — modéliser une croissance/décroissance exponentielle
//
// PÉRIMÈTRE BO 2019 Première spé. Conventions : LaTeX, règle QCM. Canvas : fonctionGraphique (courbe exp via points).

import type { TutorBankItemV4, CanvasFigure } from "@/lib/tutor-v4/types";

function randomInt(min: number, max: number) {
  return Math.floor(Math.random() * (max - min + 1)) + min;
}

function exp(definition: string, methode: string, calcul: string, conclusion: string) {
  return (
    `Définition : ${definition}\n\n` +
    `Méthode : ${methode}\n\n` +
    `Calcul / Observation : ${calcul}\n\n` +
    `Conclusion : ${conclusion}`
  );
}

function echantillonne(f: (x: number) => number, xmin: number, xmax: number, step: number) {
  const pts: { x: number; y: number }[] = [];
  for (let x = xmin; x <= xmax + 1e-9; x += step) {
    const xr = Math.round(x * 100) / 100;
    pts.push({ x: xr, y: Math.round(f(xr) * 100) / 100 });
  }
  return pts;
}

const courbeExp: CanvasFigure = {
  kind: "fonctionGraphique",
  size: { width: 320, height: 300 },
  xmin: -3,
  xmax: 3,
  ymin: -1,
  ymax: 9,
  grille: true,
  courbes: [{ id: "f", type: "points", couleur: "#2563eb", points: echantillonne((x) => Math.exp(x), -3, 2.1, 0.3) }],
  misesEnEvidence: [{ point: { x: 0, y: 1, label: "(0 ; 1)", couleur: "#dc2626" } }],
};

export const exponentielleBank: TutorBankItemV4[] = [
  /* ===================== EXP_PROPRIETES ===================== */
  {
    kind: "fixed",
    id: "premiere_exp_prop_fixed_1",
    niveau: "premiere-spe",
    matiere: "maths",
    notionId: "exponentielle",
    microId: "exp_proprietes",
    difficulty: 1,
    theme: "neutral",
    text: "À quoi est égal $e^{x} \\times e^{y}$ ?",
    format: "qcm",
    choices: ["$e^{x+y}$", "$e^{xy}$", "$e^{x-y}$", "$e^x + e^y$"],
    expected: ["$e^{x+y}$"],
    comparator: "mcq_exact",
    hint: "Produit d'exponentielles → somme des exposants.",
    explanation: exp(
      "L'exponentielle transforme les produits en sommes d'exposants.",
      "$e^{x} \\times e^{y} = e^{x+y}$.",
      "C'est la propriété fondamentale.",
      "$e^{x+y}$."
    ),
    tags: ["premiere", "maths", "exponentielle", "proprietes", "qcm"],
  },
  {
    kind: "fixed",
    id: "premiere_exp_prop_fixed_2",
    niveau: "premiere-spe",
    matiere: "maths",
    notionId: "exponentielle",
    microId: "exp_proprietes",
    difficulty: 2,
    theme: "neutral",
    text: "À quoi est égal $e^{-x}$ ?",
    format: "qcm",
    choices: ["$\\dfrac{1}{e^x}$", "$-e^x$", "$e^x$", "$1 - e^x$"],
    expected: ["$\\dfrac{1}{e^x}$"],
    comparator: "mcq_exact",
    hint: "$e^x \\times e^{-x} = 1$.",
    explanation: exp(
      "On utilise $e^x \\times e^{-x} = e^0 = 1$.",
      "Donc $e^{-x}$ est l'inverse de $e^x$.",
      "$e^{-x} = \\dfrac{1}{e^x}$.",
      "$\\dfrac{1}{e^x}$."
    ),
    tags: ["premiere", "maths", "exponentielle", "proprietes", "qcm"],
  },
  {
    kind: "fixed",
    id: "premiere_exp_prop_fixed_3",
    niveau: "premiere-spe",
    matiere: "maths",
    notionId: "exponentielle",
    microId: "exp_proprietes",
    difficulty: 2,
    theme: "neutral",
    text: "Combien vaut $e^0$ ?",
    format: "short",
    expected: ["1"],
    comparator: "number_equal",
    hint: "Cas particulier.",
    explanation: exp(
      "Par définition, l'exponentielle vérifie $e^0 = 1$.",
      "C'est la condition initiale.",
      "$e^0 = 1$.",
      "$e^0 = 1$."
    ),
    tags: ["premiere", "maths", "exponentielle", "proprietes", "short"],
  },
  {
    kind: "fixed",
    id: "premiere_exp_prop_fixed_4",
    niveau: "premiere-spe",
    matiere: "maths",
    notionId: "exponentielle",
    microId: "exp_proprietes",
    difficulty: 3,
    theme: "neutral",
    text: "À quoi est égal $\\dfrac{e^{x}}{e^{y}}$ ?",
    format: "qcm",
    choices: ["$e^{x-y}$", "$e^{x+y}$", "$e^{x/y}$", "$e^{xy}$"],
    expected: ["$e^{x-y}$"],
    comparator: "mcq_exact",
    hint: "Quotient → différence des exposants.",
    explanation: exp(
      "Le quotient d'exponentielles se traduit par une différence d'exposants.",
      "$\\dfrac{e^x}{e^y} = e^{x-y}$.",
      "C'est la propriété du quotient.",
      "$e^{x-y}$."
    ),
    tags: ["premiere", "maths", "exponentielle", "proprietes", "qcm"],
  },
  {
    kind: "fixed",
    id: "premiere_exp_prop_fixed_5",
    niveau: "premiere-spe",
    matiere: "maths",
    notionId: "exponentielle",
    microId: "exp_proprietes",
    difficulty: 3,
    theme: "neutral",
    text: "À quoi est égal $\\left(e^{x}\\right)^{n}$ ?",
    format: "qcm",
    choices: ["$e^{nx}$", "$e^{x^n}$", "$n e^{x}$", "$e^{x+n}$"],
    expected: ["$e^{nx}$"],
    comparator: "mcq_exact",
    hint: "Puissance → produit des exposants.",
    explanation: exp(
      "Élever une exponentielle à une puissance multiplie l'exposant.",
      "$\\left(e^x\\right)^n = e^{nx}$.",
      "C'est la propriété de la puissance.",
      "$e^{nx}$."
    ),
    tags: ["premiere", "maths", "exponentielle", "proprietes", "qcm"],
  },
  {
    kind: "fixed",
    id: "premiere_exp_prop_fixed_6",
    niveau: "premiere-spe",
    matiere: "maths",
    notionId: "exponentielle",
    microId: "exp_proprietes",
    difficulty: 2,
    theme: "neutral",
    text: "Quelle est une valeur approchée de $e$ ?",
    format: "qcm",
    choices: ["$2{,}718$", "$3{,}141$", "$1{,}618$", "$1{,}414$"],
    expected: ["$2{,}718$"],
    comparator: "mcq_exact",
    hint: "Ce n'est ni $\\pi$, ni le nombre d'or, ni $\\sqrt{2}$.",
    explanation: exp(
      "Le nombre $e$ est la base de la fonction exponentielle : c'est l'unique nombre tel que $e^1 = e$ et dont la fonction exponentielle est sa propre dérivée.",
      "Sa valeur approchée est $e \\approx 2{,}718$.",
      "$3{,}141$ est $\\pi$, $1{,}618$ le nombre d'or et $1{,}414$ vaut $\\sqrt{2}$.",
      "$e \\approx 2{,}718$."
    ),
    tags: ["premiere", "maths", "exponentielle", "proprietes", "qcm"],
  },
  {
    kind: "fixed",
    id: "premiere_exp_prop_fixed_7",
    niveau: "premiere-spe",
    matiere: "maths",
    notionId: "exponentielle",
    microId: "exp_proprietes",
    difficulty: 3,
    theme: "neutral",
    text: "À quoi est égal $e^2 \\times e^5$ ?",
    format: "qcm",
    choices: ["$e^{7}$", "$e^{10}$", "$2e^{5}$", "$e^{2 \\times 5}$"],
    expected: ["$e^{7}$"],
    comparator: "mcq_exact",
    hint: "Produit d'exponentielles → SOMME des exposants.",
    explanation: exp(
      "La propriété fondamentale est $e^a \\times e^b = e^{a+b}$.",
      "Ici $a = 2$ et $b = 5$ : $e^2 \\times e^5 = e^{2+5}$.",
      "$= e^7$. Multiplier les exposants ($e^{10}$) est l'erreur la plus fréquente : c'est la règle de la PUISSANCE, pas du produit.",
      "$e^2 \\times e^5 = e^7$."
    ),
    tags: ["premiere", "maths", "exponentielle", "proprietes", "qcm"],
  },
  {
    kind: "fixed",
    id: "premiere_exp_prop_fixed_8",
    niveau: "premiere-spe",
    matiere: "maths",
    notionId: "exponentielle",
    microId: "exp_proprietes",
    difficulty: 3,
    theme: "neutral",
    text: "À quoi est égal $\\dfrac{e^{5}}{e^{3}}$ ?",
    format: "qcm",
    choices: ["$e^{2}$", "$e^{8}$", "$e^{\\frac{5}{3}}$", "$e^{15}$"],
    expected: ["$e^{2}$"],
    comparator: "mcq_exact",
    hint: "Quotient d'exponentielles → DIFFÉRENCE des exposants.",
    explanation: exp(
      "La règle du quotient est $\\dfrac{e^a}{e^b} = e^{a-b}$.",
      "Ici $\\dfrac{e^5}{e^3} = e^{5-3}$.",
      "$= e^2$. On ne divise pas les exposants entre eux.",
      "$\\dfrac{e^5}{e^3} = e^2$."
    ),
    tags: ["premiere", "maths", "exponentielle", "proprietes", "qcm"],
  },
  {
    kind: "fixed",
    id: "premiere_exp_prop_fixed_9",
    niveau: "premiere-spe",
    matiere: "maths",
    notionId: "exponentielle",
    microId: "exp_proprietes",
    difficulty: 3,
    theme: "neutral",
    text: "À quoi est égal $\\left(e^{2}\\right)^{3}$ ?",
    format: "qcm",
    choices: ["$e^{6}$", "$e^{5}$", "$e^{8}$", "$3e^{2}$"],
    expected: ["$e^{6}$"],
    comparator: "mcq_exact",
    hint: "Puissance d'une puissance → PRODUIT des exposants.",
    explanation: exp(
      "La règle est $\\left(e^a\\right)^n = e^{na}$.",
      "Ici $\\left(e^2\\right)^3 = e^{2 \\times 3}$.",
      "$= e^6$. C'est ici qu'on multiplie les exposants — pas dans un produit d'exponentielles, où on les additionne.",
      "$\\left(e^2\\right)^3 = e^6$."
    ),
    tags: ["premiere", "maths", "exponentielle", "proprietes", "qcm"],
  },
  {
    kind: "fixed",
    id: "premiere_exp_prop_fixed_10",
    niveau: "premiere-spe",
    matiere: "maths",
    notionId: "exponentielle",
    microId: "exp_proprietes",
    difficulty: 5,
    theme: "neutral",
    text: "A-t-on $e^x + e^y = e^{x+y}$ ?",
    format: "qcm",
    choices: [
      "non : c'est le PRODUIT qui donne $e^{x+y}$",
      "oui, toujours",
      "oui, seulement si $x = y$",
      "oui, seulement si $x$ et $y$ sont positifs",
    ],
    expected: ["non : c'est le PRODUIT qui donne $e^{x+y}$"],
    comparator: "mcq_exact",
    hint: "Teste avec $x = y = 0$ : à gauche $1 + 1$, à droite $e^0$.",
    explanation: exp(
      "Les propriétés de l'exponentielle transforment un PRODUIT en somme d'exposants, jamais une somme.",
      "Contre-exemple : pour $x = y = 0$, à gauche $e^0 + e^0 = 2$, à droite $e^0 = 1$. Les deux diffèrent.",
      "L'égalité correcte est $e^x \\times e^y = e^{x+y}$ ; une somme d'exponentielles ne se simplifie pas (au mieux, elle se factorise).",
      "Non : c'est le produit qui donne $e^{x+y}$."
    ),
    tags: ["premiere", "maths", "exponentielle", "proprietes", "qcm"],
  },
  {
    kind: "fixed",
    id: "premiere_exp_prop_fixed_11",
    niveau: "premiere-spe",
    matiere: "maths",
    notionId: "exponentielle",
    microId: "exp_proprietes",
    difficulty: 3,
    theme: "neutral",
    text: "Comment s'écrit autrement $e^{-3}$ ?",
    format: "qcm",
    choices: ["$\\dfrac{1}{e^{3}}$", "$-e^{3}$", "$-\\dfrac{1}{e^{3}}$", "$e^{3}$"],
    expected: ["$\\dfrac{1}{e^{3}}$"],
    comparator: "mcq_exact",
    hint: "Un exposant négatif donne un inverse, pas un nombre négatif.",
    explanation: exp(
      "Par définition, $e^{-a} = \\dfrac{1}{e^{a}}$.",
      "Ici $e^{-3} = \\dfrac{1}{e^3}$.",
      "L'exponentielle est TOUJOURS strictement positive : $e^{-3}$ est un petit nombre positif ($\\approx 0{,}05$), jamais un nombre négatif.",
      "$e^{-3} = \\dfrac{1}{e^3}$."
    ),
    tags: ["premiere", "maths", "exponentielle", "proprietes", "qcm"],
  },
  {
    kind: "template",
    id: "premiere_exp_prop_tpl_1",
    niveau: "premiere-spe",
    matiere: "maths",
    notionId: "exponentielle",
    microId: "exp_proprietes",
    difficulty: 2,
    theme: "neutral",
    hint: "Produit → somme des exposants.",
    tags: ["premiere", "maths", "exponentielle", "proprietes", "template"],
    generate: () => {
      const a = randomInt(2, 6);
      const b = randomInt(2, 6);
      const correct = `$e^{${a + b}}$`;
      const choices = [correct, `$e^{${a * b}}$`, `$e^{${Math.abs(a - b)}}$`, `$2e^{${a + b}}$`];
      return {
        text: `Simplifie $e^{${a}} \\times e^{${b}}$.`,
        format: "qcm",
        choices,
        expected: [correct],
        comparator: "mcq_exact",
        explanation: exp(
          "On ajoute les exposants.",
          `$e^{${a}} \\times e^{${b}} = e^{${a} + ${b}}$.`,
          `$= e^{${a + b}}$.`,
          `$e^{${a + b}}$.`
        ),
      };
    },
  },
  {
    kind: "template",
    id: "premiere_exp_prop_tpl_2",
    niveau: "premiere-spe",
    matiere: "maths",
    notionId: "exponentielle",
    microId: "exp_proprietes",
    difficulty: 3,
    theme: "neutral",
    hint: "Quotient → différence des exposants.",
    tags: ["premiere", "maths", "exponentielle", "proprietes", "template"],
    generate: () => {
      const a = randomInt(5, 9);
      const b = randomInt(1, 4);
      const correct = `$e^{${a - b}}$`;
      const choices = [correct, `$e^{${a + b}}$`, `$e^{${a * b}}$`, `$e^{${a}/${b}}$`];
      return {
        text: `Simplifie $\\dfrac{e^{${a}}}{e^{${b}}}$.`,
        format: "qcm",
        choices,
        expected: [correct],
        comparator: "mcq_exact",
        explanation: exp(
          "On soustrait les exposants.",
          `$\\dfrac{e^{${a}}}{e^{${b}}} = e^{${a} - ${b}}$.`,
          `$= e^{${a - b}}$.`,
          `$e^{${a - b}}$.`
        ),
      };
    },
  },

  /* ===================== EXP_SIMPLIFIER ===================== */
  {
    kind: "fixed",
    id: "premiere_exp_simp_fixed_1",
    niveau: "premiere-spe",
    matiere: "maths",
    notionId: "exponentielle",
    microId: "exp_simplifier",
    difficulty: 2,
    theme: "neutral",
    text: "Simplifie $e^x \\times e^{-x}$.",
    format: "short",
    expected: ["1"],
    comparator: "number_equal",
    hint: "Somme des exposants : $x + (-x)$.",
    explanation: exp(
      "On ajoute les exposants.",
      "$e^x \\times e^{-x} = e^{x - x} = e^0$.",
      "$= 1$.",
      "$e^x \\times e^{-x} = 1$."
    ),
    tags: ["premiere", "maths", "exponentielle", "simplifier", "short"],
  },
  {
    kind: "fixed",
    id: "premiere_exp_simp_fixed_2",
    niveau: "premiere-spe",
    matiere: "maths",
    notionId: "exponentielle",
    microId: "exp_simplifier",
    difficulty: 3,
    theme: "neutral",
    text: "Simplifie $\\dfrac{e^{2x} \\times e^{3x}}{e^{x}}$.",
    format: "qcm",
    choices: ["$e^{4x}$", "$e^{6x}$", "$e^{5x}$", "$e^{x}$"],
    expected: ["$e^{4x}$"],
    comparator: "mcq_exact",
    hint: "$2x + 3x - x$.",
    explanation: exp(
      "On combine les exposants : produit → somme, quotient → différence.",
      "$\\dfrac{e^{2x} \\times e^{3x}}{e^x} = e^{2x + 3x - x}$.",
      "$= e^{4x}$.",
      "$e^{4x}$."
    ),
    tags: ["premiere", "maths", "exponentielle", "simplifier", "qcm"],
  },
  {
    kind: "fixed",
    id: "premiere_exp_simp_fixed_3",
    niveau: "premiere-spe",
    matiere: "maths",
    notionId: "exponentielle",
    microId: "exp_simplifier",
    difficulty: 3,
    theme: "neutral",
    text: "Simplifie $\\left(e^{x}\\right)^{3} \\times e^{x}$.",
    format: "qcm",
    choices: ["$e^{4x}$", "$e^{3x}$", "$e^{x^3}$", "$e^{3x^2}$"],
    expected: ["$e^{4x}$"],
    comparator: "mcq_exact",
    hint: "$(e^x)^3 = e^{3x}$.",
    explanation: exp(
      "On applique la puissance puis le produit.",
      "$(e^x)^3 = e^{3x}$, puis $e^{3x} \\times e^x = e^{3x + x}$.",
      "$= e^{4x}$.",
      "$e^{4x}$."
    ),
    tags: ["premiere", "maths", "exponentielle", "simplifier", "qcm"],
  },
  {
    kind: "fixed",
    id: "premiere_exp_simp_fixed_4",
    niveau: "premiere-spe",
    matiere: "maths",
    notionId: "exponentielle",
    microId: "exp_simplifier",
    difficulty: 4,
    theme: "neutral",
    text: "Simplifie $\\dfrac{1}{e^{-2x}}$.",
    format: "qcm",
    choices: ["$e^{2x}$", "$e^{-2x}$", "$-e^{2x}$", "$\\dfrac{1}{e^{2x}}$"],
    expected: ["$e^{2x}$"],
    comparator: "mcq_exact",
    hint: "$\\dfrac{1}{e^{a}} = e^{-a}$.",
    explanation: exp(
      "L'inverse d'une exponentielle change le signe de l'exposant.",
      "$\\dfrac{1}{e^{-2x}} = e^{-(-2x)}$.",
      "$= e^{2x}$.",
      "$e^{2x}$."
    ),
    tags: ["premiere", "maths", "exponentielle", "simplifier", "qcm"],
  },
  {
    kind: "fixed",
    id: "premiere_exp_simp_fixed_5",
    niveau: "premiere-spe",
    matiere: "maths",
    notionId: "exponentielle",
    microId: "exp_simplifier",
    difficulty: 3,
    theme: "neutral",
    text: "Simplifie $e^{2x} \\times e^{-x}$.",
    format: "qcm",
    choices: ["$e^{x}$", "$e^{3x}$", "$e^{-2x^2}$", "$1$"],
    expected: ["$e^{x}$"],
    comparator: "mcq_exact",
    hint: "On additionne les exposants : $2x + (-x)$.",
    explanation: exp(
      "Dans un produit d'exponentielles, on additionne les exposants.",
      "$e^{2x} \\times e^{-x} = e^{2x - x}$.",
      "$= e^{x}$.",
      "$e^{2x} \\times e^{-x} = e^{x}$."
    ),
    tags: ["premiere", "maths", "exponentielle", "simplifier", "qcm"],
  },
  {
    kind: "fixed",
    id: "premiere_exp_simp_fixed_6",
    niveau: "premiere-spe",
    matiere: "maths",
    notionId: "exponentielle",
    microId: "exp_simplifier",
    difficulty: 3,
    theme: "neutral",
    text: "Simplifie $\\dfrac{e^{5x}}{e^{2x}}$.",
    format: "qcm",
    choices: ["$e^{3x}$", "$e^{7x}$", "$e^{2{,}5x}$", "$e^{10x}$"],
    expected: ["$e^{3x}$"],
    comparator: "mcq_exact",
    hint: "On soustrait les exposants.",
    explanation: exp(
      "Dans un quotient d'exponentielles, on soustrait les exposants.",
      "$\\dfrac{e^{5x}}{e^{2x}} = e^{5x - 2x}$.",
      "$= e^{3x}$.",
      "$\\dfrac{e^{5x}}{e^{2x}} = e^{3x}$."
    ),
    tags: ["premiere", "maths", "exponentielle", "simplifier", "qcm"],
  },
  {
    kind: "fixed",
    id: "premiere_exp_simp_fixed_7",
    niveau: "premiere-spe",
    matiere: "maths",
    notionId: "exponentielle",
    microId: "exp_simplifier",
    difficulty: 4,
    theme: "neutral",
    text: "Simplifie $\\left(e^{x}\\right)^{2} \\times e^{-2x}$.",
    format: "qcm",
    choices: ["$1$", "$e^{4x}$", "$e^{-4x}$", "$e^{x}$"],
    expected: ["$1$"],
    comparator: "mcq_exact",
    hint: "Commence par $\\left(e^{x}\\right)^{2} = e^{2x}$.",
    explanation: exp(
      "On applique d'abord la règle de la puissance, puis celle du produit.",
      "$\\left(e^{x}\\right)^{2} = e^{2x}$, donc l'expression vaut $e^{2x} \\times e^{-2x} = e^{2x - 2x}$.",
      "$= e^{0} = 1$.",
      "L'expression est constante et vaut $1$."
    ),
    tags: ["premiere", "maths", "exponentielle", "simplifier", "qcm"],
  },
  {
    kind: "fixed",
    id: "premiere_exp_simp_fixed_8",
    niveau: "premiere-spe",
    matiere: "maths",
    notionId: "exponentielle",
    microId: "exp_simplifier",
    difficulty: 4,
    theme: "neutral",
    text: "Simplifie $e^{x+1} \\times e^{-1}$.",
    format: "qcm",
    choices: ["$e^{x}$", "$e^{x+2}$", "$e^{x-1}$", "$1$"],
    expected: ["$e^{x}$"],
    comparator: "mcq_exact",
    hint: "$(x + 1) + (-1) = ?$",
    explanation: exp(
      "On additionne les exposants, en pensant bien à mettre l'exposant complet entre parenthèses.",
      "$e^{x+1} \\times e^{-1} = e^{(x+1) + (-1)}$.",
      "$= e^{x + 1 - 1} = e^{x}$.",
      "$e^{x+1} \\times e^{-1} = e^{x}$."
    ),
    tags: ["premiere", "maths", "exponentielle", "simplifier", "qcm"],
  },
  {
    kind: "fixed",
    id: "premiere_exp_simp_fixed_9",
    niveau: "premiere-spe",
    matiere: "maths",
    notionId: "exponentielle",
    microId: "exp_simplifier",
    difficulty: 5,
    theme: "neutral",
    text: "Simplifie $\\dfrac{e^{3x} \\times e^{x}}{e^{4x}}$.",
    format: "qcm",
    choices: ["$1$", "$e^{8x}$", "$e^{3x}$", "$e^{-4x}$"],
    expected: ["$1$"],
    comparator: "mcq_exact",
    hint: "Simplifie d'abord le numérateur.",
    explanation: exp(
      "On regroupe le numérateur, puis on soustrait l'exposant du dénominateur.",
      "$e^{3x} \\times e^{x} = e^{4x}$, donc l'expression vaut $\\dfrac{e^{4x}}{e^{4x}} = e^{4x - 4x}$.",
      "$= e^{0} = 1$.",
      "L'expression vaut $1$."
    ),
    tags: ["premiere", "maths", "exponentielle", "simplifier", "qcm"],
  },
  {
    kind: "fixed",
    id: "premiere_exp_simp_fixed_10",
    niveau: "premiere-spe",
    matiere: "maths",
    notionId: "exponentielle",
    microId: "exp_simplifier",
    difficulty: 4,
    theme: "neutral",
    text: "Simplifie $\\left(e^{-x}\\right)^{3}$.",
    format: "qcm",
    choices: ["$e^{-3x}$", "$e^{3x}$", "$-e^{3x}$", "$\\dfrac{1}{3e^{x}}$"],
    expected: ["$e^{-3x}$"],
    comparator: "mcq_exact",
    hint: "On multiplie les exposants, signe compris.",
    explanation: exp(
      "La puissance d'une exponentielle multiplie l'exposant : $\\left(e^a\\right)^n = e^{na}$.",
      "Ici $a = -x$ et $n = 3$ : $\\left(e^{-x}\\right)^{3} = e^{3 \\times (-x)}$.",
      "$= e^{-3x}$. Le résultat reste positif : le signe « moins » est dans l'exposant, pas devant.",
      "$\\left(e^{-x}\\right)^{3} = e^{-3x}$."
    ),
    tags: ["premiere", "maths", "exponentielle", "simplifier", "qcm"],
  },
  {
    kind: "fixed",
    id: "premiere_exp_simp_fixed_11",
    niveau: "premiere-spe",
    matiere: "maths",
    notionId: "exponentielle",
    microId: "exp_simplifier",
    difficulty: 5,
    theme: "neutral",
    text: "Simplifie $\\dfrac{e^{2x} + e^{3x}}{e^{x}}$.",
    format: "qcm",
    choices: [
      "$e^{x} + e^{2x}$",
      "$e^{4x}$",
      "$e^{5x}$",
      "$e^{x} + e^{3x}$",
    ],
    expected: ["$e^{x} + e^{2x}$"],
    comparator: "mcq_exact",
    hint: "Le dénominateur se distribue sur CHAQUE terme du numérateur.",
    explanation: exp(
      "Quand le numérateur est une somme, on divise chaque terme séparément : $\\dfrac{a + b}{c} = \\dfrac{a}{c} + \\dfrac{b}{c}$.",
      "$\\dfrac{e^{2x}}{e^{x}} + \\dfrac{e^{3x}}{e^{x}} = e^{2x - x} + e^{3x - x}$.",
      "$= e^{x} + e^{2x}$. On ne peut pas additionner les exposants du numérateur : ce n'est pas un produit.",
      "$\\dfrac{e^{2x} + e^{3x}}{e^{x}} = e^{x} + e^{2x}$."
    ),
    tags: ["premiere", "maths", "exponentielle", "simplifier", "qcm"],
  },
  {
    kind: "template",
    id: "premiere_exp_simp_tpl_1",
    niveau: "premiere-spe",
    matiere: "maths",
    notionId: "exponentielle",
    microId: "exp_simplifier",
    difficulty: 3,
    theme: "neutral",
    hint: "Additionne et soustrais les exposants.",
    tags: ["premiere", "maths", "exponentielle", "simplifier", "template"],
    generate: () => {
      const a = randomInt(2, 5);
      const b = randomInt(2, 5);
      const c = randomInt(1, 3);
      const k = a + b - c;
      const correct = `$e^{${k}x}$`;
      const choices = [correct, `$e^{${a + b + c}x}$`, `$e^{${a + b}x}$`, `$e^{${k}x^2}$`];
      return {
        text: `Simplifie $\\dfrac{e^{${a}x} \\times e^{${b}x}}{e^{${c}x}}$.`,
        format: "qcm",
        choices,
        expected: [correct],
        comparator: "mcq_exact",
        explanation: exp(
          "Produit → somme, quotient → différence des exposants.",
          `$e^{${a}x + ${b}x - ${c}x}$.`,
          `$= e^{${k}x}$.`,
          `$e^{${k}x}$.`
        ),
      };
    },
  },
  {
    kind: "template",
    id: "premiere_exp_simp_tpl_2",
    niveau: "premiere-spe",
    matiere: "maths",
    notionId: "exponentielle",
    microId: "exp_simplifier",
    difficulty: 2,
    theme: "neutral",
    hint: "Exposants opposés → $e^0 = 1$.",
    tags: ["premiere", "maths", "exponentielle", "simplifier", "template"],
    generate: () => {
      const a = randomInt(2, 7);
      return {
        text: `Simplifie $e^{${a}x} \\times e^{-${a}x}$.`,
        format: "short",
        expected: ["1"],
        comparator: "number_equal",
        explanation: exp(
          "On ajoute les exposants.",
          `$e^{${a}x - ${a}x} = e^0$.`,
          "$= 1$.",
          "Le résultat est $1$."
        ),
      };
    },
  },

  /* ===================== EXP_DERIVEE ===================== */
  {
    kind: "fixed",
    id: "premiere_exp_der_fixed_1",
    niveau: "premiere-spe",
    matiere: "maths",
    notionId: "exponentielle",
    microId: "exp_derivee",
    difficulty: 1,
    theme: "neutral",
    text: "Quelle est la dérivée de $f(x) = e^x$ ?",
    format: "qcm",
    choices: ["$f'(x) = e^x$", "$f'(x) = x e^{x-1}$", "$f'(x) = e^{x-1}$", "$f'(x) = 1$"],
    expected: ["$f'(x) = e^x$"],
    comparator: "mcq_exact",
    hint: "L'exponentielle est sa propre dérivée.",
    explanation: exp(
      "La fonction exponentielle est définie comme égale à sa dérivée.",
      "$(e^x)' = e^x$.",
      "Avec $e^0 = 1$.",
      "$f'(x) = e^x$."
    ),
    tags: ["premiere", "maths", "exponentielle", "derivee", "qcm"],
  },
  {
    kind: "fixed",
    id: "premiere_exp_der_fixed_2",
    niveau: "premiere-spe",
    matiere: "maths",
    notionId: "exponentielle",
    microId: "exp_derivee",
    difficulty: 2,
    theme: "neutral",
    text: "Quel est le signe de $e^x$ sur $\\mathbb{R}$ ?",
    format: "qcm",
    choices: ["toujours strictement positif", "toujours négatif", "positif puis négatif", "nul en $0$"],
    expected: ["toujours strictement positif"],
    comparator: "mcq_exact",
    hint: "La courbe est au-dessus de l'axe des abscisses.",
    explanation: exp(
      "L'exponentielle ne s'annule jamais et reste au-dessus de l'axe des $x$.",
      "Pour tout réel $x$, $e^x > 0$.",
      "Elle est donc strictement positive sur $\\mathbb{R}$.",
      "Toujours strictement positif."
    ),
    canvas: courbeExp,
    tags: ["premiere", "maths", "exponentielle", "derivee", "canvas", "qcm"],
  },
  {
    kind: "fixed",
    id: "premiere_exp_der_fixed_3",
    niveau: "premiere-spe",
    matiere: "maths",
    notionId: "exponentielle",
    microId: "exp_derivee",
    difficulty: 3,
    theme: "neutral",
    text: "La fonction $x \\mapsto e^x$ est :",
    format: "qcm",
    choices: ["strictement croissante sur $\\mathbb{R}$", "décroissante", "constante", "croissante puis décroissante"],
    expected: ["strictement croissante sur $\\mathbb{R}$"],
    comparator: "mcq_exact",
    hint: "Sa dérivée $e^x$ est positive.",
    explanation: exp(
      "Le sens de variation se déduit du signe de la dérivée.",
      "$(e^x)' = e^x > 0$ sur $\\mathbb{R}$.",
      "Une dérivée strictement positive donne une fonction strictement croissante.",
      "Strictement croissante sur $\\mathbb{R}$."
    ),
    canvas: courbeExp,
    tags: ["premiere", "maths", "exponentielle", "derivee", "canvas", "qcm"],
  },
  {
    kind: "fixed",
    id: "premiere_exp_der_fixed_4",
    niveau: "premiere-spe",
    matiere: "maths",
    notionId: "exponentielle",
    microId: "exp_derivee",
    difficulty: 4,
    theme: "neutral",
    text: "Quelle est la dérivée de $f(x) = e^{3x}$ ?",
    format: "qcm",
    choices: ["$f'(x) = 3e^{3x}$", "$f'(x) = e^{3x}$", "$f'(x) = 3x e^{3x}$", "$f'(x) = e^{3}$"],
    expected: ["$f'(x) = 3e^{3x}$"],
    comparator: "mcq_exact",
    hint: "Dérivée de $e^{ax+b}$ : $a e^{ax+b}$.",
    explanation: exp(
      "La dérivée de $x \\mapsto e^{ax+b}$ est $a\\,e^{ax+b}$.",
      "Ici $a = 3$.",
      "$f'(x) = 3e^{3x}$.",
      "$f'(x) = 3e^{3x}$."
    ),
    tags: ["premiere", "maths", "exponentielle", "derivee", "qcm"],
  },
  {
    kind: "fixed",
    id: "premiere_exp_der_fixed_5",
    niveau: "premiere-spe",
    matiere: "maths",
    notionId: "exponentielle",
    microId: "exp_derivee",
    difficulty: 4,
    theme: "neutral",
    text: "Quelle est la dérivée de $f(x) = e^{-x}$ ?",
    format: "qcm",
    choices: [
      "$f'(x) = -e^{-x}$",
      "$f'(x) = e^{-x}$",
      "$f'(x) = -e^{x}$",
      "$f'(x) = -x e^{-x}$",
    ],
    expected: ["$f'(x) = -e^{-x}$"],
    comparator: "mcq_exact",
    hint: "Dérivée de $e^{ax}$ : $a e^{ax}$, avec ici $a = -1$.",
    explanation: exp(
      "La dérivée de $x \\mapsto e^{ax+b}$ est $a\\,e^{ax+b}$.",
      "Ici $a = -1$, donc $f'(x) = -1 \\times e^{-x}$.",
      "$= -e^{-x}$. Comme $e^{-x} > 0$, cette dérivée est toujours négative.",
      "$f'(x) = -e^{-x}$ : la fonction est décroissante."
    ),
    tags: ["premiere", "maths", "exponentielle", "derivee", "qcm"],
  },
  {
    kind: "fixed",
    id: "premiere_exp_der_fixed_6",
    niveau: "premiere-spe",
    matiere: "maths",
    notionId: "exponentielle",
    microId: "exp_derivee",
    difficulty: 3,
    theme: "neutral",
    text: "Quelle est la dérivée de $f(x) = 5e^{x}$ ?",
    format: "qcm",
    choices: ["$f'(x) = 5e^{x}$", "$f'(x) = e^{x}$", "$f'(x) = 5x e^{x}$", "$f'(x) = 5$"],
    expected: ["$f'(x) = 5e^{x}$"],
    comparator: "mcq_exact",
    hint: "Un coefficient constant reste en facteur : $(ku)' = k u'$.",
    explanation: exp(
      "Multiplier une fonction par un nombre multiplie sa dérivée par ce même nombre.",
      "$(e^x)' = e^x$, donc $f'(x) = 5 \\times e^x$.",
      "$= 5e^x$ : la fonction est égale à sa propre dérivée, au coefficient près.",
      "$f'(x) = 5e^{x}$."
    ),
    tags: ["premiere", "maths", "exponentielle", "derivee", "qcm"],
  },
  {
    kind: "fixed",
    id: "premiere_exp_der_fixed_7",
    niveau: "premiere-spe",
    matiere: "maths",
    notionId: "exponentielle",
    microId: "exp_derivee",
    difficulty: 4,
    theme: "neutral",
    text: "Quelle est la dérivée de $f(x) = e^{2x+1}$ ?",
    format: "qcm",
    choices: [
      "$f'(x) = 2e^{2x+1}$",
      "$f'(x) = e^{2x+1}$",
      "$f'(x) = (2x+1)e^{2x+1}$",
      "$f'(x) = 2e^{2x}$",
    ],
    expected: ["$f'(x) = 2e^{2x+1}$"],
    comparator: "mcq_exact",
    hint: "Le facteur qui sort est le coefficient de $x$ dans l'exposant.",
    explanation: exp(
      "La dérivée de $x \\mapsto e^{ax+b}$ est $a\\,e^{ax+b}$ : l'exposant ne change pas.",
      "Ici $a = 2$ et $b = 1$.",
      "$f'(x) = 2e^{2x+1}$. Le $+1$ reste dans l'exposant : il ne disparaît pas comme le ferait une constante additive.",
      "$f'(x) = 2e^{2x+1}$."
    ),
    tags: ["premiere", "maths", "exponentielle", "derivee", "qcm"],
  },
  {
    kind: "fixed",
    id: "premiere_exp_der_fixed_8",
    niveau: "premiere-spe",
    matiere: "maths",
    notionId: "exponentielle",
    microId: "exp_derivee",
    difficulty: 5,
    theme: "neutral",
    text: "Quelle est la dérivée de $f(x) = x e^{x}$ ?",
    format: "qcm",
    choices: [
      "$f'(x) = (1 + x)e^{x}$",
      "$f'(x) = e^{x}$",
      "$f'(x) = x e^{x}$",
      "$f'(x) = (1 - x)e^{x}$",
    ],
    expected: ["$f'(x) = (1 + x)e^{x}$"],
    comparator: "mcq_exact",
    hint: "C'est un produit : $(uv)' = u'v + uv'$ avec $u = x$ et $v = e^x$.",
    explanation: exp(
      "On applique la formule du produit $(uv)' = u'v + uv'$.",
      "Avec $u = x$ ($u' = 1$) et $v = e^x$ ($v' = e^x$) : $f'(x) = 1 \\times e^x + x \\times e^x$.",
      "$= e^x + x e^x = (1 + x)e^x$ en factorisant par $e^x$.",
      "$f'(x) = (1 + x)e^{x}$."
    ),
    tags: ["premiere", "maths", "exponentielle", "derivee", "qcm"],
  },
  {
    kind: "fixed",
    id: "premiere_exp_der_fixed_9",
    niveau: "premiere-spe",
    matiere: "maths",
    notionId: "exponentielle",
    microId: "exp_derivee",
    difficulty: 4,
    theme: "neutral",
    text: "La fonction $x \\mapsto e^{-x}$ est :",
    format: "qcm",
    choices: [
      "décroissante sur $\\mathbb{R}$",
      "croissante sur $\\mathbb{R}$",
      "constante",
      "décroissante puis croissante",
    ],
    expected: ["décroissante sur $\\mathbb{R}$"],
    comparator: "mcq_exact",
    hint: "Sa dérivée est $-e^{-x}$ : quel est son signe ?",
    explanation: exp(
      "Le sens de variation se lit sur le signe de la dérivée.",
      "La dérivée vaut $-e^{-x}$, et une exponentielle est toujours strictement positive.",
      "Donc $-e^{-x} < 0$ pour tout $x$ : la dérivée est négative partout.",
      "La fonction est décroissante sur $\\mathbb{R}$."
    ),
    tags: ["premiere", "maths", "exponentielle", "derivee", "qcm"],
  },
  {
    kind: "fixed",
    id: "premiere_exp_der_fixed_10",
    niveau: "premiere-spe",
    matiere: "maths",
    notionId: "exponentielle",
    microId: "exp_derivee",
    difficulty: 4,
    theme: "neutral",
    text: "Combien de solutions a l'équation $e^{x} = 0$ ?",
    format: "short",
    expected: ["0"],
    comparator: "number_equal",
    hint: "L'exponentielle prend-elle un jour la valeur zéro ?",
    explanation: exp(
      "La fonction exponentielle est strictement positive sur $\\mathbb{R}$ : $e^x > 0$ pour tout $x$.",
      "Elle ne peut donc jamais valoir $0$.",
      "Sa courbe s'approche de l'axe des abscisses quand $x$ diminue, mais ne le touche jamais.",
      "L'équation n'a aucune solution : $0$ solution."
    ),
    tags: ["premiere", "maths", "exponentielle", "derivee", "short"],
  },
  {
    kind: "fixed",
    id: "premiere_exp_der_fixed_11",
    niveau: "premiere-spe",
    matiere: "maths",
    notionId: "exponentielle",
    microId: "exp_derivee",
    difficulty: 3,
    theme: "neutral",
    text: "En quel point la courbe de $x \\mapsto e^{x}$ coupe-t-elle l'axe des ordonnées ?",
    format: "qcm",
    choices: ["$(0 ; 1)$", "$(1 ; 0)$", "$(0 ; 0)$", "$(1 ; e)$"],
    expected: ["$(0 ; 1)$"],
    comparator: "mcq_exact",
    hint: "L'axe des ordonnées correspond à $x = 0$ : calcule $e^0$.",
    explanation: exp(
      "La courbe coupe l'axe des ordonnées au point d'abscisse $x = 0$.",
      "$e^0 = 1$, donc le point a pour coordonnées $(0 ; 1)$.",
      "La courbe ne coupe jamais l'axe des abscisses, puisque $e^x$ ne s'annule pas.",
      "Elle coupe l'axe des ordonnées en $(0 ; 1)$."
    ),
    tags: ["premiere", "maths", "exponentielle", "derivee", "qcm"],
  },
  {
    kind: "template",
    id: "premiere_exp_der_tpl_1",
    niveau: "premiere-spe",
    matiere: "maths",
    notionId: "exponentielle",
    microId: "exp_derivee",
    difficulty: 4,
    theme: "neutral",
    hint: "$(e^{ax})' = a e^{ax}$.",
    tags: ["premiere", "maths", "exponentielle", "derivee", "template"],
    generate: () => {
      const a = randomInt(2, 6);
      const correct = `$f'(x) = ${a}e^{${a}x}$`;
      const choices = [correct, `$f'(x) = e^{${a}x}$`, `$f'(x) = ${a}x e^{${a}x}$`, `$f'(x) = ${a}e^{x}$`];
      return {
        text: `Quelle est la dérivée de $f(x) = e^{${a}x}$ ?`,
        format: "qcm",
        choices,
        expected: [correct],
        comparator: "mcq_exact",
        explanation: exp(
          "On utilise $(e^{ax})' = a e^{ax}$.",
          `Ici $a = ${a}$.`,
          `$f'(x) = ${a}e^{${a}x}$.`,
          `${correct}.`
        ),
      };
    },
  },
  {
    kind: "template",
    id: "premiere_exp_der_tpl_2",
    niveau: "premiere-spe",
    matiere: "maths",
    notionId: "exponentielle",
    microId: "exp_derivee",
    difficulty: 3,
    theme: "neutral",
    hint: "$(k e^x)' = k e^x$.",
    tags: ["premiere", "maths", "exponentielle", "derivee", "template"],
    generate: () => {
      const k = randomInt(2, 8);
      const correct = `$f'(x) = ${k}e^{x}$`;
      const choices = [correct, `$f'(x) = e^{x}$`, `$f'(x) = ${k}x e^{x}$`, `$f'(x) = ${k}$`];
      return {
        text: `Quelle est la dérivée de $f(x) = ${k}e^{x}$ ?`,
        format: "qcm",
        choices,
        expected: [correct],
        comparator: "mcq_exact",
        explanation: exp(
          "On garde le coefficient et $e^x$ reste sa propre dérivée.",
          `$(${k}e^x)' = ${k}e^x$.`,
          "Le coefficient ne change pas.",
          `${correct}.`
        ),
      };
    },
  },

  /* ===================== EXP_MODELISATION ===================== */
  {
    kind: "fixed",
    id: "premiere_exp_mod_fixed_1",
    niveau: "premiere-spe",
    matiere: "maths",
    notionId: "exponentielle",
    microId: "exp_modelisation",
    difficulty: 2,
    theme: "neutral",
    text: "Une quantité modélisée par $N(t) = N_0 e^{kt}$ avec $k > 0$ correspond à :",
    format: "qcm",
    choices: ["une croissance exponentielle", "une décroissance", "une fonction constante", "une fonction affine"],
    expected: ["une croissance exponentielle"],
    comparator: "mcq_exact",
    hint: "$k > 0$ : l'exposant augmente.",
    explanation: exp(
      "Le signe de $k$ détermine croissance ou décroissance.",
      "Si $k > 0$, $e^{kt}$ augmente avec $t$.",
      "C'est une croissance exponentielle.",
      "Une croissance exponentielle."
    ),
    tags: ["premiere", "maths", "exponentielle", "modelisation", "qcm"],
  },
  {
    kind: "fixed",
    id: "premiere_exp_mod_fixed_2",
    niveau: "premiere-spe",
    matiere: "maths",
    notionId: "exponentielle",
    microId: "exp_modelisation",
    difficulty: 3,
    theme: "neutral",
    text: "La masse d'un échantillon radioactif est $m(t) = 100 e^{-0{,}2t}$. Que vaut $m(0)$ ?",
    format: "short",
    expected: ["100"],
    comparator: "number_equal",
    hint: "$e^0 = 1$.",
    explanation: exp(
      "On remplace $t$ par $0$.",
      "$m(0) = 100 \\times e^{0} = 100 \\times 1$.",
      "$= 100$.",
      "$m(0) = 100$."
    ),
    tags: ["premiere", "maths", "exponentielle", "modelisation", "short"],
  },
  {
    kind: "fixed",
    id: "premiere_exp_mod_fixed_3",
    niveau: "premiere-spe",
    matiere: "maths",
    notionId: "exponentielle",
    microId: "exp_modelisation",
    difficulty: 3,
    theme: "neutral",
    text: "Pour $m(t) = 100 e^{-0{,}2t}$ (décroissance radioactive), la masse :",
    format: "qcm",
    choices: ["diminue au cours du temps", "augmente", "reste constante", "devient négative"],
    expected: ["diminue au cours du temps"],
    comparator: "mcq_exact",
    hint: "Exposant négatif.",
    explanation: exp(
      "Le coefficient dans l'exposant est $k = -0{,}2 < 0$.",
      "Donc $e^{-0{,}2t}$ décroît quand $t$ augmente.",
      "La masse diminue au cours du temps.",
      "Elle diminue au cours du temps."
    ),
    tags: ["premiere", "maths", "exponentielle", "modelisation", "qcm"],
  },
  {
    kind: "fixed",
    id: "premiere_exp_mod_fixed_4",
    niveau: "premiere-spe",
    matiere: "maths",
    notionId: "exponentielle",
    microId: "exp_modelisation",
    difficulty: 3,
    theme: "neutral",
    text: "Un capital de $2000$ € placé à intérêts continus suit $C(t) = 2000 e^{0{,}03t}$. Que vaut le capital initial $C(0)$ ?",
    format: "short",
    expected: ["2000"],
    comparator: "number_equal",
    hint: "$e^0 = 1$.",
    explanation: exp(
      "Le capital initial correspond à $t = 0$.",
      "$C(0) = 2000 \\times e^0 = 2000 \\times 1$.",
      "$= 2000$.",
      "$C(0) = 2000$ €."
    ),
    tags: ["premiere", "maths", "exponentielle", "modelisation", "short"],
  },
  {
    kind: "fixed",
    id: "premiere_exp_mod_fixed_5",
    niveau: "premiere-spe",
    matiere: "maths",
    notionId: "exponentielle",
    microId: "exp_modelisation",
    difficulty: 4,
    theme: "neutral",
    text: "Pour tout réel $a$, la suite $(e^{na})_{n}$ est :",
    format: "qcm",
    choices: [
      "géométrique de raison $e^a$",
      "arithmétique de raison $a$",
      "constante",
      "géométrique de raison $a$",
    ],
    expected: ["géométrique de raison $e^a$"],
    comparator: "mcq_exact",
    hint: "$e^{(n+1)a} = e^{na} \\times e^a$.",
    explanation: exp(
      "On compare deux termes consécutifs.",
      "$e^{(n+1)a} = e^{na} \\times e^{a}$ : on multiplie par $e^a$.",
      "C'est donc une suite géométrique de raison $e^a$.",
      "Géométrique de raison $e^a$."
    ),
    tags: ["premiere", "maths", "exponentielle", "modelisation", "qcm"],
  },
  {
    kind: "fixed",
    id: "premiere_exp_mod_fixed_6",
    niveau: "premiere-spe",
    matiere: "maths",
    notionId: "exponentielle",
    microId: "exp_modelisation",
    difficulty: 3,
    theme: "neutral",
    text: "Une quantité modélisée par $N(t) = N_0 e^{kt}$ avec $k < 0$ correspond à :",
    format: "qcm",
    choices: [
      "une décroissance exponentielle",
      "une croissance exponentielle",
      "une quantité constante",
      "une quantité qui devient négative",
    ],
    expected: ["une décroissance exponentielle"],
    comparator: "mcq_exact",
    hint: "La dérivée vaut $k N_0 e^{kt}$ : quel est son signe si $k < 0$ ?",
    explanation: exp(
      "Le signe de $k$ décide du sens de variation du modèle.",
      "La dérivée est $N'(t) = k N_0 e^{kt}$. Comme $e^{kt} > 0$ et $N_0 > 0$, le signe est celui de $k$.",
      "Avec $k < 0$, la dérivée est négative : la quantité diminue. Elle reste pourtant toujours strictement positive — elle s'approche de zéro sans jamais l'atteindre.",
      "C'est une décroissance exponentielle."
    ),
    tags: ["premiere", "maths", "exponentielle", "modelisation", "qcm"],
  },
  {
    kind: "fixed",
    id: "premiere_exp_mod_fixed_7",
    niveau: "premiere-spe",
    matiere: "maths",
    notionId: "exponentielle",
    microId: "exp_modelisation",
    difficulty: 3,
    theme: "neutral",
    text: "Dans le modèle $N(t) = N_0 e^{kt}$, que représente $N_0$ ?",
    format: "qcm",
    choices: [
      "la quantité à l'instant $t = 0$",
      "la quantité finale",
      "le taux de croissance",
      "la durée du phénomène",
    ],
    expected: ["la quantité à l'instant $t = 0$"],
    comparator: "mcq_exact",
    hint: "Remplace $t$ par $0$ dans le modèle.",
    explanation: exp(
      "Pour interpréter un paramètre, on l'évalue à un instant simple.",
      "$N(0) = N_0 e^{k \\times 0} = N_0 \\times e^0 = N_0 \\times 1$.",
      "$N(0) = N_0$ : c'est donc la quantité de départ.",
      "$N_0$ est la quantité à l'instant $t = 0$."
    ),
    tags: ["premiere", "maths", "exponentielle", "modelisation", "qcm"],
  },
  {
    kind: "fixed",
    id: "premiere_exp_mod_fixed_8",
    niveau: "premiere-spe",
    matiere: "maths",
    notionId: "exponentielle",
    microId: "exp_modelisation",
    difficulty: 4,
    theme: "neutral",
    text: "Un capital suit $C(t) = 2000 e^{0{,}03t}$, avec $t$ en années. Que représente le coefficient $0{,}03$ ?",
    format: "qcm",
    choices: [
      "le taux de croissance continu, soit environ $3\\%$ par an",
      "le capital initial",
      "le nombre d'années de placement",
      "les intérêts en euros",
    ],
    expected: ["le taux de croissance continu, soit environ $3\\%$ par an"],
    comparator: "mcq_exact",
    hint: "C'est le $k$ du modèle $N_0 e^{kt}$ : il gouverne la VITESSE de croissance.",
    explanation: exp(
      "Dans $N_0 e^{kt}$, le coefficient $k$ est le taux de croissance continu.",
      "Ici $k = 0{,}03$, soit $3\\%$ par an. Le capital initial, lui, est $C(0) = 2000$ €.",
      "Plus $k$ est grand, plus le capital grimpe vite ; s'il était négatif, le capital fondrait.",
      "$0{,}03$ est le taux de croissance continu, environ $3\\%$ par an."
    ),
    tags: ["premiere", "maths", "exponentielle", "modelisation", "qcm"],
  },
  {
    kind: "fixed",
    id: "premiere_exp_mod_fixed_9",
    niveau: "premiere-spe",
    matiere: "maths",
    notionId: "exponentielle",
    microId: "exp_modelisation",
    difficulty: 5,
    theme: "neutral",
    text: "Pour $m(t) = 100 e^{-0{,}2t}$, quelle est la dérivée $m'(t)$ ?",
    format: "qcm",
    choices: [
      "$m'(t) = -20 e^{-0{,}2t}$",
      "$m'(t) = 100 e^{-0{,}2t}$",
      "$m'(t) = -0{,}2 e^{-0{,}2t}$",
      "$m'(t) = -20 e^{-t}$",
    ],
    expected: ["$m'(t) = -20 e^{-0{,}2t}$"],
    comparator: "mcq_exact",
    hint: "Le coefficient $100$ reste, et $-0{,}2$ sort de l'exponentielle.",
    explanation: exp(
      "La dérivée de $k\\,e^{at}$ est $k\\,a\\,e^{at}$ : le coefficient devant reste, et celui de $t$ sort.",
      "$m'(t) = 100 \\times (-0{,}2) \\times e^{-0{,}2t}$.",
      "$= -20 e^{-0{,}2t}$, toujours négative : la masse diminue sans cesse.",
      "$m'(t) = -20 e^{-0{,}2t}$."
    ),
    tags: ["premiere", "maths", "exponentielle", "modelisation", "qcm"],
  },
  {
    kind: "fixed",
    id: "premiere_exp_mod_fixed_10",
    niveau: "premiere-spe",
    matiere: "maths",
    notionId: "exponentielle",
    microId: "exp_modelisation",
    difficulty: 4,
    theme: "neutral",
    text: "Deux populations suivent $A(t) = 100 e^{0{,}05t}$ et $B(t) = 100 e^{0{,}02t}$. Laquelle croît le plus vite ?",
    format: "qcm",
    choices: [
      "$A$, car son coefficient $k$ est plus grand",
      "$B$, car son coefficient $k$ est plus petit",
      "les deux à la même vitesse : même valeur initiale",
      "on ne peut pas comparer",
    ],
    expected: ["$A$, car son coefficient $k$ est plus grand"],
    comparator: "mcq_exact",
    hint: "Les deux partent de $100$ : seule la valeur de $k$ les distingue.",
    explanation: exp(
      "Dans $N_0 e^{kt}$, c'est $k$ qui fixe la vitesse de croissance ; $N_0$ ne fixe que le point de départ.",
      "Les deux populations partent de $100$, mais $0{,}05 > 0{,}02$.",
      "$A$ croît donc plus vite : au bout de quelques années, l'écart entre les deux devient considérable.",
      "C'est $A$, car son coefficient $k$ est plus grand."
    ),
    tags: ["premiere", "maths", "exponentielle", "modelisation", "qcm"],
  },
  {
    kind: "fixed",
    id: "premiere_exp_mod_fixed_11",
    niveau: "premiere-spe",
    matiere: "maths",
    notionId: "exponentielle",
    microId: "exp_modelisation",
    difficulty: 3,
    theme: "neutral",
    text: "Parmi ces modèles, lequel décrit une décroissance exponentielle ?",
    format: "qcm",
    choices: [
      "$N(t) = 80 e^{-0{,}3t}$",
      "$N(t) = 80 e^{0{,}3t}$",
      "$N(t) = 80 - 0{,}3t$",
      "$N(t) = 80 \\times 0{,}3 t$",
    ],
    expected: ["$N(t) = 80 e^{-0{,}3t}$"],
    comparator: "mcq_exact",
    hint: "Exponentielle ET décroissante : il faut un $e$, et un exposant négatif.",
    explanation: exp(
      "Un modèle exponentiel s'écrit $N_0 e^{kt}$ ; il décroît lorsque $k < 0$.",
      "$80 e^{-0{,}3t}$ a bien $k = -0{,}3 < 0$.",
      "$80 e^{0{,}3t}$ croît ; $80 - 0{,}3t$ décroît, mais de façon AFFINE (elle finit par devenir négative, ce qu'une exponentielle ne fait jamais).",
      "C'est $N(t) = 80 e^{-0{,}3t}$."
    ),
    tags: ["premiere", "maths", "exponentielle", "modelisation", "qcm"],
  },
  {
    kind: "template",
    id: "premiere_exp_mod_tpl_1",
    niveau: "premiere-spe",
    matiere: "maths",
    notionId: "exponentielle",
    microId: "exp_modelisation",
    difficulty: 3,
    theme: "neutral",
    hint: "Valeur initiale : remplace $t$ par $0$ et $e^0 = 1$.",
    tags: ["premiere", "maths", "exponentielle", "modelisation", "template"],
    generate: () => {
      const n0 = randomInt(2, 9) * 100;
      const k = randomInt(1, 4);
      return {
        text: `Une population est modélisée par $N(t) = ${n0} e^{0{,}0${k}t}$. Quelle est la population initiale $N(0)$ ?`,
        format: "short",
        expected: [String(n0)],
        comparator: "number_equal",
        explanation: exp(
          "La valeur initiale correspond à $t = 0$.",
          `$N(0) = ${n0} \\times e^0 = ${n0} \\times 1$.`,
          `$= ${n0}$.`,
          `$N(0) = ${n0}$.`
        ),
      };
    },
  },
  {
    kind: "template",
    id: "premiere_exp_mod_tpl_2",
    niveau: "premiere-spe",
    matiere: "maths",
    notionId: "exponentielle",
    microId: "exp_modelisation",
    difficulty: 3,
    theme: "neutral",
    hint: "Signe de $k$ : croissance si $k>0$, décroissance si $k<0$.",
    tags: ["premiere", "maths", "exponentielle", "modelisation", "template"],
    generate: () => {
      const croissance = randomInt(0, 1) === 1;
      const k = randomInt(1, 5);
      const correct = croissance ? "croissance exponentielle" : "décroissance exponentielle";
      return {
        text: `Une grandeur suit $G(t) = G_0 e^{${croissance ? "" : "-"}0{,}${k}t}$. Cela modélise une :`,
        format: "qcm",
        choices: ["croissance exponentielle", "décroissance exponentielle", "fonction constante", "fonction affine"],
        expected: [correct],
        comparator: "mcq_exact",
        explanation: exp(
          "Le signe du coefficient dans l'exposant donne le sens.",
          `Ici le coefficient est ${croissance ? "positif" : "négatif"}.`,
          `Donc c'est une ${correct}.`,
          `Une ${correct}.`
        ),
      };
    },
  },
];
