// lib/tutor-v4/questionBank/premiere-spe/maths/probabilites-conditionnelles.bank.ts
//
// Chapitre : Probabilités conditionnelles et indépendance (notion "probabilites_conditionnelles")
// microSkills :
//   pc_conditionnelle — calculer une probabilité conditionnelle P_A(B)
//   pc_arbre          — arbre pondéré : règle du produit et de la somme
//   pc_totales        — formule des probabilités totales
//   pc_independance   — indépendance de deux événements
//
// PÉRIMÈTRE BO 2019 Première spé. Conventions : LaTeX, règle QCM. Canvas : arbre_proba.

import type { TutorBankItemV4, CanvasFigure } from "@/lib/tutor-v4/types";

function randomInt(min: number, max: number) {
  return Math.floor(Math.random() * (max - min + 1)) + min;
}

function exp(definition: string, methode: string, calcul: string, conclusion: string) {
  return (
    `Définition : ${definition}\n\n` +
    `Méthode : ${methode}\n\n` +
    `Calcul / Observation : ${calcul}\n\n` +
    `Conclusion : ${conclusion}`
  );
}

// Format virgule française pour l'affichage des probabilités dans l'arbre.
function fr(x: number): string {
  return String(Math.round(x * 100) / 100).replace(".", ",");
}

function arbre(pA: number, pBsiA: number, pBsiNonA: number): CanvasFigure {
  return {
    kind: "arbre_proba",
    titre: "Arbre pondéré",
    racineEnfants: [
      {
        label: "A",
        proba: fr(pA),
        enfants: [
          { label: "B", proba: fr(pBsiA) },
          { label: "B̄", proba: fr(1 - pBsiA) },
        ],
      },
      {
        label: "Ā",
        proba: fr(1 - pA),
        enfants: [
          { label: "B", proba: fr(pBsiNonA) },
          { label: "B̄", proba: fr(1 - pBsiNonA) },
        ],
      },
    ],
  };
}

export const probabilitesConditionnellesBank: TutorBankItemV4[] = [
  /* ===================== PC_CONDITIONNELLE ===================== */
  {
    kind: "fixed",
    id: "premiere_pc_cond_fixed_1",
    niveau: "premiere-spe",
    matiere: "maths",
    notionId: "probabilites_conditionnelles",
    microId: "pc_conditionnelle",
    difficulty: 2,
    theme: "neutral",
    text: "La probabilité conditionnelle $P_A(B)$ se calcule par :",
    format: "qcm",
    choices: [
      "$\\dfrac{P(A \\cap B)}{P(A)}$",
      "$\\dfrac{P(A \\cap B)}{P(B)}$",
      "$P(A) \\times P(B)$",
      "$\\dfrac{P(A)}{P(B)}$",
    ],
    expected: ["$\\dfrac{P(A \\cap B)}{P(A)}$"],
    comparator: "mcq_exact",
    hint: "On divise par la probabilité de la condition $A$.",
    explanation: exp(
      "$P_A(B)$ est la probabilité de $B$ sachant que $A$ est réalisé.",
      "On divise la probabilité de l'intersection par celle de la condition.",
      "$P_A(B) = \\dfrac{P(A \\cap B)}{P(A)}$.",
      "$\\dfrac{P(A \\cap B)}{P(A)}$."
    ),
    tags: ["premiere", "maths", "probas_cond", "conditionnelle", "qcm"],
  },
  {
    kind: "fixed",
    id: "premiere_pc_cond_fixed_2",
    niveau: "premiere-spe",
    matiere: "maths",
    notionId: "probabilites_conditionnelles",
    microId: "pc_conditionnelle",
    difficulty: 3,
    theme: "neutral",
    text: "On a $P(A) = 0{,}4$ et $P(A \\cap B) = 0{,}2$. Combien vaut $P_A(B)$ ?",
    format: "short",
    expected: ["0,5"],
    comparator: "number_equal",
    hint: "$\\dfrac{0{,}2}{0{,}4}$.",
    explanation: exp(
      "On applique $P_A(B) = \\dfrac{P(A \\cap B)}{P(A)}$.",
      "$\\dfrac{0{,}2}{0{,}4}$.",
      "$= 0{,}5$.",
      "$P_A(B) = 0{,}5$."
    ),
    tags: ["premiere", "maths", "probas_cond", "conditionnelle", "short"],
  },
  {
    kind: "fixed",
    id: "premiere_pc_cond_fixed_3",
    niveau: "premiere-spe",
    matiere: "maths",
    notionId: "probabilites_conditionnelles",
    microId: "pc_conditionnelle",
    difficulty: 3,
    theme: "neutral",
    text: "Dans une classe, $P(\\text{fille}) = 0{,}6$ et $P(\\text{fille et demi-pensionnaire}) = 0{,}3$. Quelle est la probabilité qu'une fille soit demi-pensionnaire ?",
    format: "short",
    expected: ["0,5"],
    comparator: "number_equal",
    hint: "$\\dfrac{0{,}3}{0{,}6}$.",
    explanation: exp(
      "On cherche $P_{\\text{fille}}(\\text{DP}) = \\dfrac{P(\\text{fille} \\cap \\text{DP})}{P(\\text{fille})}$.",
      "$\\dfrac{0{,}3}{0{,}6}$.",
      "$= 0{,}5$.",
      "La probabilité est $0{,}5$."
    ),
    tags: ["premiere", "maths", "probas_cond", "conditionnelle", "short"],
  },
  {
    kind: "fixed",
    id: "premiere_pc_cond_fixed_4",
    niveau: "premiere-spe",
    matiere: "maths",
    notionId: "probabilites_conditionnelles",
    microId: "pc_conditionnelle",
    difficulty: 4,
    theme: "neutral",
    text: "On lit dans un tableau : $50$ élèves dont $20$ font de l'anglais ; parmi ces $20$, $12$ font aussi espagnol. Quelle est la probabilité qu'un angliciste fasse espagnol ?",
    format: "short",
    expected: ["0,6"],
    comparator: "number_equal",
    hint: "$\\dfrac{12}{20}$.",
    explanation: exp(
      "On se restreint aux $20$ anglicistes (la condition).",
      "Parmi eux, $12$ font espagnol : $\\dfrac{12}{20}$.",
      "$= 0{,}6$.",
      "La probabilité est $0{,}6$."
    ),
    tags: ["premiere", "maths", "probas_cond", "conditionnelle", "short"],
  },
  {
    kind: "fixed",
    id: "premiere_pc_cond_fixed_5",
    niveau: "premiere-spe",
    matiere: "maths",
    notionId: "probabilites_conditionnelles",
    microId: "pc_conditionnelle",
    difficulty: 4,
    theme: "neutral",
    text: "On a $P(A) = 0{,}5$ et $P(A \\cap B) = 0{,}15$. Combien vaut $P_A(B)$ ?",
    format: "short",
    expected: ["0,3"],
    comparator: "number_equal",
    hint: "$\\dfrac{0{,}15}{0{,}5}$.",
    explanation: exp(
      "On applique $P_A(B) = \\dfrac{P(A \\cap B)}{P(A)}$.",
      "$\\dfrac{0{,}15}{0{,}5}$.",
      "$= 0{,}3$. Le dénominateur est toujours la probabilité de l'événement qui CONDITIONNE.",
      "$P_A(B) = 0{,}3$."
    ),
    tags: ["premiere", "maths", "probas_cond", "conditionnelle", "short"],
  },
  {
    kind: "fixed",
    id: "premiere_pc_cond_fixed_6",
    niveau: "premiere-spe",
    matiere: "maths",
    notionId: "probabilites_conditionnelles",
    microId: "pc_conditionnelle",
    difficulty: 4,
    theme: "neutral",
    text: "Sur $200$ clients, $80$ achètent le produit X ; parmi ces $80$, $40$ achètent aussi le produit Y. Quelle est la probabilité qu'un acheteur de X achète aussi Y ?",
    format: "short",
    expected: ["0,5"],
    comparator: "number_equal",
    hint: "On ne travaille plus que sur les $80$ acheteurs de X.",
    explanation: exp(
      "Conditionner, c'est réduire l'univers : on ne considère plus que les acheteurs de X.",
      "Parmi ces $80$, il y en a $40$ qui achètent Y : $\\dfrac{40}{80}$.",
      "$= 0{,}5$. Le total de $200$ ne sert pas ici : il servirait pour $P(X \\cap Y) = \\dfrac{40}{200}$.",
      "La probabilité est $0{,}5$."
    ),
    tags: ["premiere", "maths", "probas_cond", "conditionnelle", "short"],
  },
  {
    kind: "fixed",
    id: "premiere_pc_cond_fixed_7",
    niveau: "premiere-spe",
    matiere: "maths",
    notionId: "probabilites_conditionnelles",
    microId: "pc_conditionnelle",
    difficulty: 5,
    theme: "neutral",
    text: "A-t-on toujours $P_A(B) = P_B(A)$ ?",
    format: "qcm",
    choices: [
      "non : les dénominateurs sont différents",
      "oui, toujours",
      "oui, si $A$ et $B$ sont indépendants",
      "oui, si $P(A \\cap B) > 0$",
    ],
    expected: ["non : les dénominateurs sont différents"],
    comparator: "mcq_exact",
    hint: "Écris les deux formules l'une sous l'autre.",
    explanation: exp(
      "$P_A(B) = \\dfrac{P(A \\cap B)}{P(A)}$ et $P_B(A) = \\dfrac{P(A \\cap B)}{P(B)}$.",
      "Le numérateur est le même, mais le dénominateur change : elles ne sont égales que si $P(A) = P(B)$.",
      "Exemple : parmi les élèves qui prennent le bus, beaucoup arrivent en avance ; mais parmi ceux qui arrivent en avance, tous ne prennent pas le bus.",
      "Non : les deux probabilités conditionnelles sont différentes en général."
    ),
    tags: ["premiere", "maths", "probas_cond", "conditionnelle", "qcm"],
  },
  {
    kind: "fixed",
    id: "premiere_pc_cond_fixed_8",
    niveau: "premiere-spe",
    matiere: "maths",
    notionId: "probabilites_conditionnelles",
    microId: "pc_conditionnelle",
    difficulty: 4,
    theme: "neutral",
    text: "On a $P(A) = 0{,}5$ et $P_A(B) = 0{,}4$. Combien vaut $P(A \\cap B)$ ?",
    format: "short",
    expected: ["0,2"],
    comparator: "number_equal",
    hint: "$P(A \\cap B) = P(A) \\times P_A(B)$.",
    explanation: exp(
      "En multipliant les deux membres de $P_A(B) = \\dfrac{P(A \\cap B)}{P(A)}$ par $P(A)$, on obtient $P(A \\cap B) = P(A) \\times P_A(B)$.",
      "$0{,}5 \\times 0{,}4$.",
      "$= 0{,}2$.",
      "$P(A \\cap B) = 0{,}2$."
    ),
    tags: ["premiere", "maths", "probas_cond", "conditionnelle", "short"],
  },
  {
    kind: "fixed",
    id: "premiere_pc_cond_fixed_9",
    niveau: "premiere-spe",
    matiere: "maths",
    notionId: "probabilites_conditionnelles",
    microId: "pc_conditionnelle",
    difficulty: 4,
    theme: "reunion",
    text: "Sur $100$ élèves d'un collège, $60$ prennent le car ; parmi eux, $45$ arrivent avant $7$ h $30$. Quelle est la probabilité qu'un élève venant en car arrive avant $7$ h $30$ ?",
    format: "short",
    expected: ["0,75"],
    comparator: "number_equal",
    hint: "$\\dfrac{45}{60}$ : on se limite aux élèves du car.",
    explanation: exp(
      "L'énoncé impose une condition : « venant en car ». On se restreint donc à ces $60$ élèves.",
      "Parmi eux, $45$ arrivent avant $7$ h $30$ : $\\dfrac{45}{60}$.",
      "$= 0{,}75$.",
      "La probabilité est $0{,}75$."
    ),
    tags: ["premiere", "maths", "probas_cond", "conditionnelle", "short"],
  },
  {
    kind: "fixed",
    id: "premiere_pc_cond_fixed_10",
    niveau: "premiere-spe",
    matiere: "maths",
    notionId: "probabilites_conditionnelles",
    microId: "pc_conditionnelle",
    difficulty: 3,
    theme: "neutral",
    text: "Que signifie la notation $P_A(B)$ ?",
    format: "qcm",
    choices: [
      "la probabilité de $B$ sachant que $A$ est réalisé",
      "la probabilité de $A$ sachant que $B$ est réalisé",
      "la probabilité que $A$ et $B$ soient réalisés",
      "la probabilité que $A$ ou $B$ soit réalisé",
    ],
    expected: ["la probabilité de $B$ sachant que $A$ est réalisé"],
    comparator: "mcq_exact",
    hint: "L'événement en indice est celui qu'on SUPPOSE réalisé.",
    explanation: exp(
      "Dans $P_A(B)$, l'événement écrit en indice est la CONDITION : on suppose $A$ déjà réalisé.",
      "On calcule alors la probabilité de $B$ dans cet univers réduit.",
      "La probabilité que les deux soient réalisés se note $P(A \\cap B)$ : c'est autre chose.",
      "$P_A(B)$ est la probabilité de $B$ sachant $A$."
    ),
    tags: ["premiere", "maths", "probas_cond", "conditionnelle", "qcm"],
  },
  {
    kind: "fixed",
    id: "premiere_pc_cond_fixed_11",
    niveau: "premiere-spe",
    matiere: "maths",
    notionId: "probabilites_conditionnelles",
    microId: "pc_conditionnelle",
    difficulty: 5,
    theme: "neutral",
    text: "Pourquoi la définition de $P_A(B)$ exige-t-elle $P(A) \\neq 0$ ?",
    format: "qcm",
    choices: [
      "car $P(A)$ est au dénominateur",
      "car une probabilité ne peut pas être nulle",
      "car $B$ doit être réalisé",
      "ce n'est pas exigé",
    ],
    expected: ["car $P(A)$ est au dénominateur"],
    comparator: "mcq_exact",
    hint: "Regarde la formule $P_A(B) = \\dfrac{P(A \\cap B)}{P(A)}$.",
    explanation: exp(
      "La probabilité conditionnelle est définie par le quotient $\\dfrac{P(A \\cap B)}{P(A)}$.",
      "Une division par zéro est impossible : il faut donc $P(A) \\neq 0$.",
      "C'est aussi logique : conditionner par un événement impossible n'a aucun sens.",
      "Parce que $P(A)$ figure au dénominateur."
    ),
    tags: ["premiere", "maths", "probas_cond", "conditionnelle", "qcm"],
  },
  {
    kind: "template",
    id: "premiere_pc_cond_tpl_1",
    niveau: "premiere-spe",
    matiere: "maths",
    notionId: "probabilites_conditionnelles",
    microId: "pc_conditionnelle",
    difficulty: 3,
    theme: "neutral",
    hint: "$P_A(B) = \\dfrac{P(A \\cap B)}{P(A)}$.",
    tags: ["premiere", "maths", "probas_cond", "conditionnelle", "template"],
    generate: () => {
      const pA = randomInt(2, 8) / 10;
      const pAB = (Math.round(pA * 10) * randomInt(1, 9)) / 100; // <= pA
      const val = Math.round((pAB / pA) * 100) / 100;
      return {
        text: `On a $P(A) = ${fr(pA)}$ et $P(A \\cap B) = ${fr(pAB)}$. Combien vaut $P_A(B)$ ? (arrondir au centième)`,
        format: "short",
        expected: [fr(val)],
        comparator: "number_equal",
        explanation: exp(
          "On applique $P_A(B) = \\dfrac{P(A \\cap B)}{P(A)}$.",
          `$\\dfrac{${fr(pAB)}}{${fr(pA)}}$.`,
          `$= ${fr(val)}$.`,
          `$P_A(B) = ${fr(val)}$.`
        ),
      };
    },
  },

  /* ===================== PC_ARBRE ===================== */
  {
    kind: "fixed",
    id: "premiere_pc_arb_fixed_1",
    niveau: "premiere-spe",
    matiere: "maths",
    notionId: "probabilites_conditionnelles",
    microId: "pc_arbre",
    difficulty: 2,
    theme: "neutral",
    text: "Dans un arbre pondéré, la probabilité d'un chemin (de la racine à une feuille) s'obtient en :",
    format: "qcm",
    choices: [
      "multipliant les probabilités le long du chemin",
      "additionnant les probabilités le long du chemin",
      "prenant la plus grande probabilité",
      "soustrayant les probabilités",
    ],
    expected: ["multipliant les probabilités le long du chemin"],
    comparator: "mcq_exact",
    hint: "Règle du produit.",
    explanation: exp(
      "La probabilité d'un chemin suit la règle du produit.",
      "On multiplie les probabilités rencontrées le long du chemin.",
      "Ex. : $P(A \\cap B) = P(A) \\times P_A(B)$.",
      "On multiplie les probabilités le long du chemin."
    ),
    tags: ["premiere", "maths", "probas_cond", "arbre", "qcm"],
  },
  {
    kind: "fixed",
    id: "premiere_pc_arb_fixed_2",
    niveau: "premiere-spe",
    matiere: "maths",
    notionId: "probabilites_conditionnelles",
    microId: "pc_arbre",
    difficulty: 3,
    theme: "neutral",
    text: "Sur l'arbre, calcule $P(A \\cap B)$ avec $P(A) = 0{,}6$ et $P_A(B) = 0{,}5$.",
    format: "short",
    expected: ["0,3"],
    comparator: "number_equal",
    hint: "$0{,}6 \\times 0{,}5$.",
    explanation: exp(
      "On multiplie le long du chemin A → B.",
      "$P(A \\cap B) = P(A) \\times P_A(B) = 0{,}6 \\times 0{,}5$.",
      "$= 0{,}3$.",
      "$P(A \\cap B) = 0{,}3$."
    ),
    canvas: arbre(0.6, 0.5, 0.2),
    tags: ["premiere", "maths", "probas_cond", "arbre", "canvas", "short"],
  },
  {
    kind: "fixed",
    id: "premiere_pc_arb_fixed_3",
    niveau: "premiere-spe",
    matiere: "maths",
    notionId: "probabilites_conditionnelles",
    microId: "pc_arbre",
    difficulty: 3,
    theme: "neutral",
    text: "Sur une branche issue d'un nœud, la somme des probabilités des sous-branches vaut :",
    format: "short",
    expected: ["1"],
    comparator: "number_equal",
    hint: "Toutes les possibilités sont couvertes.",
    explanation: exp(
      "À partir d'un nœud, les branches couvrent tous les cas possibles.",
      "Leurs probabilités forment une partition.",
      "Leur somme vaut donc $1$.",
      "La somme vaut $1$."
    ),
    tags: ["premiere", "maths", "probas_cond", "arbre", "short"],
  },
  {
    kind: "fixed",
    id: "premiere_pc_arb_fixed_4",
    niveau: "premiere-spe",
    matiere: "maths",
    notionId: "probabilites_conditionnelles",
    microId: "pc_arbre",
    difficulty: 4,
    theme: "neutral",
    text: "Sur l'arbre, $P(A) = 0{,}7$ et $P_A(B) = 0{,}4$. Quelle est la probabilité $P_A(\\bar{B})$ ?",
    format: "short",
    expected: ["0,6"],
    comparator: "number_equal",
    hint: "$P_A(\\bar B) = 1 - P_A(B)$.",
    explanation: exp(
      "Les deux sous-branches issues de $A$ ont une somme égale à $1$.",
      "$P_A(\\bar B) = 1 - P_A(B) = 1 - 0{,}4$.",
      "$= 0{,}6$.",
      "$P_A(\\bar B) = 0{,}6$."
    ),
    canvas: arbre(0.7, 0.4, 0.3),
    tags: ["premiere", "maths", "probas_cond", "arbre", "canvas", "short"],
  },
  {
    kind: "fixed",
    id: "premiere_pc_arb_fixed_5",
    niveau: "premiere-spe",
    matiere: "maths",
    notionId: "probabilites_conditionnelles",
    microId: "pc_arbre",
    difficulty: 4,
    theme: "neutral",
    text: "Sur l'arbre, $P(A) = 0{,}3$ et $P_A(B) = 0{,}8$. Combien vaut $P(A \\cap B)$ ?",
    format: "short",
    expected: ["0,24"],
    comparator: "number_equal",
    hint: "On MULTIPLIE les probabilités le long du chemin.",
    explanation: exp(
      "La probabilité d'un chemin est le produit des probabilités portées par ses branches.",
      "$P(A \\cap B) = P(A) \\times P_A(B) = 0{,}3 \\times 0{,}8$.",
      "$= 0{,}24$. On multiplie le long d'un chemin ; on additionne entre chemins différents.",
      "$P(A \\cap B) = 0{,}24$."
    ),
    canvas: arbre(0.3, 0.8, 0.5),
    tags: ["premiere", "maths", "probas_cond", "arbre", "canvas", "short"],
  },
  {
    kind: "fixed",
    id: "premiere_pc_arb_fixed_6",
    niveau: "premiere-spe",
    matiere: "maths",
    notionId: "probabilites_conditionnelles",
    microId: "pc_arbre",
    difficulty: 3,
    theme: "neutral",
    text: "Sur un arbre, la branche menant à $\\bar A$ porte $0{,}6$. Que porte la branche menant à $A$ ?",
    format: "short",
    expected: ["0,4"],
    comparator: "number_equal",
    hint: "La somme des branches issues d'un même nœud vaut $1$.",
    explanation: exp(
      "Les branches issues d'un même nœud décrivent tous les cas possibles : leur somme vaut $1$.",
      "$P(A) = 1 - P(\\bar A) = 1 - 0{,}6$.",
      "$= 0{,}4$.",
      "La branche menant à $A$ porte $0{,}4$."
    ),
    tags: ["premiere", "maths", "probas_cond", "arbre", "short"],
  },
  {
    kind: "fixed",
    id: "premiere_pc_arb_fixed_7",
    niveau: "premiere-spe",
    matiere: "maths",
    notionId: "probabilites_conditionnelles",
    microId: "pc_arbre",
    difficulty: 4,
    theme: "neutral",
    text: "Sur l'arbre, $P(\\bar A) = 0{,}5$ et $P_{\\bar A}(B) = 0{,}6$. Combien vaut $P(\\bar A \\cap B)$ ?",
    format: "short",
    expected: ["0,3"],
    comparator: "number_equal",
    hint: "Même règle du produit, sur le chemin qui passe par $\\bar A$.",
    explanation: exp(
      "La règle du produit vaut pour tous les chemins de l'arbre, y compris ceux qui passent par l'événement contraire.",
      "$P(\\bar A \\cap B) = P(\\bar A) \\times P_{\\bar A}(B) = 0{,}5 \\times 0{,}6$.",
      "$= 0{,}3$.",
      "$P(\\bar A \\cap B) = 0{,}3$."
    ),
    tags: ["premiere", "maths", "probas_cond", "arbre", "short"],
  },
  {
    kind: "fixed",
    id: "premiere_pc_arb_fixed_8",
    niveau: "premiere-spe",
    matiere: "maths",
    notionId: "probabilites_conditionnelles",
    microId: "pc_arbre",
    difficulty: 3,
    theme: "neutral",
    text: "Que porte une branche du PREMIER niveau d'un arbre pondéré ?",
    format: "qcm",
    choices: [
      "une probabilité simple, comme $P(A)$",
      "une probabilité conditionnelle, comme $P_A(B)$",
      "une intersection, comme $P(A \\cap B)$",
      "toujours $0{,}5$",
    ],
    expected: ["une probabilité simple, comme $P(A)$"],
    comparator: "mcq_exact",
    hint: "Au premier niveau, aucune information n'est encore connue.",
    explanation: exp(
      "Le premier niveau part de la racine : rien n'est encore supposé réalisé.",
      "On y écrit donc des probabilités simples : $P(A)$ et $P(\\bar A)$.",
      "Les probabilités conditionnelles apparaissent au deuxième niveau, une fois qu'on sait par où l'on est passé.",
      "Une probabilité simple, comme $P(A)$."
    ),
    tags: ["premiere", "maths", "probas_cond", "arbre", "qcm"],
  },
  {
    kind: "fixed",
    id: "premiere_pc_arb_fixed_9",
    niveau: "premiere-spe",
    matiere: "maths",
    notionId: "probabilites_conditionnelles",
    microId: "pc_arbre",
    difficulty: 4,
    theme: "neutral",
    text: "Que porte une branche du DEUXIÈME niveau d'un arbre pondéré ?",
    format: "qcm",
    choices: [
      "une probabilité conditionnelle, comme $P_A(B)$",
      "une probabilité simple, comme $P(B)$",
      "une intersection, comme $P(A \\cap B)$",
      "la somme des probabilités précédentes",
    ],
    expected: ["une probabilité conditionnelle, comme $P_A(B)$"],
    comparator: "mcq_exact",
    hint: "Au deuxième niveau, on sait déjà par quelle branche on est passé.",
    explanation: exp(
      "Arrivé au deuxième niveau, on a déjà emprunté une branche : cette information conditionne la suite.",
      "On y écrit donc $P_A(B)$ ou $P_{\\bar A}(B)$ selon le chemin suivi.",
      "L'intersection $P(A \\cap B)$, elle, n'apparaît pas sur une branche : c'est le résultat du PRODUIT le long du chemin, écrit au bout.",
      "Une probabilité conditionnelle, comme $P_A(B)$."
    ),
    tags: ["premiere", "maths", "probas_cond", "arbre", "qcm"],
  },
  {
    kind: "fixed",
    id: "premiere_pc_arb_fixed_10",
    niveau: "premiere-spe",
    matiere: "maths",
    notionId: "probabilites_conditionnelles",
    microId: "pc_arbre",
    difficulty: 3,
    theme: "neutral",
    text: "Un arbre a deux niveaux, chacun avec deux branches ($A$ ou $\\bar A$, puis $B$ ou $\\bar B$). Combien de chemins complets compte-t-il ?",
    format: "short",
    expected: ["4"],
    comparator: "number_equal",
    hint: "$2$ possibilités, puis $2$ pour chacune.",
    explanation: exp(
      "Chaque chemin complet part de la racine et va jusqu'à une extrémité.",
      "Il y a $2$ choix au premier niveau, et pour chacun $2$ choix au second : $2 \\times 2$.",
      "$= 4$ chemins : $A \\cap B$, $A \\cap \\bar B$, $\\bar A \\cap B$, $\\bar A \\cap \\bar B$.",
      "L'arbre compte $4$ chemins, dont les probabilités ont pour somme $1$."
    ),
    tags: ["premiere", "maths", "probas_cond", "arbre", "short"],
  },
  {
    kind: "fixed",
    id: "premiere_pc_arb_fixed_11",
    niveau: "premiere-spe",
    matiere: "maths",
    notionId: "probabilites_conditionnelles",
    microId: "pc_arbre",
    difficulty: 5,
    theme: "neutral",
    text: "Un sac contient $3$ boules rouges et $2$ vertes. On tire une boule, on la REMET, puis on en tire une seconde. Quelle est la probabilité d'obtenir deux rouges ?",
    format: "short",
    expected: ["0,36"],
    comparator: "number_equal",
    hint: "Avec remise, la composition du sac ne change pas : $0{,}6$ à chaque tirage.",
    explanation: exp(
      "On construit un arbre à deux niveaux ; avec remise, les probabilités du second niveau sont les mêmes qu'au premier.",
      "$P(\\text{rouge}) = \\dfrac{3}{5} = 0{,}6$ à chaque tirage, et on multiplie le long du chemin.",
      "$0{,}6 \\times 0{,}6 = 0{,}36$.",
      "La probabilité est $0{,}36$."
    ),
    tags: ["premiere", "maths", "probas_cond", "arbre", "short"],
  },
  {
    kind: "template",
    id: "premiere_pc_arb_tpl_1",
    niveau: "premiere-spe",
    matiere: "maths",
    notionId: "probabilites_conditionnelles",
    microId: "pc_arbre",
    difficulty: 3,
    theme: "neutral",
    hint: "Multiplie le long du chemin.",
    tags: ["premiere", "maths", "probas_cond", "arbre", "template"],
    generate: () => {
      const pA = randomInt(2, 8) / 10;
      const pBsiA = randomInt(2, 8) / 10;
      const inter = Math.round(pA * pBsiA * 100) / 100;
      return {
        text: `Sur l'arbre, $P(A) = ${fr(pA)}$ et $P_A(B) = ${fr(pBsiA)}$. Calcule $P(A \\cap B)$.`,
        format: "short",
        expected: [fr(inter)],
        comparator: "number_equal",
        canvas: arbre(pA, pBsiA, 0.3),
        explanation: exp(
          "On multiplie le long du chemin A → B.",
          `$P(A \\cap B) = ${fr(pA)} \\times ${fr(pBsiA)}$.`,
          `$= ${fr(inter)}$.`,
          `$P(A \\cap B) = ${fr(inter)}$.`
        ),
      };
    },
  },

  /* ===================== PC_TOTALES ===================== */
  {
    kind: "fixed",
    id: "premiere_pc_tot_fixed_1",
    niveau: "premiere-spe",
    matiere: "maths",
    notionId: "probabilites_conditionnelles",
    microId: "pc_totales",
    difficulty: 3,
    theme: "neutral",
    text: "Avec la partition $\\{A ; \\bar A\\}$, la formule des probabilités totales donne $P(B) =$",
    format: "qcm",
    choices: [
      "$P(A \\cap B) + P(\\bar A \\cap B)$",
      "$P(A) \\times P(B)$",
      "$P(A \\cap B) - P(\\bar A \\cap B)$",
      "$P(A) + P(B)$",
    ],
    expected: ["$P(A \\cap B) + P(\\bar A \\cap B)$"],
    comparator: "mcq_exact",
    hint: "On additionne les chemins menant à $B$.",
    explanation: exp(
      "$B$ est atteint soit via $A$, soit via $\\bar A$.",
      "On additionne les probabilités de ces deux chemins.",
      "$P(B) = P(A \\cap B) + P(\\bar A \\cap B)$.",
      "$P(A \\cap B) + P(\\bar A \\cap B)$."
    ),
    tags: ["premiere", "maths", "probas_cond", "totales", "qcm"],
  },
  {
    kind: "fixed",
    id: "premiere_pc_tot_fixed_2",
    niveau: "premiere-spe",
    matiere: "maths",
    notionId: "probabilites_conditionnelles",
    microId: "pc_totales",
    difficulty: 4,
    theme: "neutral",
    text: "On a $P(A \\cap B) = 0{,}3$ et $P(\\bar A \\cap B) = 0{,}2$. Combien vaut $P(B)$ ?",
    format: "short",
    expected: ["0,5"],
    comparator: "number_equal",
    hint: "Somme des deux chemins menant à $B$.",
    explanation: exp(
      "On applique la formule des probabilités totales.",
      "$P(B) = P(A \\cap B) + P(\\bar A \\cap B) = 0{,}3 + 0{,}2$.",
      "$= 0{,}5$.",
      "$P(B) = 0{,}5$."
    ),
    tags: ["premiere", "maths", "probas_cond", "totales", "short"],
  },
  {
    kind: "fixed",
    id: "premiere_pc_tot_fixed_3",
    niveau: "premiere-spe",
    matiere: "maths",
    notionId: "probabilites_conditionnelles",
    microId: "pc_totales",
    difficulty: 4,
    theme: "neutral",
    text: "Avec $P(A) = 0{,}6$, $P_A(B) = 0{,}5$, $P_{\\bar A}(B) = 0{,}25$, calcule $P(B)$.",
    format: "short",
    expected: ["0,4"],
    comparator: "number_equal",
    hint: "$P(B) = P(A)P_A(B) + P(\\bar A)P_{\\bar A}(B)$.",
    explanation: exp(
      "On applique la formule des probabilités totales développée.",
      "$P(B) = 0{,}6 \\times 0{,}5 + 0{,}4 \\times 0{,}25 = 0{,}3 + 0{,}1$.",
      "$= 0{,}4$.",
      "$P(B) = 0{,}4$."
    ),
    canvas: arbre(0.6, 0.5, 0.25),
    tags: ["premiere", "maths", "probas_cond", "totales", "canvas", "short"],
  },
  {
    kind: "fixed",
    id: "premiere_pc_tot_fixed_4",
    niveau: "premiere-spe",
    matiere: "maths",
    notionId: "probabilites_conditionnelles",
    microId: "pc_totales",
    difficulty: 5,
    theme: "neutral",
    text: "Un test : $P(\\text{malade}) = 0{,}1$, $P_{\\text{malade}}(+) = 0{,}9$, $P_{\\text{sain}}(+) = 0{,}2$. Quelle est la probabilité d'avoir un test positif ?",
    format: "short",
    expected: ["0,27"],
    comparator: "number_equal",
    hint: "$0{,}1 \\times 0{,}9 + 0{,}9 \\times 0{,}2$.",
    explanation: exp(
      "On applique les probabilités totales sur la partition malade/sain.",
      "$P(+) = 0{,}1 \\times 0{,}9 + 0{,}9 \\times 0{,}2 = 0{,}09 + 0{,}18$.",
      "$= 0{,}27$.",
      "$P(+) = 0{,}27$."
    ),
    canvas: arbre(0.1, 0.9, 0.2),
    tags: ["premiere", "maths", "probas_cond", "totales", "canvas", "short"],
  },
  {
    kind: "fixed",
    id: "premiere_pc_tot_fixed_5",
    niveau: "premiere-spe",
    matiere: "maths",
    notionId: "probabilites_conditionnelles",
    microId: "pc_totales",
    difficulty: 5,
    theme: "neutral",
    text: "Avec $P(A) = 0{,}3$, $P_A(B) = 0{,}6$ et $P_{\\bar A}(B) = 0{,}2$, calcule $P(B)$.",
    format: "short",
    expected: ["0,32"],
    comparator: "number_equal",
    hint: "$P(\\bar A) = 0{,}7$ : additionne les deux chemins menant à $B$.",
    explanation: exp(
      "La formule des probabilités totales additionne les chemins qui aboutissent à $B$ : $P(B) = P(A) \\times P_A(B) + P(\\bar A) \\times P_{\\bar A}(B)$.",
      "$P(\\bar A) = 1 - 0{,}3 = 0{,}7$, donc $P(B) = 0{,}3 \\times 0{,}6 + 0{,}7 \\times 0{,}2$.",
      "$= 0{,}18 + 0{,}14 = 0{,}32$.",
      "$P(B) = 0{,}32$."
    ),
    canvas: arbre(0.3, 0.6, 0.2),
    tags: ["premiere", "maths", "probas_cond", "totales", "canvas", "short"],
  },
  {
    kind: "fixed",
    id: "premiere_pc_tot_fixed_6",
    niveau: "premiere-spe",
    matiere: "maths",
    notionId: "probabilites_conditionnelles",
    microId: "pc_totales",
    difficulty: 3,
    theme: "neutral",
    text: "On a $P(A \\cap B) = 0{,}25$ et $P(\\bar A \\cap B) = 0{,}15$. Combien vaut $P(B)$ ?",
    format: "short",
    expected: ["0,4"],
    comparator: "number_equal",
    hint: "$B$ se réalise soit avec $A$, soit avec $\\bar A$ : il n'y a pas d'autre cas.",
    explanation: exp(
      "Tout événement $B$ se décompose selon la partition $\\{A ; \\bar A\\}$ : $P(B) = P(A \\cap B) + P(\\bar A \\cap B)$.",
      "$0{,}25 + 0{,}15$.",
      "$= 0{,}4$.",
      "$P(B) = 0{,}4$."
    ),
    tags: ["premiere", "maths", "probas_cond", "totales", "short"],
  },
  {
    kind: "fixed",
    id: "premiere_pc_tot_fixed_7",
    niveau: "premiere-spe",
    matiere: "maths",
    notionId: "probabilites_conditionnelles",
    microId: "pc_totales",
    difficulty: 4,
    theme: "neutral",
    text: "On a $P(B) = 0{,}5$ et $P(A \\cap B) = 0{,}2$. Combien vaut $P(\\bar A \\cap B)$ ?",
    format: "short",
    expected: ["0,3"],
    comparator: "number_equal",
    hint: "Les deux morceaux de $B$ ont pour somme $P(B)$.",
    explanation: exp(
      "$B$ se partage en deux morceaux disjoints : celui qui rencontre $A$ et celui qui rencontre $\\bar A$.",
      "$P(\\bar A \\cap B) = P(B) - P(A \\cap B) = 0{,}5 - 0{,}2$.",
      "$= 0{,}3$.",
      "$P(\\bar A \\cap B) = 0{,}3$."
    ),
    tags: ["premiere", "maths", "probas_cond", "totales", "short"],
  },
  {
    kind: "fixed",
    id: "premiere_pc_tot_fixed_8",
    niveau: "premiere-spe",
    matiere: "maths",
    notionId: "probabilites_conditionnelles",
    microId: "pc_totales",
    difficulty: 4,
    theme: "neutral",
    text: "Pourquoi $\\{A ; \\bar A\\}$ forme-t-il une partition de l'univers ?",
    format: "qcm",
    choices: [
      "car $A$ et $\\bar A$ sont incompatibles et couvrent tous les cas",
      "car $A$ et $\\bar A$ ont la même probabilité",
      "car $P(A) + P(\\bar A) = 0$",
      "car $A$ et $\\bar A$ sont indépendants",
    ],
    expected: ["car $A$ et $\\bar A$ sont incompatibles et couvrent tous les cas"],
    comparator: "mcq_exact",
    hint: "Une partition : aucun recouvrement, aucun oubli.",
    explanation: exp(
      "Une partition découpe l'univers en morceaux disjoints qui, réunis, le recouvrent entièrement.",
      "$A$ et $\\bar A$ ne peuvent pas se produire ensemble (incompatibles) et l'un des deux se produit forcément.",
      "C'est ce qui autorise la formule des probabilités totales. Leurs probabilités ont pour somme $1$, et non $0$ ; elles n'ont aucune raison d'être égales.",
      "Ils sont incompatibles et couvrent tous les cas."
    ),
    tags: ["premiere", "maths", "probas_cond", "totales", "qcm"],
  },
  {
    kind: "fixed",
    id: "premiere_pc_tot_fixed_9",
    niveau: "premiere-spe",
    matiere: "maths",
    notionId: "probabilites_conditionnelles",
    microId: "pc_totales",
    difficulty: 5,
    theme: "neutral",
    text: "Une usine a deux machines : la première produit $60\\%$ des pièces avec $2\\%$ de défauts, la seconde $40\\%$ avec $5\\%$ de défauts. Quelle est la probabilité qu'une pièce soit défectueuse ?",
    format: "short",
    expected: ["0,032"],
    comparator: "number_equal",
    hint: "$0{,}6 \\times 0{,}02 + 0{,}4 \\times 0{,}05$.",
    explanation: exp(
      "La machine d'origine forme une partition : on additionne les deux chemins menant à « défectueuse ».",
      "$P(D) = 0{,}6 \\times 0{,}02 + 0{,}4 \\times 0{,}05 = 0{,}012 + 0{,}02$.",
      "$= 0{,}032$, soit $3{,}2\\%$ des pièces.",
      "La probabilité est $0{,}032$."
    ),
    canvas: arbre(0.6, 0.02, 0.05),
    tags: ["premiere", "maths", "probas_cond", "totales", "canvas", "short"],
  },
  {
    kind: "fixed",
    id: "premiere_pc_tot_fixed_10",
    niveau: "premiere-spe",
    matiere: "maths",
    notionId: "probabilites_conditionnelles",
    microId: "pc_totales",
    difficulty: 5,
    theme: "neutral",
    text: "A-t-on $P(B) = P_A(B) + P_{\\bar A}(B)$ ?",
    format: "qcm",
    choices: [
      "non : il faut pondérer par $P(A)$ et $P(\\bar A)$",
      "oui, toujours",
      "oui, si $A$ et $B$ sont indépendants",
      "oui, si $P(A) = 0{,}5$",
    ],
    expected: ["non : il faut pondérer par $P(A)$ et $P(\\bar A)$"],
    comparator: "mcq_exact",
    hint: "Cette somme pourrait dépasser $1$ : par exemple $0{,}9 + 0{,}8$.",
    explanation: exp(
      "La formule correcte est $P(B) = P(A) \\times P_A(B) + P(\\bar A) \\times P_{\\bar A}(B)$.",
      "Sans les poids $P(A)$ et $P(\\bar A)$, la somme peut dépasser $1$ : avec $P_A(B) = 0{,}9$ et $P_{\\bar A}(B) = 0{,}8$, on obtiendrait $1{,}7$, ce qui est impossible.",
      "Chaque probabilité conditionnelle doit être pesée par la probabilité du chemin qui y mène.",
      "Non : il faut pondérer par $P(A)$ et $P(\\bar A)$."
    ),
    tags: ["premiere", "maths", "probas_cond", "totales", "qcm"],
  },
  {
    kind: "fixed",
    id: "premiere_pc_tot_fixed_11",
    niveau: "premiere-spe",
    matiere: "maths",
    notionId: "probabilites_conditionnelles",
    microId: "pc_totales",
    difficulty: 3,
    theme: "neutral",
    text: "À quoi sert la formule des probabilités totales ?",
    format: "qcm",
    choices: [
      "à calculer $P(B)$ en additionnant tous les chemins qui mènent à $B$",
      "à calculer $P_A(B)$ à partir de $P_B(A)$",
      "à vérifier que deux événements sont indépendants",
      "à calculer la somme des branches d'un nœud",
    ],
    expected: ["à calculer $P(B)$ en additionnant tous les chemins qui mènent à $B$"],
    comparator: "mcq_exact",
    hint: "Sur un arbre, combien de chemins aboutissent à $B$ ?",
    explanation: exp(
      "Un événement $B$ peut être atteint par plusieurs chemins de l'arbre.",
      "La formule additionne la probabilité de chacun de ces chemins pour reconstituer $P(B)$.",
      "C'est la règle « on multiplie le long d'un chemin, on additionne entre les chemins ».",
      "Elle sert à calculer $P(B)$ en additionnant tous les chemins qui mènent à $B$."
    ),
    tags: ["premiere", "maths", "probas_cond", "totales", "qcm"],
  },
  {
    kind: "template",
    id: "premiere_pc_tot_tpl_1",
    niveau: "premiere-spe",
    matiere: "maths",
    notionId: "probabilites_conditionnelles",
    microId: "pc_totales",
    difficulty: 4,
    theme: "neutral",
    hint: "$P(B) = P(A)P_A(B) + P(\\bar A)P_{\\bar A}(B)$.",
    tags: ["premiere", "maths", "probas_cond", "totales", "template"],
    generate: () => {
      const pA = randomInt(2, 8) / 10;
      const pBsiA = randomInt(1, 9) / 10;
      const pBsiNonA = randomInt(1, 9) / 10;
      const pB = Math.round((pA * pBsiA + (1 - pA) * pBsiNonA) * 100) / 100;
      return {
        text: `Avec $P(A) = ${fr(pA)}$, $P_A(B) = ${fr(pBsiA)}$, $P_{\\bar A}(B) = ${fr(pBsiNonA)}$, calcule $P(B)$. (arrondir au centième)`,
        format: "short",
        expected: [fr(pB)],
        comparator: "number_equal",
        canvas: arbre(pA, pBsiA, pBsiNonA),
        explanation: exp(
          "On applique la formule des probabilités totales.",
          `$P(B) = ${fr(pA)} \\times ${fr(pBsiA)} + ${fr(1 - pA)} \\times ${fr(pBsiNonA)}$.`,
          `$= ${fr(pB)}$.`,
          `$P(B) = ${fr(pB)}$.`
        ),
      };
    },
  },

  /* ===================== PC_INDEPENDANCE ===================== */
  {
    kind: "fixed",
    id: "premiere_pc_ind_fixed_1",
    niveau: "premiere-spe",
    matiere: "maths",
    notionId: "probabilites_conditionnelles",
    microId: "pc_independance",
    difficulty: 2,
    theme: "neutral",
    text: "Deux événements $A$ et $B$ sont indépendants si et seulement si :",
    format: "qcm",
    choices: [
      "$P(A \\cap B) = P(A) \\times P(B)$",
      "$P(A \\cap B) = P(A) + P(B)$",
      "$P(A \\cap B) = 0$",
      "$P(A) = P(B)$",
    ],
    expected: ["$P(A \\cap B) = P(A) \\times P(B)$"],
    comparator: "mcq_exact",
    hint: "Produit des probabilités.",
    explanation: exp(
      "L'indépendance se caractérise par le produit.",
      "$A$ et $B$ indépendants $\\Leftrightarrow P(A \\cap B) = P(A) \\times P(B)$.",
      "C'est équivalent à $P_A(B) = P(B)$.",
      "$P(A \\cap B) = P(A) \\times P(B)$."
    ),
    tags: ["premiere", "maths", "probas_cond", "independance", "qcm"],
  },
  {
    kind: "fixed",
    id: "premiere_pc_ind_fixed_2",
    niveau: "premiere-spe",
    matiere: "maths",
    notionId: "probabilites_conditionnelles",
    microId: "pc_independance",
    difficulty: 3,
    theme: "neutral",
    text: "Si $A$ et $B$ sont indépendants avec $P(A) = 0{,}5$ et $P(B) = 0{,}4$, combien vaut $P(A \\cap B)$ ?",
    format: "short",
    expected: ["0,2"],
    comparator: "number_equal",
    hint: "$P(A) \\times P(B)$.",
    explanation: exp(
      "Pour des événements indépendants, $P(A \\cap B) = P(A) \\times P(B)$.",
      "$0{,}5 \\times 0{,}4$.",
      "$= 0{,}2$.",
      "$P(A \\cap B) = 0{,}2$."
    ),
    tags: ["premiere", "maths", "probas_cond", "independance", "short"],
  },
  {
    kind: "fixed",
    id: "premiere_pc_ind_fixed_3",
    niveau: "premiere-spe",
    matiere: "maths",
    notionId: "probabilites_conditionnelles",
    microId: "pc_independance",
    difficulty: 4,
    theme: "neutral",
    text: "On a $P(A) = 0{,}5$, $P(B) = 0{,}4$, $P(A \\cap B) = 0{,}3$. Les événements sont-ils indépendants ?",
    format: "qcm",
    choices: [
      "Non, car $0{,}3 \\neq 0{,}5 \\times 0{,}4$",
      "Oui, car $0{,}3 = 0{,}5 \\times 0{,}4$",
      "Oui, toujours",
      "On ne peut pas savoir",
    ],
    expected: ["Non, car $0{,}3 \\neq 0{,}5 \\times 0{,}4$"],
    comparator: "mcq_exact",
    hint: "Compare $P(A \\cap B)$ et $P(A)P(B)$.",
    explanation: exp(
      "On compare $P(A \\cap B)$ et $P(A) \\times P(B)$.",
      "$P(A) \\times P(B) = 0{,}5 \\times 0{,}4 = 0{,}2$, or $P(A \\cap B) = 0{,}3$.",
      "$0{,}3 \\neq 0{,}2$ : pas indépendants.",
      "Non, ils ne sont pas indépendants."
    ),
    tags: ["premiere", "maths", "probas_cond", "independance", "qcm"],
  },
  {
    kind: "fixed",
    id: "premiere_pc_ind_fixed_4",
    niveau: "premiere-spe",
    matiere: "maths",
    notionId: "probabilites_conditionnelles",
    microId: "pc_independance",
    difficulty: 3,
    theme: "neutral",
    text: "Si $A$ et $B$ sont indépendants, alors $P_A(B)$ est égale à :",
    format: "qcm",
    choices: ["$P(B)$", "$P(A)$", "$0$", "$1$"],
    expected: ["$P(B)$"],
    comparator: "mcq_exact",
    hint: "L'événement $A$ n'influence pas $B$.",
    explanation: exp(
      "L'indépendance signifie que $A$ n'influe pas sur $B$.",
      "La probabilité de $B$ sachant $A$ est la même que celle de $B$.",
      "$P_A(B) = P(B)$.",
      "$P(B)$."
    ),
    tags: ["premiere", "maths", "probas_cond", "independance", "qcm"],
  },
  {
    kind: "fixed",
    id: "premiere_pc_ind_fixed_5",
    niveau: "premiere-spe",
    matiere: "maths",
    notionId: "probabilites_conditionnelles",
    microId: "pc_independance",
    difficulty: 3,
    theme: "neutral",
    text: "Si $A$ et $B$ sont indépendants avec $P(A) = 0{,}2$ et $P(B) = 0{,}5$, combien vaut $P(A \\cap B)$ ?",
    format: "short",
    expected: ["0,1"],
    comparator: "number_equal",
    hint: "Pour des événements indépendants, on multiplie simplement les probabilités.",
    explanation: exp(
      "L'indépendance se traduit par $P(A \\cap B) = P(A) \\times P(B)$.",
      "$0{,}2 \\times 0{,}5$.",
      "$= 0{,}1$.",
      "$P(A \\cap B) = 0{,}1$."
    ),
    tags: ["premiere", "maths", "probas_cond", "independance", "short"],
  },
  {
    kind: "fixed",
    id: "premiere_pc_ind_fixed_6",
    niveau: "premiere-spe",
    matiere: "maths",
    notionId: "probabilites_conditionnelles",
    microId: "pc_independance",
    difficulty: 4,
    theme: "neutral",
    text: "On a $P(A) = 0{,}4$, $P(B) = 0{,}6$ et $P(A \\cap B) = 0{,}24$. Les événements sont-ils indépendants ?",
    format: "qcm",
    choices: [
      "oui, car $0{,}4 \\times 0{,}6 = 0{,}24$",
      "non, car $0{,}4 + 0{,}6 \\neq 0{,}24$",
      "non, car $P(A) \\neq P(B)$",
      "on ne peut pas conclure",
    ],
    expected: ["oui, car $0{,}4 \\times 0{,}6 = 0{,}24$"],
    comparator: "mcq_exact",
    hint: "Compare $P(A) \\times P(B)$ et $P(A \\cap B)$.",
    explanation: exp(
      "Le test d'indépendance consiste à comparer $P(A \\cap B)$ au produit $P(A) \\times P(B)$.",
      "$0{,}4 \\times 0{,}6 = 0{,}24$.",
      "C'est exactement la valeur de $P(A \\cap B)$ : le test est concluant.",
      "Oui, les événements sont indépendants."
    ),
    tags: ["premiere", "maths", "probas_cond", "independance", "qcm"],
  },
  {
    kind: "fixed",
    id: "premiere_pc_ind_fixed_7",
    niveau: "premiere-spe",
    matiere: "maths",
    notionId: "probabilites_conditionnelles",
    microId: "pc_independance",
    difficulty: 4,
    theme: "neutral",
    text: "On a $P(B) = 0{,}3$ et $P_A(B) = 0{,}3$. Que peut-on en déduire ?",
    format: "qcm",
    choices: [
      "$A$ et $B$ sont indépendants",
      "$A$ et $B$ sont incompatibles",
      "$P(A) = 0{,}3$",
      "$A$ est inclus dans $B$",
    ],
    expected: ["$A$ et $B$ sont indépendants"],
    comparator: "mcq_exact",
    hint: "Savoir que $A$ est réalisé change-t-il la probabilité de $B$ ?",
    explanation: exp(
      "L'indépendance signifie que la réalisation de $A$ ne modifie pas la probabilité de $B$.",
      "Ici $P_A(B) = P(B) = 0{,}3$ : l'information « $A$ est réalisé » n'apporte rien sur $B$.",
      "C'est exactement la caractérisation de l'indépendance ; on ne peut en revanche rien dire de $P(A)$.",
      "$A$ et $B$ sont indépendants."
    ),
    tags: ["premiere", "maths", "probas_cond", "independance", "qcm"],
  },
  {
    kind: "fixed",
    id: "premiere_pc_ind_fixed_8",
    niveau: "premiere-spe",
    matiere: "maths",
    notionId: "probabilites_conditionnelles",
    microId: "pc_independance",
    difficulty: 5,
    theme: "neutral",
    text: "Deux événements INCOMPATIBLES $A$ et $B$, de probabilités non nulles, sont-ils indépendants ?",
    format: "qcm",
    choices: [
      "non : $P(A \\cap B) = 0$ alors que $P(A) \\times P(B) > 0$",
      "oui : incompatibles et indépendants, c'est la même chose",
      "oui, si $P(A) = P(B)$",
      "on ne peut pas savoir",
    ],
    expected: ["non : $P(A \\cap B) = 0$ alors que $P(A) \\times P(B) > 0$"],
    comparator: "mcq_exact",
    hint: "Incompatibles signifie qu'ils ne peuvent pas se produire ensemble : que vaut alors $P(A \\cap B)$ ?",
    explanation: exp(
      "Incompatibles et indépendants sont deux notions différentes, souvent confondues.",
      "Incompatibles : $A \\cap B$ est impossible, donc $P(A \\cap B) = 0$. Or $P(A) \\times P(B) > 0$ puisque les deux probabilités sont non nulles.",
      "Les deux nombres diffèrent : les événements ne sont donc PAS indépendants. C'est même le contraire : savoir que $A$ est réalisé rend $B$ impossible.",
      "Non, ils ne sont pas indépendants."
    ),
    tags: ["premiere", "maths", "probas_cond", "independance", "qcm"],
  },
  {
    kind: "fixed",
    id: "premiere_pc_ind_fixed_9",
    niveau: "premiere-spe",
    matiere: "maths",
    notionId: "probabilites_conditionnelles",
    microId: "pc_independance",
    difficulty: 3,
    theme: "neutral",
    text: "On lance un dé deux fois de suite. Les résultats des deux lancers sont-ils indépendants ?",
    format: "qcm",
    choices: [
      "oui : le dé n'a pas de mémoire",
      "non : le premier lancer influence le second",
      "oui, seulement si le premier donne $6$",
      "non, car il s'agit du même dé",
    ],
    expected: ["oui : le dé n'a pas de mémoire"],
    comparator: "mcq_exact",
    hint: "Le résultat du premier lancer modifie-t-il les chances au second ?",
    explanation: exp(
      "Deux expériences sont indépendantes lorsque le résultat de l'une ne modifie pas les probabilités de l'autre.",
      "Un dé ne conserve aucune trace du lancer précédent : chaque face garde une probabilité de $\\dfrac{1}{6}$.",
      "Le fait que ce soit le même objet ne change rien ; c'est l'absence d'influence qui compte.",
      "Oui, les deux lancers sont indépendants."
    ),
    tags: ["premiere", "maths", "probas_cond", "independance", "qcm"],
  },
  {
    kind: "fixed",
    id: "premiere_pc_ind_fixed_10",
    niveau: "premiere-spe",
    matiere: "maths",
    notionId: "probabilites_conditionnelles",
    microId: "pc_independance",
    difficulty: 5,
    theme: "neutral",
    text: "On tire deux cartes SANS REMISE dans un jeu. Les deux tirages sont-ils indépendants ?",
    format: "qcm",
    choices: [
      "non : la première carte tirée modifie la composition du jeu",
      "oui : les cartes sont mélangées",
      "oui : chaque carte a la même probabilité",
      "cela dépend de la première carte",
    ],
    expected: ["non : la première carte tirée modifie la composition du jeu"],
    comparator: "mcq_exact",
    hint: "Après le premier tirage, combien de cartes reste-t-il ?",
    explanation: exp(
      "L'indépendance suppose que le premier résultat ne change rien aux probabilités du second.",
      "Sans remise, la carte tirée ne revient pas : le second tirage se fait sur un jeu réduit et modifié.",
      "Les probabilités du second tirage dépendent donc du premier : c'est le cas typique où l'on doit passer par un arbre et des probabilités conditionnelles.",
      "Non, les tirages ne sont pas indépendants."
    ),
    tags: ["premiere", "maths", "probas_cond", "independance", "qcm"],
  },
  {
    kind: "fixed",
    id: "premiere_pc_ind_fixed_11",
    niveau: "premiere-spe",
    matiere: "maths",
    notionId: "probabilites_conditionnelles",
    microId: "pc_independance",
    difficulty: 5,
    theme: "neutral",
    text: "$A$ et $B$ sont indépendants, $P(A) = 0{,}3$ et $P(A \\cap B) = 0{,}12$. Combien vaut $P(B)$ ?",
    format: "short",
    expected: ["0,4"],
    comparator: "number_equal",
    hint: "$0{,}3 \\times P(B) = 0{,}12$.",
    explanation: exp(
      "L'indépendance donne $P(A \\cap B) = P(A) \\times P(B)$ : on peut y voir une équation d'inconnue $P(B)$.",
      "$0{,}3 \\times P(B) = 0{,}12$.",
      "$P(B) = \\dfrac{0{,}12}{0{,}3} = 0{,}4$.",
      "$P(B) = 0{,}4$."
    ),
    tags: ["premiere", "maths", "probas_cond", "independance", "short"],
  },
  {
    kind: "template",
    id: "premiere_pc_ind_tpl_1",
    niveau: "premiere-spe",
    matiere: "maths",
    notionId: "probabilites_conditionnelles",
    microId: "pc_independance",
    difficulty: 3,
    theme: "neutral",
    hint: "Indépendants → $P(A \\cap B) = P(A) \\times P(B)$.",
    tags: ["premiere", "maths", "probas_cond", "independance", "template"],
    generate: () => {
      const pA = randomInt(2, 8) / 10;
      const pB = randomInt(2, 8) / 10;
      const inter = Math.round(pA * pB * 100) / 100;
      return {
        text: `$A$ et $B$ sont indépendants avec $P(A) = ${fr(pA)}$ et $P(B) = ${fr(pB)}$. Combien vaut $P(A \\cap B)$ ? (arrondir au centième)`,
        format: "short",
        expected: [fr(inter)],
        comparator: "number_equal",
        explanation: exp(
          "Pour des événements indépendants, on multiplie les probabilités.",
          `$P(A \\cap B) = ${fr(pA)} \\times ${fr(pB)}$.`,
          `$= ${fr(inter)}$.`,
          `$P(A \\cap B) = ${fr(inter)}$.`
        ),
      };
    },
  },
];
