// lib/tutor-v4/questionBank/premiere-spe/maths/produit-scalaire.bank.ts
//
// Chapitre : Calcul vectoriel et produit scalaire (notion "produit_scalaire")
// microSkills :
//   ps_coordonnees   — produit scalaire à partir des coordonnées
//   ps_norme_angle   — produit scalaire avec normes et angle (cosinus)
//   ps_orthogonalite — caractériser l'orthogonalité
//   ps_alkashi       — calculer une longueur ou un angle (Al-Kashi)
//
// PÉRIMÈTRE BO 2019 Première spé. Conventions : LaTeX, règle QCM. Canvas : fonctionGraphique (vecteurs comme points).

import type { TutorBankItemV4, CanvasFigure } from "@/lib/tutor-v4/types";

function randomInt(min: number, max: number) {
  return Math.floor(Math.random() * (max - min + 1)) + min;
}

function exp(definition: string, methode: string, calcul: string, conclusion: string) {
  return (
    `Définition : ${definition}\n\n` +
    `Méthode : ${methode}\n\n` +
    `Calcul / Observation : ${calcul}\n\n` +
    `Conclusion : ${conclusion}`
  );
}

// Deux vecteurs issus de l'origine, représentés par leurs extrémités.
function vecteurs(x1: number, y1: number, x2: number, y2: number): CanvasFigure {
  return {
    kind: "fonctionGraphique",
    size: { width: 300, height: 300 },
    xmin: -6,
    xmax: 6,
    ymin: -6,
    ymax: 6,
    grille: true,
    courbes: [
      { id: "u", type: "points", couleur: "#2563eb", points: [{ x: 0, y: 0 }, { x: x1, y: y1 }] },
      { id: "v", type: "points", couleur: "#dc2626", points: [{ x: 0, y: 0 }, { x: x2, y: y2 }] },
    ],
    points: [
      { x: x1, y: y1, label: "u", couleur: "#2563eb" },
      { x: x2, y: y2, label: "v", couleur: "#dc2626" },
    ],
  };
}

export const produitScalaireBank: TutorBankItemV4[] = [
  /* ===================== PS_COORDONNEES ===================== */
  {
    kind: "fixed",
    id: "premiere_ps_coord_fixed_1",
    niveau: "premiere-spe",
    matiere: "maths",
    notionId: "produit_scalaire",
    microId: "ps_coordonnees",
    difficulty: 2,
    theme: "neutral",
    text: "Dans une base orthonormée, le produit scalaire de $\\vec{u}(x ; y)$ et $\\vec{v}(x' ; y')$ vaut :",
    format: "qcm",
    choices: ["$xx' + yy'$", "$xy' + x'y$", "$xx' - yy'$", "$xy + x'y'$"],
    expected: ["$xx' + yy'$"],
    comparator: "mcq_exact",
    hint: "Produit des abscisses + produit des ordonnées.",
    explanation: exp(
      "En base orthonormée, le produit scalaire a une expression simple.",
      "On multiplie les abscisses, les ordonnées, et on additionne.",
      "$\\vec{u} \\cdot \\vec{v} = xx' + yy'$.",
      "$xx' + yy'$."
    ),
    tags: ["premiere", "maths", "produit_scalaire", "coordonnees", "qcm"],
  },
  {
    kind: "fixed",
    id: "premiere_ps_coord_fixed_2",
    niveau: "premiere-spe",
    matiere: "maths",
    notionId: "produit_scalaire",
    microId: "ps_coordonnees",
    difficulty: 3,
    theme: "neutral",
    text: "Calcule $\\vec{u} \\cdot \\vec{v}$ avec $\\vec{u}(2 ; 3)$ et $\\vec{v}(4 ; 1)$.",
    format: "short",
    expected: ["11"],
    comparator: "number_equal",
    hint: "$2 \\times 4 + 3 \\times 1$.",
    explanation: exp(
      "On applique $\\vec{u} \\cdot \\vec{v} = xx' + yy'$.",
      "$2 \\times 4 + 3 \\times 1 = 8 + 3$.",
      "$= 11$.",
      "$\\vec{u} \\cdot \\vec{v} = 11$."
    ),
    canvas: vecteurs(2, 3, 4, 1),
    tags: ["premiere", "maths", "produit_scalaire", "coordonnees", "canvas", "short"],
  },
  {
    kind: "fixed",
    id: "premiere_ps_coord_fixed_3",
    niveau: "premiere-spe",
    matiere: "maths",
    notionId: "produit_scalaire",
    microId: "ps_coordonnees",
    difficulty: 3,
    theme: "neutral",
    text: "Calcule $\\vec{u} \\cdot \\vec{v}$ avec $\\vec{u}(5 ; -2)$ et $\\vec{v}(3 ; 4)$.",
    format: "short",
    expected: ["7"],
    comparator: "number_equal",
    hint: "$5 \\times 3 + (-2) \\times 4$.",
    explanation: exp(
      "On applique $xx' + yy'$.",
      "$5 \\times 3 + (-2) \\times 4 = 15 - 8$.",
      "$= 7$.",
      "$\\vec{u} \\cdot \\vec{v} = 7$."
    ),
    canvas: vecteurs(5, -2, 3, 4),
    tags: ["premiere", "maths", "produit_scalaire", "coordonnees", "canvas", "short"],
  },
  {
    kind: "fixed",
    id: "premiere_ps_coord_fixed_4",
    niveau: "premiere-spe",
    matiere: "maths",
    notionId: "produit_scalaire",
    microId: "ps_coordonnees",
    difficulty: 2,
    theme: "neutral",
    text: "La norme d'un vecteur $\\vec{u}(x ; y)$ vaut :",
    format: "qcm",
    choices: ["$\\sqrt{x^2 + y^2}$", "$x^2 + y^2$", "$x + y$", "$\\sqrt{x + y}$"],
    expected: ["$\\sqrt{x^2 + y^2}$"],
    comparator: "mcq_exact",
    hint: "Théorème de Pythagore.",
    explanation: exp(
      "La norme est la longueur du vecteur.",
      "Avec Pythagore : $\\|\\vec{u}\\| = \\sqrt{x^2 + y^2}$.",
      "C'est aussi $\\sqrt{\\vec{u} \\cdot \\vec{u}}$.",
      "$\\sqrt{x^2 + y^2}$."
    ),
    tags: ["premiere", "maths", "produit_scalaire", "coordonnees", "qcm"],
  },
  {
    kind: "fixed",
    id: "premiere_ps_coord_fixed_5",
    niveau: "premiere-spe",
    matiere: "maths",
    notionId: "produit_scalaire",
    microId: "ps_coordonnees",
    difficulty: 3,
    theme: "neutral",
    text: "Calcule la norme de $\\vec{u}(3 ; 4)$.",
    format: "short",
    expected: ["5"],
    comparator: "number_equal",
    hint: "$\\sqrt{3^2 + 4^2}$.",
    explanation: exp(
      "On applique $\\|\\vec{u}\\| = \\sqrt{x^2 + y^2}$.",
      "$\\sqrt{3^2 + 4^2} = \\sqrt{9 + 16} = \\sqrt{25}$.",
      "$= 5$.",
      "$\\|\\vec{u}\\| = 5$."
    ),
    tags: ["premiere", "maths", "produit_scalaire", "coordonnees", "short"],
  },
  {
    kind: "fixed",
    id: "premiere_ps_coord_fixed_6",
    niveau: "premiere-spe",
    matiere: "maths",
    notionId: "produit_scalaire",
    microId: "ps_coordonnees",
    difficulty: 4,
    theme: "neutral",
    text: "Calcule $\\vec{u} \\cdot \\vec{v}$ avec $\\vec{u}(1 ; -3)$ et $\\vec{v}(2 ; 5)$.",
    format: "short",
    expected: ["-13"],
    comparator: "number_equal",
    hint: "$xx' + yy'$ : attention au signe de $-3$.",
    explanation: exp(
      "En base orthonormée, $\\vec{u} \\cdot \\vec{v} = xx' + yy'$.",
      "$1 \\times 2 + (-3) \\times 5 = 2 - 15$.",
      "$= -13$. Un produit scalaire peut être négatif : cela signifie que l'angle est obtus.",
      "$\\vec{u} \\cdot \\vec{v} = -13$."
    ),
    tags: ["premiere", "maths", "produit_scalaire", "coordonnees", "short"],
  },
  {
    kind: "fixed",
    id: "premiere_ps_coord_fixed_7",
    niveau: "premiere-spe",
    matiere: "maths",
    notionId: "produit_scalaire",
    microId: "ps_coordonnees",
    difficulty: 4,
    theme: "neutral",
    text: "Calcule $\\vec{u} \\cdot \\vec{v}$ avec $\\vec{u}(-2 ; 4)$ et $\\vec{v}(3 ; -1)$.",
    format: "short",
    expected: ["-10"],
    comparator: "number_equal",
    hint: "$(-2) \\times 3 + 4 \\times (-1)$.",
    explanation: exp(
      "On applique $\\vec{u} \\cdot \\vec{v} = xx' + yy'$ en soignant les signes.",
      "$(-2) \\times 3 = -6$ et $4 \\times (-1) = -4$.",
      "$-6 + (-4) = -10$.",
      "$\\vec{u} \\cdot \\vec{v} = -10$."
    ),
    tags: ["premiere", "maths", "produit_scalaire", "coordonnees", "short"],
  },
  {
    kind: "fixed",
    id: "premiere_ps_coord_fixed_8",
    niveau: "premiere-spe",
    matiere: "maths",
    notionId: "produit_scalaire",
    microId: "ps_coordonnees",
    difficulty: 4,
    theme: "neutral",
    text: "Calcule la norme de $\\vec{u}(-5 ; 12)$.",
    format: "short",
    expected: ["13"],
    comparator: "number_equal",
    hint: "$\\sqrt{(-5)^2 + 12^2}$ : le carré efface le signe moins.",
    explanation: exp(
      "La norme vaut $\\|\\vec{u}\\| = \\sqrt{x^2 + y^2}$.",
      "$(-5)^2 = 25$ et $12^2 = 144$, donc $\\sqrt{25 + 144} = \\sqrt{169}$.",
      "$= 13$. Une norme est une longueur : elle est toujours positive.",
      "$\\|\\vec{u}\\| = 13$."
    ),
    tags: ["premiere", "maths", "produit_scalaire", "coordonnees", "short"],
  },
  {
    kind: "fixed",
    id: "premiere_ps_coord_fixed_9",
    niveau: "premiere-spe",
    matiere: "maths",
    notionId: "produit_scalaire",
    microId: "ps_coordonnees",
    difficulty: 4,
    theme: "neutral",
    text: "Quelle est la norme de $\\vec{u}(1 ; 1)$ ?",
    format: "qcm",
    choices: ["$\\sqrt{2}$", "$2$", "$1$", "$\\sqrt{1}$"],
    expected: ["$\\sqrt{2}$"],
    comparator: "mcq_exact",
    hint: "$\\sqrt{1^2 + 1^2}$ ne se simplifie pas en un entier.",
    explanation: exp(
      "On applique $\\|\\vec{u}\\| = \\sqrt{x^2 + y^2}$.",
      "$\\sqrt{1^2 + 1^2} = \\sqrt{2}$.",
      "$\\sqrt{2} \\approx 1{,}41$ : c'est la diagonale du carré de côté $1$, et non $2$ (on n'additionne pas les coordonnées).",
      "$\\|\\vec{u}\\| = \\sqrt{2}$."
    ),
    tags: ["premiere", "maths", "produit_scalaire", "coordonnees", "qcm"],
  },
  {
    kind: "fixed",
    id: "premiere_ps_coord_fixed_10",
    niveau: "premiere-spe",
    matiere: "maths",
    notionId: "produit_scalaire",
    microId: "ps_coordonnees",
    difficulty: 5,
    theme: "neutral",
    text: "À quoi est égal $\\vec{u} \\cdot \\vec{u}$ ?",
    format: "qcm",
    choices: [
      "$\\|\\vec{u}\\|^2$",
      "$\\|\\vec{u}\\|$",
      "$0$",
      "$2\\|\\vec{u}\\|$",
    ],
    expected: ["$\\|\\vec{u}\\|^2$"],
    comparator: "mcq_exact",
    hint: "Calcule avec les coordonnées : $x \\times x + y \\times y$.",
    explanation: exp(
      "On applique la formule des coordonnées au vecteur avec lui-même.",
      "$\\vec{u} \\cdot \\vec{u} = x \\times x + y \\times y = x^2 + y^2$.",
      "Or $\\|\\vec{u}\\| = \\sqrt{x^2 + y^2}$, donc $x^2 + y^2 = \\|\\vec{u}\\|^2$.",
      "$\\vec{u} \\cdot \\vec{u} = \\|\\vec{u}\\|^2$ : c'est le carré scalaire."
    ),
    tags: ["premiere", "maths", "produit_scalaire", "coordonnees", "qcm"],
  },
  {
    kind: "fixed",
    id: "premiere_ps_coord_fixed_11",
    niveau: "premiere-spe",
    matiere: "maths",
    notionId: "produit_scalaire",
    microId: "ps_coordonnees",
    difficulty: 3,
    theme: "neutral",
    text: "Calcule $\\vec{u} \\cdot \\vec{v}$ avec $\\vec{u}(6 ; 0)$ et $\\vec{v}(0 ; 7)$.",
    format: "short",
    expected: ["0"],
    comparator: "number_equal",
    hint: "$6 \\times 0 + 0 \\times 7$.",
    explanation: exp(
      "On applique $\\vec{u} \\cdot \\vec{v} = xx' + yy'$.",
      "$6 \\times 0 + 0 \\times 7 = 0 + 0$.",
      "$= 0$. Ces deux vecteurs sont dirigés l'un selon l'axe des abscisses, l'autre selon celui des ordonnées.",
      "$\\vec{u} \\cdot \\vec{v} = 0$ : les vecteurs sont orthogonaux."
    ),
    tags: ["premiere", "maths", "produit_scalaire", "coordonnees", "short"],
  },
  {
    kind: "template",
    id: "premiere_ps_coord_tpl_1",
    niveau: "premiere-spe",
    matiere: "maths",
    notionId: "produit_scalaire",
    microId: "ps_coordonnees",
    difficulty: 3,
    theme: "neutral",
    hint: "$xx' + yy'$.",
    tags: ["premiere", "maths", "produit_scalaire", "coordonnees", "template"],
    generate: () => {
      const x1 = randomInt(1, 5);
      const y1 = randomInt(-4, 5);
      const x2 = randomInt(1, 5);
      const y2 = randomInt(-4, 5);
      const ps = x1 * x2 + y1 * y2;
      return {
        text: `Calcule $\\vec{u} \\cdot \\vec{v}$ avec $\\vec{u}(${x1} ; ${y1})$ et $\\vec{v}(${x2} ; ${y2})$.`,
        format: "short",
        expected: [String(ps)],
        comparator: "number_equal",
        explanation: exp(
          "On applique $\\vec{u} \\cdot \\vec{v} = xx' + yy'$.",
          `$${x1} \\times ${x2} + (${y1}) \\times (${y2})$.`,
          `$= ${x1 * x2} ${y1 * y2 >= 0 ? "+ " + y1 * y2 : "- " + -(y1 * y2)} = ${ps}$.`,
          `$\\vec{u} \\cdot \\vec{v} = ${ps}$.`
        ),
      };
    },
  },
  {
    kind: "template",
    id: "premiere_ps_coord_tpl_2",
    niveau: "premiere-spe",
    matiere: "maths",
    notionId: "produit_scalaire",
    microId: "ps_coordonnees",
    difficulty: 3,
    theme: "neutral",
    hint: "$\\sqrt{x^2 + y^2}$ (pense aux triplets pythagoriciens).",
    tags: ["premiere", "maths", "produit_scalaire", "coordonnees", "template"],
    generate: () => {
      const triplets = [
        { x: 3, y: 4, n: 5 },
        { x: 6, y: 8, n: 10 },
        { x: 5, y: 12, n: 13 },
        { x: 8, y: 6, n: 10 },
      ];
      const t = triplets[randomInt(0, triplets.length - 1)];
      return {
        text: `Calcule la norme de $\\vec{u}(${t.x} ; ${t.y})$.`,
        format: "short",
        expected: [String(t.n)],
        comparator: "number_equal",
        explanation: exp(
          "On applique $\\|\\vec{u}\\| = \\sqrt{x^2 + y^2}$.",
          `$\\sqrt{${t.x}^2 + ${t.y}^2} = \\sqrt{${t.x * t.x + t.y * t.y}}$.`,
          `$= ${t.n}$.`,
          `$\\|\\vec{u}\\| = ${t.n}$.`
        ),
      };
    },
  },

  /* ===================== PS_NORME_ANGLE ===================== */
  {
    kind: "fixed",
    id: "premiere_ps_na_fixed_1",
    niveau: "premiere-spe",
    matiere: "maths",
    notionId: "produit_scalaire",
    microId: "ps_norme_angle",
    difficulty: 2,
    theme: "neutral",
    text: "Le produit scalaire avec l'angle $\\theta$ entre les vecteurs s'écrit :",
    format: "qcm",
    choices: [
      "$\\|\\vec{u}\\| \\, \\|\\vec{v}\\| \\cos\\theta$",
      "$\\|\\vec{u}\\| \\, \\|\\vec{v}\\| \\sin\\theta$",
      "$\\|\\vec{u}\\| + \\|\\vec{v}\\|$",
      "$\\|\\vec{u}\\| \\, \\|\\vec{v}\\| \\tan\\theta$",
    ],
    expected: ["$\\|\\vec{u}\\| \\, \\|\\vec{v}\\| \\cos\\theta$"],
    comparator: "mcq_exact",
    hint: "Avec le cosinus de l'angle.",
    explanation: exp(
      "Le produit scalaire relie normes et angle.",
      "$\\vec{u} \\cdot \\vec{v} = \\|\\vec{u}\\| \\, \\|\\vec{v}\\| \\cos\\theta$.",
      "Le cosinus apparaît, pas le sinus.",
      "$\\|\\vec{u}\\| \\, \\|\\vec{v}\\| \\cos\\theta$."
    ),
    tags: ["premiere", "maths", "produit_scalaire", "norme_angle", "qcm"],
  },
  {
    kind: "fixed",
    id: "premiere_ps_na_fixed_2",
    niveau: "premiere-spe",
    matiere: "maths",
    notionId: "produit_scalaire",
    microId: "ps_norme_angle",
    difficulty: 3,
    theme: "neutral",
    text: "Deux vecteurs de normes $3$ et $5$ forment un angle de $60°$. Combien vaut leur produit scalaire ?",
    format: "short",
    expected: ["7.5"],
    comparator: "number_equal",
    hint: "$3 \\times 5 \\times \\cos(60°)$ avec $\\cos(60°) = 0{,}5$.",
    explanation: exp(
      "On applique $\\vec{u} \\cdot \\vec{v} = \\|\\vec{u}\\| \\, \\|\\vec{v}\\| \\cos\\theta$.",
      "$3 \\times 5 \\times \\cos(60°) = 15 \\times 0{,}5$.",
      "$= 7{,}5$.",
      "$\\vec{u} \\cdot \\vec{v} = 7{,}5$."
    ),
    tags: ["premiere", "maths", "produit_scalaire", "norme_angle", "short"],
  },
  {
    kind: "fixed",
    id: "premiere_ps_na_fixed_3",
    niveau: "premiere-spe",
    matiere: "maths",
    notionId: "produit_scalaire",
    microId: "ps_norme_angle",
    difficulty: 3,
    theme: "neutral",
    text: "Deux vecteurs colinéaires de même sens, de normes $4$ et $6$. Que vaut leur produit scalaire ?",
    format: "short",
    expected: ["24"],
    comparator: "number_equal",
    hint: "Angle $0°$, $\\cos(0) = 1$.",
    explanation: exp(
      "Colinéaires de même sens : l'angle est $0°$, $\\cos(0) = 1$.",
      "$\\vec{u} \\cdot \\vec{v} = 4 \\times 6 \\times 1$.",
      "$= 24$.",
      "$\\vec{u} \\cdot \\vec{v} = 24$."
    ),
    tags: ["premiere", "maths", "produit_scalaire", "norme_angle", "short"],
  },
  {
    kind: "fixed",
    id: "premiere_ps_na_fixed_4",
    niveau: "premiere-spe",
    matiere: "maths",
    notionId: "produit_scalaire",
    microId: "ps_norme_angle",
    difficulty: 4,
    theme: "neutral",
    text: "Le produit scalaire de deux vecteurs non nuls est négatif. L'angle entre eux est :",
    format: "qcm",
    choices: ["obtus (entre $90°$ et $180°$)", "aigu", "droit", "nul"],
    expected: ["obtus (entre $90°$ et $180°$)"],
    comparator: "mcq_exact",
    hint: "Signe de $\\cos\\theta$.",
    explanation: exp(
      "Le signe du produit scalaire est celui de $\\cos\\theta$.",
      "$\\vec{u} \\cdot \\vec{v} < 0$ signifie $\\cos\\theta < 0$.",
      "Donc l'angle est obtus.",
      "Obtus (entre $90°$ et $180°$)."
    ),
    tags: ["premiere", "maths", "produit_scalaire", "norme_angle", "qcm"],
  },
  {
    kind: "fixed",
    id: "premiere_ps_na_fixed_5",
    niveau: "premiere-spe",
    matiere: "maths",
    notionId: "produit_scalaire",
    microId: "ps_norme_angle",
    difficulty: 3,
    theme: "neutral",
    text: "Deux vecteurs de normes $2$ et $7$ forment un angle de $0°$. Combien vaut leur produit scalaire ?",
    format: "short",
    expected: ["14"],
    comparator: "number_equal",
    hint: "$\\cos 0° = 1$.",
    explanation: exp(
      "La formule est $\\vec{u} \\cdot \\vec{v} = \\|\\vec{u}\\| \\times \\|\\vec{v}\\| \\times \\cos\\theta$.",
      "Un angle de $0°$ signifie que les vecteurs sont de même direction et même sens : $\\cos 0° = 1$.",
      "$2 \\times 7 \\times 1 = 14$.",
      "Le produit scalaire vaut $14$ : c'est sa valeur maximale pour ces deux normes."
    ),
    tags: ["premiere", "maths", "produit_scalaire", "norme_angle", "short"],
  },
  {
    kind: "fixed",
    id: "premiere_ps_na_fixed_6",
    niveau: "premiere-spe",
    matiere: "maths",
    notionId: "produit_scalaire",
    microId: "ps_norme_angle",
    difficulty: 3,
    theme: "neutral",
    text: "Deux vecteurs de normes $3$ et $4$ forment un angle de $90°$. Combien vaut leur produit scalaire ?",
    format: "short",
    expected: ["0"],
    comparator: "number_equal",
    hint: "$\\cos 90° = 0$.",
    explanation: exp(
      "On applique $\\vec{u} \\cdot \\vec{v} = \\|\\vec{u}\\| \\times \\|\\vec{v}\\| \\times \\cos\\theta$.",
      "Pour un angle droit, $\\cos 90° = 0$.",
      "$3 \\times 4 \\times 0 = 0$, quelles que soient les normes.",
      "Le produit scalaire vaut $0$ : c'est la caractérisation de l'orthogonalité."
    ),
    tags: ["premiere", "maths", "produit_scalaire", "norme_angle", "short"],
  },
  {
    kind: "fixed",
    id: "premiere_ps_na_fixed_7",
    niveau: "premiere-spe",
    matiere: "maths",
    notionId: "produit_scalaire",
    microId: "ps_norme_angle",
    difficulty: 4,
    theme: "neutral",
    text: "Deux vecteurs de normes $5$ et $2$ sont colinéaires de sens CONTRAIRE (angle $180°$). Combien vaut leur produit scalaire ?",
    format: "short",
    expected: ["-10"],
    comparator: "number_equal",
    hint: "$\\cos 180° = -1$.",
    explanation: exp(
      "On applique $\\vec{u} \\cdot \\vec{v} = \\|\\vec{u}\\| \\times \\|\\vec{v}\\| \\times \\cos\\theta$.",
      "Deux vecteurs de sens contraire forment un angle de $180°$, et $\\cos 180° = -1$.",
      "$5 \\times 2 \\times (-1) = -10$.",
      "Le produit scalaire vaut $-10$ : c'est sa valeur minimale pour ces deux normes."
    ),
    tags: ["premiere", "maths", "produit_scalaire", "norme_angle", "short"],
  },
  {
    kind: "fixed",
    id: "premiere_ps_na_fixed_8",
    niveau: "premiere-spe",
    matiere: "maths",
    notionId: "produit_scalaire",
    microId: "ps_norme_angle",
    difficulty: 4,
    theme: "neutral",
    text: "Deux vecteurs de normes $4$ et $6$ forment un angle de $60°$. Combien vaut leur produit scalaire (avec $\\cos 60° = 0{,}5$) ?",
    format: "short",
    expected: ["12"],
    comparator: "number_equal",
    hint: "$4 \\times 6 \\times 0{,}5$.",
    explanation: exp(
      "On applique $\\vec{u} \\cdot \\vec{v} = \\|\\vec{u}\\| \\times \\|\\vec{v}\\| \\times \\cos\\theta$.",
      "$4 \\times 6 = 24$, puis $24 \\times 0{,}5$.",
      "$= 12$.",
      "Le produit scalaire vaut $12$."
    ),
    tags: ["premiere", "maths", "produit_scalaire", "norme_angle", "short"],
  },
  {
    kind: "fixed",
    id: "premiere_ps_na_fixed_9",
    niveau: "premiere-spe",
    matiere: "maths",
    notionId: "produit_scalaire",
    microId: "ps_norme_angle",
    difficulty: 4,
    theme: "neutral",
    text: "Le produit scalaire de deux vecteurs non nuls est positif. L'angle entre eux est :",
    format: "qcm",
    choices: ["aigu (entre $0°$ et $90°$)", "obtus", "droit", "plat"],
    expected: ["aigu (entre $0°$ et $90°$)"],
    comparator: "mcq_exact",
    hint: "Les normes sont positives : le signe vient de $\\cos\\theta$.",
    explanation: exp(
      "Dans $\\|\\vec{u}\\| \\times \\|\\vec{v}\\| \\times \\cos\\theta$, les deux normes sont strictement positives.",
      "Le signe du produit scalaire est donc exactement celui de $\\cos\\theta$.",
      "$\\cos\\theta > 0$ correspond à un angle compris entre $0°$ et $90°$.",
      "L'angle est aigu."
    ),
    tags: ["premiere", "maths", "produit_scalaire", "norme_angle", "qcm"],
  },
  {
    kind: "fixed",
    id: "premiere_ps_na_fixed_10",
    niveau: "premiere-spe",
    matiere: "maths",
    notionId: "produit_scalaire",
    microId: "ps_norme_angle",
    difficulty: 5,
    theme: "neutral",
    text: "Deux vecteurs de normes $3$ et $8$ forment un angle de $45°$. Combien vaut leur produit scalaire (avec $\\cos 45° = \\dfrac{\\sqrt{2}}{2}$) ?",
    format: "qcm",
    choices: ["$12\\sqrt{2}$", "$24\\sqrt{2}$", "$12$", "$\\dfrac{24}{\\sqrt{2}}$"],
    expected: ["$12\\sqrt{2}$"],
    comparator: "mcq_exact",
    hint: "$24 \\times \\dfrac{\\sqrt{2}}{2}$ : divise $24$ par $2$.",
    explanation: exp(
      "On applique $\\vec{u} \\cdot \\vec{v} = \\|\\vec{u}\\| \\times \\|\\vec{v}\\| \\times \\cos\\theta$.",
      "$3 \\times 8 = 24$, puis $24 \\times \\dfrac{\\sqrt{2}}{2}$.",
      "$= \\dfrac{24\\sqrt{2}}{2} = 12\\sqrt{2}$.",
      "Le produit scalaire vaut $12\\sqrt{2} \\approx 17$."
    ),
    tags: ["premiere", "maths", "produit_scalaire", "norme_angle", "qcm"],
  },
  {
    kind: "fixed",
    id: "premiere_ps_na_fixed_11",
    niveau: "premiere-spe",
    matiere: "maths",
    notionId: "produit_scalaire",
    microId: "ps_norme_angle",
    difficulty: 5,
    theme: "neutral",
    text: "À normes fixées, pour quel angle le produit scalaire est-il MAXIMAL ?",
    format: "qcm",
    choices: ["$0°$", "$45°$", "$90°$", "$180°$"],
    expected: ["$0°$"],
    comparator: "mcq_exact",
    hint: "Quand $\\cos\\theta$ est-il le plus grand possible ?",
    explanation: exp(
      "Les normes étant fixées, le produit scalaire varie comme $\\cos\\theta$.",
      "Le cosinus atteint son maximum, $1$, en $\\theta = 0°$.",
      "Le produit scalaire vaut alors $\\|\\vec{u}\\| \\times \\|\\vec{v}\\|$ : les vecteurs « tirent » exactement dans la même direction. À $180°$, il est au contraire minimal.",
      "Le produit scalaire est maximal pour un angle de $0°$."
    ),
    tags: ["premiere", "maths", "produit_scalaire", "norme_angle", "qcm"],
  },
  {
    kind: "template",
    id: "premiere_ps_na_tpl_1",
    niveau: "premiere-spe",
    matiere: "maths",
    notionId: "produit_scalaire",
    microId: "ps_norme_angle",
    difficulty: 3,
    theme: "neutral",
    hint: "$\\|\\vec{u}\\| \\, \\|\\vec{v}\\| \\cos\\theta$.",
    tags: ["premiere", "maths", "produit_scalaire", "norme_angle", "template"],
    generate: () => {
      const cas = randomInt(0, 2);
      const data = [
        { deg: "0°", cos: 1, cosTxt: "1" },
        { deg: "60°", cos: 0.5, cosTxt: "0{,}5" },
        { deg: "90°", cos: 0, cosTxt: "0" },
      ][cas];
      const nu = randomInt(2, 6);
      const nv = randomInt(2, 6);
      const ps = nu * nv * data.cos;
      return {
        text: `Deux vecteurs de normes $${nu}$ et $${nv}$ forment un angle de $${data.deg}$. Combien vaut leur produit scalaire ?`,
        format: "short",
        expected: [String(ps)],
        comparator: "number_equal",
        explanation: exp(
          "On applique $\\vec{u} \\cdot \\vec{v} = \\|\\vec{u}\\| \\, \\|\\vec{v}\\| \\cos\\theta$.",
          `$${nu} \\times ${nv} \\times \\cos(${data.deg}) = ${nu * nv} \\times ${data.cosTxt}$.`,
          `$= ${ps}$.`,
          `$\\vec{u} \\cdot \\vec{v} = ${String(ps).replace(".", "{,}")}$.`
        ),
      };
    },
  },

  /* ===================== PS_ORTHOGONALITE ===================== */
  {
    kind: "fixed",
    id: "premiere_ps_orth_fixed_1",
    niveau: "premiere-spe",
    matiere: "maths",
    notionId: "produit_scalaire",
    microId: "ps_orthogonalite",
    difficulty: 2,
    theme: "neutral",
    text: "Deux vecteurs non nuls sont orthogonaux si et seulement si leur produit scalaire est :",
    format: "qcm",
    choices: ["nul", "positif", "négatif", "égal à $1$"],
    expected: ["nul"],
    comparator: "mcq_exact",
    hint: "$\\cos(90°) = 0$.",
    explanation: exp(
      "Orthogonaux signifie angle droit, donc $\\cos(90°) = 0$.",
      "Le produit scalaire $\\|\\vec{u}\\|\\|\\vec{v}\\|\\cos\\theta$ vaut alors $0$.",
      "$\\vec{u} \\perp \\vec{v} \\Leftrightarrow \\vec{u} \\cdot \\vec{v} = 0$.",
      "Le produit scalaire est nul."
    ),
    tags: ["premiere", "maths", "produit_scalaire", "orthogonalite", "qcm"],
  },
  {
    kind: "fixed",
    id: "premiere_ps_orth_fixed_2",
    niveau: "premiere-spe",
    matiere: "maths",
    notionId: "produit_scalaire",
    microId: "ps_orthogonalite",
    difficulty: 3,
    theme: "neutral",
    text: "Les vecteurs $\\vec{u}(2 ; 3)$ et $\\vec{v}(3 ; -2)$ sont-ils orthogonaux ?",
    format: "qcm",
    choices: ["Oui, car $\\vec{u} \\cdot \\vec{v} = 0$", "Non", "Oui, car colinéaires", "On ne peut pas savoir"],
    expected: ["Oui, car $\\vec{u} \\cdot \\vec{v} = 0$"],
    comparator: "mcq_exact",
    hint: "Calcule $2\\times3 + 3\\times(-2)$.",
    explanation: exp(
      "On calcule le produit scalaire.",
      "$2 \\times 3 + 3 \\times (-2) = 6 - 6 = 0$.",
      "Produit scalaire nul → orthogonaux.",
      "Oui, ils sont orthogonaux."
    ),
    canvas: vecteurs(2, 3, 3, -2),
    tags: ["premiere", "maths", "produit_scalaire", "orthogonalite", "canvas", "qcm"],
  },
  {
    kind: "fixed",
    id: "premiere_ps_orth_fixed_3",
    niveau: "premiere-spe",
    matiere: "maths",
    notionId: "produit_scalaire",
    microId: "ps_orthogonalite",
    difficulty: 3,
    theme: "neutral",
    text: "Pour quelle valeur de $k$ les vecteurs $\\vec{u}(2 ; k)$ et $\\vec{v}(4 ; -2)$ sont-ils orthogonaux ?",
    format: "short",
    expected: ["4"],
    comparator: "number_equal",
    hint: "$\\vec{u} \\cdot \\vec{v} = 0$ : $8 - 2k = 0$.",
    explanation: exp(
      "On écrit que le produit scalaire est nul.",
      "$2 \\times 4 + k \\times (-2) = 0 \\Leftrightarrow 8 - 2k = 0$.",
      "$2k = 8$ donc $k = 4$.",
      "$k = 4$."
    ),
    tags: ["premiere", "maths", "produit_scalaire", "orthogonalite", "short"],
  },
  {
    kind: "fixed",
    id: "premiere_ps_orth_fixed_4",
    niveau: "premiere-spe",
    matiere: "maths",
    notionId: "produit_scalaire",
    microId: "ps_orthogonalite",
    difficulty: 2,
    theme: "neutral",
    text: "Les vecteurs $\\vec{u}(1 ; 0)$ et $\\vec{v}(0 ; 1)$ sont :",
    format: "qcm",
    choices: ["orthogonaux", "colinéaires", "égaux", "opposés"],
    expected: ["orthogonaux"],
    comparator: "mcq_exact",
    hint: "Produit scalaire $= 0$ ?",
    explanation: exp(
      "On calcule le produit scalaire.",
      "$1 \\times 0 + 0 \\times 1 = 0$.",
      "Produit nul → orthogonaux (ce sont les axes).",
      "Orthogonaux."
    ),
    tags: ["premiere", "maths", "produit_scalaire", "orthogonalite", "qcm"],
  },
  {
    kind: "fixed",
    id: "premiere_ps_orth_fixed_5",
    niveau: "premiere-spe",
    matiere: "maths",
    notionId: "produit_scalaire",
    microId: "ps_orthogonalite",
    difficulty: 4,
    theme: "neutral",
    text: "Les vecteurs $\\vec{u}(3 ; 1)$ et $\\vec{v}(-1 ; 3)$ sont-ils orthogonaux ?",
    format: "qcm",
    choices: [
      "oui, car leur produit scalaire vaut $0$",
      "non, car leur produit scalaire vaut $6$",
      "non, car leurs coordonnées sont différentes",
      "on ne peut pas savoir sans l'angle",
    ],
    expected: ["oui, car leur produit scalaire vaut $0$"],
    comparator: "mcq_exact",
    hint: "Calcule $3 \\times (-1) + 1 \\times 3$.",
    explanation: exp(
      "Deux vecteurs non nuls sont orthogonaux si et seulement si leur produit scalaire est nul.",
      "$\\vec{u} \\cdot \\vec{v} = 3 \\times (-1) + 1 \\times 3 = -3 + 3$.",
      "$= 0$. Nul besoin de connaître l'angle : les coordonnées suffisent.",
      "Oui, ils sont orthogonaux."
    ),
    tags: ["premiere", "maths", "produit_scalaire", "orthogonalite", "qcm"],
  },
  {
    kind: "fixed",
    id: "premiere_ps_orth_fixed_6",
    niveau: "premiere-spe",
    matiere: "maths",
    notionId: "produit_scalaire",
    microId: "ps_orthogonalite",
    difficulty: 4,
    theme: "neutral",
    text: "Les vecteurs $\\vec{u}(4 ; 2)$ et $\\vec{v}(1 ; 2)$ sont-ils orthogonaux ?",
    format: "qcm",
    choices: [
      "non, car leur produit scalaire vaut $8$",
      "oui, car leur produit scalaire vaut $0$",
      "oui, car ils n'ont aucune coordonnée commune",
      "non, car ils sont colinéaires",
    ],
    expected: ["non, car leur produit scalaire vaut $8$"],
    comparator: "mcq_exact",
    hint: "Calcule $4 \\times 1 + 2 \\times 2$.",
    explanation: exp(
      "On teste l'orthogonalité en calculant le produit scalaire.",
      "$\\vec{u} \\cdot \\vec{v} = 4 \\times 1 + 2 \\times 2 = 4 + 4$.",
      "$= 8 \\neq 0$ : les vecteurs ne sont pas orthogonaux. Le produit étant positif, l'angle est même aigu.",
      "Non : leur produit scalaire vaut $8$."
    ),
    tags: ["premiere", "maths", "produit_scalaire", "orthogonalite", "qcm"],
  },
  {
    kind: "fixed",
    id: "premiere_ps_orth_fixed_7",
    niveau: "premiere-spe",
    matiere: "maths",
    notionId: "produit_scalaire",
    microId: "ps_orthogonalite",
    difficulty: 5,
    theme: "neutral",
    text: "Pour quelle valeur de $k$ les vecteurs $\\vec{u}(3 ; k)$ et $\\vec{v}(6 ; -2)$ sont-ils orthogonaux ?",
    format: "short",
    expected: ["9"],
    comparator: "number_equal",
    hint: "Résous $3 \\times 6 + k \\times (-2) = 0$.",
    explanation: exp(
      "Deux vecteurs sont orthogonaux lorsque leur produit scalaire est nul : on pose l'équation.",
      "$3 \\times 6 + k \\times (-2) = 0$, soit $18 - 2k = 0$.",
      "$2k = 18$, donc $k = 9$.",
      "Pour $k = 9$, les vecteurs sont orthogonaux."
    ),
    tags: ["premiere", "maths", "produit_scalaire", "orthogonalite", "short"],
  },
  {
    kind: "fixed",
    id: "premiere_ps_orth_fixed_8",
    niveau: "premiere-spe",
    matiere: "maths",
    notionId: "produit_scalaire",
    microId: "ps_orthogonalite",
    difficulty: 5,
    theme: "neutral",
    text: "Quel vecteur est toujours orthogonal à $\\vec{u}(a ; b)$ ?",
    format: "qcm",
    choices: [
      "$\\vec{v}(-b ; a)$",
      "$\\vec{v}(a ; -b)$",
      "$\\vec{v}(b ; a)$",
      "$\\vec{v}(-a ; -b)$",
    ],
    expected: ["$\\vec{v}(-b ; a)$"],
    comparator: "mcq_exact",
    hint: "Teste chaque proposition en calculant le produit scalaire avec $\\vec{u}$.",
    explanation: exp(
      "On cherche $\\vec{v}$ tel que $\\vec{u} \\cdot \\vec{v} = 0$ pour TOUTES les valeurs de $a$ et $b$.",
      "Avec $\\vec{v}(-b ; a)$ : $a \\times (-b) + b \\times a = -ab + ab = 0$. C'est vrai quels que soient $a$ et $b$.",
      "Avec $\\vec{v}(a ; -b)$, on obtiendrait $a^2 - b^2$, qui n'est nul que dans des cas particuliers.",
      "Le vecteur $\\vec{v}(-b ; a)$ est toujours orthogonal à $\\vec{u}(a ; b)$ : on échange les coordonnées et on change un signe."
    ),
    tags: ["premiere", "maths", "produit_scalaire", "orthogonalite", "qcm"],
  },
  {
    kind: "fixed",
    id: "premiere_ps_orth_fixed_9",
    niveau: "premiere-spe",
    matiere: "maths",
    notionId: "produit_scalaire",
    microId: "ps_orthogonalite",
    difficulty: 5,
    theme: "neutral",
    text: "Deux droites ont pour vecteurs directeurs $\\vec{u}(1 ; 2)$ et $\\vec{v}(2 ; -1)$. Que peut-on dire de ces droites ?",
    format: "qcm",
    choices: [
      "elles sont perpendiculaires",
      "elles sont parallèles",
      "elles sont confondues",
      "on ne peut pas conclure",
    ],
    expected: ["elles sont perpendiculaires"],
    comparator: "mcq_exact",
    hint: "Deux droites sont perpendiculaires quand leurs vecteurs directeurs sont orthogonaux.",
    explanation: exp(
      "L'orthogonalité des vecteurs directeurs caractérise la perpendicularité des droites.",
      "$\\vec{u} \\cdot \\vec{v} = 1 \\times 2 + 2 \\times (-1) = 2 - 2$.",
      "$= 0$ : les vecteurs directeurs sont orthogonaux.",
      "Les droites sont perpendiculaires."
    ),
    tags: ["premiere", "maths", "produit_scalaire", "orthogonalite", "qcm"],
  },
  {
    kind: "fixed",
    id: "premiere_ps_orth_fixed_10",
    niveau: "premiere-spe",
    matiere: "maths",
    notionId: "produit_scalaire",
    microId: "ps_orthogonalite",
    difficulty: 4,
    theme: "neutral",
    text: "Dans un triangle $ABC$, comment traduire par un produit scalaire que $(AH)$ est la hauteur issue de $A$ ?",
    format: "qcm",
    choices: [
      "$\\vec{AH} \\cdot \\vec{BC} = 0$",
      "$\\vec{AH} \\cdot \\vec{BC} = 1$",
      "$\\vec{AB} \\cdot \\vec{AC} = 0$",
      "$\\vec{AH} \\cdot \\vec{AB} = 0$",
    ],
    expected: ["$\\vec{AH} \\cdot \\vec{BC} = 0$"],
    comparator: "mcq_exact",
    hint: "Une hauteur est perpendiculaire au côté OPPOSÉ.",
    explanation: exp(
      "La hauteur issue de $A$ est la droite passant par $A$ et perpendiculaire au côté opposé $[BC]$.",
      "Perpendiculaire se traduit par un produit scalaire nul entre un vecteur de la hauteur et un vecteur du côté.",
      "D'où $\\vec{AH} \\cdot \\vec{BC} = 0$. La proposition $\\vec{AB} \\cdot \\vec{AC} = 0$ dirait, elle, que le triangle est rectangle en $A$.",
      "$\\vec{AH} \\cdot \\vec{BC} = 0$."
    ),
    tags: ["premiere", "maths", "produit_scalaire", "orthogonalite", "qcm"],
  },
  {
    kind: "fixed",
    id: "premiere_ps_orth_fixed_11",
    niveau: "premiere-spe",
    matiere: "maths",
    notionId: "produit_scalaire",
    microId: "ps_orthogonalite",
    difficulty: 4,
    theme: "neutral",
    text: "Dans un quadrilatère $ABCD$, on a $\\vec{AB} \\cdot \\vec{AD} = 0$. Qu'en déduit-on ?",
    format: "qcm",
    choices: [
      "l'angle en $A$ est droit",
      "le quadrilatère est un carré",
      "les côtés $[AB]$ et $[AD]$ ont la même longueur",
      "le quadrilatère est un losange",
    ],
    expected: ["l'angle en $A$ est droit"],
    comparator: "mcq_exact",
    hint: "Un produit scalaire nul donne une information d'ANGLE, pas de longueur.",
    explanation: exp(
      "Un produit scalaire nul entre deux vecteurs non nuls signifie qu'ils sont orthogonaux.",
      "$\\vec{AB}$ et $\\vec{AD}$ partent tous deux de $A$ : l'angle qu'ils forment en $A$ est donc droit.",
      "Cela ne dit rien des longueurs : un carré exigerait en plus $AB = AD$ et des conditions sur les autres sommets.",
      "L'angle en $A$ est droit."
    ),
    tags: ["premiere", "maths", "produit_scalaire", "orthogonalite", "qcm"],
  },
  {
    kind: "template",
    id: "premiere_ps_orth_tpl_1",
    niveau: "premiere-spe",
    matiere: "maths",
    notionId: "produit_scalaire",
    microId: "ps_orthogonalite",
    difficulty: 3,
    theme: "neutral",
    hint: "Orthogonaux ⟺ produit scalaire nul.",
    tags: ["premiere", "maths", "produit_scalaire", "orthogonalite", "template"],
    generate: () => {
      const a = randomInt(1, 4);
      const b = randomInt(1, 4);
      // v orthogonal à u(a;b) : v(b;-a) -> ps = ab - ab = 0
      const ortho = randomInt(0, 1) === 1;
      const x2 = b;
      const y2 = ortho ? -a : a; // si non ortho, ps = ab + ab != 0
      const ps = a * x2 + b * y2;
      const correct = ps === 0 ? "Oui (orthogonaux)" : "Non";
      return {
        text: `Les vecteurs $\\vec{u}(${a} ; ${b})$ et $\\vec{v}(${x2} ; ${y2})$ sont-ils orthogonaux ?`,
        format: "qcm",
        choices: ["Oui (orthogonaux)", "Non", "Ils sont colinéaires", "On ne peut pas savoir"],
        expected: [correct],
        comparator: "mcq_exact",
        explanation: exp(
          "On calcule le produit scalaire $xx' + yy'$.",
          `$${a} \\times ${x2} + ${b} \\times (${y2}) = ${ps}$.`,
          `Produit scalaire ${ps === 0 ? "nul → orthogonaux" : "non nul → non orthogonaux"}.`,
          `${correct}.`
        ),
      };
    },
  },

  /* ===================== PS_ALKASHI ===================== */
  {
    kind: "fixed",
    id: "premiere_ps_alk_fixed_1",
    niveau: "premiere-spe",
    matiere: "maths",
    notionId: "produit_scalaire",
    microId: "ps_alkashi",
    difficulty: 3,
    theme: "neutral",
    text: "La formule d'Al-Kashi dans un triangle $ABC$ s'écrit :",
    format: "qcm",
    choices: [
      "$a^2 = b^2 + c^2 - 2bc\\cos A$",
      "$a^2 = b^2 + c^2 + 2bc\\cos A$",
      "$a^2 = b^2 - c^2 - 2bc\\cos A$",
      "$a = b + c - 2bc\\cos A$",
    ],
    expected: ["$a^2 = b^2 + c^2 - 2bc\\cos A$"],
    comparator: "mcq_exact",
    hint: "Généralisation de Pythagore avec un $\\cos$.",
    explanation: exp(
      "Al-Kashi généralise le théorème de Pythagore à un triangle quelconque.",
      "Le terme correctif est $-2bc\\cos A$.",
      "$a^2 = b^2 + c^2 - 2bc\\cos A$.",
      "$a^2 = b^2 + c^2 - 2bc\\cos A$."
    ),
    tags: ["premiere", "maths", "produit_scalaire", "alkashi", "qcm"],
  },
  {
    kind: "fixed",
    id: "premiere_ps_alk_fixed_2",
    niveau: "premiere-spe",
    matiere: "maths",
    notionId: "produit_scalaire",
    microId: "ps_alkashi",
    difficulty: 4,
    theme: "neutral",
    text: "Dans un triangle, $b = 3$, $c = 5$, $\\widehat{A} = 60°$. Calcule $a^2$ (avec $\\cos 60° = 0{,}5$).",
    format: "short",
    expected: ["19"],
    comparator: "number_equal",
    hint: "$a^2 = 9 + 25 - 2\\times3\\times5\\times0{,}5$.",
    explanation: exp(
      "On applique Al-Kashi.",
      "$a^2 = 3^2 + 5^2 - 2 \\times 3 \\times 5 \\times 0{,}5 = 9 + 25 - 15$.",
      "$= 19$.",
      "$a^2 = 19$."
    ),
    tags: ["premiere", "maths", "produit_scalaire", "alkashi", "short"],
  },
  {
    kind: "fixed",
    id: "premiere_ps_alk_fixed_3",
    niveau: "premiere-spe",
    matiere: "maths",
    notionId: "produit_scalaire",
    microId: "ps_alkashi",
    difficulty: 4,
    theme: "neutral",
    text: "Si l'angle $\\widehat{A} = 90°$, la formule d'Al-Kashi $a^2 = b^2 + c^2 - 2bc\\cos A$ devient :",
    format: "qcm",
    choices: ["$a^2 = b^2 + c^2$ (Pythagore)", "$a^2 = b^2 - c^2$", "$a^2 = 2bc$", "$a = b + c$"],
    expected: ["$a^2 = b^2 + c^2$ (Pythagore)"],
    comparator: "mcq_exact",
    hint: "$\\cos 90° = 0$.",
    explanation: exp(
      "Quand $\\widehat{A} = 90°$, $\\cos A = 0$.",
      "Le terme $-2bc\\cos A$ disparaît.",
      "$a^2 = b^2 + c^2$ : c'est Pythagore.",
      "$a^2 = b^2 + c^2$ (Pythagore)."
    ),
    tags: ["premiere", "maths", "produit_scalaire", "alkashi", "qcm"],
  },
  {
    kind: "fixed",
    id: "premiere_ps_alk_fixed_4",
    niveau: "premiere-spe",
    matiere: "maths",
    notionId: "produit_scalaire",
    microId: "ps_alkashi",
    difficulty: 5,
    theme: "neutral",
    text: "Dans un triangle, $b = 4$, $c = 6$, $\\widehat{A} = 60°$. Calcule $a$ (avec $\\cos 60° = 0{,}5$).",
    format: "qcm",
    choices: ["$2\\sqrt{7}$", "$\\sqrt{28}$ arrondi à $6$", "$10$", "$\\sqrt{52}$"],
    expected: ["$2\\sqrt{7}$"],
    comparator: "mcq_exact",
    hint: "$a^2 = 16 + 36 - 2\\times4\\times6\\times0{,}5 = 28$.",
    explanation: exp(
      "On calcule d'abord $a^2$ avec Al-Kashi.",
      "$a^2 = 16 + 36 - 24 = 28$.",
      "$a = \\sqrt{28} = 2\\sqrt{7}$.",
      "$a = 2\\sqrt{7}$."
    ),
    tags: ["premiere", "maths", "produit_scalaire", "alkashi", "qcm"],
  },
  {
    kind: "fixed",
    id: "premiere_ps_alk_fixed_5",
    niveau: "premiere-spe",
    matiere: "maths",
    notionId: "produit_scalaire",
    microId: "ps_alkashi",
    difficulty: 4,
    theme: "neutral",
    text: "Dans un triangle, $b = 5$, $c = 8$ et $\\widehat{A} = 60°$. Calcule $a$ (avec $\\cos 60° = 0{,}5$).",
    format: "short",
    expected: ["7"],
    comparator: "number_equal",
    hint: "$a^2 = 25 + 64 - 2 \\times 5 \\times 8 \\times 0{,}5$.",
    explanation: exp(
      "La formule d'Al-Kashi donne $a^2 = b^2 + c^2 - 2bc\\cos A$.",
      "$a^2 = 25 + 64 - 2 \\times 5 \\times 8 \\times 0{,}5 = 89 - 40$.",
      "$a^2 = 49$, donc $a = 7$ (une longueur est positive).",
      "$a = 7$."
    ),
    tags: ["premiere", "maths", "produit_scalaire", "alkashi", "short"],
  },
  {
    kind: "fixed",
    id: "premiere_ps_alk_fixed_6",
    niveau: "premiere-spe",
    matiere: "maths",
    notionId: "produit_scalaire",
    microId: "ps_alkashi",
    difficulty: 5,
    theme: "neutral",
    text: "Dans un triangle, $b = 2$, $c = 3$ et $\\widehat{A} = 120°$. Calcule $a^2$ (avec $\\cos 120° = -0{,}5$).",
    format: "short",
    expected: ["19"],
    comparator: "number_equal",
    hint: "Le cosinus est négatif : $-2bc \\times (-0{,}5)$ devient une ADDITION.",
    explanation: exp(
      "On applique $a^2 = b^2 + c^2 - 2bc\\cos A$ en soignant le signe du cosinus.",
      "$a^2 = 4 + 9 - 2 \\times 2 \\times 3 \\times (-0{,}5) = 13 - (-6)$.",
      "$= 13 + 6 = 19$. Avec un angle obtus, le côté opposé est plus grand que ne le donnerait Pythagore.",
      "$a^2 = 19$."
    ),
    tags: ["premiere", "maths", "produit_scalaire", "alkashi", "short"],
  },
  {
    kind: "fixed",
    id: "premiere_ps_alk_fixed_7",
    niveau: "premiere-spe",
    matiere: "maths",
    notionId: "produit_scalaire",
    microId: "ps_alkashi",
    difficulty: 5,
    theme: "neutral",
    text: "Dans un triangle, $a = 7$, $b = 5$ et $c = 8$. Combien vaut $\\cos \\widehat{A}$ ?",
    format: "qcm",
    choices: ["$0{,}5$", "$-0{,}5$", "$0{,}8$", "$1$"],
    expected: ["$0{,}5$"],
    comparator: "mcq_exact",
    hint: "Isole $\\cos A$ dans $a^2 = b^2 + c^2 - 2bc\\cos A$.",
    explanation: exp(
      "Al-Kashi permet aussi de retrouver un ANGLE quand on connaît les trois côtés.",
      "$49 = 25 + 64 - 2 \\times 5 \\times 8 \\times \\cos A$, soit $49 = 89 - 80\\cos A$.",
      "$80\\cos A = 40$, donc $\\cos A = 0{,}5$ (l'angle $\\widehat{A}$ vaut $60°$).",
      "$\\cos \\widehat{A} = 0{,}5$."
    ),
    tags: ["premiere", "maths", "produit_scalaire", "alkashi", "qcm"],
  },
  {
    kind: "fixed",
    id: "premiere_ps_alk_fixed_8",
    niveau: "premiere-spe",
    matiere: "maths",
    notionId: "produit_scalaire",
    microId: "ps_alkashi",
    difficulty: 3,
    theme: "neutral",
    text: "Dans quel cas la formule d'Al-Kashi est-elle utile ?",
    format: "qcm",
    choices: [
      "on connaît deux côtés et l'angle entre eux, et on cherche le troisième côté",
      "on connaît les trois angles et on cherche les côtés",
      "uniquement dans un triangle rectangle",
      "uniquement dans un triangle équilatéral",
    ],
    expected: [
      "on connaît deux côtés et l'angle entre eux, et on cherche le troisième côté",
    ],
    comparator: "mcq_exact",
    hint: "C'est la généralisation de Pythagore à un triangle quelconque.",
    explanation: exp(
      "Al-Kashi relie les trois côtés d'un triangle quelconque à l'un de ses angles.",
      "Connaissant $b$, $c$ et l'angle $\\widehat{A}$ qu'ils forment, elle donne $a$ ; connaissant les trois côtés, elle donne les angles.",
      "Les trois angles seuls ne suffisent jamais : une infinité de triangles de tailles différentes ont les mêmes angles.",
      "Elle sert quand on connaît deux côtés et l'angle entre eux."
    ),
    tags: ["premiere", "maths", "produit_scalaire", "alkashi", "qcm"],
  },
  {
    kind: "fixed",
    id: "premiere_ps_alk_fixed_9",
    niveau: "premiere-spe",
    matiere: "maths",
    notionId: "produit_scalaire",
    microId: "ps_alkashi",
    difficulty: 4,
    theme: "neutral",
    text: "Dans un triangle, $b = 4$, $c = 5$ et $\\widehat{A} = 90°$. Calcule $a^2$.",
    format: "short",
    expected: ["41"],
    comparator: "number_equal",
    hint: "$\\cos 90° = 0$ : le dernier terme disparaît.",
    explanation: exp(
      "On applique $a^2 = b^2 + c^2 - 2bc\\cos A$ avec $\\cos 90° = 0$.",
      "$a^2 = 16 + 25 - 2 \\times 4 \\times 5 \\times 0$.",
      "$= 41$. On retrouve exactement le théorème de Pythagore : Al-Kashi le généralise.",
      "$a^2 = 41$."
    ),
    tags: ["premiere", "maths", "produit_scalaire", "alkashi", "short"],
  },
  {
    kind: "fixed",
    id: "premiere_ps_alk_fixed_10",
    niveau: "premiere-spe",
    matiere: "maths",
    notionId: "produit_scalaire",
    microId: "ps_alkashi",
    difficulty: 5,
    theme: "reunion",
    text: "Un terrain triangulaire a deux côtés de $30$ m et $40$ m formant un angle de $60°$. Combien vaut le carré de la longueur du troisième côté (avec $\\cos 60° = 0{,}5$) ?",
    format: "short",
    expected: ["1300"],
    comparator: "number_equal",
    hint: "$30^2 + 40^2 - 2 \\times 30 \\times 40 \\times 0{,}5$.",
    explanation: exp(
      "On modélise le terrain par un triangle et on applique Al-Kashi.",
      "$a^2 = 900 + 1600 - 2 \\times 30 \\times 40 \\times 0{,}5 = 2500 - 1200$.",
      "$= 1300$. (Le troisième côté mesure $\\sqrt{1300} \\approx 36$ m.)",
      "$a^2 = 1300$."
    ),
    tags: ["premiere", "maths", "produit_scalaire", "alkashi", "short"],
  },
  {
    kind: "fixed",
    id: "premiere_ps_alk_fixed_11",
    niveau: "premiere-spe",
    matiere: "maths",
    notionId: "produit_scalaire",
    microId: "ps_alkashi",
    difficulty: 5,
    theme: "neutral",
    text: "Si l'angle $\\widehat{A}$ est OBTUS, que peut-on dire de $a^2$ par rapport à $b^2 + c^2$ ?",
    format: "qcm",
    choices: [
      "$a^2 > b^2 + c^2$",
      "$a^2 < b^2 + c^2$",
      "$a^2 = b^2 + c^2$",
      "on ne peut pas comparer",
    ],
    expected: ["$a^2 > b^2 + c^2$"],
    comparator: "mcq_exact",
    hint: "Pour un angle obtus, $\\cos A < 0$ : que devient le terme $-2bc\\cos A$ ?",
    explanation: exp(
      "Tout se joue sur le signe du terme correctif $-2bc\\cos A$ dans $a^2 = b^2 + c^2 - 2bc\\cos A$.",
      "Un angle obtus a un cosinus négatif, donc $-2bc\\cos A$ est POSITIF : on ajoute quelque chose à $b^2 + c^2$.",
      "D'où $a^2 > b^2 + c^2$ : plus l'angle en $A$ s'ouvre, plus le côté opposé s'allonge.",
      "$a^2 > b^2 + c^2$."
    ),
    tags: ["premiere", "maths", "produit_scalaire", "alkashi", "qcm"],
  },
  {
    kind: "template",
    id: "premiere_ps_alk_tpl_1",
    niveau: "premiere-spe",
    matiere: "maths",
    notionId: "produit_scalaire",
    microId: "ps_alkashi",
    difficulty: 4,
    theme: "neutral",
    hint: "$a^2 = b^2 + c^2 - 2bc\\cos A$, $\\cos 60° = 0{,}5$.",
    tags: ["premiere", "maths", "produit_scalaire", "alkashi", "template"],
    generate: () => {
      const b = randomInt(2, 6);
      const c = randomInt(2, 7);
      const a2 = b * b + c * c - b * c; // cos60 = 0.5 → 2bc*0.5 = bc
      return {
        text: `Dans un triangle, $b = ${b}$, $c = ${c}$, $\\widehat{A} = 60°$. Calcule $a^2$ (avec $\\cos 60° = 0{,}5$).`,
        format: "short",
        expected: [String(a2)],
        comparator: "number_equal",
        explanation: exp(
          "On applique Al-Kashi $a^2 = b^2 + c^2 - 2bc\\cos A$.",
          `$a^2 = ${b}^2 + ${c}^2 - 2 \\times ${b} \\times ${c} \\times 0{,}5 = ${b * b} + ${c * c} - ${b * c}$.`,
          `$= ${a2}$.`,
          `$a^2 = ${a2}$.`
        ),
      };
    },
  },
];
