// lib/tutor-v4/questionBank/premiere-spe/maths/suites.bank.ts
//
// Chapitre : Suites numériques (notion "suites")
// microSkills :
//   suite_termes        — calculer des termes (explicite / récurrence)
//   suite_arithmetique  — raison et terme général d'une suite arithmétique
//   suite_geometrique   — raison et terme général d'une suite géométrique
//   suite_variation     — sens de variation d'une suite
//   suite_sommes        — sommes 1+2+...+n et 1+q+...+q^n
//
// PÉRIMÈTRE BO 2019 Première spé. Conventions : LaTeX, règle QCM (bonne réponse en 1re position, mélangée par le moteur).

import type { TutorBankItemV4 } from "@/lib/tutor-v4/types";

function randomInt(min: number, max: number) {
  return Math.floor(Math.random() * (max - min + 1)) + min;
}

function exp(definition: string, methode: string, calcul: string, conclusion: string) {
  return (
    `Définition : ${definition}\n\n` +
    `Méthode : ${methode}\n\n` +
    `Calcul / Observation : ${calcul}\n\n` +
    `Conclusion : ${conclusion}`
  );
}

export const suitesBank: TutorBankItemV4[] = [
  /* ===================== SUITE_TERMES ===================== */
  {
    kind: "fixed",
    id: "premiere_suites_termes_fixed_1",
    niveau: "premiere-spe",
    matiere: "maths",
    notionId: "suites",
    microId: "suite_termes",
    difficulty: 2,
    theme: "neutral",
    text: "La suite est définie par $u_n = 2n + 1$. Combien vaut $u_3$ ?",
    format: "short",
    expected: ["7"],
    comparator: "number_equal",
    hint: "Remplace $n$ par $3$.",
    explanation: exp(
      "Une suite explicite se calcule en remplaçant $n$ par sa valeur.",
      "On remplace $n$ par $3$ dans $u_n = 2n + 1$.",
      "$u_3 = 2 \\times 3 + 1 = 7$.",
      "$u_3 = 7$."
    ),
    tags: ["premiere", "maths", "suites", "termes", "short"],
  },
  {
    kind: "fixed",
    id: "premiere_suites_termes_fixed_2",
    niveau: "premiere-spe",
    matiere: "maths",
    notionId: "suites",
    microId: "suite_termes",
    difficulty: 3,
    theme: "neutral",
    text: "La suite est définie par $u_n = n^2 - 1$. Combien vaut $u_4$ ?",
    format: "short",
    expected: ["15"],
    comparator: "number_equal",
    hint: "$u_4 = 4^2 - 1$.",
    explanation: exp(
      "On remplace $n$ par la valeur demandée dans l'expression de $u_n$.",
      "Ici $u_4 = 4^2 - 1$.",
      "$= 16 - 1 = 15$.",
      "$u_4 = 15$."
    ),
    tags: ["premiere", "maths", "suites", "termes", "short"],
  },
  {
    kind: "fixed",
    id: "premiere_suites_termes_fixed_3",
    niveau: "premiere-spe",
    matiere: "maths",
    notionId: "suites",
    microId: "suite_termes",
    difficulty: 3,
    theme: "neutral",
    text: "La suite est définie par $u_0 = 5$ et $u_{n+1} = u_n + 4$. Combien vaut $u_2$ ?",
    format: "short",
    expected: ["13"],
    comparator: "number_equal",
    hint: "Calcule $u_1$ puis $u_2$.",
    explanation: exp(
      "Une suite par récurrence se calcule de proche en proche.",
      "$u_1 = u_0 + 4 = 9$, puis $u_2 = u_1 + 4$.",
      "$u_2 = 9 + 4 = 13$.",
      "$u_2 = 13$."
    ),
    tags: ["premiere", "maths", "suites", "termes", "recurrence", "short"],
  },
  {
    kind: "fixed",
    id: "premiere_suites_termes_fixed_4",
    niveau: "premiere-spe",
    matiere: "maths",
    notionId: "suites",
    microId: "suite_termes",
    difficulty: 4,
    theme: "neutral",
    text: "La suite est définie par $u_0 = 2$ et $u_{n+1} = 3u_n - 1$. Combien vaut $u_2$ ?",
    format: "short",
    expected: ["14"],
    comparator: "number_equal",
    hint: "$u_1 = 3 \\times 2 - 1$, puis recommence.",
    explanation: exp(
      "On applique la relation de récurrence pas à pas.",
      "$u_1 = 3 \\times 2 - 1 = 5$, puis $u_2 = 3 \\times 5 - 1$.",
      "$u_2 = 15 - 1 = 14$.",
      "$u_2 = 14$."
    ),
    tags: ["premiere", "maths", "suites", "termes", "recurrence", "short"],
  },
  {
    kind: "fixed",
    id: "premiere_suites_termes_fixed_5",
    niveau: "premiere-spe",
    matiere: "maths",
    notionId: "suites",
    microId: "suite_termes",
    difficulty: 3,
    theme: "neutral",
    text: "Pour la suite $u_{n+1} = f(u_n)$, que faut-il connaître pour calculer $u_5$ ?",
    format: "qcm",
    choices: [
      "Le terme précédent $u_4$",
      "Seulement la valeur de $5$",
      "Tous les termes après $u_5$",
      "Rien, $u_5 = 5$",
    ],
    expected: ["Le terme précédent $u_4$"],
    comparator: "mcq_exact",
    hint: "« Récurrence » = chaque terme dépend du précédent.",
    explanation: exp(
      "Dans une suite récurrente, chaque terme dépend du terme précédent.",
      "Pour obtenir $u_5$ avec $u_{n+1} = f(u_n)$, il faut $u_4$.",
      "On calcule donc de proche en proche depuis le premier terme.",
      "Il faut connaître le terme précédent $u_4$."
    ),
    tags: ["premiere", "maths", "suites", "termes", "qcm"],
  },
  {
    kind: "fixed",
    id: "premiere_suites_termes_fixed_6",
    niveau: "premiere-spe",
    matiere: "maths",
    notionId: "suites",
    microId: "suite_termes",
    difficulty: 3,
    theme: "neutral",
    text: "La suite est définie par $u_n = \\dfrac{n + 3}{n + 1}$. Combien vaut $u_1$ ?",
    format: "short",
    expected: ["2"],
    comparator: "number_equal",
    hint: "Remplace $n$ par $1$ au numérateur ET au dénominateur.",
    explanation: exp(
      "Dans une suite explicite, on remplace $n$ par sa valeur partout où il apparaît.",
      "Ici $u_1 = \\dfrac{1 + 3}{1 + 1}$.",
      "$= \\dfrac{4}{2} = 2$.",
      "$u_1 = 2$."
    ),
    tags: ["premiere", "maths", "suites", "termes", "short"],
  },
  {
    kind: "fixed",
    id: "premiere_suites_termes_fixed_7",
    niveau: "premiere-spe",
    matiere: "maths",
    notionId: "suites",
    microId: "suite_termes",
    difficulty: 4,
    theme: "neutral",
    text: "La suite est définie par $u_0 = 1$ et $u_{n+1} = u_n^2 + 1$. Combien vaut $u_2$ ?",
    format: "short",
    expected: ["5"],
    comparator: "number_equal",
    hint: "Calcule d'abord $u_1$, puis élève CE résultat au carré.",
    explanation: exp(
      "Chaque terme s'obtient en élevant le précédent au carré puis en ajoutant $1$.",
      "$u_1 = 1^2 + 1 = 2$, puis $u_2 = 2^2 + 1$.",
      "$u_2 = 4 + 1 = 5$.",
      "$u_2 = 5$."
    ),
    tags: ["premiere", "maths", "suites", "termes", "recurrence", "short"],
  },
  {
    kind: "fixed",
    id: "premiere_suites_termes_fixed_8",
    niveau: "premiere-spe",
    matiere: "maths",
    notionId: "suites",
    microId: "suite_termes",
    difficulty: 3,
    theme: "reunion",
    text: "Un planteur de Bras-Panon récolte $u_n = 50 - 3n$ gousses de vanille sur un pied lors de la $n$-ième année. Combien en récolte-t-il la 4ᵉ année ?",
    format: "short",
    expected: ["38"],
    comparator: "number_equal",
    hint: "Remplace $n$ par $4$.",
    explanation: exp(
      "La formule donne directement la récolte de l'année $n$.",
      "On remplace $n$ par $4$ : $u_4 = 50 - 3 \\times 4$.",
      "$= 50 - 12 = 38$.",
      "Il récolte $38$ gousses la 4ᵉ année."
    ),
    tags: ["premiere", "maths", "suites", "termes", "short"],
  },
  {
    kind: "fixed",
    id: "premiere_suites_termes_fixed_9",
    niveau: "premiere-spe",
    matiere: "maths",
    notionId: "suites",
    microId: "suite_termes",
    difficulty: 4,
    theme: "neutral",
    text: "La suite est définie par $u_n = n^2$. Quelle est l'expression de $u_{n+1}$ ?",
    format: "qcm",
    choices: ["$(n+1)^2$", "$n^2 + 1$", "$u_n + 1$", "$2n$"],
    expected: ["$(n+1)^2$"],
    comparator: "mcq_exact",
    hint: "On remplace $n$ par $n+1$ dans TOUTE l'expression.",
    explanation: exp(
      "Pour obtenir $u_{n+1}$, on remplace $n$ par $n+1$ dans l'expression de $u_n$.",
      "$u_n = n^2$ devient donc $u_{n+1} = (n+1)^2$.",
      "Attention : $(n+1)^2 = n^2 + 2n + 1$, ce n'est pas $n^2 + 1$.",
      "$u_{n+1} = (n+1)^2$."
    ),
    tags: ["premiere", "maths", "suites", "termes", "qcm"],
  },
  {
    kind: "fixed",
    id: "premiere_suites_termes_fixed_10",
    niveau: "premiere-spe",
    matiere: "maths",
    notionId: "suites",
    microId: "suite_termes",
    difficulty: 5,
    theme: "neutral",
    text: "La suite est définie par $u_0 = 2$ et $u_{n+1} = 2u_n - 3$. Combien vaut $u_3$ ?",
    format: "short",
    expected: ["-5"],
    comparator: "number_equal",
    hint: "Trois calculs de suite : $u_1$, puis $u_2$, puis $u_3$. Les termes deviennent négatifs.",
    explanation: exp(
      "On applique la relation de récurrence trois fois de suite.",
      "$u_1 = 2 \\times 2 - 3 = 1$, puis $u_2 = 2 \\times 1 - 3 = -1$.",
      "$u_3 = 2 \\times (-1) - 3 = -2 - 3 = -5$.",
      "$u_3 = -5$."
    ),
    tags: ["premiere", "maths", "suites", "termes", "recurrence", "short"],
  },
  {
    kind: "fixed",
    id: "premiere_suites_termes_fixed_11",
    niveau: "premiere-spe",
    matiere: "maths",
    notionId: "suites",
    microId: "suite_termes",
    difficulty: 3,
    theme: "neutral",
    text: "Parmi ces définitions, laquelle définit la suite PAR RÉCURRENCE ?",
    format: "qcm",
    choices: [
      "$u_0 = 1$ et $u_{n+1} = u_n + 3$",
      "$u_n = 3n + 1$",
      "$u_n = n^2 - 5$",
      "$u_n = \\dfrac{1}{n}$",
    ],
    expected: ["$u_0 = 1$ et $u_{n+1} = u_n + 3$"],
    comparator: "mcq_exact",
    hint: "Récurrence : le terme suivant se calcule à partir du précédent.",
    explanation: exp(
      "Une définition explicite donne $u_n$ directement en fonction de $n$ ; une définition par récurrence donne $u_{n+1}$ à partir de $u_n$.",
      "Les trois dernières propositions donnent $u_n$ en fonction de $n$ : elles sont explicites.",
      "Seule $u_{n+1} = u_n + 3$ utilise le terme précédent, avec un premier terme pour démarrer.",
      "C'est $u_0 = 1$ et $u_{n+1} = u_n + 3$."
    ),
    tags: ["premiere", "maths", "suites", "termes", "recurrence", "qcm"],
  },
  {
    kind: "template",
    id: "premiere_suites_termes_tpl_1",
    niveau: "premiere-spe",
    matiere: "maths",
    notionId: "suites",
    microId: "suite_termes",
    difficulty: 2,
    theme: "neutral",
    hint: "Remplace $n$ par la valeur demandée.",
    tags: ["premiere", "maths", "suites", "termes", "template"],
    generate: () => {
      const a = randomInt(2, 6);
      const b = randomInt(1, 9);
      const k = randomInt(2, 6);
      const val = a * k + b;
      return {
        text: `La suite est définie par $u_n = ${a}n + ${b}$. Combien vaut $u_${k}$ ?`,
        format: "short",
        expected: [String(val)],
        comparator: "number_equal",
        explanation: exp(
          "On remplace $n$ par la valeur demandée.",
          `$u_${k} = ${a} \\times ${k} + ${b}$.`,
          `$= ${a * k} + ${b} = ${val}$.`,
          `$u_${k} = ${val}$.`
        ),
      };
    },
  },
  {
    kind: "template",
    id: "premiere_suites_termes_tpl_2",
    niveau: "premiere-spe",
    matiere: "maths",
    notionId: "suites",
    microId: "suite_termes",
    difficulty: 4,
    theme: "neutral",
    hint: "Calcule de proche en proche depuis $u_0$.",
    tags: ["premiere", "maths", "suites", "termes", "recurrence", "template"],
    generate: () => {
      const u0 = randomInt(1, 4);
      const a = randomInt(2, 3);
      const b = randomInt(1, 5);
      const u1 = a * u0 + b;
      const u2 = a * u1 + b;
      return {
        text: `La suite est définie par $u_0 = ${u0}$ et $u_{n+1} = ${a}u_n + ${b}$. Combien vaut $u_2$ ?`,
        format: "short",
        expected: [String(u2)],
        comparator: "number_equal",
        explanation: exp(
          "On applique la relation de récurrence terme après terme.",
          `$u_1 = ${a} \\times ${u0} + ${b} = ${u1}$, puis $u_2 = ${a} \\times ${u1} + ${b}$.`,
          `$u_2 = ${u2}$.`,
          `$u_2 = ${u2}$.`
        ),
      };
    },
  },

  /* ===================== SUITE_ARITHMETIQUE ===================== */
  {
    kind: "fixed",
    id: "premiere_suites_arith_fixed_1",
    niveau: "premiere-spe",
    matiere: "maths",
    notionId: "suites",
    microId: "suite_arithmetique",
    difficulty: 2,
    theme: "neutral",
    text: "Une suite arithmétique de premier terme $u_0$ et de raison $r$ a pour terme général :",
    format: "qcm",
    choices: ["$u_n = u_0 + nr$", "$u_n = u_0 \\times r^n$", "$u_n = u_0 + r^n$", "$u_n = n r$"],
    expected: ["$u_n = u_0 + nr$"],
    comparator: "mcq_exact",
    hint: "On ajoute $r$ à chaque étape.",
    explanation: exp(
      "Dans une suite arithmétique on ajoute la raison $r$ à chaque terme.",
      "Au bout de $n$ étapes depuis $u_0$, on a ajouté $n$ fois $r$.",
      "$u_n = u_0 + nr$.",
      "$u_n = u_0 + nr$."
    ),
    tags: ["premiere", "maths", "suites", "arithmetique", "qcm"],
  },
  {
    kind: "fixed",
    id: "premiere_suites_arith_fixed_2",
    niveau: "premiere-spe",
    matiere: "maths",
    notionId: "suites",
    microId: "suite_arithmetique",
    difficulty: 3,
    theme: "sport",
    text: "Un coureur parcourt $3$ km le 1er jour puis $2$ km de plus chaque jour. La suite des distances est arithmétique : quelle est sa raison ?",
    format: "short",
    expected: ["2"],
    comparator: "number_equal",
    hint: "La raison est ce qu'on ajoute à chaque étape.",
    explanation: exp(
      "La raison d'une suite arithmétique est l'écart constant entre deux termes.",
      "Ici on ajoute $2$ km chaque jour.",
      "Donc $r = 2$.",
      "La raison est $r = 2$."
    ),
    tags: ["premiere", "maths", "suites", "arithmetique", "short"],
  },
  {
    kind: "fixed",
    id: "premiere_suites_arith_fixed_3",
    niveau: "premiere-spe",
    matiere: "maths",
    notionId: "suites",
    microId: "suite_arithmetique",
    difficulty: 3,
    theme: "neutral",
    text: "Une suite arithmétique vérifie $u_0 = 4$ et $r = 3$. Combien vaut $u_5$ ?",
    format: "short",
    expected: ["19"],
    comparator: "number_equal",
    hint: "$u_n = u_0 + nr$.",
    explanation: exp(
      "On utilise $u_n = u_0 + nr$.",
      "$u_5 = 4 + 5 \\times 3$.",
      "$= 4 + 15 = 19$.",
      "$u_5 = 19$."
    ),
    tags: ["premiere", "maths", "suites", "arithmetique", "short"],
  },
  {
    kind: "fixed",
    id: "premiere_suites_arith_fixed_4",
    niveau: "premiere-spe",
    matiere: "maths",
    notionId: "suites",
    microId: "suite_arithmetique",
    difficulty: 4,
    theme: "neutral",
    text: "Une suite arithmétique vérifie $u_2 = 7$ et $u_5 = 19$. Quelle est sa raison ?",
    format: "short",
    expected: ["4"],
    comparator: "number_equal",
    hint: "$u_5 - u_2 = (5 - 2)r$.",
    explanation: exp(
      "L'écart entre deux termes vaut le nombre d'étapes fois la raison.",
      "$u_5 - u_2 = (5 - 2) r$, soit $19 - 7 = 3r$.",
      "$12 = 3r$ donc $r = 4$.",
      "La raison est $r = 4$."
    ),
    tags: ["premiere", "maths", "suites", "arithmetique", "short"],
  },
  {
    kind: "fixed",
    id: "premiere_suites_arith_fixed_5",
    niveau: "premiere-spe",
    matiere: "maths",
    notionId: "suites",
    microId: "suite_arithmetique",
    difficulty: 4,
    theme: "neutral",
    text: "Une suite arithmétique vérifie $u_1 = 5$ et $r = -3$. Combien vaut $u_7$ ?",
    format: "short",
    expected: ["-13"],
    comparator: "number_equal",
    hint: "Le premier terme est $u_1$, pas $u_0$ : de $u_1$ à $u_7$ il y a $6$ étapes.",
    explanation: exp(
      "Quand la suite démarre à $u_1$, la formule devient $u_n = u_1 + (n - 1)r$.",
      "De $u_1$ à $u_7$, on ajoute $6$ fois la raison : $u_7 = 5 + 6 \\times (-3)$.",
      "$= 5 - 18 = -13$.",
      "$u_7 = -13$."
    ),
    tags: ["premiere", "maths", "suites", "arithmetique", "short"],
  },
  {
    kind: "fixed",
    id: "premiere_suites_arith_fixed_6",
    niveau: "premiere-spe",
    matiere: "maths",
    notionId: "suites",
    microId: "suite_arithmetique",
    difficulty: 3,
    theme: "neutral",
    text: "Parmi ces suites, laquelle est arithmétique ?",
    format: "qcm",
    choices: ["$u_n = 4n - 7$", "$u_n = 2^n$", "$u_n = n^2$", "$u_n = \\dfrac{3}{n}$"],
    expected: ["$u_n = 4n - 7$"],
    comparator: "mcq_exact",
    hint: "Arithmétique = on AJOUTE toujours le même nombre.",
    explanation: exp(
      "Une suite est arithmétique si la différence $u_{n+1} - u_n$ est constante.",
      "Pour $u_n = 4n - 7$ : $u_{n+1} - u_n = 4(n+1) - 7 - (4n - 7) = 4$.",
      "$2^n$ est géométrique, $n^2$ et $\\dfrac{3}{n}$ n'ont pas d'écart constant.",
      "$u_n = 4n - 7$ est arithmétique de raison $4$."
    ),
    tags: ["premiere", "maths", "suites", "arithmetique", "qcm"],
  },
  {
    kind: "fixed",
    id: "premiere_suites_arith_fixed_7",
    niveau: "premiere-spe",
    matiere: "maths",
    notionId: "suites",
    microId: "suite_arithmetique",
    difficulty: 4,
    theme: "sport",
    text: "Un coureur prépare un trail : $12$ km la première semaine, puis $4$ km de plus chaque semaine. Combien de kilomètres court-il la 6ᵉ semaine ?",
    format: "short",
    expected: ["32"],
    comparator: "number_equal",
    hint: "De la 1ʳᵉ à la 6ᵉ semaine, il y a $5$ augmentations, pas $6$.",
    explanation: exp(
      "Les distances forment une suite arithmétique de premier terme $12$ et de raison $4$.",
      "De la semaine $1$ à la semaine $6$, la raison s'ajoute $5$ fois : $12 + 5 \\times 4$.",
      "$= 12 + 20 = 32$.",
      "Il court $32$ km la 6ᵉ semaine."
    ),
    tags: ["premiere", "maths", "suites", "arithmetique", "short"],
  },
  {
    kind: "fixed",
    id: "premiere_suites_arith_fixed_8",
    niveau: "premiere-spe",
    matiere: "maths",
    notionId: "suites",
    microId: "suite_arithmetique",
    difficulty: 4,
    theme: "neutral",
    text: "Une suite arithmétique de raison $r = 3$ vérifie $u_4 = 20$. Combien vaut $u_0$ ?",
    format: "short",
    expected: ["8"],
    comparator: "number_equal",
    hint: "Pour remonter de $u_4$ à $u_0$, on RETIRE la raison.",
    explanation: exp(
      "On utilise $u_4 = u_0 + 4r$.",
      "Donc $20 = u_0 + 4 \\times 3$, soit $20 = u_0 + 12$.",
      "$u_0 = 20 - 12 = 8$.",
      "$u_0 = 8$."
    ),
    tags: ["premiere", "maths", "suites", "arithmetique", "short"],
  },
  {
    kind: "fixed",
    id: "premiere_suites_arith_fixed_9",
    niveau: "premiere-spe",
    matiere: "maths",
    notionId: "suites",
    microId: "suite_arithmetique",
    difficulty: 5,
    theme: "neutral",
    text: "Une suite arithmétique vérifie $u_0 = 7$ et $r = 5$. Pour quel rang $n$ a-t-on $u_n = 52$ ?",
    format: "short",
    expected: ["9"],
    comparator: "number_equal",
    hint: "Écris $7 + 5n = 52$ et résous.",
    explanation: exp(
      "Le terme général est $u_n = u_0 + nr = 7 + 5n$.",
      "On cherche $n$ tel que $7 + 5n = 52$, soit $5n = 45$.",
      "$n = \\dfrac{45}{5} = 9$.",
      "C'est au rang $n = 9$."
    ),
    tags: ["premiere", "maths", "suites", "arithmetique", "short"],
  },
  {
    kind: "fixed",
    id: "premiere_suites_arith_fixed_10",
    niveau: "premiere-spe",
    matiere: "maths",
    notionId: "suites",
    microId: "suite_arithmetique",
    difficulty: 2,
    theme: "neutral",
    text: "Une suite arithmétique est constante lorsque :",
    format: "qcm",
    choices: [
      "sa raison vaut $0$",
      "son premier terme vaut $0$",
      "sa raison vaut $1$",
      "son premier terme vaut $1$",
    ],
    expected: ["sa raison vaut $0$"],
    comparator: "mcq_exact",
    hint: "Que se passe-t-il si on n'ajoute rien à chaque étape ?",
    explanation: exp(
      "Dans une suite arithmétique, on ajoute la raison $r$ à chaque étape.",
      "Si $r = 0$, on n'ajoute rien : tous les termes sont égaux à $u_0$.",
      "Le premier terme, lui, ne change rien au fait que la suite bouge ou non.",
      "La suite est constante lorsque $r = 0$."
    ),
    tags: ["premiere", "maths", "suites", "arithmetique", "qcm"],
  },
  {
    kind: "fixed",
    id: "premiere_suites_arith_fixed_11",
    niveau: "premiere-spe",
    matiere: "maths",
    notionId: "suites",
    microId: "suite_arithmetique",
    difficulty: 5,
    theme: "neutral",
    text: "On donne $u_n = 5n + 2$. Combien vaut la différence $u_{n+1} - u_n$ ?",
    format: "short",
    expected: ["5"],
    comparator: "number_equal",
    hint: "Calcule d'abord $u_{n+1} = 5(n+1) + 2$, puis soustrais.",
    explanation: exp(
      "Pour prouver qu'une suite est arithmétique, on calcule $u_{n+1} - u_n$.",
      "$u_{n+1} = 5(n+1) + 2 = 5n + 5 + 2 = 5n + 7$.",
      "$u_{n+1} - u_n = (5n + 7) - (5n + 2) = 5$.",
      "La différence vaut $5$ : la suite est arithmétique de raison $5$."
    ),
    tags: ["premiere", "maths", "suites", "arithmetique", "short"],
  },
  {
    kind: "template",
    id: "premiere_suites_arith_tpl_1",
    niveau: "premiere-spe",
    matiere: "maths",
    notionId: "suites",
    microId: "suite_arithmetique",
    difficulty: 3,
    theme: "neutral",
    hint: "$u_n = u_0 + nr$.",
    tags: ["premiere", "maths", "suites", "arithmetique", "template"],
    generate: () => {
      const u0 = randomInt(1, 8);
      const r = randomInt(2, 7);
      const n = randomInt(4, 9);
      const un = u0 + n * r;
      return {
        text: `Une suite arithmétique vérifie $u_0 = ${u0}$ et $r = ${r}$. Combien vaut $u_${n}$ ?`,
        format: "short",
        expected: [String(un)],
        comparator: "number_equal",
        explanation: exp(
          "On applique $u_n = u_0 + nr$.",
          `$u_${n} = ${u0} + ${n} \\times ${r}$.`,
          `$= ${u0} + ${n * r} = ${un}$.`,
          `$u_${n} = ${un}$.`
        ),
      };
    },
  },
  {
    kind: "template",
    id: "premiere_suites_arith_tpl_2",
    niveau: "premiere-spe",
    matiere: "maths",
    notionId: "suites",
    microId: "suite_arithmetique",
    difficulty: 4,
    theme: "neutral",
    hint: "La raison se déduit de l'écart entre deux termes connus.",
    tags: ["premiere", "maths", "suites", "arithmetique", "template"],
    generate: () => {
      const r = randomInt(2, 6);
      const u0 = randomInt(1, 5);
      const p = randomInt(2, 4);
      const q = p + randomInt(2, 4);
      const up = u0 + p * r;
      const uq = u0 + q * r;
      return {
        text: `Une suite arithmétique vérifie $u_${p} = ${up}$ et $u_${q} = ${uq}$. Quelle est sa raison ?`,
        format: "short",
        expected: [String(r)],
        comparator: "number_equal",
        explanation: exp(
          "L'écart entre deux termes vaut (nombre d'étapes) × raison.",
          `$u_${q} - u_${p} = (${q} - ${p}) r$, soit $${uq} - ${up} = ${q - p}r$.`,
          `$${uq - up} = ${q - p}r$ donc $r = ${r}$.`,
          `La raison est $r = ${r}$.`
        ),
      };
    },
  },

  /* ===================== SUITE_GEOMETRIQUE ===================== */
  {
    kind: "fixed",
    id: "premiere_suites_geo_fixed_1",
    niveau: "premiere-spe",
    matiere: "maths",
    notionId: "suites",
    microId: "suite_geometrique",
    difficulty: 2,
    theme: "neutral",
    text: "Une suite géométrique de premier terme $u_0$ et de raison $q$ a pour terme général :",
    format: "qcm",
    choices: ["$u_n = u_0 \\times q^n$", "$u_n = u_0 + nq$", "$u_n = u_0 + q^n$", "$u_n = q^{u_0}$"],
    expected: ["$u_n = u_0 \\times q^n$"],
    comparator: "mcq_exact",
    hint: "On multiplie par $q$ à chaque étape.",
    explanation: exp(
      "Dans une suite géométrique on multiplie par la raison $q$ à chaque terme.",
      "Au bout de $n$ étapes depuis $u_0$, on a multiplié $n$ fois par $q$.",
      "$u_n = u_0 \\times q^n$.",
      "$u_n = u_0 \\times q^n$."
    ),
    tags: ["premiere", "maths", "suites", "geometrique", "qcm"],
  },
  {
    kind: "fixed",
    id: "premiere_suites_geo_fixed_2",
    niveau: "premiere-spe",
    matiere: "maths",
    notionId: "suites",
    microId: "suite_geometrique",
    difficulty: 3,
    theme: "neutral",
    text: "Un capital de $1000$ € augmente de $5\\%$ par an. Quelle est la raison de la suite géométrique des capitaux ?",
    format: "qcm",
    choices: ["$1{,}05$", "$0{,}05$", "$5$", "$1{,}5$"],
    expected: ["$1{,}05$"],
    comparator: "mcq_exact",
    hint: "Augmenter de $5\\%$, c'est multiplier par $1 + \\dfrac{5}{100}$.",
    explanation: exp(
      "Augmenter de $t\\%$ revient à multiplier par le coefficient $1 + \\dfrac{t}{100}$.",
      "Ici $t = 5$, donc le coefficient est $1 + 0{,}05$.",
      "$= 1{,}05$.",
      "La raison est $q = 1{,}05$."
    ),
    tags: ["premiere", "maths", "suites", "geometrique", "qcm"],
  },
  {
    kind: "fixed",
    id: "premiere_suites_geo_fixed_3",
    niveau: "premiere-spe",
    matiere: "maths",
    notionId: "suites",
    microId: "suite_geometrique",
    difficulty: 3,
    theme: "neutral",
    text: "Une suite géométrique vérifie $u_0 = 2$ et $q = 3$. Combien vaut $u_3$ ?",
    format: "short",
    expected: ["54"],
    comparator: "number_equal",
    hint: "$u_n = u_0 \\times q^n$.",
    explanation: exp(
      "On utilise $u_n = u_0 \\times q^n$.",
      "$u_3 = 2 \\times 3^3 = 2 \\times 27$.",
      "$= 54$.",
      "$u_3 = 54$."
    ),
    tags: ["premiere", "maths", "suites", "geometrique", "short"],
  },
  {
    kind: "fixed",
    id: "premiere_suites_geo_fixed_4",
    niveau: "premiere-spe",
    matiere: "maths",
    notionId: "suites",
    microId: "suite_geometrique",
    difficulty: 3,
    theme: "neutral",
    text: "Une suite géométrique vérifie $u_0 = 5$ et $q = 2$. Combien vaut $u_4$ ?",
    format: "short",
    expected: ["80"],
    comparator: "number_equal",
    hint: "$u_4 = 5 \\times 2^4$.",
    explanation: exp(
      "On applique $u_n = u_0 \\times q^n$.",
      "$u_4 = 5 \\times 2^4 = 5 \\times 16$.",
      "$= 80$.",
      "$u_4 = 80$."
    ),
    tags: ["premiere", "maths", "suites", "geometrique", "short"],
  },
  {
    kind: "fixed",
    id: "premiere_suites_geo_fixed_5",
    niveau: "premiere-spe",
    matiere: "maths",
    notionId: "suites",
    microId: "suite_geometrique",
    difficulty: 3,
    theme: "neutral",
    text: "Une population diminue de $20\\%$ chaque année. Quelle est la raison de la suite géométrique correspondante ?",
    format: "qcm",
    choices: ["$0{,}8$", "$-0{,}2$", "$0{,}2$", "$1{,}2$"],
    expected: ["$0{,}8$"],
    comparator: "mcq_exact",
    hint: "Diminuer de $20\\%$, c'est garder $80\\%$.",
    explanation: exp(
      "Diminuer de $t\\%$ revient à multiplier par $1 - \\dfrac{t}{100}$.",
      "Ici $t = 20$, donc le coefficient est $1 - 0{,}2$.",
      "$= 0{,}8$. Une raison négative ferait changer le signe des termes, ce qui n'a pas de sens pour une population.",
      "La raison est $q = 0{,}8$."
    ),
    tags: ["premiere", "maths", "suites", "geometrique", "qcm"],
  },
  {
    kind: "fixed",
    id: "premiere_suites_geo_fixed_6",
    niveau: "premiere-spe",
    matiere: "maths",
    notionId: "suites",
    microId: "suite_geometrique",
    difficulty: 3,
    theme: "neutral",
    text: "Une suite géométrique vérifie $u_2 = 12$ et $u_3 = 36$. Quelle est sa raison $q$ ?",
    format: "short",
    expected: ["3"],
    comparator: "number_equal",
    hint: "La raison est le QUOTIENT de deux termes consécutifs.",
    explanation: exp(
      "Dans une suite géométrique, $u_{n+1} = q \\times u_n$.",
      "Donc $q = \\dfrac{u_3}{u_2} = \\dfrac{36}{12}$.",
      "$= 3$.",
      "La raison est $q = 3$."
    ),
    tags: ["premiere", "maths", "suites", "geometrique", "short"],
  },
  {
    kind: "fixed",
    id: "premiere_suites_geo_fixed_7",
    niveau: "premiere-spe",
    matiere: "maths",
    notionId: "suites",
    microId: "suite_geometrique",
    difficulty: 4,
    theme: "neutral",
    text: "Une suite géométrique vérifie $u_0 = 1000$ et $q = 0{,}5$. Combien vaut $u_3$ ?",
    format: "short",
    expected: ["125"],
    comparator: "number_equal",
    hint: "Multiplier par $0{,}5$, c'est diviser par $2$ : trois fois de suite.",
    explanation: exp(
      "On applique $u_n = u_0 \\times q^n$.",
      "$u_3 = 1000 \\times 0{,}5^3 = 1000 \\times 0{,}125$.",
      "$= 125$. Autrement dit, on divise $1000$ par $2$ trois fois : $500$, $250$, $125$.",
      "$u_3 = 125$."
    ),
    tags: ["premiere", "maths", "suites", "geometrique", "short"],
  },
  {
    kind: "fixed",
    id: "premiere_suites_geo_fixed_8",
    niveau: "premiere-spe",
    matiere: "maths",
    notionId: "suites",
    microId: "suite_geometrique",
    difficulty: 3,
    theme: "neutral",
    text: "Parmi ces suites, laquelle est géométrique ?",
    format: "qcm",
    choices: ["$u_n = 3 \\times 2^n$", "$u_n = 2n + 3$", "$u_n = n^2$", "$u_n = \\dfrac{n}{2}$"],
    expected: ["$u_n = 3 \\times 2^n$"],
    comparator: "mcq_exact",
    hint: "Géométrique = on MULTIPLIE toujours par le même nombre.",
    explanation: exp(
      "Une suite est géométrique si le quotient $\\dfrac{u_{n+1}}{u_n}$ est constant.",
      "Pour $u_n = 3 \\times 2^n$ : $\\dfrac{u_{n+1}}{u_n} = \\dfrac{3 \\times 2^{n+1}}{3 \\times 2^n} = 2$.",
      "$2n + 3$ et $\\dfrac{n}{2}$ sont arithmétiques, $n^2$ n'est ni l'un ni l'autre.",
      "$u_n = 3 \\times 2^n$ est géométrique de raison $2$."
    ),
    tags: ["premiere", "maths", "suites", "geometrique", "qcm"],
  },
  {
    kind: "fixed",
    id: "premiere_suites_geo_fixed_9",
    niveau: "premiere-spe",
    matiere: "maths",
    notionId: "suites",
    microId: "suite_geometrique",
    difficulty: 4,
    theme: "reunion",
    text: "Une colonie de $200$ tortues marines augmente de $10\\%$ par an. Combien d'individus dans $2$ ans ?",
    format: "short",
    expected: ["242"],
    comparator: "number_equal",
    hint: "Multiplie par $1{,}1$, puis encore par $1{,}1$.",
    explanation: exp(
      "Augmenter de $10\\%$ revient à multiplier par $1{,}1$ : la suite est géométrique.",
      "$u_2 = 200 \\times 1{,}1^2 = 200 \\times 1{,}21$.",
      "$= 242$. (Attention : ce n'est pas $200 + 20 + 20$, la 2ᵉ hausse porte sur $220$.)",
      "Il y aura $242$ tortues."
    ),
    tags: ["premiere", "maths", "suites", "geometrique", "short"],
  },
  {
    kind: "fixed",
    id: "premiere_suites_geo_fixed_10",
    niveau: "premiere-spe",
    matiere: "maths",
    notionId: "suites",
    microId: "suite_geometrique",
    difficulty: 5,
    theme: "neutral",
    text: "Une suite géométrique de raison $q = 3$ vérifie $u_2 = 18$. Combien vaut $u_5$ ?",
    format: "short",
    expected: ["486"],
    comparator: "number_equal",
    hint: "De $u_2$ à $u_5$, on multiplie $3$ fois par la raison.",
    explanation: exp(
      "Entre deux rangs, on utilise $u_n = u_p \\times q^{n-p}$.",
      "De $u_2$ à $u_5$ il y a $3$ étapes : $u_5 = 18 \\times 3^3$.",
      "$= 18 \\times 27 = 486$.",
      "$u_5 = 486$."
    ),
    tags: ["premiere", "maths", "suites", "geometrique", "short"],
  },
  {
    kind: "fixed",
    id: "premiere_suites_geo_fixed_11",
    niveau: "premiere-spe",
    matiere: "maths",
    notionId: "suites",
    microId: "suite_geometrique",
    difficulty: 5,
    theme: "neutral",
    text: "Une suite géométrique vérifie $u_0 = 1$ et $q = -2$. Combien vaut $u_3$ ?",
    format: "short",
    expected: ["-8"],
    comparator: "number_equal",
    hint: "$(-2)^3$ : un exposant impair garde le signe moins.",
    explanation: exp(
      "La raison peut être négative : les termes changent alors de signe à chaque étape.",
      "$u_3 = 1 \\times (-2)^3 = (-2) \\times (-2) \\times (-2)$.",
      "$= 4 \\times (-2) = -8$.",
      "$u_3 = -8$."
    ),
    tags: ["premiere", "maths", "suites", "geometrique", "short"],
  },
  {
    kind: "template",
    id: "premiere_suites_geo_tpl_1",
    niveau: "premiere-spe",
    matiere: "maths",
    notionId: "suites",
    microId: "suite_geometrique",
    difficulty: 3,
    theme: "neutral",
    hint: "$u_n = u_0 \\times q^n$.",
    tags: ["premiere", "maths", "suites", "geometrique", "template"],
    generate: () => {
      const u0 = randomInt(2, 5);
      const q = randomInt(2, 4);
      const n = randomInt(2, 4);
      const un = u0 * q ** n;
      return {
        text: `Une suite géométrique vérifie $u_0 = ${u0}$ et $q = ${q}$. Combien vaut $u_${n}$ ?`,
        format: "short",
        expected: [String(un)],
        comparator: "number_equal",
        explanation: exp(
          "On applique $u_n = u_0 \\times q^n$.",
          `$u_${n} = ${u0} \\times ${q}^${n} = ${u0} \\times ${q ** n}$.`,
          `$= ${un}$.`,
          `$u_${n} = ${un}$.`
        ),
      };
    },
  },
  {
    kind: "template",
    id: "premiere_suites_geo_tpl_2",
    niveau: "premiere-spe",
    matiere: "maths",
    notionId: "suites",
    microId: "suite_geometrique",
    difficulty: 4,
    theme: "neutral",
    hint: "Le rapport de deux termes consécutifs donne la raison.",
    tags: ["premiere", "maths", "suites", "geometrique", "template"],
    generate: () => {
      const u0 = randomInt(2, 4);
      const q = randomInt(2, 4);
      const u1 = u0 * q;
      const u2 = u1 * q;
      return {
        text: `Une suite géométrique vérifie $u_0 = ${u0}$, $u_1 = ${u1}$, $u_2 = ${u2}$. Quelle est sa raison $q$ ?`,
        format: "short",
        expected: [String(q)],
        comparator: "number_equal",
        explanation: exp(
          "La raison est le rapport de deux termes consécutifs.",
          `$q = \\dfrac{u_1}{u_0} = \\dfrac{${u1}}{${u0}}$.`,
          `$= ${q}$.`,
          `La raison est $q = ${q}$.`
        ),
      };
    },
  },

  /* ===================== SUITE_VARIATION ===================== */
  {
    kind: "fixed",
    id: "premiere_suites_var_fixed_1",
    niveau: "premiere-spe",
    matiere: "maths",
    notionId: "suites",
    microId: "suite_variation",
    difficulty: 2,
    theme: "neutral",
    text: "Une suite arithmétique de raison $r = -2$ est :",
    format: "qcm",
    choices: ["décroissante", "croissante", "constante", "ni l'un ni l'autre"],
    expected: ["décroissante"],
    comparator: "mcq_exact",
    hint: "Signe de la raison.",
    explanation: exp(
      "Pour une suite arithmétique, le sens de variation dépend du signe de $r$.",
      "Ici $r = -2 < 0$.",
      "Quand $r < 0$, la suite est décroissante.",
      "La suite est décroissante."
    ),
    tags: ["premiere", "maths", "suites", "variation", "qcm"],
  },
  {
    kind: "fixed",
    id: "premiere_suites_var_fixed_2",
    niveau: "premiere-spe",
    matiere: "maths",
    notionId: "suites",
    microId: "suite_variation",
    difficulty: 3,
    theme: "neutral",
    text: "Une suite géométrique de premier terme positif et de raison $q = 1{,}2$ est :",
    format: "qcm",
    choices: ["croissante", "décroissante", "constante", "alternée"],
    expected: ["croissante"],
    comparator: "mcq_exact",
    hint: "$q > 1$ avec un terme initial positif.",
    explanation: exp(
      "Pour une suite géométrique à termes positifs, le sens dépend de $q$ par rapport à $1$.",
      "Ici $q = 1{,}2 > 1$.",
      "Quand $q > 1$ (termes positifs), la suite est croissante.",
      "La suite est croissante."
    ),
    tags: ["premiere", "maths", "suites", "variation", "qcm"],
  },
  {
    kind: "fixed",
    id: "premiere_suites_var_fixed_3",
    niveau: "premiere-spe",
    matiere: "maths",
    notionId: "suites",
    microId: "suite_variation",
    difficulty: 4,
    theme: "neutral",
    text: "Pour étudier le sens de variation d'une suite, on calcule en général :",
    format: "qcm",
    choices: [
      "le signe de $u_{n+1} - u_n$",
      "la valeur de $u_0$ seulement",
      "la somme des termes",
      "le produit $u_n \\times u_{n+1}$",
    ],
    expected: ["le signe de $u_{n+1} - u_n$"],
    comparator: "mcq_exact",
    hint: "On compare deux termes consécutifs.",
    explanation: exp(
      "Une suite est croissante si $u_{n+1} - u_n \\ge 0$ pour tout $n$, décroissante si $\\le 0$.",
      "On étudie donc le signe de la différence $u_{n+1} - u_n$.",
      "C'est la méthode générale, valable pour toute suite.",
      "On étudie le signe de $u_{n+1} - u_n$."
    ),
    tags: ["premiere", "maths", "suites", "variation", "qcm"],
  },
  {
    kind: "fixed",
    id: "premiere_suites_var_fixed_4",
    niveau: "premiere-spe",
    matiere: "maths",
    notionId: "suites",
    microId: "suite_variation",
    difficulty: 3,
    theme: "neutral",
    text: "La suite définie par $u_n = 3n + 1$ est :",
    format: "qcm",
    choices: ["croissante", "décroissante", "constante", "alternée"],
    expected: ["croissante"],
    comparator: "mcq_exact",
    hint: "Calcule $u_{n+1} - u_n$.",
    explanation: exp(
      "On compare deux termes consécutifs.",
      "$u_{n+1} - u_n = 3(n+1) + 1 - (3n + 1) = 3$.",
      "Cette différence est positive pour tout $n$.",
      "La suite est croissante."
    ),
    tags: ["premiere", "maths", "suites", "variation", "qcm"],
  },
  {
    kind: "fixed",
    id: "premiere_suites_var_fixed_5",
    niveau: "premiere-spe",
    matiere: "maths",
    notionId: "suites",
    microId: "suite_variation",
    difficulty: 3,
    theme: "neutral",
    text: "Une suite géométrique de premier terme $u_0 = 8$ et de raison $q = 0{,}5$ est :",
    format: "qcm",
    choices: ["décroissante", "croissante", "constante", "alternée"],
    expected: ["décroissante"],
    comparator: "mcq_exact",
    hint: "$0 < q < 1$ avec un premier terme positif.",
    explanation: exp(
      "Pour une suite géométrique à termes positifs, tout dépend de la position de $q$ par rapport à $1$.",
      "Ici $q = 0{,}5$, donc $0 < q < 1$ : chaque terme est la moitié du précédent.",
      "Les termes $8$, $4$, $2$, $1$… diminuent.",
      "La suite est décroissante."
    ),
    tags: ["premiere", "maths", "suites", "variation", "qcm"],
  },
  {
    kind: "fixed",
    id: "premiere_suites_var_fixed_6",
    niveau: "premiere-spe",
    matiere: "maths",
    notionId: "suites",
    microId: "suite_variation",
    difficulty: 5,
    theme: "neutral",
    text: "Une suite géométrique de premier terme $u_0 = 1$ et de raison $q = -2$ est :",
    format: "qcm",
    choices: [
      "ni croissante ni décroissante",
      "croissante",
      "décroissante",
      "constante",
    ],
    expected: ["ni croissante ni décroissante"],
    comparator: "mcq_exact",
    hint: "Écris les premiers termes : $1$, $-2$, $4$, $-8$…",
    explanation: exp(
      "Le sens de variation suppose que la suite aille toujours dans le même sens.",
      "Ici les termes valent $1$, $-2$, $4$, $-8$, $16$… : ils changent de signe à chaque étape.",
      "La suite monte, puis descend, puis remonte : elle n'est ni croissante ni décroissante.",
      "Une raison négative interdit tout sens de variation."
    ),
    tags: ["premiere", "maths", "suites", "variation", "qcm"],
  },
  {
    kind: "fixed",
    id: "premiere_suites_var_fixed_7",
    niveau: "premiere-spe",
    matiere: "maths",
    notionId: "suites",
    microId: "suite_variation",
    difficulty: 4,
    theme: "neutral",
    text: "La suite définie par $u_n = \\dfrac{1}{n}$ pour $n \\ge 1$ est :",
    format: "qcm",
    choices: ["décroissante", "croissante", "constante", "alternée"],
    expected: ["décroissante"],
    comparator: "mcq_exact",
    hint: "Compare $\\dfrac{1}{1}$, $\\dfrac{1}{2}$, $\\dfrac{1}{3}$…",
    explanation: exp(
      "Quand le dénominateur grandit et que le numérateur reste fixe, la fraction diminue.",
      "Les termes valent $1$, $\\dfrac{1}{2}$, $\\dfrac{1}{3}$, $\\dfrac{1}{4}$…",
      "Chaque terme est plus petit que le précédent.",
      "La suite est décroissante."
    ),
    tags: ["premiere", "maths", "suites", "variation", "qcm"],
  },
  {
    kind: "fixed",
    id: "premiere_suites_var_fixed_8",
    niveau: "premiere-spe",
    matiere: "maths",
    notionId: "suites",
    microId: "suite_variation",
    difficulty: 4,
    theme: "neutral",
    text: "Pour une suite à termes strictement POSITIFS, on peut aussi étudier les variations en comparant :",
    format: "qcm",
    choices: [
      "$\\dfrac{u_{n+1}}{u_n}$ à $1$",
      "$u_{n+1} \\times u_n$ à $1$",
      "$u_n$ à $0$",
      "$u_0$ à $u_1$ uniquement",
    ],
    expected: ["$\\dfrac{u_{n+1}}{u_n}$ à $1$"],
    comparator: "mcq_exact",
    hint: "C'est la méthode pratique pour les suites géométriques.",
    explanation: exp(
      "Si tous les termes sont strictement positifs, on peut diviser sans changer le sens de l'inégalité.",
      "Si $\\dfrac{u_{n+1}}{u_n} > 1$, alors $u_{n+1} > u_n$ : la suite croît. Si le quotient est $< 1$, elle décroît.",
      "Comparer $u_0$ à $u_1$ ne prouve rien : il faut que ce soit vrai pour TOUT $n$.",
      "On compare $\\dfrac{u_{n+1}}{u_n}$ à $1$."
    ),
    tags: ["premiere", "maths", "suites", "variation", "qcm"],
  },
  {
    kind: "fixed",
    id: "premiere_suites_var_fixed_9",
    niveau: "premiere-spe",
    matiere: "maths",
    notionId: "suites",
    microId: "suite_variation",
    difficulty: 3,
    theme: "neutral",
    text: "La suite définie par $u_n = n^2$ pour $n \\ge 0$ est :",
    format: "qcm",
    choices: ["croissante", "décroissante", "constante", "alternée"],
    expected: ["croissante"],
    comparator: "mcq_exact",
    hint: "Les termes valent $0$, $1$, $4$, $9$…",
    explanation: exp(
      "On compare deux termes consécutifs.",
      "$u_{n+1} - u_n = (n+1)^2 - n^2 = 2n + 1$.",
      "Pour $n \\ge 0$, $2n + 1$ est toujours positif.",
      "La suite est croissante."
    ),
    tags: ["premiere", "maths", "suites", "variation", "qcm"],
  },
  {
    kind: "fixed",
    id: "premiere_suites_var_fixed_10",
    niveau: "premiere-spe",
    matiere: "maths",
    notionId: "suites",
    microId: "suite_variation",
    difficulty: 5,
    theme: "neutral",
    text: "Une suite vérifie $u_{n+1} - u_n = 2n - 6$. À partir de quel rang $n$ la suite devient-elle croissante ?",
    format: "short",
    expected: ["3"],
    comparator: "number_equal",
    hint: "Cherche à partir de quand $2n - 6$ est positif ou nul.",
    explanation: exp(
      "La suite croît là où la différence $u_{n+1} - u_n$ est positive ou nulle.",
      "On résout $2n - 6 \\ge 0$, soit $2n \\ge 6$.",
      "$n \\ge 3$ : avant ce rang la différence est négative, la suite décroît.",
      "La suite est croissante à partir du rang $n = 3$."
    ),
    tags: ["premiere", "maths", "suites", "variation", "short"],
  },
  {
    kind: "fixed",
    id: "premiere_suites_var_fixed_11",
    niveau: "premiere-spe",
    matiere: "maths",
    notionId: "suites",
    microId: "suite_variation",
    difficulty: 2,
    theme: "neutral",
    text: "Une suite géométrique de premier terme $5$ et de raison $q = 1$ est :",
    format: "qcm",
    choices: ["constante", "croissante", "décroissante", "alternée"],
    expected: ["constante"],
    comparator: "mcq_exact",
    hint: "Multiplier par $1$ ne change rien.",
    explanation: exp(
      "Dans une suite géométrique, chaque terme est le précédent multiplié par $q$.",
      "Ici $q = 1$ : $5 \\times 1 = 5$, puis encore $5$…",
      "Tous les termes valent $5$.",
      "La suite est constante."
    ),
    tags: ["premiere", "maths", "suites", "variation", "qcm"],
  },
  {
    kind: "template",
    id: "premiere_suites_var_tpl_1",
    niveau: "premiere-spe",
    matiere: "maths",
    notionId: "suites",
    microId: "suite_variation",
    difficulty: 3,
    theme: "neutral",
    hint: "Signe de la raison.",
    tags: ["premiere", "maths", "suites", "variation", "template"],
    generate: () => {
      const positif = randomInt(0, 1) === 1;
      const r = positif ? randomInt(1, 6) : -randomInt(1, 6);
      const correct = positif ? "croissante" : "décroissante";
      return {
        text: `Une suite arithmétique de raison $r = ${r}$ est :`,
        format: "qcm",
        choices: ["croissante", "décroissante", "constante", "ni l'un ni l'autre"],
        expected: [correct],
        comparator: "mcq_exact",
        explanation: exp(
          "Le sens de variation d'une suite arithmétique dépend du signe de $r$.",
          `Ici $r = ${r}$, qui est ${positif ? "positif" : "négatif"}.`,
          `Donc la suite est ${correct}.`,
          `La suite est ${correct}.`
        ),
      };
    },
  },

  /* ===================== SUITE_SOMMES ===================== */
  {
    kind: "fixed",
    id: "premiere_suites_sommes_fixed_1",
    niveau: "premiere-spe",
    matiere: "maths",
    notionId: "suites",
    microId: "suite_sommes",
    difficulty: 2,
    theme: "neutral",
    text: "Quelle est la formule de $1 + 2 + 3 + \\dots + n$ ?",
    format: "qcm",
    choices: [
      "$\\dfrac{n(n+1)}{2}$",
      "$n^2$",
      "$\\dfrac{n(n-1)}{2}$",
      "$2n$",
    ],
    expected: ["$\\dfrac{n(n+1)}{2}$"],
    comparator: "mcq_exact",
    hint: "Somme des $n$ premiers entiers.",
    explanation: exp(
      "La somme des entiers de $1$ à $n$ est un résultat classique.",
      "On regroupe les termes par paires de somme $n+1$.",
      "$1 + 2 + \\dots + n = \\dfrac{n(n+1)}{2}$.",
      "$1 + 2 + \\dots + n = \\dfrac{n(n+1)}{2}$."
    ),
    tags: ["premiere", "maths", "suites", "sommes", "qcm"],
  },
  {
    kind: "fixed",
    id: "premiere_suites_sommes_fixed_2",
    niveau: "premiere-spe",
    matiere: "maths",
    notionId: "suites",
    microId: "suite_sommes",
    difficulty: 3,
    theme: "neutral",
    text: "Combien vaut $1 + 2 + 3 + \\dots + 100$ ?",
    format: "short",
    expected: ["5050"],
    comparator: "number_equal",
    hint: "Utilise $\\dfrac{n(n+1)}{2}$ avec $n = 100$.",
    explanation: exp(
      "On applique $1 + 2 + \\dots + n = \\dfrac{n(n+1)}{2}$.",
      "Ici $n = 100$ : $\\dfrac{100 \\times 101}{2}$.",
      "$= \\dfrac{10100}{2} = 5050$.",
      "La somme vaut $5050$."
    ),
    tags: ["premiere", "maths", "suites", "sommes", "short"],
  },
  {
    kind: "fixed",
    id: "premiere_suites_sommes_fixed_3",
    niveau: "premiere-spe",
    matiere: "maths",
    notionId: "suites",
    microId: "suite_sommes",
    difficulty: 4,
    theme: "neutral",
    text: "Quelle est la formule de $1 + q + q^2 + \\dots + q^n$ pour $q \\neq 1$ ?",
    format: "qcm",
    choices: [
      "$\\dfrac{1 - q^{n+1}}{1 - q}$",
      "$\\dfrac{1 - q^{n}}{1 - q}$",
      "$\\dfrac{q^{n+1} - 1}{q}$",
      "$q^{n+1}$",
    ],
    expected: ["$\\dfrac{1 - q^{n+1}}{1 - q}$"],
    comparator: "mcq_exact",
    hint: "Somme géométrique : attention à l'exposant $n+1$.",
    explanation: exp(
      "C'est la somme des termes d'une suite géométrique de raison $q$.",
      "Il y a $n+1$ termes (de $q^0$ à $q^n$).",
      "$1 + q + \\dots + q^n = \\dfrac{1 - q^{n+1}}{1 - q}$.",
      "$\\dfrac{1 - q^{n+1}}{1 - q}$."
    ),
    tags: ["premiere", "maths", "suites", "sommes", "qcm"],
  },
  {
    kind: "fixed",
    id: "premiere_suites_sommes_fixed_4",
    niveau: "premiere-spe",
    matiere: "maths",
    notionId: "suites",
    microId: "suite_sommes",
    difficulty: 3,
    theme: "neutral",
    text: "Combien vaut $1 + 2 + 3 + \\dots + 50$ ?",
    format: "short",
    expected: ["1275"],
    comparator: "number_equal",
    hint: "$\\dfrac{n(n+1)}{2}$ avec $n = 50$.",
    explanation: exp(
      "On applique la formule des $n$ premiers entiers.",
      "$\\dfrac{50 \\times 51}{2}$.",
      "$= \\dfrac{2550}{2} = 1275$.",
      "La somme vaut $1275$."
    ),
    tags: ["premiere", "maths", "suites", "sommes", "short"],
  },
  {
    kind: "fixed",
    id: "premiere_suites_sommes_fixed_5",
    niveau: "premiere-spe",
    matiere: "maths",
    notionId: "suites",
    microId: "suite_sommes",
    difficulty: 5,
    theme: "neutral",
    text: "Une suite arithmétique vérifie $u_0 = 2$ et $r = 3$. Combien vaut $u_0 + u_1 + \\dots + u_9$ ?",
    format: "short",
    expected: ["155"],
    comparator: "number_equal",
    hint: "$10$ termes ; le dernier est $u_9 = 2 + 9 \\times 3$.",
    explanation: exp(
      "Pour une suite arithmétique : somme $=$ (nombre de termes) $\\times \\dfrac{\\text{premier} + \\text{dernier}}{2}$.",
      "Il y a $10$ termes (de $u_0$ à $u_9$) et $u_9 = 2 + 27 = 29$.",
      "$S = 10 \\times \\dfrac{2 + 29}{2} = 10 \\times 15{,}5 = 155$.",
      "La somme vaut $155$."
    ),
    tags: ["premiere", "maths", "suites", "sommes", "short"],
  },
  {
    kind: "fixed",
    id: "premiere_suites_sommes_fixed_6",
    niveau: "premiere-spe",
    matiere: "maths",
    notionId: "suites",
    microId: "suite_sommes",
    difficulty: 5,
    theme: "neutral",
    text: "Combien vaut $1 + 2 + 4 + 8 + \\dots + 2^{10}$ ?",
    format: "short",
    expected: ["2047"],
    comparator: "number_equal",
    hint: "Somme géométrique de raison $2$ : $\\dfrac{1 - 2^{11}}{1 - 2}$.",
    explanation: exp(
      "C'est une somme géométrique de raison $q = 2$, de $2^0$ à $2^{10}$.",
      "$S = \\dfrac{1 - 2^{11}}{1 - 2} = \\dfrac{1 - 2048}{-1}$.",
      "$= 2047$. (Retenir : la somme vaut le terme suivant moins $1$.)",
      "La somme vaut $2047$."
    ),
    tags: ["premiere", "maths", "suites", "sommes", "short"],
  },
  {
    kind: "fixed",
    id: "premiere_suites_sommes_fixed_7",
    niveau: "premiere-spe",
    matiere: "maths",
    notionId: "suites",
    microId: "suite_sommes",
    difficulty: 4,
    theme: "neutral",
    text: "Combien y a-t-il de termes dans la somme $1 + q + q^2 + \\dots + q^n$ ?",
    format: "qcm",
    choices: ["$n + 1$", "$n$", "$n - 1$", "$2n$"],
    expected: ["$n + 1$"],
    comparator: "mcq_exact",
    hint: "N'oublie pas le premier terme $q^0 = 1$.",
    explanation: exp(
      "Les exposants vont de $0$ à $n$.",
      "Compter de $0$ à $n$ donne $n + 1$ valeurs, pas $n$.",
      "C'est l'oubli classique : le terme $q^0 = 1$ compte lui aussi.",
      "Il y a $n + 1$ termes."
    ),
    tags: ["premiere", "maths", "suites", "sommes", "qcm"],
  },
  {
    kind: "fixed",
    id: "premiere_suites_sommes_fixed_8",
    niveau: "premiere-spe",
    matiere: "maths",
    notionId: "suites",
    microId: "suite_sommes",
    difficulty: 3,
    theme: "neutral",
    text: "Pour une suite ARITHMÉTIQUE, la somme de termes consécutifs vaut :",
    format: "qcm",
    choices: [
      "$(\\text{nombre de termes}) \\times \\dfrac{\\text{premier} + \\text{dernier}}{2}$",
      "$(\\text{nombre de termes}) \\times (\\text{premier} + \\text{dernier})$",
      "$\\dfrac{\\text{premier} \\times \\text{dernier}}{2}$",
      "$\\dfrac{1 - q^{n+1}}{1 - q}$",
    ],
    expected: [
      "$(\\text{nombre de termes}) \\times \\dfrac{\\text{premier} + \\text{dernier}}{2}$",
    ],
    comparator: "mcq_exact",
    hint: "On multiplie le nombre de termes par la MOYENNE des extrêmes.",
    explanation: exp(
      "En regroupant les termes deux par deux (le premier avec le dernier, etc.), chaque paire a la même somme.",
      "Cela revient à multiplier le nombre de termes par la moyenne du premier et du dernier.",
      "La dernière proposition est la formule de la somme GÉOMÉTRIQUE : elle ne s'applique pas ici.",
      "$S = (\\text{nombre de termes}) \\times \\dfrac{\\text{premier} + \\text{dernier}}{2}$."
    ),
    tags: ["premiere", "maths", "suites", "sommes", "qcm"],
  },
  {
    kind: "fixed",
    id: "premiere_suites_sommes_fixed_9",
    niveau: "premiere-spe",
    matiere: "maths",
    notionId: "suites",
    microId: "suite_sommes",
    difficulty: 4,
    theme: "neutral",
    text: "Combien vaut $1 + 3 + 9 + 27 + 81$ ?",
    format: "short",
    expected: ["121"],
    comparator: "number_equal",
    hint: "Somme géométrique de raison $3$, de $3^0$ à $3^4$.",
    explanation: exp(
      "Chaque terme est le triple du précédent : c'est une somme géométrique de raison $3$.",
      "$S = \\dfrac{1 - 3^5}{1 - 3} = \\dfrac{1 - 243}{-2}$.",
      "$= \\dfrac{-242}{-2} = 121$.",
      "La somme vaut $121$."
    ),
    tags: ["premiere", "maths", "suites", "sommes", "short"],
  },
  {
    kind: "fixed",
    id: "premiere_suites_sommes_fixed_10",
    niveau: "premiere-spe",
    matiere: "maths",
    notionId: "suites",
    microId: "suite_sommes",
    difficulty: 5,
    theme: "neutral",
    text: "Un élève place $1$ € le premier jour, $2$ € le deuxième, $4$ € le troisième, et double chaque jour. Combien a-t-il placé en tout au bout de $10$ jours ?",
    format: "short",
    expected: ["1023"],
    comparator: "number_equal",
    hint: "Les mises vont de $2^0$ à $2^9$ : c'est une somme géométrique.",
    explanation: exp(
      "Les mises forment une suite géométrique de raison $2$ : $2^0$, $2^1$, …, $2^9$ pour $10$ jours.",
      "$S = \\dfrac{1 - 2^{10}}{1 - 2} = \\dfrac{1 - 1024}{-1}$.",
      "$= 1023$. Attention à l'exposant : $10$ jours s'arrêtent à $2^9$, pas à $2^{10}$.",
      "Il a placé $1023$ €."
    ),
    tags: ["premiere", "maths", "suites", "sommes", "short"],
  },
  {
    kind: "fixed",
    id: "premiere_suites_sommes_fixed_11",
    niveau: "premiere-spe",
    matiere: "maths",
    notionId: "suites",
    microId: "suite_sommes",
    difficulty: 5,
    theme: "neutral",
    text: "Combien vaut $2 + 4 + 6 + \\dots + 100$ ?",
    format: "short",
    expected: ["2550"],
    comparator: "number_equal",
    hint: "Mets $2$ en facteur : $2(1 + 2 + \\dots + 50)$.",
    explanation: exp(
      "Ce sont les $50$ premiers nombres pairs.",
      "On factorise par $2$ : $2 + 4 + \\dots + 100 = 2(1 + 2 + \\dots + 50)$.",
      "$= 2 \\times \\dfrac{50 \\times 51}{2} = 2 \\times 1275 = 2550$.",
      "La somme vaut $2550$."
    ),
    tags: ["premiere", "maths", "suites", "sommes", "short"],
  },
  {
    kind: "template",
    id: "premiere_suites_sommes_tpl_1",
    niveau: "premiere-spe",
    matiere: "maths",
    notionId: "suites",
    microId: "suite_sommes",
    difficulty: 3,
    theme: "neutral",
    hint: "$1 + 2 + \\dots + n = \\dfrac{n(n+1)}{2}$.",
    tags: ["premiere", "maths", "suites", "sommes", "template"],
    generate: () => {
      const n = randomInt(10, 50);
      const val = (n * (n + 1)) / 2;
      return {
        text: `Combien vaut $1 + 2 + 3 + \\dots + ${n}$ ?`,
        format: "short",
        expected: [String(val)],
        comparator: "number_equal",
        explanation: exp(
          "On applique la formule des $n$ premiers entiers.",
          `$\\dfrac{${n} \\times ${n + 1}}{2}$.`,
          `$= \\dfrac{${n * (n + 1)}}{2} = ${val}$.`,
          `La somme vaut $${val}$.`
        ),
      };
    },
  },
];
