// lib/tutor-v4/questionBank/premiere-spe/maths/variations-fonctions.bank.ts
//
// Chapitre : Variations et courbes des fonctions (notion "variations_fonctions")
// microSkills :
//   var_signe_derivee — lien entre signe de f' et variations
//   var_tableau       — dresser un tableau de variations
//   var_extremum      — déterminer un extremum
//   var_optimisation  — résoudre un problème d'optimisation
//
// PÉRIMÈTRE BO 2019 Première spé. Conventions : LaTeX, règle QCM. Canvas : fonctionGraphique.

import type { TutorBankItemV4, CanvasFigure } from "@/lib/tutor-v4/types";

function randomInt(min: number, max: number) {
  return Math.floor(Math.random() * (max - min + 1)) + min;
}

function exp(definition: string, methode: string, calcul: string, conclusion: string) {
  return (
    `Définition : ${definition}\n\n` +
    `Méthode : ${methode}\n\n` +
    `Calcul / Observation : ${calcul}\n\n` +
    `Conclusion : ${conclusion}`
  );
}

function parabole(a: number, b: number, c: number): CanvasFigure {
  const xs = -b / (2 * a);
  const ys = a * xs * xs + b * xs + c;
  return {
    kind: "fonctionGraphique",
    size: { width: 300, height: 300 },
    xmin: -6,
    xmax: 6,
    ymin: -8,
    ymax: 8,
    grille: true,
    courbes: [{ id: "f", type: "quadratique", a, b, c, couleur: "#2563eb" }],
    misesEnEvidence: [
      { point: { x: Math.round(xs * 100) / 100, y: Math.round(ys * 100) / 100, label: "S", couleur: "#dc2626" } },
    ],
  };
}

export const variationsFonctionsBank: TutorBankItemV4[] = [
  /* ===================== VAR_SIGNE_DERIVEE ===================== */
  {
    kind: "fixed",
    id: "premiere_var_sg_fixed_1",
    niveau: "premiere-spe",
    matiere: "maths",
    notionId: "variations_fonctions",
    microId: "var_signe_derivee",
    difficulty: 2,
    theme: "neutral",
    text: "Sur un intervalle où $f'(x) > 0$, la fonction $f$ est :",
    format: "qcm",
    choices: ["croissante", "décroissante", "constante", "nulle"],
    expected: ["croissante"],
    comparator: "mcq_exact",
    hint: "Dérivée positive.",
    explanation: exp(
      "Le signe de la dérivée donne le sens de variation.",
      "Si $f'(x) > 0$ sur un intervalle, $f$ y croît.",
      "C'est la règle fondamentale dérivée ↔ variations.",
      "$f$ est croissante."
    ),
    tags: ["premiere", "maths", "variations", "signe_derivee", "qcm"],
  },
  {
    kind: "fixed",
    id: "premiere_var_sg_fixed_2",
    niveau: "premiere-spe",
    matiere: "maths",
    notionId: "variations_fonctions",
    microId: "var_signe_derivee",
    difficulty: 2,
    theme: "neutral",
    text: "Sur un intervalle où $f'(x) < 0$, la fonction $f$ est :",
    format: "qcm",
    choices: ["décroissante", "croissante", "constante", "maximale"],
    expected: ["décroissante"],
    comparator: "mcq_exact",
    hint: "Dérivée négative.",
    explanation: exp(
      "Le signe de la dérivée donne le sens de variation.",
      "Si $f'(x) < 0$ sur un intervalle, $f$ y décroît.",
      "C'est la règle dérivée ↔ variations.",
      "$f$ est décroissante."
    ),
    tags: ["premiere", "maths", "variations", "signe_derivee", "qcm"],
  },
  {
    kind: "fixed",
    id: "premiere_var_sg_fixed_3",
    niveau: "premiere-spe",
    matiere: "maths",
    notionId: "variations_fonctions",
    microId: "var_signe_derivee",
    difficulty: 3,
    theme: "neutral",
    text: "Si $f'(x) = 0$ sur tout un intervalle, alors $f$ y est :",
    format: "qcm",
    choices: ["constante", "croissante", "décroissante", "nulle"],
    expected: ["constante"],
    comparator: "mcq_exact",
    hint: "Pas de variation.",
    explanation: exp(
      "Une dérivée nulle sur un intervalle signifie aucune variation.",
      "$f$ ne monte ni ne descend.",
      "Elle est donc constante sur cet intervalle.",
      "$f$ est constante."
    ),
    tags: ["premiere", "maths", "variations", "signe_derivee", "qcm"],
  },
  {
    kind: "fixed",
    id: "premiere_var_sg_fixed_4",
    niveau: "premiere-spe",
    matiere: "maths",
    notionId: "variations_fonctions",
    microId: "var_signe_derivee",
    difficulty: 3,
    theme: "neutral",
    text: "Soit $f(x) = x^2 - 4x + 1$ donc $f'(x) = 2x - 4$. Sur quel intervalle $f$ est-elle croissante ?",
    format: "qcm",
    choices: ["$[2 ; +\\infty[$", "$]-\\infty ; 2]$", "$\\mathbb{R}$", "$[0 ; 2]$"],
    expected: ["$[2 ; +\\infty[$"],
    comparator: "mcq_exact",
    hint: "Là où $f'(x) \\ge 0$, soit $2x - 4 \\ge 0$.",
    explanation: exp(
      "$f$ croît là où $f'(x) \\ge 0$.",
      "$2x - 4 \\ge 0 \\Leftrightarrow x \\ge 2$.",
      "Donc $f$ croît sur $[2 ; +\\infty[$.",
      "$[2 ; +\\infty[$."
    ),
    canvas: parabole(1, -4, 1),
    tags: ["premiere", "maths", "variations", "signe_derivee", "canvas", "qcm"],
  },
  {
    kind: "fixed",
    id: "premiere_var_sg_fixed_5",
    niveau: "premiere-spe",
    matiere: "maths",
    notionId: "variations_fonctions",
    microId: "var_signe_derivee",
    difficulty: 4,
    theme: "neutral",
    text: "Pour étudier les variations d'une fonction dérivable, on étudie d'abord :",
    format: "qcm",
    choices: ["le signe de $f'(x)$", "le signe de $f(x)$", "la valeur de $f(0)$", "les racines de $f$"],
    expected: ["le signe de $f'(x)$"],
    comparator: "mcq_exact",
    hint: "Variations ← dérivée.",
    explanation: exp(
      "Les variations se déduisent du signe de la dérivée.",
      "On calcule $f'$, puis on étudie son signe.",
      "On en déduit le tableau de variations.",
      "On étudie le signe de $f'(x)$."
    ),
    tags: ["premiere", "maths", "variations", "signe_derivee", "qcm"],
  },
  {
    kind: "fixed",
    id: "premiere_var_sg_fixed_6",
    niveau: "premiere-spe",
    matiere: "maths",
    notionId: "variations_fonctions",
    microId: "var_signe_derivee",
    difficulty: 4,
    theme: "neutral",
    text: "Une fonction $f$ a pour dérivée $f'(x) = 3x^2 + 1$. Que peut-on dire de $f$ sur $\\mathbb{R}$ ?",
    format: "qcm",
    choices: [
      "elle est croissante sur $\\mathbb{R}$",
      "elle est décroissante sur $\\mathbb{R}$",
      "elle est constante",
      "elle change de sens en $x = 0$",
    ],
    expected: ["elle est croissante sur $\\mathbb{R}$"],
    comparator: "mcq_exact",
    hint: "$3x^2$ est positif ou nul : que vaut alors $3x^2 + 1$ ?",
    explanation: exp(
      "Le sens de variation est donné par le signe de la dérivée.",
      "Un carré est toujours positif ou nul, donc $3x^2 \\ge 0$ et $3x^2 + 1 \\ge 1 > 0$.",
      "La dérivée est strictement positive partout : elle ne s'annule jamais.",
      "$f$ est croissante sur $\\mathbb{R}$."
    ),
    tags: ["premiere", "maths", "variations", "signe_derivee", "qcm"],
  },
  {
    kind: "fixed",
    id: "premiere_var_sg_fixed_7",
    niveau: "premiere-spe",
    matiere: "maths",
    notionId: "variations_fonctions",
    microId: "var_signe_derivee",
    difficulty: 5,
    theme: "neutral",
    text: "Soit $f(x) = x^3 - 3x$, donc $f'(x) = 3x^2 - 3$. Sur quel intervalle $f$ est-elle décroissante ?",
    format: "qcm",
    choices: ["$[-1 ; 1]$", "$[0 ; 3]$", "$]-\\infty ; -1]$", "$\\mathbb{R}$"],
    expected: ["$[-1 ; 1]$"],
    comparator: "mcq_exact",
    hint: "Factorise : $3x^2 - 3 = 3(x - 1)(x + 1)$. Où ce trinôme est-il négatif ?",
    explanation: exp(
      "$f$ décroît là où $f'(x) \\le 0$.",
      "$f'(x) = 3(x^2 - 1) = 3(x - 1)(x + 1)$ : les racines sont $-1$ et $1$, et le coefficient de $x^2$ est positif.",
      "Un tel trinôme est négatif ENTRE ses racines, donc sur $[-1 ; 1]$.",
      "$f$ est décroissante sur $[-1 ; 1]$."
    ),
    tags: ["premiere", "maths", "variations", "signe_derivee", "qcm"],
  },
  {
    kind: "fixed",
    id: "premiere_var_sg_fixed_8",
    niveau: "premiere-spe",
    matiere: "maths",
    notionId: "variations_fonctions",
    microId: "var_signe_derivee",
    difficulty: 3,
    theme: "neutral",
    text: "Si $f$ est décroissante sur un intervalle $I$, alors sur $I$ :",
    format: "qcm",
    choices: [
      "$f'(x) \\le 0$",
      "$f'(x) \\ge 0$",
      "$f(x) \\le 0$",
      "$f'(x) = 0$",
    ],
    expected: ["$f'(x) \\le 0$"],
    comparator: "mcq_exact",
    hint: "Attention : c'est le signe de la DÉRIVÉE, pas celui de $f$.",
    explanation: exp(
      "Le lien fonctionne dans les deux sens : $f$ décroissante sur $I$ équivaut à $f' \\le 0$ sur $I$.",
      "Le signe de $f(x)$ n'a rien à voir : une fonction peut être décroissante tout en restant positive.",
      "Par exemple $f(x) = \\dfrac{1}{x}$ sur $]0 ; +\\infty[$ est positive ET décroissante.",
      "Sur $I$, $f'(x) \\le 0$."
    ),
    tags: ["premiere", "maths", "variations", "signe_derivee", "qcm"],
  },
  {
    kind: "fixed",
    id: "premiere_var_sg_fixed_9",
    niveau: "premiere-spe",
    matiere: "maths",
    notionId: "variations_fonctions",
    microId: "var_signe_derivee",
    difficulty: 2,
    theme: "neutral",
    text: "Soit $f(x) = -2x + 7$. Que peut-on dire de $f$ ?",
    format: "qcm",
    choices: [
      "elle est décroissante sur $\\mathbb{R}$",
      "elle est croissante sur $\\mathbb{R}$",
      "elle est constante",
      "elle décroît puis croît",
    ],
    expected: ["elle est décroissante sur $\\mathbb{R}$"],
    comparator: "mcq_exact",
    hint: "$f'(x) = -2$ : quel est son signe ?",
    explanation: exp(
      "Pour une fonction affine $ax + b$, la dérivée est la constante $a$.",
      "Ici $f'(x) = -2$, qui est négatif quel que soit $x$.",
      "La dérivée est négative partout, donc la fonction descend partout.",
      "$f$ est décroissante sur $\\mathbb{R}$."
    ),
    tags: ["premiere", "maths", "variations", "signe_derivee", "qcm"],
  },
  {
    kind: "fixed",
    id: "premiere_var_sg_fixed_10",
    niveau: "premiere-spe",
    matiere: "maths",
    notionId: "variations_fonctions",
    microId: "var_signe_derivee",
    difficulty: 5,
    theme: "neutral",
    text: "Une fonction $f$ a pour dérivée $f'(x) = (x - 3)^2$. Que peut-on dire de $f$ sur $\\mathbb{R}$ ?",
    format: "qcm",
    choices: [
      "elle est croissante sur $\\mathbb{R}$",
      "elle est décroissante sur $\\mathbb{R}$",
      "elle a un maximum en $x = 3$",
      "elle a un minimum en $x = 3$",
    ],
    expected: ["elle est croissante sur $\\mathbb{R}$"],
    comparator: "mcq_exact",
    hint: "Un carré s'annule, mais ne devient jamais négatif.",
    explanation: exp(
      "Le sens de variation dépend du SIGNE de $f'$, pas de ses valeurs nulles.",
      "$(x - 3)^2 \\ge 0$ pour tout $x$ : la dérivée est positive partout, et nulle seulement en $x = 3$.",
      "En $x = 3$ la dérivée s'annule sans changer de signe : la courbe a une tangente horizontale, mais $f$ continue de monter — ce n'est pas un extremum.",
      "$f$ est croissante sur $\\mathbb{R}$."
    ),
    tags: ["premiere", "maths", "variations", "signe_derivee", "qcm"],
  },
  {
    kind: "fixed",
    id: "premiere_var_sg_fixed_11",
    niveau: "premiere-spe",
    matiere: "maths",
    notionId: "variations_fonctions",
    microId: "var_signe_derivee",
    difficulty: 4,
    theme: "neutral",
    text: "On sait que $f'(x) > 0$ sur $]-\\infty ; 2[$ et $f'(x) < 0$ sur $]2 ; +\\infty[$. Que fait $f$ ?",
    format: "qcm",
    choices: [
      "elle croît puis décroît",
      "elle décroît puis croît",
      "elle croît sur $\\mathbb{R}$",
      "elle est constante après $2$",
    ],
    expected: ["elle croît puis décroît"],
    comparator: "mcq_exact",
    hint: "Dérivée positive = ça monte ; dérivée négative = ça descend.",
    explanation: exp(
      "On traduit chaque intervalle de signe de $f'$ en sens de variation de $f$.",
      "$f' > 0$ avant $2$ : $f$ croît. $f' < 0$ après $2$ : $f$ décroît.",
      "La fonction monte jusqu'en $2$ puis redescend : elle atteint un maximum en $x = 2$.",
      "$f$ croît puis décroît."
    ),
    tags: ["premiere", "maths", "variations", "signe_derivee", "qcm"],
  },
  {
    kind: "template",
    id: "premiere_var_sg_tpl_1",
    niveau: "premiere-spe",
    matiere: "maths",
    notionId: "variations_fonctions",
    microId: "var_signe_derivee",
    difficulty: 3,
    theme: "neutral",
    hint: "Là où $f'(x) \\ge 0$.",
    tags: ["premiere", "maths", "variations", "signe_derivee", "template"],
    generate: () => {
      const alpha = randomInt(1, 4);
      const b = -2 * alpha;
      const c = randomInt(-2, 3);
      const correct = `$[${alpha} ; +\\infty[$`;
      const choices = [correct, `$]-\\infty ; ${alpha}]$`, "$\\mathbb{R}$", `$[0 ; ${alpha}]$`];
      return {
        text: `Soit $f(x) = x^2 ${b >= 0 ? "+ " + b : "- " + -b}x ${c >= 0 ? "+ " + c : "- " + -c}$, donc $f'(x) = 2x ${b >= 0 ? "+ " + b : "- " + -b}$. Sur quel intervalle $f$ est-elle croissante ?`,
        format: "qcm",
        choices,
        expected: [correct],
        comparator: "mcq_exact",
        explanation: exp(
          "$f$ croît là où $f'(x) \\ge 0$.",
          `$2x ${b >= 0 ? "+ " + b : "- " + -b} \\ge 0 \\Leftrightarrow x \\ge ${alpha}$.`,
          `Donc $f$ croît sur $[${alpha} ; +\\infty[$.`,
          `$[${alpha} ; +\\infty[$.`
        ),
      };
    },
  },

  /* ===================== VAR_TABLEAU ===================== */
  {
    kind: "fixed",
    id: "premiere_var_tab_fixed_1",
    niveau: "premiere-spe",
    matiere: "maths",
    notionId: "variations_fonctions",
    microId: "var_tableau",
    difficulty: 2,
    theme: "neutral",
    text: "Dans un tableau de variations, une flèche montante signifie que la fonction est :",
    format: "qcm",
    choices: ["croissante", "décroissante", "constante", "négative"],
    expected: ["croissante"],
    comparator: "mcq_exact",
    hint: "Flèche ↗.",
    explanation: exp(
      "Le tableau de variations représente le sens de variation par des flèches.",
      "Une flèche montante ↗ correspond à une croissance.",
      "Elle se place là où $f' > 0$.",
      "La fonction est croissante."
    ),
    tags: ["premiere", "maths", "variations", "tableau", "qcm"],
  },
  {
    kind: "fixed",
    id: "premiere_var_tab_fixed_2",
    niveau: "premiere-spe",
    matiere: "maths",
    notionId: "variations_fonctions",
    microId: "var_tableau",
    difficulty: 3,
    theme: "neutral",
    text: "Pour $f(x) = x^2$, le tableau de variations montre que $f$ :",
    format: "qcm",
    choices: [
      "décroît puis croît",
      "croît puis décroît",
      "est toujours croissante",
      "est constante",
    ],
    expected: ["décroît puis croît"],
    comparator: "mcq_exact",
    hint: "Parabole tournée vers le haut, sommet en $0$.",
    explanation: exp(
      "$f'(x) = 2x$ : négatif avant $0$, positif après.",
      "$f$ décroît sur $]-\\infty ; 0]$ puis croît sur $[0 ; +\\infty[$.",
      "Le sommet (minimum) est en $x = 0$.",
      "$f$ décroît puis croît."
    ),
    canvas: parabole(1, 0, 0),
    tags: ["premiere", "maths", "variations", "tableau", "canvas", "qcm"],
  },
  {
    kind: "fixed",
    id: "premiere_var_tab_fixed_3",
    niveau: "premiere-spe",
    matiere: "maths",
    notionId: "variations_fonctions",
    microId: "var_tableau",
    difficulty: 3,
    theme: "neutral",
    text: "Dans un tableau de variations, où place-t-on les valeurs qui annulent $f'$ ?",
    format: "qcm",
    choices: [
      "aux changements de sens (extremums)",
      "uniquement aux bornes",
      "nulle part",
      "à $x = 0$ seulement",
    ],
    expected: ["aux changements de sens (extremums)"],
    comparator: "mcq_exact",
    hint: "$f' = 0$ : la dérivée change souvent de signe.",
    explanation: exp(
      "Les valeurs annulant $f'$ peuvent marquer un changement de sens.",
      "On les place comme abscisses séparant croissance et décroissance.",
      "Elles correspondent souvent à un extremum local.",
      "Aux changements de sens (extremums)."
    ),
    tags: ["premiere", "maths", "variations", "tableau", "qcm"],
  },
  {
    kind: "fixed",
    id: "premiere_var_tab_fixed_4",
    niveau: "premiere-spe",
    matiere: "maths",
    notionId: "variations_fonctions",
    microId: "var_tableau",
    difficulty: 4,
    theme: "neutral",
    text: "Pour $f(x) = -x^2 + 6x$, $f'(x) = -2x + 6$. La fonction croît sur :",
    format: "qcm",
    choices: ["$]-\\infty ; 3]$", "$[3 ; +\\infty[$", "$\\mathbb{R}$", "$[0 ; 6]$"],
    expected: ["$]-\\infty ; 3]$"],
    comparator: "mcq_exact",
    hint: "$f'(x) \\ge 0 \\Leftrightarrow -2x + 6 \\ge 0$.",
    explanation: exp(
      "$f$ croît là où $f'(x) \\ge 0$.",
      "$-2x + 6 \\ge 0 \\Leftrightarrow x \\le 3$.",
      "Donc $f$ croît sur $]-\\infty ; 3]$ (parabole vers le bas).",
      "$]-\\infty ; 3]$."
    ),
    canvas: parabole(-1, 6, 0),
    tags: ["premiere", "maths", "variations", "tableau", "canvas", "qcm"],
  },
  {
    kind: "fixed",
    id: "premiere_var_tab_fixed_5",
    niveau: "premiere-spe",
    matiere: "maths",
    notionId: "variations_fonctions",
    microId: "var_tableau",
    difficulty: 2,
    theme: "neutral",
    text: "Dans un tableau de variations, une flèche descendante signifie que la fonction est :",
    format: "qcm",
    choices: ["décroissante", "croissante", "constante", "négative"],
    expected: ["décroissante"],
    comparator: "mcq_exact",
    hint: "La flèche suit le trajet de la courbe.",
    explanation: exp(
      "Les flèches d'un tableau de variations dessinent le trajet de la courbe.",
      "Une flèche qui descend indique que les valeurs de $f$ diminuent quand $x$ augmente.",
      "C'est la définition d'une fonction décroissante. La flèche ne dit rien du SIGNE de $f$ : une fonction décroissante peut rester positive.",
      "La fonction est décroissante."
    ),
    tags: ["premiere", "maths", "variations", "tableau", "qcm"],
  },
  {
    kind: "fixed",
    id: "premiere_var_tab_fixed_6",
    niveau: "premiere-spe",
    matiere: "maths",
    notionId: "variations_fonctions",
    microId: "var_tableau",
    difficulty: 4,
    theme: "neutral",
    text: "Pour $f(x) = x^3 - 3x$, on a $f'(x) = 3x^2 - 3$. Combien de valeurs de $x$ annulent $f'$ ?",
    format: "short",
    expected: ["2"],
    comparator: "number_equal",
    hint: "Résous $3x^2 - 3 = 0$.",
    explanation: exp(
      "Les valeurs qui annulent $f'$ sont celles qui découpent le tableau de variations en colonnes.",
      "$3x^2 - 3 = 0 \\Leftrightarrow x^2 = 1$.",
      "Il y a deux solutions : $x = -1$ et $x = 1$.",
      "Deux valeurs annulent $f'$ : le tableau aura donc trois zones de variation."
    ),
    tags: ["premiere", "maths", "variations", "tableau", "short"],
  },
  {
    kind: "fixed",
    id: "premiere_var_tab_fixed_7",
    niveau: "premiere-spe",
    matiere: "maths",
    notionId: "variations_fonctions",
    microId: "var_tableau",
    difficulty: 5,
    theme: "neutral",
    text: "Pour $f(x) = 2x^3 - 6x$, on a $f'(x) = 6x^2 - 6$. Sur quels intervalles $f$ est-elle croissante ?",
    format: "qcm",
    choices: [
      "$]-\\infty ; -1]$ et $[1 ; +\\infty[$",
      "$[-1 ; 1]$",
      "$\\mathbb{R}$",
      "$[0 ; +\\infty[$",
    ],
    expected: ["$]-\\infty ; -1]$ et $[1 ; +\\infty[$"],
    comparator: "mcq_exact",
    hint: "$6x^2 - 6 = 6(x - 1)(x + 1)$ : positif à l'extérieur des racines.",
    explanation: exp(
      "$f$ croît là où $f'(x) \\ge 0$.",
      "$f'(x) = 6(x - 1)(x + 1)$ : c'est un trinôme de racines $-1$ et $1$ avec un coefficient dominant positif.",
      "Il est donc positif à l'EXTÉRIEUR des racines : sur $]-\\infty ; -1]$ et sur $[1 ; +\\infty[$.",
      "$f$ croît sur $]-\\infty ; -1]$ et sur $[1 ; +\\infty[$."
    ),
    tags: ["premiere", "maths", "variations", "tableau", "qcm"],
  },
  {
    kind: "fixed",
    id: "premiere_var_tab_fixed_8",
    niveau: "premiere-spe",
    matiere: "maths",
    notionId: "variations_fonctions",
    microId: "var_tableau",
    difficulty: 3,
    theme: "neutral",
    text: "Que contiennent les trois lignes d'un tableau de variations ?",
    format: "qcm",
    choices: [
      "les valeurs de $x$, le signe de $f'(x)$, les variations de $f$",
      "les valeurs de $x$, le signe de $f(x)$, les variations de $f'$",
      "les valeurs de $x$, les racines de $f$, le maximum",
      "les valeurs de $f$, celles de $f'$, celles de $f''$",
    ],
    expected: ["les valeurs de $x$, le signe de $f'(x)$, les variations de $f$"],
    comparator: "mcq_exact",
    hint: "On part de $x$, on passe par la dérivée, on conclut sur $f$.",
    explanation: exp(
      "Le tableau raconte le raisonnement dans l'ordre où on le mène.",
      "Ligne 1 : les valeurs de $x$ (bornes de l'intervalle et valeurs qui annulent $f'$). Ligne 2 : le signe de $f'(x)$. Ligne 3 : les flèches de variation de $f$.",
      "C'est bien le signe de $f'$ qui figure au milieu, pas celui de $f$ : les deux n'ont aucune raison de coïncider.",
      "$x$, puis le signe de $f'(x)$, puis les variations de $f$."
    ),
    tags: ["premiere", "maths", "variations", "tableau", "qcm"],
  },
  {
    kind: "fixed",
    id: "premiere_var_tab_fixed_9",
    niveau: "premiere-spe",
    matiere: "maths",
    notionId: "variations_fonctions",
    microId: "var_tableau",
    difficulty: 4,
    theme: "neutral",
    text: "Le tableau de variations de $f$ sur $[0 ; 5]$ indique : $f$ croissante sur $[0 ; 3]$ puis décroissante sur $[3 ; 5]$, avec $f(3) = 7$. Quel est le maximum de $f$ sur $[0 ; 5]$ ?",
    format: "short",
    expected: ["7"],
    comparator: "number_equal",
    hint: "Le maximum est atteint là où la fonction cesse de monter.",
    explanation: exp(
      "Sur un tableau de variations, le maximum se lit au sommet, là où les flèches changent de sens.",
      "Ici $f$ monte jusqu'en $x = 3$ puis redescend : le point le plus haut est atteint en $3$.",
      "La valeur correspondante est $f(3) = 7$. (Le maximum est la VALEUR $7$, l'abscisse $3$ est l'endroit où il est atteint.)",
      "Le maximum de $f$ vaut $7$."
    ),
    tags: ["premiere", "maths", "variations", "tableau", "short"],
  },
  {
    kind: "fixed",
    id: "premiere_var_tab_fixed_10",
    niveau: "premiere-spe",
    matiere: "maths",
    notionId: "variations_fonctions",
    microId: "var_tableau",
    difficulty: 4,
    theme: "neutral",
    text: "Pour $f(x) = x^2 - 2x + 3$, en quelle abscisse le tableau de variations change-t-il de sens ?",
    format: "short",
    expected: ["1"],
    comparator: "number_equal",
    hint: "Résous $f'(x) = 0$ avec $f'(x) = 2x - 2$.",
    explanation: exp(
      "Le tableau change de sens là où la dérivée s'annule en changeant de signe.",
      "$f'(x) = 2x - 2$, donc $f'(x) = 0 \\Leftrightarrow x = 1$.",
      "Avant $1$, $f'$ est négative ($f$ décroît) ; après, elle est positive ($f$ croît).",
      "Le changement a lieu en $x = 1$."
    ),
    canvas: parabole(1, -2, 3),
    tags: ["premiere", "maths", "variations", "tableau", "canvas", "short"],
  },
  {
    kind: "fixed",
    id: "premiere_var_tab_fixed_11",
    niveau: "premiere-spe",
    matiere: "maths",
    notionId: "variations_fonctions",
    microId: "var_tableau",
    difficulty: 3,
    theme: "neutral",
    text: "Dans la ligne des variations, qu'écrit-on au bout de chaque flèche ?",
    format: "qcm",
    choices: [
      "les images $f(x)$ des valeurs remarquables",
      "les valeurs de $f'(x)$",
      "toujours $0$",
      "les racines de $f$",
    ],
    expected: ["les images $f(x)$ des valeurs remarquables"],
    comparator: "mcq_exact",
    hint: "La ligne du bas décrit $f$, pas $f'$.",
    explanation: exp(
      "La dernière ligne du tableau décrit la fonction $f$ elle-même.",
      "Aux extrémités des flèches, on écrit les images : $f$ des bornes de l'intervalle, et $f$ des valeurs qui annulent $f'$.",
      "Ce sont ces images qui donnent les extremums. La valeur $f'(x) = 0$, elle, figure sur la ligne du dessus.",
      "On écrit les images $f(x)$ des valeurs remarquables."
    ),
    tags: ["premiere", "maths", "variations", "tableau", "qcm"],
  },
  {
    kind: "template",
    id: "premiere_var_tab_tpl_1",
    niveau: "premiere-spe",
    matiere: "maths",
    notionId: "variations_fonctions",
    microId: "var_tableau",
    difficulty: 3,
    theme: "neutral",
    hint: "Signe de $a$ : vers le haut → décroît puis croît.",
    tags: ["premiere", "maths", "variations", "tableau", "template"],
    generate: () => {
      const versHaut = randomInt(0, 1) === 1;
      const a = versHaut ? 1 : -1;
      const correct = versHaut ? "décroît puis croît" : "croît puis décroît";
      return {
        text: `Une parabole d'équation $y = ${a === 1 ? "" : "-"}x^2 + bx + c$ a son coefficient de $x^2$ ${versHaut ? "positif" : "négatif"}. Que fait la fonction ?`,
        format: "qcm",
        choices: ["décroît puis croît", "croît puis décroît", "est toujours croissante", "est constante"],
        expected: [correct],
        comparator: "mcq_exact",
        explanation: exp(
          "Le signe du coefficient de $x^2$ donne l'allure de la parabole.",
          `Ici il est ${versHaut ? "positif (parabole vers le haut)" : "négatif (parabole vers le bas)"}.`,
          `Donc la fonction ${correct}.`,
          `La fonction ${correct}.`
        ),
      };
    },
  },

  /* ===================== VAR_EXTREMUM ===================== */
  {
    kind: "fixed",
    id: "premiere_var_ext_fixed_1",
    niveau: "premiere-spe",
    matiere: "maths",
    notionId: "variations_fonctions",
    microId: "var_extremum",
    difficulty: 2,
    theme: "neutral",
    text: "Un extremum d'une fonction dérivable est atteint là où :",
    format: "qcm",
    choices: [
      "$f'$ s'annule en changeant de signe",
      "$f$ s'annule",
      "$f' > 0$",
      "$f$ est négative",
    ],
    expected: ["$f'$ s'annule en changeant de signe"],
    comparator: "mcq_exact",
    hint: "La dérivée change de signe.",
    explanation: exp(
      "Un extremum local correspond à un changement de sens de variation.",
      "La dérivée s'annule et change de signe à cet endroit.",
      "Si $f'$ passe de $+$ à $-$ : maximum ; de $-$ à $+$ : minimum.",
      "$f'$ s'annule en changeant de signe."
    ),
    tags: ["premiere", "maths", "variations", "extremum", "qcm"],
  },
  {
    kind: "fixed",
    id: "premiere_var_ext_fixed_2",
    niveau: "premiere-spe",
    matiere: "maths",
    notionId: "variations_fonctions",
    microId: "var_extremum",
    difficulty: 3,
    theme: "neutral",
    text: "Pour $f(x) = x^2 - 6x + 5$, en quelle abscisse $f$ atteint-elle son minimum ?",
    format: "short",
    expected: ["3"],
    comparator: "number_equal",
    hint: "$f'(x) = 2x - 6 = 0$.",
    explanation: exp(
      "Le minimum est atteint là où $f'(x) = 0$.",
      "$2x - 6 = 0 \\Leftrightarrow x = 3$.",
      "$f'$ passe de $-$ à $+$ : c'est bien un minimum.",
      "Minimum atteint en $x = 3$."
    ),
    canvas: parabole(1, -6, 5),
    tags: ["premiere", "maths", "variations", "extremum", "canvas", "short"],
  },
  {
    kind: "fixed",
    id: "premiere_var_ext_fixed_3",
    niveau: "premiere-spe",
    matiere: "maths",
    notionId: "variations_fonctions",
    microId: "var_extremum",
    difficulty: 4,
    theme: "neutral",
    text: "Pour $f(x) = x^2 - 6x + 5$, quelle est la valeur du minimum ?",
    format: "short",
    expected: ["-4"],
    comparator: "number_equal",
    hint: "Calcule $f(3)$.",
    explanation: exp(
      "Le minimum vaut $f$ en l'abscisse du sommet.",
      "$f(3) = 3^2 - 6 \\times 3 + 5 = 9 - 18 + 5$.",
      "$= -4$.",
      "Le minimum vaut $-4$."
    ),
    canvas: parabole(1, -6, 5),
    tags: ["premiere", "maths", "variations", "extremum", "canvas", "short"],
  },
  {
    kind: "fixed",
    id: "premiere_var_ext_fixed_4",
    niveau: "premiere-spe",
    matiere: "maths",
    notionId: "variations_fonctions",
    microId: "var_extremum",
    difficulty: 3,
    theme: "neutral",
    text: "Si $f'$ passe de positif à négatif en $x = a$, alors $f(a)$ est :",
    format: "qcm",
    choices: ["un maximum local", "un minimum local", "nul", "une racine"],
    expected: ["un maximum local"],
    comparator: "mcq_exact",
    hint: "$f$ monte puis descend.",
    explanation: exp(
      "Le sens de variation change selon le signe de $f'$.",
      "$f'$ de $+$ à $-$ : $f$ croît puis décroît.",
      "Le point le plus haut est un maximum local.",
      "Un maximum local."
    ),
    tags: ["premiere", "maths", "variations", "extremum", "qcm"],
  },
  {
    kind: "fixed",
    id: "premiere_var_ext_fixed_5",
    niveau: "premiere-spe",
    matiere: "maths",
    notionId: "variations_fonctions",
    microId: "var_extremum",
    difficulty: 4,
    theme: "neutral",
    text: "Pour $f(x) = -x^2 + 6x$, quelle est la valeur du maximum ?",
    format: "short",
    expected: ["9"],
    comparator: "number_equal",
    hint: "Le maximum est atteint en $x = 3$ : calcule $f(3)$.",
    explanation: exp(
      "La valeur d'un extremum est l'IMAGE du point où la dérivée s'annule.",
      "$f'(x) = -2x + 6$ s'annule en $x = 3$ ; on calcule $f(3) = -3^2 + 6 \\times 3$.",
      "$= -9 + 18 = 9$.",
      "Le maximum vaut $9$ (atteint en $x = 3$)."
    ),
    canvas: parabole(-1, 6, 0),
    tags: ["premiere", "maths", "variations", "extremum", "canvas", "short"],
  },
  {
    kind: "fixed",
    id: "premiere_var_ext_fixed_6",
    niveau: "premiere-spe",
    matiere: "maths",
    notionId: "variations_fonctions",
    microId: "var_extremum",
    difficulty: 3,
    theme: "neutral",
    text: "Si $f'$ passe de négatif à positif en $x = a$, alors $f(a)$ est :",
    format: "qcm",
    choices: ["un minimum local", "un maximum local", "nul", "une racine de $f$"],
    expected: ["un minimum local"],
    comparator: "mcq_exact",
    hint: "$f$ descend puis remonte.",
    explanation: exp(
      "Le sens de variation de $f$ suit le signe de $f'$.",
      "$f'$ négative avant $a$ : $f$ décroît. $f'$ positive après : $f$ croît.",
      "La fonction descend puis remonte : le point le plus bas est atteint en $a$.",
      "$f(a)$ est un minimum local."
    ),
    tags: ["premiere", "maths", "variations", "extremum", "qcm"],
  },
  {
    kind: "fixed",
    id: "premiere_var_ext_fixed_7",
    niveau: "premiere-spe",
    matiere: "maths",
    notionId: "variations_fonctions",
    microId: "var_extremum",
    difficulty: 5,
    theme: "neutral",
    text: "Pour $f(x) = x^3$, on a $f'(0) = 0$. La fonction admet-elle un extremum en $0$ ?",
    format: "qcm",
    choices: [
      "non : $f'$ ne change pas de signe en $0$",
      "oui : c'est un minimum",
      "oui : c'est un maximum",
      "oui, car $f'(0) = 0$ suffit",
    ],
    expected: ["non : $f'$ ne change pas de signe en $0$"],
    comparator: "mcq_exact",
    hint: "$f'(x) = 3x^2$ : quel est son signe avant et après $0$ ?",
    explanation: exp(
      "Une dérivée nulle ne suffit pas : il faut qu'elle CHANGE DE SIGNE pour qu'il y ait un extremum.",
      "$f'(x) = 3x^2$ est positive avant $0$ comme après $0$ : elle s'annule sans changer de signe.",
      "La fonction continue donc de croître ; en $0$ la courbe a seulement une tangente horizontale.",
      "Non : il n'y a pas d'extremum en $0$."
    ),
    tags: ["premiere", "maths", "variations", "extremum", "qcm"],
  },
  {
    kind: "fixed",
    id: "premiere_var_ext_fixed_8",
    niveau: "premiere-spe",
    matiere: "maths",
    notionId: "variations_fonctions",
    microId: "var_extremum",
    difficulty: 4,
    theme: "neutral",
    text: "Pour $f(x) = x^2 - 8x + 3$, quelle est la valeur du minimum ?",
    format: "short",
    expected: ["-13"],
    comparator: "number_equal",
    hint: "$f'(x) = 2x - 8$ s'annule en $4$ : calcule $f(4)$.",
    explanation: exp(
      "On cherche d'abord où $f'$ s'annule, puis on calcule l'image de cette valeur.",
      "$f'(x) = 2x - 8 = 0 \\Leftrightarrow x = 4$. Puis $f(4) = 16 - 32 + 3$.",
      "$= -13$. Comme $f'$ passe de $-$ à $+$, c'est bien un minimum.",
      "Le minimum vaut $-13$."
    ),
    tags: ["premiere", "maths", "variations", "extremum", "short"],
  },
  {
    kind: "fixed",
    id: "premiere_var_ext_fixed_9",
    niveau: "premiere-spe",
    matiere: "maths",
    notionId: "variations_fonctions",
    microId: "var_extremum",
    difficulty: 3,
    theme: "neutral",
    text: "Que signifie « $f$ admet un maximum LOCAL en $a$ » ?",
    format: "qcm",
    choices: [
      "$f(a)$ est la plus grande valeur sur un intervalle autour de $a$",
      "$f(a)$ est la plus grande valeur sur tout l'ensemble de définition",
      "$f(a) = 0$",
      "$f$ est croissante après $a$",
    ],
    expected: ["$f(a)$ est la plus grande valeur sur un intervalle autour de $a$"],
    comparator: "mcq_exact",
    hint: "« Local » : ce qui se passe tout près de $a$.",
    explanation: exp(
      "Un maximum local ne vaut que dans le voisinage du point.",
      "$f(a)$ est la plus grande valeur atteinte sur un petit intervalle autour de $a$ : ailleurs, la fonction peut monter bien plus haut.",
      "Si la propriété vaut sur TOUT l'ensemble de définition, on parle de maximum global.",
      "C'est la plus grande valeur sur un intervalle autour de $a$."
    ),
    tags: ["premiere", "maths", "variations", "extremum", "qcm"],
  },
  {
    kind: "fixed",
    id: "premiere_var_ext_fixed_10",
    niveau: "premiere-spe",
    matiere: "maths",
    notionId: "variations_fonctions",
    microId: "var_extremum",
    difficulty: 5,
    theme: "neutral",
    text: "Pour $f(x) = 2x^3 - 6x$, on a $f'(x) = 6x^2 - 6$. En quelle abscisse $f$ admet-elle un maximum local ?",
    format: "short",
    expected: ["-1"],
    comparator: "number_equal",
    hint: "$f'$ s'annule en $-1$ et $1$ : lequel correspond à un passage de $+$ à $-$ ?",
    explanation: exp(
      "Un maximum local est atteint là où $f'$ passe de positif à négatif.",
      "$f'(x) = 6(x - 1)(x + 1)$ s'annule en $-1$ et en $1$. Ce trinôme est positif à l'extérieur des racines, négatif entre elles.",
      "En $x = -1$, $f'$ passe donc de $+$ à $-$ : maximum. En $x = 1$, elle passe de $-$ à $+$ : minimum.",
      "Le maximum local est atteint en $x = -1$."
    ),
    tags: ["premiere", "maths", "variations", "extremum", "short"],
  },
  {
    kind: "fixed",
    id: "premiere_var_ext_fixed_11",
    niveau: "premiere-spe",
    matiere: "maths",
    notionId: "variations_fonctions",
    microId: "var_extremum",
    difficulty: 5,
    theme: "neutral",
    text: "Le bénéfice d'un atelier est $B(x) = -x^2 + 40x - 300$ euros pour $x$ objets vendus. Quel est le bénéfice maximal ?",
    format: "short",
    expected: ["100"],
    comparator: "number_equal",
    hint: "$B'(x) = -2x + 40$ s'annule en $20$ : calcule $B(20)$.",
    explanation: exp(
      "Le bénéfice est maximal là où sa dérivée s'annule en passant de $+$ à $-$.",
      "$B'(x) = -2x + 40 = 0 \\Leftrightarrow x = 20$ objets. Puis $B(20) = -400 + 800 - 300$.",
      "$= 100$.",
      "Le bénéfice maximal est de $100$ € (pour $20$ objets vendus)."
    ),
    tags: ["premiere", "maths", "variations", "extremum", "short"],
  },
  {
    kind: "template",
    id: "premiere_var_ext_tpl_1",
    niveau: "premiere-spe",
    matiere: "maths",
    notionId: "variations_fonctions",
    microId: "var_extremum",
    difficulty: 3,
    theme: "neutral",
    hint: "Abscisse de l'extremum : $f'(x) = 0$.",
    tags: ["premiere", "maths", "variations", "extremum", "template"],
    generate: () => {
      const alpha = randomInt(1, 5);
      const b = -2 * alpha;
      const c = randomInt(0, 6);
      return {
        text: `Pour $f(x) = x^2 ${b >= 0 ? "+ " + b : "- " + -b}x + ${c}$, en quelle abscisse $f$ atteint-elle son minimum ?`,
        format: "short",
        expected: [String(alpha)],
        comparator: "number_equal",
        explanation: exp(
          "Le minimum est atteint là où $f'(x) = 0$.",
          `$f'(x) = 2x ${b >= 0 ? "+ " + b : "- " + -b}$, qui s'annule en $x = ${alpha}$.`,
          "$f'$ passe de $-$ à $+$ : c'est un minimum.",
          `Minimum en $x = ${alpha}$.`
        ),
      };
    },
  },
  {
    kind: "template",
    id: "premiere_var_ext_tpl_2",
    niveau: "premiere-spe",
    matiere: "maths",
    notionId: "variations_fonctions",
    microId: "var_extremum",
    difficulty: 4,
    theme: "neutral",
    hint: "Valeur du minimum $= f(\\alpha)$.",
    tags: ["premiere", "maths", "variations", "extremum", "template"],
    generate: () => {
      const alpha = randomInt(1, 4);
      const b = -2 * alpha;
      const c = randomInt(0, 6);
      const minVal = alpha * alpha + b * alpha + c;
      return {
        text: `Pour $f(x) = x^2 ${b >= 0 ? "+ " + b : "- " + -b}x + ${c}$, quelle est la valeur du minimum ?`,
        format: "short",
        expected: [String(minVal)],
        comparator: "number_equal",
        explanation: exp(
          "Le minimum vaut $f(\\alpha)$ avec $\\alpha = ${alpha}$.".replace("${alpha}", String(alpha)),
          `$f(${alpha}) = ${alpha}^2 ${b >= 0 ? "+ " + b : "- " + -b} \\times ${alpha} + ${c}$.`,
          `$= ${minVal}$.`,
          `Le minimum vaut $${minVal}$.`
        ),
      };
    },
  },

  /* ===================== VAR_OPTIMISATION ===================== */
  {
    kind: "fixed",
    id: "premiere_var_opt_fixed_1",
    niveau: "premiere-spe",
    matiere: "maths",
    notionId: "variations_fonctions",
    microId: "var_optimisation",
    difficulty: 3,
    theme: "neutral",
    text: "Pour optimiser une grandeur modélisée par une fonction dérivable, on cherche :",
    format: "qcm",
    choices: [
      "où la dérivée s'annule",
      "où la fonction s'annule",
      "l'ordonnée à l'origine",
      "les asymptotes",
    ],
    expected: ["où la dérivée s'annule"],
    comparator: "mcq_exact",
    hint: "Maximum/minimum ↔ dérivée nulle.",
    explanation: exp(
      "Optimiser, c'est chercher un maximum ou un minimum.",
      "Ces extremums sont là où la dérivée s'annule en changeant de signe.",
      "On étudie donc le signe de la dérivée.",
      "Où la dérivée s'annule."
    ),
    tags: ["premiere", "maths", "variations", "optimisation", "qcm"],
  },
  {
    kind: "fixed",
    id: "premiere_var_opt_fixed_2",
    niveau: "premiere-spe",
    matiere: "maths",
    notionId: "variations_fonctions",
    microId: "var_optimisation",
    difficulty: 4,
    theme: "neutral",
    text: "L'aire d'un rectangle est $A(x) = x(10 - x)$ (un potager partagé). Pour quelle valeur de $x$ l'aire est-elle maximale ?",
    format: "short",
    expected: ["5"],
    comparator: "number_equal",
    hint: "$A(x) = 10x - x^2$, $A'(x) = 10 - 2x$.",
    explanation: exp(
      "On dérive l'aire et on cherche où la dérivée s'annule.",
      "$A(x) = 10x - x^2$, donc $A'(x) = 10 - 2x$.",
      "$A'(x) = 0 \\Leftrightarrow x = 5$ (maximum).",
      "L'aire est maximale pour $x = 5$."
    ),
    tags: ["premiere", "maths", "variations", "optimisation", "short"],
  },
  {
    kind: "fixed",
    id: "premiere_var_opt_fixed_3",
    niveau: "premiere-spe",
    matiere: "maths",
    notionId: "variations_fonctions",
    microId: "var_optimisation",
    difficulty: 4,
    theme: "neutral",
    text: "Avec $A(x) = x(10 - x)$, quelle est l'aire maximale du potager ?",
    format: "short",
    expected: ["25"],
    comparator: "number_equal",
    hint: "Calcule $A(5)$.",
    explanation: exp(
      "L'aire maximale est $A$ en l'abscisse optimale.",
      "$A(5) = 5 \\times (10 - 5) = 5 \\times 5$.",
      "$= 25$.",
      "L'aire maximale vaut $25$."
    ),
    tags: ["premiere", "maths", "variations", "optimisation", "short"],
  },
  {
    kind: "fixed",
    id: "premiere_var_opt_fixed_4",
    niveau: "premiere-spe",
    matiere: "maths",
    notionId: "variations_fonctions",
    microId: "var_optimisation",
    difficulty: 3,
    theme: "sport",
    text: "La hauteur d'un ballon est $h(t) = -5t^2 + 20t$. À quel instant atteint-il sa hauteur maximale ?",
    format: "short",
    expected: ["2"],
    comparator: "number_equal",
    hint: "$h'(t) = -10t + 20 = 0$.",
    explanation: exp(
      "La hauteur est maximale là où $h'(t) = 0$.",
      "$h'(t) = -10t + 20$, donc $-10t + 20 = 0 \\Leftrightarrow t = 2$.",
      "$h'$ passe de $+$ à $-$ : c'est bien un maximum.",
      "Hauteur maximale à $t = 2$ s."
    ),
    tags: ["premiere", "maths", "variations", "optimisation", "short"],
  },
  {
    kind: "fixed",
    id: "premiere_var_opt_fixed_5",
    niveau: "premiere-spe",
    matiere: "maths",
    notionId: "variations_fonctions",
    microId: "var_optimisation",
    difficulty: 5,
    theme: "neutral",
    text: "Un enclos rectangulaire est adossé à un mur : on dispose de $60$ m de grillage pour les trois autres côtés. Si $x$ est la largeur, l'aire vaut $A(x) = x(60 - 2x)$. Pour quelle largeur l'aire est-elle maximale ?",
    format: "short",
    expected: ["15"],
    comparator: "number_equal",
    hint: "Développe : $A(x) = 60x - 2x^2$, puis résous $A'(x) = 0$.",
    explanation: exp(
      "L'aire est maximale là où sa dérivée s'annule en changeant de signe.",
      "$A(x) = 60x - 2x^2$, donc $A'(x) = 60 - 4x$.",
      "$60 - 4x = 0 \\Leftrightarrow x = 15$. $A'$ passe de $+$ à $-$ : c'est bien un maximum.",
      "La largeur optimale est $x = 15$ m."
    ),
    tags: ["premiere", "maths", "variations", "optimisation", "short"],
  },
  {
    kind: "fixed",
    id: "premiere_var_opt_fixed_6",
    niveau: "premiere-spe",
    matiere: "maths",
    notionId: "variations_fonctions",
    microId: "var_optimisation",
    difficulty: 5,
    theme: "neutral",
    text: "Avec $A(x) = x(60 - 2x)$ et une largeur optimale de $15$ m, quelle est l'aire maximale de l'enclos, en m² ?",
    format: "short",
    expected: ["450"],
    comparator: "number_equal",
    hint: "Calcule $A(15) = 15 \\times (60 - 30)$.",
    explanation: exp(
      "Une fois la valeur optimale trouvée, on calcule son image pour obtenir le maximum.",
      "$A(15) = 15 \\times (60 - 2 \\times 15) = 15 \\times 30$.",
      "$= 450$. L'enclos mesure alors $15$ m sur $30$ m.",
      "L'aire maximale est de $450$ m²."
    ),
    tags: ["premiere", "maths", "variations", "optimisation", "short"],
  },
  {
    kind: "fixed",
    id: "premiere_var_opt_fixed_7",
    niveau: "premiere-spe",
    matiere: "maths",
    notionId: "variations_fonctions",
    microId: "var_optimisation",
    difficulty: 4,
    theme: "sport",
    text: "La hauteur d'un ballon est $h(t) = -5t^2 + 20t$ (en mètres). Quelle est sa hauteur maximale ?",
    format: "short",
    expected: ["20"],
    comparator: "number_equal",
    hint: "Le maximum est atteint à $t = 2$ : calcule $h(2)$.",
    explanation: exp(
      "L'instant du maximum se trouve avec $h'(t) = 0$ ; la HAUTEUR maximale est l'image de cet instant.",
      "$h'(t) = -10t + 20$ s'annule en $t = 2$. Puis $h(2) = -5 \\times 4 + 20 \\times 2$.",
      "$= -20 + 40 = 20$.",
      "La hauteur maximale est de $20$ m, atteinte au bout de $2$ s."
    ),
    tags: ["premiere", "maths", "variations", "optimisation", "short"],
  },
  {
    kind: "fixed",
    id: "premiere_var_opt_fixed_8",
    niveau: "premiere-spe",
    matiere: "maths",
    notionId: "variations_fonctions",
    microId: "var_optimisation",
    difficulty: 4,
    theme: "neutral",
    text: "Après avoir trouvé une valeur $x_0$ telle que $f'(x_0) = 0$, que faut-il faire pour conclure à un maximum ?",
    format: "qcm",
    choices: [
      "vérifier que $f'$ passe du positif au négatif en $x_0$",
      "vérifier que $f(x_0) > 0$",
      "rien : $f'(x_0) = 0$ suffit toujours",
      "calculer $f(0)$",
    ],
    expected: ["vérifier que $f'$ passe du positif au négatif en $x_0$"],
    comparator: "mcq_exact",
    hint: "Une dérivée nulle peut aussi donner un minimum, ou rien du tout.",
    explanation: exp(
      "Annuler la dérivée ne suffit pas : cela signale un candidat, pas un maximum.",
      "Il faut étudier le SIGNE de $f'$ autour de $x_0$ : de $+$ à $-$ donne un maximum, de $-$ à $+$ un minimum.",
      "Si le signe ne change pas (comme pour $x^3$ en $0$), il n'y a aucun extremum.",
      "Il faut vérifier que $f'$ passe du positif au négatif en $x_0$."
    ),
    tags: ["premiere", "maths", "variations", "optimisation", "qcm"],
  },
  {
    kind: "fixed",
    id: "premiere_var_opt_fixed_9",
    niveau: "premiere-spe",
    matiere: "maths",
    notionId: "variations_fonctions",
    microId: "var_optimisation",
    difficulty: 4,
    theme: "reunion",
    text: "Un loueur de kayaks à Saint-Gilles estime sa recette journalière à $R(x) = x(50 - x)$ euros, où $x$ est le prix d'une sortie. Quel prix rend la recette maximale ?",
    format: "short",
    expected: ["25"],
    comparator: "number_equal",
    hint: "$R(x) = 50x - x^2$ : résous $R'(x) = 0$.",
    explanation: exp(
      "La recette est maximale là où sa dérivée s'annule en changeant de signe.",
      "$R(x) = 50x - x^2$, donc $R'(x) = 50 - 2x$.",
      "$50 - 2x = 0 \\Leftrightarrow x = 25$. Au-delà, augmenter le prix fait fuir trop de clients : la recette baisse.",
      "Le prix optimal est de $25$ €."
    ),
    tags: ["premiere", "maths", "variations", "optimisation", "short"],
  },
  {
    kind: "fixed",
    id: "premiere_var_opt_fixed_10",
    niveau: "premiere-spe",
    matiere: "maths",
    notionId: "variations_fonctions",
    microId: "var_optimisation",
    difficulty: 4,
    theme: "reunion",
    text: "Avec $R(x) = x(50 - x)$ et un prix optimal de $25$ €, quelle est la recette maximale, en euros ?",
    format: "short",
    expected: ["625"],
    comparator: "number_equal",
    hint: "$R(25) = 25 \\times (50 - 25)$.",
    explanation: exp(
      "On calcule l'image du prix optimal.",
      "$R(25) = 25 \\times (50 - 25) = 25 \\times 25$.",
      "$= 625$.",
      "La recette maximale est de $625$ €."
    ),
    tags: ["premiere", "maths", "variations", "optimisation", "short"],
  },
  {
    kind: "fixed",
    id: "premiere_var_opt_fixed_11",
    niveau: "premiere-spe",
    matiere: "maths",
    notionId: "variations_fonctions",
    microId: "var_optimisation",
    difficulty: 5,
    theme: "neutral",
    text: "L'aire d'un rectangle est $A(x) = x(10 - x)$, où $x$ est une longueur en cm. Sur quel intervalle l'étude a-t-elle un sens ?",
    format: "qcm",
    choices: ["$]0 ; 10[$", "$\\mathbb{R}$", "$[0 ; 5]$", "$]-\\infty ; 10]$"],
    expected: ["$]0 ; 10[$"],
    comparator: "mcq_exact",
    hint: "Les deux côtés, $x$ et $10 - x$, doivent être des longueurs strictement positives.",
    explanation: exp(
      "Dans un problème d'optimisation, il faut d'abord fixer l'intervalle d'étude imposé par la situation.",
      "Les deux dimensions doivent être positives : $x > 0$ ET $10 - x > 0$, donc $x < 10$.",
      "L'étude se mène donc sur $]0 ; 10[$ : en dehors, l'aire n'a plus de sens géométrique (elle deviendrait négative).",
      "L'intervalle est $]0 ; 10[$."
    ),
    tags: ["premiere", "maths", "variations", "optimisation", "qcm"],
  },
  {
    kind: "template",
    id: "premiere_var_opt_tpl_1",
    niveau: "premiere-spe",
    matiere: "maths",
    notionId: "variations_fonctions",
    microId: "var_optimisation",
    difficulty: 4,
    theme: "neutral",
    hint: "Aire $x(L - x)$ : maximale au milieu.",
    tags: ["premiere", "maths", "variations", "optimisation", "template"],
    generate: () => {
      const demi = randomInt(3, 8);
      const L = 2 * demi;
      return {
        text: `L'aire d'un rectangle de demi-périmètre $${L}$ est $A(x) = x(${L} - x)$. Pour quelle valeur de $x$ l'aire est-elle maximale ?`,
        format: "short",
        expected: [String(demi)],
        comparator: "number_equal",
        explanation: exp(
          "On dérive : $A(x) = ${L}x - x^2$, $A'(x) = ${L} - 2x$.".replace(/\$\{L\}/g, String(L)),
          `$A'(x) = 0 \\Leftrightarrow x = ${demi}$.`,
          "C'est un maximum (carré de côté optimal).",
          `L'aire est maximale pour $x = ${demi}$.`
        ),
      };
    },
  },
];
