// lib/tutor-v4/questionBank/premiere-spe/maths/variables-aleatoires.bank.ts
//
// Chapitre : Variables aléatoires réelles (notion "variables_aleatoires")
// microSkills :
//   va_loi       — déterminer la loi de probabilité
//   va_esperance — calculer une espérance
//   va_variance  — calculer une variance et un écart-type
//   va_notation  — interpréter les notations {X = a}, P(X ⩽ a)
//
// PÉRIMÈTRE BO 2019 Première spé. Conventions : LaTeX, règle QCM. Canvas : stat_graph (loi en bâtons).

import type { TutorBankItemV4, CanvasFigure } from "@/lib/tutor-v4/types";

function randomInt(min: number, max: number) {
  return Math.floor(Math.random() * (max - min + 1)) + min;
}

function exp(definition: string, methode: string, calcul: string, conclusion: string) {
  return (
    `Définition : ${definition}\n\n` +
    `Méthode : ${methode}\n\n` +
    `Calcul / Observation : ${calcul}\n\n` +
    `Conclusion : ${conclusion}`
  );
}

function loiGraph(valeurs: number[], probas: number[]): CanvasFigure {
  return {
    kind: "stat_graph",
    graphType: "batons",
    title: "Loi de probabilité de X",
    size: { width: 320, height: 240 },
    data: valeurs.map((v, i) => ({ label: String(v), value: probas[i] })),
    display: { showValues: true, showLabels: true },
  };
}

export const variablesAleatoiresBank: TutorBankItemV4[] = [
  /* ===================== VA_LOI ===================== */
  {
    kind: "fixed",
    id: "premiere_va_loi_fixed_1",
    niveau: "premiere-spe",
    matiere: "maths",
    notionId: "variables_aleatoires",
    microId: "va_loi",
    difficulty: 2,
    theme: "neutral",
    text: "Pour une loi de probabilité, la somme de toutes les probabilités vaut :",
    format: "short",
    expected: ["1"],
    comparator: "number_equal",
    hint: "Toutes les valeurs possibles sont couvertes.",
    explanation: exp(
      "La loi d'une variable aléatoire associe une probabilité à chaque valeur.",
      "Toutes les valeurs possibles couvrent tout l'univers.",
      "La somme des probabilités vaut donc $1$.",
      "La somme vaut $1$."
    ),
    tags: ["premiere", "maths", "variables_aleatoires", "loi", "short"],
  },
  {
    kind: "fixed",
    id: "premiere_va_loi_fixed_2",
    niveau: "premiere-spe",
    matiere: "maths",
    notionId: "variables_aleatoires",
    microId: "va_loi",
    difficulty: 3,
    theme: "neutral",
    text: "$X$ prend les valeurs $0$, $1$, $2$ avec $P(X=0) = 0{,}3$ et $P(X=1) = 0{,}5$. Combien vaut $P(X=2)$ ?",
    format: "short",
    expected: ["0,2"],
    comparator: "number_equal",
    hint: "La somme des probabilités vaut $1$.",
    explanation: exp(
      "La somme des probabilités d'une loi vaut $1$.",
      "$P(X=2) = 1 - 0{,}3 - 0{,}5$.",
      "$= 0{,}2$.",
      "$P(X=2) = 0{,}2$."
    ),
    canvas: loiGraph([0, 1, 2], [0.3, 0.5, 0.2]),
    tags: ["premiere", "maths", "variables_aleatoires", "loi", "canvas", "short"],
  },
  {
    kind: "fixed",
    id: "premiere_va_loi_fixed_3",
    niveau: "premiere-spe",
    matiere: "maths",
    notionId: "variables_aleatoires",
    microId: "va_loi",
    difficulty: 3,
    theme: "jeux_video",
    text: "Dans un jeu, le gain $X$ vaut $0$, $5$ ou $10$ avec $P(X=0) = 0{,}6$ et $P(X=5) = 0{,}3$. Combien vaut $P(X=10)$ ?",
    format: "short",
    expected: ["0,1"],
    comparator: "number_equal",
    hint: "Somme $= 1$.",
    explanation: exp(
      "La somme des probabilités vaut $1$.",
      "$P(X=10) = 1 - 0{,}6 - 0{,}3$.",
      "$= 0{,}1$.",
      "$P(X=10) = 0{,}1$."
    ),
    canvas: loiGraph([0, 5, 10], [0.6, 0.3, 0.1]),
    tags: ["premiere", "maths", "variables_aleatoires", "loi", "canvas", "short"],
  },
  {
    kind: "fixed",
    id: "premiere_va_loi_fixed_4",
    niveau: "premiere-spe",
    matiere: "maths",
    notionId: "variables_aleatoires",
    microId: "va_loi",
    difficulty: 3,
    theme: "neutral",
    text: "On lance un dé équilibré et $X$ est le résultat. Combien vaut $P(X = 4)$ ?",
    format: "qcm",
    choices: ["$\\dfrac{1}{6}$", "$\\dfrac{1}{4}$", "$\\dfrac{4}{6}$", "$\\dfrac{1}{2}$"],
    expected: ["$\\dfrac{1}{6}$"],
    comparator: "mcq_exact",
    hint: "Dé à $6$ faces équilibré.",
    explanation: exp(
      "Le dé a $6$ faces équiprobables.",
      "Chaque valeur a la même probabilité $\\dfrac{1}{6}$.",
      "$P(X=4) = \\dfrac{1}{6}$.",
      "$\\dfrac{1}{6}$."
    ),
    tags: ["premiere", "maths", "variables_aleatoires", "loi", "qcm"],
  },
  {
    kind: "fixed",
    id: "premiere_va_loi_fixed_5",
    niveau: "premiere-spe",
    matiere: "maths",
    notionId: "variables_aleatoires",
    microId: "va_loi",
    difficulty: 4,
    theme: "neutral",
    text: "$X$ prend les valeurs $0$, $1$, $2$, $3$ avec $P(X=0) = 0{,}1$, $P(X=1) = 0{,}2$ et $P(X=2) = 0{,}4$. Combien vaut $P(X=3)$ ?",
    format: "short",
    expected: ["0,3"],
    comparator: "number_equal",
    hint: "La somme de toutes les probabilités vaut $1$.",
    explanation: exp(
      "Dans une loi de probabilité, la somme des probabilités de toutes les valeurs vaut $1$.",
      "$0{,}1 + 0{,}2 + 0{,}4 = 0{,}7$, il manque donc $1 - 0{,}7$.",
      "$P(X=3) = 0{,}3$.",
      "$P(X=3) = 0{,}3$."
    ),
    tags: ["premiere", "maths", "variables_aleatoires", "loi", "short"],
  },
  {
    kind: "fixed",
    id: "premiere_va_loi_fixed_6",
    niveau: "premiere-spe",
    matiere: "maths",
    notionId: "variables_aleatoires",
    microId: "va_loi",
    difficulty: 5,
    theme: "neutral",
    text: "On lance deux fois une pièce équilibrée et $X$ compte le nombre de PILE. Combien vaut $P(X = 0)$ ?",
    format: "short",
    expected: ["0,25"],
    comparator: "number_equal",
    hint: "$X = 0$ signifie « FACE puis FACE ».",
    explanation: exp(
      "On liste les issues équiprobables : PP, PF, FP, FF — quatre cas.",
      "$X = 0$ correspond au seul cas FF : $\\dfrac{1}{4}$.",
      "$= 0{,}25$. (On peut aussi multiplier : $0{,}5 \\times 0{,}5$, les lancers étant indépendants.)",
      "$P(X = 0) = 0{,}25$."
    ),
    tags: ["premiere", "maths", "variables_aleatoires", "loi", "short"],
  },
  {
    kind: "fixed",
    id: "premiere_va_loi_fixed_7",
    niveau: "premiere-spe",
    matiere: "maths",
    notionId: "variables_aleatoires",
    microId: "va_loi",
    difficulty: 4,
    theme: "neutral",
    text: "Peut-on avoir une variable aléatoire prenant seulement les valeurs $1$ et $2$, avec $P(X=1) = 0{,}5$ et $P(X=2) = 0{,}6$ ?",
    format: "qcm",
    choices: [
      "non : la somme dépasse $1$",
      "oui, c'est une loi valable",
      "non : les probabilités doivent être égales",
      "oui, si $X$ prend d'autres valeurs",
    ],
    expected: ["non : la somme dépasse $1$"],
    comparator: "mcq_exact",
    hint: "Additionne les deux probabilités.",
    explanation: exp(
      "Pour définir une loi, il faut que toutes les probabilités soient dans $[0 ; 1]$ ET que leur somme fasse exactement $1$.",
      "Ici $0{,}5 + 0{,}6 = 1{,}1 > 1$.",
      "C'est impossible : $X$ ne prenant que ces deux valeurs, la somme devrait valoir $1$. Ajouter d'autres valeurs ne ferait qu'aggraver le dépassement.",
      "Non : la somme dépasse $1$."
    ),
    tags: ["premiere", "maths", "variables_aleatoires", "loi", "qcm"],
  },
  {
    kind: "fixed",
    id: "premiere_va_loi_fixed_8",
    niveau: "premiere-spe",
    matiere: "maths",
    notionId: "variables_aleatoires",
    microId: "va_loi",
    difficulty: 3,
    theme: "neutral",
    text: "Qu'est-ce qu'une variable aléatoire ?",
    format: "qcm",
    choices: [
      "une fonction qui associe un nombre à chaque issue de l'expérience",
      "une probabilité comprise entre $0$ et $1$",
      "un nombre tiré au hasard entre $0$ et $1$",
      "l'ensemble de toutes les issues possibles",
    ],
    expected: [
      "une fonction qui associe un nombre à chaque issue de l'expérience",
    ],
    comparator: "mcq_exact",
    hint: "Elle traduit chaque résultat de l'expérience en un nombre.",
    explanation: exp(
      "Une variable aléatoire traduit le résultat d'une expérience en une valeur numérique.",
      "Exemple : on lance deux dés (l'issue est un couple de faces) et $X$ donne la somme obtenue.",
      "Elle n'est donc pas une probabilité : c'est une fonction définie sur l'univers, à valeurs dans les nombres.",
      "C'est une fonction qui associe un nombre à chaque issue."
    ),
    tags: ["premiere", "maths", "variables_aleatoires", "loi", "qcm"],
  },
  {
    kind: "fixed",
    id: "premiere_va_loi_fixed_9",
    niveau: "premiere-spe",
    matiere: "maths",
    notionId: "variables_aleatoires",
    microId: "va_loi",
    difficulty: 3,
    theme: "neutral",
    text: "Une urne contient $5$ boules dont $2$ gagnantes. $X$ vaut $1$ si la boule tirée est gagnante, $0$ sinon. Combien vaut $P(X = 1)$ ?",
    format: "short",
    expected: ["0,4"],
    comparator: "number_equal",
    hint: "$\\dfrac{2}{5}$.",
    explanation: exp(
      "On compte les cas favorables sur le nombre total de cas, les tirages étant équiprobables.",
      "$P(X = 1) = \\dfrac{2}{5}$.",
      "$= 0{,}4$. On en déduit $P(X = 0) = 0{,}6$, et la somme vaut bien $1$.",
      "$P(X = 1) = 0{,}4$."
    ),
    tags: ["premiere", "maths", "variables_aleatoires", "loi", "short"],
  },
  {
    kind: "fixed",
    id: "premiere_va_loi_fixed_10",
    niveau: "premiere-spe",
    matiere: "maths",
    notionId: "variables_aleatoires",
    microId: "va_loi",
    difficulty: 4,
    theme: "neutral",
    text: "On lance un dé équilibré. $X$ vaut $10$ si on obtient $6$, et $0$ sinon. Combien vaut $P(X = 0)$ ?",
    format: "qcm",
    choices: [
      "$\\dfrac{5}{6}$",
      "$\\dfrac{1}{6}$",
      "$0$",
      "$\\dfrac{1}{2}$",
    ],
    expected: ["$\\dfrac{5}{6}$"],
    comparator: "mcq_exact",
    hint: "Combien de faces ne donnent pas $6$ ?",
    explanation: exp(
      "$X = 0$ correspond à toutes les issues sauf le $6$.",
      "Cinq faces sur six conviennent : $\\dfrac{5}{6}$.",
      "On peut aussi passer par l'événement contraire : $1 - \\dfrac{1}{6} = \\dfrac{5}{6}$.",
      "$P(X = 0) = \\dfrac{5}{6}$."
    ),
    tags: ["premiere", "maths", "variables_aleatoires", "loi", "qcm"],
  },
  {
    kind: "fixed",
    id: "premiere_va_loi_fixed_11",
    niveau: "premiere-spe",
    matiere: "maths",
    notionId: "variables_aleatoires",
    microId: "va_loi",
    difficulty: 3,
    theme: "neutral",
    text: "Que signifie « donner la loi de probabilité de $X$ » ?",
    format: "qcm",
    choices: [
      "donner toutes les valeurs possibles de $X$ et leur probabilité",
      "donner uniquement l'espérance de $X$",
      "donner la plus grande valeur de $X$",
      "donner la formule de $X$",
    ],
    expected: [
      "donner toutes les valeurs possibles de $X$ et leur probabilité",
    ],
    comparator: "mcq_exact",
    hint: "C'est ce qu'on présente en général dans un tableau à deux lignes.",
    explanation: exp(
      "La loi de probabilité décrit complètement le comportement de $X$.",
      "On liste toutes les valeurs $x_i$ que $X$ peut prendre, et pour chacune la probabilité $P(X = x_i)$.",
      "On la présente souvent dans un tableau, dont la ligne des probabilités a pour somme $1$. L'espérance se calcule ENSUITE, à partir de cette loi.",
      "C'est donner toutes les valeurs possibles de $X$ et leur probabilité."
    ),
    tags: ["premiere", "maths", "variables_aleatoires", "loi", "qcm"],
  },
  {
    kind: "template",
    id: "premiere_va_loi_tpl_1",
    niveau: "premiere-spe",
    matiere: "maths",
    notionId: "variables_aleatoires",
    microId: "va_loi",
    difficulty: 3,
    theme: "neutral",
    hint: "La somme des probabilités vaut $1$.",
    tags: ["premiere", "maths", "variables_aleatoires", "loi", "template"],
    generate: () => {
      const p0 = randomInt(1, 5) / 10;
      const p1 = randomInt(1, 9 - p0 * 10) / 10;
      const p2 = Math.round((1 - p0 - p1) * 10) / 10;
      return {
        text: `$X$ prend les valeurs $0$, $1$, $2$ avec $P(X=0) = ${String(p0).replace(".", ",")}$ et $P(X=1) = ${String(p1).replace(".", ",")}$. Combien vaut $P(X=2)$ ?`,
        format: "short",
        expected: [String(p2).replace(".", ",")],
        comparator: "number_equal",
        canvas: loiGraph([0, 1, 2], [p0, p1, p2]),
        explanation: exp(
          "La somme des probabilités vaut $1$.",
          `$P(X=2) = 1 - ${String(p0).replace(".", ",")} - ${String(p1).replace(".", ",")}$.`,
          `$= ${String(p2).replace(".", ",")}$.`,
          `$P(X=2) = ${String(p2).replace(".", ",")}$.`
        ),
      };
    },
  },

  /* ===================== VA_ESPERANCE ===================== */
  {
    kind: "fixed",
    id: "premiere_va_esp_fixed_1",
    niveau: "premiere-spe",
    matiere: "maths",
    notionId: "variables_aleatoires",
    microId: "va_esperance",
    difficulty: 2,
    theme: "neutral",
    text: "L'espérance d'une variable aléatoire $X$ se calcule par :",
    format: "qcm",
    choices: [
      "$E(X) = \\sum x_i \\, p_i$",
      "$E(X) = \\sum p_i$",
      "$E(X) = \\sum x_i$",
      "$E(X) = \\dfrac{\\sum x_i}{n}$",
    ],
    expected: ["$E(X) = \\sum x_i \\, p_i$"],
    comparator: "mcq_exact",
    hint: "Somme des valeurs pondérées par leurs probabilités.",
    explanation: exp(
      "L'espérance est une moyenne pondérée des valeurs.",
      "Chaque valeur $x_i$ est pondérée par sa probabilité $p_i$.",
      "$E(X) = \\sum x_i \\, p_i$.",
      "$E(X) = \\sum x_i \\, p_i$."
    ),
    tags: ["premiere", "maths", "variables_aleatoires", "esperance", "qcm"],
  },
  {
    kind: "fixed",
    id: "premiere_va_esp_fixed_2",
    niveau: "premiere-spe",
    matiere: "maths",
    notionId: "variables_aleatoires",
    microId: "va_esperance",
    difficulty: 3,
    theme: "neutral",
    text: "$X$ vaut $0$, $1$, $2$ avec probabilités $0{,}3$, $0{,}5$, $0{,}2$. Calcule $E(X)$.",
    format: "short",
    expected: ["0,9"],
    comparator: "number_equal",
    hint: "$0 \\times 0{,}3 + 1 \\times 0{,}5 + 2 \\times 0{,}2$.",
    explanation: exp(
      "On applique $E(X) = \\sum x_i \\, p_i$.",
      "$0 \\times 0{,}3 + 1 \\times 0{,}5 + 2 \\times 0{,}2 = 0 + 0{,}5 + 0{,}4$.",
      "$= 0{,}9$.",
      "$E(X) = 0{,}9$."
    ),
    canvas: loiGraph([0, 1, 2], [0.3, 0.5, 0.2]),
    tags: ["premiere", "maths", "variables_aleatoires", "esperance", "canvas", "short"],
  },
  {
    kind: "fixed",
    id: "premiere_va_esp_fixed_3",
    niveau: "premiere-spe",
    matiere: "maths",
    notionId: "variables_aleatoires",
    microId: "va_esperance",
    difficulty: 4,
    theme: "jeux_video",
    text: "Un jeu coûte $2$ €. Le gain $X$ (déjà net) vaut $0$ € (proba $0{,}7$) ou $5$ € (proba $0{,}3$). Quelle est l'espérance de gain $E(X)$ ?",
    format: "short",
    expected: ["1,5"],
    comparator: "number_equal",
    hint: "$0 \\times 0{,}7 + 5 \\times 0{,}3$.",
    explanation: exp(
      "On calcule l'espérance du gain.",
      "$E(X) = 0 \\times 0{,}7 + 5 \\times 0{,}3$.",
      "$= 1{,}5$.",
      "$E(X) = 1{,}5$ € (le jeu coûtant $2$ €, il n'est pas favorable au joueur)."
    ),
    canvas: loiGraph([0, 5], [0.7, 0.3]),
    tags: ["premiere", "maths", "variables_aleatoires", "esperance", "canvas", "short"],
  },
  {
    kind: "fixed",
    id: "premiere_va_esp_fixed_4",
    niveau: "premiere-spe",
    matiere: "maths",
    notionId: "variables_aleatoires",
    microId: "va_esperance",
    difficulty: 3,
    theme: "neutral",
    text: "Un jeu est dit « équitable » lorsque l'espérance de gain (mise déduite) vaut :",
    format: "short",
    expected: ["0"],
    comparator: "number_equal",
    hint: "Ni favorable, ni défavorable.",
    explanation: exp(
      "Un jeu équitable n'avantage ni le joueur ni l'organisateur.",
      "Le gain moyen (mise déduite) est alors nul.",
      "$E(X) = 0$.",
      "L'espérance vaut $0$."
    ),
    tags: ["premiere", "maths", "variables_aleatoires", "esperance", "short"],
  },
  {
    kind: "fixed",
    id: "premiere_va_esp_fixed_5",
    niveau: "premiere-spe",
    matiere: "maths",
    notionId: "variables_aleatoires",
    microId: "va_esperance",
    difficulty: 4,
    theme: "neutral",
    text: "$X$ vaut $1$, $2$ ou $3$ avec les probabilités $0{,}2$, $0{,}5$ et $0{,}3$. Calcule $E(X)$.",
    format: "short",
    expected: ["2,1"],
    comparator: "number_equal",
    hint: "$1 \\times 0{,}2 + 2 \\times 0{,}5 + 3 \\times 0{,}3$.",
    explanation: exp(
      "L'espérance est la somme des valeurs multipliées par leurs probabilités : $E(X) = \\sum x_i p_i$.",
      "$1 \\times 0{,}2 + 2 \\times 0{,}5 + 3 \\times 0{,}3 = 0{,}2 + 1 + 0{,}9$.",
      "$= 2{,}1$.",
      "$E(X) = 2{,}1$."
    ),
    tags: ["premiere", "maths", "variables_aleatoires", "esperance", "short"],
  },
  {
    kind: "fixed",
    id: "premiere_va_esp_fixed_6",
    niveau: "premiere-spe",
    matiere: "maths",
    notionId: "variables_aleatoires",
    microId: "va_esperance",
    difficulty: 5,
    theme: "neutral",
    text: "$X$ vaut $-1$, $0$ ou $4$ avec les probabilités $0{,}5$, $0{,}3$ et $0{,}2$. Calcule $E(X)$.",
    format: "short",
    expected: ["0,3"],
    comparator: "number_equal",
    hint: "Attention au terme négatif : $-1 \\times 0{,}5 = -0{,}5$.",
    explanation: exp(
      "On applique $E(X) = \\sum x_i p_i$, valeurs négatives comprises.",
      "$(-1) \\times 0{,}5 + 0 \\times 0{,}3 + 4 \\times 0{,}2 = -0{,}5 + 0 + 0{,}8$.",
      "$= 0{,}3$.",
      "$E(X) = 0{,}3$."
    ),
    tags: ["premiere", "maths", "variables_aleatoires", "esperance", "short"],
  },
  {
    kind: "fixed",
    id: "premiere_va_esp_fixed_7",
    niveau: "premiere-spe",
    matiere: "maths",
    notionId: "variables_aleatoires",
    microId: "va_esperance",
    difficulty: 5,
    theme: "neutral",
    text: "On lance un dé équilibré et $X$ est le résultat. Combien vaut $E(X)$ ?",
    format: "short",
    expected: ["3,5"],
    comparator: "number_equal",
    hint: "$\\dfrac{1 + 2 + 3 + 4 + 5 + 6}{6}$.",
    explanation: exp(
      "Toutes les faces ayant la même probabilité $\\dfrac{1}{6}$, l'espérance est la moyenne des valeurs.",
      "$E(X) = \\dfrac{1 + 2 + 3 + 4 + 5 + 6}{6} = \\dfrac{21}{6}$.",
      "$= 3{,}5$.",
      "$E(X) = 3{,}5$ : l'espérance n'est pas forcément une valeur que $X$ peut prendre."
    ),
    tags: ["premiere", "maths", "variables_aleatoires", "esperance", "short"],
  },
  {
    kind: "fixed",
    id: "premiere_va_esp_fixed_8",
    niveau: "premiere-spe",
    matiere: "maths",
    notionId: "variables_aleatoires",
    microId: "va_esperance",
    difficulty: 3,
    theme: "neutral",
    text: "Que représente concrètement l'espérance $E(X)$ ?",
    format: "qcm",
    choices: [
      "la valeur moyenne de $X$ si on répète l'expérience un très grand nombre de fois",
      "la valeur la plus probable de $X$",
      "la plus grande valeur que $X$ peut prendre",
      "la probabilité que $X$ soit positif",
    ],
    expected: [
      "la valeur moyenne de $X$ si on répète l'expérience un très grand nombre de fois",
    ],
    comparator: "mcq_exact",
    hint: "C'est une moyenne, pondérée par les probabilités.",
    explanation: exp(
      "L'espérance est la moyenne des valeurs de $X$, chacune pesée par sa probabilité.",
      "Sur un très grand nombre de répétitions, la moyenne des résultats observés se rapproche de $E(X)$.",
      "Ce n'est pas la valeur la plus probable : pour un dé, $E(X) = 3{,}5$, une valeur que le dé ne donne jamais.",
      "C'est la valeur moyenne sur un très grand nombre de répétitions."
    ),
    tags: ["premiere", "maths", "variables_aleatoires", "esperance", "qcm"],
  },
  {
    kind: "fixed",
    id: "premiere_va_esp_fixed_9",
    niveau: "premiere-spe",
    matiere: "maths",
    notionId: "variables_aleatoires",
    microId: "va_esperance",
    difficulty: 5,
    theme: "neutral",
    text: "À un jeu, le gain NET $X$ vaut $-3$ € avec la probabilité $0{,}75$ et $7$ € avec la probabilité $0{,}25$. Calcule $E(X)$.",
    format: "short",
    expected: ["-0,5"],
    comparator: "number_equal",
    hint: "$(-3) \\times 0{,}75 + 7 \\times 0{,}25$.",
    explanation: exp(
      "Le gain net tient déjà compte de la mise : on applique directement $E(X) = \\sum x_i p_i$.",
      "$(-3) \\times 0{,}75 + 7 \\times 0{,}25 = -2{,}25 + 1{,}75$.",
      "$= -0{,}5$.",
      "$E(X) = -0{,}5$ € : le jeu est défavorable au joueur."
    ),
    tags: ["premiere", "maths", "variables_aleatoires", "esperance", "short"],
  },
  {
    kind: "fixed",
    id: "premiere_va_esp_fixed_10",
    niveau: "premiere-spe",
    matiere: "maths",
    notionId: "variables_aleatoires",
    microId: "va_esperance",
    difficulty: 4,
    theme: "neutral",
    text: "Un jeu a une espérance de gain de $-0{,}5$ € par partie. Quelle perte moyenne peut-on prévoir sur $100$ parties, en euros ?",
    format: "short",
    expected: ["50"],
    comparator: "number_equal",
    hint: "$100 \\times 0{,}5$.",
    explanation: exp(
      "L'espérance donne le gain moyen par partie : sur $n$ parties, on prévoit environ $n \\times E(X)$.",
      "$100 \\times (-0{,}5) = -50$.",
      "Le joueur perd donc en moyenne $50$ € sur $100$ parties.",
      "La perte moyenne prévisible est de $50$ €."
    ),
    tags: ["premiere", "maths", "variables_aleatoires", "esperance", "short"],
  },
  {
    kind: "fixed",
    id: "premiere_va_esp_fixed_11",
    niveau: "premiere-spe",
    matiere: "maths",
    notionId: "variables_aleatoires",
    microId: "va_esperance",
    difficulty: 3,
    theme: "neutral",
    text: "$X$ vaut $0$ avec la probabilité $0{,}9$ et $10$ avec la probabilité $0{,}1$. Calcule $E(X)$.",
    format: "short",
    expected: ["1"],
    comparator: "number_equal",
    hint: "$0 \\times 0{,}9 + 10 \\times 0{,}1$.",
    explanation: exp(
      "On applique $E(X) = \\sum x_i p_i$.",
      "$0 \\times 0{,}9 + 10 \\times 0{,}1 = 0 + 1$.",
      "$= 1$.",
      "$E(X) = 1$ : un gros gain rare peut donner une espérance modeste."
    ),
    tags: ["premiere", "maths", "variables_aleatoires", "esperance", "short"],
  },
  {
    kind: "template",
    id: "premiere_va_esp_tpl_1",
    niveau: "premiere-spe",
    matiere: "maths",
    notionId: "variables_aleatoires",
    microId: "va_esperance",
    difficulty: 3,
    theme: "neutral",
    hint: "$E(X) = \\sum x_i \\, p_i$.",
    tags: ["premiere", "maths", "variables_aleatoires", "esperance", "template"],
    generate: () => {
      const p0 = randomInt(1, 4) / 10;
      const p1 = randomInt(1, 4) / 10;
      const p2 = Math.round((1 - p0 - p1) * 10) / 10;
      const x = [randomInt(0, 2), randomInt(3, 5), randomInt(6, 9)];
      const esp = Math.round((x[0] * p0 + x[1] * p1 + x[2] * p2) * 100) / 100;
      return {
        text: `$X$ vaut $${x[0]}$, $${x[1]}$, $${x[2]}$ avec probabilités $${String(p0).replace(".", ",")}$, $${String(p1).replace(".", ",")}$, $${String(p2).replace(".", ",")}$. Calcule $E(X)$. (arrondir au centième)`,
        format: "short",
        expected: [String(esp).replace(".", ",")],
        comparator: "number_equal",
        canvas: loiGraph(x, [p0, p1, p2]),
        explanation: exp(
          "On applique $E(X) = \\sum x_i \\, p_i$.",
          `$${x[0]} \\times ${String(p0).replace(".", ",")} + ${x[1]} \\times ${String(p1).replace(".", ",")} + ${x[2]} \\times ${String(p2).replace(".", ",")}$.`,
          `$= ${String(esp).replace(".", ",")}$.`,
          `$E(X) = ${String(esp).replace(".", ",")}$.`
        ),
      };
    },
  },

  /* ===================== VA_VARIANCE ===================== */
  {
    kind: "fixed",
    id: "premiere_va_var_fixed_1",
    niveau: "premiere-spe",
    matiere: "maths",
    notionId: "variables_aleatoires",
    microId: "va_variance",
    difficulty: 3,
    theme: "neutral",
    text: "La variance d'une variable aléatoire mesure :",
    format: "qcm",
    choices: [
      "la dispersion autour de l'espérance",
      "la valeur la plus probable",
      "la somme des valeurs",
      "le nombre de valeurs",
    ],
    expected: ["la dispersion autour de l'espérance"],
    comparator: "mcq_exact",
    hint: "Écart par rapport à la moyenne.",
    explanation: exp(
      "La variance quantifie l'éloignement des valeurs par rapport à l'espérance.",
      "$V(X) = \\sum p_i (x_i - E(X))^2$.",
      "Plus elle est grande, plus les valeurs sont dispersées.",
      "La dispersion autour de l'espérance."
    ),
    tags: ["premiere", "maths", "variables_aleatoires", "variance", "qcm"],
  },
  {
    kind: "fixed",
    id: "premiere_va_var_fixed_2",
    niveau: "premiere-spe",
    matiere: "maths",
    notionId: "variables_aleatoires",
    microId: "va_variance",
    difficulty: 3,
    theme: "neutral",
    text: "L'écart-type $\\sigma(X)$ se déduit de la variance par :",
    format: "qcm",
    choices: ["$\\sigma(X) = \\sqrt{V(X)}$", "$\\sigma(X) = V(X)^2$", "$\\sigma(X) = V(X)$", "$\\sigma(X) = \\dfrac{V(X)}{2}$"],
    expected: ["$\\sigma(X) = \\sqrt{V(X)}$"],
    comparator: "mcq_exact",
    hint: "Racine carrée.",
    explanation: exp(
      "L'écart-type est la racine carrée de la variance.",
      "$\\sigma(X) = \\sqrt{V(X)}$.",
      "Il a la même unité que $X$.",
      "$\\sigma(X) = \\sqrt{V(X)}$."
    ),
    tags: ["premiere", "maths", "variables_aleatoires", "variance", "qcm"],
  },
  {
    kind: "fixed",
    id: "premiere_va_var_fixed_3",
    niveau: "premiere-spe",
    matiere: "maths",
    notionId: "variables_aleatoires",
    microId: "va_variance",
    difficulty: 4,
    theme: "neutral",
    text: "$X$ vaut $0$ ou $2$ avec probabilité $0{,}5$ chacune. $E(X) = 1$. Calcule la variance $V(X)$.",
    format: "short",
    expected: ["1"],
    comparator: "number_equal",
    hint: "$0{,}5(0-1)^2 + 0{,}5(2-1)^2$.",
    explanation: exp(
      "On applique $V(X) = \\sum p_i (x_i - E(X))^2$.",
      "$0{,}5 \\times (0 - 1)^2 + 0{,}5 \\times (2 - 1)^2 = 0{,}5 + 0{,}5$.",
      "$= 1$.",
      "$V(X) = 1$."
    ),
    canvas: loiGraph([0, 2], [0.5, 0.5]),
    tags: ["premiere", "maths", "variables_aleatoires", "variance", "canvas", "short"],
  },
  {
    kind: "fixed",
    id: "premiere_va_var_fixed_4",
    niveau: "premiere-spe",
    matiere: "maths",
    notionId: "variables_aleatoires",
    microId: "va_variance",
    difficulty: 4,
    theme: "neutral",
    text: "Si $V(X) = 9$, combien vaut l'écart-type $\\sigma(X)$ ?",
    format: "short",
    expected: ["3"],
    comparator: "number_equal",
    hint: "$\\sqrt{9}$.",
    explanation: exp(
      "L'écart-type est la racine carrée de la variance.",
      "$\\sigma(X) = \\sqrt{9}$.",
      "$= 3$.",
      "$\\sigma(X) = 3$."
    ),
    tags: ["premiere", "maths", "variables_aleatoires", "variance", "short"],
  },
  {
    kind: "fixed",
    id: "premiere_va_var_fixed_5",
    niveau: "premiere-spe",
    matiere: "maths",
    notionId: "variables_aleatoires",
    microId: "va_variance",
    difficulty: 3,
    theme: "neutral",
    text: "Si $V(X) = 16$, combien vaut l'écart-type $\\sigma(X)$ ?",
    format: "short",
    expected: ["4"],
    comparator: "number_equal",
    hint: "$\\sqrt{16}$.",
    explanation: exp(
      "L'écart-type est la racine carrée de la variance : $\\sigma(X) = \\sqrt{V(X)}$.",
      "$\\sigma(X) = \\sqrt{16}$.",
      "$= 4$. On prend la racine pour revenir à la même unité que $X$ : la variance, elle, s'exprime en unités au carré.",
      "$\\sigma(X) = 4$."
    ),
    tags: ["premiere", "maths", "variables_aleatoires", "variance", "short"],
  },
  {
    kind: "fixed",
    id: "premiere_va_var_fixed_6",
    niveau: "premiere-spe",
    matiere: "maths",
    notionId: "variables_aleatoires",
    microId: "va_variance",
    difficulty: 5,
    theme: "neutral",
    text: "$X$ vaut $0$ ou $4$ avec la probabilité $0{,}5$ chacune, et $E(X) = 2$. Calcule la variance $V(X)$.",
    format: "short",
    expected: ["4"],
    comparator: "number_equal",
    hint: "$(0-2)^2 \\times 0{,}5 + (4-2)^2 \\times 0{,}5$.",
    explanation: exp(
      "La variance est la moyenne des carrés des écarts à l'espérance : $V(X) = \\sum p_i (x_i - E(X))^2$.",
      "$(0 - 2)^2 \\times 0{,}5 + (4 - 2)^2 \\times 0{,}5 = 4 \\times 0{,}5 + 4 \\times 0{,}5$.",
      "$= 2 + 2 = 4$. Les écarts sont élevés au carré : la variance ne peut jamais être négative.",
      "$V(X) = 4$ (et $\\sigma(X) = 2$)."
    ),
    tags: ["premiere", "maths", "variables_aleatoires", "variance", "short"],
  },
  {
    kind: "fixed",
    id: "premiere_va_var_fixed_7",
    niveau: "premiere-spe",
    matiere: "maths",
    notionId: "variables_aleatoires",
    microId: "va_variance",
    difficulty: 4,
    theme: "neutral",
    text: "Si l'écart-type vaut $\\sigma(X) = 3$, combien vaut la variance $V(X)$ ?",
    format: "short",
    expected: ["9"],
    comparator: "number_equal",
    hint: "La variance est le CARRÉ de l'écart-type.",
    explanation: exp(
      "Les deux quantités sont liées par $\\sigma(X) = \\sqrt{V(X)}$, donc $V(X) = \\sigma(X)^2$.",
      "$V(X) = 3^2$.",
      "$= 9$.",
      "$V(X) = 9$."
    ),
    tags: ["premiere", "maths", "variables_aleatoires", "variance", "short"],
  },
  {
    kind: "fixed",
    id: "premiere_va_var_fixed_8",
    niveau: "premiere-spe",
    matiere: "maths",
    notionId: "variables_aleatoires",
    microId: "va_variance",
    difficulty: 4,
    theme: "neutral",
    text: "Quelle formule donne la variance de $X$ ?",
    format: "qcm",
    choices: [
      "$V(X) = \\sum p_i \\left(x_i - E(X)\\right)^2$",
      "$V(X) = \\sum p_i \\left(x_i - E(X)\\right)$",
      "$V(X) = \\sum x_i p_i$",
      "$V(X) = \\sqrt{\\sum p_i x_i^2}$",
    ],
    expected: ["$V(X) = \\sum p_i \\left(x_i - E(X)\\right)^2$"],
    comparator: "mcq_exact",
    hint: "Sans le carré, la somme des écarts vaudrait toujours $0$.",
    explanation: exp(
      "La variance mesure la dispersion autour de l'espérance : on part des écarts $x_i - E(X)$.",
      "Ces écarts sont élevés au CARRÉ, sinon les écarts positifs et négatifs se compenseraient et la somme vaudrait toujours $0$.",
      "Chaque carré est ensuite pesé par sa probabilité $p_i$. La formule $\\sum x_i p_i$, elle, donne l'espérance.",
      "$V(X) = \\sum p_i \\left(x_i - E(X)\\right)^2$."
    ),
    tags: ["premiere", "maths", "variables_aleatoires", "variance", "qcm"],
  },
  {
    kind: "fixed",
    id: "premiere_va_var_fixed_9",
    niveau: "premiere-spe",
    matiere: "maths",
    notionId: "variables_aleatoires",
    microId: "va_variance",
    difficulty: 4,
    theme: "neutral",
    text: "Deux variables ont la même espérance, mais $V(X) = 0{,}5$ et $V(Y) = 20$. Que peut-on dire ?",
    format: "qcm",
    choices: [
      "les valeurs de $Y$ sont bien plus dispersées que celles de $X$",
      "les valeurs de $Y$ sont plus grandes que celles de $X$",
      "$Y$ a une plus grande probabilité d'être positive",
      "on ne peut rien comparer",
    ],
    expected: ["les valeurs de $Y$ sont bien plus dispersées que celles de $X$"],
    comparator: "mcq_exact",
    hint: "La variance mesure l'écartement autour de la moyenne, pas la taille des valeurs.",
    explanation: exp(
      "La variance mesure à quel point les valeurs s'écartent de l'espérance.",
      "$V(Y) = 20$ est bien supérieure à $V(X) = 0{,}5$ : les valeurs de $Y$ s'éloignent beaucoup plus de la moyenne.",
      "Cela ne dit rien de leur taille : les deux ont ici la même espérance. $X$ est simplement plus régulière, $Y$ plus imprévisible.",
      "Les valeurs de $Y$ sont bien plus dispersées."
    ),
    tags: ["premiere", "maths", "variables_aleatoires", "variance", "qcm"],
  },
  {
    kind: "fixed",
    id: "premiere_va_var_fixed_10",
    niveau: "premiere-spe",
    matiere: "maths",
    notionId: "variables_aleatoires",
    microId: "va_variance",
    difficulty: 5,
    theme: "neutral",
    text: "Une variable aléatoire vérifie $V(X) = 0$. Que peut-on en déduire ?",
    format: "qcm",
    choices: [
      "$X$ prend toujours la même valeur",
      "$X$ vaut toujours $0$",
      "$E(X) = 0$",
      "c'est impossible",
    ],
    expected: ["$X$ prend toujours la même valeur"],
    comparator: "mcq_exact",
    hint: "Une somme de carrés est nulle seulement si chaque terme l'est.",
    explanation: exp(
      "La variance est une somme de termes positifs $p_i(x_i - E(X))^2$.",
      "Elle ne peut être nulle que si chaque écart $x_i - E(X)$ est nul : toutes les valeurs prises coïncident avec l'espérance.",
      "$X$ est donc constante — mais cette constante n'est pas forcément $0$ : une variable valant toujours $7$ a une variance nulle et une espérance de $7$.",
      "$X$ prend toujours la même valeur."
    ),
    tags: ["premiere", "maths", "variables_aleatoires", "variance", "qcm"],
  },
  {
    kind: "fixed",
    id: "premiere_va_var_fixed_11",
    niveau: "premiere-spe",
    matiere: "maths",
    notionId: "variables_aleatoires",
    microId: "va_variance",
    difficulty: 5,
    theme: "neutral",
    text: "$X$ vaut $1$ ou $3$ avec la probabilité $0{,}5$ chacune, et $E(X) = 2$. Calcule $V(X)$.",
    format: "short",
    expected: ["1"],
    comparator: "number_equal",
    hint: "Chaque valeur est à une distance de $1$ de l'espérance.",
    explanation: exp(
      "On applique $V(X) = \\sum p_i (x_i - E(X))^2$.",
      "$(1 - 2)^2 \\times 0{,}5 + (3 - 2)^2 \\times 0{,}5 = 1 \\times 0{,}5 + 1 \\times 0{,}5$.",
      "$= 1$. Le carré rend positif l'écart $(1 - 2) = -1$.",
      "$V(X) = 1$ (et $\\sigma(X) = 1$)."
    ),
    tags: ["premiere", "maths", "variables_aleatoires", "variance", "short"],
  },
  {
    kind: "template",
    id: "premiere_va_var_tpl_1",
    niveau: "premiere-spe",
    matiere: "maths",
    notionId: "variables_aleatoires",
    microId: "va_variance",
    difficulty: 4,
    theme: "neutral",
    hint: "$\\sigma(X) = \\sqrt{V(X)}$.",
    tags: ["premiere", "maths", "variables_aleatoires", "variance", "template"],
    generate: () => {
      const sigma = randomInt(2, 9);
      const v = sigma * sigma;
      return {
        text: `Si $V(X) = ${v}$, combien vaut l'écart-type $\\sigma(X)$ ?`,
        format: "short",
        expected: [String(sigma)],
        comparator: "number_equal",
        explanation: exp(
          "L'écart-type est la racine carrée de la variance.",
          `$\\sigma(X) = \\sqrt{${v}}$.`,
          `$= ${sigma}$.`,
          `$\\sigma(X) = ${sigma}$.`
        ),
      };
    },
  },
  {
    kind: "template",
    id: "premiere_va_var_tpl_2",
    niveau: "premiere-spe",
    matiere: "maths",
    notionId: "variables_aleatoires",
    microId: "va_variance",
    difficulty: 4,
    theme: "neutral",
    hint: "$V(X) = \\sum p_i (x_i - E)^2$ avec deux valeurs équiprobables.",
    tags: ["premiere", "maths", "variables_aleatoires", "variance", "template"],
    generate: () => {
      const m = randomInt(1, 5); // demi-écart
      // X vaut 0 ou 2m, proba 0.5 ; E = m ; V = 0.5(m)^2 + 0.5(m)^2 = m^2
      const v = m * m;
      return {
        text: `$X$ vaut $0$ ou $${2 * m}$ avec probabilité $0{,}5$ chacune (donc $E(X) = ${m}$). Calcule $V(X)$.`,
        format: "short",
        expected: [String(v)],
        comparator: "number_equal",
        canvas: loiGraph([0, 2 * m], [0.5, 0.5]),
        explanation: exp(
          "On applique $V(X) = \\sum p_i (x_i - E(X))^2$.",
          `$0{,}5 \\times (0 - ${m})^2 + 0{,}5 \\times (${2 * m} - ${m})^2 = 0{,}5 \\times ${v} + 0{,}5 \\times ${v}$.`,
          `$= ${v}$.`,
          `$V(X) = ${v}$.`
        ),
      };
    },
  },

  /* ===================== VA_NOTATION ===================== */
  {
    kind: "fixed",
    id: "premiere_va_not_fixed_1",
    niveau: "premiere-spe",
    matiere: "maths",
    notionId: "variables_aleatoires",
    microId: "va_notation",
    difficulty: 2,
    theme: "neutral",
    text: "Que désigne l'événement $\\{X = 3\\}$ ?",
    format: "qcm",
    choices: [
      "« la variable $X$ prend la valeur $3$ »",
      "« $X$ est inférieur à $3$ »",
      "« $X$ vaut au moins $3$ »",
      "« la probabilité est $3$ »",
    ],
    expected: ["« la variable $X$ prend la valeur $3$ »"],
    comparator: "mcq_exact",
    hint: "Lecture directe.",
    explanation: exp(
      "$\\{X = a\\}$ est l'événement « $X$ prend la valeur $a$ ».",
      "Ici $a = 3$.",
      "C'est l'ensemble des issues où $X$ vaut exactement $3$.",
      "« $X$ prend la valeur $3$ »."
    ),
    tags: ["premiere", "maths", "variables_aleatoires", "notation", "qcm"],
  },
  {
    kind: "fixed",
    id: "premiere_va_not_fixed_2",
    niveau: "premiere-spe",
    matiere: "maths",
    notionId: "variables_aleatoires",
    microId: "va_notation",
    difficulty: 3,
    theme: "neutral",
    text: "$X$ vaut $1$, $2$, $3$ avec $P(X=1)=0{,}2$, $P(X=2)=0{,}5$, $P(X=3)=0{,}3$. Combien vaut $P(X \\le 2)$ ?",
    format: "short",
    expected: ["0,7"],
    comparator: "number_equal",
    hint: "$P(X=1) + P(X=2)$.",
    explanation: exp(
      "$\\{X \\le 2\\}$ regroupe les valeurs $1$ et $2$.",
      "$P(X \\le 2) = P(X=1) + P(X=2) = 0{,}2 + 0{,}5$.",
      "$= 0{,}7$.",
      "$P(X \\le 2) = 0{,}7$."
    ),
    canvas: loiGraph([1, 2, 3], [0.2, 0.5, 0.3]),
    tags: ["premiere", "maths", "variables_aleatoires", "notation", "canvas", "short"],
  },
  {
    kind: "fixed",
    id: "premiere_va_not_fixed_3",
    niveau: "premiere-spe",
    matiere: "maths",
    notionId: "variables_aleatoires",
    microId: "va_notation",
    difficulty: 3,
    theme: "neutral",
    text: "Avec $P(X=1)=0{,}2$, $P(X=2)=0{,}5$, $P(X=3)=0{,}3$, combien vaut $P(X \\ge 2)$ ?",
    format: "short",
    expected: ["0,8"],
    comparator: "number_equal",
    hint: "$P(X=2) + P(X=3)$.",
    explanation: exp(
      "$\\{X \\ge 2\\}$ regroupe les valeurs $2$ et $3$.",
      "$P(X \\ge 2) = 0{,}5 + 0{,}3$.",
      "$= 0{,}8$.",
      "$P(X \\ge 2) = 0{,}8$."
    ),
    canvas: loiGraph([1, 2, 3], [0.2, 0.5, 0.3]),
    tags: ["premiere", "maths", "variables_aleatoires", "notation", "canvas", "short"],
  },
  {
    kind: "fixed",
    id: "premiere_va_not_fixed_4",
    niveau: "premiere-spe",
    matiere: "maths",
    notionId: "variables_aleatoires",
    microId: "va_notation",
    difficulty: 2,
    theme: "neutral",
    text: "L'événement $\\{X \\le 5\\}$ signifie :",
    format: "qcm",
    choices: [
      "« $X$ est inférieur ou égal à $5$ »",
      "« $X$ est égal à $5$ »",
      "« $X$ est strictement supérieur à $5$ »",
      "« $X$ vaut $5$ avec probabilité $1$ »",
    ],
    expected: ["« $X$ est inférieur ou égal à $5$ »"],
    comparator: "mcq_exact",
    hint: "Symbole $\\le$.",
    explanation: exp(
      "$\\{X \\le a\\}$ regroupe toutes les valeurs inférieures ou égales à $a$.",
      "Ici $a = 5$.",
      "C'est l'événement « $X \\le 5$ ».",
      "« $X$ est inférieur ou égal à $5$ »."
    ),
    tags: ["premiere", "maths", "variables_aleatoires", "notation", "qcm"],
  },
  {
    kind: "fixed",
    id: "premiere_va_not_fixed_5",
    niveau: "premiere-spe",
    matiere: "maths",
    notionId: "variables_aleatoires",
    microId: "va_notation",
    difficulty: 4,
    theme: "neutral",
    text: "Avec $P(X=1)=0{,}2$, $P(X=2)=0{,}5$ et $P(X=3)=0{,}3$, combien vaut $P(X < 3)$ ?",
    format: "short",
    expected: ["0,7"],
    comparator: "number_equal",
    hint: "Strictement inférieur à $3$ : les valeurs $1$ et $2$.",
    explanation: exp(
      "L'inégalité STRICTE $X < 3$ exclut la valeur $3$.",
      "Restent les valeurs $1$ et $2$ : $0{,}2 + 0{,}5$.",
      "$= 0{,}7$.",
      "$P(X < 3) = 0{,}7$."
    ),
    tags: ["premiere", "maths", "variables_aleatoires", "notation", "short"],
  },
  {
    kind: "fixed",
    id: "premiere_va_not_fixed_6",
    niveau: "premiere-spe",
    matiere: "maths",
    notionId: "variables_aleatoires",
    microId: "va_notation",
    difficulty: 4,
    theme: "neutral",
    text: "Avec $P(X=1)=0{,}2$, $P(X=2)=0{,}5$ et $P(X=3)=0{,}3$, combien vaut $P(X > 1)$ ?",
    format: "short",
    expected: ["0,8"],
    comparator: "number_equal",
    hint: "Strictement supérieur à $1$ : les valeurs $2$ et $3$.",
    explanation: exp(
      "$X > 1$ exclut la valeur $1$ elle-même.",
      "Restent $2$ et $3$ : $0{,}5 + 0{,}3$.",
      "$= 0{,}8$. On peut aussi passer par l'événement contraire : $1 - P(X = 1) = 1 - 0{,}2$.",
      "$P(X > 1) = 0{,}8$."
    ),
    tags: ["premiere", "maths", "variables_aleatoires", "notation", "short"],
  },
  {
    kind: "fixed",
    id: "premiere_va_not_fixed_7",
    niveau: "premiere-spe",
    matiere: "maths",
    notionId: "variables_aleatoires",
    microId: "va_notation",
    difficulty: 3,
    theme: "neutral",
    text: "Que désigne l'événement $\\{X \\ge 2\\}$ ?",
    format: "qcm",
    choices: [
      "« $X$ prend la valeur $2$ ou une valeur plus grande »",
      "« $X$ prend une valeur strictement plus grande que $2$ »",
      "« $X$ est égal à $2$ »",
      "« $X$ prend une valeur plus petite que $2$ »",
    ],
    expected: ["« $X$ prend la valeur $2$ ou une valeur plus grande »"],
    comparator: "mcq_exact",
    hint: "Le trait sous le symbole $\\ge$ inclut l'égalité.",
    explanation: exp(
      "Le symbole $\\ge$ signifie « supérieur OU ÉGAL ».",
      "L'événement $\\{X \\ge 2\\}$ regroupe donc la valeur $2$ et toutes les valeurs au-dessus.",
      "Sans le trait, $\\{X > 2\\}$ exclurait la valeur $2$ : la différence porte exactement sur $P(X = 2)$.",
      "C'est « $X$ prend la valeur $2$ ou une valeur plus grande »."
    ),
    tags: ["premiere", "maths", "variables_aleatoires", "notation", "qcm"],
  },
  {
    kind: "fixed",
    id: "premiere_va_not_fixed_8",
    niveau: "premiere-spe",
    matiere: "maths",
    notionId: "variables_aleatoires",
    microId: "va_notation",
    difficulty: 3,
    theme: "neutral",
    text: "Si $P(X = 2) = 0{,}5$, combien vaut la probabilité que $X$ ne prenne PAS la valeur $2$ ?",
    format: "short",
    expected: ["0,5"],
    comparator: "number_equal",
    hint: "Événement contraire : on retranche à $1$.",
    explanation: exp(
      "« Ne pas prendre la valeur $2$ » est l'événement contraire de $\\{X = 2\\}$.",
      "Sa probabilité vaut $1 - P(X = 2) = 1 - 0{,}5$.",
      "$= 0{,}5$.",
      "La probabilité est $0{,}5$."
    ),
    tags: ["premiere", "maths", "variables_aleatoires", "notation", "short"],
  },
  {
    kind: "fixed",
    id: "premiere_va_not_fixed_9",
    niveau: "premiere-spe",
    matiere: "maths",
    notionId: "variables_aleatoires",
    microId: "va_notation",
    difficulty: 5,
    theme: "neutral",
    text: "Quelle est la différence entre $\\{X \\le 2\\}$ et $\\{X < 2\\}$ ?",
    format: "qcm",
    choices: [
      "le premier contient la valeur $2$, pas le second",
      "aucune, les deux sont identiques",
      "le second contient la valeur $2$, pas le premier",
      "le premier ne contient que la valeur $2$",
    ],
    expected: ["le premier contient la valeur $2$, pas le second"],
    comparator: "mcq_exact",
    hint: "$\\le$ autorise l'égalité, $<$ l'interdit.",
    explanation: exp(
      "$\\le$ signifie « inférieur ou égal », $<$ signifie « strictement inférieur ».",
      "$\\{X \\le 2\\}$ inclut donc la valeur $2$, que $\\{X < 2\\}$ exclut.",
      "L'écart entre les deux probabilités est exactement $P(X = 2)$. Pour une variable prenant des valeurs entières, $\\{X < 2\\}$ revient à $\\{X \\le 1\\}$.",
      "Le premier contient la valeur $2$, pas le second."
    ),
    tags: ["premiere", "maths", "variables_aleatoires", "notation", "qcm"],
  },
  {
    kind: "fixed",
    id: "premiere_va_not_fixed_10",
    niveau: "premiere-spe",
    matiere: "maths",
    notionId: "variables_aleatoires",
    microId: "va_notation",
    difficulty: 5,
    theme: "neutral",
    text: "$X$ prend les valeurs $0$, $1$, $2$, $3$ avec les probabilités $0{,}1$, $0{,}2$, $0{,}4$ et $0{,}3$. Combien vaut $P(1 \\le X \\le 2)$ ?",
    format: "short",
    expected: ["0,6"],
    comparator: "number_equal",
    hint: "Les deux bornes sont incluses : additionne $P(X=1)$ et $P(X=2)$.",
    explanation: exp(
      "L'encadrement $1 \\le X \\le 2$ retient les valeurs comprises entre $1$ et $2$, bornes INCLUSES.",
      "Seules les valeurs $1$ et $2$ conviennent : $0{,}2 + 0{,}4$.",
      "$= 0{,}6$.",
      "$P(1 \\le X \\le 2) = 0{,}6$."
    ),
    tags: ["premiere", "maths", "variables_aleatoires", "notation", "short"],
  },
  {
    kind: "fixed",
    id: "premiere_va_not_fixed_11",
    niveau: "premiere-spe",
    matiere: "maths",
    notionId: "variables_aleatoires",
    microId: "va_notation",
    difficulty: 4,
    theme: "neutral",
    text: "$X$ prend uniquement les valeurs $1$, $2$ et $3$. Combien vaut $P(X \\le 3)$ ?",
    format: "short",
    expected: ["1"],
    comparator: "number_equal",
    hint: "Cet événement contient-il toutes les valeurs possibles ?",
    explanation: exp(
      "$\\{X \\le 3\\}$ regroupe les valeurs $1$, $2$ et $3$.",
      "Or ce sont les SEULES valeurs que $X$ peut prendre : l'événement est certain.",
      "Sa probabilité vaut donc $0{,}2 + 0{,}5 + 0{,}3 = 1$, quelle que soit la loi.",
      "$P(X \\le 3) = 1$."
    ),
    tags: ["premiere", "maths", "variables_aleatoires", "notation", "short"],
  },
  {
    kind: "template",
    id: "premiere_va_not_tpl_1",
    niveau: "premiere-spe",
    matiere: "maths",
    notionId: "variables_aleatoires",
    microId: "va_notation",
    difficulty: 3,
    theme: "neutral",
    hint: "$P(X \\le 2) = P(X=1) + P(X=2)$.",
    tags: ["premiere", "maths", "variables_aleatoires", "notation", "template"],
    generate: () => {
      const p1 = randomInt(1, 4) / 10;
      const p2 = randomInt(1, 4) / 10;
      const p3 = Math.round((1 - p1 - p2) * 10) / 10;
      const cumul = Math.round((p1 + p2) * 10) / 10;
      return {
        text: `$X$ vaut $1$, $2$, $3$ avec $P(X=1)=${String(p1).replace(".", ",")}$, $P(X=2)=${String(p2).replace(".", ",")}$, $P(X=3)=${String(p3).replace(".", ",")}$. Combien vaut $P(X \\le 2)$ ?`,
        format: "short",
        expected: [String(cumul).replace(".", ",")],
        comparator: "number_equal",
        canvas: loiGraph([1, 2, 3], [p1, p2, p3]),
        explanation: exp(
          "$\\{X \\le 2\\}$ regroupe les valeurs $1$ et $2$.",
          `$P(X \\le 2) = ${String(p1).replace(".", ",")} + ${String(p2).replace(".", ",")}$.`,
          `$= ${String(cumul).replace(".", ",")}$.`,
          `$P(X \\le 2) = ${String(cumul).replace(".", ",")}$.`
        ),
      };
    },
  },
];
