import type { TutorBankItemV4 } from "@/lib/tutor-v4/types";

export const iaA1QuestionBank: TutorBankItemV4[] = [
  {
    kind: "fixed",
    id: "ia_a1_expliquer_ia_qcm_001",
    niveau: "a1",
    matiere: "ia",
    notionId: "ia_a1_definition",
    microId: "ia_a1_expliquer_ia",
    difficulty: 1,
    text: "Quelle affirmation valide la micro-comp?tence A1 : Je sais expliquer ce qu'est une intelligence artificielle avec mes mots.",
    format: "qcm",
    choices: ["Je sais expliquer ce qu'est une intelligence artificielle avec mes mots.","Je laisse l'IA d?cider ? ma place.","Je copie la r?ponse sans v?rifier."],
    expected: ["A"],
    comparator: "mcq_exact",
    hint: "Cherche la r?ponse qui garde m?thode, jugement et responsabilit? humaine.",
    explanation: "Bonne r?ponse : Je sais expliquer ce qu'est une intelligence artificielle avec mes mots.",
  },
  {
    kind: "fixed",
    id: "ia_a1_expliquer_ia_qcm_002",
    niveau: "a1",
    matiere: "ia",
    notionId: "ia_a1_definition",
    microId: "ia_a1_expliquer_ia",
    difficulty: 1,
    text: "Dans une situation r?elle, quelle action correspond le mieux ? : Je sais expliquer ce qu'est une intelligence artificielle avec mes mots.",
    format: "qcm",
    choices: ["Je sais expliquer ce qu'est une intelligence artificielle avec mes mots.","Partager des informations sensibles pour aller plus vite.","Faire confiance ? une seule r?ponse sans recul."],
    expected: ["A"],
    comparator: "mcq_exact",
    hint: "L'IA est un outil : l'?l?ve garde l'objectif, la v?rification et la d?cision.",
    explanation: "Cette micro-comp?tence se valide quand l'?l?ve sait faire ceci : Je sais expliquer ce qu'est une intelligence artificielle avec mes mots.",
  },
  {
    kind: "fixed",
    id: "ia_a1_distinguer_outils_qcm_001",
    niveau: "a1",
    matiere: "ia",
    notionId: "ia_a1_definition",
    microId: "ia_a1_distinguer_outils",
    difficulty: 1,
    text: "Quelle affirmation valide la micro-comp?tence A1 : Je sais distinguer IA, moteur de recherche, calculatrice et humain.",
    format: "qcm",
    choices: ["Je sais distinguer IA, moteur de recherche, calculatrice et humain.","Je laisse l'IA d?cider ? ma place.","Je copie la r?ponse sans v?rifier."],
    expected: ["A"],
    comparator: "mcq_exact",
    hint: "Cherche la r?ponse qui garde m?thode, jugement et responsabilit? humaine.",
    explanation: "Bonne r?ponse : Je sais distinguer IA, moteur de recherche, calculatrice et humain.",
  },
  {
    kind: "fixed",
    id: "ia_a1_distinguer_outils_qcm_002",
    niveau: "a1",
    matiere: "ia",
    notionId: "ia_a1_definition",
    microId: "ia_a1_distinguer_outils",
    difficulty: 1,
    text: "Dans une situation r?elle, quelle action correspond le mieux ? : Je sais distinguer IA, moteur de recherche, calculatrice et humain.",
    format: "qcm",
    choices: ["Je sais distinguer IA, moteur de recherche, calculatrice et humain.","Partager des informations sensibles pour aller plus vite.","Faire confiance ? une seule r?ponse sans recul."],
    expected: ["A"],
    comparator: "mcq_exact",
    hint: "L'IA est un outil : l'?l?ve garde l'objectif, la v?rification et la d?cision.",
    explanation: "Cette micro-comp?tence se valide quand l'?l?ve sait faire ceci : Je sais distinguer IA, moteur de recherche, calculatrice et humain.",
  },
  {
    kind: "fixed",
    id: "ia_a1_prediction_qcm_001",
    niveau: "a1",
    matiere: "ia",
    notionId: "ia_a1_definition",
    microId: "ia_a1_prediction",
    difficulty: 2,
    text: "Quelle affirmation valide la micro-comp?tence A1 : Je comprends qu'une IA produit une r?ponse probable ? partir de donn?es et de mod?les.",
    format: "qcm",
    choices: ["Je comprends qu'une IA produit une r?ponse probable ? partir de donn?es et de mod?les.","Je laisse l'IA d?cider ? ma place.","Je copie la r?ponse sans v?rifier."],
    expected: ["A"],
    comparator: "mcq_exact",
    hint: "Cherche la r?ponse qui garde m?thode, jugement et responsabilit? humaine.",
    explanation: "Bonne r?ponse : Je comprends qu'une IA produit une r?ponse probable ? partir de donn?es et de mod?les.",
  },
  {
    kind: "fixed",
    id: "ia_a1_prediction_qcm_002",
    niveau: "a1",
    matiere: "ia",
    notionId: "ia_a1_definition",
    microId: "ia_a1_prediction",
    difficulty: 2,
    text: "Dans une situation r?elle, quelle action correspond le mieux ? : Je comprends qu'une IA produit une r?ponse probable ? partir de donn?es et de mod?les.",
    format: "qcm",
    choices: ["Je comprends qu'une IA produit une r?ponse probable ? partir de donn?es et de mod?les.","Partager des informations sensibles pour aller plus vite.","Faire confiance ? une seule r?ponse sans recul."],
    expected: ["A"],
    comparator: "mcq_exact",
    hint: "L'IA est un outil : l'?l?ve garde l'objectif, la v?rification et la d?cision.",
    explanation: "Cette micro-comp?tence se valide quand l'?l?ve sait faire ceci : Je comprends qu'une IA produit une r?ponse probable ? partir de donn?es et de mod?les.",
  },
  {
    kind: "fixed",
    id: "ia_a1_exemples_quotidiens_qcm_001",
    niveau: "a1",
    matiere: "ia",
    notionId: "ia_a1_usages_limites",
    microId: "ia_a1_exemples_quotidiens",
    difficulty: 2,
    text: "Quelle affirmation valide la micro-comp?tence A1 : Je connais des exemples d'IA dans la vie quotidienne et les m?tiers.",
    format: "qcm",
    choices: ["Je connais des exemples d'IA dans la vie quotidienne et les m?tiers.","Je laisse l'IA d?cider ? ma place.","Je copie la r?ponse sans v?rifier."],
    expected: ["A"],
    comparator: "mcq_exact",
    hint: "Cherche la r?ponse qui garde m?thode, jugement et responsabilit? humaine.",
    explanation: "Bonne r?ponse : Je connais des exemples d'IA dans la vie quotidienne et les m?tiers.",
  },
  {
    kind: "fixed",
    id: "ia_a1_exemples_quotidiens_qcm_002",
    niveau: "a1",
    matiere: "ia",
    notionId: "ia_a1_usages_limites",
    microId: "ia_a1_exemples_quotidiens",
    difficulty: 2,
    text: "Dans une situation r?elle, quelle action correspond le mieux ? : Je connais des exemples d'IA dans la vie quotidienne et les m?tiers.",
    format: "qcm",
    choices: ["Je connais des exemples d'IA dans la vie quotidienne et les m?tiers.","Partager des informations sensibles pour aller plus vite.","Faire confiance ? une seule r?ponse sans recul."],
    expected: ["A"],
    comparator: "mcq_exact",
    hint: "L'IA est un outil : l'?l?ve garde l'objectif, la v?rification et la d?cision.",
    explanation: "Cette micro-comp?tence se valide quand l'?l?ve sait faire ceci : Je connais des exemples d'IA dans la vie quotidienne et les m?tiers.",
  },
  {
    kind: "fixed",
    id: "ia_a1_erreur_possible_qcm_001",
    niveau: "a1",
    matiere: "ia",
    notionId: "ia_a1_usages_limites",
    microId: "ia_a1_erreur_possible",
    difficulty: 3,
    text: "Quelle affirmation valide la micro-comp?tence A1 : Je sais expliquer qu'une IA peut se tromper m?me si elle r?pond avec assurance.",
    format: "qcm",
    choices: ["Je sais expliquer qu'une IA peut se tromper m?me si elle r?pond avec assurance.","Je laisse l'IA d?cider ? ma place.","Je copie la r?ponse sans v?rifier."],
    expected: ["A"],
    comparator: "mcq_exact",
    hint: "Cherche la r?ponse qui garde m?thode, jugement et responsabilit? humaine.",
    explanation: "Bonne r?ponse : Je sais expliquer qu'une IA peut se tromper m?me si elle r?pond avec assurance.",
  },
  {
    kind: "fixed",
    id: "ia_a1_erreur_possible_qcm_002",
    niveau: "a1",
    matiere: "ia",
    notionId: "ia_a1_usages_limites",
    microId: "ia_a1_erreur_possible",
    difficulty: 3,
    text: "Dans une situation r?elle, quelle action correspond le mieux ? : Je sais expliquer qu'une IA peut se tromper m?me si elle r?pond avec assurance.",
    format: "qcm",
    choices: ["Je sais expliquer qu'une IA peut se tromper m?me si elle r?pond avec assurance.","Partager des informations sensibles pour aller plus vite.","Faire confiance ? une seule r?ponse sans recul."],
    expected: ["A"],
    comparator: "mcq_exact",
    hint: "L'IA est un outil : l'?l?ve garde l'objectif, la v?rification et la d?cision.",
    explanation: "Cette micro-comp?tence se valide quand l'?l?ve sait faire ceci : Je sais expliquer qu'une IA peut se tromper m?me si elle r?pond avec assurance.",
  },
  {
    kind: "fixed",
    id: "ia_a1_vocabulaire_base_qcm_001",
    niveau: "a1",
    matiere: "ia",
    notionId: "ia_a1_usages_limites",
    microId: "ia_a1_vocabulaire_base",
    difficulty: 3,
    text: "Quelle affirmation valide la micro-comp?tence A1 : Je connais les mots donn?e, mod?le, prompt, biais et hallucination.",
    format: "qcm",
    choices: ["Je connais les mots donn?e, mod?le, prompt, biais et hallucination.","Je laisse l'IA d?cider ? ma place.","Je copie la r?ponse sans v?rifier."],
    expected: ["A"],
    comparator: "mcq_exact",
    hint: "Cherche la r?ponse qui garde m?thode, jugement et responsabilit? humaine.",
    explanation: "Bonne r?ponse : Je connais les mots donn?e, mod?le, prompt, biais et hallucination.",
  },
  {
    kind: "fixed",
    id: "ia_a1_vocabulaire_base_qcm_002",
    niveau: "a1",
    matiere: "ia",
    notionId: "ia_a1_usages_limites",
    microId: "ia_a1_vocabulaire_base",
    difficulty: 3,
    text: "Dans une situation r?elle, quelle action correspond le mieux ? : Je connais les mots donn?e, mod?le, prompt, biais et hallucination.",
    format: "qcm",
    choices: ["Je connais les mots donn?e, mod?le, prompt, biais et hallucination.","Partager des informations sensibles pour aller plus vite.","Faire confiance ? une seule r?ponse sans recul."],
    expected: ["A"],
    comparator: "mcq_exact",
    hint: "L'IA est un outil : l'?l?ve garde l'objectif, la v?rification et la d?cision.",
    explanation: "Cette micro-comp?tence se valide quand l'?l?ve sait faire ceci : Je connais les mots donn?e, mod?le, prompt, biais et hallucination.",
  },
];

export function getIaA1QuestionBank(args?: {
  notionId?: string | null;
  microId?: string | null;
}): TutorBankItemV4[] {
  let bank = iaA1QuestionBank;

  if (args?.notionId) bank = bank.filter((item) => item.notionId === args.notionId);
  if (args?.microId) bank = bank.filter((item) => item.microId === args.microId);

  return bank;
}
