import type { TutorBankItemV4 } from "@/lib/tutor-v4/types";

export const iaA1QuestionBank: TutorBankItemV4[] = [
  {
    kind: "fixed",
    id: "ia_a1_expliquer_ia_qcm_001",
    niveau: "a1",
    matiere: "ia",
    notionId: "ia_a1_definition",
    microId: "ia_a1_expliquer_ia",
    difficulty: 1,
    text: "Quelle affirmation valide la micro-competence A1 : Je sais expliquer ce qu'est une intelligence artificielle avec mes mots.",
    format: "qcm",
    choices: ["Je sais expliquer ce qu'est une intelligence artificielle avec mes mots.","Je laisse l'IA decider a ma place.","Je copie la reponse sans verifier."],
    expected: ["Je sais expliquer ce qu'est une intelligence artificielle avec mes mots."],
    comparator: "mcq_exact",
    hint: "Cherche la reponse qui garde methode, jugement et responsabilite humaine.",
    explanation: "Bonne reponse : Je sais expliquer ce qu'est une intelligence artificielle avec mes mots.",
  },
  {
    kind: "fixed",
    id: "ia_a1_expliquer_ia_qcm_002",
    niveau: "a1",
    matiere: "ia",
    notionId: "ia_a1_definition",
    microId: "ia_a1_expliquer_ia",
    difficulty: 1,
    text: "Dans une situation reelle, quelle action correspond le mieux a : Je sais expliquer ce qu'est une intelligence artificielle avec mes mots.",
    format: "qcm",
    choices: ["Je sais expliquer ce qu'est une intelligence artificielle avec mes mots.","Partager des informations sensibles pour aller plus vite.","Faire confiance a une seule reponse sans recul."],
    expected: ["Je sais expliquer ce qu'est une intelligence artificielle avec mes mots."],
    comparator: "mcq_exact",
    hint: "L'IA est un outil : l'eleve garde l'objectif, la verification et la decision.",
    explanation: "Cette micro-competence se valide quand l'eleve sait faire ceci : Je sais expliquer ce qu'est une intelligence artificielle avec mes mots.",
  },
  {
    kind: "fixed",
    id: "ia_a1_distinguer_outils_qcm_001",
    niveau: "a1",
    matiere: "ia",
    notionId: "ia_a1_definition",
    microId: "ia_a1_distinguer_outils",
    difficulty: 1,
    text: "Quelle affirmation valide la micro-competence A1 : Je sais distinguer IA, moteur de recherche, calculatrice et humain.",
    format: "qcm",
    choices: ["Je sais distinguer IA, moteur de recherche, calculatrice et humain.","Je laisse l'IA decider a ma place.","Je copie la reponse sans verifier."],
    expected: ["Je sais distinguer IA, moteur de recherche, calculatrice et humain."],
    comparator: "mcq_exact",
    hint: "Cherche la reponse qui garde methode, jugement et responsabilite humaine.",
    explanation: "Bonne reponse : Je sais distinguer IA, moteur de recherche, calculatrice et humain.",
  },
  {
    kind: "fixed",
    id: "ia_a1_distinguer_outils_qcm_002",
    niveau: "a1",
    matiere: "ia",
    notionId: "ia_a1_definition",
    microId: "ia_a1_distinguer_outils",
    difficulty: 1,
    text: "Dans une situation reelle, quelle action correspond le mieux a : Je sais distinguer IA, moteur de recherche, calculatrice et humain.",
    format: "qcm",
    choices: ["Je sais distinguer IA, moteur de recherche, calculatrice et humain.","Partager des informations sensibles pour aller plus vite.","Faire confiance a une seule reponse sans recul."],
    expected: ["Je sais distinguer IA, moteur de recherche, calculatrice et humain."],
    comparator: "mcq_exact",
    hint: "L'IA est un outil : l'eleve garde l'objectif, la verification et la decision.",
    explanation: "Cette micro-competence se valide quand l'eleve sait faire ceci : Je sais distinguer IA, moteur de recherche, calculatrice et humain.",
  },
  {
    kind: "fixed",
    id: "ia_a1_prediction_qcm_001",
    niveau: "a1",
    matiere: "ia",
    notionId: "ia_a1_definition",
    microId: "ia_a1_prediction",
    difficulty: 2,
    text: "Quelle affirmation valide la micro-competence A1 : Je comprends qu'une IA produit une reponse probable a partir de donnees et de modeles.",
    format: "qcm",
    choices: ["Je comprends qu'une IA produit une reponse probable a partir de donnees et de modeles.","Je laisse l'IA decider a ma place.","Je copie la reponse sans verifier."],
    expected: ["Je comprends qu'une IA produit une reponse probable a partir de donnees et de modeles."],
    comparator: "mcq_exact",
    hint: "Cherche la reponse qui garde methode, jugement et responsabilite humaine.",
    explanation: "Bonne reponse : Je comprends qu'une IA produit une reponse probable a partir de donnees et de modeles.",
  },
  {
    kind: "fixed",
    id: "ia_a1_prediction_qcm_002",
    niveau: "a1",
    matiere: "ia",
    notionId: "ia_a1_definition",
    microId: "ia_a1_prediction",
    difficulty: 2,
    text: "Dans une situation reelle, quelle action correspond le mieux a : Je comprends qu'une IA produit une reponse probable a partir de donnees et de modeles.",
    format: "qcm",
    choices: ["Je comprends qu'une IA produit une reponse probable a partir de donnees et de modeles.","Partager des informations sensibles pour aller plus vite.","Faire confiance a une seule reponse sans recul."],
    expected: ["Je comprends qu'une IA produit une reponse probable a partir de donnees et de modeles."],
    comparator: "mcq_exact",
    hint: "L'IA est un outil : l'eleve garde l'objectif, la verification et la decision.",
    explanation: "Cette micro-competence se valide quand l'eleve sait faire ceci : Je comprends qu'une IA produit une reponse probable a partir de donnees et de modeles.",
  },
  {
    kind: "fixed",
    id: "ia_a1_exemples_quotidiens_qcm_001",
    niveau: "a1",
    matiere: "ia",
    notionId: "ia_a1_usages_limites",
    microId: "ia_a1_exemples_quotidiens",
    difficulty: 2,
    text: "Quelle affirmation valide la micro-competence A1 : Je connais des exemples d'IA dans la vie quotidienne et les metiers.",
    format: "qcm",
    choices: ["Je connais des exemples d'IA dans la vie quotidienne et les metiers.","Je laisse l'IA decider a ma place.","Je copie la reponse sans verifier."],
    expected: ["Je connais des exemples d'IA dans la vie quotidienne et les metiers."],
    comparator: "mcq_exact",
    hint: "Cherche la reponse qui garde methode, jugement et responsabilite humaine.",
    explanation: "Bonne reponse : Je connais des exemples d'IA dans la vie quotidienne et les metiers.",
  },
  {
    kind: "fixed",
    id: "ia_a1_exemples_quotidiens_qcm_002",
    niveau: "a1",
    matiere: "ia",
    notionId: "ia_a1_usages_limites",
    microId: "ia_a1_exemples_quotidiens",
    difficulty: 2,
    text: "Dans une situation reelle, quelle action correspond le mieux a : Je connais des exemples d'IA dans la vie quotidienne et les metiers.",
    format: "qcm",
    choices: ["Je connais des exemples d'IA dans la vie quotidienne et les metiers.","Partager des informations sensibles pour aller plus vite.","Faire confiance a une seule reponse sans recul."],
    expected: ["Je connais des exemples d'IA dans la vie quotidienne et les metiers."],
    comparator: "mcq_exact",
    hint: "L'IA est un outil : l'eleve garde l'objectif, la verification et la decision.",
    explanation: "Cette micro-competence se valide quand l'eleve sait faire ceci : Je connais des exemples d'IA dans la vie quotidienne et les metiers.",
  },
  {
    kind: "fixed",
    id: "ia_a1_erreur_possible_qcm_001",
    niveau: "a1",
    matiere: "ia",
    notionId: "ia_a1_usages_limites",
    microId: "ia_a1_erreur_possible",
    difficulty: 3,
    text: "Quelle affirmation valide la micro-competence A1 : Je sais expliquer qu'une IA peut se tromper meme si elle repond avec assurance.",
    format: "qcm",
    choices: ["Je sais expliquer qu'une IA peut se tromper meme si elle repond avec assurance.","Je laisse l'IA decider a ma place.","Je copie la reponse sans verifier."],
    expected: ["Je sais expliquer qu'une IA peut se tromper meme si elle repond avec assurance."],
    comparator: "mcq_exact",
    hint: "Cherche la reponse qui garde methode, jugement et responsabilite humaine.",
    explanation: "Bonne reponse : Je sais expliquer qu'une IA peut se tromper meme si elle repond avec assurance.",
  },
  {
    kind: "fixed",
    id: "ia_a1_erreur_possible_qcm_002",
    niveau: "a1",
    matiere: "ia",
    notionId: "ia_a1_usages_limites",
    microId: "ia_a1_erreur_possible",
    difficulty: 3,
    text: "Dans une situation reelle, quelle action correspond le mieux a : Je sais expliquer qu'une IA peut se tromper meme si elle repond avec assurance.",
    format: "qcm",
    choices: ["Je sais expliquer qu'une IA peut se tromper meme si elle repond avec assurance.","Partager des informations sensibles pour aller plus vite.","Faire confiance a une seule reponse sans recul."],
    expected: ["Je sais expliquer qu'une IA peut se tromper meme si elle repond avec assurance."],
    comparator: "mcq_exact",
    hint: "L'IA est un outil : l'eleve garde l'objectif, la verification et la decision.",
    explanation: "Cette micro-competence se valide quand l'eleve sait faire ceci : Je sais expliquer qu'une IA peut se tromper meme si elle repond avec assurance.",
  },
  {
    kind: "fixed",
    id: "ia_a1_vocabulaire_base_qcm_001",
    niveau: "a1",
    matiere: "ia",
    notionId: "ia_a1_usages_limites",
    microId: "ia_a1_vocabulaire_base",
    difficulty: 3,
    text: "Quelle affirmation valide la micro-competence A1 : Je connais les mots donnee, modele, prompt, biais et hallucination.",
    format: "qcm",
    choices: ["Je connais les mots donnee, modele, prompt, biais et hallucination.","Je laisse l'IA decider a ma place.","Je copie la reponse sans verifier."],
    expected: ["Je connais les mots donnee, modele, prompt, biais et hallucination."],
    comparator: "mcq_exact",
    hint: "Cherche la reponse qui garde methode, jugement et responsabilite humaine.",
    explanation: "Bonne reponse : Je connais les mots donnee, modele, prompt, biais et hallucination.",
  },
  {
    kind: "fixed",
    id: "ia_a1_vocabulaire_base_qcm_002",
    niveau: "a1",
    matiere: "ia",
    notionId: "ia_a1_usages_limites",
    microId: "ia_a1_vocabulaire_base",
    difficulty: 3,
    text: "Dans une situation reelle, quelle action correspond le mieux a : Je connais les mots donnee, modele, prompt, biais et hallucination.",
    format: "qcm",
    choices: ["Je connais les mots donnee, modele, prompt, biais et hallucination.","Partager des informations sensibles pour aller plus vite.","Faire confiance a une seule reponse sans recul."],
    expected: ["Je connais les mots donnee, modele, prompt, biais et hallucination."],
    comparator: "mcq_exact",
    hint: "L'IA est un outil : l'eleve garde l'objectif, la verification et la decision.",
    explanation: "Cette micro-competence se valide quand l'eleve sait faire ceci : Je connais les mots donnee, modele, prompt, biais et hallucination.",
  },
];

export function getIaA1QuestionBank(args?: {
  notionId?: string | null;
  microId?: string | null;
}): TutorBankItemV4[] {
  let bank = iaA1QuestionBank;

  if (args?.notionId) bank = bank.filter((item) => item.notionId === args.notionId);
  if (args?.microId) bank = bank.filter((item) => item.microId === args.microId);

  return bank;
}
