// lib/english-maths/words/geometry.ts

import type { EnglishMathsWord } from "../types";

export const englishMathsGeometryWords: EnglishMathsWord[] = [
  {
    id: "geometry_point",
    category: "geometry",
    english: "point",
    french: "point",
    image: "•",
    audioWordSrc: "/audio/english-maths/geometry/point.mp3",
    audioSentenceSrc: "/audio/english-maths/geometry/point-sentence.mp3",
    sentenceEn: "This is a point.",
    sentenceFr: "Ceci est un point.",
  },
  {
    id: "geometry_line",
    category: "geometry",
    english: "line",
    french: "droite",
    image: "↔️",
    audioWordSrc: "/audio/english-maths/geometry/line.mp3",
    audioSentenceSrc: "/audio/english-maths/geometry/line-sentence.mp3",
    sentenceEn: "This is a line.",
    sentenceFr: "Ceci est une droite.",
  },
  {
    id: "geometry_triangle",
    category: "geometry",
    english: "triangle",
    french: "triangle",
    image: "🔺",
    audioWordSrc: "/audio/english-maths/geometry/triangle.mp3",
    audioSentenceSrc: "/audio/english-maths/geometry/triangle-sentence.mp3",
    sentenceEn: "This is a triangle.",
    sentenceFr: "Ceci est un triangle.",
  },
  {
    id: "geometry_square",
    category: "geometry",
    english: "square",
    french: "carré",
    image: "◼️",
    audioWordSrc: "/audio/english-maths/geometry/square.mp3",
    audioSentenceSrc: "/audio/english-maths/geometry/square-sentence.mp3",
    sentenceEn: "This is a square.",
    sentenceFr: "Ceci est un carré.",
  },
  {
    id: "geometry_circle",
    category: "geometry",
    english: "circle",
    french: "cercle",
    image: "⭕",
    audioWordSrc: "/audio/english-maths/geometry/circle.mp3",
    audioSentenceSrc: "/audio/english-maths/geometry/circle-sentence.mp3",
    sentenceEn: "This is a circle.",
    sentenceFr: "Ceci est un cercle.",
  },
  {
    id: "geometry_angle",
    category: "geometry",
    english: "angle",
    french: "angle",
    image: "📐",
    audioWordSrc: "/audio/english-maths/geometry/angle.mp3",
    audioSentenceSrc: "/audio/english-maths/geometry/angle-sentence.mp3",
    sentenceEn: "This is an angle.",
    sentenceFr: "Ceci est un angle.",
  },
  {
    id: "geometry_side",
    category: "geometry",
    english: "side",
    french: "côté",
    image: "📏",
    audioWordSrc: "/audio/english-maths/geometry/side.mp3",
    audioSentenceSrc: "/audio/english-maths/geometry/side-sentence.mp3",
    sentenceEn: "A triangle has three sides.",
    sentenceFr: "Un triangle a trois côtés.",
  },
  {
    id: "geometry_vertex",
    category: "geometry",
    english: "vertex",
    french: "sommet",
    image: "🔺",
    audioWordSrc: "/audio/english-maths/geometry/vertex.mp3",
    audioSentenceSrc: "/audio/english-maths/geometry/vertex-sentence.mp3",
    sentenceEn: "A vertex is a corner of a shape.",
    sentenceFr: "Un sommet est un coin d'une figure.",
  },
  {
    id: "geometry_rectangle",
    category: "geometry",
    english: "rectangle",
    french: "rectangle",
    image: "▭",
    audioWordSrc: "/audio/english-maths/geometry/rectangle.mp3",
    audioSentenceSrc: "/audio/english-maths/geometry/rectangle-sentence.mp3",
    sentenceEn: "This is a rectangle.",
    sentenceFr: "Ceci est un rectangle.",
  },
  {
    id: "geometry_perimeter",
    category: "geometry",
    english: "perimeter",
    french: "périmètre",
    image: "📏",
    audioWordSrc: "/audio/english-maths/geometry/perimeter.mp3",
    audioSentenceSrc: "/audio/english-maths/geometry/perimeter-sentence.mp3",
    sentenceEn: "The perimeter is the distance around a shape.",
    sentenceFr: "Le périmètre est la longueur autour d'une figure.",
  },
];