// lib/english-maths/words/numbers.ts

import type { EnglishMathsWord } from "../types";

export const englishMathsNumbersWords: EnglishMathsWord[] = [
  {
    id: "numbers_number",
    category: "numbers",
    english: "number",
    french: "nombre",
    image: "🔢",
    audioWordSrc: "/audio/english-maths/numbers/number.mp3",
    audioSentenceSrc: "/audio/english-maths/numbers/number-sentence.mp3",
    sentenceEn: "This is a number.",
    sentenceFr: "Ceci est un nombre.",
  },
  {
    id: "numbers_ten",
    category: "numbers",
    english: "ten",
    french: "dix",
    image: "🔟",
    audioWordSrc: "/audio/english-maths/numbers/ten.mp3",
    audioSentenceSrc: "/audio/english-maths/numbers/ten-sentence.mp3",
    sentenceEn: "Ten is a number.",
    sentenceFr: "Dix est un nombre.",
  },
  {
    id: "numbers_hundred",
    category: "numbers",
    english: "hundred",
    french: "cent",
    image: "💯",
    audioWordSrc: "/audio/english-maths/numbers/hundred.mp3",
    audioSentenceSrc: "/audio/english-maths/numbers/hundred-sentence.mp3",
    sentenceEn: "One hundred is ten times ten.",
    sentenceFr: "Cent, c’est dix fois dix.",
  },
  {
    id: "numbers_thousand",
    category: "numbers",
    english: "thousand",
    french: "mille",
    image: "1000",
    audioWordSrc: "/audio/english-maths/numbers/thousand.mp3",
    audioSentenceSrc: "/audio/english-maths/numbers/thousand-sentence.mp3",
    sentenceEn: "One thousand is ten hundreds.",
    sentenceFr: "Mille, c’est dix centaines.",
  },
  {
    id: "numbers_half",
    category: "numbers",
    english: "half",
    french: "moitié",
    image: "½",
    audioWordSrc: "/audio/english-maths/numbers/half.mp3",
    audioSentenceSrc: "/audio/english-maths/numbers/half-sentence.mp3",
    sentenceEn: "One half is half of one.",
    sentenceFr: "Un demi est la moitié de un.",
  },
];