import type { TutorBankItemV4 } from "@/lib/tutor-v4/types";

export const iaA2QuestionBank: TutorBankItemV4[] = [
  {
    kind: "fixed",
    id: "ia_a2_prompt_clair_qcm_001",
    niveau: "a2",
    matiere: "ia",
    notionId: "ia_a2_prompts",
    microId: "ia_a2_prompt_clair",
    difficulty: 1,
    text: "Quelle affirmation valide la micro-comp?tence A2 : Je sais ?crire un prompt simple, clair et orient? vers un objectif.",
    format: "qcm",
    choices: ["Je sais ?crire un prompt simple, clair et orient? vers un objectif.","Je laisse l'IA d?cider ? ma place.","Je copie la r?ponse sans v?rifier."],
    expected: ["A"],
    comparator: "mcq_exact",
    hint: "Cherche la r?ponse qui garde m?thode, jugement et responsabilit? humaine.",
    explanation: "Bonne r?ponse : Je sais ?crire un prompt simple, clair et orient? vers un objectif.",
  },
  {
    kind: "fixed",
    id: "ia_a2_prompt_clair_qcm_002",
    niveau: "a2",
    matiere: "ia",
    notionId: "ia_a2_prompts",
    microId: "ia_a2_prompt_clair",
    difficulty: 1,
    text: "Dans une situation r?elle, quelle action correspond le mieux ? : Je sais ?crire un prompt simple, clair et orient? vers un objectif.",
    format: "qcm",
    choices: ["Je sais ?crire un prompt simple, clair et orient? vers un objectif.","Partager des informations sensibles pour aller plus vite.","Faire confiance ? une seule r?ponse sans recul."],
    expected: ["A"],
    comparator: "mcq_exact",
    hint: "L'IA est un outil : l'?l?ve garde l'objectif, la v?rification et la d?cision.",
    explanation: "Cette micro-comp?tence se valide quand l'?l?ve sait faire ceci : Je sais ?crire un prompt simple, clair et orient? vers un objectif.",
  },
  {
    kind: "fixed",
    id: "ia_a2_contexte_niveau_qcm_001",
    niveau: "a2",
    matiere: "ia",
    notionId: "ia_a2_prompts",
    microId: "ia_a2_contexte_niveau",
    difficulty: 1,
    text: "Quelle affirmation valide la micro-comp?tence A2 : Je sais donner un contexte et demander une r?ponse adapt?e ? mon niveau.",
    format: "qcm",
    choices: ["Je sais donner un contexte et demander une r?ponse adapt?e ? mon niveau.","Je laisse l'IA d?cider ? ma place.","Je copie la r?ponse sans v?rifier."],
    expected: ["A"],
    comparator: "mcq_exact",
    hint: "Cherche la r?ponse qui garde m?thode, jugement et responsabilit? humaine.",
    explanation: "Bonne r?ponse : Je sais donner un contexte et demander une r?ponse adapt?e ? mon niveau.",
  },
  {
    kind: "fixed",
    id: "ia_a2_contexte_niveau_qcm_002",
    niveau: "a2",
    matiere: "ia",
    notionId: "ia_a2_prompts",
    microId: "ia_a2_contexte_niveau",
    difficulty: 1,
    text: "Dans une situation r?elle, quelle action correspond le mieux ? : Je sais donner un contexte et demander une r?ponse adapt?e ? mon niveau.",
    format: "qcm",
    choices: ["Je sais donner un contexte et demander une r?ponse adapt?e ? mon niveau.","Partager des informations sensibles pour aller plus vite.","Faire confiance ? une seule r?ponse sans recul."],
    expected: ["A"],
    comparator: "mcq_exact",
    hint: "L'IA est un outil : l'?l?ve garde l'objectif, la v?rification et la d?cision.",
    explanation: "Cette micro-comp?tence se valide quand l'?l?ve sait faire ceci : Je sais donner un contexte et demander une r?ponse adapt?e ? mon niveau.",
  },
  {
    kind: "fixed",
    id: "ia_a2_expliquer_autrement_qcm_001",
    niveau: "a2",
    matiere: "ia",
    notionId: "ia_a2_prompts",
    microId: "ia_a2_expliquer_autrement",
    difficulty: 2,
    text: "Quelle affirmation valide la micro-comp?tence A2 : Je sais demander ? l'IA d'expliquer une notion autrement.",
    format: "qcm",
    choices: ["Je sais demander ? l'IA d'expliquer une notion autrement.","Je laisse l'IA d?cider ? ma place.","Je copie la r?ponse sans v?rifier."],
    expected: ["A"],
    comparator: "mcq_exact",
    hint: "Cherche la r?ponse qui garde m?thode, jugement et responsabilit? humaine.",
    explanation: "Bonne r?ponse : Je sais demander ? l'IA d'expliquer une notion autrement.",
  },
  {
    kind: "fixed",
    id: "ia_a2_expliquer_autrement_qcm_002",
    niveau: "a2",
    matiere: "ia",
    notionId: "ia_a2_prompts",
    microId: "ia_a2_expliquer_autrement",
    difficulty: 2,
    text: "Dans une situation r?elle, quelle action correspond le mieux ? : Je sais demander ? l'IA d'expliquer une notion autrement.",
    format: "qcm",
    choices: ["Je sais demander ? l'IA d'expliquer une notion autrement.","Partager des informations sensibles pour aller plus vite.","Faire confiance ? une seule r?ponse sans recul."],
    expected: ["A"],
    comparator: "mcq_exact",
    hint: "L'IA est un outil : l'?l?ve garde l'objectif, la v?rification et la d?cision.",
    explanation: "Cette micro-comp?tence se valide quand l'?l?ve sait faire ceci : Je sais demander ? l'IA d'expliquer une notion autrement.",
  },
  {
    kind: "fixed",
    id: "ia_a2_fiche_revision_qcm_001",
    niveau: "a2",
    matiere: "ia",
    notionId: "ia_a2_reviser",
    microId: "ia_a2_fiche_revision",
    difficulty: 2,
    text: "Quelle affirmation valide la micro-comp?tence A2 : Je sais utiliser l'IA pour cr?er une fiche de r?vision.",
    format: "qcm",
    choices: ["Je sais utiliser l'IA pour cr?er une fiche de r?vision.","Je laisse l'IA d?cider ? ma place.","Je copie la r?ponse sans v?rifier."],
    expected: ["A"],
    comparator: "mcq_exact",
    hint: "Cherche la r?ponse qui garde m?thode, jugement et responsabilit? humaine.",
    explanation: "Bonne r?ponse : Je sais utiliser l'IA pour cr?er une fiche de r?vision.",
  },
  {
    kind: "fixed",
    id: "ia_a2_fiche_revision_qcm_002",
    niveau: "a2",
    matiere: "ia",
    notionId: "ia_a2_reviser",
    microId: "ia_a2_fiche_revision",
    difficulty: 2,
    text: "Dans une situation r?elle, quelle action correspond le mieux ? : Je sais utiliser l'IA pour cr?er une fiche de r?vision.",
    format: "qcm",
    choices: ["Je sais utiliser l'IA pour cr?er une fiche de r?vision.","Partager des informations sensibles pour aller plus vite.","Faire confiance ? une seule r?ponse sans recul."],
    expected: ["A"],
    comparator: "mcq_exact",
    hint: "L'IA est un outil : l'?l?ve garde l'objectif, la v?rification et la d?cision.",
    explanation: "Cette micro-comp?tence se valide quand l'?l?ve sait faire ceci : Je sais utiliser l'IA pour cr?er une fiche de r?vision.",
  },
  {
    kind: "fixed",
    id: "ia_a2_quiz_entrainement_qcm_001",
    niveau: "a2",
    matiere: "ia",
    notionId: "ia_a2_reviser",
    microId: "ia_a2_quiz_entrainement",
    difficulty: 3,
    text: "Quelle affirmation valide la micro-comp?tence A2 : Je sais demander un quiz pour m'entra?ner.",
    format: "qcm",
    choices: ["Je sais demander un quiz pour m'entra?ner.","Je laisse l'IA d?cider ? ma place.","Je copie la r?ponse sans v?rifier."],
    expected: ["A"],
    comparator: "mcq_exact",
    hint: "Cherche la r?ponse qui garde m?thode, jugement et responsabilit? humaine.",
    explanation: "Bonne r?ponse : Je sais demander un quiz pour m'entra?ner.",
  },
  {
    kind: "fixed",
    id: "ia_a2_quiz_entrainement_qcm_002",
    niveau: "a2",
    matiere: "ia",
    notionId: "ia_a2_reviser",
    microId: "ia_a2_quiz_entrainement",
    difficulty: 3,
    text: "Dans une situation r?elle, quelle action correspond le mieux ? : Je sais demander un quiz pour m'entra?ner.",
    format: "qcm",
    choices: ["Je sais demander un quiz pour m'entra?ner.","Partager des informations sensibles pour aller plus vite.","Faire confiance ? une seule r?ponse sans recul."],
    expected: ["A"],
    comparator: "mcq_exact",
    hint: "L'IA est un outil : l'?l?ve garde l'objectif, la v?rification et la d?cision.",
    explanation: "Cette micro-comp?tence se valide quand l'?l?ve sait faire ceci : Je sais demander un quiz pour m'entra?ner.",
  },
  {
    kind: "fixed",
    id: "ia_a2_aide_sans_triche_qcm_001",
    niveau: "a2",
    matiere: "ia",
    notionId: "ia_a2_reviser",
    microId: "ia_a2_aide_sans_triche",
    difficulty: 3,
    text: "Quelle affirmation valide la micro-comp?tence A2 : Je sais demander une aide ou une correction sans d?l?guer ma pens?e.",
    format: "qcm",
    choices: ["Je sais demander une aide ou une correction sans d?l?guer ma pens?e.","Je laisse l'IA d?cider ? ma place.","Je copie la r?ponse sans v?rifier."],
    expected: ["A"],
    comparator: "mcq_exact",
    hint: "Cherche la r?ponse qui garde m?thode, jugement et responsabilit? humaine.",
    explanation: "Bonne r?ponse : Je sais demander une aide ou une correction sans d?l?guer ma pens?e.",
  },
  {
    kind: "fixed",
    id: "ia_a2_aide_sans_triche_qcm_002",
    niveau: "a2",
    matiere: "ia",
    notionId: "ia_a2_reviser",
    microId: "ia_a2_aide_sans_triche",
    difficulty: 3,
    text: "Dans une situation r?elle, quelle action correspond le mieux ? : Je sais demander une aide ou une correction sans d?l?guer ma pens?e.",
    format: "qcm",
    choices: ["Je sais demander une aide ou une correction sans d?l?guer ma pens?e.","Partager des informations sensibles pour aller plus vite.","Faire confiance ? une seule r?ponse sans recul."],
    expected: ["A"],
    comparator: "mcq_exact",
    hint: "L'IA est un outil : l'?l?ve garde l'objectif, la v?rification et la d?cision.",
    explanation: "Cette micro-comp?tence se valide quand l'?l?ve sait faire ceci : Je sais demander une aide ou une correction sans d?l?guer ma pens?e.",
  },
];

export function getIaA2QuestionBank(args?: {
  notionId?: string | null;
  microId?: string | null;
}): TutorBankItemV4[] {
  let bank = iaA2QuestionBank;

  if (args?.notionId) bank = bank.filter((item) => item.notionId === args.notionId);
  if (args?.microId) bank = bank.filter((item) => item.microId === args.microId);

  return bank;
}
