import type { TutorBankItemV4 } from "@/lib/tutor-v4/types";

export const iaA2QuestionBank: TutorBankItemV4[] = [
  {
    kind: "fixed",
    id: "ia_a2_prompt_clair_qcm_001",
    niveau: "a2",
    matiere: "ia",
    notionId: "ia_a2_prompts",
    microId: "ia_a2_prompt_clair",
    difficulty: 1,
    text: "Quelle affirmation valide la micro-competence A2 : Je sais ecrire un prompt simple, clair et oriente vers un objectif.",
    format: "qcm",
    choices: ["Je sais ecrire un prompt simple, clair et oriente vers un objectif.","Je laisse l'IA decider a ma place.","Je copie la reponse sans verifier."],
    expected: ["Je sais ecrire un prompt simple, clair et oriente vers un objectif."],
    comparator: "mcq_exact",
    hint: "Cherche la reponse qui garde methode, jugement et responsabilite humaine.",
    explanation: "Bonne reponse : Je sais ecrire un prompt simple, clair et oriente vers un objectif.",
  },
  {
    kind: "fixed",
    id: "ia_a2_prompt_clair_qcm_002",
    niveau: "a2",
    matiere: "ia",
    notionId: "ia_a2_prompts",
    microId: "ia_a2_prompt_clair",
    difficulty: 1,
    text: "Dans une situation reelle, quelle action correspond le mieux a : Je sais ecrire un prompt simple, clair et oriente vers un objectif.",
    format: "qcm",
    choices: ["Je sais ecrire un prompt simple, clair et oriente vers un objectif.","Partager des informations sensibles pour aller plus vite.","Faire confiance a une seule reponse sans recul."],
    expected: ["Je sais ecrire un prompt simple, clair et oriente vers un objectif."],
    comparator: "mcq_exact",
    hint: "L'IA est un outil : l'eleve garde l'objectif, la verification et la decision.",
    explanation: "Cette micro-competence se valide quand l'eleve sait faire ceci : Je sais ecrire un prompt simple, clair et oriente vers un objectif.",
  },
  {
    kind: "fixed",
    id: "ia_a2_contexte_niveau_qcm_001",
    niveau: "a2",
    matiere: "ia",
    notionId: "ia_a2_prompts",
    microId: "ia_a2_contexte_niveau",
    difficulty: 1,
    text: "Quelle affirmation valide la micro-competence A2 : Je sais donner un contexte et demander une reponse adaptee a mon niveau.",
    format: "qcm",
    choices: ["Je sais donner un contexte et demander une reponse adaptee a mon niveau.","Je laisse l'IA decider a ma place.","Je copie la reponse sans verifier."],
    expected: ["Je sais donner un contexte et demander une reponse adaptee a mon niveau."],
    comparator: "mcq_exact",
    hint: "Cherche la reponse qui garde methode, jugement et responsabilite humaine.",
    explanation: "Bonne reponse : Je sais donner un contexte et demander une reponse adaptee a mon niveau.",
  },
  {
    kind: "fixed",
    id: "ia_a2_contexte_niveau_qcm_002",
    niveau: "a2",
    matiere: "ia",
    notionId: "ia_a2_prompts",
    microId: "ia_a2_contexte_niveau",
    difficulty: 1,
    text: "Dans une situation reelle, quelle action correspond le mieux a : Je sais donner un contexte et demander une reponse adaptee a mon niveau.",
    format: "qcm",
    choices: ["Je sais donner un contexte et demander une reponse adaptee a mon niveau.","Partager des informations sensibles pour aller plus vite.","Faire confiance a une seule reponse sans recul."],
    expected: ["Je sais donner un contexte et demander une reponse adaptee a mon niveau."],
    comparator: "mcq_exact",
    hint: "L'IA est un outil : l'eleve garde l'objectif, la verification et la decision.",
    explanation: "Cette micro-competence se valide quand l'eleve sait faire ceci : Je sais donner un contexte et demander une reponse adaptee a mon niveau.",
  },
  {
    kind: "fixed",
    id: "ia_a2_expliquer_autrement_qcm_001",
    niveau: "a2",
    matiere: "ia",
    notionId: "ia_a2_prompts",
    microId: "ia_a2_expliquer_autrement",
    difficulty: 2,
    text: "Quelle affirmation valide la micro-competence A2 : Je sais demander a l'IA d'expliquer une notion autrement.",
    format: "qcm",
    choices: ["Je sais demander a l'IA d'expliquer une notion autrement.","Je laisse l'IA decider a ma place.","Je copie la reponse sans verifier."],
    expected: ["Je sais demander a l'IA d'expliquer une notion autrement."],
    comparator: "mcq_exact",
    hint: "Cherche la reponse qui garde methode, jugement et responsabilite humaine.",
    explanation: "Bonne reponse : Je sais demander a l'IA d'expliquer une notion autrement.",
  },
  {
    kind: "fixed",
    id: "ia_a2_expliquer_autrement_qcm_002",
    niveau: "a2",
    matiere: "ia",
    notionId: "ia_a2_prompts",
    microId: "ia_a2_expliquer_autrement",
    difficulty: 2,
    text: "Dans une situation reelle, quelle action correspond le mieux a : Je sais demander a l'IA d'expliquer une notion autrement.",
    format: "qcm",
    choices: ["Je sais demander a l'IA d'expliquer une notion autrement.","Partager des informations sensibles pour aller plus vite.","Faire confiance a une seule reponse sans recul."],
    expected: ["Je sais demander a l'IA d'expliquer une notion autrement."],
    comparator: "mcq_exact",
    hint: "L'IA est un outil : l'eleve garde l'objectif, la verification et la decision.",
    explanation: "Cette micro-competence se valide quand l'eleve sait faire ceci : Je sais demander a l'IA d'expliquer une notion autrement.",
  },
  {
    kind: "fixed",
    id: "ia_a2_fiche_revision_qcm_001",
    niveau: "a2",
    matiere: "ia",
    notionId: "ia_a2_reviser",
    microId: "ia_a2_fiche_revision",
    difficulty: 2,
    text: "Quelle affirmation valide la micro-competence A2 : Je sais utiliser l'IA pour creer une fiche de revision.",
    format: "qcm",
    choices: ["Je sais utiliser l'IA pour creer une fiche de revision.","Je laisse l'IA decider a ma place.","Je copie la reponse sans verifier."],
    expected: ["Je sais utiliser l'IA pour creer une fiche de revision."],
    comparator: "mcq_exact",
    hint: "Cherche la reponse qui garde methode, jugement et responsabilite humaine.",
    explanation: "Bonne reponse : Je sais utiliser l'IA pour creer une fiche de revision.",
  },
  {
    kind: "fixed",
    id: "ia_a2_fiche_revision_qcm_002",
    niveau: "a2",
    matiere: "ia",
    notionId: "ia_a2_reviser",
    microId: "ia_a2_fiche_revision",
    difficulty: 2,
    text: "Dans une situation reelle, quelle action correspond le mieux a : Je sais utiliser l'IA pour creer une fiche de revision.",
    format: "qcm",
    choices: ["Je sais utiliser l'IA pour creer une fiche de revision.","Partager des informations sensibles pour aller plus vite.","Faire confiance a une seule reponse sans recul."],
    expected: ["Je sais utiliser l'IA pour creer une fiche de revision."],
    comparator: "mcq_exact",
    hint: "L'IA est un outil : l'eleve garde l'objectif, la verification et la decision.",
    explanation: "Cette micro-competence se valide quand l'eleve sait faire ceci : Je sais utiliser l'IA pour creer une fiche de revision.",
  },
  {
    kind: "fixed",
    id: "ia_a2_quiz_entrainement_qcm_001",
    niveau: "a2",
    matiere: "ia",
    notionId: "ia_a2_reviser",
    microId: "ia_a2_quiz_entrainement",
    difficulty: 3,
    text: "Quelle affirmation valide la micro-competence A2 : Je sais demander un quiz pour m'entrainer.",
    format: "qcm",
    choices: ["Je sais demander un quiz pour m'entrainer.","Je laisse l'IA decider a ma place.","Je copie la reponse sans verifier."],
    expected: ["Je sais demander un quiz pour m'entrainer."],
    comparator: "mcq_exact",
    hint: "Cherche la reponse qui garde methode, jugement et responsabilite humaine.",
    explanation: "Bonne reponse : Je sais demander un quiz pour m'entrainer.",
  },
  {
    kind: "fixed",
    id: "ia_a2_quiz_entrainement_qcm_002",
    niveau: "a2",
    matiere: "ia",
    notionId: "ia_a2_reviser",
    microId: "ia_a2_quiz_entrainement",
    difficulty: 3,
    text: "Dans une situation reelle, quelle action correspond le mieux a : Je sais demander un quiz pour m'entrainer.",
    format: "qcm",
    choices: ["Je sais demander un quiz pour m'entrainer.","Partager des informations sensibles pour aller plus vite.","Faire confiance a une seule reponse sans recul."],
    expected: ["Je sais demander un quiz pour m'entrainer."],
    comparator: "mcq_exact",
    hint: "L'IA est un outil : l'eleve garde l'objectif, la verification et la decision.",
    explanation: "Cette micro-competence se valide quand l'eleve sait faire ceci : Je sais demander un quiz pour m'entrainer.",
  },
  {
    kind: "fixed",
    id: "ia_a2_aide_sans_triche_qcm_001",
    niveau: "a2",
    matiere: "ia",
    notionId: "ia_a2_reviser",
    microId: "ia_a2_aide_sans_triche",
    difficulty: 3,
    text: "Quelle affirmation valide la micro-competence A2 : Je sais demander une aide ou une correction sans deleguer ma pensee.",
    format: "qcm",
    choices: ["Je sais demander une aide ou une correction sans deleguer ma pensee.","Je laisse l'IA decider a ma place.","Je copie la reponse sans verifier."],
    expected: ["Je sais demander une aide ou une correction sans deleguer ma pensee."],
    comparator: "mcq_exact",
    hint: "Cherche la reponse qui garde methode, jugement et responsabilite humaine.",
    explanation: "Bonne reponse : Je sais demander une aide ou une correction sans deleguer ma pensee.",
  },
  {
    kind: "fixed",
    id: "ia_a2_aide_sans_triche_qcm_002",
    niveau: "a2",
    matiere: "ia",
    notionId: "ia_a2_reviser",
    microId: "ia_a2_aide_sans_triche",
    difficulty: 3,
    text: "Dans une situation reelle, quelle action correspond le mieux a : Je sais demander une aide ou une correction sans deleguer ma pensee.",
    format: "qcm",
    choices: ["Je sais demander une aide ou une correction sans deleguer ma pensee.","Partager des informations sensibles pour aller plus vite.","Faire confiance a une seule reponse sans recul."],
    expected: ["Je sais demander une aide ou une correction sans deleguer ma pensee."],
    comparator: "mcq_exact",
    hint: "L'IA est un outil : l'eleve garde l'objectif, la verification et la decision.",
    explanation: "Cette micro-competence se valide quand l'eleve sait faire ceci : Je sais demander une aide ou une correction sans deleguer ma pensee.",
  },
];

export function getIaA2QuestionBank(args?: {
  notionId?: string | null;
  microId?: string | null;
}): TutorBankItemV4[] {
  let bank = iaA2QuestionBank;

  if (args?.notionId) bank = bank.filter((item) => item.notionId === args.notionId);
  if (args?.microId) bank = bank.filter((item) => item.microId === args.microId);

  return bank;
}
