import type { CoachBrevetDay } from "./types";

export const coachBrevetWeekly: CoachBrevetDay[] = [
  // SEMAINE 1 — Nombres et calculs
  {
    dayNumber: 1,
    title: "Jour 1 — Fractions",
    mainNotion: "fractions",
    description: "Maîtrise les opérations sur les fractions : addition, soustraction, multiplication, division et simplification.",
    itemIds: ["brevet-frac-001", "brevet-frac-002", "brevet-frac-004", "brevet-frac-005"],
    problemId: undefined,
  },
  {
    dayNumber: 2,
    title: "Jour 2 — Puissances",
    mainNotion: "puissances",
    description: "Règles de calcul avec les puissances, puissances négatives et notation scientifique.",
    itemIds: ["brevet-puis-001", "brevet-puis-002", "brevet-puis-003", "brevet-puis-005"],
  },
  {
    dayNumber: 3,
    title: "Jour 3 — Fractions approfondies",
    mainNotion: "fractions",
    description: "Comparaison de fractions, calculs mixtes et expressions combinées.",
    itemIds: ["brevet-frac-003", "brevet-frac-006", "brevet-frac-007"],
  },
  {
    dayNumber: 4,
    title: "Jour 4 — Puissances avancées",
    mainNotion: "puissances",
    description: "Notation scientifique, quotients de puissances et pièges classiques.",
    itemIds: ["brevet-puis-004", "brevet-puis-006", "brevet-puis-007"],
  },
  {
    dayNumber: 5,
    title: "Jour 5 — Révision calcul numérique",
    mainNotion: "fractions",
    description: "Révision globale des fractions et puissances. Premier mini-bilan.",
    itemIds: ["brevet-frac-001", "brevet-frac-007", "brevet-puis-002", "brevet-puis-006"],
  },

  // SEMAINE 2 — Algèbre
  {
    dayNumber: 6,
    title: "Jour 6 — Calcul littéral",
    mainNotion: "calcul_litteral",
    description: "Développement, réduction et factorisation d'expressions algébriques.",
    itemIds: ["brevet-alg-001", "brevet-alg-002", "brevet-alg-003"],
  },
  {
    dayNumber: 7,
    title: "Jour 7 — Équations",
    mainNotion: "equations",
    description: "Équations du 1er degré avec ou sans parenthèses.",
    itemIds: ["brevet-alg-004", "brevet-alg-005"],
    expressSubjectId: "brevet-se-001",
  },
  {
    dayNumber: 8,
    title: "Jour 8 — Systèmes d'équations",
    mainNotion: "equations",
    description: "Résolution de systèmes de deux équations à deux inconnues.",
    itemIds: ["brevet-alg-006"],
    problemId: "brevet-pb-003",
  },
  {
    dayNumber: 9,
    title: "Jour 9 — Inéquations",
    mainNotion: "inegalites",
    description: "Résolution d'inéquations et piège du signe négatif.",
    itemIds: ["brevet-alg-007", "brevet-alg-008"],
  },
  {
    dayNumber: 10,
    title: "Jour 10 — Révision algèbre",
    mainNotion: "calcul_litteral",
    description: "Bilan algèbre : identités remarquables, équations, inéquations.",
    itemIds: ["brevet-alg-002", "brevet-alg-003", "brevet-alg-005", "brevet-alg-008"],
  },

  // SEMAINE 3 — Géométrie
  {
    dayNumber: 11,
    title: "Jour 11 — Théorème de Pythagore",
    mainNotion: "pythagore",
    description: "Calcul de longueurs dans un triangle rectangle et réciproque de Pythagore.",
    itemIds: ["brevet-geo-001", "brevet-geo-002"],
    problemId: "brevet-pb-001",
  },
  {
    dayNumber: 12,
    title: "Jour 12 — Trigonométrie",
    mainNotion: "trigonometrie",
    description: "sin, cos, tan dans un triangle rectangle pour trouver une longueur ou un angle.",
    itemIds: ["brevet-geo-003", "brevet-geo-004"],
  },
  {
    dayNumber: 13,
    title: "Jour 13 — Théorème de Thalès",
    mainNotion: "thales",
    description: "Application du théorème de Thalès pour calculer des longueurs inconnues.",
    itemIds: ["brevet-geo-005"],
    problemId: "brevet-pb-005",
  },
  {
    dayNumber: 14,
    title: "Jour 14 — Transformations et espace",
    mainNotion: "transformations",
    description: "Symétries, translations, rotations. Volumes de solides de l'espace.",
    itemIds: ["brevet-geo-006", "brevet-geo-007", "brevet-geo-008"],
    expressSubjectId: "brevet-se-002",
  },
  {
    dayNumber: 15,
    title: "Jour 15 — Révision géométrie",
    mainNotion: "pythagore",
    description: "Bilan géométrie : Pythagore, trigonométrie, Thalès, volumes.",
    itemIds: ["brevet-geo-001", "brevet-geo-003", "brevet-geo-005", "brevet-geo-007"],
  },

  // SEMAINE 4 — Fonctions et proportionnalité
  {
    dayNumber: 16,
    title: "Jour 16 — Fonctions affines",
    mainNotion: "fonctions",
    description: "Fonctions linéaires et affines, lecture graphique, pente et ordonnée à l'origine.",
    itemIds: ["brevet-fonc-001", "brevet-fonc-002", "brevet-fonc-003"],
  },
  {
    dayNumber: 17,
    title: "Jour 17 — Fonctions du second degré",
    mainNotion: "fonctions",
    description: "Fonctions de la forme x², tableau de valeurs, parabole.",
    itemIds: ["brevet-fonc-004", "brevet-fonc-005"],
    problemId: "brevet-pb-006",
  },
  {
    dayNumber: 18,
    title: "Jour 18 — Proportionnalité",
    mainNotion: "proportionnalite",
    description: "Règle de trois, coefficient de proportionnalité, tableaux de proportionnalité.",
    itemIds: ["brevet-prop-001", "brevet-prop-002", "brevet-prop-003"],
  },
  {
    dayNumber: 19,
    title: "Jour 19 — Pourcentages",
    mainNotion: "pourcentages",
    description: "Calculs de pourcentages, augmentations, réductions et taux d'évolution.",
    itemIds: ["brevet-prop-004", "brevet-prop-005", "brevet-prop-006", "brevet-prop-007"],
    problemId: "brevet-pb-002",
  },
  {
    dayNumber: 20,
    title: "Jour 20 — Révision fonctions",
    mainNotion: "fonctions",
    description: "Bilan fonctions et proportionnalité.",
    itemIds: ["brevet-fonc-002", "brevet-fonc-005", "brevet-fonc-006", "brevet-prop-007"],
  },

  // SEMAINE 5 — Statistiques et probabilités
  {
    dayNumber: 21,
    title: "Jour 21 — Statistiques descriptives",
    mainNotion: "statistiques",
    description: "Moyenne, médiane, étendue et lecture de tableaux ou diagrammes.",
    itemIds: ["brevet-stat-001", "brevet-stat-002", "brevet-stat-003"],
  },
  {
    dayNumber: 22,
    title: "Jour 22 — Moyenne pondérée",
    mainNotion: "statistiques",
    description: "Calcul de moyenne avec coefficients.",
    itemIds: ["brevet-stat-004"],
  },
  {
    dayNumber: 23,
    title: "Jour 23 — Probabilités",
    mainNotion: "probabilites",
    description: "Calcul de probabilités, complémentaire, événements.",
    itemIds: ["brevet-stat-005", "brevet-stat-007"],
    problemId: "brevet-pb-004",
  },
  {
    dayNumber: 24,
    title: "Jour 24 — Probabilités avec arbre",
    mainNotion: "probabilites",
    description: "Arbres de probabilités, tirages sans remise.",
    itemIds: ["brevet-stat-006"],
    expressSubjectId: "brevet-se-003",
  },
  {
    dayNumber: 25,
    title: "Jour 25 — Révision stats & probas",
    mainNotion: "statistiques",
    description: "Bilan statistiques et probabilités.",
    itemIds: ["brevet-stat-001", "brevet-stat-002", "brevet-stat-005", "brevet-stat-006"],
  },

  // SEMAINE 6 — Révisions et synthèse finale
  {
    dayNumber: 26,
    title: "Jour 26 — Synthèse calcul",
    mainNotion: "synthese",
    description: "Retour sur fractions, puissances et algèbre. Pièges les plus fréquents.",
    itemIds: ["brevet-frac-004", "brevet-puis-005", "brevet-alg-008"],
  },
  {
    dayNumber: 27,
    title: "Jour 27 — Synthèse géométrie",
    mainNotion: "synthese",
    description: "Pythagore, Thalès, trigonométrie et volumes — tour d'horizon.",
    itemIds: ["brevet-geo-001", "brevet-geo-005", "brevet-geo-008"],
  },
  {
    dayNumber: 28,
    title: "Jour 28 — Synthèse fonctions & stats",
    mainNotion: "synthese",
    description: "Fonctions, pourcentages, probabilités — révision finale.",
    itemIds: ["brevet-fonc-006", "brevet-prop-007", "brevet-stat-006"],
  },
  {
    dayNumber: 29,
    title: "Jour 29 — Entraînement conditions brevet",
    mainNotion: "synthese",
    description: "Simule les conditions réelles du brevet : 2h, calculatrice autorisée.",
    itemIds: ["brevet-alg-006", "brevet-geo-003", "brevet-fonc-003", "brevet-stat-004"],
    expressSubjectId: "brevet-se-004",
  },
  {
    dayNumber: 30,
    title: "Jour 30 — Veille du brevet 🎯",
    mainNotion: "synthese",
    description: "Dernière révision légère. Relis tes fiches, sois serein(e). Tu es prêt(e) !",
    itemIds: ["brevet-frac-001", "brevet-puis-003", "brevet-alg-004", "brevet-geo-001", "brevet-stat-005"],
  },
];
