import type { MotDico } from "../types";

// 🔢 Dico Maths 6e — 50 mots essentiels
// 10 nombres/calcul · 15 géométrie · 10 grandeurs/mesures · 10 données/proba · 5 consignes
// Chaque mot entraîne un geste numérique (saisie clavier, clic, menu déroulant, association).

export const motsMaths6e: MotDico[] = [
  // ─────────────────────────── NOMBRES & CALCUL (10) ───────────────────────────
  {
    id: "m6-chiffre",
    mot: "Chiffre",
    famille: "nombres-calcul",
    definition: "Un des dix symboles (0, 1, 2, … 9) qui servent à écrire les nombres.",
    defi: {
      geste: "saisie",
      question: "Dans le nombre 357, tape le chiffre des dizaines.",
      reponse: "5",
      aide: "Les dizaines, c'est le 2e chiffre en partant de la droite.",
    },
  },
  {
    id: "m6-nombre-entier",
    mot: "Nombre entier",
    famille: "nombres-calcul",
    definition: "Un nombre sans virgule, comme 0, 1, 17 ou 245.",
    defi: {
      geste: "menu",
      question: "Choisis le nombre entier.",
      options: ["12,5", "3/4", "48", "0,7"],
      bonne: "48",
    },
  },
  {
    id: "m6-nombre-decimal",
    mot: "Nombre décimal",
    famille: "nombres-calcul",
    definition: "Un nombre avec une virgule, comme 3,5 ou 12,07.",
    defi: {
      geste: "clic",
      question: "Clique sur le nombre décimal.",
      choix: ["7", "2,4", "19", "100"],
      bonne: "2,4",
    },
  },
  {
    id: "m6-fraction",
    mot: "Fraction",
    famille: "nombres-calcul",
    definition: "Une écriture comme 3/4 qui partage une quantité en parts égales.",
    defi: {
      geste: "clic",
      question: "Quelle écriture est une fraction ?",
      choix: ["2,5", "3/4", "17", "12 cm"],
      bonne: "3/4",
    },
  },
  {
    id: "m6-numerateur",
    mot: "Numérateur",
    famille: "nombres-calcul",
    definition: "Le nombre du haut d'une fraction (au-dessus du trait).",
    defi: {
      geste: "saisie",
      question: "Dans la fraction 5/8, tape le numérateur.",
      reponse: "5",
    },
  },
  {
    id: "m6-denominateur",
    mot: "Dénominateur",
    famille: "nombres-calcul",
    definition: "Le nombre du bas d'une fraction (sous le trait).",
    defi: {
      geste: "saisie",
      question: "Dans la fraction 5/8, tape le dénominateur.",
      reponse: "8",
    },
  },
  {
    id: "m6-multiple",
    mot: "Multiple",
    famille: "nombres-calcul",
    definition: "Un multiple de 5 s'obtient en multipliant 5 par un entier : 5, 10, 15…",
    defi: {
      geste: "clic",
      question: "Clique sur un multiple de 5.",
      choix: ["12", "20", "18", "7"],
      bonne: "20",
    },
  },
  {
    id: "m6-diviseur",
    mot: "Diviseur",
    famille: "nombres-calcul",
    definition: "Un diviseur d'un nombre le divise sans reste. 4 est un diviseur de 12.",
    defi: {
      geste: "menu",
      question: "Choisis un diviseur de 12.",
      options: ["5", "8", "4", "7"],
      bonne: "4",
    },
  },
  {
    id: "m6-quotient",
    mot: "Quotient",
    famille: "nombres-calcul",
    definition: "Le résultat d'une division. Dans 12 : 3 = 4, le quotient est 4.",
    defi: {
      geste: "saisie",
      question: "Tape le quotient de 20 par 4.",
      reponse: "5",
    },
  },
  {
    id: "m6-produit",
    mot: "Produit",
    famille: "nombres-calcul",
    definition: "Le résultat d'une multiplication. Le produit de 6 par 7 est 42.",
    defi: {
      geste: "saisie",
      question: "Tape le produit de 8 × 5.",
      reponse: "40",
    },
  },

  // ─────────────────────────────── GÉOMÉTRIE (15) ───────────────────────────────
  {
    id: "m6-point",
    mot: "Point",
    famille: "geometrie",
    definition: "Un endroit précis, nommé par une lettre majuscule (A, B…).",
    defi: {
      geste: "clic",
      question: "Comment nomme-t-on un point ?",
      choix: ["Par une lettre minuscule", "Par une lettre majuscule", "Par un chiffre", "Par une couleur"],
      bonne: "Par une lettre majuscule",
    },
  },
  {
    id: "m6-segment",
    mot: "Segment",
    famille: "geometrie",
    definition: "Une portion de droite limitée par deux points.",
    defi: {
      geste: "menu",
      question: "Un segment [AB] est limité par…",
      options: ["un seul point", "deux points", "aucun point", "trois points"],
      bonne: "deux points",
    },
  },
  {
    id: "m6-droite",
    mot: "Droite",
    famille: "geometrie",
    definition: "Une ligne droite illimitée des deux côtés.",
    defi: {
      geste: "clic",
      question: "Une droite est…",
      choix: ["limitée des deux côtés", "illimitée des deux côtés", "limitée d'un seul côté", "courbée"],
      bonne: "illimitée des deux côtés",
    },
  },
  {
    id: "m6-demi-droite",
    mot: "Demi-droite",
    famille: "geometrie",
    definition: "Une ligne droite qui a un début (une origine) mais pas de fin.",
    defi: {
      geste: "menu",
      question: "Une demi-droite a…",
      options: ["deux extrémités", "aucune origine", "une origine et pas de fin", "une longueur fixe"],
      bonne: "une origine et pas de fin",
    },
  },
  {
    id: "m6-milieu",
    mot: "Milieu",
    famille: "geometrie",
    definition: "Le point au centre d'un segment, à égale distance des deux bouts.",
    defi: {
      geste: "saisie",
      question: "Le milieu partage un segment en deux parts é____. Tape le mot.",
      reponse: "égales",
      aide: "On parle de deux parts qui ont la même longueur.",
    },
  },
  {
    id: "m6-perpendiculaires",
    mot: "Perpendiculaires",
    famille: "geometrie",
    definition: "Deux droites qui se croisent en formant un angle droit.",
    defi: {
      geste: "clic",
      question: "Deux droites perpendiculaires forment un angle…",
      choix: ["plat", "droit", "aigu", "obtus"],
      bonne: "droit",
    },
  },
  {
    id: "m6-paralleles",
    mot: "Parallèles",
    famille: "geometrie",
    definition: "Deux droites qui ne se croisent jamais, toujours à la même distance.",
    defi: {
      geste: "menu",
      question: "Deux droites parallèles…",
      options: ["se croisent en un point", "se croisent en deux points", "ne se croisent jamais", "forment un angle droit"],
      bonne: "ne se croisent jamais",
    },
  },
  {
    id: "m6-angle",
    mot: "Angle",
    famille: "geometrie",
    definition: "L'écartement entre deux demi-droites de même origine.",
    defi: {
      geste: "saisie",
      question: "On mesure un angle en… Tape l'unité.",
      reponse: "degrés",
      aide: "Le symbole de cette unité est le petit rond : °.",
    },
  },
  {
    id: "m6-angle-droit",
    mot: "Angle droit",
    famille: "geometrie",
    definition: "Un angle qui mesure 90°, comme le coin d'une feuille.",
    defi: {
      geste: "saisie",
      question: "Un angle droit mesure … degrés. Tape le nombre.",
      reponse: "90",
    },
  },
  {
    id: "m6-polygone",
    mot: "Polygone",
    famille: "geometrie",
    definition: "Une figure fermée formée uniquement de segments (les côtés).",
    defi: {
      geste: "clic",
      question: "Clique sur un polygone.",
      choix: ["un cercle", "un triangle", "une courbe", "un point"],
      bonne: "un triangle",
    },
  },
  {
    id: "m6-quadrilatere",
    mot: "Quadrilatère",
    famille: "geometrie",
    definition: "Un polygone à 4 côtés.",
    defi: {
      geste: "saisie",
      question: "Combien de côtés a un quadrilatère ? Tape le nombre.",
      reponse: "4",
    },
  },
  {
    id: "m6-rectangle",
    mot: "Rectangle",
    famille: "geometrie",
    definition: "Un quadrilatère avec 4 angles droits.",
    defi: {
      geste: "menu",
      question: "Un rectangle a 4 angles…",
      options: ["aigus", "droits", "plats", "obtus"],
      bonne: "droits",
    },
  },
  {
    id: "m6-carre",
    mot: "Carré",
    famille: "geometrie",
    definition: "Un rectangle dont les 4 côtés ont la même longueur.",
    defi: {
      geste: "clic",
      question: "Un carré est un rectangle qui a…",
      choix: ["des côtés tous égaux", "un seul angle droit", "trois côtés", "des côtés courbés"],
      bonne: "des côtés tous égaux",
    },
  },
  {
    id: "m6-triangle",
    mot: "Triangle",
    famille: "geometrie",
    definition: "Un polygone à 3 côtés.",
    defi: {
      geste: "saisie",
      question: "Combien de côtés a un triangle ? Tape le nombre.",
      reponse: "3",
    },
  },
  {
    id: "m6-cercle",
    mot: "Cercle",
    famille: "geometrie",
    definition: "Une courbe fermée dont tous les points sont à la même distance du centre.",
    defi: {
      geste: "menu",
      question: "Le segment qui va du centre au cercle s'appelle le…",
      options: ["diamètre", "rayon", "périmètre", "côté"],
      bonne: "rayon",
    },
  },

  // ─────────────────────────── GRANDEURS & MESURES (10) ───────────────────────────
  {
    id: "m6-longueur",
    mot: "Longueur",
    famille: "grandeurs-mesures",
    definition: "La mesure d'une distance, par exemple en cm ou en m.",
    defi: {
      geste: "menu",
      question: "Quelle unité mesure une longueur ?",
      options: ["le litre", "le mètre", "le gramme", "la seconde"],
      bonne: "le mètre",
    },
  },
  {
    id: "m6-perimetre",
    mot: "Périmètre",
    famille: "grandeurs-mesures",
    definition: "La longueur du tour d'une figure.",
    defi: {
      geste: "saisie",
      question: "Un carré de côté 5 cm. Tape son périmètre en cm.",
      reponse: "20",
      aide: "Périmètre du carré = 4 × côté.",
    },
  },
  {
    id: "m6-aire",
    mot: "Aire",
    famille: "grandeurs-mesures",
    definition: "La mesure de la surface d'une figure (en cm², m²…).",
    defi: {
      geste: "clic",
      question: "L'aire d'un rectangle se calcule par…",
      choix: ["longueur + largeur", "longueur × largeur", "côté × 4", "2 × longueur"],
      bonne: "longueur × largeur",
    },
  },
  {
    id: "m6-duree",
    mot: "Durée",
    famille: "grandeurs-mesures",
    definition: "Le temps écoulé, mesuré en heures, minutes, secondes.",
    defi: {
      geste: "saisie",
      question: "Combien de minutes dans 1 heure ? Tape le nombre.",
      reponse: "60",
    },
  },
  {
    id: "m6-masse",
    mot: "Masse",
    famille: "grandeurs-mesures",
    definition: "La quantité de matière d'un objet, en grammes ou kilogrammes.",
    defi: {
      geste: "menu",
      question: "Quelle unité mesure une masse ?",
      options: ["le mètre", "le litre", "le gramme", "le degré"],
      bonne: "le gramme",
    },
  },
  {
    id: "m6-contenance",
    mot: "Contenance",
    famille: "grandeurs-mesures",
    definition: "La quantité de liquide que peut contenir un récipient (en litres).",
    defi: {
      geste: "clic",
      question: "Quelle unité mesure une contenance ?",
      choix: ["le mètre", "le litre", "le gramme", "la seconde"],
      bonne: "le litre",
    },
  },
  {
    id: "m6-unite",
    mot: "Unité de mesure",
    famille: "grandeurs-mesures",
    definition: "Le mot qui précise une mesure : cm, kg, L, min…",
    defi: {
      geste: "clic",
      question: "Clique sur une unité de mesure.",
      choix: ["12", "kg", "rectangle", "×"],
      bonne: "kg",
    },
  },
  {
    id: "m6-metre",
    mot: "Mètre",
    famille: "grandeurs-mesures",
    definition: "L'unité principale de longueur. Symbole : m.",
    defi: {
      geste: "saisie",
      question: "Combien de centimètres dans 1 mètre ? Tape le nombre.",
      reponse: "100",
    },
  },
  {
    id: "m6-kilogramme",
    mot: "Kilogramme",
    famille: "grandeurs-mesures",
    definition: "Une unité de masse. 1 kg = 1000 g. Symbole : kg.",
    defi: {
      geste: "saisie",
      question: "Combien de grammes dans 1 kilogramme ? Tape le nombre.",
      reponse: "1000",
    },
  },
  {
    id: "m6-litre",
    mot: "Litre",
    famille: "grandeurs-mesures",
    definition: "Une unité de contenance. Symbole : L.",
    defi: {
      geste: "menu",
      question: "Le litre mesure…",
      options: ["une longueur", "une masse", "une contenance", "une durée"],
      bonne: "une contenance",
    },
  },

  // ─────────────────────────── DONNÉES & PROBABILITÉS (10) ───────────────────────────
  {
    id: "m6-donnee",
    mot: "Donnée",
    famille: "donnees-proba",
    definition: "Une information chiffrée que l'on recueille (nombre, mesure…).",
    defi: {
      geste: "clic",
      question: "Une donnée, c'est…",
      choix: ["une information chiffrée", "une couleur", "un dessin libre", "une opinion"],
      bonne: "une information chiffrée",
    },
  },
  {
    id: "m6-tableau",
    mot: "Tableau",
    famille: "donnees-proba",
    definition: "Une grille de lignes et de colonnes pour ranger des données.",
    defi: {
      geste: "menu",
      question: "Un tableau range les données en…",
      options: ["lignes et colonnes", "cercles", "courbes", "piles"],
      bonne: "lignes et colonnes",
    },
  },
  {
    id: "m6-graphique",
    mot: "Graphique",
    famille: "donnees-proba",
    definition: "Un dessin qui représente des données pour mieux les lire.",
    defi: {
      geste: "clic",
      question: "À quoi sert un graphique ?",
      choix: ["à cacher les données", "à représenter des données", "à calculer une aire", "à mesurer un angle"],
      bonne: "à représenter des données",
    },
  },
  {
    id: "m6-diagramme-barres",
    mot: "Diagramme en barres",
    famille: "donnees-proba",
    definition: "Un graphique où chaque valeur est représentée par une barre.",
    defi: {
      geste: "menu",
      question: "Dans un diagramme en barres, plus la barre est haute, plus la valeur est…",
      options: ["petite", "grande", "nulle", "négative"],
      bonne: "grande",
    },
  },
  {
    id: "m6-effectif",
    mot: "Effectif",
    famille: "donnees-proba",
    definition: "Le nombre de fois qu'une valeur apparaît.",
    defi: {
      geste: "saisie",
      question: "7 élèves aiment le bleu. Tape l'effectif du bleu.",
      reponse: "7",
    },
  },
  {
    id: "m6-abscisse",
    mot: "Abscisse",
    famille: "donnees-proba",
    definition: "La position horizontale d'un point (sur l'axe horizontal).",
    defi: {
      geste: "menu",
      question: "L'abscisse se lit sur l'axe…",
      options: ["vertical", "horizontal", "incliné", "circulaire"],
      bonne: "horizontal",
    },
  },
  {
    id: "m6-ordonnee",
    mot: "Ordonnée",
    famille: "donnees-proba",
    definition: "La position verticale d'un point (sur l'axe vertical).",
    defi: {
      geste: "menu",
      question: "L'ordonnée se lit sur l'axe…",
      options: ["horizontal", "vertical", "des x", "circulaire"],
      bonne: "vertical",
    },
  },
  {
    id: "m6-axe-gradue",
    mot: "Axe gradué",
    famille: "donnees-proba",
    definition: "Une droite avec des repères réguliers pour lire des nombres.",
    defi: {
      geste: "clic",
      question: "Un axe gradué sert à…",
      choix: ["repérer des nombres", "colorier", "mesurer une masse", "tracer un cercle"],
      bonne: "repérer des nombres",
    },
  },
  {
    id: "m6-legende",
    mot: "Légende",
    famille: "donnees-proba",
    definition: "Le texte qui explique les couleurs ou symboles d'un graphique.",
    defi: {
      geste: "clic",
      question: "La légende d'un graphique sert à…",
      choix: ["décorer", "expliquer les couleurs et symboles", "calculer", "cacher les données"],
      bonne: "expliquer les couleurs et symboles",
    },
  },
  {
    id: "m6-hasard",
    mot: "Hasard",
    famille: "donnees-proba",
    definition: "Ce qui donne un résultat imprévisible, comme lancer un dé.",
    defi: {
      geste: "menu",
      question: "Lancer un dé est une situation de…",
      options: ["certitude", "hasard", "mesure", "calcul"],
      bonne: "hasard",
    },
  },

  // ──────────────────────────── MOTS-CONSIGNES (5) ────────────────────────────
  {
    id: "m6-choisir",
    mot: "Choisir",
    famille: "consignes",
    definition: "Sélectionner la bonne réponse parmi plusieurs propositions.",
    defi: {
      geste: "clic",
      question: "CHOISIS la bonne réponse : 6 × 4 = ?",
      choix: ["24", "10", "18", "64"],
      bonne: "24",
    },
  },
  {
    id: "m6-completer",
    mot: "Compléter",
    famille: "consignes",
    definition: "Ajouter ce qui manque pour finir un calcul, une phrase, un tableau.",
    defi: {
      geste: "saisie",
      question: "COMPLÈTE : 7 + … = 10. Tape le nombre manquant.",
      reponse: "3",
    },
  },
  {
    id: "m6-associer",
    mot: "Associer",
    famille: "consignes",
    definition: "Relier deux éléments qui vont ensemble (un mot et sa définition).",
    defi: {
      geste: "association",
      question: "ASSOCIE le mot à sa définition. « Carré » = ?",
      choix: ["4 côtés égaux et 4 angles droits", "3 côtés", "une courbe fermée", "une seule droite"],
      bonne: "4 côtés égaux et 4 angles droits",
    },
  },
  {
    id: "m6-justifier",
    mot: "Justifier",
    famille: "consignes",
    definition: "Expliquer pourquoi, donner la raison de sa réponse.",
    defi: {
      geste: "menu",
      question: "JUSTIFIE : pourquoi 12 est-il pair ? Choisis la bonne raison.",
      options: ["parce qu'il est grand", "parce qu'il se termine par un chiffre pair", "parce qu'il est rouge", "parce qu'on l'a dit"],
      bonne: "parce qu'il se termine par un chiffre pair",
    },
  },
  {
    id: "m6-calculer",
    mot: "Calculer",
    famille: "consignes",
    definition: "Trouver un résultat en faisant une opération.",
    defi: {
      geste: "saisie",
      question: "CALCULE : 15 + 27. Tape le résultat.",
      reponse: "42",
    },
  },
];
