import type { MotDico } from "../types";

// 📖 Dico Français 6e — 50 mots essentiels
// 12 nature des mots · 8 fonctions · 10 conjugaison · 10 orthographe/lexique
// · 5 texte/compréhension · 5 consignes
// Chaque mot entraîne un geste numérique (saisie clavier, clic, menu déroulant, association).

export const motsFrancais6e: MotDico[] = [
  // ─────────────────────────── NATURE DES MOTS (12) ───────────────────────────
  {
    id: "f6-nom",
    mot: "Nom",
    famille: "gram-nature",
    definition: "Un mot qui désigne une personne, un animal, une chose ou une idée.",
    defi: {
      geste: "menu",
      question: "Choisis le nom.",
      options: ["manger", "chien", "vite", "beau"],
      bonne: "chien",
    },
  },
  {
    id: "f6-nom-commun",
    mot: "Nom commun",
    famille: "gram-nature",
    definition: "Un nom général (chat, ville, table), sans majuscule.",
    defi: {
      geste: "menu",
      question: "Choisis le nom commun.",
      options: ["Paris", "Léa", "table", "France"],
      bonne: "table",
    },
  },
  {
    id: "f6-nom-propre",
    mot: "Nom propre",
    famille: "gram-nature",
    definition: "Un nom qui désigne une personne ou un lieu précis, avec une majuscule (Paris, Léa).",
    defi: {
      geste: "clic",
      question: "Clique sur le nom propre.",
      choix: ["Marie", "ville", "chien", "table"],
      bonne: "Marie",
    },
  },
  {
    id: "f6-verbe",
    mot: "Verbe",
    famille: "gram-nature",
    definition: "Un mot qui exprime une action ou un état (être, avoir).",
    defi: {
      geste: "clic",
      question: "Clique sur le verbe.",
      choix: ["table", "courir", "rouge", "sous"],
      bonne: "courir",
    },
  },
  {
    id: "f6-adjectif",
    mot: "Adjectif",
    famille: "gram-nature",
    definition: "Un mot qui décrit le nom, qui donne sa qualité (un grand chien).",
    defi: {
      geste: "menu",
      question: "Choisis l'adjectif.",
      options: ["maison", "gentil", "manger", "et"],
      bonne: "gentil",
    },
  },
  {
    id: "f6-determinant",
    mot: "Déterminant",
    famille: "gram-nature",
    definition: "Un petit mot placé devant le nom (le, la, un, mon, ce…).",
    defi: {
      geste: "clic",
      question: "Quel mot est un déterminant ?",
      choix: ["le", "manger", "vite", "grand"],
      bonne: "le",
    },
  },
  {
    id: "f6-article",
    mot: "Article",
    famille: "gram-nature",
    definition: "Un déterminant : le, la, les, un, une, des.",
    defi: {
      geste: "saisie",
      question: "Recopie l'article du groupe « la maison ». Tape-le.",
      reponse: "la",
    },
  },
  {
    id: "f6-pronom",
    mot: "Pronom",
    famille: "gram-nature",
    definition: "Un mot qui remplace un nom (il, elle, le, lui…).",
    defi: {
      geste: "menu",
      question: "Choisis le pronom.",
      options: ["table", "elle", "beau", "avec"],
      bonne: "elle",
    },
  },
  {
    id: "f6-pronom-personnel",
    mot: "Pronom personnel",
    famille: "gram-nature",
    definition: "Un pronom qui désigne les personnes : je, tu, il, nous, vous, ils.",
    defi: {
      geste: "saisie",
      question: "Dans « Il mange », tape le pronom personnel.",
      reponse: "il",
    },
  },
  {
    id: "f6-adverbe",
    mot: "Adverbe",
    famille: "gram-nature",
    definition: "Un mot invariable qui précise (souvent, vite, très, lentement…).",
    defi: {
      geste: "clic",
      question: "Clique sur l'adverbe.",
      choix: ["lentement", "chat", "vert", "une"],
      bonne: "lentement",
    },
  },
  {
    id: "f6-preposition",
    mot: "Préposition",
    famille: "gram-nature",
    definition: "Un mot invariable qui relie (à, de, dans, sur, avec…).",
    defi: {
      geste: "menu",
      question: "Choisis la préposition.",
      options: ["dans", "manger", "joli", "il"],
      bonne: "dans",
    },
  },
  {
    id: "f6-conjonction",
    mot: "Conjonction",
    famille: "gram-nature",
    definition: "Un mot qui relie deux éléments (et, ou, mais, donc, car…).",
    defi: {
      geste: "clic",
      question: "Clique sur la conjonction.",
      choix: ["et", "chien", "vite", "le"],
      bonne: "et",
    },
  },

  // ─────────────────────────────── FONCTIONS (8) ───────────────────────────────
  {
    id: "f6-sujet",
    mot: "Sujet",
    famille: "gram-fonction",
    definition: "Le sujet fait l'action ; il répond à « qui est-ce qui ? ».",
    defi: {
      geste: "saisie",
      question: "Dans « Léa chante », tape le sujet.",
      reponse: "Léa",
    },
  },
  {
    id: "f6-predicat",
    mot: "Prédicat",
    famille: "gram-fonction",
    definition: "Ce que l'on dit du sujet : le verbe et ce qui le complète.",
    defi: {
      geste: "menu",
      question: "Dans « Le chat dort dans le panier », le prédicat est…",
      options: ["Le chat", "dort dans le panier", "le panier", "dans"],
      bonne: "dort dans le panier",
    },
  },
  {
    id: "f6-verbe-conjugue",
    mot: "Verbe conjugué",
    famille: "gram-fonction",
    definition: "Le verbe accordé avec le sujet à un temps (il mange, nous mangeons).",
    defi: {
      geste: "clic",
      question: "Dans « Les élèves écrivent », le verbe conjugué est…",
      choix: ["Les", "élèves", "écrivent", "écrire"],
      bonne: "écrivent",
    },
  },
  {
    id: "f6-complement-verbe",
    mot: "Complément du verbe",
    famille: "gram-fonction",
    definition: "Il complète le verbe et ne peut pas se déplacer (mange une pomme).",
    defi: {
      geste: "menu",
      question: "Dans « Tom mange une pomme », le complément du verbe est…",
      options: ["Tom", "mange", "une pomme", "Tom mange"],
      bonne: "une pomme",
    },
  },
  {
    id: "f6-complement-phrase",
    mot: "Complément de phrase",
    famille: "gram-fonction",
    definition: "Il précise quand, où, comment ; il peut se déplacer dans la phrase.",
    defi: {
      geste: "clic",
      question: "Dans « Ce matin, Léa lit », le complément de phrase est…",
      choix: ["Ce matin", "Léa", "lit", "Léa lit"],
      bonne: "Ce matin",
    },
  },
  {
    id: "f6-attribut",
    mot: "Attribut du sujet",
    famille: "gram-fonction",
    definition: "Il donne une qualité au sujet après le verbe être (Il est grand).",
    defi: {
      geste: "menu",
      question: "Dans « Le ciel est bleu », l'attribut du sujet est…",
      options: ["Le ciel", "est", "bleu", "ciel"],
      bonne: "bleu",
    },
  },
  {
    id: "f6-groupe-nominal",
    mot: "Groupe nominal",
    famille: "gram-fonction",
    definition: "Un groupe de mots organisé autour d'un nom (le petit chat noir).",
    defi: {
      geste: "clic",
      question: "Quel groupe est un groupe nominal ?",
      choix: ["la grande maison", "il court vite", "mange et boit", "très lentement"],
      bonne: "la grande maison",
    },
  },
  {
    id: "f6-complement-nom",
    mot: "Complément du nom",
    famille: "gram-fonction",
    definition: "Il précise le nom, souvent après « de » (la porte de la maison).",
    defi: {
      geste: "menu",
      question: "Dans « le livre de Marie », le complément du nom est…",
      options: ["le livre", "de Marie", "livre", "le"],
      bonne: "de Marie",
    },
  },

  // ─────────────────────────────── CONJUGAISON (10) ───────────────────────────────
  {
    id: "f6-infinitif",
    mot: "Infinitif",
    famille: "conjugaison",
    definition: "La forme du verbe non conjugué (manger, finir, prendre).",
    defi: {
      geste: "menu",
      question: "Choisis l'infinitif.",
      options: ["mange", "manger", "mangeait", "mangé"],
      bonne: "manger",
    },
  },
  {
    id: "f6-radical",
    mot: "Radical",
    famille: "conjugaison",
    definition: "La partie du verbe qui ne change pas (chant- dans chanter).",
    defi: {
      geste: "saisie",
      question: "Dans « chanter », tape le radical.",
      reponse: "chant",
    },
  },
  {
    id: "f6-terminaison",
    mot: "Terminaison",
    famille: "conjugaison",
    definition: "La fin du verbe, qui change selon la personne (-ons, -ez, -ent…).",
    defi: {
      geste: "clic",
      question: "Dans « nous chantons », la terminaison est…",
      choix: ["chant", "-ons", "nous", "chanter"],
      bonne: "-ons",
    },
  },
  {
    id: "f6-present",
    mot: "Présent",
    famille: "conjugaison",
    definition: "Le temps de ce qui se passe maintenant (je mange).",
    defi: {
      geste: "menu",
      question: "« Je mange » est au temps…",
      options: ["présent", "futur", "imparfait", "passé composé"],
      bonne: "présent",
    },
  },
  {
    id: "f6-futur",
    mot: "Futur",
    famille: "conjugaison",
    definition: "Le temps de ce qui va se passer (je mangerai).",
    defi: {
      geste: "clic",
      question: "« Je mangerai » est au…",
      choix: ["présent", "futur", "passé", "imparfait"],
      bonne: "futur",
    },
  },
  {
    id: "f6-imparfait",
    mot: "Imparfait",
    famille: "conjugaison",
    definition: "Un temps du passé pour décrire ou raconter (je mangeais).",
    defi: {
      geste: "menu",
      question: "« Je mangeais » est au temps…",
      options: ["présent", "futur", "imparfait", "passé composé"],
      bonne: "imparfait",
    },
  },
  {
    id: "f6-passe-compose",
    mot: "Passé composé",
    famille: "conjugaison",
    definition: "Un temps du passé formé avec avoir ou être (j'ai mangé).",
    defi: {
      geste: "menu",
      question: "« J'ai mangé » est au temps…",
      options: ["présent", "futur", "passé composé", "imparfait"],
      bonne: "passé composé",
    },
  },
  {
    id: "f6-auxiliaire",
    mot: "Auxiliaire",
    famille: "conjugaison",
    definition: "Le verbe avoir ou être utilisé pour conjuguer (il est parti).",
    defi: {
      geste: "clic",
      question: "Dans « il est parti », l'auxiliaire est…",
      choix: ["être", "parti", "il", "avoir"],
      bonne: "être",
    },
  },
  {
    id: "f6-participe-passe",
    mot: "Participe passé",
    famille: "conjugaison",
    definition: "La forme du verbe après l'auxiliaire (mangé, fini, pris).",
    defi: {
      geste: "saisie",
      question: "Le participe passé de « finir » est fin__. Tape le mot.",
      reponse: "fini",
    },
  },
  {
    id: "f6-personne",
    mot: "Personne",
    famille: "conjugaison",
    definition: "Qui fait l'action : 1re (je), 2e (tu), 3e (il/elle)…",
    defi: {
      geste: "menu",
      question: "« Tu » est la… personne.",
      options: ["1re", "2e", "3e", "4e"],
      bonne: "2e",
    },
  },

  // ─────────────────────────── ORTHOGRAPHE & LEXIQUE (10) ───────────────────────────
  {
    id: "f6-synonyme",
    mot: "Synonyme",
    famille: "ortho-lexique",
    definition: "Un mot de sens proche (content = heureux).",
    defi: {
      geste: "menu",
      question: "Un synonyme de « content » est…",
      options: ["triste", "heureux", "petit", "vite"],
      bonne: "heureux",
    },
  },
  {
    id: "f6-contraire",
    mot: "Contraire",
    famille: "ortho-lexique",
    definition: "Un mot de sens opposé (grand ≠ petit). On dit aussi antonyme.",
    defi: {
      geste: "clic",
      question: "Le contraire de « grand » est…",
      choix: ["énorme", "haut", "petit", "large"],
      bonne: "petit",
    },
  },
  {
    id: "f6-accord",
    mot: "Accord",
    famille: "ortho-lexique",
    definition: "Mettre un mot à la bonne forme avec un autre (le pluriel, le féminin).",
    defi: {
      geste: "saisie",
      question: "Accorde au pluriel : « des chat__ ». Tape le mot complet.",
      reponse: "chats",
    },
  },
  {
    id: "f6-homophone",
    mot: "Homophone",
    famille: "ortho-lexique",
    definition: "Des mots qui se prononcent pareil mais s'écrivent différemment (a / à).",
    defi: {
      geste: "clic",
      question: "Quel mot est un homophone du verbe « a » ?",
      choix: ["à", "et", "est", "on"],
      bonne: "à",
    },
  },
  {
    id: "f6-syllabe",
    mot: "Syllabe",
    famille: "ortho-lexique",
    definition: "Un morceau de mot qu'on prononce d'un seul coup (cha-peau).",
    defi: {
      geste: "saisie",
      question: "Combien de syllabes dans « chocolat » ? Tape le nombre.",
      reponse: "3",
    },
  },
  {
    id: "f6-prefixe",
    mot: "Préfixe",
    famille: "ortho-lexique",
    definition: "Un élément placé devant le radical (re-, dé-, in-).",
    defi: {
      geste: "menu",
      question: "Dans « refaire », le préfixe est…",
      options: ["re-", "-faire", "fai", "-re"],
      bonne: "re-",
    },
  },
  {
    id: "f6-suffixe",
    mot: "Suffixe",
    famille: "ortho-lexique",
    definition: "Un élément placé après le radical (-tion, -able, -ment).",
    defi: {
      geste: "clic",
      question: "Dans « lentement », le suffixe est…",
      choix: ["lent-", "-ement", "lente", "ment-"],
      bonne: "-ement",
    },
  },
  {
    id: "f6-pluriel",
    mot: "Pluriel",
    famille: "ortho-lexique",
    definition: "Quand il y a plusieurs ; on ajoute souvent un -s (un chat → des chats).",
    defi: {
      geste: "menu",
      question: "Le pluriel de « un chat » est…",
      options: ["un chat", "des chats", "le chat", "chat"],
      bonne: "des chats",
    },
  },
  {
    id: "f6-feminin",
    mot: "Féminin",
    famille: "ortho-lexique",
    definition: "La forme pour les filles ou femelles (un ami → une amie).",
    defi: {
      geste: "saisie",
      question: "Mets au féminin : « un ami → une am__ ». Tape le mot.",
      reponse: "amie",
    },
  },
  {
    id: "f6-famille-mots",
    mot: "Famille de mots",
    famille: "ortho-lexique",
    definition: "Des mots qui partagent le même radical (dent, dentiste, dentaire).",
    defi: {
      geste: "clic",
      question: "Quel mot est de la famille de « terre » ?",
      choix: ["terrain", "tirer", "tard", "tort"],
      bonne: "terrain",
    },
  },

  // ─────────────────────────── TEXTE & COMPRÉHENSION (5) ───────────────────────────
  {
    id: "f6-paragraphe",
    mot: "Paragraphe",
    famille: "texte",
    definition: "Un groupe de phrases qui forme une partie du texte.",
    defi: {
      geste: "menu",
      question: "Un paragraphe est…",
      options: ["une seule lettre", "un groupe de phrases", "un seul mot", "un titre"],
      bonne: "un groupe de phrases",
    },
  },
  {
    id: "f6-titre",
    mot: "Titre",
    famille: "texte",
    definition: "Le nom du texte, écrit en haut.",
    defi: {
      geste: "clic",
      question: "Où se trouve le titre ?",
      choix: ["au milieu", "en haut du texte", "à la fin", "nulle part"],
      bonne: "en haut du texte",
    },
  },
  {
    id: "f6-personnage",
    mot: "Personnage",
    famille: "texte",
    definition: "Une personne ou un être qui agit dans l'histoire.",
    defi: {
      geste: "menu",
      question: "Un personnage est…",
      options: ["un lieu", "un être qui agit dans l'histoire", "une date", "un titre"],
      bonne: "un être qui agit dans l'histoire",
    },
  },
  {
    id: "f6-narrateur",
    mot: "Narrateur",
    famille: "texte",
    definition: "Celui qui raconte l'histoire.",
    defi: {
      geste: "clic",
      question: "Le narrateur est…",
      choix: ["celui qui raconte l'histoire", "le héros méchant", "le lecteur", "le titre"],
      bonne: "celui qui raconte l'histoire",
    },
  },
  {
    id: "f6-dialogue",
    mot: "Dialogue",
    famille: "texte",
    definition: "Le moment où les personnages parlent (avec des tirets ou des guillemets).",
    defi: {
      geste: "menu",
      question: "Un dialogue, c'est quand…",
      options: ["on décrit un lieu", "les personnages parlent", "l'histoire se termine", "on saute une ligne"],
      bonne: "les personnages parlent",
    },
  },

  // ──────────────────────────── MOTS-CONSIGNES (5) ────────────────────────────
  {
    id: "f6-relever",
    mot: "Relever",
    famille: "consignes",
    definition: "Recopier exactement un mot ou une phrase du texte.",
    defi: {
      geste: "clic",
      question: "RELEVER, c'est…",
      choix: ["inventer une phrase", "recopier un mot du texte", "colorier", "souligner au hasard"],
      bonne: "recopier un mot du texte",
    },
  },
  {
    id: "f6-souligner",
    mot: "Souligner",
    famille: "consignes",
    definition: "Tracer un trait sous un mot pour le repérer.",
    defi: {
      geste: "menu",
      question: "SOULIGNER un mot, c'est tracer un trait…",
      options: ["au-dessus", "sous le mot", "à côté", "autour"],
      bonne: "sous le mot",
    },
  },
  {
    id: "f6-recopier",
    mot: "Recopier",
    famille: "consignes",
    definition: "Réécrire exactement, sans erreur.",
    defi: {
      geste: "saisie",
      question: "RECOPIE sans erreur le mot : « bonjour ». Tape-le.",
      reponse: "bonjour",
    },
  },
  {
    id: "f6-justifier",
    mot: "Justifier",
    famille: "consignes",
    definition: "Expliquer pourquoi, en donnant une preuve dans le texte.",
    defi: {
      geste: "menu",
      question: "JUSTIFIER, c'est…",
      options: ["répondre par oui ou non", "expliquer pourquoi avec une preuve", "recopier le titre", "dessiner"],
      bonne: "expliquer pourquoi avec une preuve",
    },
  },
  {
    id: "f6-expliquer",
    mot: "Expliquer",
    famille: "consignes",
    definition: "Dire avec ses propres mots ce que cela veut dire.",
    defi: {
      geste: "clic",
      question: "EXPLIQUER un mot, c'est…",
      choix: ["le recopier", "dire ce qu'il veut dire", "le souligner", "l'effacer"],
      bonne: "dire ce qu'il veut dire",
    },
  },
];
