// lib/coach-bac-spe/banks/algorithmique.bank.ts

import type { CoachBacItem } from "../types";

export const algorithmiqueBank: CoachBacItem[] = [
  {
    kind: "fixed",
    id: "algo_for_001",
    niveau: "terminale",
    matiere: "maths",
    notionId: "algorithmique",
    microId: "boucle_for",
    difficulty: 1,
    theme: "automatisme",
    text: "En Python, une boucle for sert surtout à...",
    format: "qcm",
    choices: ["répéter un nombre connu de fois", "résoudre une équation", "tracer une courbe automatiquement", "définir une probabilité"],
    expected: ["répéter un nombre connu de fois"],
    comparator: "mcq_exact",
    hint: "for est utilisé quand on connaît souvent le nombre de répétitions.",
    explanation: "Une boucle for permet de répéter une instruction un nombre déterminé de fois.",
    tags: ["algorithmique", "python", "for"],
  },
  {
    kind: "fixed",
    id: "algo_while_001",
    niveau: "terminale",
    matiere: "maths",
    notionId: "algorithmique",
    microId: "boucle_while",
    difficulty: 1,
    theme: "automatisme",
    text: "Une boucle while continue tant que...",
    format: "qcm",
    choices: ["une condition est vraie", "une condition est fausse", "n vaut toujours 0", "le programme est fermé"],
    expected: ["une condition est vraie"],
    comparator: "mcq_exact",
    hint: "while signifie tant que.",
    explanation: "Une boucle while continue tant que la condition donnée reste vraie.",
    tags: ["algorithmique", "python", "while"],
  },
  {
    kind: "fixed",
    id: "algo_condition_001",
    niveau: "terminale",
    matiere: "maths",
    notionId: "algorithmique",
    microId: "condition",
    difficulty: 1,
    theme: "automatisme",
    text: "En Python, le mot-clé if permet...",
    format: "qcm",
    choices: ["de tester une condition", "de répéter 10 fois", "de calculer une dérivée", "de créer une liste uniquement"],
    expected: ["de tester une condition"],
    comparator: "mcq_exact",
    hint: "if signifie si.",
    explanation: "Le mot-clé if permet d’exécuter une instruction si une condition est vérifiée.",
    tags: ["algorithmique", "condition"],
  },
  {
    kind: "fixed",
    id: "algo_suite_001",
    niveau: "terminale",
    matiere: "maths",
    notionId: "algorithmique",
    microId: "suite_algorithme",
    difficulty: 2,
    theme: "bac",
    text: "Dans un algorithme de suite, l’instruction u = 0.5*u + 3 permet généralement de calculer...",
    format: "qcm",
    choices: ["le terme suivant", "le premier terme uniquement", "la dérivée", "la probabilité totale"],
    expected: ["le terme suivant"],
    comparator: "mcq_exact",
    hint: "On remplace l’ancienne valeur de u par une nouvelle.",
    explanation: "L’instruction met à jour u à partir de sa valeur précédente : elle calcule le terme suivant.",
    tags: ["algorithmique", "suite"],
  },
  {
    kind: "fixed",
    id: "algo_seuil_001",
    niveau: "terminale",
    matiere: "maths",
    notionId: "algorithmique",
    microId: "seuil",
    difficulty: 2,
    theme: "bac",
    text: "Un algorithme de seuil sert souvent à déterminer...",
    format: "qcm",
    choices: ["le premier rang à partir duquel une condition est vérifiée", "la dérivée exacte", "une primitive", "une valeur interdite"],
    expected: ["le premier rang à partir duquel une condition est vérifiée"],
    comparator: "mcq_exact",
    hint: "On avance jusqu’à dépasser ou atteindre une valeur.",
    explanation: "Un algorithme de seuil permet de trouver le premier rang où une condition devient vraie.",
    tags: ["algorithmique", "seuil"],
  },
  {
    kind: "fixed",
    id: "algo_piege_initialisation_001",
    niveau: "terminale",
    matiere: "maths",
    notionId: "algorithmique",
    microId: "piege_initialisation",
    difficulty: 2,
    theme: "piege",
    text: "Dans un algorithme de suite, oublier l’initialisation de u et n est...",
    format: "qcm",
    choices: ["grave, car le programme ne sait pas d’où partir", "sans importance", "utile pour aller plus vite", "obligatoire"],
    expected: ["grave, car le programme ne sait pas d’où partir"],
    comparator: "mcq_exact",
    hint: "Un algorithme doit avoir un point de départ.",
    explanation: "Sans initialisation, le programme ne connaît pas les valeurs de départ de u et n.",
    tags: ["algorithmique", "piege", "initialisation"],
  },
];