// lib/coach-bac-spe/banks/derivees.bank.ts

import type { CoachBacItem } from "../types";

export const deriveesBank: CoachBacItem[] = [
  {
    kind: "fixed",
    id: "derivee_affine_001",
    niveau: "terminale",
    matiere: "maths",
    notionId: "derivees",
    microId: "derivee_affine",
    difficulty: 1,
    theme: "automatisme",
    text: "Quelle est la dérivée de f(x) = 3x + 5 ?",
    format: "short",
    expected: ["3"],
    comparator: "number_equal",
    hint: "La dérivée de ax + b est a.",
    explanation: "La dérivée de 3x est 3. La dérivée de 5 est 0. Donc f'(x) = 3.",
    tags: ["derivees", "affine"],
  },
  {
    kind: "fixed",
    id: "derivee_polynome_001",
    niveau: "terminale",
    matiere: "maths",
    notionId: "derivees",
    microId: "derivee_polynome",
    difficulty: 1,
    theme: "automatisme",
    text: "Quelle est la dérivée de f(x) = x² - 4x + 1 ?",
    format: "short",
    expected: ["2x-4", "2x - 4"],
    comparator: "exact",
    hint: "Dérive terme à terme.",
    explanation: "La dérivée de x² est 2x, celle de -4x est -4, celle de 1 est 0. Donc f'(x) = 2x - 4.",
    tags: ["derivees", "polynome"],
  },
  {
    kind: "fixed",
    id: "derivee_inverse_001",
    niveau: "terminale",
    matiere: "maths",
    notionId: "derivees",
    microId: "derivee_inverse",
    difficulty: 2,
    theme: "automatisme",
    text: "Quelle est la dérivée de f(x) = 1/x sur ]0 ; +∞[ ?",
    format: "qcm",
    choices: ["1/x²", "-1/x²", "ln(x)", "x²"],
    expected: ["-1/x²"],
    comparator: "mcq_exact",
    hint: "Attention au signe moins.",
    explanation: "La dérivée de 1/x est -1/x².",
    tags: ["derivees", "inverse", "piege_signe"],
  },
  {
    kind: "fixed",
    id: "derivee_exp_001",
    niveau: "terminale",
    matiere: "maths",
    notionId: "derivees",
    microId: "derivee_exponentielle",
    difficulty: 1,
    theme: "automatisme",
    text: "Quelle est la dérivée de f(x) = eˣ ?",
    format: "short",
    expected: ["e^x", "eˣ"],
    comparator: "exact",
    hint: "La fonction exponentielle est sa propre dérivée.",
    explanation: "La dérivée de eˣ est eˣ.",
    tags: ["derivees", "exponentielle"],
  },
  {
    kind: "fixed",
    id: "derivee_ln_001",
    niveau: "terminale",
    matiere: "maths",
    notionId: "derivees",
    microId: "derivee_logarithme",
    difficulty: 1,
    theme: "automatisme",
    text: "Quelle est la dérivée de f(x) = ln(x) sur ]0 ; +∞[ ?",
    format: "qcm",
    choices: ["1/x", "x", "ln(x)", "eˣ"],
    expected: ["1/x"],
    comparator: "mcq_exact",
    hint: "C’est une formule de base.",
    explanation: "Sur ]0 ; +∞[, la dérivée de ln(x) est 1/x.",
    tags: ["derivees", "logarithme"],
  },
  {
    kind: "fixed",
    id: "derivee_piege_constante_e_001",
    niveau: "terminale",
    matiere: "maths",
    notionId: "derivees",
    microId: "derivee_constante",
    difficulty: 1,
    theme: "piege",
    text: "Quelle est la dérivée de f(x) = x + e ?",
    format: "qcm",
    choices: ["1", "1 + e", "e", "0"],
    expected: ["1"],
    comparator: "mcq_exact",
    hint: "e est un nombre constant.",
    explanation: "La dérivée de x est 1. Le nombre e est une constante, donc sa dérivée est 0. Donc f'(x) = 1.",
    tags: ["derivees", "piege", "constante", "e"],
  },
  {
    kind: "fixed",
    id: "derivee_piege_composee_001",
    niveau: "terminale",
    matiere: "maths",
    notionId: "derivees",
    microId: "derivee_composee",
    difficulty: 2,
    theme: "piege",
    text: "Quelle est la dérivée de f(x) = e^(2x + 1) ?",
    format: "qcm",
    choices: ["e^(2x + 1)", "2e^(2x + 1)", "(2x + 1)e^(2x + 1)", "2x e^(2x + 1)"],
    expected: ["2e^(2x + 1)"],
    comparator: "mcq_exact",
    hint: "Il faut multiplier par la dérivée de 2x + 1.",
    explanation: "Si f(x)=e^u, alors f'(x)=u'e^u. Ici u(x)=2x+1 donc u'(x)=2. Donc f'(x)=2e^(2x+1).",
    tags: ["derivees", "composee", "exponentielle", "piege"],
  },
];