// lib/coach-bac-spe/banks/exponentielle.bank.ts

import type { CoachBacItem } from "../types";

export const exponentielleBank: CoachBacItem[] = [
  {
    kind: "fixed",
    id: "exp_valeurs_remarquables_001",
    niveau: "terminale",
    matiere: "maths",
    notionId: "exponentielle",
    microId: "valeurs_remarquables",
    difficulty: 1,
    theme: "automatisme",
    text: "Combien vaut e⁰ ?",
    format: "qcm",
    choices: ["0", "1", "e", "-1"],
    expected: ["1"],
    comparator: "mcq_exact",
    hint: "Tout nombre non nul à la puissance 0 vaut 1.",
    explanation: "e⁰ = 1.",
    tags: ["exponentielle", "valeur_remarquable"],
  },
  {
    kind: "fixed",
    id: "exp_equation_001",
    niveau: "terminale",
    matiere: "maths",
    notionId: "exponentielle",
    microId: "equation",
    difficulty: 2,
    theme: "bac",
    text: "Résoudre eˣ = e³.",
    format: "short",
    expected: ["3"],
    comparator: "number_equal",
    hint: "La fonction exponentielle est strictement croissante.",
    explanation: "eˣ = e³ implique x = 3.",
    tags: ["exponentielle", "equation"],
  },
  {
    kind: "fixed",
    id: "exp_inequation_001",
    niveau: "terminale",
    matiere: "maths",
    notionId: "exponentielle",
    microId: "inequation",
    difficulty: 2,
    theme: "bac",
    text: "Résoudre eˣ > 1.",
    format: "qcm",
    choices: ["x > 0", "x < 0", "x > 1", "x = 0"],
    expected: ["x > 0"],
    comparator: "mcq_exact",
    hint: "1 = e⁰.",
    explanation: "eˣ > 1 équivaut à eˣ > e⁰, donc x > 0.",
    tags: ["exponentielle", "inequation"],
  },
  {
    kind: "fixed",
    id: "exp_derivee_001",
    niveau: "terminale",
    matiere: "maths",
    notionId: "exponentielle",
    microId: "derivee",
    difficulty: 2,
    theme: "automatisme",
    text: "Quelle est la dérivée de f(x)=e^(3x) ?",
    format: "qcm",
    choices: ["e^(3x)", "3e^(3x)", "3x e^(3x)", "e³"],
    expected: ["3e^(3x)"],
    comparator: "mcq_exact",
    hint: "Utilise la dérivée de e^u.",
    explanation: "Si f(x)=e^u, alors f'(x)=u'e^u. Ici u=3x donc u'=3. Donc f'(x)=3e^(3x).",
    tags: ["exponentielle", "derivee"],
  },
  {
    kind: "fixed",
    id: "exp_limite_001",
    niveau: "terminale",
    matiere: "maths",
    notionId: "exponentielle",
    microId: "limite",
    difficulty: 2,
    theme: "bac",
    text: "Quelle est la limite de eˣ quand x tend vers +∞ ?",
    format: "qcm",
    choices: ["+∞", "0", "1", "-∞"],
    expected: ["+∞"],
    comparator: "mcq_exact",
    hint: "L’exponentielle croît très vite.",
    explanation: "Quand x tend vers +∞, eˣ tend vers +∞.",
    tags: ["exponentielle", "limite"],
  },
  {
    kind: "fixed",
    id: "exp_piege_e0_001",
    niveau: "terminale",
    matiere: "maths",
    notionId: "exponentielle",
    microId: "piege_e0",
    difficulty: 1,
    theme: "piege",
    text: "Piège classique : e⁰ vaut...",
    format: "qcm",
    choices: ["0", "1", "e", "Impossible"],
    expected: ["1"],
    comparator: "mcq_exact",
    hint: "La puissance 0 d’un nombre non nul vaut 1.",
    explanation: "e⁰ = 1. Beaucoup d’élèves confondent avec 0.",
    tags: ["exponentielle", "piege"],
  },
  {
    kind: "fixed",
    id: "exp_piege_somme_001",
    niveau: "terminale",
    matiere: "maths",
    notionId: "exponentielle",
    microId: "piege_somme",
    difficulty: 2,
    theme: "piege",
    text: "Quelle égalité est vraie ?",
    format: "qcm",
    choices: ["e^(a+b)=e^a+e^b", "e^(a+b)=e^a×e^b", "e^(ab)=e^a+e^b", "e^a=ae"],
    expected: ["e^(a+b)=e^a×e^b"],
    comparator: "mcq_exact",
    hint: "Une somme dans l’exposant devient un produit.",
    explanation: "La propriété correcte est e^(a+b)=e^a×e^b.",
    tags: ["exponentielle", "propriete", "piege"],
  },
];