// lib/coach-bac-spe/banks/fonctions.bank.ts

import type { CoachBacItem } from "../types";

export const fonctionsBank: CoachBacItem[] = [
  {
    kind: "fixed",
    id: "fonctions_image_001",
    niveau: "terminale",
    matiere: "maths",
    notionId: "fonctions",
    microId: "image",
    difficulty: 1,
    theme: "automatisme",
    text: "Si f(x)=2x+1, combien vaut f(3) ?",
    format: "short",
    expected: ["7"],
    comparator: "number_equal",
    hint: "Remplace x par 3.",
    explanation: "f(3)=2×3+1=7.",
    tags: ["fonctions", "image"],
  },
  {
    kind: "fixed",
    id: "fonctions_antecedent_001",
    niveau: "terminale",
    matiere: "maths",
    notionId: "fonctions",
    microId: "antecedent",
    difficulty: 1,
    theme: "automatisme",
    text: "Si f(x)=2x+1, quel est l’antécédent de 9 ?",
    format: "short",
    expected: ["4"],
    comparator: "number_equal",
    hint: "Résous 2x+1=9.",
    explanation: "2x+1=9 donc 2x=8 et x=4.",
    tags: ["fonctions", "antecedent"],
  },
  {
    kind: "fixed",
    id: "fonctions_signe_001",
    niveau: "terminale",
    matiere: "maths",
    notionId: "fonctions",
    microId: "signe",
    difficulty: 2,
    theme: "bac",
    text: "Pour f(x)=x-3, sur quel intervalle f(x) est-elle positive ?",
    format: "qcm",
    choices: ["[3 ; +∞[", "]-∞ ; 3]", "]-∞ ; +∞[", "{3}"],
    expected: ["[3 ; +∞["],
    comparator: "mcq_exact",
    hint: "Résous x - 3 ≥ 0.",
    explanation: "x - 3 ≥ 0 équivaut à x ≥ 3. Donc f est positive sur [3 ; +∞[.",
    tags: ["fonctions", "signe"],
  },
  {
    kind: "fixed",
    id: "fonctions_variations_001",
    niveau: "terminale",
    matiere: "maths",
    notionId: "fonctions",
    microId: "variations",
    difficulty: 2,
    theme: "bac",
    text: "Si f'(x)>0 sur un intervalle I, alors f est...",
    format: "qcm",
    choices: ["croissante sur I", "décroissante sur I", "constante sur I", "négative sur I"],
    expected: ["croissante sur I"],
    comparator: "mcq_exact",
    hint: "Le signe de la dérivée donne le sens de variation.",
    explanation: "Si f'(x)>0 sur I, alors f est croissante sur I.",
    tags: ["fonctions", "variations", "derivee"],
  },
  {
    kind: "fixed",
    id: "fonctions_extremum_001",
    niveau: "terminale",
    matiere: "maths",
    notionId: "fonctions",
    microId: "extremum",
    difficulty: 2,
    theme: "bac",
    text: "Si f' passe de positif à négatif en a, alors f admet en a...",
    format: "qcm",
    choices: ["un maximum local", "un minimum local", "une limite infinie", "une asymptote"],
    expected: ["un maximum local"],
    comparator: "mcq_exact",
    hint: "La fonction monte puis descend.",
    explanation: "Si f' passe de + à -, alors f croît puis décroît : f admet un maximum local.",
    tags: ["fonctions", "extremum", "derivee"],
  },
  {
    kind: "fixed",
    id: "fonctions_piege_image_antecedent_001",
    niveau: "terminale",
    matiere: "maths",
    notionId: "fonctions",
    microId: "piege_image_antecedent",
    difficulty: 1,
    theme: "piege",
    text: "Dans l’égalité f(2)=5, le nombre 2 est...",
    format: "qcm",
    choices: ["une image", "un antécédent", "une fonction", "une dérivée"],
    expected: ["un antécédent"],
    comparator: "mcq_exact",
    hint: "On entre 2 dans la fonction et on obtient 5.",
    explanation: "2 est un antécédent de 5 par f. 5 est l’image de 2.",
    tags: ["fonctions", "piege", "image", "antecedent"],
  },
];