// lib/coach-bac-spe/banks/geometrie-espace.bank.ts

import type { CoachBacItem } from "../types";

export const geometrieEspaceBank: CoachBacItem[] = [
  {
    kind: "fixed",
    id: "geo_vecteurs_001",
    niveau: "terminale",
    matiere: "maths",
    notionId: "geometrie_espace",
    microId: "vecteurs",
    difficulty: 1,
    theme: "automatisme",
    text: "Si A(1;2;3) et B(4;6;8), alors le vecteur AB a pour coordonnées...",
    format: "qcm",
    choices: ["(3;4;5)", "(5;8;11)", "(-3;-4;-5)", "(4;6;8)"],
    expected: ["(3;4;5)"],
    comparator: "mcq_exact",
    hint: "AB = B - A coordonnée par coordonnée.",
    explanation: "AB = (4-1 ; 6-2 ; 8-3) = (3 ; 4 ; 5).",
    tags: ["geometrie_espace", "vecteurs"],
  },
  {
    kind: "fixed",
    id: "geo_produit_scalaire_001",
    niveau: "terminale",
    matiere: "maths",
    notionId: "geometrie_espace",
    microId: "produit_scalaire",
    difficulty: 2,
    theme: "bac",
    text: "Calculer le produit scalaire de u(1;2;3) et v(2;0;1).",
    format: "short",
    expected: ["5"],
    comparator: "number_equal",
    hint: "u·v = xx' + yy' + zz'.",
    explanation: "u·v = 1×2 + 2×0 + 3×1 = 2 + 0 + 3 = 5.",
    tags: ["geometrie_espace", "produit_scalaire"],
  },
  {
    kind: "fixed",
    id: "geo_orthogonalite_001",
    niveau: "terminale",
    matiere: "maths",
    notionId: "geometrie_espace",
    microId: "orthogonalite",
    difficulty: 2,
    theme: "bac",
    text: "Deux vecteurs non nuls sont orthogonaux si leur produit scalaire vaut...",
    format: "short",
    expected: ["0"],
    comparator: "number_equal",
    hint: "C’est le critère d’orthogonalité.",
    explanation: "Deux vecteurs non nuls sont orthogonaux si leur produit scalaire vaut 0.",
    tags: ["geometrie_espace", "orthogonalite"],
  },
  {
    kind: "fixed",
    id: "geo_representation_parametrique_001",
    niveau: "terminale",
    matiere: "maths",
    notionId: "geometrie_espace",
    microId: "representation_parametrique",
    difficulty: 2,
    theme: "bac",
    text: "Une droite passant par A(1;2;3) et de vecteur directeur u(2;1;0) peut s’écrire...",
    format: "qcm",
    choices: ["x=1+2t, y=2+t, z=3", "x=2+t, y=1+2t, z=3t", "x=1, y=2, z=3", "x=2t, y=t, z=0"],
    expected: ["x=1+2t, y=2+t, z=3"],
    comparator: "mcq_exact",
    hint: "Point de départ + t × vecteur directeur.",
    explanation: "On écrit x=1+2t, y=2+t, z=3+0t donc z=3.",
    tags: ["geometrie_espace", "droite", "parametrique"],
  },
  {
    kind: "fixed",
    id: "geo_intersection_droite_plan_001",
    niveau: "terminale",
    matiere: "maths",
    notionId: "geometrie_espace",
    microId: "intersection_droite_plan",
    difficulty: 3,
    theme: "bac",
    text: "Pour trouver l’intersection d’une droite paramétrée avec un plan, on remplace généralement...",
    format: "qcm",
    choices: ["x, y, z dans l’équation du plan", "le plan dans la droite", "t par 0 seulement", "les coordonnées par des probabilités"],
    expected: ["x, y, z dans l’équation du plan"],
    comparator: "mcq_exact",
    hint: "On injecte la représentation paramétrique dans l’équation du plan.",
    explanation: "On remplace x, y et z par leurs expressions en t dans l’équation du plan, puis on résout.",
    tags: ["geometrie_espace", "intersection"],
  },
  {
    kind: "fixed",
    id: "geo_piege_colineaire_orthogonal_001",
    niveau: "terminale",
    matiere: "maths",
    notionId: "geometrie_espace",
    microId: "piege_colineaire_orthogonal",
    difficulty: 2,
    theme: "piege",
    text: "Deux vecteurs colinéaires sont forcément orthogonaux.",
    format: "qcm",
    choices: ["Vrai", "Faux"],
    expected: ["Faux"],
    comparator: "mcq_exact",
    hint: "Colinéaire signifie même direction ou directions opposées.",
    explanation: "Deux vecteurs colinéaires ne sont pas forcément orthogonaux. Ils ont la même direction, alors que des vecteurs orthogonaux forment un angle droit.",
    tags: ["geometrie_espace", "piege"],
  },
];