// lib/coach-bac-spe/banks/limites.bank.ts

import type { CoachBacItem } from "../types";

export const limitesBank: CoachBacItem[] = [
  {
    kind: "fixed",
    id: "limites_polynome_001",
    niveau: "terminale",
    matiere: "maths",
    notionId: "limites",
    microId: "polynome",
    difficulty: 1,
    theme: "automatisme",
    text: "Quelle est la limite de f(x)=x²+3x quand x tend vers +∞ ?",
    format: "qcm",
    choices: ["+∞", "-∞", "0", "3"],
    expected: ["+∞"],
    comparator: "mcq_exact",
    hint: "Le terme dominant est x².",
    explanation: "Quand x tend vers +∞, x² domine et tend vers +∞. Donc f(x) tend vers +∞.",
    tags: ["limites", "polynome"],
  },
  {
    kind: "fixed",
    id: "limites_quotient_001",
    niveau: "terminale",
    matiere: "maths",
    notionId: "limites",
    microId: "quotient",
    difficulty: 2,
    theme: "bac",
    text: "Quelle est la limite de (2x²+1)/(x²+3) quand x tend vers +∞ ?",
    format: "short",
    expected: ["2"],
    comparator: "number_equal",
    hint: "Compare les coefficients des termes de plus haut degré.",
    explanation: "Le numérateur est équivalent à 2x² et le dénominateur à x². La limite vaut donc 2.",
    tags: ["limites", "quotient"],
  },
  {
    kind: "fixed",
    id: "limites_infini_001",
    niveau: "terminale",
    matiere: "maths",
    notionId: "limites",
    microId: "infini",
    difficulty: 1,
    theme: "automatisme",
    text: "Quelle est la limite de 1/x quand x tend vers +∞ ?",
    format: "short",
    expected: ["0"],
    comparator: "number_equal",
    hint: "Plus x est grand, plus 1/x est proche de 0.",
    explanation: "Quand x tend vers +∞, 1/x tend vers 0.",
    tags: ["limites", "inverse"],
  },
  {
    kind: "fixed",
    id: "limites_forme_indeterminee_001",
    niveau: "terminale",
    matiere: "maths",
    notionId: "limites",
    microId: "forme_indeterminee",
    difficulty: 3,
    theme: "bac",
    text: "La forme ∞ - ∞ permet-elle de conclure directement ?",
    format: "qcm",
    choices: ["Oui", "Non"],
    expected: ["Non"],
    comparator: "mcq_exact",
    hint: "C’est une forme indéterminée.",
    explanation: "La forme ∞ - ∞ est indéterminée. Il faut transformer l’expression avant de conclure.",
    tags: ["limites", "forme_indeterminee"],
  },
  {
    kind: "fixed",
    id: "limites_piege_valeur_interdite_001",
    niveau: "terminale",
    matiere: "maths",
    notionId: "limites",
    microId: "piege_valeur_interdite",
    difficulty: 2,
    theme: "piege",
    text: "Si une fonction n’est pas définie en x=2, peut-elle avoir une limite finie quand x tend vers 2 ?",
    format: "qcm",
    choices: ["Oui", "Non"],
    expected: ["Oui"],
    comparator: "mcq_exact",
    hint: "La limite étudie le comportement autour du point, pas forcément la valeur au point.",
    explanation: "Une fonction peut avoir une limite en 2 même si elle n’est pas définie en 2. Il ne faut pas confondre valeur interdite et limite.",
    tags: ["limites", "piege", "valeur_interdite"],
  },
];