// lib/coach-bac-spe/banks/logarithme.bank.ts

import type { CoachBacItem } from "../types";

export const logarithmeBank: CoachBacItem[] = [
  {
    kind: "fixed",
    id: "ln_valeurs_remarquables_001",
    niveau: "terminale",
    matiere: "maths",
    notionId: "logarithme",
    microId: "valeurs_remarquables",
    difficulty: 1,
    theme: "automatisme",
    text: "Combien vaut ln(1) ?",
    format: "short",
    expected: ["0"],
    comparator: "number_equal",
    hint: "ln(1)=0 car e⁰=1.",
    explanation: "ln(1)=0.",
    tags: ["logarithme", "valeur_remarquable"],
  },
  {
    kind: "fixed",
    id: "ln_equation_001",
    niveau: "terminale",
    matiere: "maths",
    notionId: "logarithme",
    microId: "equation",
    difficulty: 2,
    theme: "bac",
    text: "Résoudre ln(x)=0 sur ]0 ; +∞[.",
    format: "short",
    expected: ["1"],
    comparator: "number_equal",
    hint: "ln(1)=0.",
    explanation: "ln(x)=0 équivaut à x=1.",
    tags: ["logarithme", "equation"],
  },
  {
    kind: "fixed",
    id: "ln_inequation_001",
    niveau: "terminale",
    matiere: "maths",
    notionId: "logarithme",
    microId: "inequation",
    difficulty: 2,
    theme: "bac",
    text: "Résoudre ln(x)>0 sur ]0 ; +∞[.",
    format: "qcm",
    choices: ["x > 1", "x > 0", "x < 1", "x = 1"],
    expected: ["x > 1"],
    comparator: "mcq_exact",
    hint: "ln(1)=0 et ln est croissante.",
    explanation: "Comme ln est croissante et ln(1)=0, ln(x)>0 équivaut à x>1.",
    tags: ["logarithme", "inequation"],
  },
  {
    kind: "fixed",
    id: "ln_derivee_001",
    niveau: "terminale",
    matiere: "maths",
    notionId: "logarithme",
    microId: "derivee",
    difficulty: 1,
    theme: "automatisme",
    text: "Quelle est la dérivée de ln(x) sur ]0 ; +∞[ ?",
    format: "qcm",
    choices: ["1/x", "x", "eˣ", "ln(x)"],
    expected: ["1/x"],
    comparator: "mcq_exact",
    hint: "C’est une formule de base.",
    explanation: "La dérivée de ln(x) est 1/x.",
    tags: ["logarithme", "derivee"],
  },
  {
    kind: "fixed",
    id: "ln_domaine_001",
    niveau: "terminale",
    matiere: "maths",
    notionId: "logarithme",
    microId: "domaine",
    difficulty: 2,
    theme: "bac",
    text: "Pour que ln(x - 2) soit défini, il faut...",
    format: "qcm",
    choices: ["x > 2", "x ≥ 2", "x < 2", "x ≠ 2"],
    expected: ["x > 2"],
    comparator: "mcq_exact",
    hint: "L’intérieur du logarithme doit être strictement positif.",
    explanation: "Il faut x - 2 > 0, donc x > 2.",
    tags: ["logarithme", "domaine"],
  },
  {
    kind: "fixed",
    id: "ln_piege_ln1_001",
    niveau: "terminale",
    matiere: "maths",
    notionId: "logarithme",
    microId: "piege_ln1",
    difficulty: 1,
    theme: "piege",
    text: "Piège classique : ln(1) vaut...",
    format: "qcm",
    choices: ["0", "1", "e", "-1"],
    expected: ["0"],
    comparator: "mcq_exact",
    hint: "ln(1)=0 car e⁰=1.",
    explanation: "ln(1)=0. Beaucoup d’élèves répondent 1 par réflexe.",
    tags: ["logarithme", "piege"],
  },
  {
    kind: "fixed",
    id: "ln_piege_somme_001",
    niveau: "terminale",
    matiere: "maths",
    notionId: "logarithme",
    microId: "piege_somme",
    difficulty: 2,
    theme: "piege",
    text: "Quelle affirmation est fausse en général ?",
    format: "qcm",
    choices: ["ln(ab)=ln(a)+ln(b)", "ln(a/b)=ln(a)-ln(b)", "ln(a+b)=ln(a)+ln(b)", "ln(1)=0"],
    expected: ["ln(a+b)=ln(a)+ln(b)"],
    comparator: "mcq_exact",
    hint: "Le logarithme transforme les produits en sommes, pas les sommes.",
    explanation: "ln(a+b)=ln(a)+ln(b) est faux en général.",
    tags: ["logarithme", "piege", "propriete"],
  },
];