// lib/coach-bac-spe/banks/probabilites.bank.ts

import type { CoachBacItem } from "../types";

export const probabilitesBank: CoachBacItem[] = [
  {
    kind: "fixed",
    id: "proba_arbre_001",
    niveau: "terminale",
    matiere: "maths",
    notionId: "probabilites",
    microId: "arbre",
    difficulty: 1,
    theme: "automatisme",
    text: "Dans un arbre, P(A)=0,4 et P_A(B)=0,7. Calculer P(A ∩ B).",
    format: "short",
    expected: ["0.28", "0,28"],
    comparator: "number_equal",
    hint: "On multiplie le long d’une branche.",
    explanation: "P(A ∩ B) = P(A) × P_A(B) = 0,4 × 0,7 = 0,28.",
    tags: ["probabilites", "arbre"],
  },
  {
    kind: "fixed",
    id: "proba_intersection_001",
    niveau: "terminale",
    matiere: "maths",
    notionId: "probabilites",
    microId: "intersection",
    difficulty: 1,
    theme: "automatisme",
    text: "Si P(A)=0,5 et P(B)=0,2 avec A et B indépendants, combien vaut P(A ∩ B) ?",
    format: "short",
    expected: ["0.1", "0,1"],
    comparator: "number_equal",
    hint: "Pour deux événements indépendants : P(A ∩ B)=P(A)P(B).",
    explanation: "P(A ∩ B)=0,5×0,2=0,1.",
    tags: ["probabilites", "independance", "intersection"],
  },
  {
    kind: "fixed",
    id: "proba_conditionnelle_001",
    niveau: "terminale",
    matiere: "maths",
    notionId: "probabilites",
    microId: "conditionnelle",
    difficulty: 2,
    theme: "bac",
    text: "On sait que P(A ∩ B)=0,12 et P(A)=0,3. Calculer P_A(B).",
    format: "short",
    expected: ["0.4", "0,4"],
    comparator: "number_equal",
    hint: "P_A(B)=P(A ∩ B)/P(A).",
    explanation: "P_A(B)=0,12/0,3=0,4.",
    tags: ["probabilites", "conditionnelle"],
  },
  {
    kind: "fixed",
    id: "proba_totales_001",
    niveau: "terminale",
    matiere: "maths",
    notionId: "probabilites",
    microId: "probabilites_totales",
    difficulty: 2,
    theme: "bac",
    text: "Si P(A)=0,6, P_A(B)=0,5 et P_nonA(B)=0,2, combien vaut P(B) ?",
    format: "short",
    expected: ["0.38", "0,38"],
    comparator: "number_equal",
    hint: "Utilise P(B)=P(A)P_A(B)+P(non A)P_nonA(B).",
    explanation: "P(B)=0,6×0,5 + 0,4×0,2 = 0,3 + 0,08 = 0,38.",
    tags: ["probabilites", "totales"],
  },
  {
    kind: "fixed",
    id: "proba_independance_001",
    niveau: "terminale",
    matiere: "maths",
    notionId: "probabilites",
    microId: "independance",
    difficulty: 2,
    theme: "bac",
    text: "Si P(A)=0,4, P(B)=0,5 et P(A ∩ B)=0,2, les événements A et B sont-ils indépendants ?",
    format: "qcm",
    choices: ["Oui", "Non"],
    expected: ["Oui"],
    comparator: "mcq_exact",
    hint: "Compare P(A ∩ B) avec P(A)×P(B).",
    explanation: "P(A)×P(B)=0,4×0,5=0,2. C’est égal à P(A ∩ B), donc A et B sont indépendants.",
    tags: ["probabilites", "independance"],
  },
  {
    kind: "fixed",
    id: "proba_piege_intersection_conditionnelle_001",
    niveau: "terminale",
    matiere: "maths",
    notionId: "probabilites",
    microId: "piege_conditionnelle",
    difficulty: 2,
    theme: "piege",
    text: "P_A(B) désigne...",
    format: "qcm",
    choices: ["P(A ∩ B)", "La probabilité de B sachant A", "P(A) × P(B)", "La probabilité de A sachant B"],
    expected: ["La probabilité de B sachant A"],
    comparator: "mcq_exact",
    hint: "Le A en indice signifie : sachant A.",
    explanation: "P_A(B) signifie la probabilité de B sachant que A est réalisé. Ce n’est pas directement P(A ∩ B).",
    tags: ["probabilites", "piege", "conditionnelle"],
  },
  {
    kind: "fixed",
    id: "proba_piege_addition_multiplication_001",
    niveau: "terminale",
    matiere: "maths",
    notionId: "probabilites",
    microId: "piege_arbre",
    difficulty: 2,
    theme: "piege",
    text: "Dans un arbre de probabilités, pour calculer la probabilité d’un chemin, on doit...",
    format: "qcm",
    choices: ["additionner les probabilités", "multiplier les probabilités", "soustraire les probabilités", "prendre la plus grande probabilité"],
    expected: ["multiplier les probabilités"],
    comparator: "mcq_exact",
    hint: "Sur une même branche complète, on multiplie.",
    explanation: "Dans un arbre, on multiplie le long d’un chemin et on additionne seulement des chemins différents.",
    tags: ["probabilites", "piege", "arbre"],
  },
];