// lib/coach-bac-spe/banks/suites.bank.ts

import type { CoachBacItem } from "../types";

export const suitesBank: CoachBacItem[] = [
  {
    kind: "fixed",
    id: "suites_calcul_termes_001",
    niveau: "terminale",
    matiere: "maths",
    notionId: "suites",
    microId: "calculer_termes",
    difficulty: 1,
    theme: "automatisme",
    text: "On définit u₀ = 2 et uₙ₊₁ = 3uₙ - 1. Calculer u₁.",
    format: "short",
    expected: ["5"],
    comparator: "number_equal",
    hint: "Remplace u₀ par 2 dans la formule.",
    explanation: "u₁ = 3 × u₀ - 1 = 3 × 2 - 1 = 5.",
    tags: ["suites", "calcul", "automatisme"],
  },
  {
    kind: "fixed",
    id: "suites_arithmetique_001",
    niveau: "terminale",
    matiere: "maths",
    notionId: "suites",
    microId: "suite_arithmetique",
    difficulty: 1,
    theme: "automatisme",
    text: "Une suite arithmétique vérifie u₀ = 4 et r = 3. Calculer u₅.",
    format: "short",
    expected: ["19"],
    comparator: "number_equal",
    hint: "Pour une suite arithmétique : uₙ = u₀ + nr.",
    explanation: "u₅ = 4 + 5 × 3 = 19.",
    tags: ["suites", "arithmetique"],
  },
  {
    kind: "fixed",
    id: "suites_geometrique_001",
    niveau: "terminale",
    matiere: "maths",
    notionId: "suites",
    microId: "suite_geometrique",
    difficulty: 1,
    theme: "automatisme",
    text: "Une suite géométrique vérifie u₀ = 2 et q = 3. Calculer u₄.",
    format: "short",
    expected: ["162"],
    comparator: "number_equal",
    hint: "Pour une suite géométrique : uₙ = u₀ × qⁿ.",
    explanation: "u₄ = 2 × 3⁴ = 2 × 81 = 162.",
    tags: ["suites", "geometrique"],
  },
  {
    kind: "fixed",
    id: "suites_variation_001",
    niveau: "terminale",
    matiere: "maths",
    notionId: "suites",
    microId: "variation",
    difficulty: 2,
    theme: "bac",
    text: "Si, pour tout n, uₙ₊₁ - uₙ ≥ 0, que peut-on dire de la suite (uₙ) ?",
    format: "qcm",
    choices: ["Elle est croissante", "Elle est décroissante", "Elle est constante", "On ne peut rien dire"],
    expected: ["Elle est croissante"],
    comparator: "mcq_exact",
    hint: "Compare uₙ₊₁ et uₙ.",
    explanation: "Si uₙ₊₁ - uₙ ≥ 0, alors uₙ₊₁ ≥ uₙ. La suite est donc croissante.",
    tags: ["suites", "variation"],
  },
  {
    kind: "fixed",
    id: "suites_piege_u0_u1_001",
    niveau: "terminale",
    matiere: "maths",
    notionId: "suites",
    microId: "piege_indices",
    difficulty: 2,
    theme: "piege",
    text: "Une suite arithmétique vérifie u₀ = 10 et r = 2. Quelle est la valeur de u₁₀ ?",
    format: "qcm",
    choices: ["28", "30", "20", "32"],
    expected: ["30"],
    comparator: "mcq_exact",
    hint: "Attention : on part de u₀, donc u₁₀ = u₀ + 10r.",
    explanation: "u₁₀ = 10 + 10 × 2 = 30. Le piège est de calculer seulement 9 écarts.",
    tags: ["suites", "piege", "u0", "u1"],
  },
  {
    kind: "fixed",
    id: "suites_piege_arith_geo_001",
    niveau: "terminale",
    matiere: "maths",
    notionId: "suites",
    microId: "piege_arithmetique_geometrique",
    difficulty: 2,
    theme: "piege",
    text: "La suite 3 ; 6 ; 12 ; 24 semble être...",
    format: "qcm",
    choices: ["arithmétique", "géométrique", "constante", "ni arithmétique ni géométrique"],
    expected: ["géométrique"],
    comparator: "mcq_exact",
    hint: "Regarde si on ajoute toujours le même nombre ou si on multiplie toujours par le même nombre.",
    explanation: "On multiplie chaque terme par 2. La suite est donc géométrique de raison 2.",
    tags: ["suites", "piege", "arithmetique", "geometrique"],
  },
  {
    kind: "fixed",
    id: "suites_limite_simple_001",
    niveau: "terminale",
    matiere: "maths",
    notionId: "suites",
    microId: "limite_simple",
    difficulty: 2,
    theme: "bac",
    text: "Quelle est la limite de la suite uₙ = 3 + 1/n quand n tend vers +∞ ?",
    format: "short",
    expected: ["3"],
    comparator: "number_equal",
    hint: "Quand n devient très grand, 1/n tend vers 0.",
    explanation: "Comme 1/n tend vers 0, uₙ = 3 + 1/n tend vers 3.",
    tags: ["suites", "limite"],
  },
];