// lib/coach-bac-spe/banks/variables-aleatoires.bank.ts

import type { CoachBacItem } from "../types";

export const variablesAleatoiresBank: CoachBacItem[] = [
  {
    kind: "fixed",
    id: "va_loi_001",
    niveau: "terminale",
    matiere: "maths",
    notionId: "variables_aleatoires",
    microId: "loi",
    difficulty: 1,
    theme: "automatisme",
    text: "Une variable aléatoire X prend les valeurs 0 et 10 avec probabilités 0,7 et 0,3. La somme des probabilités vaut...",
    format: "short",
    expected: ["1"],
    comparator: "number_equal",
    hint: "Dans une loi de probabilité, la somme des probabilités vaut 1.",
    explanation: "0,7 + 0,3 = 1.",
    tags: ["variables_aleatoires", "loi"],
  },
  {
    kind: "fixed",
    id: "va_esperance_001",
    niveau: "terminale",
    matiere: "maths",
    notionId: "variables_aleatoires",
    microId: "esperance",
    difficulty: 2,
    theme: "bac",
    text: "X vaut 0 avec probabilité 0,5 et 10 avec probabilité 0,5. Calculer E(X).",
    format: "short",
    expected: ["5"],
    comparator: "number_equal",
    hint: "E(X)=somme des valeurs × probabilités.",
    explanation: "E(X)=0×0,5 + 10×0,5 = 5.",
    tags: ["variables_aleatoires", "esperance"],
  },
  {
    kind: "fixed",
    id: "va_variance_001",
    niveau: "terminale",
    matiere: "maths",
    notionId: "variables_aleatoires",
    microId: "variance",
    difficulty: 3,
    theme: "bac",
    text: "Si E(X)=5 et E(X²)=30, alors V(X)=...",
    format: "short",
    expected: ["5"],
    comparator: "number_equal",
    hint: "V(X)=E(X²)-[E(X)]².",
    explanation: "V(X)=30-5²=30-25=5.",
    tags: ["variables_aleatoires", "variance"],
  },
  {
    kind: "fixed",
    id: "va_ecart_type_001",
    niveau: "terminale",
    matiere: "maths",
    notionId: "variables_aleatoires",
    microId: "ecart_type",
    difficulty: 2,
    theme: "bac",
    text: "Si V(X)=9, alors l’écart-type σ(X) vaut...",
    format: "short",
    expected: ["3"],
    comparator: "number_equal",
    hint: "L’écart-type est la racine carrée de la variance.",
    explanation: "σ(X)=√9=3.",
    tags: ["variables_aleatoires", "ecart_type"],
  },
  {
    kind: "fixed",
    id: "va_interpretation_001",
    niveau: "terminale",
    matiere: "maths",
    notionId: "variables_aleatoires",
    microId: "interpretation",
    difficulty: 2,
    theme: "bac",
    text: "L’espérance d’un gain représente...",
    format: "qcm",
    choices: ["le gain certain", "le gain moyen à long terme", "le plus grand gain possible", "la probabilité de gagner"],
    expected: ["le gain moyen à long terme"],
    comparator: "mcq_exact",
    hint: "C’est une moyenne théorique.",
    explanation: "L’espérance représente le gain moyen si l’expérience est répétée un très grand nombre de fois.",
    tags: ["variables_aleatoires", "interpretation"],
  },
  {
    kind: "fixed",
    id: "va_piege_esperance_gain_001",
    niveau: "terminale",
    matiere: "maths",
    notionId: "variables_aleatoires",
    microId: "piege_esperance",
    difficulty: 2,
    theme: "piege",
    text: "Si l’espérance d’un jeu est négative, alors...",
    format: "qcm",
    choices: ["le joueur gagne toujours", "le jeu est favorable au joueur", "le jeu est défavorable au joueur à long terme", "le jeu est impossible"],
    expected: ["le jeu est défavorable au joueur à long terme"],
    comparator: "mcq_exact",
    hint: "Une espérance négative signifie une perte moyenne.",
    explanation: "Si l’espérance est négative, le joueur perd en moyenne à long terme.",
    tags: ["variables_aleatoires", "piege", "esperance"],
  },
];