import type { MicroSkillSource } from "@/lib/tutor-v4/knowledge/buildKnowledge";

export const microSkills: MicroSkillSource[] = [
  {
    id: "adulte_calcul_mental_total",
    label: "Calculer un total de courses",
    notionId: "calcul_mental_utile",
    prerequis: [],
  },
  {
    id: "adulte_calcul_difference",
    label: "Calculer un ecart ou une monnaie rendue",
    notionId: "calcul_mental_utile",
    prerequis: ["adulte_calcul_mental_total"],
  },
  {
    id: "adulte_calcul_estimer",
    label: "Estimer rapidement un montant",
    notionId: "calcul_mental_utile",
    prerequis: ["adulte_calcul_mental_total"],
  },
  {
    id: "adulte_budget_reste",
    label: "Calculer ce qu'il reste dans un budget",
    notionId: "argent_budget",
    prerequis: ["adulte_calcul_difference"],
  },
  {
    id: "adulte_budget_plusieurs_depenses",
    label: "Suivre plusieurs depenses",
    notionId: "argent_budget",
    prerequis: ["adulte_budget_reste"],
  },
  {
    id: "adulte_prix_unitaire",
    label: "Trouver un prix au kilo ou a l'unite",
    notionId: "prix_comparer",
    prerequis: ["adulte_calcul_mental_total"],
  },
  {
    id: "adulte_comparer_offres",
    label: "Choisir l'offre la plus avantageuse",
    notionId: "prix_comparer",
    prerequis: ["adulte_prix_unitaire"],
  },
  {
    id: "adulte_pourcentage_10",
    label: "Calculer 10 %",
    notionId: "pourcentages_quotidien",
    prerequis: ["adulte_calcul_mental_total"],
  },
  {
    id: "adulte_pourcentage_20_25_50",
    label: "Calculer 20 %, 25 % et 50 %",
    notionId: "pourcentages_quotidien",
    prerequis: ["adulte_pourcentage_10"],
  },
  {
    id: "adulte_remise",
    label: "Calculer une remise",
    notionId: "pourcentages_quotidien",
    prerequis: ["adulte_pourcentage_10"],
  },
  {
    id: "adulte_prix_apres_remise",
    label: "Trouver le prix apres une remise",
    notionId: "pourcentages_quotidien",
    prerequis: ["adulte_remise"],
  },
  {
    id: "adulte_pourcentage_augmentation",
    label: "Comprendre une hausse ou une baisse",
    notionId: "pourcentages_quotidien",
    prerequis: ["adulte_pourcentage_10"],
  },
  {
    id: "adulte_recette",
    label: "Adapter une recette",
    notionId: "proportionnalite_pratique",
    prerequis: ["adulte_calcul_mental_total"],
  },
  {
    id: "adulte_dose_quantite",
    label: "Doser une quantite pour plus ou moins de personnes",
    notionId: "proportionnalite_pratique",
    prerequis: ["adulte_recette"],
  },
  {
    id: "adulte_fraction_part",
    label: "Utiliser moitie, quart, tiers",
    notionId: "fractions_ratios",
    prerequis: ["adulte_calcul_mental_total"],
  },
  {
    id: "adulte_partage_montant",
    label: "Partager un montant ou une quantite",
    notionId: "fractions_ratios",
    prerequis: ["adulte_fraction_part"],
  },
  {
    id: "adulte_conversion_mesure",
    label: "Convertir litres, centilitres, grammes",
    notionId: "mesures_conversions",
    prerequis: ["adulte_calcul_mental_total"],
  },
  {
    id: "adulte_conversion_distance",
    label: "Convertir metres et kilometres",
    notionId: "mesures_conversions",
    prerequis: ["adulte_conversion_mesure"],
  },
  {
    id: "adulte_horaire_duree",
    label: "Calculer une duree ou une heure d'arrivee",
    notionId: "durees_trajets",
    prerequis: ["adulte_calcul_mental_total"],
  },
  {
    id: "adulte_horaire_attente",
    label: "Calculer un temps d'attente",
    notionId: "durees_trajets",
    prerequis: ["adulte_horaire_duree"],
  },
  {
    id: "adulte_tableau_lire",
    label: "Lire une valeur dans un tableau",
    notionId: "donnees_tableaux",
    prerequis: ["adulte_calcul_mental_total"],
  },
  {
    id: "adulte_tableau_comparer",
    label: "Comparer des donnees dans un tableau",
    notionId: "donnees_tableaux",
    prerequis: ["adulte_tableau_lire"],
  },
  {
    id: "adulte_moyenne",
    label: "Calculer une moyenne simple",
    notionId: "statistiques_simples",
    prerequis: ["adulte_tableau_lire"],
  },
  {
    id: "adulte_stat_total",
    label: "Calculer un total a partir de donnees",
    notionId: "statistiques_simples",
    prerequis: ["adulte_tableau_lire"],
  },
];
