// « Cartes défis · Vers le CM2 » — révision CM1 → entrée en CM2 (~9-10 ans).
// Conseil à 7 rôles, l'élève tranche : jeu avant tout, jamais moralisateur.
// Mélange équilibré (on a corrigé un excès de nutrition) : maths/français/anglais/
// sciences en cœur, 🌋 La Réunion (fierté péi), et sport + un peu de nutrition fun
// (les bonnes habitudes anti-diabète 974 se prennent tôt, mais sans en faire une leçon).

import type { CarteDefi } from "@/components/cartes/types";

export const CARTES: CarteDefi[] = [
  { ref: "CM2·01", questions: [ {matiere:"maths",q:"Combien font 7 × 8 ?",r:"56"}, {matiere:"francais",q:"Le pluriel de « cheval » ?",r:"chevaux"}, {matiere:"anglais",q:"« red » en français ?",r:"rouge"}, {matiere:"sciences",q:"Combien de poumons a-t-on ?",r:"2"} ], bouge: "10 sauts en étoile !" },
  { ref: "CM2·02", questions: [ {matiere:"maths",q:"La moitié de 50 ?",r:"25"}, {matiere:"francais",q:"« je mange » : quel temps ?",r:"le présent"}, {matiere:"reunion",q:"Le volcan de La Réunion ?",r:"le Piton de la Fournaise"}, {matiere:"sport",q:"Avant de courir, on fait quoi ?",r:"on s'échauffe"} ], bouge: "Cours sur place 15 secondes." },
  { ref: "CM2·03", questions: [ {matiere:"maths",q:"Périmètre d'un carré de côté 5 cm ?",r:"20 cm"}, {matiere:"sciences",q:"L'eau bout à combien de degrés ?",r:"100 °C"}, {matiere:"geo",q:"Combien y a-t-il de continents ?",r:"6 (ou 7)"}, {matiere:"nutrition",q:"L'eau ou le soda pour la soif ?",r:"l'eau"} ], bouge: "Bois un verre d'eau maintenant." },
  { ref: "CM2·04", questions: [ {matiere:"maths",q:"Combien font 9 × 6 ?",r:"54"}, {matiere:"francais",q:"« a » ou « à » : « Il va ___ l'école » ?",r:"à"}, {matiere:"anglais",q:"« dog » en français ?",r:"chien"}, {matiere:"histoire",q:"Qui construisait des pyramides ?",r:"les Égyptiens"} ], bouge: "Fais la statue 10 secondes." },
  { ref: "CM2·05", questions: [ {matiere:"maths",q:"Le double de 12 ?",r:"24"}, {matiere:"sport",q:"Pourquoi bien dormir avant le sport ?",r:"pour avoir de l'énergie"}, {matiere:"nutrition",q:"Un fruit sucré et péi ?",r:"le letchi"}, {matiere:"francais",q:"Contraire de « grand » ?",r:"petit"} ], bouge: "Étire tes bras vers le ciel." },
  { ref: "CM2·06", questions: [ {matiere:"maths",q:"38 + 47 = ?",r:"85"}, {matiere:"francais",q:"Nature du mot « rapide » ?",r:"un adjectif"}, {matiere:"sciences",q:"Une plante boit par quoi ?",r:"ses racines"}, {matiere:"geo",q:"La capitale de la France ?",r:"Paris"} ], bouge: "Touche tes orteils 5 fois." },
  { ref: "CM2·07", questions: [ {matiere:"maths",q:"Combien font 6 × 7 ?",r:"42"}, {matiere:"anglais",q:"« blue » en français ?",r:"bleu"}, {matiere:"sport",q:"Au foot, combien de joueurs par équipe ?",r:"11"}, {matiere:"nutrition",q:"Bon pour les os, ça se boit ?",r:"le lait"} ], bouge: "10 flexions des genoux." },
  { ref: "CM2·08", questions: [ {matiere:"maths",q:"1/2 de 20 ?",r:"10"}, {matiere:"francais",q:"« il est » : verbe et personne ?",r:"être, 3e du singulier"}, {matiere:"reunion",q:"« Koman i lé ? » veut dire ?",r:"Comment ça va ?"}, {matiere:"histoire",q:"Avec quoi écrivaient les Romains ?",r:"un stylet sur des tablettes"} ], bouge: "Fais 8 pas de géant." },
  { ref: "CM2·09", questions: [ {matiere:"maths",q:"100 − 36 = ?",r:"64"}, {matiere:"sciences",q:"Combien de pattes a une araignée ?",r:"8"}, {matiere:"geo",q:"Le plus grand océan ?",r:"le Pacifique"}, {matiere:"nutrition",q:"Trop de sucre longtemps, ça donne quelle maladie ?",r:"le diabète"} ], bouge: "Marche comme une araignée 5 pas." },
  { ref: "CM2·10", questions: [ {matiere:"maths",q:"Combien font 4 × 9 ?",r:"36"}, {matiere:"francais",q:"Le féminin de « acteur » ?",r:"actrice"}, {matiere:"anglais",q:"« cat » en français ?",r:"chat"}, {matiere:"geo",q:"La France est sur quel continent ?",r:"l'Europe"} ], bouge: "Saute 8 fois sur un pied." },
  { ref: "CM2·11", questions: [ {matiere:"maths",q:"3 h = combien de minutes ?",r:"180 min"}, {matiere:"reunion",q:"La Réunion est dans quel océan ?",r:"l'océan Indien"}, {matiere:"sport",q:"Pendant l'effort, il faut penser à ?",r:"s'hydrater"}, {matiere:"nutrition",q:"5 par jour, ce sont les ?",r:"fruits et légumes"} ], bouge: "Respire à fond 3 fois." },
  { ref: "CM2·12", questions: [ {matiere:"maths",q:"Combien font 8 × 8 ?",r:"64"}, {matiere:"francais",q:"Synonyme de « content » ?",r:"heureux"}, {matiere:"sciences",q:"Le sang est poussé par quel organe ?",r:"le cœur"}, {matiere:"histoire",q:"Les Gaulois vivaient dans quel pays ?",r:"la Gaule (la France)"} ], bouge: "Pose ta main sur ton cœur, sens-le battre." },
  { ref: "CM2·13", questions: [ {matiere:"maths",q:"2 km = combien de mètres ?",r:"2000 m"}, {matiere:"anglais",q:"« three » en français ?",r:"trois"}, {matiere:"geo",q:"L'océan à l'ouest de la France ?",r:"l'Atlantique"}, {matiere:"francais",q:"Le pluriel de « journal » ?",r:"journaux"} ], bouge: "Fais 3 grands pas en avant." },
  { ref: "CM2·14", questions: [ {matiere:"maths",q:"Aire d'un rectangle 4 cm × 3 cm ?",r:"12 cm²"}, {matiere:"francais",q:"« nous chantons » : quel groupe de verbe ?",r:"le 1er groupe"}, {matiere:"reunion",q:"« Nou la fé » veut dire ?",r:"On l'a fait !"}, {matiere:"nutrition",q:"Le meilleur en-cas : chips ou banane ?",r:"la banane"} ], bouge: "Crie « Nou la fé ! » en levant les bras." },
  { ref: "CM2·15", questions: [ {matiere:"maths",q:"Combien font 7 × 7 ?",r:"49"}, {matiere:"sciences",q:"La planète où on vit ?",r:"la Terre"}, {matiere:"sport",q:"Au basket, on met le ballon dans le ?",r:"panier"}, {matiere:"nutrition",q:"Combien de repas par jour, à peu près ?",r:"3 (+ un goûter)"} ], bouge: "Fais semblant de tirer au panier 5 fois." },
  { ref: "CM2·16", questions: [ {matiere:"maths",q:"45 ÷ 5 = ?",r:"9"}, {matiere:"francais",q:"Le contraire de « ouvrir » ?",r:"fermer"}, {matiere:"anglais",q:"« yellow » en français ?",r:"jaune"}, {matiere:"reunion",q:"Combien de cirques a La Réunion ?",r:"3 (Cilaos, Mafate, Salazie)"} ], bouge: "Ouvre et ferme les poings 10 fois." },
  { ref: "CM2·17", questions: [ {matiere:"maths",q:"Combien font 5 × 12 ?",r:"60"}, {matiere:"sport",q:"Au rugby, on marque un ?",r:"essai"}, {matiere:"geo",q:"Le plus grand désert chaud ?",r:"le Sahara"}, {matiere:"sciences",q:"Combien de dents de lait environ ?",r:"20"} ], bouge: "Cours vers un mur et touche-le." },
  { ref: "CM2·18", questions: [ {matiere:"maths",q:"1/4 de 20 ?",r:"5"}, {matiere:"francais",q:"Nature du mot « courir » ?",r:"un verbe"}, {matiere:"sciences",q:"L'air qu'on respire pour vivre ?",r:"l'oxygène"}, {matiere:"reunion",q:"Le plat créole avec du riz et des grains ?",r:"le cari"} ], bouge: "Respire par le nez, souffle par la bouche." },
  { ref: "CM2·19", questions: [ {matiere:"maths",q:"Combien font 9 × 9 ?",r:"81"}, {matiere:"anglais",q:"« green » en français ?",r:"vert"}, {matiere:"sport",q:"Le sport où on nage ?",r:"la natation"}, {matiere:"nutrition",q:"Après le sport, on boit surtout ?",r:"de l'eau"} ], bouge: "Imite la brasse 10 mouvements." },
  { ref: "CM2·20", questions: [ {matiere:"maths",q:"Combien de côtés a un triangle ?",r:"3"}, {matiere:"francais",q:"« a » ou « à » : « Elle ___ un chien » ?",r:"a"}, {matiere:"histoire",q:"Le chef gaulois célèbre ?",r:"Vercingétorix"}, {matiere:"sport",q:"Combien de temps dormir vers 10 ans ?",r:"environ 10 heures"} ], bouge: "Dessine un triangle en l'air avec le doigt." },
  { ref: "CM2·21", questions: [ {matiere:"maths",q:"1000 g = combien de kg ?",r:"1 kg"}, {matiere:"sciences",q:"Le Soleil est une étoile ou une planète ?",r:"une étoile"}, {matiere:"reunion",q:"Le point culminant de l'île ?",r:"le Piton des Neiges"}, {matiere:"nutrition",q:"Un légume péi vert et long ?",r:"le brède (ou haricot)"} ], bouge: "Grimpe comme si tu montais le Piton." },
  { ref: "CM2·22", questions: [ {matiere:"maths",q:"Combien font 6 × 6 ?",r:"36"}, {matiere:"francais",q:"Le pluriel de « bijou » ?",r:"bijoux"}, {matiere:"anglais",q:"« seven » en français ?",r:"sept"}, {matiere:"sport",q:"Au tennis, on frappe avec une ?",r:"raquette"} ], bouge: "Fais 6 revers imaginaires." },
  { ref: "CM2·23", questions: [ {matiere:"maths",q:"Combien de minutes dans une demi-heure ?",r:"30 min"}, {matiere:"geo",q:"L'océan gelé au nord ?",r:"l'océan Arctique"}, {matiere:"sport",q:"Le vélo de course s'appelle le ?",r:"cyclisme"}, {matiere:"nutrition",q:"Vrai ou faux : sauter le petit-déj aide à apprendre.",r:"faux"} ], bouge: "Pédale en l'air, allongé ou assis, 10 fois." },
  { ref: "CM2·24", questions: [ {matiere:"maths",q:"Combien font 3 × 11 ?",r:"33"}, {matiere:"francais",q:"Synonyme de « rapide » ?",r:"vite / véloce"}, {matiere:"sciences",q:"L'eau gèle à combien de degrés ?",r:"0 °C"}, {matiere:"reunion",q:"L'oiseau blanc symbole de l'île ?",r:"le paille-en-queue"} ], bouge: "Écarte les bras comme des ailes 5 secondes." },
  { ref: "CM2·25", questions: [ {matiere:"maths",q:"Combien font 8 × 4 ?",r:"32"}, {matiere:"anglais",q:"« white » en français ?",r:"blanc"}, {matiere:"sport",q:"Combien de joueurs au basket par équipe ?",r:"5"}, {matiere:"histoire",q:"Qui a inventé l'écriture il y a très longtemps ?",r:"les Sumériens / Égyptiens"} ], bouge: "Fais 5 pas chassés sur le côté." },
  { ref: "CM2·26", questions: [ {matiere:"francais",q:"Le féminin de « lecteur » ?",r:"lectrice"}, {matiere:"sciences",q:"Combien de dents de lait environ ?",r:"20"}, {matiere:"reunion",q:"On dit bonjour en créole : « ___ »",r:"Bonzour"}, {matiere:"nutrition",q:"Boisson sans sucre pour tous les jours ?",r:"l'eau"} ], bouge: "Souris et dis « Bonzour ! »" },
  { ref: "CM2·27", questions: [ {matiere:"maths",q:"Combien font 12 × 2 ?",r:"24"}, {matiere:"francais",q:"Le pluriel de « nez » ?",r:"nez (invariable)"}, {matiere:"geo",q:"Le fleuve qui passe à Paris ?",r:"la Seine"}, {matiere:"sport",q:"Au hand, on marque un ?",r:"but"} ], bouge: "Lance une balle imaginaire 5 fois." },
  { ref: "CM2·28", questions: [ {matiere:"sciences",q:"Un animal qui pond des œufs, ex. ?",r:"la poule"}, {matiere:"anglais",q:"« ten » en français ?",r:"dix"}, {matiere:"sport",q:"Étirer ses muscles, ça s'appelle ?",r:"s'étirer / stretching"}, {matiere:"reunion",q:"La danse et musique péi classée UNESCO ?",r:"le maloya"} ], bouge: "Étire ton cou doucement à droite et à gauche." },
  { ref: "CM2·29", questions: [ {matiere:"maths",q:"Combien un carré a-t-il d'axes de symétrie ?",r:"4"}, {matiere:"francais",q:"« vous parlez » : quel groupe ?",r:"le 1er groupe"}, {matiere:"reunion",q:"Un fruit péi juteux de l'été austral ?",r:"la mangue (ou le letchi)"}, {matiere:"sciences",q:"L'organe qui pense ?",r:"le cerveau"} ], bouge: "Plie ta feuille en deux : c'est la symétrie !" },
  { ref: "CM2·30", questions: [ {matiere:"maths",q:"Combien font 7 × 9 ?",r:"63"}, {matiere:"sport",q:"Avant l'effort, échauffement ou étirement ?",r:"échauffement"}, {matiere:"histoire",q:"Les hommes de la Préhistoire vivaient dans des ?",r:"grottes"}, {matiere:"nutrition",q:"Le matin, un bon petit-déjeuner donne de l' ?",r:"énergie"} ], bouge: "Fais 7 pas de course sur place, puis souffle." },
];
